### ISSUE TITLE
[Core/Taxi] Incorrect behavior at path end

### ISSUE THREAD

**Issue by Pitcrawler** [TrinityCore/TrinityCore#10051]
I stumbled over this issue when working on a quest. http://www.wowhead.com/spell=46814 is related. 
When the flight is performed and the player reaches the last node from TaxiPathNode.dbc the flight ends and the player falls to the ground. Especially on this path the above mentioned node and the endnode 237 in TaxiNodes.dbc for this path have quite different coordinates which makes the problem quite obvious.
Instead of falling to the ground the player is supposed to teleport to the coordinates of the endnode. 

You can see this here at about 4:33 https://www.youtube.com/watch?v=XHi9Z15QE6Q.
Keep an eye on the minimap and notice how the position changes at the moment the drake lands.

hash: d163c58258160b65a2d785ef552653fc2c8f5eb1
##

**Comment by StormBytePP** [comment]
@Shauren can you look at this? It's important for 6.x work, as in 6.x it's even worse. Also look at related #15490

**Comment by Daribon** [comment]
Flight paths on every server currently uses taxinode.dbc to check if you can use a flight path in that area, then once you are onboard a flight path it will use taxipathnode.dbc until the end.
Which is incorrect, if a emulator only uses taxipathnode.dbc you will end up in the wrong position in the end, which is usually seen as you falling down to the ground once flight path is finished.

Videos from vanilla displaying this:
https://www.youtube.com/watch?v=0Rx3xCa51IU
https://www.youtube.com/watch?v=jo-cfBB4BY8
This still exists on retail, so it's very easy to test.


Expected behaviour:
What is supposed to happen after you reach last id of a pathid at your final destination is that the
server should read from taxinode.dbc and teleport you to the location stated inside of the .dbc.
So if you take a flight from Westfall to Stormwind, you should end up at the position .worldport 0 -8840.56 489.7 109.61 after teleportation, which is stated by taxinode.dbc under the name Stormwind, Elwynn".

Steps To Reproduce: Take flightpath from any place to Stormwind, notice that you spawn on different location than where you spawned on retail when flight is over.

**Comment by Aokromes** [comment]
(6a0a800
