### ISSUE TITLE
{achievement}Champion of the Horde Achive

### ISSUE THREAD

**Issue by BlackVortex** [TrinityCore/TrinityCore#10264]
hello everyone,
the achivment champion of the horde that you are getting from achiving all the achivments at the argent cursade champions is in bug you can achive only one title of each main horde city for exemaple me -troll got the achivment of the senjin,i already got the ambassador titel so it means i am exalted with all main horde cities i earmed it to check if the bug is that you need to be exalted with each city before you even get their quest but it aint this the cues for it.
i have been checked and been told that the champion of the allys is working, ihave noticed another bug that migth be the cues for it after finishing one rep quest and gaining the first champion achive you can take all their quest at once but it aint giving you anything at all.
wowhead link to one of the achiv- http://www.wowhead.com/achievement=2771
zone-icecrown(Argent Tournament)
TBD : 335.51
Hash: 0e4cebf
Linux, SQL.
Thx for help.
##

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by SQLfix** [comment]
CONFIRM

**Comment by SQLfix** [comment]
When Complete Your race Quest And Give Achive Other Race Start Quest Active and Can Get Quest
Example :  [Valiant Of Sen'jin] - Orgrimmar and ... ( For Alliance too )
when u Give Quest to Npc NExt Quest chain is not Active ...

**Comment by dr-j** [comment]
This is more than like caused by the tournament elegibility marker which is set when you turn in first quest of each faction and released once you return the quest to defeat the valiant which under normal circumstances works fine.

But if there should be a crash or restart shortly after turning in quest and before character gets automatically saved at next save interval and suffers roll back then the the quest is still returned but player has auras reset to what they had at last save interval including the eligibility marker.

There are two spells http://www.wowhead.com/spell=63466/horde-tournament-eligibility-release or http://www.wowhead.com/spell=63465/alliance-tournament-eligibility-release which actually gets cast as a reward spell when you return the valiants challenge.

However if for some reason you find yourself unable to take quest for next faction after completing the valiants charge casting the appropriate spell on player will solve the issue and remove the marker enabling player to continue chain.

Don't hear about this happening very often but a crash is usually to blame for this.

**Comment by Killyana** [comment]
I cannot reproduce on  rev. e10d7dd45cfc
If this happen because of a crash a GM must fix the issue.
