### ISSUE TITLE
[Bug/Waypoints]Forsaken Courier and her Forsaken Bodyguards

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#10535]
Bugs:
1. Forsaken Courier and her bodyguards have no waypoints;
If the comment on wowhead are true:
2. Forsaken Courier and her bodyguards don't despawn after they reach Tarren Mill. This is due to them not having any waypoints(see bug Nr.1).
Possible bug:
3. Forsaken Courier and her bodyguards might only spawn when a player accepts the quest "Hints of a New Plague?" and the quest perhaps should even fail if they reach Tarren Mill(see bug Nr.2). 

Forsaken Courier - http://www.wowhead.com/npc=2714
Forsaken Bodyguard - http://www.wowhead.com/npc=2721
Apothecary Jorell - http://www.wowhead.com/npc=2733
Hints of a New Plague? - http://www.wowhead.com/quest=658

Core revision: Trinity Core 659535bac120
Database revision: TDB 335.52
Addons: Anticheat1

**Comment by Rushor** [comment]
```sql
[1] Waypoint: X: -1105.372 Y: -1697.142 Z: 44.55867
[2] Waypoint: X: -1103.872 Y: -1696.892 Z: 44.55867
[3] Waypoint: X: -1101.122 Y: -1696.142 Z: 43.80867
[4] Waypoint: X: -1098.122 Y: -1695.392 Z: 43.05867
[5] Waypoint: X: -1095.122 Y: -1694.642 Z: 42.55867
[6] Waypoint: X: -1092.372 Y: -1693.892 Z: 41.80867
[7] Waypoint: X: -1087.372 Y: -1692.892 Z: 41.05867
[8] Waypoint: X: -1081.622 Y: -1691.392 Z: 40.30867
[9] Waypoint: X: -1074.872 Y: -1689.642 Z: 39.80867
[10] Waypoint: X: -1069.122 Y: -1688.392 Z: 39.05867
```

several points mentioned in sniffs, but never one clear path.
also rechecked on retail -> does not have wps there.

seems to be an "will-no-longer-be-fixed"-issue :(

**Comment by MrSmite** [comment]
> seems to be an "will-no-longer-be-fixed"-issue :(

Well the grid system needs some tweaking anyway or he eventually stops when no players are around.

When the pathing / WP system was built, they should have modified the grid system to always keep grids loaded for NPCs that are on an active path.

**Comment by Kittnz** [comment]
@jackpoz was talking about this in another issue, but i don't know if anyone was working on it.

**Comment by MrSmite** [comment]
I just ran through Southshore yesterday (been that long since I've played) and was reminded of this bug. The path that @Rushor mentioned that's missing from retail may be due to it being 6.x now, I'm not sure how much they changed in the old world.

In 335 though, Trinity seems to have it completely wrong. Besides the missing waypoints, the NPC is supposed to spawn in Arathi Highlands at Go'shek Farm when any player has the quest [Hints of a New Plague](http://www.wowhead.com/?npc=2733) and path to Tarren Mill. It is unclear if it despawns or turns around and paths back to Go'shek Farm.
