### ISSUE TITLE
(Spell)Problem changing seats after using Grab Crate on Salvaged demolisher

### ISSUE THREAD

**Issue by TheAvichay** [TrinityCore/TrinityCore#10566]
Hello every one,
i have noticed a problem in the spell "Grab Crate".
After u use the spell "grab crate" ur unable to go back to the passenger sit.

Salvaged demolisher : http://www.wowhead.com/npc=33109/salvaged-demolisher - ID :33109
Salvaged demolisher mechanic seat :http://www.wowhead.com/npc=33167/salvaged-demolisher-mechanic-seat ID:33167
Liquid pyrite : http://www.wowwiki.com/Liquid_Pyrite - ID:33189

TBD:335.52
Hash: 20a61b6
Linux,SQL.
The for help,
Avichay.
##

**Comment by ariel-** [comment]
Confimed in HEAD@1e3247f00e08900180dcda2bdbc1c55e7e05baf9

Some additional notes:
* Using "Grab Crate" puts passenger out of turret (Liquid pyrite takes the place of the mechanic seat which is wrong because that way passenger can't use "inject pyrite" spell)
* In addition, the mechanic seat/turret is despawned and it behaves like a normal seat afterwards
* After pilot is seated, second player to seat doesn't go directly to mechanic seat, instead goes to another seat which is unselectable.
* Spells on turret/vehicle can damage friendly units (including npcs, players and other vehicles)
* Load into Catapult spell just removes the turret passenger from the vehicle instead of loading him/her on the catapult, which should enable the driver to use Throw Passenger

**Comment by selenir** [comment]
Any news guys?

**Comment by Keader** [comment]
still bugged on c5b0b7e8297c76e7fe39d3c32d802b69f441ab7d

**Comment by sirikfoll** [comment]
With that, the seat and the player will not be dismounted anymore, but not fix the issue yet.

Need a way to despawn the boarded pyrite and some sort of condition that make the spell cast fail if there is already a pyrite on the demolisher.

```diff
diff --git a/src/server/game/Spells/SpellEffects.cpp b/src/server/game/Spells/SpellEffects.cpp
index 69607b4..76a4eff 100644
--- a/src/server/game/Spells/SpellEffects.cpp
+++ b/src/server/game/Spells/SpellEffects.cpp
@@ -3955,7 +3955,7 @@ void Spell::EffectScriptEffect(SpellEffIndex effIndex)
                             {
                                 /// @todo a hack, range = 11, should after some time cast, otherwise too far
                                 m_caster->CastSpell(parent, 62496, true);
-                                unitTarget->CastSpell(parent, m_spellInfo->Effects[EFFECT_0].CalcValue());
+                                unitTarget->CastSpell(seat, m_spellInfo->Effects[EFFECT_0].CalcValue());
                             }
                         }
                     }

**Comment by Bullfface** [comment]
Any news or hack for fix? Changed the seatID to 1 to get into the Salvaged Demolisher Mechanic seat but using the pyrite grab spell still replaces the seat and then despawns it. Current Rev

**Comment by Aokromes** [comment]
#3831
