### ISSUE TITLE
Brewfest zone music isn't playing

### ISSUE THREAD

**Issue by lasershark** [TrinityCore/TrinityCore#10706]
I did an .event start 24 to verify Brewfest is working. Everything spawned ok, but the brewfest zone music sounds do not play when a toon enters the brewfest area.

Confirmed the sound files are present in my client and work by using PlaySoundFile scripts. 

Can someone confirm this issue, or is it just me?

Database: 335.52 with updates to 2013_08_24_00
self compiled 
TrinityCore rev. 58e6503eef92 2013-08-24 15:45:19 +0100 (master branch) (Win32, Release) (worldserver-daemon)
OS platform windows7x64

**Comment by dr-j** [comment]
Well I will post here since is related but there should also be music for Midsummer Fire Festival in capital cities or https://www.youtube.com/watch?v=7CWCYbsX8_4 / https://www.youtube.com/watch?v=QJY89I4MxuI 

Now for both brewfest and Midsummer Fire Festival and other events there are the following objects and since verified build is 12340 these existed in 3.3.5

http://wotlk.openwow.com/object=186221 Brewfest Music Doodad
http://wotlk.openwow.com/object=180335 Darkmoon Faire Music Doodad
http://wotlk.openwow.com/object=186312 L70ETC Music Doodad
http://wotlk.openwow.com/object=188174 Midsummer Music Doodad

**Comment by Killyana** [comment]
Do we have any sniffs to see how this gobs works?

**Comment by Kittnz** [comment]
Well i bet it works the same as the l70etc music

**Comment by Kittnz** [comment]
Not sure why they aren't playing, i was searching in a sniff and the doodad isn't doing much. The l70etc music is played by http://shinworld.altervista.org/Keira2/#/sai/0/23830  - http://www.wowhead.com/npc=23830/dnd-l70etc-fx-controller

**Comment by Demonid** [comment]
I was using this 4 years ago for the Midsummer Music, im pretty sure it's useless for TC but what ever:

https://gist.github.com/Demonid/308fc50887ea0e43e034ca381cb6b357

**Comment by Kittnz** [comment]
I got a working fix for this, i just need some more time to do some adjusting.
Also since 4.x they changed it a bit but got a it working too.

**Comment by Kittnz** [comment]
Adding the other music doodad scripts later.

**Comment by Kittnz** [comment]
Fixed all the music doodad's with 963278459a1d9df5aa3c2e1c8b5f5f112f6a370c & e3560f3f518ee8a76921b4922292805c03871d4a & 19f8acdb616909758391d1c1459fe61196531f3b
