### ISSUE TITLE
[Quest 335a] Replenishing the Healing Crystals

### ISSUE THREAD

**Issue by Ischtaratu** [TrinityCore/TrinityCore#11450]
Rev: d78e69c
Client: 3.3.5a enGB
DB: 335.52 & updates till 12.01.14

NPC: Proenitus (ID 16477) Azuremyst Island

Quest "Urgent Delivery!" (ID 9409) should not Start befor "Replenishing the Healing Crystals (ID 9369)" has finished. The Questtext make no sense if not.

And at Quest "Replenishing the Healing Crystals (ID 9369)" you need to collect 6 Vial of Moth Blood and not 8 ... :)

**Comment by Killyana** [comment]
```sql
UPDATE `quest_template` SET `PrevQuestId`=9279 WHERE `id`=9369;
UPDATE `quest_template` SET `PrevQuestId`=9371 WHERE `id`=9409;
UPDATE `quest_template` SET `NextQuestId`=9409 WHERE `id` IN (9280, 9369);

**Comment by XaveT** [comment]
TrinityCore rev. 3f886025a255 2016-01-22 22:14:28 +0100 (3.3.5 branch) (Unix, Release)

This is happening again as of 2016-01-22.  "Urgent Delivery!" is available and auto-accepted before "Replenishing the Healing Crystals" is complete.

**Comment by Rushor** [comment]
create a new ticket for this pls @XaveT

**Comment by tkrokli** [comment]
TrinityCore rev. cb8faad211f6 2016-01-23 23:43:05 +0100 (3.3.5 branch) (Win64, Release)

The columns `PrevQuestId` and `NextQuestId` got moved to the table `quest_template_addon` after TDB 335.59 or after the fix above was made, so I it might be valid to post it here. One of the lines in the solution above is actually missing and needs to be reapplied to the new table:

Maybe this happens because of the only pre-requisite for "Urgent Delivery!" (ID 9409) is the quest "Botanist Taerix" (ID 9371)? List of these quests in TDB 335.60:
```sql
SELECT `ID`,`PrevQuestID`,`NextQuestID` FROM `quest_template_addon`
WHERE `ID` IN (9279,9280,9369,9371,9409);
```
```
    ID  PrevQuestID  NextQuestID
------  -----------  -----------
  9279            0            0
  9280         9279         9409
  9369            0         9409
  9371            0            0
  9409         9371            0
```
