### ISSUE TITLE
Training dummies start zones class quests

### ISSUE THREAD

**Issue by Demonith88** [TrinityCore/TrinityCore#11865]
Broken quest for mage in start zone for humans 

http://cata.openwow.com/quest=26916

TrinityCore rev. a903c335024d
##

**Comment by Aokromes** [comment]
If the fix is valid plz create a PR for it.

**Comment by Aokromes** [comment]
This fix is still needed on master branch?

**Comment by funjoker** [comment]
Not necessary in master because this quest was removed in 7.0.3

**Comment by BahDumbBugs** [comment]
Just wanted to check on the status of this because I am still experiencing issues with all training dummies in all race start zones (with all classes so far). I am running commit e0fb444. In other words, all my Level 3 quests involving training dummies cannot be completed. Can someone please confirm/deny this issue still exists? I'll open a new ticket if necessary, just don't want to clutter the board.
