### ISSUE TITLE
The Nexus - Chaotic Rift 

### ISSUE THREAD

**Issue by iceyman** [TrinityCore/TrinityCore#11997]
Chaotic Rift can now be targeted  but very hard to find the right spot, u should be able to just click on them like another NPC
http://www.wowwiki.com/Chaotic_Rift
Core - 0c8df80+

addons npcbots and ahbot

TDB 335.53
##

**Comment by Killyana** [comment]
The nps doesn't have a model, he have this aura id: 48019 [Arcaneform]  it change the model but it will not allow the player to select the npc by click, it's a general issue, maybe on retail it's the same thing.

**Comment by tkrokli** [comment]
> The NPC doesn't have a model, it has this aura id: 48019 [Arcaneform](http://www.wowhead.com/spell=48019/arcaneform). It changes the model, but it will not allow the player to select the NPC by click. It's a general issue, maybe on retail it's the same thing.

I agree. Looking at the comment http://www.wowhead.com/npc=26918/chaotic-rift#comments:id=691701: `Um.. Why does the 3D viewer show an Infernal?` and the reply: `I'm guessing that the little effect you see in game is just that; an effect. Most effects, such as torches, small lights, fires, etc all use infernals or imps as their "models". Instead of drawing the actual model, the developers draw the effects, instead. Why they chose an infernal is beyond me though.` (3D view is no longer available.)

I think this is similar to the use of "spell bunnies", since Blizzard may have used infernal NPCs (invisible and not selectable) as models. If you look at other spell bunnies used elsewhere in the game, the infernal or imp seems to be popular with Blizzard as the preferred model. I can only speculate that they have got a penchant for demon-like creatures, since these spells are handled by an invisible model.

Even though I can't document it more than the above information, I presume this is not an issue after all?

**Comment by Rushor** [comment]
```sql
-- Chaotic Rift SAI
SET @ENTRY := 26918;
UPDATE `creature_template` SET `AIName`="SmartAI" , `scriptname` ="" WHERE `entry`= @ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,60,0,100,0,5000,5000,10000,10000,11,47692,0,0,0,0,0,1,0,0,0,0,0,0,0,"Chaotic Rift - On Update - Cast 'Summon Arcane Wraith' with CastFlag: 0 and TriggerFlag: 0 (TargetLimit: 0)"),
(@ENTRY,0,1,2,8,0,100,0,47747,0,0,0,28,47687,0,0,0,0,0,1,0,0,0,0,0,0,0,"Chaotic Rift - On Spellhit 'Charge Rifts' - Remove Aura 'Chaotic Rift Aura'"),
(@ENTRY,0,2,3,61,0,100,0,0,0,0,0,11,47733,0,0,0,0,0,1,0,0,0,0,0,0,0,"Chaotic Rift - On Spellhit - Cast 'Chaotic Rift Aura' with CastFlag: 0 and TriggerFlag: 0 (TargetLimit: 0)"),
(@ENTRY,0,3,0,61,0,100,0,0,0,0,0,22,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Chaotic Rift - On Spellhit - Set Event Phase 1"),
(@ENTRY,0,4,0,60,1,100,0,10000,10000,10000,10000,11,47692,0,0,0,0,0,1,0,0,0,0,0,0,0,"Chaotic Rift - On Update - Cast 'Summon Arcane Wraith' with CastFlag: 0 and TriggerFlag: 0 (TargetLimit: 0) (Phase 1)");

DELETE FROM `creature_template_addon` WHERE `entry` IN (26918, 30522);
INSERT INTO `creature_template_addon` (`entry`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `visibilityDistanceType`, `auras`) VALUES 
(26918, 0, 0, 0, 4097, 0, 0, '48019 47687'),
(30522, 0, 0, 0, 4097, 0, 0, '48019 47687');

UPDATE creature_template SET unit_flags=4|131072, lootid=0, pickpocketloot=0, skinloot=0, mechanic_immune_mask=650854271, flags_extra=0x200000, AIName='SmartAI', ScriptName='' WHERE entry=26918;
UPDATE creature_template SET unit_flags=4|131072, lootid=0, pickpocketloot=0, skinloot=0, mechanic_immune_mask=650854271, flags_extra=0x200000, AIName='', ScriptName='' WHERE entry=30522;
```

**Comment by Aokromes** [comment]
i can target the mob on retail from here:
https://i.imgur.com/yxicGyq.png

**Comment by CraftedRO** [comment]
```sql
-- Add proper auras for Chaotic Rift
UPDATE `creature_template_addon` SET `auras`='48019 47687 47732 63577' WHERE `entry`=26918; -- 26918 (Chaotic Rift) - Arcaneform, Chaotic Rift Aura, Chaotic Rift Summon Aura, Chaotic Rift Aggro Proc
```

**Comment by CraftedRO** [comment]
https://github.com/TrinityCore/TrinityCore/assets/24683355/2d269825-84e2-4b43-b138-daaa96d23668
