### ISSUE TITLE
[3.3.5][Naxxramas] Core/Creature: Kel'thuzad trash mobs - Enrage abilities

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#12037]
Due to the "recent" changes on his script I tested him today and this is what i found on its 10 man mode:
- NPC http://es.wowhead.com/npc=16428 has http://es.wowhead.com/spell=28468 from the beginning of the fight and melee attacks are disabled until Mortal Wound is casted:

![image](https://cloud.githubusercontent.com/assets/4329612/2922419/81a49612-d701-11e3-9b03-3e05d9c9a3ab.png)
![image](https://cloud.githubusercontent.com/assets/4329612/2922421/8a380a2a-d701-11e3-8f02-bb02b58aae0b.png)
- NPC http://es.wowhead.com/npc=16441 gets movement disabled after using http://es.wowhead.com/spell=28470 and wont move again till the end of the encounter

![image](https://cloud.githubusercontent.com/assets/4329612/2922473/8aa9a0f8-d702-11e3-80c2-854b2f1ba96a.png)

Still they can autoattack no matter how far you go from them, as seen in the picture.

rev: 33978774ffc5c47c1e08153e8b0d7b3b037089fb
##

**Comment by Killyana** [comment]
This issue still exists on rev. 5dba91fb0e38

**Comment by tkrokli** [comment]
Because this issue is quite specific about these 2 mobs and their abilities,
- http://www.wowhead.com/npc=16428/unstoppable-abomination
  - http://www.wowhead.com/spell=28468/frenzy
  - http://www.wowhead.com/spell=28467/mortal-wound
- http://www.wowhead.com/npc=16441/guardian-of-icecrown
  - http://www.wowhead.com/spell=28470/blood-tap

... it would be practical with a more detailed issue title to say what makes this different from issue  #16388 (Core/Movement: Unstoppable Abomination movement during the Kel'Thuzad fight).

**Comment by Aokromes** [comment]
Test  #16634

**Comment by Treeston** [comment]
assume closed by #16634
