### ISSUE TITLE
[3.3.5][Core]Quest with area explore seems don't work fine.

### ISSUE THREAD

**Issue by kldxzzhc2** [TrinityCore/TrinityCore#12172]
core: 8d539ee6c0a44f76a1977e9772b1f9c2cd68fb9d
db: up to date
Let me explain via an example.
Just like the quest 9160. This kind of quest ask player do two things:
1.explore/investigate some area [condition 1 for complete]
2.kill some creature                    [condition 2 for complete]

The offical wow works like below:
1.when enter area, complete condition 1
2.when finish the kill, complete condition 2 (at the same time, complete the request)
that's mean condition1 and condition 2 are independence

But the TrinityCore works like below:
1.when enter area, nothing happens (I know there's something happen, I have trace the code : HandleAreaTriggerOpcode calls AreaExploredOrEventHappens, but the game client nothing happens).
2.when finish the kill, condition 1 and condition 2 complete at the same time (at the same time, complete the request)
It do work, but I think there is small problem in the code. How can I fix it?

**Comment by danlapps** [comment]
Is this still a valid issue ?

**Comment by tkrokli** [comment]
> Is this still a valid issue ?

Good question. I will do a quick run to check and report back with status. Checklist:
1. Alliance: human char to take quest 62: The Fargodeep Mine (lvl 4-7 quest)
2. Horde: lvl 11 belf char to Ghostlands and take quest 9160, "Investigate An'daroth (2 objectives)
3. Horde: lvl 25, Ashenvale, quest 25: Stonetalon Standstill / Mystral Lake (2 objectives)
(Did I miss any relevant points above?)

**Comment by tkrokli** [comment]
TrinityCore rev. ea78bce592b6 2015-03-19 19:07:32 -0300 (3.3.5 branch) (Win64, Release)

1. Quest 62, The Fargodeep Mine: works as intended, no issues. The same goes for the followup quest, The Jasperlode Mine. No issues at all, since there is only 1 objective, completed without killing NPCs.

2. Quest 9160 "Investigate An'daroth : discovery announced after killing 12 NPCs, like @dr-j explained.
3. Quest 25 Stonetalon Standstill : completed after killing 12 NPCs and discovery triggered, like @dr-j explained. Discovery "objective complete" is not announced until you kill the last of the 12 NPCs.

Going by what dr-j has said, the bug behaves like this:
When a quest contains 2 objectives - 1) kill X number of NPCs, 2) discover point Y - completing the discovery objective will not be announced before all the required NPC kills have been done.
Going to test the Plains of Nasam too later, but I think I can predict the outcome.

I will also test untaught's suggested fix later to see if that makes any difference.
