### ISSUE TITLE
[Bug]Recruitment Letter

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12286]
Bug:
"Recruitment Letter" and "Signed Recruitment Letter" seem to have some typos.

```sql
Recruitment Letter should read:
'Horde Conscription Registration$b$bThis person has demonstrated incredible feats of strength and skill in the name of the Horde. They should immediately be assigned to work in the Crossroads.$b$bRespectfully yours:$b- Takrin Pathseeker'

Signed Recruitment Letter should probably read:
'Horde Conscription Registration$b$bThis person has demonstrated incredible feats of strength and skill in the name of the Horde. They should immediately be assigned to work in the Crossroads.$b$bRespectfully yours:$b- Takrin Pathseeker$b$bLooks good to me.$b- Kargal Battlescar'
```

Core revision: 0f0cea104dcceb029fc74e12f60f913e55d267fc
Database version: TDB 335.53
Addons: Anticheat1

**Comment by tkrokli** [comment]
The logic behind the letter(s) is a bit different than you think, @Crysicle. If you look at the item description text for the [[Recruitment Letter]](http://wow.gamepedia.com/Recruitment_Letter), you will notice that it says: "An unsigned recruitment letter."

![Recruitment Letter](http://i.imgur.com/C4B7RNf.png "Recruitment Letter")

This suggests that initially, the Recruitment Letter should not be signed by any of the NPCs, but the letter is forwarded from [Kargal Battlescar](http://wow.gamepedia.com/Kargal_Battlescar) to [Takrin Pathseeker](http://wow.gamepedia.com/Takrin_Pathseeker) who is looking for a new recruit. Takrin Pathseeker is not the authorizing part in the letter, he only gives his approval by saying "Looks good to me." because he is lower in command than Kargal Battlescar, who is the authorizing part.

Because of this, Kargal Battlescar's signature belongs under the text "Respectfully yours:", while Takrin Pathseeker's signature belongs with "Looks good to me." Remember, this letter is to be delivered to a higher officer above Kargal Battlescar's level, so Kargal should authorize the final signed letter
([[Signed Recruitment Letter]](http://wow.gamepedia.com/Signed_Recruitment_Letter)) with his signature.

**Comment by Killyana** [comment]
Also it's the same in all languages.
