### ISSUE TITLE
[335] Evading Home NPCs do not take their pets with them

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#12596]
**Core:** https://github.com/TrinityCore/TrinityCore/commit/c28345e279f31af2fa32df2411325ccfabe06fc8
**DB:** TDB_full_335.52 + updates

**Bug:**

When an NPC with a pet evades home, the pet continues to attack

**Details:**

It seems that the NPC and its pet are not properly "linked" in that when the NPC Owner evades home due to being pulled beyond aggro radius, the pet will continue to attack you

**Notes:**

This could possibly be fixed by reimplementing the proper evade mechanic (#11159) of NPCs not evading when being damaged and treating the pet as an extension of the NPC.
##

**Comment by Sidious78** [comment]
5474ed1 
335.57

I can confirm this. Seems to be a general mob/pet problem. Noticed this first with the murlocs that spawns crab in Westfall.

Watch this video: https://www.youtube.com/watch?v=9XlXS7UrkjI&feature=youtu.be

This mob pet is kited into another zone!

Could this be related to the need-to-relog-because-of-constant-aggro-in-dungeons-problem? :)

**Comment by MrSmite** [comment]
@Sidious78 

There are two possible fixes for this issue:

* When the pet's owner / summoner evades, either send CombatStop() or EnterEvadeMode() to the pet, or simply despawn it

* Put back the evade mechanics that were incorrectly removed as mentioned in my OP.

**Comment by Sidious78** [comment]
I think I would like to emphasize that this bug is general with mob pets, doesn't look pretty at all, and can be potentially somewhat gamebreaking.

Example: I just finished one of the quests at Stromgarde (Arathi Highlands). Unknowingly I pulled one of the voidwalker mob pets there when returning. After returning and to Refuge Point and selling my junk to a vendor, it hunted me down after some time in the refuge!

Had I gone for one of my many coffee-runs, I might have ended up dead! ^^ (No, the refuge guards did not care)

I'm not calling the shots, but I would argue this issue deserves to be prioritized. Kiting mobs across entire continents is somewhat extreme. :-P

**Comment by MrSmite** [comment]
@Sidious78 - I've noticed myself that friendly "guards" quite often do not assist me when I get attacked by any mob. Aside from the issue of the pet hunting you down, it seems like there are many friendly NPCs that have incorrect faction flags which is why they do not assist.

**Comment by Kittnz** [comment]
I guess If Creature has summoned pet && if creature goes into EnterEvadeMode
Do follow or something

**Comment by CraftedRO** [comment]
835e2918319e Seems no longer valid:


https://user-images.githubusercontent.com/24683355/214264187-a71ce32f-36c6-445c-9888-7a38eb219217.mp4

https://user-images.githubusercontent.com/24683355/214263986-633c203f-b9f6-4142-8370-1f871e5752a3.mp4

https://user-images.githubusercontent.com/24683355/214264005-d8120686-7056-41e0-8e37-82d6061e5a11.mp4
