### ISSUE TITLE
Creature walk speed

### ISSUE THREAD

**Issue by malcrom** [TrinityCore/TrinityCore#12706]
After pathing Fen Striders, Marsh Walkers, Darkcrest & Bloodscale sentries in Zangarmarsh I have noticed that thier walk speed is higher than on offi while speeds set from offi.

http://www.wowhead.com/npc=18134
http://www.wowhead.com/npc=18135
http://www.wowhead.com/npc=20079
http://www.wowhead.com/npc=20090
##

**Comment by danlapps** [comment]
Do you still need a sniff of their pathing, or has it just been forgotten ?

**Comment by tkrokli** [comment]
> Do you still need a sniff of their pathing, or has it just been forgotten?

Most likely forgotten because of prioritizing other tasks, even though this issue is labeled "Priority-High".

**Comment by Rushor** [comment]
it affects eben more creatures, imagine some creatures in  stormwind and untercity, dunno if this was fixed meanwhile

**Comment by Killyana** [comment]
I got the same values from sniffs walk speed=1 run and speed= 1.14286;

**Comment by danlapps** [comment]
Is it linked to the core or with the speed_walk and speed_run fields of DB ?

**Comment by chaodhib** [comment]
Reminder: the formula used for the speed of npcs is:
speed[WALKING] = npcs_base_speed[WALKING] * this_npc_speed_rate[WALKING]
(and these values are completely independent to speed, base_speed & speed_rate in RUNNING)

Malcrom's observation means speed[WALKING] is too high. If speed_rate[WALKING] = 1 is taken from a sniff (and therefore unquestionable), this means:

a) not all npcs share the same base speed (maybe pvp guards have their own base_speed) and the formula used should be adapted accordingly.
or
b) npcs_base_speed is wrong.

**Comment by Killyana** [comment]
The problem in this case doesn't come from the speed used on the DB.
When any npc walk in a short water (not swimming) its speed will be slowed (must have Ground: Run, Swim: true)
The issue here when an npc have waypoints the speed used will not be slowed by the water.
But if you start a combat with 18134, you can notice the chasing speed is slowed when the npc is on the water during the chase movement. Same with a follow the speed will change according if the npc is on the water or not.
