### ISSUE TITLE
Kodo Roundup Quest

### ISSUE THREAD

**Issue by KaungKhantZaw** [TrinityCore/TrinityCore#12811]
Quest ID : 13892
Core : cde18e19c89e
DB : TDB 335.53

I can't tame kodos with Kodo Kombobular, nothing happened.

**Comment by tkrokli** [comment]
Confirmed, but with deviations in description of target kodo response and order of events.

Base core : https://github.com/TrinityCore/TrinityCore/commit/4adf31ce0ac5e41e80a61c107fd2c8cee64985eb + https://github.com/tkrokli/TrinityCore/commit/073c14eb4e5080f229661278b1be09e2f39179cc
DB : TDB 335.57 + updates => 2015_02_06_13_world_335.sql (4adf31c)
Manual additions:  https://github.com/TrinityCore/TrinityCore/commit/0c9e39f1510c838cb3c84fc7502db9dd00bd4771 + https://github.com/TrinityCore/TrinityCore/commit/03edeeb9d81728ed856d05cace9e264f0d0c37fc + @Rushor's https://github.com/TrinityCore/TrinityCore/issues/14020#issuecomment-72644028 (SQL query inserts)

The Kodo Kombobulator puts the kodo into combat with the player, not always changing the kodo to "Tamed Kodo" (creature_template entry 11627), but making the kodo attack the player instead -- most of the time. So it looks like the Kodo Kombobulator spell is 50% (or less) effective in changing an Aging Kodo or Dying Kodo into a Tamed Kodo. (Could this inefficiency have anything to do with race, class or spec of the player?) Also, because the temporary tamed kodos are in a combat state, they follow the player at melee range, matching the running speed of the player until they reach Scrabblescrew's camp. This is not what is supposed to happen according to the quest, because the kodo should be walking slow enough for the player to lose it **if and when** the character runs too far ahead.

When the player and kodo are close enough to trigger Smeed Scrabblescrew's say text about inspecting the kodo, the kodo drops aggro & Tamed status immediately and heads home at walking speed. This is where the kodo should STOP and stand still (but it doesn't). Even so, at this moment, I was able to activate the Kodo Kombobulator before losing the kodo out of range, making the kodo Tamed again, but the kodo is suddenly in *evade speed mode* (returning home at max speed), but this is where it would have been possible to talk to the kodo (**if it only had been standing still**).

I want to test this theory more, but I don't know which codes I can test to make the kodo stop at Scrabblescrew's Camp (or when Smeed tells me to inspect the kodo). It would be quite interesting to confirm if the kodo could be inspected "in place" and perhaps make this quest completable (but with the need for a double spell cast with the Kodo Kombobulator), just by making the kodo stop. :game_die:

Hmm, this makes me think about my old issue from last year, when @dr-j helped me making the Icepaw Bears attackable, aggressive and attacking in aggro range in #13030 / #13167 => https://github.com/TrinityCore/TrinityCore/commit/d672e78a5b7a98f4b58936a0bd1c948028005dc0 . Should I post some of the creatures' info (.npc info) here in this issue, just to get hold of creature flags and states?

**Comment by tkrokli** [comment]
OK, I have tested a bit more and have found the following useful details:
- Using the command `.npc follow` produces the correct behaviour from the kodo, making the NPC/creature follow your character while not triggering aggro. The creature now keeps a reasonable distance and does not twist and turn as when locked in combat.

- Upon reaching Smeed Scrabblescrew, he correctly says one of his text lines when the player and/or kodo is within range. The downside is that Smeed also at the same time seems to dispel the `.npc follow` command so I need to re-issue it for each animal. I even tested rounding up 5 kodos at once, in the faint hope that 5 of them at once would trigger the quest counter... but alas, no luck. The upside is the following: There is no need at all to cast aggro through the spell from the Kodo Kombobulator. Cast a similar or the same spell/command as `.npc follow` on the NPC, from the player. Whether a flag should be set to allow a player the chance to summon more kodos at once: maybe not.

(I was going to write a third chapter here, but when I spawned "Tamed Kodo" (creature ID 11627), my premiss changed, so I will skip ahead to dealing with that creature.)

![Kodo Roundup](http://wow.zamimg.com/uploads/screenshots/normal/59346.jpg "Smeed Scrabblescrew comments on the gathered tamed kodos")

**I think I am beginning to get close to a solution here**, at least I know what needs to be done, even if I don't know all the tables, spells or items to change yet. First of all, for this quest to work, the following events need to happen:

The player must select one of these 3 **valid** creatures to cast the spell upon:
- NPC ID (Entry) 4700; Aged Kodo - http://www.wowhead.com/npc=4700/aged-kodo
- NPC ID (Entry) 4701; Dying Kodo - http://www.wowhead.com/npc=4701/dying-kodo
- NPC ID (Entry) 4702; Ancient Kodo - http://www.wowhead.com/npc=4702/ancient-kodo

The player should already have the provided Kodo Kombobulator (ID 13892) from quest NPC, but the current spell attached to item13892 is not working as intended. Looking up item 13892 on Wowhead.com, I find it linked to spell 18153, "Kodo Kombobulator", which is 1 of 5 spells with the same name:

1. http://www.wowhead.com/spell=18153/kodo-kombobulator :
Cast Kodo Kombobulator on any Ancient or Aged Kodo to lure the Kodo to follow (one at a time).

2. http://www.wowhead.com/spell=18172/kodo-kombobulator :
The Kodo casts on Player to give player condition for Quest Credit

3. http://www.wowhead.com/spell=18269/kodo-kombobulator :
This is linked to a periodic trigger to alert the kodo to Despawn

4. http://www.wowhead.com/spell=18362/kodo-kombobulator :
This is used to turn the kodo into gossip to give player Quest Credit

5. http://www.wowhead.com/spell=18377/kodo-kombobulator
The Kodo casts on self after being hit by 'kodo Item'

When the spell is cast, the NPC must be despawned and replaced with Entry/NPC ID 11627 (spawned in the same spot). At the same time, the command (or matching spell) `.npc follow` must be cast on entry 11627, optionally **without** command result screen output. (Currently, the spell ID 18153 seems to be broken or at least not working as intended.) The player should now be ready to walk towards Scrabblescrew's Camp. An optional detail here will be setting the max_speed of creature entry 11627, so the player can be able to outrun the Tamed Kodo and lose the controlled animal when out of range.

When reaching Smeed Scrabblescrew, this creature (ID: 11627) behaves correctly. It stops, it has a gossip option and a gossip window, but **no gossip text** (maybe a missing script?). Nothing positive related to the quest happens, only that the creature despawns after a set amount of time (30 secs?)

Since the creature has no gossip text and the supposed script in spell 18362 does not seem to be cast (or if cast, it does not work), we now have an idea about the missing pieces of the puzzle.

To go any further with my investigations here, I need a little feedback on what to do next and which information I should be looking for (and ideally, where). So most kinds of feedback will be appreciated.

**In case you want to test my theory, here is a short how-to for this quest:**
- Level 30+ character, travel/teleport to Desolace / Ghostwalker Post / Scrabblescrew's Camp
- Accept the quest ![Quest](http://wow.zamimg.com/images/wow/icons/tiny/quest_start.gif)[Kodo Roundup](http://www.wowhead.com/quest=5561/kodo-roundup) from Smeed Scrabblescrew
- Move across the "parking lot" to be out of range (50+ yards) from Smeed's detection
- Spawn Tamed Kodo (`.npc add 11627`) and cast `.npc follow` on the Tamed Kodo
- Walk the Tamed Kodo over to Smeed Scrabblescrew, get the say text, talk to Tamed Kodo
- After repeated attempts to "talk" with the kodo (empty gossip), it will despawn (10-20 seconds later)

**Comment by tkrokli** [comment]
OK, so I found the missing gossip text in the database, but that alone does not trigger the quest credit.
Anyway, here is my result from adding the missing gossip text to the tables :
```sql
-- Add the missing link to npc_text in gossip_menu:
DELETE FROM `gossip_menu` WHERE `entry`=11627 AND `text_id`=4449;
INSERT INTO `gossip_menu` (`entry`, `text_id`) VALUES (11627, 4449);
-- Link the npc_text from gossip_menu:
UPDATE `creature_template` SET `gossip_menu_id`=11627 WHERE  `entry`=11627;
```
The wiki pages say that the `creature_template`.`gossip_menu_id` and `gossip_menu`.`entry` should be above 50 000, but 11627 is not in use, so for testing purposes it was easier to use the creature ID.

**Comment by dr-j** [comment]
The correct gossip menu id here is 3650

ServerToClient: SMSG_GOSSIP_MESSAGE (0x0077) Length: 33 ConnIdx: 0 Time: 03/30/2015 18:20:05.953 Number: 21495
GossipGUID: Full: 0x1C14B4002004978000002D0000187281 Creature/0 R1325/S45 Map: 1 Entry: 4702 Low: 1602177
GossipID: 3650
FriendshipFactionID: 0
TextID: 4449
GossipOptions: 0
GossipText: 0

ServerToClient: SMSG_GOSSIP_MESSAGE (0x0077) Length: 32 ConnIdx: 0 Time: 03/30/2015 18:22:47.765 Number: 23119
GossipGUID: Full: 0x1C14B4002004970000002D00001871F4 Creature/0 R1325/S45 Map: 1 Entry: 4700 Low: 1602036
GossipID: 3650
FriendshipFactionID: 0
TextID: 4449
GossipOptions: 0
GossipText: 0

**Comment by tkrokli** [comment]
Thanks. I will correct the GossipID. Thanks a lot for the feedback. :+1: I am still learning these details.
