### ISSUE TITLE
[3.3.5][6.x] Core/Loot/Gameobject: Tempspawned Gameobjects despawn after looting

### ISSUE THREAD

**Issue by kldxzzhc2** [TrinityCore/TrinityCore#12842]
**How it is:**
Any tempspawned chest object which is spawned with a spell from a creature (like http://www.wowhead.com/spell=46310) will despawn if **ONE single** player lootet the object.

**How it should be:**
Any tempspawned chest object which is spawned with a spell from a creature (like http://www.wowhead.com/spell=46310) should **ONLY** despawn **if the timer from the spelldescription expires** (like in the case of spell 46310 it should despawn after 1 minute)
During this time every player should be able to loot that gameobject multiple times even without a group.

Examples for quests/gos:

[Piece of Krom'zar's Banner](http://wotlk.openwow.com/item=11227)
Kaw the Mammoth Destroyer http://www.wowhead.com/spell=46310
http://www.wowhead.com/quest=10997
http://www.wowhead.com/quest=10995
http://www.wowhead.com/quest=10996
http://de.wowhead.com/quest=12713
http://www.wowhead.com/spell=18661
http://www.wowhead.com/quest=11529
http://www.wowhead.com/quest=12498
[Scythe of Antiok](http://www.wowhead.com/item=38305/scythe-of-antiok) from [Scythe of Antiok](http://www.wowhead.com/object=190354/scythe-of-antiok) for [On Ruby Wings](http://www.wowhead.com/object=190354/scythe-of-antiok).
[Drakuru's Skull](http://www.wowhead.com/item=40425/drakurus-skull) from [Drakuru's Skull](http://www.wowhead.com/object=191458/drakurus-skull).

**Comment by tkrokli** [comment]
Unless anyone else has a good reason why I should not do so, I think I need to try to use this in a PR.

**Comment by tkrokli** [comment]
[Brian](https://github.com/runningnak3d) / @runningnak3d , is there any chance you still have got the "proper fix" available on your "box at work"? When or if you see this message, could you please give us a hint what that fix would be, or even post the code? :smirk_cat:

**Comment by Rushor** [comment]
just noticed, that this is the same issues https://github.com/TrinityCore/TrinityCore/issues/12077

12077 can be closed :D

**Comment by tkrokli** [comment]
> just noticed, that this is the same issues #12077 -- 12077 can be closed :D

Well, your issue is older, has no updates and is not as specific as this issue. I am not sure if you intended to find a solution for all of those quests with one PR, did you? :smiling_imp:

Your issue has listed the following quests:
[**Alas, Andorhal**](http://www.wowhead.com/quest=105/alas-andorhal) - http://www.wowhead.com/quest=105/alas-andorhal with
[**Araj's Phylactery**](http://www.wowhead.com/spell=18661/arajs-phylactery) - http://www.wowhead.com/spell=18661/arajs-phylactery,
[**Grulloc Has Two Skulls**](http://www.wowhead.com/quest=10995/grulloc-has-two-skulls) - http://www.wowhead.com/quest=10995/grulloc-has-two-skulls,
[**Maggoc's Treasure Chest**](http://www.wowhead.com/quest=10996/maggocs-treasure-chest) - http://www.wowhead.com/quest=10996/maggocs-treasure-chest and
[**Even Gronn Have Standards**](http://www.wowhead.com/quest=10997/even-gronn-have-standards) - http://www.wowhead.com/quest=10997/even-gronn-have-standards
So I don't think your issue is so similar that it needs to be closed. :suspect: :8ball:

Or did I miss something about the code, that the suggested solution started by @runningnak3d covers all of these quests because of the group loot aspect? :smirk_cat:

**Comment by tkrokli** [comment]
Core : 4adf31c + tkrokli@073c14e (Win32, Release)
TDB 335.57 + updates + manual additions: 0c9e39f + 03edeeb

Confirmed with 2 different accounts on same computer (very slow) in party (group).
Krom'zar's Banner [164690] despawns *immediately* when 1 player loots it, I don't even manage to Alt-Tab to the other player to see it disappear. Not sure if it is worth while testing a single character to see if it remains outside of group.

Besides waiting for feedback from Brian / runningnak3d - anything else worth doing here?

**Comment by tkrokli** [comment]
@Rushor (& @runningnak3d, if you ever read your updates again); is there any code that could be applied to the GO Krom'zar's Banner [164690] so it does not despawn immediately, but stays up with a "decay" period of 5 minutes, regardless of single player or group?

I just think it does not matter if it stays visible 5 minutes after being looted by only 1 player, since it takes quite some time before the questgiver is able to activate "Counterattack!" again anyway (see https://github.com/TrinityCore/TrinityCore/issues/5420).

**Comment by tkrokli** [comment]
Looking at the code suggested by @runningnak3d in the file [GameObject.cpp](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/GameObject/GameObject.cpp) and especially the code bit
```c++
if (!m_spawnedByDefault)
```
which I think means "if object not spawned by default" (I guess). And about the next piece of code:
```c++
SetLootState(GO_JUST_DEACTIVATED);
```
won't that just create our problem instead of solving it? Wouldn't it be better to set a 5 minute decay timer?

**Comment by tkrokli** [comment]
Started to look at [/src/server/game/Entities/GameObject/GameObject.cpp](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/GameObject/GameObject.cpp), it sure is a lot to read.
Then again, if this is a global game object issue, look at https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/GameObject/GameObject.cpp#L517-L539 .
```cpp
                case GAMEOBJECT_TYPE_GOOBER:
                    if (m_cooldownTime < time(NULL))
                    {
                        RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_IN_USE);

                        SetLootState(GO_JUST_DEACTIVATED);
                        m_cooldownTime = 0;
                    }
                    break;
                case GAMEOBJECT_TYPE_CHEST:
                    if (m_groupLootTimer)
                    {
                        if (m_groupLootTimer <= diff)
                        {
                            Group* group = sGroupMgr->GetGroupByGUID(lootingGroupLowGUID);
                            if (group)
                                group->EndRoll(&loot);
                            m_groupLootTimer = 0;
                            lootingGroupLowGUID = 0;
                        }
                        else m_groupLootTimer -= diff;
                    }
                    break;
```
Maybe the value for `m_groupLootTimer` || `m_cooldownTime` should be set to uint32(300) seconds (5 minutes) somewhere here or elsewhere in the file GameObject.cpp ?

**Comment by Killyana** [comment]
According to https://youtu.be/710FEegH13Y?t=8m29s  to be in party or alone don't change the fact that the gob must be despawned by the spell timer (5min) and not by script.

**Comment by Rushor** [comment]
LFD(ev) to fix this issue :D 
Forget the whole discussion above Killyana's post - It's just the issue that the GO needs to stay 5 minutes on the ground. looting it meanwhile does not change it's state and it's always lootable again during these 5 minutes

**Comment by tkrokli** [comment]
It seems the current code overrides the despawn time of the objects, so perhaps the despawn command for this particular kind of object should be removed from the source? Going to // comment out and test.

**Comment by tkrokli** [comment]
More testing, this time testing to spawn the GameObject manually with .gobject add [Krom'zar's Banner]

- **.quest add 4021** (get the quest Counterattack! in your log, so you can loot the item)
- **.cast 13965** (it looks like it has spawned the g-GameObject, right? I'm not sure about that.)
- **.gobject near**
```
Found near gameobjects (distance 10.000000): 0
```
Now go at least 10 meters away from that banner to use a different GM command:
- **.gobject add 164690**
- **.gobject near**
```sql
164492 (Entry: 164690) - [Krom'zar's Banner X:-603.653442 Y:-4292.774414 Z:37.811275 MapId:1] 
Found near gameobjects (distance 10.000000): 1 
```
See the difference? This is the real object, the spell result is a different object which does not register as a GameObject, for some reason. Not sure if there should be another spell involved, because when I look up http://www.wowhead.com/spell=13965/create-kromzars-banner and http://www.wowhead.com/object=164690/kromzars-banner , it looks normal.

Notice: when looting the manually spawned g-object, it fades for normal players or with gm off, but is visible when turning GM ON. I just tested with only 2 level 1 characters in a group, but even if I spawned gobject 164690, it became invisible after first loot and could only be looted by GM after first loot. Is this a dead end too, or is there any practical information to be found here?

**Comment by Rushor** [comment]
@tkrokli: the gameobject is not displayed with .gobj near if you summon it with .cast 13965 because the summoned gameobject by cast is only a tempspawn without a guid in the database.
the command .gobject near only displays gameobjects with a guid in the database

still wonder if there is a easy solution to add the information to the go to not despawn after looting it

**Comment by tkrokli** [comment]
Yes, that looks correct. The object spawned by spell 13965 is only a temp gameobject.
I also wonder if there should be a simple solution to this, like a specific condition in the DB.

**Comment by Killyana** [comment]
It's a general issue, with many other objects.

**Comment by tkrokli** [comment]
Good point, looks like it is related to the objects in https://github.com/TrinityCore/TrinityCore/issues/12842#issuecomment-73031516 from Rushor's old issue https://github.com/TrinityCore/TrinityCore/issues/12077 .

**Comment by Aokromes** [comment]
@runningnak3d any new on this?

**Comment by tkrokli** [comment]
I doubt he will respond, since he has not been active on github for more than a year (since 2014).

**Comment by runningnak3d** [comment]
Not sure how I missed this the last time I looked at this, but https://github.com/TrinityCore/TrinityCore/blob/942403be0cf36b535e96fd6077204f1c98d2834c/src/server/game/Entities/GameObject/GameObject.cpp#L626 is going to override any fix that is put in place since this is summoned by a spell, so I was just wasting my time :)

Bottom line, whether it is fixed there, or where I suggested above, to fix this:

* Check if there is a group
* Get members of group
* Iterate through and check to see if the GO has loot for each member
* If no loot, continue till all members have been checked and had a chance to loot
* resume despawn timer (on offy, the GO would not immediately despawn once all members had a chance to loot -- it was on a timer)

If no active devs want to pick this up, I guess I will set myself back up a build environment and fix this. Ya, know, after looking it over, someone may want to try commenting out that code at line 626 and see if this just works again. I am not sure why that code was added. GOs spawned by spell, or GOs spawned by a negative spawn timer shouldn't be handled any differently.

**Comment by Rushor** [comment]
@runningnak3d the check for group member is not needed. if the go was spawned with the spell it should stay there for x minutes and can be looted by every player who finds it.

as pitcrawler already sai:
>http://www.wowhead.com/quest=11300 (Note that 2. comment: "If you happen to come up as someone >finishes, the cipher is on the ground. You can easily loot it without killing a thing."...).
>http://www.wowhead.com/quest=11529
>http://www.wowhead.com/quest=12498

**Comment by runningnak3d** [comment]
Well I guess I should have read the follow up comments. I just wasted 2 days writing a bunch of code to handle checking if in a group, and allowing the group members to loot before despawn. After reading this follow up, it was much simpler, but the other day was spent tracking down where the effing problem was in the first place. Anyway, here is the fix: https://gist.github.com/runningnak3d/6c306427524de37b8927db877beb0d0c

I have only tested it on 'Kaw the Mammoth Destroyer':

.quest add 11879
.cast 46310

I tested with two clients as my "group", but as was stated, you don't have to be in a group. If a spell spawns a GO, and there is a quest item for you -- you can loot it if you beat the timer.

I'm not going to make a PR till this is tested with other quests, and since this affects ALL spell summoned GOs (even if they don't have loot), they need to be tested as well.

**Comment by Rushor** [comment]
thank you very much! i will give feedback to this after one week, after some player tested these quests

**Comment by Aokromes** [comment]
This is still needed?

**Comment by runningnak3d** [comment]
Yes. Feel free to create a PR, or I will when I am back from vacation.

**Comment by runningnak3d** [comment]
Actually, no I wont. I already made a PR based on an updated patch ... that is correct ... and it was closed. Patch runs fine on my server, doesn't matter to me if the powers that be don't feel like doing a little research. What makes me lmao is the code snippet @shauren posted from the client proved I was correct, he just read it wrong.
