### ISSUE TITLE
Error spam

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#12853]
Recently the core shows this error repeatedly:

"SmartScript: Action target Creature (GUID: 45218 Entry: 5743) is not using SmartAI, action called by Creature (GUID: 45218 Entry: 5743) skipped to prevent crash."

hash: e65f5ec142c3c3fd9fe7e8dc81ffee2a9099c980

**Comment by Killyana** [comment]
``` sql UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=5743;

**Comment by joschiwald** [comment]
this is not the right way to fix this issue

**Comment by tkrokli** [comment]
TrinityCore rev. 9e3001a44b7f 2015-05-25 01:07:52 +0200 (3.3.5 branch) (Win64, Release)
Using World DB: TDB 335.58 (+ updates up to and including 2015_05_25_00_world.sql)
In my DBErrors.log, the message is slightly different :

SmartScript: Action target Creature (GUID: 37284 Entry: 11836) is not using SmartAI, action called by Creature (GUID: 37284 Entry: 11836) skipped to prevent crash.

Difference: GUID 45218 => 37284; Entry 5743 => 11836 :
http://www.wowhead.com/npc=11836/captured-rabid-thistle-bear
Related to this quest : http://wowwiki.wikia.com/Quest:Plagued_Lands (quest removed in Cataclysm)

Old Entry: 
http://wotlk.openwow.com/npc=5743 (Caged Sheep) - `This NPC can be found in Undercity.`
http://www.wowhead.com/npc=5743/caged-sheep - `The location of this NPC is unknown.`

I can only guess that the error is variable and not specific, because it triggered during game play.

**Comment by tkrokli** [comment]
TrinityCore rev. e6a7818 2016-01-24 16:47:39 +0100 (3.3.5 branch) (Win64, Release), TDB 335.60

Confirming that the error still shows up when in Undercity, near the Apothecarium. The solution suggested by **Killyana** works, so I don't understand why it can't be used. @joschiwald : why not?

**Comment by dr-j** [comment]
There are a number of npcs which which change entry to another creature during script since the script is on the original entry (and is still running perfectly ingame) it throws up these errors because it thinks there is no script on the creature.  Happens with the other caged creatures from the apothecary script too.

Due to the fact that it works in game think in these circumstances these are false errors and it was discussed somewhere before if not on github on rizon but saying the core should store the default entry of a creature before any updates are made to entry so that those errors can be excluded.

**Comment by SnapperRy** [comment]
Error was due to SAI despawn calling IsSmart() (which returned that error log) despite it not being limited to SAI-only targets.

Fixed in 727f77e by changing SMART_ACTION_FORCE_DESPAWN to actually use DespawnOrUnsummon() directly instead of using the internal despawn system (that still called DespawnOrUnsummon() after the specified delay. Useless since DespawnOrUnsummon() takes a delay argument).
