### ISSUE TITLE
[crash] SetUnloadReferenceLock

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#13009]
I have this crash on commit c5f475c114c3a468783d7578bd500c02a39e6965

http://pastebin.com/EcM1KB7L

Ubuntu 14.04.
pvpranks, passive antihack and transmogrification patch.

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Pirricli** [comment]
Without crash since the last comment.

**Comment by Pirricli** [comment]
http://pastebin.com/JrRY1Fk0

da74aa526a30a1312abd071d3c6906907c6f0d2c

**Comment by xjose93** [comment]
http://pastebin.com/4SXwgk3D yesterday happened

0148832b322b58a5219ea4393331e1b5937c304c

**Comment by xjose93** [comment]
http://pastebin.com/qYqm43bK

cac4f95976989a70fc7f5b50f0d76100300af067

**Comment by xjose93** [comment]
http://pastebin.com/8EW69pGD

0b9cd22a6b5a0cca6e3c07dd5ae077ddbdfc3992

**Comment by xjose93** [comment]
http://pastebin.com/N6JjqMuG

c544e88437106fb79dba14bbf8469deadb679e8a

**Comment by jackpoz** [comment]
Do you have any custom patch or change applied ?

**Comment by xjose93** [comment]
Yeah, i have some fixes and custom patches like ac, transmog.

**Comment by tkrokli** [comment]
@xjose93 : you are most likely getting crashes in AntiCheat, because the following line is not clean source:
```cpp
MapInstanced::RemoveGridMapReference (this=<optimized out>, p=...) at /home/wow/335/source/tc335/src/server/game/Maps/MapInstanced.h:60
```
If you take the time to browse your logs and look for the TC source files mentioned, then look up the files and lines in the online code like this one, https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Maps/MapInstanced.h#L60 ,  you will see that your source contains different code from the TC 3.3.5 branch and that your extra code is referenced in the crash logs.

**Comment by xjose93** [comment]
http://pastebin.com/N6JjqMuG on line 36:
 i = {_Ptr = 0x0}

Can this be null?

**Comment by jackpoz** [comment]
try after https://github.com/TrinityCore/TrinityCore/commit/ca7f31c6cdceb7e2921d5d83e1ae22ccb247988d

**Comment by xjose93** [comment]
Thanks a lot @jackpoz i'll reopen ticket if i got same or similar crashlog.

**Comment by jackpoz** [comment]
my commit is not strictly related to this issue but it's worth a try
