### ISSUE TITLE
AHBot buyer not working

### ISSUE THREAD

**Issue by Argusi** [TrinityCore/TrinityCore#13142]
Unable to get the AHBot buyer to buy anything. Tried several revs, last tested was a6ed252

Enabled auctionhouse and ahbot logging in worldserver.conf, restarted, but no output related to this after 24 hours. 

I tested many items, but in my last controlled test, this is what I did:
Item: Shadowblade x15 (Item 2163)
Sell Price per tooltip: 4.67.10
Buy price: Not sure, but I know it's more than sell price
AHBot selling this item for ~22-23 Gold
 
I put 5 Shadowblades up for buyout at 1 Silver.
5 at 4 Gold
5 at 7 Gold
24 hour auction. Nothing sold. 

Everything is enabled as far as I can tell. The pertinent part of worldserver.conf is available here:
http://pastebin.com/PpuLCF9U

Here is what you will most likely ask about:
AuctionHouseBot.Buyer.Enabled = 1
AuctionHouseBot.Buyer.Alliance.Enabled = 1
AuctionHouseBot.Buyer.Horde.Enabled = 1
AuctionHouseBot.Buyer.Neutral.Enabled = 1
AuctionHouseBot.Buyer.Buyprice = 1
AuctionHouseBot.Buyer.Recheck.Interval = 20
AuctionHouseBot.Buyer.Alliance.Chance.Ratio = 2
AuctionHouseBot.Buyer.Horde.Chance.Ratio = 2
AuctionHouseBot.Buyer.Neutral.Chance.Ratio = 2

AHBot sells just fine. No issues there that I can see.

**Comment by dmanbob** [comment]
The configs don't seem to change anything in the AH

AHbot seller
AuctionHouseBot.BuyPrice.Seller = 1
e.g. AuctionHouseBot.Alliance.Price.Ratio=1000 I would think that this would list items at 10x the item vendor buy price plus that original 50% so 1050% but the buyout prices just stays=to vendor buy price of the item.
The only time the 50% increase happens is when I list an item in the AH it adds 50% to the starting bid above the vendor buy price.

AHbot buyer.
No matter what price I set an item to the ahbot will not purchase it and looking at the code there is a very small chance anything will be purchased no matter the price.
I assumed changing this value would give 100% chance for the AHbot to buy a reasonably priced item. AuctionHouseBot.Buyer.Alliance.Chance.Ratio = 1 I assume by the description this should change the chance the ahbot would buy a reasonable priced item to 1 to 1 ratio =100% as the default ratio is 1 to 3 chance 33%

I'm going to rewrite the code similar to my stand alone AHBuyer program and see if I can make the AHbot configs easier for everyone.

**Comment by dmanbob** [comment]
I tried increasing the chance ratios in the code by decreasing the ratios even to as low as 1 which in theory should raise chances to 100% if I set the ahbuyer chance ratio to 1 in the config.
AuctionHouseBot.Buyer.Alliance.Chance.Ratio = 1
AuctionHouseBot.Buyer.Horde.Chance.Ratio = 1
AuctionHouseBot.Buyer.Neutral.Chance.Ratio = 1

After a recompile:

Still no matter what I list even at extremely low price the AHbot never buys or bids on anything I list whether it's a grey or purple item. One interesting thing I noticed if I list something with a starting price and a buyout price the ahbot changes my starting price to match my buyout price after a few seconds.(this happened even before I edited anything in the code)

**Comment by dmanbob** [comment]
config.FactionChance = 5000 * factionChance;

maxChance / 500 and maxChance / 1000

I changed these values  to 1 which should in theory make your chances of selling your item very high if you also change in worldserver.conf

AuctionHouseBot.Buyer.Alliance.Chance.Ratio = 1  (1 out of 1 chance=100%)
AuctionHouseBot.Buyer.Horde.Chance.Ratio = 1
AuctionHouseBot.Buyer.Neutral.Chance.Ratio = 1

I recompiled with these changes and still the AHbot won't by any items no mater how I price them.

seems all the ahbuyer code needs to be looked at.

**Comment by MrSmite** [comment]
Personally I think that the whole "chance to buy" calculation is being made more difficult than it needs to be. All you really need is:

* Check if an item is biddable by making sure the listed price is within (base_price) + (% overprice)
* Roll a random chance (config based 0 to 100) to see if the bot will actually bid on the valid item
* Roll a random chance between 0 and 1 to see if the bot will bid or buy the valid item item

So if *Percent.Overpriced = 50* and my item is 150% above it's BuyPrice or SellPrice (depends on the choice of which price type you're using) then it is a valid item. If *Chance.BidOrBuy = 33* then the bot rolls a random with a 33% chance of success and if it wins then it simply picks a random between 1 and 0 to determine its action.

**Comment by dmanbob** [comment]
Not sure where this is at but this would be my 2 cents on a rewrite.
Use the config selling settings of the items qualities to establish a "market value" for the ahbuyer.
e.g combination of these 2 settings
AuctionHouseBot.Alliance.Price.Ratio = 100 (even eliminate this who cares about faction)
AuctionHouseBot.Items.Blue.Price.Ratio = 200

Check to see if starting bid and/or buyout price fall within selling configs "market value"

buyout item or place a bid buy using a chance.ratio from configs to bid or buyout. bid to a maximum amount of buyout price or max "market price" if item listing has no buyout price.

Eliminate factionchance e.g. Alliance, Horde and Neutral chances (who cares where the ahbot is buying from)

Eliminate adding a bid if a player adds a bid. Most small servers this is never going to happen anyways.

AuctionHouseBot.Buyer.Chance.Ratio = 1   use this as the main chance to buy or bid. number 1-10 1=100% 10=10%

I think it needs to be kept really simple as on a small population based server you would want your players to have a decent chance to sell their items.

**Comment by jackpoz** [comment]
@Rochet2 your AHBot is still broken after a few months of it being merged, can we see a fix anytime soon ?

**Comment by Rochet2** [comment]
@jackpoz It seems a rather great task considering all the hardcoded values. To make the logic clearer and to make one able to understand it better, a rewrite of the logic is probably needed as few have suggested. The original creators might not be around to explain needed parts and there are no comments on the hard coded values, figuring them out is largely guessing.
The bot is not _mine_, I simply updated it and fixed various things in it.

You can get a greater buying chance with setting these to 1, since the urand is between 1 and faction chance ratio * 3 and the smaller value, the better.
```
AuctionHouseBot.Buyer.Alliance.Chance.Ratio = 1
AuctionHouseBot.Buyer.Horde.Chance.Ratio = 1
AuctionHouseBot.Buyer.Neutral.Chance.Ratio = 1
```

The already posted logs and from what I tested, the items are being bidded and bought, so the chances is not the actual issue - even though they seem to be way too small for some cases.
From below comments you can see that the chances for bidding are extremely small. Tweaking this part to have higher chances for under priced and items under max price could be needed.
The buying works similarly.
```C++
    // Price too low, IE shadow blade sold with default 7g or under
    if (bidPrice <= minBidPrice)
    {
        if (inGameBuyPrice != 0 && bidPrice < inGameBuyPrice - (inGameBuyPrice / 30))
            chance = maxChance; // Sold under 29/30 of ingame price - Chance (50%)
        else
        {
            if (bidPrice < maxBidablePrice)
            {
                ratio = maxBidablePrice / bidPrice;
                if (ratio < 3)
                    chance = maxChance / 500 * ratio; // Sold cheap and bidded on some, set chance higher if low bid price - Chance (0.1%-0.4%)
                else
                    chance = maxChance / 500; // sold cheap and not bidded on or bidded too much - Chance (0.1%)
            }
        }
    }
    else if (bidPrice < (inGameBuyPrice - (inGameBuyPrice / 30)))
        chance = (maxChance / 10); // Price is under 29/30 of ingame price, but still over minimum bid price. Chance (5%)
    else
    {
        // Price over minimum and over ingame price and under max price
        if (bidPrice < maxBidablePrice)
        {
            ratio = maxBidablePrice / bidPrice;
            if (ratio < 4)
                chance = maxChance / 1000 * ratio; // Set chance higher if low bid price - Chance (0.05%-0.2%)
            else
                chance = maxChance / 1000; // Chance (0.05%)
        }
    }
```

Few actual bugs I noticed is that the auctions are not instantly bought by the bot and that the bidding doesnt change the bidder to the bot.
When the bot buys, the bid price is set equal to buyout and that causes the auction to be locked (cant bid or buyout) until the time runs out. After time is out, the item is won by bot since he was last bidder.
`AuctionBotBuyer::BuyEntry`
When the bot bids, the bid price is increased, but the buyer is not set to 0. This can possibly cause the previous bidder to seem to have bidded it for more than he did, while it was actually the bot.
`AuctionBotBuyer::PlaceBidToEntry`

After fixing that, the bot should be able to bid and buy.
I can maybe try code and test them over next week, but maybe thinking out a new logic is also required..

**Comment by Rochet2** [comment]
I got the buying fixed but the bid and buy logic needs better math.
I was thinking that could have something like the base price and then the chance would get lowered when sold for more and more gold.
For example: `1/sqrt( sellprice/vendorprice )` This would provide a number between 0 and 1+ as the chance and for example selling with 100* item price (which seems common) there would be 10 % chance, for 10 times vendor price it would be 30 % chance and for 1000 times vendor price - which is really high - it would be 3% chance. Selling an item for vendor price would be 100% chance for bot to buy it and all sold under that are also above 100% so they will be bought by 100% chance as well.
A hard cap at 1000*vendor price could be made or similar.

This could be made tweakable, or maybe someone can think of a better formula.
Having just the chances or relying on prices used by others seems very unreliable to me as it would be pure random or the user could fake auctions to make the bot buy his.
Using a formula like this would also use the vendor price and make more sense than using some min and max.

Thoughts?

**Comment by dmanbob** [comment]
The selling prices set by "others" is actually be the ahbot seller because if your ahbot seller configs is set too e.g.
AuctionHouseBot.Alliance.Price.Ratio = 100    (actual value 1)
AuctionHouseBot.Items.Blue.Price.Ratio = 600. (actual value 6)

This means the going price for blue itemsin Allaince AH is 6x what a vendor would buy or sell if for depending on if you set vendor sell or vendor buy price. So you could still set market prices by tweaking the ahbot quality selling prices. If your listed "blue item" fell within the 6x range then there is a great chance it should be bought by the ahbot. If you asked say 7-9x the price then there should be  a small chance you would sell it and more than 10x not much chance at all. If you did not have the AHbot seller enabled then I could see you would need to some how set some min/ maxes so people don't exploit. But I can't personally see anyone using just the buying side of the ahbot without using the ahbot seller.  By having the AHbot sller enabled I look at those prices as a "market value" Again as my previous post said that is how I base me asking price on an item when I play retail. I look at the item if it is listed and set a reasonable price based on what others are posting that item or similar items for. This way I have a good chance to sell it.

**Comment by MrSmite** [comment]
> Using a formula like this would also use the vendor price

By "vendor price" are you referring to BuyPrice (the price to buy from a vendor)? If so, this would mean the bot would ignore a lot of items where BuyPrice=0 AND SellPrice>0 (354 items total). For example, most of the cut gems have no BuyPrice.

On the other hand, if you're referring to SellPrice (the price the vendor pays to buy from you), there are also several items (241 total) that would be ignored (eg: enchanting mats, mounts, recipes).

This was one of the problems with the original AHBot. Forcing it to use either BuyPrice or SellPrice without an option to buy it if either (or both) is zero means a lot of items are ignored.

**Comment by dmanbob** [comment]
I agree that items with no vendor sell or buy price is a very tricky because you don't have any benchmarks to set these prices. Although if you have one known value you can set the other. Basically the vendor will usually give you about 
25% of what you buy an item from them. So the gems for example because we know we can sell them for say 4 gold to a vendor then we can set a starting "vendor buy" price to 16 gold it will take some coding but could be done this would at least give the ahbot something to work with .

**Comment by Rochet2** [comment]
> By "vendor price" are you referring to BuyPrice (the price to buy from a vendor)?

I meant the price a vendor offers you when you sell the item. However the default AH price comes from vendor sellprice*1.5 and if there is no sellprice its 1 silver, so similarly I was going to use a base price and possibly vary it by item quality or similar.

> If you ask way too much (compared to other similar or exact items) no one will buy your item period.

Except the bot that can be fooled. One can find an item that isnt sold at all or sold little and reap benefits.

**Comment by dmanbob** [comment]
Sorry I was referring to "vendor price" as being from the AHbot configs

#    AuctionHouseBot.BuyPrice.Seller
#       Description: Should the Seller use BuyPrice or SellPrice to determine Bid Prices
#       Default:     1 - (use SellPrice)
#                    0 - (use BuyPrice)

AuctionHouseBot.BuyPrice.Seller = 0

I meant that you would use one or the other as the starting point for your AH price listings which would also be the same starting point aka "market value" for the AHbuyer  combined of course with these 2 settings as an example from the seller configs.

AuctionHouseBot.Alliance.Price.Ratio = 100 (actual value 1)
AuctionHouseBot.Items.Blue.Price.Ratio = 600. (actual value 6)

**Comment by Rochet2** [comment]
Here is the fixed version:
https://github.com/Rochet2/TrinityCore/tree/ahbot_buyer

The buy / bid rolls have been changed though and currently the market value is ignored.

**Comment by dmanbob** [comment]
Great thanks Rochet2 as long as it works I'm OK with that ;)

**Comment by jackpoz** [comment]
We could continue the discussion on a PR of those changes

**Comment by Rochet2** [comment]
Alright. Ill make few more changes and then Ill PR

**Comment by jackpoz** [comment]
Fixed in https://github.com/TrinityCore/TrinityCore/commit/b69fd4ac682347b8b735ac7116ada25d79698933
