### ISSUE TITLE
BUG: Quest: Massacre At Light's Point

### ISSUE THREAD

**Issue by Milcheff** [TrinityCore/TrinityCore#13342]
Scarlet Cannon on the ships can be moved.

**Comment by Aokromes** [comment]
#8736

**Comment by ccrs** [comment]
@Aokromes there are more issue appart from the cannon move <.<

**Comment by Rushor** [comment]
too much for one issue :D

**Comment by pete318** [comment]
The thing is, the bug was opened about the cannons. But, much more was detailed. At any rate, once the cannon fix is absorbed, I'll try to make an SAI change as an issue to correct the other issues.

I think this one can remained closed.. My memory isn't that bad. Also another issue can always be raised to report the other issues anyway. :)
