### ISSUE TITLE
[3.3.5][Hunter] Autoshot/Autoattack - Bad function if victim runs away

### ISSUE THREAD

**Issue by iceyman** [TrinityCore/TrinityCore#13595]
when using autoshot on the hunter and the npc come close to kill with close combat item and then runs in fear autoshot doesn't always work 

stop auto attack bot isn't ticked either

Core 898ecf7222fb

DB 335.57

addons - NONE
##

**Comment by MrSmite** [comment]
Couple notes:

* This may be related to #14460
* This happens on older core: 42f1a0babfaac but not on even older: c28345e279f3 though I didn't look to see what's different
* This happens even with the Blizzard UI setting "Auto Attack / Auto Shot" enabled

I noticed while playing on 42f1a0babfaac that whenever a mob would "run away in fear", my autoshot will get stuck if they run out of range and then back in range. Also, if the mob runs to melee range when this happens, you also will not switch attack modes.

Once it is stuck you have to manually stop attacking and start again.

**Comment by Demonid** [comment]
Confirmed on 1184e98da1690f1a12e5939d29fec2f03bef4710

**Comment by Rushor** [comment]
**UPDATE**

I have encountered this issue pretty frequently and it's getting a bit tedious. In order to recreate the issue, you obviously need a hunter. Just use "Raptor Strike" and before it strikes the targeted creature, go out of melee range. This also happens if the targeted mob starts fleeing as you're about to hit it. This will render the hunter unable to do any melee attacks as it seems to be stuck in melee attack-mode, you will need to relog to fix this issue. I'm not sure that this is something that is hunter specific or if it occurs to other classes aswell nor am I sure if it's isolated to "Raptor Strike". It can also be hard to reproduce as the target needs to be on the edge what is considered melee range.

If the target goes out of range the attack should ofcourse reset and not force the hunter into an endless loop trying to melee attack the old target.

https://github.com/TrinityCore/TrinityCore/issues/9347

**Comment by MrSmite** [comment]
> nor am I sure if it's isolated to "Raptor Strike"

It's not limited to Raptor, I've had it happen to me when spamming Wing Clip.

**Comment by pak3935** [comment]
sorry for the stupid question
when time to fix the auto-attack on the enemy through textures or objects?

**Comment by Max0r847** [comment]
I managed to make this happen on a feral druid today, as detailed in the referenced dalaranwow issue. My conclusion is, either it's a fundamental problem for all classes, -or- it only affects classes that have different auto-attack modes they can switch to, i.e. hunters with shots/melee and druids with various forms.

**Comment by MrSmite** [comment]
It's most likely a problem with the core not sending the proper packets. Even now on "current" cores you end up with this on a Hunter:

Ranged -> mob runs to melee -> melee -> mob runs away -> Hunter switch to range but doesn't shoot

The strange thing is that the Hunter will actually switch to the ranged animation but it stops after the bow is drawn and never shoots. If the mob runs back to melee, the animation stays as if in ranged and melee attacks do not work. Currently, deselecting the target resets everything.
