### ISSUE TITLE
[3.3.5][6.x] Respawntimer should start ticking straight after killing the unit + creature should be respawned as completely new unit with new guid $20 

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#13787]
General Core issue. Revision while reporting this issue: 5d4f26d82028823f4672e370deaf0f6069fb225f

While I was playing on retail, something got my attention while I was killing some units in some starting zones. When I kill a unit and do not loot the corpse, the npc remains in world but also a new unit gets spawned after a while which is supposed to be the respawned unit.

So instead of removing the corpse from the world and re-use the guid, blizz creates completely new units.

The core currently respawns the unit by re-using the corpse instead of spawning a new one and destroy the old one after looting /  decay time expired.

So the progress should be:
1. Unit dies
2. Respawntimer to create a new npc at the spawn location starts
3. Create a completely new npc after timer expires.

So the old corpse is being completely ignored on retail. It just despawns and is completely removed from the world. This also explains why the respawned units in sniffs have different guids

This would also fix the annoying exploit that some players keep the corpses unlooted to prevent them respawning so the area stays empty after a while.
##

**Comment by pete318** [comment]
The linked PR by me is an interim solution to the issue of insufficient creatures being around in busy areas. It's an interim solution that just adds a minimum number of spawns and then chooses a current corpse to revive using specific rules to minimize player annoyance.

If you look further down and indeed into the forum thread on the subject you'll see it moves onto this exact issue and some possible solutions are suggested.

I'm currently working on a design and ultimately a change to the pooling system that will address this. But, it will mean all creatures would need to be in pools to be covered by the new functionality.

I'm not convinced the cartoon could (safely) be done. e.g. you renumber the guid of the unit itself. But, I've not looked into that. I'd be just generating new guids. As far as I know SAI works on the template and not the creature guid itself. So, changing either way wouldn't hurt that (I think at least).

**Comment by MrSmite** [comment]
This could be done relatively easy by randomly generating a GUID when the creature is spawned. The main issue is the possibility of duplicate GUIDs which could be overcome by generating them with a unix timestamp based on YYYYMMDDHHNNSSss (where NN = minutes, SS= seconds, ss=milliseconds).

I think the main problem is the amount of core rewrite that would be necessary to accomodate dynamic GUIDs would be daunting.

**Comment by Aokromes** [comment]
3.x client can't handle a such high guid like 20.150.101.101.010

**Comment by MrSmite** [comment]
> 3.x client can't handle a such high guid like 2.015.010.110.100.999, nor to say multiple creatures can be spawned on same ms.

Well I was thinking to add the numbers together so 2015-01-11 06:32:25:12 would be 2012. Also, Boost can go tighter than milliseconds but I'm not too familiar with that.

**Comment by MrSmite** [comment]
What about [Boost's UUID](http://www.boost.org/doc/libs/1_57_0/libs/uuid/uuid.html) generator?

> A UUID, or Universally unique identifier, is intended to uniquely identify information in a distributed environment without significant central coordination. It can be used to tag objects with very short lifetimes, or to reliably identify very persistent objects across a network

I don't know if it can generate an all numeric UUID or not but it might be worth looking at.

**Comment by Shauren** [comment]
You are forgetting that blizzard guid has a predefined format - it includes object type and creature entry (map, server, realm too on 6.x), the space for generated counter is very small (less than int/long long)
Changing guid format is completely out of the question

**Comment by DDuarte** [comment]
```
13:44:37 <%click> nayd: actually, atomic GUIDs aren't all that bad, BUT it's a real pain to manage, and the entropy isn't large enough inside the game - basically you'd need a 128-bit or higher entropy to avoid false positives (if generating well over 1 million UIDs within that timeframe)
13:44:57 <@Aokromes> we have a problem, client limitation
13:45:02 <@Aokromes> (as for 3.3.5a)
13:45:09 <%Nayd> timestamp is not atomic
13:46:02 <%click> nayd: no, i'm talking about atomic guids, not timestamps - the timestamp-handling is extremely shitty at best
13:48:27 <%click> an atomic GUID would require at least a 16-byte (128-bit) interpretation - the client doesn't support more than less than half of that in any case (0x7fffffff) iirc?
13:49:01 <@Aokromes> 3.3.5a supports around 2.000 millons iirc
13:50:19 <%click> 2.147.483.647
13:50:28 <%click> to be exact, and that is 0x7fffffff
13:51:37 <%Nayd> we don't need to generate random guids
13:51:48 <%Nayd> it could be as simple as ++'ing a static int
13:52:15 <%click> you'll bump into an issue with overflows then
13:53:10 <%click> but, uhm, iirc, aren't we actually using TWO guidsets? both 32-bit ints?
13:53:17 <%click> high/lowguid ?
13:53:25 <%Nayd> depends on the branch...
13:54:03 <%click> let's think 3.3.5a for now, since that is the branch that i can remember anything at all from
13:54:32 <%click> (mind you, i've been out of the loop for a serious amount of time)
13:54:51 <%Nayd> 3,3,5 we get up to 0xFFFFFFFF
13:55:15 <%click> ok, basic 32-bit
13:55:16 <%Nayd> lower than that actually
13:55:17 <%Nayd> 0xFFFFFF
13:55:29 <%click> 3-byte interpretation?
13:55:32 <%Nayd> yes
13:55:54 <%click> barely over 16M entities then
13:55:57 <%Nayd> 4 bytes in 4.x
13:56:02 <%jackpoz> 4th byte has a part of creature entry, right ?
13:56:27 <%Nayd> http://paste2.org/4ncyYeC4
13:56:57 <%Nayd> 5 bytes in 6.x
13:58:25 <%click> well, timestamp-based UUID wouldn't work anyway
13:58:29 <%Nayd> I'm not sure if it is required that two different creature (diff entry) need to have different CreationBits
13:58:40 <%click> since that leaves a 60-bit entropy
13:58:54 <%click> (with microsec/nanosec included)
13:59:03 <%click> wouldn't do no good
13:59:25 <%Nayd> removed from world creatures could put their guid into a pool of unused guids
13:59:37 <%click> that was discussed earlier
13:59:39 <%Nayd> and next guid needed could take one from there
13:59:44 <%click> and is the 'better' choice
13:59:50 <%click> guidpooling
14:00:01 <%click> but it requires a heck of a lot of maintenance
14:00:11 <%click> "guid-recycling"
14:00:21 <%jackpoz> tc has no guid recycling atm ?
14:00:21 <%click> we talked about that a few years back remember?
14:00:25 <%click> jackpoz: neg.
14:00:45 <%jackpoz> I saw it around, recycled are used only after some threshold
14:00:47 <%click> jackpoz: not on 3.3.5a branch at least, it was discussed, but never implemented as far as i can remember
14:00:56 <%jackpoz> like after 100 new guids, use the recycled ones
14:01:13 <%click> pool reclamation is a bitch btw
14:01:32 <%Nayd> ConcurrentQueue<int> gogo
14:01:34 <%click> it'll hog a lot of memory to keep a tree active
14:01:44 <%click> tree/map/whatever
14:02:21 <%Nayd> anyway, first move would to generate guids 'on the fly' and not use the DB guid = low guid
14:02:35 <%click> true
14:02:52 <@Aokromes> use instances method for all maps?
14:02:54 <%click> need a GC
14:03:00 <@Aokromes> 1st spawned, 1st served
14:03:01 <@Aokromes> xd
14:03:01 <%click> aokromes: kind of, yes
```

**Comment by MrSmite** [comment]
I remember mentioning reusing GUIDs a few years ago. I think one of the drawbacks was the performance impact but after what @Shauren mentioned, it wouldn't work anyway if it includes creature entry. You couldn't reassign a GUID to a different entry.

**Comment by killradio** [comment]
@MrSmite mb you are right and its will be more easy to rewrite spawn system in way you mentioned as temp soluton, till someone rewrite it completely. But "nothing is so permanent as a temporary".

**Comment by Shauren** [comment]
GUID stuff is partially implemented in 6.x branch already - units get a new guid when they are reloaded after grid unload, what remains is generating a new creature on respawn instead of reusing old one (see #14341)

**Comment by pete318** [comment]
I was actually considering this. I mean once I finally get some more solid time to continue putting in the 6.x changes into 3.3.5, my ultimate goal was to then work the existing pooling (part 2) to use this map unique IDs.

But it could be extended to general creatures too. e.g. to separate respawn time and corpse decay regardless. Since the guid is separated from DBGUID now. Which is the extra part I was thinking of.

I mean, the new pooling system will be nice and allow more retail like spawning of multiple creature types. But, it'd take a huge effort to respawn zones using this system. It wouldn't happen for quite some time (if ever) that all zones could be done that way (it took me an hour or so JUST to do Deathknell). Helper scripts can be made (I made some) but they are just that, helper scripts. Manual intervention is needed.

So, ultimately something needs to be done about creatures not in a pool, so that there's isn't a separate world of creatures that behave like retail and those that don't.

**Comment by killradio** [comment]
@Shauren https://github.com/TrinityCore/TrinityCore/commit/ca83e14 -- looks rly promising, thx. But as pete318 said, his pull request not done yet, it waits for some "preparation work".

**Comment by pete318** [comment]
The preparation work, is myself incorporating the 6.x local guid change by @Shauren into 3.3.5. Since, the limitation right now of using this is

1: The starting guid for dynamic spawns is max DB guid + 1. Which means it's already starting in the 200,000's. 

2: They're unique for the whole server, not just per map. 

Which combined means on even a medium population server, guid overflow would happen too soon.

So, before this can be seriously considered, I think this needs to be in 3.3.5.

**Comment by killradio** [comment]
@pete318 "Medium population server" should be last thing to worry about. Its rly interesting, how blizz handle this problem, since for 335 version they have only 16M?

**Comment by pete318** [comment]
16,777,216 if I remember right (based on how many colours the Amiga AGA chipset had, with a 24 bit palette).

But remember that's per map. So that many for EK, again for Kalimdor and per dungeon/raid instance.

Probably, it explains the weekly maintenance reboot :)

**Comment by killradio** [comment]
"that's per map" -- you mean map like kalimdor, azeroth? Or locations/zones like durotar, elwynn forest?

**Comment by pete318** [comment]
Map in terms of trinitycore is Kalimdor/Eastern Kingdoms is a map each

Then, each battleground, each dungeon etc is a map.

So all the creatures on Kalimdor use a pool and all those on EK have their own pool. Every time you enter an instance a new pool is started from 1.

Of course the only ones in danger of reaching the limit are Kalimdor/EK. But even the most populated realms likely didn't hit it in one week.

Mechanisms can be built in to force a restart in quieter times if the limit is getting close.

**Comment by MrSmite** [comment]
If GUIDs will be dynamic, why can't they be reused on creature death?

When a creature is spawning, the core can:

```C++
void RespawnExample()
{
    uint32 theGuid = GetGuid();

    if (theGuid == 0)
        theGuid = GenerateRandomGuid();
        
    // do stuff
}

void CreatureDieExample()
{
    availableGUIDs.push_back(this->GUID);
    // do stuff
}

uint32 GetGuid()
{
    uint32 tmp = 0;

    if (!availableGUIDs.empty())
    {
        tmp = availableGUIDs.begin();
        availableGUIDs.pop();
    }

    return tmp;
}
```

just a thought

**Comment by pete318** [comment]
As I mentioned in the other issue reported https://github.com/TrinityCore/TrinityCore/issues/15222 the problem isn't that you can't reuse guids. In fact, if you look at the second PR for pooling I made, there is an option to do just that.

What happens if you do is you get the strange artefact (that already exists in TC) where if the level of a creature differs from the last one the same client saw on that guid, it will show the level up animation. So far as I can see there isn't a way to prevent this happening.

Also, of course with a long time running server you could end up with quite a guid list being stored.

Also in your example it's not right either. You can only push back the GUID after the corpse despawns, not when the creature dies.

Creature dies, becomes corpse, corpse is looted or not looted, either way eventually corpse timer is exhausted and then object is despawned. You can then optionally put it into a list as you say. But this artefact will happen.

My opinion is that it's far better to just keep using guids and provide configuration options of an upper limit (say for example 10M by default) and a "quiet time" config. Once the limit is reached the server will queue a restart at the next quiet time. With a countdown etc. Probably an upper boundary (15M maybe) can be used to instantly cause a 15min countdown restart.

That way, no artefacts and it's possible only the very most active servers would be hitting this limit per map within a week. Servers should also then have a weekly maintenance restart anyway (entirely like retail).

**Comment by NorthStrider** [comment]
if you want do it like blizz you have to use new guids for each new unit. That's it.

**Comment by MrSmite** [comment]
@pete318 OK, so save the GUID on despawn then. There should be more than enough room to use unique GUIDs at server start until the first creature despawns (don't they despawn if the grid becomes inactive too?). As I mentioned in my pseudocode, you would pull a GUID for same level creature which should avoid the artifact.

@NorthStrider True but then again, some things may not be possible to do 100% Blizzlike but "close enough" might still be a good option.

**Comment by MrSmite** [comment]
These SQL statements are interesting (run against an old TDB):

```SQL
SELECT
 cr.`id`, ct.`entry`, ct.`minlevel`, ct.`maxlevel`,
 IF ((ct.`maxlevel` - ct.`minlevel`) = 0, 1, (ct.`maxlevel` - ct.`minlevel`) +1) AS `GUIDs needed`
FROM
 `creature_template` ct, `creature` cr
WHERE
 cr.`id` = ct.`entry`;


SELECT 
 SUM(`GUIDs needed`)
FROM
 (SELECT
    cr.`id`, ct.`entry`, ct.`minlevel`, ct.`maxlevel`,
    IF ((ct.`maxlevel` - ct.`minlevel`) = 0, 1, (ct.`maxlevel` - ct.`minlevel`) +1) AS `GUIDs needed`
  FROM
    `creature_template` ct, `creature` cr
  WHERE
    cr.`id` = ct.`entry`) AS query_table;
```

The first statement shows every spawn and the number of GUIDs it would take to accomodate every level that spawn could be. The second statement simply shows that we would need 251,511 GUIDs to support a unique GUID for every level of every spawn.

Why then can't we simply use the GUID in the DB as a base and simply create "ghost" GUIDS for each required level and use them when respawning? A "ghost" GUID would use the same spawn data as the base GUID but would be used when a specific level is requested to spawn.

**Comment by pete318** [comment]
@MrSmite 

The first point. Adding level into the store for used guids, would mean you now have to SEARCH for a free guid that matches your requirements rather than just pick one. This now adds processing time for every single spawn in game that wasn't needed before.

I don't think that's a good idea at all.

As for the idea of a unique guid per level. It's kinda pointless since in 6.x already the actual guid isn't tied to dbguid at all. That is to say the levelup artefact, if it used to happen in 6.x simple will not happen because it already uses a counter there.

Right now I am trying to implement that same functionality into 3.3.5. There's some caveats and I'm at the moment tearing out some of the functions just to make it work and will then be working to put the missing functions back in before PRing. At any rate, once this change is in 3.3.5, this will be irrelevant too.

I maintain the best solution is to just take from the pool (like retail does) and accept that the server needs to be restarted from time to time. Just like they do on retail anyway!

**Comment by MrSmite** [comment]
> Adding level into the store for used guids, would mean you now have to SEARCH for a free guid that matches your requirements rather than just pick one.

Not really, you could either create a std::list for each level or a new DB table where you just select from. I don't think processing time is of any concern considering there are a lot of things (eg: expiring auctions) that take a crap ton of cpu time.

> I maintain the best solution is to just take from the pool (like retail does) and accept that the server needs to be restarted from time to time. Just like they do on retail anyway!

Except they restart for patches, not to reset GUIDs. Considering the only issue in 335 is the levelup animation, I'd just assume leave it alone before adding the annoyance of forced server restarts. Either that or explore other ideas such as my suggestion.

**Comment by DDuarte** [comment]
Tying guids and levels is not a good idea, it's simply a terrible hack.
I don't like the forced restarts business either but it's unlikely those are hit before a crash/shutdown.

**Comment by Treeston** [comment]
Since creature entry is part of the GUID, why not have a simple counter for each creature entry that increments on each spawn, then use that counter for the GUID uniqueness part.

**Comment by Aokromes** [comment]
3.3.5a Client have far lower max guid.

**Comment by pete318** [comment]
I think there's two questions to ask. Did retail do this in 335? Will the client be fine with it. It sounds OK in theory though. 

One obvious problem is the extra lookup map needed for it.

**Comment by Treeston** [comment]
Napkin math says an array of uint32 indexed by creature entry, as crazy as it sounds, is only about 5mb of memory, and gives you constant time for r/w. Just tossing the idea out there.

PS: http://i.imgur.com/RPb0EwS.png - 3.3.5 GUID is 16 hex digits. Not sure what you meant by "far lower max guid".

**Comment by pete318** [comment]
Yeah I think the point about less in 3.3
5 was in comparison to 6.x where counter has 2^32 instead of 2^24 I believe. 

I think a map would do it. Remember it has to exist in each map instance. Then it only uses the entries actually in use. Bigger questions are if retail did it (need some lovely 3.3.5 sniffs to know) and of course whether the client would be happy with this. I suspect yes. But not sure.

**Comment by Treeston** [comment]
```
<Warpten> "Digits 4 through 5 are unused for NPCs. If really necessary, we can use these."
<Warpten> you can't
<Warpten> client will either ignore them (best case scenario) or crash (worst case)
<Treeston> so client actually only uses the lower half?
<Treeston> has anyone tested this
<Warpten> and im pretty sure it just ignores
<Aokromes> iirc Shauren said it crashes with guids ~17 millon
<Aokromes> (3.3.5a)
<Treeston> well, digits 6 through 10 are the entry
<Treeston> so if you have 17 million then you're exceeding the 6 lower half digits for spawn counter
<Treeston> what would need testing is whether the client actually ignores the two digits in the upper half that are unused on npcs
<Warpten> kinda 90% sure it does guid & 0x<appropriate mask>
<Treeston> and whether entry being different leads to guid being treated as different by client (even with identical spawn counters)
<Warpten> long time not opened 335 in ida tho
<Warpten> using the extra would be a nightmare
<Warpten> you have to do ((guid & extraMask) >> (whatever many)) | (guid & realMask)
<Warpten> i dont see any reason for that
<Warpten> iirc the "extra" part is realm identifier
<Malcrom> The only creatures that would casue an issue are high spawnrate quickly dying creatures
<Treeston> yeah
<Treeston> i was just tossing the idea out there
<Treeston> or we can assume that by the time spawn counter hits 16^6, the one with spawn counter 0 isn't alive anymore
<Treeston> and let it wrap around at that point
<Malcrom> We can assume that
<Warpten> depends on server entropy
<Warpten> number of players in world fucking around that is
<Treeston> if we have a seperate spawn counter per creature
<Treeston> given that each creature _typically_ only spawns in one given zone
<Treeston> and given that you pretty much need a high pop server to ever hit 16⁶ spawns on the same creature
<Malcrom> except for triggers
<Treeston> and even then if admins are afraid of the fringe case we can just make it a config toggle - auto idlerestart if approaching guid cap, auto restart if getting really close to guid cap
<Treeston> so if people are really that averse to doing a simple server restart that takes a few minutes tops during their off tz
<Treeston> they can live with the very unlikely fringe case scenarios of guid duplication being possible
<Treeston> we can even set a toggle to true when overflow _has_ happened on a creature and then do the (slightly more intensive) tests to see if that guid is already in use before spawning instead of just incrementing once and calling it a day
```

So it doesn't get lost to IRC scrollback.

**Comment by pete318** [comment]
Well. Give it a try. Pretty sure the weirdness would be instantly apparent if the client didn't like it.

**Comment by Aokromes** [comment]
This bug is still valid after @r00ty-tc's guids commit?

**Comment by Treeston** [comment]
Yes, and it won't be resolved until dynspawns is fully merged.

**Comment by Seyden** [comment]
whats about master???

**Comment by Treeston** [comment]
Master will get it once dynamic spawning is ported.
