### ISSUE TITLE
[6.x] Battle.Net Error 114

### ISSUE THREAD

**Issue by dejonxavier** [TrinityCore/TrinityCore#13863]
http://puu.sh/e9twb/cfa9ac604c.jpg

1/5 17:29:07.210  Login program=WoW platform=Win locale=enUS
1/5 17:29:07.243  Component WoW.Win.19342
1/5 17:29:07.256  Component WoW.base.19057
1/5 17:29:07.277  Battle.net is Component Bnet.Win.37165
1/5 17:29:07.290  LOGIN: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
1/5 17:29:07.536  Connecting to 198.100.154.224:1119
1/5 17:29:07.954  LOGIN: state: LOGIN_STATE_FAILED result: LOGIN_FAILED 
1/5 17:29:07.977  Disconnected from 198.100.154.224
1/5 17:29:07.992  Client initiated Disconnect from 198.100.154.224
1/5 17:29:08.011  Client initiated Disconnect from 198.100.154.224
1/5 17:29:08.026  LOGIN: state: LOGIN_STATE_FAILED result: LOGIN_FAILED 
1/5 17:29:08.046  Login program=WoW platform=Win locale=enUS
1/5 17:29:08.057  Component WoW.Win.19342
1/5 17:29:08.069  Component WoW.base.19057
1/5 17:29:08.087  Battle.net is Component Bnet.Win.37165
1/5 17:29:21.738  LOGIN: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
1/5 17:29:21.758  Connecting to 198.100.154.224:1119
1/5 17:29:22.638  LOGIN: state: LOGIN_STATE_FAILED result: LOGIN_FAILED 
1/5 17:29:22.680  Disconnected from 198.100.154.224
1/5 17:29:22.717  Client initiated Disconnect from 198.100.154.224
1/5 17:29:22.730  Client initiated Disconnect from 198.100.154.224
1/5 17:29:22.747  LOGIN: state: LOGIN_STATE_FAILED result: LOGIN_FAILED 
1/5 17:29:22.765  Login program=WoW platform=Win locale=enUS
1/5 17:29:22.777  Component WoW.Win.19342
1/5 17:29:22.790  Component WoW.base.19057
1/5 17:29:22.806  Battle.net is Component Bnet.Win.37165
1/5 17:30:45.588  LOGIN: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
1/5 17:30:45.616  Connecting to 198.100.154.224:1119
1/5 17:30:46.330  LOGIN: state: LOGIN_STATE_FAILED result: LOGIN_FAILED 
1/5 17:30:46.366  Disconnected from 198.100.154.224
1/5 17:30:46.379  Client initiated Disconnect from 198.100.154.224
1/5 17:30:46.379  Client initiated Disconnect from 198.100.154.224
1/5 17:30:46.405  LOGIN: state: LOGIN_STATE_FAILED result: LOGIN_FAILED 
1/5 17:30:46.415  Login program=WoW platform=Win locale=enUS
1/5 17:30:46.429  Component WoW.Win.19342
1/5 17:30:46.452  Component WoW.base.19057
1/5 17:30:46.480  Battle.net is Component Bnet.Win.37165

**Comment by Aokromes** [comment]
read 6.x thread.

**Comment by msoky** [comment]
Mini-guide for 6.x:
Change WTF/Config.wtf: SET portal "EU"
Get latest connection_patcher and move with mouse wow.exe or wow64.exe on it after log in to live/retail blizz acc to character section (to download modules). (without this you will get error 114 on login screen) Wow-64_Patched.exe was created
Change WTF/Config.wtf: SET portal "localhost"
Run Wow-64_Patched.exe
Login

**Comment by Walkum** [comment]
For MAC you need do the mini-guide all time that you open WoW... not fixed yet.

**Comment by Demigodess** [comment]
Is there anyone who can login at linux server? I can login to world only on windows, linux not...

**Comment by msoky** [comment]
i cant login on private server...but on localhost is everything fine
1/12 02:29:53.136  Login program=WoW platform=Win locale=enUS
1/12 02:29:53.182  Component WoW.Win.19342
1/12 02:29:53.211  Component WoW.base.19057
1/12 02:29:53.272  Battle.net is Component Bnet.Win.37165
1/12 02:29:53.303  LOGIN: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
1/12 02:29:53.333  Connecting to 93.91.144.187:8098
1/12 02:29:53.435  LOGIN: state: LOGIN_STATE_FAILED result: DISCONNECTED 
1/12 02:29:53.465  Login program=WoW platform=Win locale=enUS
1/12 02:29:53.494  Component WoW.Win.19342
1/12 02:29:53.523  Component WoW.base.19057
1/12 02:29:53.557  Battle.net is Component Bnet.Win.37165
1/12 02:29:53.582  Client initiated Disconnect from 93.91.144.187
1/12 02:29:53.614  Client Disconnect due to reason:8
1/12 02:29:53.648  Client initiated Disconnect from 93.91.144.187
1/12 02:30:06.963  LOGIN: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
1/12 02:30:07.049  Connecting to 93.91.144.187:8098
1/12 02:30:07.146  LOGIN: state: LOGIN_STATE_FAILED result: DISCONNECTED 
1/12 02:30:07.173  Login program=WoW platform=Win locale=enUS
1/12 02:30:07.203  Component WoW.Win.19342
1/12 02:30:07.231  Component WoW.base.19057
1/12 02:30:07.265  Battle.net is Component Bnet.Win.37165
1/12 02:30:07.290  Client initiated Disconnect from 93.91.144.187
1/12 02:30:07.322  Client Disconnect due to reason:8
1/12 02:30:07.348  Client initiated Disconnect from 93.91.144.187


Client Disconnect due to reason:8 ???

**Comment by msoky** [comment]
my mistake...fixed

**Comment by zedinke** [comment]
Hello! I have a little problem. 

I can't connect to my server. My server on VPS.

4/17 16:57:55.716  Login program=WoW platform=Win locale=enUS
4/17 16:57:55.748  Component WoW.Win.19865
4/17 16:57:55.779  Component WoW.base.19793
4/17 16:57:55.810  Battle.net is Component Bnet.Win.37165
4/17 16:57:55.826  LOGIN: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
4/17 16:57:55.888  Connecting to 89.185.248.233:1119
4/17 16:57:56.279  LOGIN: state: LOGIN_STATE_FAILED result: LOGIN_FAILED 
4/17 16:57:56.357  Disconnected from 89.185.248.233
4/17 16:57:56.435  Client initiated Disconnect from 89.185.248.233
4/17 16:57:56.576  Client initiated Disconnect from 89.185.248.233
4/17 16:57:56.654  LOGIN: state: LOGIN_STATE_FAILED result: LOGIN_FAILED 
4/17 16:57:56.669  Login program=WoW platform=Win locale=enUS
4/17 16:57:56.701  Component WoW.Win.19865
4/17 16:57:56.716  Component WoW.base.19793
4/17 16:57:56.748  Battle.net is Component Bnet.Win.37165

but my friend can connect to server. I no. Why? I send Wow_patched.exe to my friend and can connect to server.

My config.wtf:

SET portal "89.185.248.233"
SET textLocale "enUS"
SET audioLocale "enUS"



every port is default. DB is updated and latest.

**Comment by msoky** [comment]
have you tried SET portal "localhost" ??

**Comment by zedinke** [comment]
No. My server running on Remote VPS server. And my client on my computer.

**Comment by zedinke** [comment]
My computer only client.

**Comment by zedinke** [comment]
I am Hungarian. Country Problem? :/

**Comment by Aokromes** [comment]
He needs to run patcher on client pc, not enough with wow_patched.exe

**Comment by msoky** [comment]
everyone who want play must self run patcher on own pc? or send wow_patched.exe to someone is enough?

**Comment by Aokromes** [comment]
Like i said, patcher must be run on client pc, because patcher creates more files than wow_patched.exe on users directory.

**Comment by Maxxgold** [comment]
You can take your libeay32.dll and move it to a remote machine in the world of warcraft directory. Then run connection_patcher. Make sure to connect to retail character creation screen first. So, you can send the patcher and the lebay32.dll file and that will work, at least it did for me.
