### ISSUE TITLE
daily reset instance deadlocks

### ISSUE THREAD

**Issue by w1sht0l1v3** [TrinityCore/TrinityCore#14024]
daily instance reset fails as below:
http://paste2.org/_VfUbebK2
and second day:
http://paste2.org/_hfvOFWHc

for @jackpoz 

possibel relation to #9372

**Comment by jackpoz** [comment]
This is most likely because we call http://dev.mysql.com/doc/refman/5.0/en/mysql-errno.html to check if the transaction failed after we send ROLLBACK command, so the check at https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/shared/Database/Transaction.cpp#L80 is never true since the ROLLBACK command actually succeeded.

**Comment by jackpoz** [comment]
https://github.com/jackpoz/TrinityCore/commit/7583fe5802aeb8aaedef6d2f61058f5b9e80a56e this is a draft of the fix

**Comment by jackpoz** [comment]
fixed in https://github.com/TrinityCore/TrinityCore/commit/d4db0c15c7e59f7139619720be3c26a48e6ff259
