### ISSUE TITLE
[3.3.5][6.x] LFG Spell Dungeon Cooldown not cast on Random Lich King Heroic

### ISSUE THREAD

**Issue by jackpoz** [TrinityCore/TrinityCore#14155]
The check at https://github.com/TrinityCore/TrinityCore/blob/590693eb91261ad1758b80f614cb0375a97caae2/src/server/game/DungeonFinding/LFGMgr.cpp#L922 is always false because at that point dungeon->type is LFG_TYPE_HEROIC even if all 5 players selected Random Lich King Heroic when queued.
##

**Comment by Rushor** [comment]
since patch 3.3.3 the cooldown should NO longer be displayed as debuff http://www.wowhead.com/spell=71328/dungeon-cooldown.

source:
http://wowwiki.wikia.com/wiki/Patch_3.3.3
The Random Dungeon cooldown is no longer displayed as a debuff. Instead, players will see the cooldown time remaining displayed in the Dungeon Finder window when Random Dungeon or Random Heroic Dungeon is selected from the pull-down.

currently:
i'm not shure if this timer display is already implemented. maybe it needs some upates for the worldstate like the timer for wintergrasp.
However tc is curently on version <3.3.3 because we are still using the cooldown:
https://github.com/TrinityCore/TrinityCore/blob/478cc756eb05591f36857be3ffd1895684529710/src/server/game/DungeonFinding/LFGMgr.cpp#L429

https://youtu.be/J7PUv1zmgco?t=13
Here you can see (for 1 second) how the timer is displayed after the player entered the dungeon

**Comment by Shauren** [comment]
@Rushor except that auras can be hidden clientside with attributes :P

**Comment by Rushor** [comment]
yeah that would be the easy solution :D i'm curious if the timer in the interface works if the apply of the cooldownspell is fixed.

back to topic: do we actually get the cooldownspell if we chose a non Random Lich King Heroic? maybe someone can test this :)

**Comment by dr-j** [comment]
Well it works for dungeon deserter saying how long you must wait before you can queue again

**Comment by Rushor** [comment]
k nice, i will just remove the dungeon->type == random flag later to just test the cooldown displays with some player to give more infos on this

**Comment by Rushor** [comment]
kay forget all the stuff i mentioned above 
http://i.imgur.com/XXfWcsq.jpg

if you add the debuff with .cast 71328 everything works fine, no debuff in interface but correct display in db-interface

only fix which is needed:
LFG_TYPE_RANDOM must give back the correct value
