### ISSUE TITLE
[3.3.5][6.x] Guardians evade issue

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#14347]
rev. 68c4ea314443

After a combat or in_combat Guardians will loose all auras (harmful or not) this breaks many quests, for pets this issue doesn't happen.

**Comment by dr-j** [comment]
confirmed and the problem here is with evade mechanics as Ive bought up elsewhere before upon evade auras and unit flags of npc gets reset to default auras and flags for that npc.

But this causes problems where for some quests that require a spell to be cast on a npc that is meant to remain on the npc but the spell only causes npc to enter in combat for a fraction of a second and then evades causing auras to reset.

When I bought this up it was said this is how evade mechanics should work but was agreed not all creatures should reset on evade for all creatures as this causes problems when trying to script somethings

**Comment by dr-j** [comment]
other examples where this behavior causes problems are frenzyheart chickens when the net is thrown at them this should net them for a few seconds but on tc net is removed a split second after been cast to player did solve this with kind of a hack where the chicken recasts the net on self like 100 ms after spellhit to get around the evade problems.

Jenny for Load'er up when player starts quest player gets an aura which has 10 stacks when a player takes damage this is meant to remove stack(s) but on tc on evade the aura gets removed.

**Comment by MrSmite** [comment]
Similar to an Issue I reported back in 2013 ;) https://github.com/TrinityCore/TrinityCore/issues/11111

**Comment by Killyana** [comment]
For pets it seems like they never evade so the doesn't loose their auras, if I'm not wrong it must be the same thing for guardians.

**Comment by Rushor** [comment]
we could just add the fix from https://github.com/mik1893/TrinityCore/commit/c0942ef587809991d43322c116b332cd86d65512, but without the changes below https://github.com/mik1893/TrinityCore/commit/c0942ef587809991d43322c116b332cd86d65512#diff-4522eeffcbc961602e86620011a2d579R4048

Then all pets and guardians will not remove their auras on evade

**Comment by MrSmite** [comment]
So my original report https://github.com/TrinityCore/TrinityCore/issues/11111 was closed as dup to this and I see this is now closed due to a patch however this does not address the original issue I posted.

My issue is with NPCs, not guardians or pets. For example, if you run up and buff an NPC in westfall, while it is patrolling along the road, it will lose its buff after it fights something. This NPC is not a pet or guardian.

**Comment by tkrokli** [comment]
Maybe you could open up a new issue and post all relevant info from the old issue?

**Comment by Killyana** [comment]
@MrSmite the issue that are you talking about was fixed long time ago, auras that are set via creature_addon are applied after the reset, npcs looses all auras once that evade but on reset they load this auras.

**Comment by MrSmite** [comment]
> the issue that are you talking about was fixed long time ago, auras that are set via creature_addon are applied after the reset, npcs looses all auras once that evade but on reset they load this auras.

Are temporary auras cast by a player saved to creature_addon? I'm talking about casting a spell such as Blessing of MIght or Thorns on an NPC that is flagged PvP. When that NPC evades the aura is wiped.

**Comment by Killyana** [comment]
So it's an issue with the unit_flag.

**Comment by MrSmite** [comment]
> So it's an issue with the unit_flag.

Perhaps but wouldn't it be simpler to just not call *RemoveAllAurasExceptType()* unless the unit died?
