### ISSUE TITLE
[6.x] Disconnected when too much packets are sended

### ISSUE THREAD

**Issue by Walkum** [TrinityCore/TrinityCore#14404]
It's a supposition, but I think that when server send too much packets to the client, you are disconnected.

How to reproduce (various examples).

Example 1:
1. Get one character on GM island.
2. Teleport or use a Hearthstone to get Stormwind or Orgrimmar.
3. When teleport is finished, you are disconnected.
4. You will never be able to login again. Need to move the character to an empty or not much populated zone.

Example 2:
1. Change to a new spec.
2. Learn one spec and all talents.
3. Back to the other spec. You will be disconnected when changed.
4. You will be able to login again, but if changes the spec, will be disconnected again.

Rev. https://github.com/TrinityCore/TrinityCore/commit/2abcd4ef4625a9d06337a4ca91afb42d7d43becd

**Comment by DDuarte** [comment]
This is related to opcodes not being enabled, not flooding.

**Comment by Walkum** [comment]
Any idea which opcodes?

**Comment by Aokromes** [comment]
All the listed there.

**Comment by Walkum** [comment]
Interesting, but my question is unanswered yet.

**Comment by Shauren** [comment]
The answer for this lies in WorldSession::DosProtection - take a look at the switch there handling packets with exceptional allowed counters, you will see most of it is commented out (this is because when changing versions, all opcodes are set to 0xBADD and as you know, a switch cannot have two cases with the same value) to allow it to compile. What you can do is either uncomment opcodes that have value different than 0xBADD and submit a pull request for this or disable flood protection in worldserver config.

Most likely candidate for this is CMSG_GAMEOBJECT_QUERY

**Comment by jackpoz** [comment]
in particular https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/worldserver/worldserver.conf.dist#L3404 is the worldserver config

**Comment by Walkum** [comment]
Now I understand, thanks @Shauren.

**Comment by Aokromes** [comment]
Try after b2746dd19c984c195a11c320b834ffdc4d5beb8d

**Comment by Walkum** [comment]
Apparently fixed, can be closed. Thanks.
