### ISSUE TITLE
[6.x] Alter Time

### ISSUE THREAD

**Issue by IntelFreak** [TrinityCore/TrinityCore#14597]
Alter Time(108978) triggers a spell(110909) that applies SPELL_AURA_OVERRIDE_ACTION_BAR_SPELLS(332) which changes Alter Time with the override(127140).Everything works fine until you try to cast the override,it'll throw a spell is not ready yet error even though it has no cooldown.
I think it is checking for Alter Times cooldown instead of the override because if you learn it yourself you'll be able to cast it just fine.
Summary: The client replaces the spell but the server is still trying to cast Alter Time.

rev: 149ff8da879a8286a01081d4ffb1f200a67ddefd

**Comment by Boomper** [comment]
The problem is in Unit::GetCastSpellInfo,
when it goes through SPELL_AURA_OVERRIDE_ACTIONBAR_SPELLS (SAOAS from now on) and SAOAS_2 on unit it uses IsAffectingSpell(which uses SpellClassMasks) to determine which spell goes where...

Long story short: In Unit::GetCastSpellInfo if the SAOAS or SAOAS_2 has miscValueA it should only work for spell ID miscValueA and if the miscValueA is 0 it should keep doing what it does now.

**Comment by Aokromes** [comment]
eeaa78c
