### ISSUE TITLE
[3.3.5] Blood Mage Drazial buffing himself

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#14599]
Blood Mage Drazial is buffing itself not the player after completing his quests

http://www.wowhead.com/npc=7505/bloodmage-drazial

Tested on cb3fcea 2015-02-05
##

**Comment by Aokromes** [comment]
Plz update your core and database before reporting bugs.

**Comment by ikir83** [comment]
Tested on 2b95a5fe3562 2015-04-26

Drazial and his girlfriend Lynnore still buffing themselves after a quest is completed.

Lynnore
http://www.wowhead.com/npc=7506/bloodmage-lynnore

**Comment by ikir83** [comment]
![schermata 2015-05-01 alle 12 55 18](https://cloud.githubusercontent.com/assets/10136428/7440787/f6d24e56-f0c9-11e4-9475-a667eb693744.png)

**Comment by Rushor** [comment]
f.ex:
quest=2581

rewardspell: 10670

Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 25
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 29 (SPELL_AURA_MOD_STAT), value = 25, misc = 0 (UNIT_MOD_STAT_STRENGTH), miscB = 0, periodic = 0

**Comment by offl** [comment]
Looks like the problem is here:
https://github.com/TrinityCore/TrinityCore/blob/8e0af1b93bed87753e89aebefba3fbb085f40565/src/server/game/Entities/Player/Player.cpp#L15155-L15177
There's no `SPELL_EFFECT_APPLY_AURA` and also `&& !spellInfo->IsSelfCast()` limits creature to cast spells with `Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)` to player.

**Comment by Killyana** [comment]
Fixed somehow.
