### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#14606]
I get this on console

![image](https://cloud.githubusercontent.com/assets/4329612/7333570/7e084e44-eb74-11e4-844c-1dba5572d184.png)

a785f0d8978b962c94e561dfa233df808263ddb9

**Comment by Aokromes** [comment]
duplicate.

**Comment by Aokromes** [comment]
#13707

**Comment by ccrs** [comment]
its not written into DBError.log, thats why i opened this

**Comment by Killyana** [comment]
"spell_kargath_executioner" script don't exist on DB or core

**Comment by ccrs** [comment]
O.o

````sql
DELETE FROM `spell_script_names` WHERE `spell_id` IN (39288,39289,39290);
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(39288, 'spell_kargath_executioner'),
(39289, 'spell_kargath_executioner'),
(39290, 'spell_kargath_executioner');
````
from: 5e06ff20e88c49167ffed329bef794cb53eda0b2

**Comment by Killyana** [comment]
Ah authored 21 hours ago

**Comment by Killyana** [comment]
@MitchesD for you: https://github.com/TrinityCore/TrinityCore/commit/5e06ff20e88c49167ffed329bef794cb53eda0b2#diff-7a487f2b87151c55795b977d0f9ed365R453

**Comment by MitchesD** [comment]
summoning @ariel-

**Comment by ariel-** [comment]
I don't know, the error is misleading, since the script is properly executed despite the warning (checked with MSVC in debug mode); If I remove that script, the 'timer' debuff isn't removed after leaving the instance.

PS: see https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/Auras/SpellAuras.cpp#L1744
