### ISSUE TITLE
Prayer of Fortitude

### ISSUE THREAD

**Issue by Noffearr** [TrinityCore/TrinityCore#14646]
Is buggy or not?

http://wotlk.openwow.com/spell=48162

I do not understand much but I believe that this spell is in trouble because when I use my life increases'm really using the latest rev https://github.com/TrinityCore/TrinityCore/commit/09aed2565966c96d403afe44a0cce423c59cb4ec

Look Image

http://i.imgur.com/Wag49OV.jpg - I have the aura (Spell) HP 164 K

http://i.imgur.com/wj4TBn4.jpg - No have the aura (Spell) HP 66

It really is that correct? Sorry for the mistakes in English'm beginner in that language!

**Comment by Killyana** [comment]
Cannot reproduce, I tested all Prayer of Fortitude and Power Word: Fortitude, the aura always update the hp correctly.
rev. 5dba91f

**Comment by tkrokli** [comment]
TrinityCore rev. 5ef9f1415ad9 2015-04-29 23:16:12 +0100 (3.3.5 branch) (Win64, Release)
I just tested this, not a problem at all. 165 stamina was added to each of the 3 characters I used (paladin, rogue and hunter). Tested first on level 1, where you can read the difference quickly, since the numbers are so low, but I noted the total HP values anyway. At level 1, all characters got +165 stamina, but at level 80 the paladin got buffed with +180 stamina:

| class \ hp | unbuffed | buffed |    stamina   | level 80 | unbuffed | buffed |   stamina   |
| ------------ |:-------------:|:--------:| ---------------:|:-----------:|:----------------:|:------------:|:--------------:|
| Rogue     | 45             | 1695   |  20 + 165 | Rogue    |         8494   |      10144  | 107 + 165 |
| Paladin   |  48            |  1698   |   5 + 180  | Paladin |        8154    |       9804   | 125 + 180 |
| Hunter    | 66              |  1716  |  20 + 165 |   Hunter |         8404   |     10054    | 126 + 165 |

Something is a little strange about my paladin character , though. The stats say that unbuffed Stamina = 5 +15 (with +15 in green). Also, with more stamina than the other 2 at level 80, shouldn't it have the highest amount of HP? Maybe it is a Cache issue, one of the accounts see the other 2 undressed.

**Comment by Mack36** [comment]
@tkrokli It's because all classes have different amounts of basehp on each level (stored in table player_classlevelstats), e.g. pally has 6934 HP, a rogue has 7604 HP, and a hunter has 7324 HP on lvl 80.

**Comment by tkrokli** [comment]
OK, thanks for that extra info, but at least it goes to show that I can't reproduce the OP problem.
If your values are 100% correct and mine deviate, there must be some minor defect in my core/DB.
I'm currently compiling d74640aa7fdd944e7ba2e82966599e0ac8a7780b to see if I can get my values closer to yours. Update when I have tested.

**Comment by Noffearr** [comment]
I discovered the error friends, I updated the source but forgot to extract the dbc again after extracting everything went normally. Thanks for listening!

**Comment by tkrokli** [comment]
You're welcome. Maybe I should extract the dbc (+maps) once again, just to see if it makes a difference.
