### ISSUE TITLE
[6.x]Sql import

### ISSUE THREAD

**Issue by Dude100** [TrinityCore/TrinityCore#14640]
Database Auth is empty, auto populating it...
>> Applying '/home/dude/servers/TrinityCore/sql/base/auth_database.sql'...
>> Done!
Database Character is empty, auto populating it...
>> Applying '/home/dude/servers/TrinityCore/sql/base/characters_database.sql'...
>> Done!
Updating Auth database...
>> Auth database is up-to-date!
Updating Character database...
>> Applying update "2015_03_29_00_characters.sql" '95D6A46'...
>> Applying update "2015_04_21_00_characters.sql" 'F2032B9'...
>> Applying update "2015_04_28_00_characters.sql" '949F62D'...
ERROR 1054 (42S22) at line 19: Unknown column 'corpseGuid' in 'field list'
Applying of file '/home/dude/servers/TrinityCore/sql/updates/characters/2015_04_28_00_characters.sql' to database 'tcharacters' failed! If you are an user pull the latest revision from the repository. If you are a developer fix your sql query.

**Comment by Dude100** [comment]
http://pastebin.com/DbVdZ5hv

**Comment by tkrokli** [comment]
@Dude100 : you need to provide your core revision hash and TDB revision for this to be valid.

Pro tip: to make your first post show the text as it appeared in your output window, use ``` (3 back ticks,  Markdown code) on a blank line above your pasted text. Also add it after the paste if you want to write more regular text beneath it again.

**Comment by Dude100** [comment]
heh okay Linux dudu 3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt9-2 (2015-04-13) i686 GNU/Linux

Core last commit
database form here http://www.trinitycore.org/f/files/file/19-tdb-6-full/
 now see here http://pastebin.com/DbVdZ5hv

**Comment by tkrokli** [comment]
> Core last commit

There is no such thing as "last commit" since the core source is updated several times each day. This means that we are unable to tell which core you are actually using. The rest of the info looks OK, but it for the future, start any issue post with the TrinityCore revision hash and the rest like the info you provided.

Example from what I normally paste into any issue I start myself (using Windows) :
TrinityCore rev. 5ef9f1415ad9 2015-04-29 23:16:12 +0100 (3.3.5 branch) (Win64, Release)

**Comment by tkrokli** [comment]
Not sure if it is directly related bug-wise, you both got DB update issues, but don't provide core rev. hash :
**[6.x]World Update SQL Error** #14589
