### ISSUE TITLE
[6.x] Hunter's Trap

### ISSUE THREAD

**Issue by frozen4** [TrinityCore/TrinityCore#14660]
Build:  https://github.com/TrinityCore/TrinityCore/commit/f432821da6b8958b51cfe8ae61696e61bdf6e47c
DB: TDB 6.1.2

All the Trap of hunter is not available

1499    Freezing Trap
13809   Ice Trap
13813   Explosive Trap

I cast the spell  but it noting happend, I just Kneel there.

![hunters trap](https://cloud.githubusercontent.com/assets/106937/7487242/3cddeef4-f3e6-11e4-84df-27dbd76713cc.png)
##

**Comment by tristind** [comment]
Same with flare. Think its because Object::BuildMovementUpdate is outdated.

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by tkrokli** [comment]
TrinityCore rev. 1b1478b 2016-06-30 17:20:13 +0200 (6.x branch) (Win64, Release, Static)
TDB 6.04 plus updates up to and including `2016_06_28_01_world.sql`

Yes, the issue is still very much like in the OP description. I guess **frozen4** did not have any of the spell buttons on the action bar, but I had the ones for the Trap Launcher version of the spells, showing the 30 sec cooldown for all those 3 spells (freeze/ice separate from fire/explosion).

What I am more worried about is that using any of the trap launchers, they will crash worldserver instantly in Release build. I have only built in Release mode so far, but do you want me to build a debug version and check if I get the crash there too, then open a new issue for it? Or is this a known problem, with no need for a separate crash issue for the hunter traps launched from the hunter's weapon?
