### ISSUE TITLE
[6.x][Hunter] Spells and Autoshot = 0

### ISSUE THREAD

**Issue by martial69320** [TrinityCore/TrinityCore#14675]
TrinityCore revision is  : ad0cc83c8422 2015-05-10 00:32:59 -0400 (6.x branch)

I post a new issue because the damage on the automatic shot and spells are 0. I think it would come from Player.cpp but I'm not sure, not being developer.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by martial69320** [comment]
Why did you give me CONTRIBUTING link ? I'm not dev x)

**Comment by DDuarte** [comment]
@martial69320: read the Issues section of that file.

**Comment by martial69320** [comment]
In Core_Version, i'm getting: TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win32, Release)
And in Core_Revision: unknown. But i know i have Core version from 2015-10-05

**Comment by DDuarte** [comment]
Start by fixing that. Properly install Git in your system and run CMake.

http://www.trinitycore.org/f/topic/345-howto-properly-install-git-on-windows-fix-trinitycore-rev-1970-01-01-000000-0000/

**Comment by martial69320** [comment]
I'm redownloading sources

**Comment by martial69320** [comment]
TrinityCore revision is  : ad0cc83c8422 2015-05-10 00:32:59 -0400 (6.x branch)

**Comment by tkrokli** [comment]
Spells related to hunter's autoshoot/auto attack:
http://www.wowhead.com/spell=145759/auto-shot : Level 20 skill. Deals 30% weapon damage.
http://www.wowhead.com/spell=75/auto-shot : Level 1. Automatically shoots the target until cancelled.

Places to start looking:
https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/scripts/Spells/spell_hunter.cpp#L729
https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Spells/Spell.cpp#L651

Since the spells are used other places in the code, we need to determine the interacting code.

**Comment by martial69320** [comment]
Is it not in Player.cpp ?

**Comment by tkrokli** [comment]
If you search in 
https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Entities/Player/Player.cpp
you will find that there is no reference to hunters using Auto Shot, only pets, armor and focus regeneration, along with some other stats like crit, dodge and mastery.
