### ISSUE TITLE
Quest Massacre At Light's Point (Not Fixed)

### ISSUE THREAD

**Issue by Noffearr** [TrinityCore/TrinityCore#14679]
I do this quest and the cars do not appear to me to kill the mobs I am using the Rev https://github.com/TrinityCore/TrinityCore/commit/35497c479ffea02911b397f1e9353d66d4b0a889

http://www.wowhead.com/quest=12701/massacre-at-lights-point

Sorry for my mistake in english but I believe you understand what I mean! Thanks for listening!

**Comment by Noffearr** [comment]
Today I tested it with the latest update and even then the error was not fixed :-1:

**Comment by Rushor** [comment]
who said that the updates affect your problem, especially this quest?

**Comment by Noffearr** [comment]
I thought with the new updates would do this quest! More as I understand it does not work like that! Let's hope who can fix this quest and share in it!

**Comment by tkrokli** [comment]
TrinityCore rev. 5bd7c295c0b0 2015-05-13 22:29:49 +0200 (3.3.5 branch) (Win64, Release)

Cannot reproduce issue. @Noffearr explained to me in Skype that for him, the issue seems to be [Massacre At Light's Point](http://wotlk.openwow.com/quest=12701) and finding the [Mine Car](http://www.wowhead.com/npc=28821/mine-car) to get picked up by one of the peasants and towed to the ship before starting the massacre of the Scarlet Crusade forces on the beach.
Like I said, I can't reproduce this issue, it works as intended for me on 5bd7c295c0b0.

**Comment by Noffearr** [comment]
@tkrokli  Thank you for your support!
