### ISSUE TITLE
[6.x] Fear - Grey display

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#14714]
Hello,
After use fear, all spells are grey.
Fear sometimes stuns players.
example:
http://savepic.org/7304630.jpg
cast http://www.wowhead.com/spell=68950/fear
http://savepic.org/7284150.jpg
http://savepic.org/7332297.jpg

rev. https://github.com/TrinityCore/TrinityCore/commit/2678c52b1fb893a3bec92a0c1caaf167cc1554f1

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by tkrokli** [comment]
TrinityCore rev. 1b1478ba86ad 2016-06-30 17:20:13 +0200 (6.x branch) (Win64, Release, Static)
TDB 6.04 plus updates up to and including `2016_06_28_01_world.sql`

1. I think this issue is invalid in itself, because it is based on wrong spell info. Spell ID 68950 (http://www.wowhead.com/spell=68950/fear) is used by Bronjahm `<Godfather of Souls>` in Forge of Souls (http://www.wowhead.com/npc=36497/bronjahm) and can only target the player, not NPC (see the page http://www.wowhead.com/spell=68950/fear for description).

2. Spell 68950 and http://www.wowhead.com/spell=5782/fear (the **real** level 14 warlock spell Fear) does currently **not** have any effect in-game, only cast animation on the player character (but no spell visual on the target). The issue is therefore something else completely in 6.x and should be documented better in a new issue, including current status of spell script and auras for this.
