### ISSUE TITLE
[3.3.5] Ice Block cooldown not reset when joining arena

### ISSUE THREAD

**Issue by jackpoz** [TrinityCore/TrinityCore#14837]
Ice Block cooldown http://wotlk.openwow.com/spell=27619 is not reset after joining arena.
Reverting https://github.com/TrinityCore/TrinityCore/commit/a3bc75b7b96913eae3343bfde0390cf921748011 fixes the issue.

**Comment by jackpoz** [comment]
<= check doesn't check the cooldown of Ice Block spell itself, it might affect other related spells tho

**Comment by jackpoz** [comment]
the <= check doesn reset spells:
- 3680 Lesser Invisibility http://wotlk.openwow.com/spell=3680
- 11392 Invisibility http://wotlk.openwow.com/spell=11392
- 28500 Invisibility http://wotlk.openwow.com/spell=28500
- 29627 Nether Step http://wotlk.openwow.com/spell=29627

This is the list of all spells reset by both cases (< and <= )
- 64505 Dark Shield
- 5858 Dryad Camouflage
- 27619 Ice Block
- 9438 Arcane Bubble
- 45438 Ice Block
- 3648 Phase Out
- 19645 Anti-Magic Shield
- 7121 Anti-Magic Shield
- 63148 Divine Shield
- 3169 Invulnerability
- 41590 Ice Block
- 6523 Phase Out Passive
- 6724 Light of Elune
- 7383 Water Bubble
- 33581 Divine Shield
- 7870 Lesser Invisibility
- 9572 Onin's Camouflage
- 37538 Anti-Magic Shield
- 13007 Divine Protection
- 13874 Divine Shield
- 21892 Arcane Protection
- 24021 Anti-Magic Shield
- 29382 Divine Shield
- 34973 Ravandwyr's Ice Block
- 36527 Stasis
- 36911 Ice Block
- 38026 Viscous Shield
- 54166 Maker's Sanctuary
- 40733 Divine Shield
- 41367 Divine Shield
- 47922 Furyhammer's Immunity
- 74458 Power Shield XL-1
- 54322 Divine Shield

**Comment by jackpoz** [comment]
the 4 spells not reset have RecoveryTime: 0, CategoryRecoveryTime: 600000

**Comment by sirikfoll** [comment]
66233 Ardent defender should reset as well, isn't?

**Comment by ariel-** [comment]
Try:

```patch
 void Player::RemoveArenaSpellCooldowns(bool removeActivePetCooldowns)
 {
+    std::vector<uint32> categoriesCache;
     // remove cooldowns on spells that have < 10 min CD
-    GetSpellHistory()->ResetCooldowns([](SpellHistory::CooldownStorageType::iterator itr) -> bool
+    GetSpellHistory()->ResetCooldowns([&categoriesCache](SpellHistory::CooldownStorageType::iterator itr) -> bool
     {
         SpellInfo const* spellInfo = sSpellMgr->EnsureSpellInfo(itr->first);
-        return spellInfo->RecoveryTime < 10 * MINUTE * IN_MILLISECONDS && spellInfo->CategoryRecoveryTime < 10 * MINUTE * IN_MILLISECONDS;
+        if (spellInfo->RecoveryTime < 10 * MINUTE * IN_MILLISECONDS && spellInfo->CategoryRecoveryTime < 10 * MINUTE * IN_MILLISECONDS)
+        {
+            if (uint32 category = spellInfo->GetCategory())
+                categoriesCache.push_back(category);
+            return true;
+        }
+        return false;
     }, true);
 
+    for (uint32 category : categoriesCache)
+    {
+        GetSpellHistory()->ResetCooldowns([category](SpellHistory::CooldownStorageType::iterator itr) -> bool
+        {
+            return sSpellMgr->EnsureSpellInfo(itr->first)->GetCategory() == category;
+        }, true);
+    }
+
     // pet cooldowns
     if (removeActivePetCooldowns)
         if (Pet* pet = GetPet())
             pet->GetSpellHistory()->ResetAllCooldowns();
 }
```

**Comment by jackpoz** [comment]
@ariel- could you post a list of spells that your code affects ?

**Comment by Goatform** [comment]
Actually I tested same script without "new cooldown feature" which you implemented before few months and everything works well.

**Comment by ariel-** [comment]
http://wotlk.openwow.com/spell=42650

Army of the dead (10 min cooldown) should not be reset automatically by
this function, since the spell isn't usable in arenas.
The problem is the categorycooldown thing IMO, maybe remove this check
instead of having to iterate twice through the spell cooldowns?

2015-06-03 12:19 GMT-03:00 Goatform <notifications@github.com>:

**Comment by jackpoz** [comment]
Please make a PR with your patch with a list of all spells that you tested ingame and that are now working, compared to the previous not-working state.

Are you suggesting to restore the <= check for CategoryRecoveryTime only ?

**Comment by ariel-** [comment]
Don't know, is it correct to start cooldowns on every single spell of that category? The code IS resetting ice block Cooldown, but since OTHER spells with CategoryRecoveryTime >= 10 min still on cooldown, the spell shows unavailable clientside.

> - 3680 Lesser Invisibility http://wotlk.openwow.com/spell=3680
- 11392 Invisibility http://wotlk.openwow.com/spell=11392
- 28500 Invisibility http://wotlk.openwow.com/spell=28500
- 29627 Nether Step http://wotlk.openwow.com/spell=29627

> the 4 spells not reset have RecoveryTime: 0, CategoryRecoveryTime: 600000

Proposed fix above just stores temporarily the spell categories which correspond to every spell resetted, then manually resets every remaining spell cooldown belonging there, but my question is:
Is there a better (more efficient) way of achieving this WITHOUT reverting commit, which imho is correct?

Btw, list of spells with recoverytime >= 10 min is http://i.imgur.com/GkZWBNi.png
(I don't have my spell.dbc loaded into a db, would be nice to know how to output the data in easier way)

**Comment by jackpoz** [comment]
@DDuarte any feedback about this ? Should we revert and check the behavior with more time or apply the patch above (with std::set instead of std::vector) and hope for the best ?

**Comment by ariel-** [comment]
All in all, the only spell affected by revert would be.... Army of the Dead, will be reset but it'll still be unusable because of arena rules.

**Comment by Laintime** [comment]
no't fix,confirm https://github.com/TrinityCore/TrinityCore/commit/071ede8a93ab239e06c2ab338bc918791cb14b06

**Comment by jackpoz** [comment]
probably related to https://github.com/TrinityCore/TrinityCore/commit/ecbbcc8972f43376c65cb726c37cf777ee968f66 (that commit has already a comment about a typo) ?

**Comment by Shauren** [comment]
Works for me, even with the typo in ecbbcc8972f43376c65cb726c37cf777ee968f66 (it incorrectly allows casting spells, not blocks)
