### ISSUE TITLE
[6.x] All the DOT aura's tooltip's issues

### ISSUE THREAD

**Issue by frozen4** [TrinityCore/TrinityCore#14832]
Build: https://github.com/TrinityCore/TrinityCore/commit/fb4a9823c41b31158f6b5d68fc2ffc1608051984
DB: TDB 6.1.2

all the DOT aura's tooltip's value is 0 
For example the spell 172 [Corruption] 

Suffering $w2 Shadow damage every $t2 sec.
but it will show Suffering 0 Shadow damage every 5.20 sec.
##

**Comment by Frytiks** [comment]
The report https://github.com/TrinityCore/TrinityCore/issues/14825 related to this too maybe.

**Comment by DDuarte** [comment]
@frozen4: does the spell do 0 damage as well or only the tooltip is incorrecty displayed?

**Comment by Frytiks** [comment]
@DDuarte I can test, or jump on IRC and u say what u need test

**Comment by frozen4** [comment]
spell has damage
 spell do 253 damage  

only the tooltip is incorrecty displayed

**Comment by Sar777** [comment]
incorrect calculation CalculateAmount

**Comment by carlos93** [comment]
Sp coeff and AP coeff are taken on SpellDamageBonusDone instead of in CalculateAmount.

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by tkrokli** [comment]
TrinityCore rev. f663743 2016-06-18 16:23:55 +0200 (6.x branch) (Win64, Release, Static)
TDB 6.04 plus updates up to and including `2016_06_17_01_world.sql`

![warlock corruption debuff tooltip](https://cloud.githubusercontent.com/assets/4903600/16174226/9b8a82b2-35b9-11e6-9d0d-566b259ff19f.png)

So, yes. The issue is still valid, even if it is a cosmetic one.
