### ISSUE TITLE
[6.x] The client disconnects at 80% load (Windows 8.1)

### ISSUE THREAD

**Issue by Misimouse** [TrinityCore/TrinityCore#14961]
Hi.

I have no problem to compile and use the TrinityCore rev. 2ce76a25c324. I have compiled the server three times, I also reinstalled all database and installed all the updates. (three times) but the problem persists. I patched the wow.exe three times too. (Leaving the unpatched wow64) I have also disabled the antivirus , open ports on my router and firewall.

I have read the following posts:

http://community.trinitycore.org/topic/11031-client-connection-hang-at-around-80/
http://community.trinitycore.org/topic/11349-solvederror-received-not-handled-opcode/

And this Issues:

https://github.com/TrinityCore/TrinityCore/issues/14401

I can connect and create a character without any problem (Client 6.1.2 19865) but at 80% load before entering the world the client disconnects. 

I have some errors in the log to show here:

Prevented sending of [SMSG_SET_PROFICIENCY 0x0D75 (3445)] to non existent socket 1 to [Player: Account: 2] 
Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x1616 (5654)] from [Player: Account: 2]

**Comment by Aokromes** [comment]
You have open port 8086?

**Comment by Misimouse** [comment]
Yes

**Comment by DJScias** [comment]
**What's going on?!**
Your wow.exe is trying to make a connection to the version file that Blizzard is hosting on (I.E. for EU) http://EU.patch.battle.net:1119/wow/versions and the last few days this has made things go bad due to the 6.2.0 release.

From my personal experience the client will stop at 80% the moment you sever the connection to both the versions & cdns file and did some extra hex edits. This is the case with the wow.exe that some private servers distribute that 'supposedly' fix the 6.1.2 connection issue.

**How do I fix it?**
You have to do a few hex edits and self-host a certain file by blizzard to stop the 'initial setup' from happening.

**versions file**
Now, Blizzard's current version file looks like this:

    Region!STRING:0|BuildConfig!HEX:16|CDNConfig!HEX:16|BuildId!DEC:4|VersionsName!String:0
    us|0ad1f56e776f7af2a722aa140ffe683e|4546da1c08fce7b4ee547459ecc40f1c|20182|6.2.0.20182
    xx|0ad1f56e776f7af2a722aa140ffe683e|4546da1c08fce7b4ee547459ecc40f1c|20182|6.2.0.20182
    eu|0ad1f56e776f7af2a722aa140ffe683e|4546da1c08fce7b4ee547459ecc40f1c|20182|6.2.0.20182
    kr|0ad1f56e776f7af2a722aa140ffe683e|4546da1c08fce7b4ee547459ecc40f1c|20182|6.2.0.20182
    tw|0ad1f56e776f7af2a722aa140ffe683e|4546da1c08fce7b4ee547459ecc40f1c|20182|6.2.0.20182
    cn|0ad1f56e776f7af2a722aa140ffe683e|4546da1c08fce7b4ee547459ecc40f1c|20182|6.2.0.20182

Your client requests the info from this file and sees that the latest version is 6.2.0 which, if you're using standard TC binaries, is not equal to 6.1.2 and it will thus start the 'initial setup' thing which you seem to have already somehow circumvented.

Regardless, you'll need to self-host a changed form of this file somewhere (I will not link any due to the fact they are part of private servers). The updated form should be:  

    Region!STRING:0|BuildConfig!HEX:16|CDNConfig!HEX:16|BuildId!DEC:4|VersionsName!String:0
    us|c8e88fbc7aded52876069bcf33f28af9|ae7a03a3475bae8072f8047d71ff289b|19865|6.1.2.19865
    xx|c8e88fbc7aded52876069bcf33f28af9|ae7a03a3475bae8072f8047d71ff289b|19865|6.1.2.19865
    eu|c8e88fbc7aded52876069bcf33f28af9|ae7a03a3475bae8072f8047d71ff289b|19865|6.1.2.19865
    kr|c8e88fbc7aded52876069bcf33f28af9|ae7a03a3475bae8072f8047d71ff289b|19865|6.1.2.19865
    tw|c8e88fbc7aded52876069bcf33f28af9|ae7a03a3475bae8072f8047d71ff289b|19865|6.1.2.19865
    cn|c8e88fbc7aded52876069bcf33f28af9|ae7a03a3475bae8072f8047d71ff289b|19865|6.1.2.19865
Save the above in a file and self-host it somewhere.

**Self-hosting done, what now with my exes?**
Now drag your wow(-64).exe on the connection_patcher and get yourself a hex editing client (010 editor for example). Then follow the steps below depending on the .exe you patched.

**wow.exe**
Hex changes to make:
 1. Go to address `9A2470h` and change `68 74 74 70 3A 2F 2F 25 73 2E 70 61 74 63 68 2E 62 61 74 74 6C 65 2E 6E 65 74 3A 31 31 31 39 2F 25 73 2F 76 65 72 73 69 6F 6E 73 00` (http://%s.patch.battle.net:1119/%s/versions in text) to your self-hosted custom-created versions file link.
 2. **The new self-hosted custom link needs to be exactly the same size as the original versions link or your wow.exe will break. So be creative in the way you'll form your self-hosted version of this.**
 3. Save your wow.exe with the hex changes.

**wow-64.exe**
Hex changes to make:
 1. Go to address `F08F68h` and change `68 74 74 70 3A 2F 2F 25 73 2E 70 61 74 63 68 2E 62 61 74 74 6C 65 2E 6E 65 74 3A 31 31 31 39 2F 25 73 2F 76 65 72 73 69 6F 6E 73` (http://%s.patch.battle.net:1119/%s/versions in text) to your self-hosted custom-created versions file link.
 2. **The new self-hosted custom link needs to be exactly the same size as the original versions link or your wow.exe will break. So be creative in the way you'll form your self-hosted version of this.**
 3. Save your wow.exe with the hex changes.

**All done, what now?**
That's it. If you've self-hosted it and forced your wow(-64).exe's to sever the connection to the official 'versions' file then your client should just start up as normal (may take a small bit the first time) and afterwards you should be able to log in (& create a char if you haven't already) and then load into the world.

I hope it also works for you as it worked for me, I'm able to log in after doing these changes without having the 80% stuck & disconnect afterwards error.

Kind regards,
DJScias

**Comment by searum** [comment]
working, thanks @DJScias

**Comment by Carbenium** [comment]
Stay tuned. That will get really awsome ;)

**Comment by Aokromes** [comment]
7e906d7

**Comment by doriangray2** [comment]
works perfect !!!

**Comment by fallcons** [comment]
hi 
still doesn't work for me.. anyone can help me ? i can access to the caracter but not in game, i have the hosted file versions anyway this error is still here : 

Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x1616 (5654)] from [Player: <none> (Account: 6)]
Received not handled opcode [CMSG_LOG_STREAMING_ERROR 0x12D6 (4822)] from [Player: <none> (Logging in: GUID Full: 0x0800040000000000000000000000000D Type: Player Entry: 0 Low: 13, Account: 6)]

thx you for the help

**Comment by tkrokli** [comment]
@fallcons : the opcodes are there, but tagged as "unhandled", so the error message is sort of correct :
https://github.com/TrinityCore/TrinityCore/blob/ac9e8cc4d38208b352c5f8ae3dd0c4cf631c5326/src/server/game/Server/Protocol/Opcodes.cpp#L204
```cpp
DEFINE_HANDLER(CMSG_BATTLE_PAY_GET_PURCHASE_LIST,                       STATUS_UNHANDLED, PROCESS_INPLACE,      WorldPackets::Null, &WorldSession::Handle_NULL);
```
https://github.com/TrinityCore/TrinityCore/blob/ac9e8cc4d38208b352c5f8ae3dd0c4cf631c5326/src/server/game/Server/Protocol/Opcodes.cpp#L497

```cpp
DEFINE_HANDLER(CMSG_LOG_STREAMING_ERROR,                                STATUS_UNHANDLED, PROCESS_INPLACE,      WorldPackets::Null, &WorldSession::Handle_NULL);
```
Not sure what causes your issue, maybe some of the devs have got a relevant suggestion.
(By the way, you forgot to mention your core revision hash, so we don't know which build you are using.)

**Comment by fallcons** [comment]
yes sorry im using the core 6.1.2 19865 sorry i don't have the revision hash

**Comment by DDuarte** [comment]
@fallcons: we support 6.2.0, not 6.1.2

**Comment by fallcons** [comment]
yes but i want to stay at the 6.1.2

**Comment by DDuarte** [comment]
Dude.

**Comment by tkrokli** [comment]
Well, your core is no longer supported. You need to compile fresh source and use the 6.2.0 20338 client.

**Comment by fallcons** [comment]
it's work in 6.2.0 but i want to stay in 6.1.2 i have the core and the client, i just have this error..
