### ISSUE TITLE
Tools/ConnectionPatcher: Signature pattern changed (20201, mac only)

### ISSUE THREAD

**Issue by Carbenium** [TrinityCore/TrinityCore#15003]
rev. 7e906d7b1926394ba436315b7222b95f5473f79b

The signature pattern isn't found anymore since 20201.

**Comment by Razinao** [comment]
Signature patterns change from build to build.

I think the new signature file is at offset 204221, and is slightly longer than before:
45 31 F6 31 F6 31 D2 48 89 DF E8 20 89 FE FF 4D 89 E5 41 BC 04 00 00 00

**Comment by tefaye** [comment]
Is there any workaround available using the signature information above while we wait for a fix?

**Comment by Razinao** [comment]
I'm not too sure, since I've not fiddled with it yet, but you can probably just apply the same changes to the signature hex I gave that are done in the current patcher. A lot of it isn't important.

This is largely unsounded but just replacing the whole signature hex above with
41 B6 01 41 BF 02 00 00 00 90 90 90 90 90 90 90 90 90 90 90 90 90 90 90

**Comment by tefaye** [comment]
I gave it a go - no luck. Still unable to find pattern when patching signature.

It's possible the offset has changed again since your original comment. My client is 6.2.0 (20338) Jul 27th 2015

**Comment by Razinao** [comment]
You sure? I just picked it up at Offset 203E41 on a 20338 build.

**Comment by Carbenium** [comment]
@Razinao: you can't just add some NOPs. They intoduced a new variable which has to be set correctly to get that stuff working. Unfortunatly I don't have a mac and atm no access to someone else's.

**Comment by uptown1919** [comment]
Can anybody fix it?

**Comment by StormBytePP** [comment]
I think none of we use mac currently :(

**Comment by tkrokli** [comment]
You may want to browse #14689 to see who some of the most active users of OSX are, even though they are not considered real TC insider developers. They have just been more active than others, that's all.

**Comment by Walkum** [comment]
I use Mac... if need some research for get working this, tell me @Carbenium

**Comment by hankxemn** [comment]
When try patch WoW app says:
MacBook-Pro:build albertoricogarcia$ /Applications/Wow/connection_patcher /Applications/Wow/World\ of\ Warcraft.app 
Creating patched binary...
EX: Type: 0 not supported!

**Comment by Carbenium** [comment]
@hankxemn: this has nothing to do with this issue. If you are sure that the problem isn't on your side, please open a new ticket. Hence I deleted your comment to keep this issue clean.

**Comment by shinzon** [comment]
Does anyone have a (working) copy of the Mac OSX ConnectionPatcher they can provide for me? I did my build on Windows 10 but I want to enable two of my mac workstations to connect to my 6.x server. Would really prefer not to have to get into having to do a full build on mac if I can prevent it, only because I have no experience doing builds on Macs.

**Comment by Rudi9719** [comment]
I have a WoW_Patched for OS X however it's having [this issue](https://github.com/TrinityCore/TrinityCore/issues/16872) and crashes instantly. What version WoW do you have?

**Comment by Shauren** [comment]
Stop commenting on old and outdated issues - patch 6.2.4 changed all patterns/patches dealing with bnet
