### ISSUE TITLE
SQLQueryHolder have memory leak

### ISSUE THREAD

**Issue by dyf303** [TrinityCore/TrinityCore#15017]
I use the  Visual  Leak Detector detect the memory leak in SQLQueryHolder.The m_queries[index].second.presult not free;

**Comment by jackpoz** [comment]
when you clicked on "New Issue" https://github.com/TrinityCore/TrinityCore/issues/new some text appeared on top
>Please review the guidelines for contributing to this repository.

As the text says, please review the guidelines before posting an issue to provide all required informations.

Since you are referring to a particular code section you might want to post the filename and line too, even better if it's a github link.

According to many valgrind runs with --leak-check=full there are currently no memory leaks in a basic usage (logging, creating characters, casting spells, playing bg's, doing a random instance run)

**Comment by jackpoz** [comment]
most likely related to https://github.com/TrinityCore/TrinityCore/issues/15000

**Comment by jackpoz** [comment]
@dyf303 any follow up to https://github.com/TrinityCore/TrinityCore/issues/15017#issuecomment-118758501 ?

**Comment by Aokromes** [comment]
No answer after months, closing.
