### ISSUE TITLE
the instruction at XXXX referenced memory at XXXX. the memory could not be read

### ISSUE THREAD

**Issue by YaGa** [TrinityCore/TrinityCore#15062]
rev. b5c5442d039f12bb114aa48c75c04c55d55ae854

This error appears randomly since, a year ago I think. The server does not crash but this Windows Error Message appears and this is really annoying. Do you know a fix for this?

**Comment by DDuarte** [comment]
I've never seen this happen on Windows. How does one reproduce this issue?

**Comment by tkrokli** [comment]
@YaGa : if you get the error message `the memory could not be read` , you should look into the probability that your Windows setup is unstable and needs fixing or reinstalling. Especially since the 6.x branch did not exist a year ago and you need some consistency in the source for this to be a likely source issue. Even so, a proper crash log from a source compiled in Debug mode is needed too.

If you get any closer to linking this problem to **very recent** source, discuss it in the TrinityCore Forum first: http://community.trinitycore.org/
