### ISSUE TITLE
[3.3.5][DB] Wrong Hearthglen Crusader spawns in Death Knight starting zone

### ISSUE THREAD

**Issue by StormBytePP** [TrinityCore/TrinityCore#15083]
I did again the quest initial chains to fully create a Death Knight. While it can be created, I noticed a series of wrong spawns that makes progress very annoying, as the target creatures (hostile) appear too close to the area where questgivers are. Furthermore, in retail, I don't remember those Hearthglen Crusader NPCs to be so close.

First little explanation on how to reproduce:
This starts to happen when you take quest "The Scarlet Apocalypse" (ID 12778), and you go to Death's Breach in gryphon to see the Lich king. You immediatelly get aggro from them, and will continue on the next quest in chain: "An End To All Things..." (ID 12779) in which you are told to kill that type of NPC.

I killed them, and did a .npc info on all of them to grab their guids. Since they are not there in retail, and they are pretty annoying, what I did is just to remove their spawns, which is also my proposed solution here.

``` sql
DELETE FROM creature WHERE guid IN ( 130567, 130570, 130574, 130602, 130608, 130658, 130721, 130722, 130733, 130743, 130792, 130793, 130815 );
DELETE FROM creature_addon WHERE guid IN ( 130567, 130570, 130574, 130602, 130608, 130658, 130721, 130722, 130733, 130743, 130792, 130793, 130815 );
```

(Edited, since I did not realized it also had data inside creature_addon)

TC rev: af8e9738036e
TDB: 335.58 (with updates enabled in config file)

**Comment by tkrokli** [comment]
:smiley: Thank you for posting this! :+1: That exact issue has bothered me and my associates for so long! :angry:

I really hope to see this confirmed from sniffs by one of the main TC developers.

**Comment by StormBytePP** [comment]
Edited OP, to reflect a new SQL query

**Comment by Exodius** [comment]
If I am not mistaken, there is a phase transition between those two quests. Are you sure it's not the issue of them being in both phases rather than one instead of them being duplicate spawns?

**Comment by tkrokli** [comment]
The main and important phase transition happens when you (as the DK character) accept quest 12778 "The Scarlet Apocalypse" from Darion Mograine inside Acherus: The Ebon Hold. This spawns all the Tirisfal Crusader elite NPCs with long range targeting and high damage artillery (ballista level damage), able to kill the player in 5-7 hits. This is very likely to happen, since the Tirisfal Crusaders got enough range (200-250 yards) to target you when you are flying on the Frostwyrm, as well as half way across Death's Breach. This keeps you covered from both sides, since there is 1 group on each ramp to the plateau.

While it is correct that the hostile NPCs should have a very long target range and high damage ranged weapons to fire upon the Frostwyrm vehicle you get from quest 12779 "An End To All Things...", the NPCs should either be continuously engaged in fighting with the Ebon Hold NPCs defending the plateau or be placed further downhill so they won't target the player so easily when landing directly beneath the Acherus (or even be able to fire upon you when you stand next to the Lich King to deliver quest 12778 and receive quest 12779. Let me show you a few pictures from this sequence:

Accepting the quest from Darion Mograine:
![1_quest_presented](https://cloud.githubusercontent.com/assets/4903600/8722852/186cb8dc-2bc9-11e5-8752-0500d54c7ff4.jpg)

Flying down from Acherus: The Ebon Hold down to Death's Breach:
![2_flying_down](https://cloud.githubusercontent.com/assets/4903600/8723004/8aae3f8c-2bca-11e5-8cfc-d8642bfc0e99.jpg)

Getting aggro directly when landing because the Death Knight Champions are dead on this side:
![3_targeted_on_landing](https://cloud.githubusercontent.com/assets/4903600/8723020/bb95df10-2bca-11e5-928d-ff86f28085d8.jpg)

Dying from 6 - 7 hits, each hit ≈ 500 dmg, player hp ≈ 3500. DKC defenders should be alive at this point:
![4_npc_defenders_dead_and_player_killed](https://cloud.githubusercontent.com/assets/4903600/8723093/4f8a32e8-2bcb-11e5-9a2b-863313489bd6.jpg)

Revived and ran to the Lich King's stand to deliver Q 12778 and receive Q 12779. Died again:
![5_dead_at_quest_delivery_to_lk](https://cloud.githubusercontent.com/assets/4903600/8723494/609353d2-2bce-11e5-934d-9bcaaaba440d.jpg)

**Comment by StormBytePP** [comment]
Thanks tkrokli, you explained it far better than me.
In fact, in retail they do not appear so close, because you should be able to take the quest at least without being killed/attacked, that is why I proposed just to remove the group which is too close.

**Comment by tkrokli** [comment]
Another difference I noticed while doing this, is that the fighting on the ramps is unbalanced. On the nearest ramp, the Tirisfal Crusaders kill the Death Knight Champions too soon, not so on the other side. Entering cheat mode/God mode (just to be on the safe side), I inspected the Death Knight Champions :

![6_checking_other_ramp](https://cloud.githubusercontent.com/assets/4903600/8738800/877b8b34-2c34-11e5-951b-49ada1b4e54a.jpg)

If these events were flipped, it might be less of a problem for the player, though I am not sure about the target range from the southwest ramp when player reaches the Lich King's podium. (It was just a thought.)

If the target here is to make it as blizzlike as possible, we should check the sniffs from retail. I don't know if there has been much change to the NPC placing in this area through the last 3 expansions (I hope not).

**Comment by Exodius** [comment]
@StormBytePP either we misunderstood each other or I did not explain it like I wanted. Phase transition between the two quests works fine. I was just asking if phasemask on creatures is wrong making them exist in two phases rather than one. I don't have anything set up on my PC currently and, quite frankly, I don't have the time to test things myself. I don't even have the time to test this on retail.

**Comment by tkrokli** [comment]
@Exodius I may have misunderstood your question as well, since I thought it would be obvious that the current phasing takes place like it is supposed to do. Upon re-reading your previous comment, I find that I have no actual idea if the hostile NPCs (or even the friendly ones, the Champions) are supposed to be spawned *before* or *after* Quest 12779 "An End To All Things..." is accepted. Do you think it would be possible to create a DK on retail if I use a trial account and apply for PTR access to check it out?

**Comment by StormBytePP** [comment]
Any updates in this issue? I mean, confirmed with sniffs? Or do you need more sniffs on this issue?

**Comment by tkrokli** [comment]
Sorry, I have not had time neither to try getting a PTR account nor do anything about sniffs, because sniffs are mostly beyond my current skills. Been too busy lately, both IRL and in some forums.

**Comment by Trisjdc** [comment]
That Flaming Arrow Assault spells that the Hearthglen Crusaders use shouldn't be used on ground units, only on the Frostwyrm the player has during 'An End To All Things...'.
Because they're using ArcherAI, they have an aggro range equal to the range of that spell, which is 150 yards

That whole phase has quite a lot of problems

**Comment by tkrokli** [comment]
Thanks for the update, @Trisjdc. If it is possible to single out the Hearthglen / Tirisfal Crusaders on both ramps, from the other crusaders in the rest of the Scarlet Enclave, then remove the ArcherAI from these NPCs, that would make it possible to deliver quest 12778 and receive quest 12779 without the overpowered ranged attacks on the player. I still don't know if that is what happens on retail, though.

**Comment by ccrs** [comment]
why erasing ArcherAI? just add conditions to the spell

**Comment by StormBytePP** [comment]
Can some dev review the sniff about that that is present in the forum in order to see what happens to those creatures I mention here?

**Comment by tkrokli** [comment]
It would certainly be interesting to hear if the Hearthglen / Tirisfal Crusaders are spawned correctly, if the number of NPCs is correct or if they should have limitations like not targeting the player when landing.

**Comment by Killyana** [comment]
I found 2 sniffs for this npcs, the first one probably used to make the spawn as coords are almost the same, the second is a little bit different, they are just 3 yards far from the actual positions on TC.
So the unique solution is to create a new DK on retail and check. Also according to some videos the attack range is lower than the one on TC (archer range)

**Comment by tkrokli** [comment]
Nice. At least we get a reprieve from the Arrow Assault attacks. That is a bit of progress. 👍
