### ISSUE TITLE
[3.3.5] [Minor] Sound missing when mounting Death Knight's Acherus Deathcharger

### ISSUE THREAD

**Issue by StormBytePP** [TrinityCore/TrinityCore#15081]
The default mount for Death Knight class, should enable a whinny sound at the end of casting as a result of the horse to appear, but instead "normal" end casting sound seems to appear.

This is a minor issue, but if it can be fixed it would be great, as that whinny sound is fantastic :)

EDIT: TC revision af8e9738036e
TDB: 335.58 with auto updates applied in config

**Comment by tkrokli** [comment]
Check your sound settings. I have to turn down the volume each time I play on a Death Knight character, because on all my 3.3.5 compiles, I get the "screaming" whinnying sound from the Death Charger, in addition to the spell sound. Too loud when using headphones (ouch).

TrinityCore rev. 5bbd7cff4c98 2015-07-11 00:30:08 +0200 (3.3.5 branch) (Win64, Release)
Unable to reproduce your issue, even if it would have been a very useful alternative for me.

**Comment by StormBytePP** [comment]
Hmmm, for some reason, I closed wow, and restarted and it worked again. Sorry for reporting, it appeared strange to me, but it is definitelly working. Not related to volume low, something happened which solved itself on game restart.

**Comment by tkrokli** [comment]
File it under "game client issues" (not a TC issue). :stuck_out_tongue_winking_eye:
