### ISSUE TITLE
Core/movements: Flying Npcs doesn't change movement from fly to walk once in the ground

### ISSUE THREAD

**Issue by Warforged** [TrinityCore/TrinityCore#15360]
The NPC ID 36725 Nerub'ar Broodkeeper "http://www.wowhead.com/npc=36725/nerubar-broodkeeper" has incorrect movement in ICC Raid it goes underneath the map when flying from down to the ground or trying to spawn the NPC has the same effect shown in image. It should be facing up on it legs. Compiled and tested on rev 4c420344fc4c8508b2142a5031d9bf8b16c0e7fd
![15f12164-3edf-11e5-97e2-5c2199ddf4ff](https://cloud.githubusercontent.com/assets/13994692/9515156/627d000c-4c54-11e5-8e41-8acab4facbda.jpg)
Close issue #15247

**Comment by emptyus** [comment]
I think there is also a problem with creatures from liquids. I would have to check it, but atm I can't do it. I remember that in all cases, where you aggro a creature, that is able to swim and walk on land, and that creature is in liquid and you on land while aggroing, upon creature exit from liquid it will move very slowly toward you, as if it was still in liquid. I have observed its movement on land, when it was not aggroed, due its path/random movement, and it would change the speed "properly" (I don't really know how exactly its supposed to be on retail, but it seams logical it moves faster on ground than in liquids, as do the players). Now, I don't remember if animation is wrong also since I can recall only some turtles or elementals, not humanoids, and the animation of them swimming isn't catchy to an eye. If someone can confirm would be neat.

**Comment by malcrom** [comment]
inhabit type is the issue. It's not implemented properly.

**Comment by Golrag** [comment]
The reason why they "look down" is because bytes_1 is set to make him look like this, just missing script :p

How it should be:
You walk in an area trigger: some spiders come down, when they are they are on the ground or enter combat, they stop "moving down" en bytes_1 gets removed.

**Comment by Killyana** [comment]
It's bytes1=33554432 = Hover mode, it always disable gravity even if the npc is on the floor.
