### ISSUE TITLE
[ROGUE] Eviscerate

### ISSUE THREAD

**Issue by click** [TrinityCore/TrinityCore#154]
What steps will reproduce the problem?
1.Place instant poison on both of your weapons (im using axes)
2.Hit your target with 2-3 sinister strikes
3.Use Eviscerate

What is the expected output? What do you see instead?

Eviscerate (mine is rank 4) should do 85-123 dmg with 2 combo points but it does alot less. About 66 dmg. Does normal dmg without poisons. Did 86 dmg

What revision of the Core are you using? On what operating system?

Core revision: Trinity Core 10767 Operating System: Ubuntu 10.04 x64

**Comment by ariel-** [comment]
Propose re-opening of this issue.
Apparently it was stealth-fixed in some patch, and the DBC data is wrong. Having a variable-AP scaling is weird, as maybe you can have a crit that has less AP than a normal hit and does less damage overall.

I think the *real* scaling is 0.07 of AP per combo point *fixed scaling*.

Sources:
DrDamage v1.7.8_release : Rogue.lua lines 357-372:

```lua
		[GetSpellInfo(2098)] = {
			["Name"] = "Eviscerate",
			[0] = { ComboPoints = true, --[[APBonus = { 0.03, 0.06, 0.09, 0.12, 0.15 },--]] APBonus = { 0.07, 0.14, 0.21, 0.28, 0.35 } },
			[1] = { 6, 10, PerCombo = 5 },
			[2] = { 14, 22, PerCombo = 11 },
			[3] = { 25, 39, PerCombo = 19 },
			[4] = { 41, 61, PerCombo = 31 },
			[5] = { 60, 90, PerCombo = 45 },
			[6] = { 93, 137, PerCombo = 71 },
			[7] = { 144, 212, PerCombo = 110 },
			[8] = { 199, 295, PerCombo = 151 },
			[9] = { 224, 332, PerCombo = 170 },
			[10] = { 245, 365, PerCombo = 185 },
			[11] = { 405, 613, PerCombo = 301 },
			[12] = { 497, 751, PerCombo = 370 },
		},
```

Aldriana's Combat Spreadsheet v1.5.2 "Calcs" hidden sheet, 972 row "N pt Eviscerate Base Damage":
```
=(254+(370+0,07*B790)*B486)*(1+0,2/3*ImpEvis+0,03*Aggression)
```

Where 254 is average base damage of Rank 12 Eviscerate (ID - 48668)
Effect 0: Id 2 (SPELL_EFFECT_SCHOOL_DAMAGE)
BasePoints = 127 to 382 + combo * 370,00

( 127 + 381) / 2  = 254

370 is combo multiplier
B790 is AP
B486 is N combos ("Optimal Evis Size", calculated as 5)

The other multiplier term factors in talents Improved Eviscerate and Aggression to add to total calculated damage.


After this analysis, I think the true formula should be
```c++
                else if (m_spellInfo->SpellFamilyFlags[0] & 0x00020000)
                {
                    if (Player* player = m_caster->ToPlayer())
                    {
                        if (uint32 combo = player->GetComboPoints())
                        {
                            float ap = m_caster->GetTotalAttackPowerValue(BASE_ATTACK);
                            damage += int32(ap * combo * 0.07f);

                            // Eviscerate and Envenom Bonus Damage (item set effect)
                            if (m_caster->HasAura(37169))
                                damage += combo*40;
                        }
                    }
                }
```

**Comment by BahDumbBugs** [comment]
This is 3.x, right?

**Comment by tkrokli** [comment]
Yes, otherwise it would be labeled [4.3.4] a few years ago, to keep it separate from master / 3.3.5.
