### ISSUE TITLE
[6.x] fix drop npc Apothecary Furrows

### ISSUE THREAD

**Issue by thomas33** [TrinityCore/TrinityCore#15429]
rev: 8652f4b

```sql
UPDATE `creature_template` SET lootid=33980 WHERE entry=33980;
DELETE FROM `creature_loot_template` WHERE entry=33980;
INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES
(33980, 727, 0, 0.24, 0, 1, 1, 1, 1, Notched Shortsword),
(33980, 818, 0, 0.46, 0, 1, 1, 1, 1, Tigerseye),
(33980, 856, 0, 0.06, 0, 1, 1, 1, 1, Blue Leather Bag),
(33980, 858, 0, 2.06, 0, 1, 1, 1, 1, Lesser Healing Potion),
(33980, 1179, 0, 2.78, 0, 1, 1, 1, 1, Ice Cold Milk),
(33980, 1210, 0, 0.18, 0, 1, 1, 1, 1, Shadowgem),
(33980, 1495, 0, 0.23, 0, 1, 1, 1, 1, Calico Shoes),
(33980, 1497, 0, 0.2, 0, 1, 1, 1, 1, Calico Cloak),
(33980, 1498, 0, 0.4, 0, 1, 1, 1, 1, Calico Gloves),
(33980, 1499, 0, 0.32, 0, 1, 1, 1, 1, Calico Pants),
(33980, 1500, 1, 0.28, 0, 1, 1, 1, 1, Calico Tunic),
(33980, 1502, 0, 0.31, 0, 1, 1, 1, 1, Warped Leather Belt),
(33980, 1503, 0, 0.31, 0, 1, 1, 1, 1, Warped Leather Boots),
(33980, 1504, 0, 0.62, 0, 1, 1, 1, 1, Warped Leather Bracers),
(33980, 1506, 0, 0.24, 0, 1, 1, 1, 1, Warped Leather Gloves),
(33980, 1507, 0, 0.24, 0, 1, 1, 1, 1, Warped Leather Pants),
(33980, 1509, 0, 0.22, 0, 1, 1, 1, 1, Warped Leather Vest),
(33980, 1510, 0, 0.38, 0, 1, 1, 1, 1, Heavy Hammer),
(33980, 1510, 1, 0.33, 0, 1, 1, 1, 1, Commoner''s Sword),
(33980, 1512, 0, 0.21, 0, 1, 1, 1, 1, Crude Battle Axe),
(33980, 1513, 0, 0.41, 0, 1, 1, 1, 1, Old Greatsword),
(33980, 1514, 0, 0.32, 0, 1, 1, 1, 1, Rusty Warhammer),
(33980, 1515, 0, 0.39, 0, 1, 1, 1, 1, Rough Wooden Staff),
(33980, 1516, 0, 0.42, 0, 1, 1, 1, 1, Worn Hatchet),
(33980, 1730, 0, 0.2, 0, 1, 1, 1, 1, Worn Mail Belt),
(33980, 1730, 1, 0.16, 0, 1, 1, 1, 1, Worn Mail Boots),
(33980, 1732, 0, 0.24, 0, 1, 1, 1, 1, Worn Mail Bracers),
(33980, 1734, 0, 0.26, 0, 1, 1, 1, 1, Worn Mail Gloves),
(33980, 1735, 0, 0.22, 0, 1, 1, 1, 1, Worn Mail Pants),
(33980, 1737, 0, 0.26, 0, 1, 1, 1, 1, Worn Mail Vest),
(33980, 2075, 0, 0.09, 0, 1, 1, 1, 1, Heavy Mace),
(33980, 2140, 0, 0.14, 0, 1, 1, 1, 1, Carving Knife),
(33980, 2214, 0, 0.26, 0, 1, 1, 1, 1, Wooden Buckler),
(33980, 2215, 0, 0.28, 0, 1, 1, 1, 1, Wooden Shield),
(33980, 2407, 0, 0.05, 0, 1, 1, 1, 1, Pattern: White Leather Jerkin),
(33980, 2455, 0, 0.9, 0, 1, 1, 1, 1, Minor Mana Potion),
(33980, 2589, 0, 55.47, 0, 1, 1, 1, 3, Linen Cloth),
(33980, 2657, 0, 0.08, 0, 1, 1, 1, 1, Red Leather Bag),
(33980, 2763, 0, 0.31, 0, 1, 1, 1, 1, Fisherman Knife),
(33980, 2777, 0, 0.45, 0, 1, 1, 1, 1, Feeble Shortbow),
(33980, 2778, 0, 0.4, 0, 1, 1, 1, 1, Cheap Blunderbuss),
(33980, 3192, 0, 0.12, 0, 1, 1, 1, 1, Short Bastard Sword),
(33980, 3280, 1, 0.17, 0, 1, 1, 1, 1, Battle Chain Gloves),
(33980, 3282, 0, 0.07, 0, 1, 1, 1, 1, Battle Chain Pants),
(33980, 3283, 0, 0.04, 0, 1, 1, 1, 1, Battle Chain Tunic),
(33980, 3285, 0, 0.13, 0, 1, 1, 1, 1, Tribal Bracers),
(33980, 3286, 0, 0.07, 0, 1, 1, 1, 1, Tribal Gloves),
(33980, 3288, 0, 0.07, 0, 1, 1, 1, 1, Tribal Vest),
(33980, 3289, 0, 0.24, 0, 1, 1, 1, 1, Ancestral Boots),
(33980, 3290, 0, 0.1, 0, 1, 1, 1, 1, Ancestral Gloves),
(33980, 3374, 0, 0.26, 0, 1, 1, 1, 1, Calico Belt),
(33980, 3375, 0, 0.21, 0, 1, 1, 1, 1, Calico Bracers),
(33980, 3609, 0, 0.05, 0, 1, 1, 1, 1, Plans: Copper Chain Vest),
(33980, 3644, 0, 0.05, 0, 1, 1, 1, 1, Barbaric Cloth Bracers),
(33980, 3649, 0, 0.06, 0, 1, 1, 1, 1, Tribal Buckler),
(33980, 4560, 1, 0.26, 0, 1, 1, 1, 1, Scalping Tomahawk),
(33980, 4562, 0, 0.12, 0, 1, 1, 1, 1, Severing Axe),
(33980, 4566, 0, 0.06, 0, 1, 1, 1, 1, Sturdy Quarterstaff),
(33980, 4569, 0, 0.04, 0, 1, 1, 1, 1, Staunch Hammer),
(33980, 4605, 0, 6.99, 0, 1, 1, 1, 1, Red-Speckled Mushroom),
(33980, 4669, 0, 0.07, 0, 1, 1, 1, 1, Battle Chain Girdle),
(33980, 4672, 0, 0.21, 0, 1, 1, 1, 1, Ancestral Belt),
(33980, 4675, 0, 0.07, 0, 1, 1, 1, 1, Tribal Belt),
(33980, 4680, 0, 0.06, 0, 1, 1, 1, 1, Brackwater Cloak),
(33980, 4686, 0, 0.05, 0, 1, 1, 1, 1, Barbaric Cloth Cloak),
(33980, 4692, 0, 0.04, 0, 1, 1, 1, 1, Ceremonial Cloak),
(33980, 4693, 0, 0.06, 0, 1, 1, 1, 1, Ceremonial Leather Belt),
(33980, 5574, 0, 0.05, 0, 1, 1, 1, 1, White Leather Bag),
(33980, 8178, 0, 0.18, 0, 1, 1, 1, 1, Training Sword),
(33980, 8180, 0, 0.25, 0, 1, 1, 1, 1, Hunting Bow),
(33980, 14086, 0, 0.06, 0, 1, 1, 1, 1, Beaded Sandals),
(33980, 14089, 0, 0.13, 0, 1, 1, 1, 1, Beaded Gloves),
(33980, 14090, 0, 0.24, 0, 1, 1, 1, 1, Beaded Britches),
(33980, 14090, 1, 0.09, 0, 1, 1, 1, 1, Beaded Robe),
(33980, 14094, 0, 0.08, 0, 1, 1, 1, 1, Beaded Wraps),
(33980, 14095, 0, 0.13, 0, 1, 1, 1, 1, Native Bands),
(33980, 14098, 0, 0.14, 0, 1, 1, 1, 1, Native Cloak),
(33980, 14115, 0, 0.05, 0, 1, 1, 1, 1, Aboriginal Bands),
(33980, 15008, 0, 0.06, 0, 1, 1, 1, 1, Primal Mitts),
(33980, 15009, 0, 0.12, 0, 1, 1, 1, 1, Primal Leggings),
(33980, 15010, 0, 0.13, 0, 1, 1, 1, 1, Primal Wraps),
(33980, 15297, 0, 0.07, 0, 1, 1, 1, 1, Grizzly Bracers),
(33980, 15299, 0, 0.05, 0, 1, 1, 1, 1, Grizzly Cape),
(33980, 15300, 0, 0.04, 0, 1, 1, 1, 1, Grizzly Gloves),
(33980, 15302, 0, 0.22, 0, 1, 1, 1, 1, Grizzly Belt),
(33980, 15303, 0, 0.08, 0, 1, 1, 1, 1, Grizzly Pants),
(33980, 15476, 0, 0.15, 0, 1, 1, 1, 1, Charger''s Handwraps),
(33980, 15477, 0, 0.12, 0, 1, 1, 1, 1 Charger''s Pants),
(33980, 15479, 0, 0.15, 0, 1, 1, 1, 1, Charger''s Armor),
(33980, 15480, 0, 0.08, 0, 1, 1, 1, 1, War Torn Girdle),
(33980, 15482, 0, 0.14, 0, 1, 1, 1, 1, War Torn Bands),
(33980, 15483, 0, 0.1, 0, 1, 1, 1, 1, War Torn Cape),
(33980, 15484, 0, 0.09, 0, 1, 1, 1, 1, War Torn Handgrips),
(33980, 15485, 0, 0.05, 0, 1, 1, 1, 1, War Torn Pants),
(33980, 15486, 0, 0.11, 0, 1, 1, 1, 1, War Torn Shield),
(33980, 15944, 0, 0.06, 0, 1, 1, 1, 1, Ancestral Orb),
(33980, 15969, 0, 0.1, 0, 1, 1, 1, 1, Beaded Orb);
```

**Comment by martial69320** [comment]
Edited your file because of missing  ',' and '\':

UPDATE creature_template SET lootid='33980' WHERE entry='33980';
DELETE FROM creature_loot_template WHERE entry='33980';
INSERT INTO creature_loot_template (Entry, Item, Reference, Chance, QuestRequired, LootMode, GroupId, MinCount, MaxCount, Comment) VALUES
('33980', '727', '0', '0.24', '1', '0', '1', '1', '1', 'Notched Shortsword'),
('33980', '818', '0', '0.46', '1', '0', '1', '1', '1', 'Tigerseye'),
('33980', '856', '0', '0.06', '1', '0', '1', '1', '1', 'Blue Leather Bag'),
('33980', '858', '0', '2.06', '1', '0', '1', '1', '1', 'Lesser Healing Potion'),
('33980', '1179', '0', '2.78', '1', '0', '1', '1', '1', 'Ice Cold Milk'),
('33980', '1210', '0', '0.18', '1', '0', '1', '1', '1', 'Shadowgem'),
('33980', '1495', '0', '0.23', '1', '0', '1', '1', '1', 'Calico Shoes'),
('33980', '1497', '0', '0.2', '1', '0', '1', '1', '1', 'Calico Cloak'),
('33980', '1498', '0', '0.4', '1', '0', '1', '1', '1', 'Calico Gloves'),
('33980', '1499', '0', '0.32', '1', '0', '1', '1', '1', 'Calico Pants'),
('33980', '1501', '0', '0.28', '1', '0', '1', '1', '1', 'Calico Tunic'),
('33980', '1502', '0', '0.31', '1', '0', '1', '1', '1', 'Warped Leather Belt'),
('33980', '1503', '0', '0.31', '1', '0', '1', '1', '1', 'Warped Leather Boots'),
('33980', '1504', '0', '0.62', '1', '0', '1', '1', '1', 'Warped Leather Bracers'),
('33980', '1506', '0', '0.24', '1', '0', '1', '1', '1', 'Warped Leather Gloves'),
('33980', '1507', '0', '0.24', '1', '0', '1', '1', '1', 'Warped Leather Pants'),
('33980', '1509', '0', '0.22', '1', '0', '1', '1', '1', 'Warped Leather Vest'),
('33980', '1510','0', '0.38', '1', '0', '1', '1', '1', 'Heavy Hammer'),
('33980', '1511', '0', '0.33', '1', '0', '1', '1', '1', 'Commoner\'s Sword'),
('33980', '1512', '0', '0.21', '1', '0', '1', '1', '1', 'Crude Battle Axe'),
('33980', '1513', '0', '0.41', '1', '0', '1', '1', '1', 'Old Greatsword'),
('33980', '1514', '0', '0.32', '1', '0', '1', '1', '1', 'Rusty Warhammer'),
('33980', '1515', '0', '0.39', '1', '0', '1', '1', '1', 'Rough Wooden Staff'),
('33980', '1516', '0', '0.42', '1', '0', '1', '1', '1', 'Worn Hatchet'),
('33980', '1730', '0', '0.2', '1', '0', '1', '1', '1', 'Worn Mail Belt'),
('33980', '1731', '0', '0.16', '1', '0', '1', '1', '1', 'Worn Mail Boots'),
('33980', '1732', '0', '0.24', '1', '0', '1', '1', '1', 'Worn Mail Bracers'),
('33980', '1734', '0', '0.26', '1', '0', '1', '1', '1', 'Worn Mail Gloves'),
('33980', '1735', '0', '0.22', '1', '0', '1', '1', '1', 'Worn Mail Pants'),
('33980', '1737', '0', '0.26', '1', '0', '1', '1', '1', 'Worn Mail Vest'),
('33980', '2075', '0', '0.09', '1', '0', '1', '1', '1', 'Heavy Mace'),
('33980', '2140', '0', '0.14', '1', '0', '1', '1', '1', 'Carving Knife'),
('33980', '2214', '0', '0.26', '1', '0', '1', '1', '1', 'Wooden Buckler'),
('33980', '2215', '0', '0.28', '1', '0', '1', '1', '1', 'Wooden Shield'),
('33980', '2407', '0', '0.05', '1', '0', '1', '1', '1', 'Pattern: White Leather Jerkin'),
('33980', '2455', '0', '0.9', '1', '0', '1', '1', '1', 'Minor Mana Potion'),
('33980', '2589', '0', '55.47', '1', '0', '1', '1', '3', 'Linen Cloth'),
('33980', '2657', '0', '0.08', '1', '0', '1', '1', '1', 'Red Leather Bag'),
('33980', '2763', '0', '0.31', '1', '0', '1', '1', '1', 'Fisherman Knife'),
('33980', '2777', '0', '0.45', '1', '0', '1', '1', '1', 'Feeble Shortbow'),
('33980', '2778', '0', '0.4', '1', '0', '1', '1', '1', 'Cheap Blunderbuss'),
('33980', '3192', '0', '0.12', '1', '0', '1', '1', '1', 'Short Bastard Sword'),
('33980', '3281', '0', '0.17', '1', '0', '1', '1', '1', 'Battle Chain Gloves'),
('33980', '3282', '0', '0.07', '1', '0', '1', '1', '1', 'Battle Chain Pants'),
('33980', '3283', '0', '0.04', '1', '0', '1', '1', '1', 'Battle Chain Tunic'),
('33980', '3285', '0', '0.13', '1', '0', '1', '1', '1', 'Tribal Bracers'),
('33980', '3286', '0', '0.07', '1', '0', '1', '1', '1', 'Tribal Gloves'),
('33980', '3288', '0', '0.07', '1', '0', '1', '1', '1', 'Tribal Vest'),
('33980', '3289', '0', '0.24', '1', '0', '1', '1', '1', 'Ancestral Boots'),
('33980', '3290', '0', '0.1', '1', '0', '1', '1', '1', 'Ancestral Gloves'),
('33980', '3374', '0', '0.26', '1', '0', '1', '1', '1', 'Calico Belt'),
('33980', '3375', '0', '0.21', '1', '0', '1', '1', '1', 'Calico Bracers'),
('33980', '3609', '0', '0.05', '1', '0', '1', '1', '1', 'Plans: Copper Chain Vest'),
('33980', '3644', '0', '0.05', '1', '0', '1', '1', '1', 'Barbaric Cloth Bracers'),
('33980', '3649', '0', '0.06', '1', '0', '1', '1', '1', 'Tribal Buckler'),
('33980', '4561', '0', '0.26', '1', '0', '1', '1', '1', 'Scalping Tomahawk'),
('33980', '4562', '0', '0.12', '1', '0', '1', '1', '1', 'Severing Axe'),
('33980', '4566', '0', '0.06', '1', '0', '1', '1', '1', 'Sturdy Quarterstaff'),
('33980', '4569', '0', '0.04', '1', '0', '1', '1', '1', 'Staunch Hammer'),
('33980', '4605', '0', '6.99', '1', '0', '1', '1', '1', 'Red-Speckled Mushroom'),
('33980', '4669', '0', '0.07', '1', '0', '1', '1', '1', 'Battle Chain Girdle'),
('33980', '4672', '0', '0.21', '1', '0', '1', '1', '1', 'Ancestral Belt'),
('33980', '4675', '0', '0.07', '1', '0', '1', '1', '1', 'Tribal Belt'),
('33980', '4680', '0', '0.06', '1', '0', '1', '1', '1', 'Brackwater Cloak'),
('33980', '4686', '0', '0.05', '1', '0', '1', '1', '1', 'Barbaric Cloth Cloak'),
('33980', '4692', '0', '0.04', '1', '0', '1', '1', '1', 'Ceremonial Cloak'),
('33980', '4693', '0', '0.06', '1', '0', '1', '1', '1', 'Ceremonial Leather Belt'),
('33980', '5574', '0', '0.05', '1', '0', '1', '1', '1', 'White Leather Bag'),
('33980', '8178', '0', '0.18', '1', '0', '1', '1', '1', 'Training Sword'),
('33980', '8180', '0', '0.25', '1', '0', '1', '1', '1', 'Hunting Bow'),
('33980', '14086', '0', '0.06', '1', '0', '1', '1', '1', 'Beaded Sandals'),
('33980', '14089', '0', '0.13', '1', '0', '1', '1', '1', 'Beaded Gloves'),
('33980', '14090', '0', '0.24', '1', '0', '1', '1', '1', 'Beaded Britches'),
('33980', '14091', '0', '0.09', '1', '0', '1', '1', '1', 'Beaded Robe'),
('33980', '14094', '0', '0.08', '1', '0', '1', '1', '1', 'Beaded Wraps'),
('33980', '14095', '0', '0.13', '1', '0', '1', '1', '1', 'Native Bands'),
('33980', '14098', '0', '0.14', '1', '0', '1', '1', '1', 'Native Cloak'),
('33980', '14115', '0', '0.05', '1', '0', '1', '1', '1', 'Aboriginal Bands'),
('33980', '15008', '0', '0.06', '1', '0', '1', '1', '1', 'Primal Mitts'),
('33980', '15009', '0', '0.12', '1', '0', '1', '1', '1', 'Primal Leggings'),
('33980', '15010', '0', '0.13', '1', '0', '1', '1', '1', 'Primal Wraps'),
('33980', '15297', '0', '0.07', '1', '0', '1', '1', '1', 'Grizzly Bracers'),
('33980', '15299', '0', '0.05', '1', '0', '1', '1', '1', 'Grizzly Cape'),
('33980', '15300', '0', '0.04', '1', '0', '1', '1', '1', 'Grizzly Gloves'),
('33980', '15302', '0', '0.22', '1', '0', '1', '1', '1', 'Grizzly Belt'),
('33980', '15303', '0', '0.08', '1', '0', '1', '1', '1', 'Grizzly Pants'),
('33980', '15476', '0', '0.15', '1', '0', '1', '1', '1', 'Charger\'s Handwraps'),
('33980', '15477', '0', '0.12', '1', '0', '1', '1', '1', 'Charger\'s Pants'),
('33980', '15479', '0', '0.15', '1', '0', '1', '1', '1', 'Charger\'s Armor'),
('33980', '15480', '0', '0.08', '1', '0', '1', '1', '1', 'War Torn Girdle'),
('33980', '15482', '0', '0.14', '1', '0', '1', '1', '1', 'War Torn Bands'),
('33980', '15483', '0', '0.1', '1', '0', '1', '1', '1', 'War Torn Cape'),
('33980', '15484', '0', '0.09', '1', '0', '1', '1', '1', 'War Torn Handgrips'),
('33980', '15485', '0', '0.05', '1', '0', '1', '1', '1', 'War Torn Pants'),
('33980', '15486', '0', '0.11', '1', '0', '1', '1', '1', 'War Torn Shield'),
('33980', '15944', '0', '0.06', '1', '0', '1', '1', '1', 'Ancestral Orb'),
('33980', '15969', '0', '0.1', '1', '0', '1', '1', '1', 'Beaded Orb');

**Comment by tkrokli** [comment]
@martial69320 : your `UPDATE` command on line 1 is useless because you are deleting it in line 2.
You also did not read Nayd's comment, TrinityCore never uses ' ', ' ' around numbers, only around text.

To both of you: If you want the SQL syntax highlighting to show, put ```sql on a single line above the code. End the section with 3 back ticks if you need to put some normal text after the code block. 

Regarding the use of apostrophes inside text: you can either use 2 apostrophes (Charger''s) or backslash + apostrophe (Charger\'s), both options work (some might say that backslash is better).

**Comment by martial69320** [comment]
I edit my comment

**Comment by Exodius** [comment]
In regards to Chance Percentages which @DDuarte explained, you can read some explanations on what he meant here:
https://github.com/TrinityCore/TDB_4.3.4_NLU/commit/6a40f587c88ec33e09bc7d64bfa0c781685752ba#commitcomment-2598694
https://github.com/TrinityCore/TrinityCore/issues/13790#issuecomment-68194928

**Comment by Exodius** [comment]
Why close?

**Comment by tkrokli** [comment]
My guess is that he misunderstood the usefulness of the SQL content and closed it because he thought it would be useless to keep this issue open. Reopen this issue and comment on what needs to be improved before the SQL code can be used in a commit. (TC devs should decide when to close.)
