### ISSUE TITLE
You are in shapeshift form [BUG]

### ISSUE THREAD

**Issue by DearAdmin** [TrinityCore/TrinityCore#15469]
Hello, 

TrinityCore rev. f50df7282018 2015-08-24 14:52:18 +02000 ( 3.3.5 branch) (Win64, Release)

http://www.wowhead.com/spell=72914

http://www.wowhead.com/spell=5502

when spell casted on players for quest

can't  use mount so quest can not be done.

Regards,

**Comment by tkrokli** [comment]
#12042 ?

**Comment by DearAdmin** [comment]
Oh damn, very sorry for this :+1:

**Comment by tkrokli** [comment]
Sure. It is a duplicate, comment on **Mount with a transformation** #12042 if you have new info. Otherwise, the problem will be fixed by  **Core/Unit: Allow mounting for certain transformations** #15452 (if it gets accepted).

Notice that your link http://www.wowhead.com/spell=5502 is broken, either the spell is wrong or it is not a spell. Try http://wotlk.openwow.com/ if you know that it is supposed to be a spell.
