### ISSUE TITLE
Thomas Miller (sometime says a blank message / missing text)

### ISSUE THREAD

**Issue by unknown-8H3D** [TrinityCore/TrinityCore#15530]
Revision: https://github.com/TrinityCore/TrinityCore/commit/2138726e61f83eea76634372e8cb1b4452e0f84d

http://www.wowhead.com/npc=3518

Sometime you can see this in chat:

Thomas Miller says: Freshly baked bread for sale!
Thomas Miller says: Fresh Bread for sale!
Thomas Miller says:
Thomas Miller says: Rolls, buns and bread. Baked fresh!

**Comment by Killyana** [comment]
Because the scripts are a mess, the npc has a SAI that display the text ooc + a waypoint_script that also display the same texts, but for on of them the broadcast_text is wrong: (dataint =4013 in id = 273 must be changed to 1102)

```sql
 select * from waypoint_scripts where id in (271, 272, 273, 274);

**Comment by Killyana** [comment]
``` sql
DELETE FROM `smart_scripts` WHERE `entryorguid`=3518 AND `source_type`=0;
UPDATE `creature_template` SET `AIName`='' WHERE `entry`=3518;
UPDATE `waypoint_scripts` SET `dataint`=1102 WHERE `id`=273 ;

**Comment by MrSmite** [comment]
Maybe enough of the Stormwind Guards yelled at him for spamming that he now and then says nothing ;)

**Comment by unknown-8H3D** [comment]
Now it is even worse, he says only 2 messages, only at the end of his path ...

![wowscrnshot_120515_080335](https://cloud.githubusercontent.com/assets/14331434/11694464/e6790f9e-9eb2-11e5-8013-97a04806f3c6.jpg)

**Comment by Killyana** [comment]
Na:
``` sql
SELECT * FROM waypoint_scripts WHERE id IN (271, 272, 273, 274);
SELECT * FROM waypoint_data WHERE id IN (797230) AND POINT IN (1,2,22,23);

**Comment by tkrokli** [comment]
TrinityCore rev. c182ea010c09 2015-12-09 17:12:49 +0100 (3.3.5 branch) (Win64, Release)
TDB 335.60 + updates up to and including 2015_12_09_01_world.sql

![wowscrnshot_120915_203832](https://cloud.githubusercontent.com/assets/4903600/11696632/a17427be-9eb5-11e5-9a40-bfaf966505e1.jpg)

I started by appearing at his initial spawn point, but after he had already spoken his lines there.
I followed him on 2 consecutive rounds, then he despawned at this point where I took the screenshot.
His lines appear to be these:
```
NPC text said at the City Square:
Thomas Miller says: Warm, wholesome bread!
Thomas Miller says: Freshly baked bread for sale!

- followed by a pause, then walking to his next WP stop -

NPC text said near the SW FP in the image:
Thomas Miller says: Fresh bread for sale!
Thomas Miller says: Rolls, buns and bread. Baked fresh!

- followed by a pause, then walking to his next WP stop -

NPC text said at the City Square:
Thomas Miller says: Warm, wholesome bread!
Thomas Miller says: Freshly baked bread for sale!

- followed by a pause, then walking to his next WP stop -

NPC text said near the SW FP in the image:
Thomas Miller says: Fresh bread for sale!
Thomas Miller says: Rolls, buns and bread. Baked fresh!
- followed by NPC despawn -
```
At least he uses 4 different lines, so the only thing I would have liked to see improved is a couple of extra seconds between "Fresh bread for sale!" and "Rolls, buns and bread. Baked fresh!", because those lines are said with less than a second between them. The first speech bubble does not get time to fade before the second appears (as you can see the time between the lines in the  image I have posted).
