### ISSUE TITLE
[3.3.5a] Air Stands Still quest

### ISSUE THREAD

**Issue by AshaX** [TrinityCore/TrinityCore#15559]
TrinityCore rev. f50df72

Quest: http://www.wowhead.com/quest=13125/the-air-stands-still

Hi, this quest does not giving credit with guardians ( with item http://www.wowhead.com/item=43206/war-horn-of-acherus )

**Comment by tkrokli** [comment]
Stop making duplicate issues: https://github.com/TrinityCore/TrinityCore/issues/15425 .

SEARCH function on top of this page https://github.com/TrinityCore/TrinityCore/search?type=Issues

or check: https://github.com/TrinityCore/TrinityCore/issues if you don't know what "search" means.

Now please close this issue because someone else has already made a page about this.

**Comment by AshaX** [comment]
I used there but still same issue....
