### ISSUE TITLE
[Crash] Map::UnloadAll

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#15570]
This night I got this crashlog.

http://pastebin.com/kr6nvuGm

c5cc7cca3e29e176b5ec0405a05c3db8e19c4e93
3.3.5

**Comment by Rochet2** [comment]
I would like to note that instance maps are unloaded in an non thread safe manner, but map container Get methods etc do not have locks guarding i_maps container that contains all maps.
Creating a map checks for map existence using the unsafe get and then continues to create a map using locked create. Create should happen in thread safe places from what I see so thread safety "shouldnt" be an issue there and unload also seems to work so too, but not for instance map since they are unloaded when the base map is unloaded (or similar).

Perhaps this is related? Note how map updater thread destroys the instance maps in the log, and the map could be running an update on it's own thread, no?

**Comment by jackpoz** [comment]
> I would like to note that instance maps are unloaded in an non thread safe manner

could you elaborate more on this, maybe providing a helgrind log of your statement or detailed explaination about how 2 threads can access the same map while 1 thread is unloading it ?

**Comment by Shauren** [comment]
Map destructor no longer calls UnloadAll. Issue outdated, please open new one with new callstack if this still happens.
