### ISSUE TITLE
Gurubashi's "Arena Treasure Chest" is not spawned correctly

### ISSUE THREAD

**Issue by unknown-8H3D** [TrinityCore/TrinityCore#15580]
Revision: https://github.com/TrinityCore/TrinityCore/commit/2138726e61f83eea76634372e8cb1b4452e0f84d

NPC: www.wowhead.com/npc=14508 (Short John Mithril)
Object: http://www.wowhead.com/object=179697 (Arena Treasure Chest)

Gurubashi's "Arena Treasure Chest" is not spawned in the middle of the arena as it should be, instead of this, it is spawned somewhere on Short John Mithril's path, near stairs, on the arena floor, after he is running back to his initial spawn point.

**Comment by dr-j** [comment]
Cannot reproduce I have just tested this again since I scripted it a while ago and he leaves chest where its meant to be this is not exactly in middle of arena but is still on arena floor the position where he drops chest was sniffed from retail.

He drops the chest at exact same point when he says his second line of text.

**Comment by unknown-8H3D** [comment]
I will try to post some proof retail vs TC next days, btw updated first post.

**Comment by Nyeriah** [comment]
I hearsay talking to him while he's walking bugs it, but haven't tested it myself.

**Comment by Rushor** [comment]
if the creatures loads the `waypoints` after eventstart nothing can stop it from walking to the ground
