### ISSUE TITLE
[335] Auctionhouse does not calculate correct deposit for multiple stacks

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#15643]
__Core:__ 747ea7ca2c2b757dc9c5a672746d801a8365ee98
__DB:__ TDB_full_335.59_2015_07_14 + updates

__Bug:__

The deposit required to create an auction of multiple stacks (same item) is not calculated and displayed correctly in the auctionhouse GUI, resulting in the possibility of a "not enough money" error.

__Details:__

* Give yourself 18x 4496 (Small Brown Pouch)
* Give yourself 5 silver, 22 copper (hint: this is what the auctionhouse will calculate)
* Open the auctionhouse to create a new auction
 * Put the bag in the item slot of the auction GUI
 * Stack size: 1
 * Number of stacks: 14
 * Price: Per item
 * Starting bid: 2 gold, 25 silver, 0 copper
 * Buyout: 2 gold, 25 silver, 0 copper
 * Duration: 24 hours
* Notice the deposit shown is 5 silver, 22 copper
* Click the "Create auction" button
* Result
 * 4 bags will be placed into auction
 * An error will appear: "You do not have enough money"
 * Your character will still have 1 silver, 22 copper

**Comment by tkrokli** [comment]
TrinityCore rev. 1dcf186dfd24 2015-09-30 22:31:00 +0200 (3.3.5 branch) (Win64, Release) / TDB 335.59
Confirmed. In addition to showing the wrong price (independent of the bid price or buyout price), the AH also shows that it wants 6c extra (36/6) for each fourth item (4) you place in the Create Auction GUI.

Average deposit is supposedly is 36 copper / item, but AH won't accept any lower deposit than 100c (1s). The big deal, though, is that the actual deposit price is 1 silver/item, a total of 1400c (14s) in your case.
```
 bags:  Deposit shown:   Actual deposit:
 -----  --------------  ----------------
  1              100           100
  2              100           200
  3              108           300
  4              150           400
  5              186           500
  6              222           600
  7              258           700
  8              300           800
  9              336           900
 10              372          1000
 11              408          1100
 12              450          1200
 13              486          1300
 14              522          1400
 15              558          1500
 16              600          1600
 17              636          1700
 18              672          1800
 19              708          1900
 20              750          2000
```
Is the GUI calculating the AH cut price instead of the Deposit cost?

**Comment by pete318** [comment]
No, looks much simpler than that. It looks like it's applying the minimum deposit per item.

However, I am interested in the every 4th item.. I wonder what the rule is there. Whenever it gets close to 50c boundary it rounds to it, then continues from there? Or some other strange rule.

I'll experiment some I think.

**Comment by pete318** [comment]
If you're feeling brave.. Try this. It should resolve all the use cases above and always take the same deposit as shown on screen.

https://github.com/pete318/TrinityCore/commit/70054998041467078aafe0c7b43241e3d0728e25

It's not properly tested and also I doubt it has a real chance of getting into the core. But, due to the way Blizzard handle this client side, I can't think of many better ways to do it.

Basically, the story is this:

Even though the received packet structure would appear to support multiple items, with multiple stack sizes. The client doesn't use this and simply sends an auction sell request for each item.

So, how does the server know that there are more coming, or how to treat them? It doesn't really. So what this does is, save everything normally, but also add the auctions to a "pending" list per player. The player update event waits until there haven't been any new auctions between update cycles and once that's the case processes them by calculating the total deposit for all items as a bulk and collecting the gold from player, but also updating the auctions in DB to ensure the total deposit equals the amount paid.

It needs a lot of work and I think it needs a different solution. I'm just not sure what yet.

**Comment by tkrokli** [comment]
OK, I will try and see if I can squeeze in a test on this too during the weekend.

@MrSmite : if you feel like testing it yourself, I think it would be a good idea to use a bit newer core than your version from August 3, but you decide what you want to do about it. :-)

**Comment by pete318** [comment]
Updated it a bit https://github.com/pete318/TrinityCore/commit/d24d96210a18faef3edb23bd716ff31b303ec8b2

Still not overall happy about the solution, but not really many other ways I can think of right now to achieve the effect. So really comes down to how important this proper handling is.

**Comment by MrSmite** [comment]
@pete318 - That's some nice work. Couple questions regarding this though

> The base is then multiplied by number of items, and the time multiplier (x2 for 24 hour, x4 for 48 hour)

The CONF allows servers to customize auction times in a couple ways:

* Rate.Auction.Time
 * I always leave this at __1__ but what happens with your code if the server sets it to 5?
* AuctionHouseBot.MinTime
 * This defaults to __1 hour__ but what happens with your code if the server sets it to 72?
* AuctionHouseBot.MaxTime
 * This defaults to __72 hours__

Will crazy numbers in these CONF settings work with your proposed fix, since the auction GUI available to players is more restrictive:

* Short - Less than 30 minutes.
* Medium - Between 30 minutes and 2 hours.
* Long - Between 2 hours and 12 hours.
* Very Long - Between 12 hours and 48 hours.

**Comment by pete318** [comment]
Well I would say give it a try and see. I didn't omit any of the current calculation aspect (I think) but did re-arrange the order to support the weird deposit.

Of course it won't match what the client tells you anyway.. So, you have to know what you expect it to be.
