### ISSUE TITLE
[3.3.5] FreezeDetectorHandler: World Thread hangs, kicking out server!

### ISSUE THREAD

**Issue by BrettDioson** [TrinityCore/TrinityCore#15653]
My 3.3.5 worldserver is crashing on a freeze detected 90 seconds after core starts:

Branch: 3.3.5
commit: 774ea0b4bd1e
Source\src\server\worldserver\Main.cpp:426 in FreezeDetectorHandler ABORTED

This happened some time after commit: 2138726e61f8

Crash log: https://gist.github.com/BrettDioson/013de45173089ae773fe

**Comment by Aokromes** [comment]
Shutdown authserver, disable freeze detector, leave core to run for 30 minutes. restart server with freeze detector enabled.

**Comment by jackpoz** [comment]
it looks like your AuctionHouse is handling a lot of expired auctions https://gist.github.com/BrettDioson/013de45173089ae773fe#file-774ea0b4bd1e_worldserver-exe_-3-10_19-13-57-txt-L256 , doing what @Aokromes suggested will get you a working worldserver because it will allow to handle properly all expired auctions (which seems to take more than 90 seconds)

**Comment by pete318** [comment]
It happens on the first startup after applying the Auction house changes recently.

So normal operation can resume after first server start.

**Comment by BrettDioson** [comment]
Thanks @Aokromes, @jackpoz, @pete318 .  I'll try that now and report back.

**Comment by Rochet2** [comment]
Hmm. Maybe the loop could be enhanced somehow - maybe it takes long because its inefficient in some way.
For example if there are 300k auctions and all are expired, the update loop would send 300k-600k mails. On each mail sending the GetPlayerAccountIdByGUID function is called since the player is likely not ingame which causes a DB query to get the player account id.

So to process 300k auctions there are 300k-600k queries to the database for account IDs.
If one query would take 1ms it would mean 600 seconds = 10 minutes at worst to go through the whole thing with the SQL queries alone. (+ the result SQL, but thats async)

Seems to me like the check just checks if the owner exists in DB if he is not online - the queried account ID is not really used:
https://github.com/TrinityCore/TrinityCore/blob/588152844510dde4bc12608afa7a26ca8383a9dd/src/server/game/AuctionHouse/AuctionHouseMgr.cpp#L173
And it was added when the whole system was created: https://github.com/TrinityCore/TrinityCore/commit/8ad58b4bcc24b71049f3831700ec48a5f4e01965#diff-001e0321747e1b42674c6ecc4ceec5a2R177
Maybe could instead of query try use sWorld->HasCharacterNameData(guid).

I tried to do some profiling but it went in the woods with blaming `Item::GetTemplate` and the stringstream usage in `Item::SaveToDB` in ahbot code.

**Comment by Aokromes** [comment]
We have the same problem on characters conversion on client version update, core ends "crashing"

**Comment by BrettDioson** [comment]
ok, I disabled MaxCoreStuckTime, let the core run for an hour or so and it did NOT crash this time.  I shut it down, set MaxCoreStuckTime to 180 and let it run for about 30 min with no crash so that seems to have solved my problem.  I'll let it run a bit more with some characters logging in and interacting with the auction house, but it looks like that fixed it.  thanks all!

**Comment by jackpoz** [comment]
@Rochet2 https://gist.github.com/BrettDioson/013de45173089ae773fe#file-774ea0b4bd1e_worldserver-exe_-3-10_19-13-57-txt-L1 , no reason to talk about efficiency after reading the first line of that crashlog

**Comment by Rochet2** [comment]
> no reason to talk about efficiency after reading the first line of that crashlog

You mean the "debug" part?
I dont see how that is relevant since it would last long even without debug.
And the suggested fix for it was a one line change anyways so maybe it could be considered. (remove DB query and replace with ram access)

**Comment by BrettDioson** [comment]
Well... no crashes since implementing your suggestions.  Thanks all!

**Comment by Pirricli** [comment]
Three related logs:

http://pastebin.com/QTLcfNc8
http://pastebin.com/9Wu39yi1
http://pastebin.com/AB1XrdvE

80ed03a84d2a0cbdd0d37d9c57994724333ae798

**Comment by Aokromes** [comment]
No, unrelated to this specific freeze, those 3 are related to wintergrasp.

**Comment by Shauren** [comment]
This one was optimized, GetPlayerAccountByGUID no longer does any DB queries - https://github.com/TrinityCore/TrinityCore/commit/4a368501675a5892c181ff77b59ec7483601d51a#diff-1596ecd5424665946209f97259f1dba8
