### ISSUE TITLE
[3.3.5] "Earthgrab Totem" chases target

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#15651]
Branch 3.3.5, rev 774ea0b4bd1e0d469cfce8013f2e557f030c7c97, TDB 335.59

Creature-summoned [Earthgrab Totem](http://www.wowhead.com/npc=6066/earthgrab-totem) will chase its target, when it should be immobile (as it's a totem, duh).

**Comment by P-Kito** [comment]
uhm... really? I cant believe :D

**Comment by Killyana** [comment]
If the npc enter combat when it's rooted it will enter in evade mode: https://github.com/TrinityCore/TrinityCore/issues/15304

**Comment by tkrokli** [comment]
Thanks for the link, Killyana. I knew I had seen this problem mentioned before, but could not find it by searching only for "Earthgrab Totem", because it is reported as Mosh'ogg Witch Doctor & Ward of Laze.

**Comment by Killyana** [comment]
@Treeston can you provide the npc that summon this totem?

**Comment by Treeston** [comment]
One type of thistleshrubs in Tanaris (I believe it is [Gnarled Thistleshrub](http://www.wowhead.com/npc=5490/gnarled-thistleshrub)), and I also vaguely remember seeing it in Stranglethorn somewhere.

**Comment by dr-j** [comment]
This arisen because of   http://www.wowhead.com/npc=670/skullsplitter-witch-doctor   a7fcd11a0/sql/old/6.x/world/01_2015_03_21/2015_07_03_05_world_2015_05_26_06.sql#L94 which fixes it for above case and since there is only one entry for the npc 'Earthgrab Totem' probably fixes all.

~~~sql
DELETE FROM `smart_scripts` WHERE  `entryorguid`=6066;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(6066, 0, 0, 0, 0, 0, 100, 0, 1000, 1000, 4800, 5200, 11, 8377, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 'Earthgrab Totem - In Combat - Cast \'Earthgrab\''),
(6066, 0, 1, 2, 4, 0, 100, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Earthgrab Totem - On Agro - Auto attack off'),
(6066, 0, 2, 0, 61, 0, 100, 0, 0, 0, 0, 0, 21, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Earthgrab Totem - On Agro - Disable Combat Movement');

**Comment by Treeston** [comment]
Root inhabittype maybe?

**Comment by tkrokli** [comment]
Sounds plausible, worth trying. PR https://github.com/TrinityCore/TrinityCore/pull/17543 (Core/Creature: implement INHABIT_ROOT to apply UNIT_STATE_ROOT to creature) makes this alternative available:
```sql
-- set InhabitType INHABIT_ROOT for NPC entry 6066 Earthgrab Totem
UPDATE `creature_template` SET `InhabitType`=`InhabitType`| 8 WHERE `entry`= 6066;
```

**Comment by Keader** [comment]
#17543 already merged @tkrokli ... so any news on this? :)

**Comment by tkrokli** [comment]
Thank you for reminding me about this, @Keader . Have you tested my query to see if it works?
If it doesn't work alone, will it work with **dr-j**'s SAI in https://github.com/TrinityCore/TrinityCore/issues/15651#issuecomment-170343978 ?

**Comment by Keader** [comment]
Not tested, just looking around some old tickets ^^
