### ISSUE TITLE
Strand of Ancients Battleground Demolisher slow immunity

### ISSUE THREAD

**Issue by ShinDarth** [TrinityCore/TrinityCore#15767]
Rev: https://github.com/TrinityCore/TrinityCore/commit/183b89dcc31e38f23645a008a8c8e6ac4e4aa9f6

Battleground Demolisher of the Strand of Ancients battleground should be immune to all slowing/stopping effects.

Fix:

```
UPDATE `creature_template` SET `mechanic_immune_mask` = 344407930 WHERE entry IN (28781, 32796);
```

![](http://s24.postimg.org/6a3c1ry11/sota_tank.png)

**Comment by pete318** [comment]
No. They're immune to stuns etc. They're not immune to slowing effects and some effects the result in an initial stop (DK has one I think) also work on them.

I played rogue for ages and in SOTA I'd always be slowing them with crippling poison.

**Comment by Shauren** [comment]
can confirm, definitely slowable

**Comment by Keader** [comment]
Thought it strange they take slow the first time I saw.But confirmed on blizzard in patch 5.4, take slow and roots xD

**Comment by Aokromes** [comment]
http://us.battle.net/wow/en/forum/topic/2112511550
[12:06:12] <Aokromes> xd

**Comment by pete318** [comment]
After a bit of looking around (since really I only played rogue in BC, Cata, MoP. I skipped rogue in Wrath because Blizzard ruined sub spec, and I didn't want to L2P again (also I had a paladin and it was Wrath so..)

Anyway. Here's a short video showing a demo being frostbolted and still appearing to move at normal speed, although I do catch up from an oblique angle. So, I'm unsure whether it was slowed by it or not.

https://www.youtube.com/watch?v=mlTubW9aEJg

Plus a few discussions at the time of cata release:

http://us.battle.net/wow/en/forum/topic/1127160056
http://www.mmo-champion.com/threads/1080190-Demolishers-in-Strand-of-The-Ancients

here suggests they could be snared, not rooted

http://www.gamefaqs.com/boards/534914-world-of-warcraft/58775943

I think the jury is out on this one. For 3.3.5 at least. After cata I can tell you for sure they moved faster than in my video but you could definitely slow them.
