### ISSUE TITLE
Scarlet Monastery/Cathedral: High Inquisitor Whitemane's door is open

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#15793]
TrinityCore rev. 60da7c655273 2015-10-31 16:04:14 +0100 (HEAD branch)

The door must be closed

![kloster](https://cloud.githubusercontent.com/assets/10637389/10864665/2e763a28-7ff6-11e5-9ab2-aa93012473f2.jpg)

**Comment by Killyana** [comment]
Provide more informations please, gob guids and entry, position, if the door can be opened by a click or by event ect....

**Comment by Kittnz** [comment]
when the event is finished the door open's, but not before the event, it should be closed

**Comment by Rushor** [comment]
[00:05:31]11877 (Entry: 104600) - [High Inquisitor's Door X:1173.010010 Y:1398.910034 Z:31.972300 MapId:189]

**Comment by Aokromes** [comment]
It looks script bug, on db the door is closed.

**Comment by Kittnz** [comment]
Was this correctly scripted before? or always had this error?

**Comment by Aokromes** [comment]
I don't remember.

**Comment by tkrokli** [comment]
TrinityCore rev. f226ebd2004d 2016-06-18 22:48:10 +0100 (3.3.5 branch) (Win64, Release, Static)
TDB 335.61 plus updates up to and including `2016_06_18_02_world.sql`

Confirming (for reference) that the door to High Inquisitor Whitemane is open before it should be.

![wowscrnshot_061916_190703](https://cloud.githubusercontent.com/assets/4903600/16178807/51282cf2-3653-11e6-9b25-58e6d6f7eef2.jpg)
Like Rushor said in https://github.com/TrinityCore/TrinityCore/issues/15793#issuecomment-152779828, it is High Inquisitor's Door (GO entry 104600, DB guid 11877)

The door is scripted in https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/ScarletMonastery/instance_scarlet_monastery.cpp which in turn is referenced in https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/ScarletMonastery/boss_mograine_and_whitemane.cpp#L134

Maybe it is possible to get a clue by searching in the commit log history of the script?
https://github.com/TrinityCore/TrinityCore/commits/3.3.5/src/server/scripts/EasternKingdoms/ScarletMonastery/instance_scarlet_monastery.cpp
(I don't know if any DB changes since 2014 could have altered the gameobject data.)

**Comment by Elarose** [comment]
https://youtu.be/LBHyuhUCJ6o?t=114

The door before the one in question is currently requiring no key, auto closes, and opens instantly. (It should not close)
Fairbanks in Cathedral also doesn't open with lever, and then auto closes even when you .gob acti 11876 it open, should stay open with lever 'down'
https://youtu.be/ON2_NSDpTFQ?t=372
https://youtu.be/cqdOLtMdyOk?t=158

And I believe fairbanks has some later sm info, as hes lying down like hes dead. (Later sm has him lying dead with no hp, not earlier.
https://youtu.be/-fSm3db4lYQ?t=479
 
Herods door in armory the lever also does nothing.

Will post more later when I find it.

**Comment by illfated** [comment]
Please consider changing the title of this issue ticket to something similar to the referenced ticket #23753:
**Scarlet Monastery/Cathedral: High Inquisitor Whitemane's door is open**
(a better title should make it easier to search for this issue for others)

**Comment by Aokromes** [comment]
832c95f
