### ISSUE TITLE
[6.x][Quest] The Wakening

### ISSUE THREAD

**Issue by Ahtuno** [TrinityCore/TrinityCore#15827]
---

Rev: 271390753d63ea34e498e45f5e00a758f6997fbc
TDB 6.03

---

Quest:
http://www.wowhead.com/quest=24960/the-wakening

NPCs:
http://www.wowhead.com/npc=38895/lilian-voss
http://www.wowhead.com/npc=49230/marshal-redpath
http://www.wowhead.com/npc=49231/valdred-moray

---

After you accept this quest, it is automatically completed. Normally you have to Speak with:
- NPCs not talk-able
 - Speak with Lilian Voss
 - Speak with Marshal Redpath
 - Speak with Valdred Moray
- Missing Gossips
- Quest Marker (arrow) should above the heads of the NPCs, but arent.

https://github.com/TrinityCore/TrinityCore/issues/13753 <- seems not working with currently Rev.

**Comment by Ahtuno** [comment]
@tkrokli any idea my friend ?

**Comment by tkrokli** [comment]
I'm downloading the game client to check and verify what works and what doesn't work at the moment.
I am also going to check what can be used from commit https://github.com/TrinityCore/TrinityCore/commit/745e1c677c89d610bb07d1708e2c9f505a88cb0c to find out why it doesn't work. I tried to look for DBErrors on any of those NPCs or their gossip_menu_id values, but could not find them, so it does not look like any of those trigger a DBError (maybe because quest 24960 is set to auto complete?).

**Comment by Ahtuno** [comment]
the funny thing is when I manually apply this https://github.com/TrinityCore/TrinityCore/commit/745e1c677c89d610bb07d1708e2c9f505a88cb0c he dont auto complete the quest, but the NPCs are still not talk-able

**Comment by Killyana** [comment]
Looks like the script for this quest wasn't pushed, also for 6.x it requires some adjustments.

**Comment by Carbenium** [comment]
@Killyana: d1b549a23af343a5e5c074c784fb4570eba1cc98

**Comment by Killyana** [comment]
Ok  I will fix it when I get some free time.

**Comment by Ahtuno** [comment]
thank you @Killyana , while this I will try to find and fix other quests
