### ISSUE TITLE
[6.x] DB/Quest: Saving the Young 

### ISSUE THREAD

**Issue by evandervecht** [TrinityCore/TrinityCore#15845]
Branch 6.x
Revision 6.03,https://github.com/TrinityCore/TrinityCore/commit/7c238cdefa7e83d9574d04851912ed58c81fd7ad

Quest: Saving the Young is not working, eggs are lootable, hatchlings out of their eggs but can't click them.

Location: Zalazane's fall

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by tkrokli** [comment]
TrinityCore rev. 77f980035a43 2016-07-02 22:44:03 +0200 (6.x branch) (Win64, Release, Static)
TDB 6.04 plus updates up to and including `2016_06_30_00_world.sql`

Yes, this issue is still valid, although http://www.wowhead.com/quest=24623/saving-the-young does not say anything about picking up Bloodtalon Eggs (http://www.wowhead.com/object=201905/bloodtalon-eggs) so I don't think they are supposed to be part of the quest. Looting animation is available, but no item gets looted. There does not seem to be any quest related to this container item, so I am guessing that this behaviour has been transferred from the Taillasher Eggs (http://www.wowhead.com/object=3240/taillasher-eggs) picked for the pre-Cataclysm quest Break A Few Eggs (http://www.wowhead.com/quest=815/break-a-few-eggs).

**Current behaviour:** Player character stands near the Lost Bloodtalon Hatchling (http://www.wowhead.com/npc=39157/lost-bloodtalon-hatchling) and uses the quest item Bloodtalon Whistle (http://www.wowhead.com/item=52283/bloodtalon-whistle), but nothing happens. Spell ID 70874 (http://www.wowhead.com/spell=70874/bloodtalon-whistle) does nothing, neither when item is used or when cast manually from the command line. Maybe this needs scripting to work.
***
Echo Isles / Darkspear Training Grounds is still an area where lots of events and quests don't work because that area is not scripted yet, regarding both phasing and quest events. There are also still a lot of quests needing to be repaired to work properly and have correct chaining as well as mixed `quest_reward_text` / `quest_item_requested` content not placed correctly (empty gossip).

**Comment by Naddley** [comment]
https://github.com/TrinityCore/TrinityCore/commit/9cee690936707345f5a0b0ed729c257dde416554
