### ISSUE TITLE
[Quest] An End To All Things...

### ISSUE THREAD

**Issue by Runico** [TrinityCore/TrinityCore#15861]
This is one of the Deathknight's quest 
Vehicle supposed to be able flying

3.3.5
Rev 302623a1516e487ad64f2028aec287b99372e33a

**Comment by tkrokli** [comment]
Please post links for everything you are talking about, so we know what you mean.
There are lots of vehicles in that area, so you need to explain more to describe your issue.

**Comment by Kittnz** [comment]
Confirmed
254aa21a85bbfda2503ef723fb6cb0d4c8670ca9

**Comment by Kittnz** [comment]
It's the quest item, when you summon the flying drake vehicle it should be flying and not stuck on the ground.

**Comment by tkrokli** [comment]
Hmm, it worked less than a month ago. That is weird. I will have to test this again and see it for myself.

**Comment by tkrokli** [comment]
Tested removing both of the lines in `/src/server/game/Entities/Creature/Creature.cpp` containing `LoadCreaturesAddon();` (line 443 and 1559), but it only resulted in the Frostbrood Vanquisher standing on the ground (walking) instead of hovering at ground level.
Also tried setting `creature_template`.`InhabitType` = 4 (Flying), but it did not make any difference.

Added PR  [**3.3.5 Fix BuildPointPath and check for MOVEMENTFLAG_DISABLE_GRAVITY #15382**](15382)
to my source copy, but no change, even with `InhabitType` = 4 (the default InhabitType for this creature is 3, so I guess it uses `MOVEMENTFLAG_DISABLE_GRAVITY` to be able to fly).

Thinking about this issue, I wanted to see if there are any other affected flying vehicles.
Oh yes. There surely is:
**On Ruby Wings**
http://www.wowhead.com/quest=12498/on-ruby-wings
http://www.wowhead.com/item=38302/ruby-beacon-of-the-dragon-queen
http://www.wowhead.com/npc=27996/wyrmrest-vanquisher

Create a new character and do the following:
```
.char level 75
.tele Dragonblight
.additem 38302

(use item and mount the Wyrmrest Vanquisher)
```
**The exact same issue applies.** Can you suggest other flying vehicle quests to test?

If this is a global issue, I suggest reverting some of the changes after 2015-11-10 00:50:15 +0100.
Maybe also change the title of this issue to **Flying vehicles can no longer fly after commit 52692c3**

**Comment by ccrs** [comment]
I think its not related to the creature, but the vehicle id.
Same happens to http://wowhead.com/npc=29403/
Also http://www.wowhead.com/npc=27996/wyrmrest-vanquisher does work, but depends on where do you use the object to summon it.

**Comment by Runico** [comment]
Every vehicle like the issue one has been brokem

**Comment by tkrokli** [comment]
OK, thanks for confirming. Would you like to change the issue title, to say how much is broken? :)

**Comment by Killyana** [comment]
@ariel- Can you have look at this, looks like your commit: https://github.com/TrinityCore/TrinityCore/commit/52692c3f9d09dc781add9cfee043d6f6ec80291a caused this issue.

**Comment by sirikfoll** [comment]
This works for me
```diff
diff --git a/src/server/game/Entities/Creature/Creature.cpp b/src/server/game/Entities/Creature/Creature.cpp
index 9173d44..ea10ce7 100644
--- a/src/server/game/Entities/Creature/Creature.cpp
+++ b/src/server/game/Entities/Creature/Creature.cpp
@@ -440,8 +440,8 @@ bool Creature::UpdateEntry(uint32 entry, CreatureData const* data /*= nullptr*/)
         ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_ATTACK_ME, true);
     }
 
-    LoadCreaturesAddon();
     UpdateMovementFlags();
+    LoadCreaturesAddon();
     return true;
 }
 
```

**Comment by tkrokli** [comment]
@sirikfoll : Very interesting. I will test that change and report back. :+1:
