### ISSUE TITLE
[3.3.5] Core/Guild Vault: Deposit resets to 0 after it exceeds (2^64 − 1) copper

### ISSUE THREAD

**Issue by c9240709-b07d-4439-9212-94f05f7a3212** [TrinityCore/TrinityCore#15936]
Revision: https://github.com/TrinityCore/TrinityCore/commit/c703e01471a3598f68051abb17e598e316b744ef

If your Guild Vault has (2^64 − 1) copper deposited (just set it to (2^64 − 1) in Database - Characters - Guild - BankMoney) and you go and deposit 1 copper, it will reset back to 0.

No Guild Vaults will have such tons of gold in reality, but maybe (just in case of a fun server) it should tell you that you are at the gold limit (limited by game client).

**Comment by Shauren** [comment]
Retail guild bank gold cap actually exists and is 999999g 99s 99c

**Comment by unknown-8H3D** [comment]
@Shauren 
Source ?
There is no limit yet implemented, as you can deposit more than 999999g 99s 99c and values smaller than 2^64 − 1 doesn't reset the deposit.

**Comment by Maibenrai** [comment]
http://wow.gamepedia.com/Money

"The most money a single player can carry is 999,999g 99s 99c; the same limit applies to guild banks. Before Patch 4.0.1, the limit was 214,748g 36s 47c (or 2^31-1c), because Blizzard stored a player's money as a signed 32-bit integer. Screenshots of players reaching the previous gold limit have been taken on both American and German servers."

**Comment by Jildor** [comment]
This can be closed with: https://github.com/TrinityCore/TrinityCore/commit/967f21a4b40d23d6501006e4fb7bc0608a1d86d1 ??
