### ISSUE TITLE
[3.3.5] Core/Guild Vault: Deposit is not displayed correctly if higher than (2^51 - 1) copper

### ISSUE THREAD

**Issue by c9240709-b07d-4439-9212-94f05f7a3212** [TrinityCore/TrinityCore#15937]
Revision: https://github.com/TrinityCore/TrinityCore/commit/c703e01471a3598f68051abb17e598e316b744ef

If your Guild Vault has a deposit bigger than (2^51 -1) copper, you have to deposit or withdraw any amount of gold / silver / copper in order to see the REAL deposit.

![wowscrnshot_120315_141916](https://cloud.githubusercontent.com/assets/14331434/11560675/ddfd5ca4-99ca-11e5-9c1a-dbf79585fc81.jpg)
![wowscrnshot_120315_141923](https://cloud.githubusercontent.com/assets/14331434/11560677/ddfeb3d8-99ca-11e5-95f2-d13a5a186f90.jpg)
![wowscrnshot_120315_141927](https://cloud.githubusercontent.com/assets/14331434/11560676/ddfeac1c-99ca-11e5-87d1-12296dab4276.jpg)

**Comment by NorthStrider** [comment]
As if you would ever get that much gold in a blizzlike situation

**Comment by Gacko** [comment]
This is no reason to not fix a bug (if fixable).

**Comment by NorthStrider** [comment]
it looks more like this isn not a actual bug; it's a client limit. Pretty sure that the guild vault also has some sort of overall gold limit which hasnt been discovered yet.

**Comment by Shauren** [comment]
This is not fixable - it comes to double to string conversion in lua code (yes, lua numbers are doubles, not ints)

**Comment by tkrokli** [comment]
From @Maibenrai's comment in #15936 :

http://wow.gamepedia.com/Money

"The most money a single player can carry is 999,999g 99s 99c; the same limit applies to guild banks. Before Patch 4.0.1, the limit was 214,748g 36s 47c (or 2^31-1c), because Blizzard stored a player's money as a signed 32-bit integer. Screenshots of players reaching the previous gold limit have been taken on both [American](http://static.mmo-champion.com/mmoc/images/news/2008/january/691k3KN.jpg) and [German](http://static.mmo-champion.com/mmoc/images/news/2008/january/goldlimit.jpg) servers."

**Comment by Gacko** [comment]
Then this limit probably has to be implemented on server-side also?

**Comment by Myst** [comment]
As I understand this is not a "bug". This is just a limit established, and also I think there is not any reason to try to change this.
