### ISSUE TITLE
[3.3.5] Core/Spell: Molten Core - Wrong spellproc

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#15942]
rev: https://github.com/TrinityCore/TrinityCore/commit/3c4f4356298d974c507fbd4c3fa54c1d4075e091
spellids:
spell=47245
spell=47246
spell=47247

Problem:
The stacks from the Buff gets removed if spell "Soul Fire" or "Incinerate" HITS the target.
This is wrong, the stackamount should be reduced DIRECTLY AFTER THE CAST of "Soul Fire" or "Incinerate"

Source for this:
https://www.youtube.com/watch?v=qir00p0iwt8 - at 4:50 min
There you can see, that the stackamount is reduced after the cast of  "Soul Fire" or "Incinerate"

If someone could at least say why the stackamount is reduced by direct negative spelldamage and not on spellcast - we could find a solution maybe

**Comment by P-Kito** [comment]
Thats actually with alot of procs like this. Also for the firemage or shadowtrance on warlocks.

**Comment by Rushor** [comment]
can you list some of them - aka the spellids?

**Comment by P-Kito** [comment]
http://wotlk.openwow.com/spell=48108
http://wotlk.openwow.com/spell=17941
http://wotlk.openwow.com/spell=44546

**Comment by Rushor** [comment]
thanks :)

**Comment by Mollestus** [comment]
http://wotlk.openwow.com/spell=70752 is also affected by this

**Comment by Rushor** [comment]
related to the removemode:
Family SPELLFAMILY_MAGE, flag [0] 0x00000000 [1] 0x00000002 [2] 0x00000008

**Comment by Greymane** [comment]
There are two maain problems on this issue:

1) mods that are taken on spellcasts should change the aura stack when the spell is cast, not when aura get procced on target hit mask.

2) biggest problem: mods are not being dropped at all if the aura has a spell_proc_event entry, so that means we will only lose the spellmods because the aura itself got removed, not because we exhausted its charges.

The proper solution (maybe, just giving a shot in the daar) would be transfering the aura stack drop to spellmod control when its a SPELLMOD_CASTING_TIME, and removing the stack drop from ProcDamageAndSpellFor code, but i imgine that would be a hella of a work...

**Comment by boom8866** [comment]
Identify problems

**Comment by tkrokli** [comment]
@boom8866 : Please be more specific and detailed. Your comment seems unclear and incomplete.
