### ISSUE TITLE
[6.x] Right Click creature attack

### ISSUE THREAD

**Issue by GnaXi** [TrinityCore/TrinityCore#15963]
Checklist for creatures which cannot be attacked with "right click"

- [ ] Quest: http://www.wowhead.com/quest=10303/the-blood-elves
The Blood Elf Scout's cannot be attacked with normal right click attack.
You can however cast a spell and make them hostile that way and then right click them afterwards.

- [ ] Killcreatures for the Quest Cutting Teeth broken http://www.wowhead.com/quest=25126

Examplescreenshot
![thebloodelves](https://cloud.githubusercontent.com/assets/1616448/11669460/0c816e4a-9dfd-11e5-81c0-b895b27475d9.png)

rev 5bf9d2bed4

**Comment by Kittnz** [comment]
is this working on 3.3.5?

**Comment by tkrokli** [comment]
Yes, it works fine in 3.3.5. I'll make a quick test on cc685ac33433 and confirm to verify.

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/issues/13492

also broken: Quest Cutting Teeth broken

i will generlise this issue and add a todolist with the wrong creatures.

http://www.wowhead.com/quest=25126

You can only kill the Mottled Boar with skills and not with right click

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by tkrokli** [comment]
6.x has become a lot better when it comes to right-click attacking now. I don't have trouble attacking other mobs on rev. afa0bac 2016-06-15 19:58:21 +0200 (6.x branch) (Win64, Release, Static)
TDB 6.04 plus updates up to and including `2016_06_15_08_world.sql`. But these NPCs are different:

![wowscrnshot_061616_034351](https://cloud.githubusercontent.com/assets/4903600/16102964/d101db1c-3374-11e6-954b-ec176e12b2f0.jpg)

Notice that the `.npc info` tells us that the Blood Elf Scout NPC has got `npcflags` = 2 (Quest Giver). This does not make any sense at all. I wonder if something is wrong with the SAI for these NPCs.

About the quest Rushor mentioned above, [Cutting Teeth](http://www.wowhead.com/quest=25126/cutting-teeth) (orc starting quest 2) is working correctly now.

**Comment by tkrokli** [comment]
TrinityCore rev. cfc40f2cccee 2016-06-16 17:47:10 +0200 (6.x branch) (Win64, Release, Static)
TDB 6.04 plus updates up to and including `2016_06_16_00_world.sql`

This issue is easily solved by setting the `creature_template`.`npcflag` to 0 instead of 2. These NPCs (`entry = 16521`) never have been quest givers as far as I remember and they don't have `npcflag` 2 in 3.3.5. So this should be confirmed by TDB 335.61 + the table `creature` in TDB 6.04 where `npcflag = 0`.

Oh, and by the way: the follow-up quest 9311, "Blood Elf Spy", also suffers from the same issue. Surveyor Candress (16522) also has got this incorrect npcflag 2 instead of 0. So my solution to making 2 draenei starter quests work as intended is as follows:
```sql
-- make Blood Elf Scout (16521) and Surveyor Candress (16522) attackable
UPDATE `creature_template` SET `npcflag` = 0 WHERE `entry` IN (16521,16522);
```
Notice that I don't have sniffs to verify this, but TDB 335.61 and the `creature` table in TDB 6.04 should confirm this `npcflag` value. None of their SAI lines do anything to change the npcflag of these creatures.

Right-click to attack creatures works OK in 6.x now, so this issue can be closed with the SQL above.

**Comment by Aokromes** [comment]
Better:
```sql
UPDATE `creature_template` SET `npcflag`=`npcflag` &~2 WHERE `entry` IN (16521, 16522);
```

**Comment by tkrokli** [comment]
OK, thanks. :+1:
