### ISSUE TITLE
 Dancing Rune Weapon [3.3.5a]

### ISSUE THREAD

**Issue by declart** [TrinityCore/TrinityCore#16023]
Dancing Rune Weapon still doesn't apply the disease and still doesn't copy all dk's attacks ( white or yellow damage ).
the sword seems to stand still and do nothing

https://github.com/TrinityCore/TrinityCore/commit/cc685ac334335d9f6a25a7c1c739a905f919328f

**Comment by Aokromes** [comment]
#6192

**Comment by declart** [comment]
@Aokromes the fix work correctly ?

**Comment by tkrokli** [comment]
@declart : issue [**[Core/Spells] Dancing Rune Weapon #6192**](https://github.com/TrinityCore/TrinityCore/issues/6192) is still open, that means this problem is still unsolved. Please post in issue #6192 if you have something to add to the conversation (if it has not been mentioned already). Read that issue thread and see what has been discussed, suggested and dismissed as not working to get a proper overview.
