### ISSUE TITLE
[6.x] DB/Quest: Hunting the Huntress Drop Rate

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#16064]
What is the drop rate set to for this quest? 
http://www.wowhead.com/quest=903/hunting-the-huntress

It seems the drop for this item required to fulfill this quest (http://www.wowhead.com/item=5096/huntress-claws) are set by retail at 50.08. I have killed about 50 of these mobs and not one has dropped for me yet. 

How do we adjust drop rates?

TrinityCore rev. 4695e23 2015-12-09 01:33:37 +0100 (6.x branch) (Unix, Release)

**Comment by BahDumbBugs** [comment]
Or is it just shitty luck? :)

**Comment by Saben65** [comment]
Table from TDB 3.3.5 is at the bottom. You can check yours by using the following query.

```SQL
SELECT * FROM `creature_loot_template` WHERE `Item`=5096;
```

```SQL
INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES 
(3425, 5096, 0, 80, 1, 1, 0, 1, 1, NULL);
```

**Comment by tkrokli** [comment]
Fuzzy logic that Blizz has kept the same ID for http://www.wowhead.com/quest=903/hunting-the-huntress because the quest has changed in 2 obvious places compared to 3.3.5a and earlier:
1) the quest name changed from "Prowlers of the Barrens" to "Hunting the Huntress" and
2) the target changed from "Savannah Prowlers" (male lions) to Savannah Huntress (female lions).

**Comment by tkrokli** [comment]
Just to pick up on the comments from @Saben65, @BahDumbBugs and the quest description:
```sql
SELECT * FROM `creature_loot_template` WHERE `Item`=5096;
```
from TDB 6.03 + updates, rev. 67c57c4b5be0 2015-12-19 23:43:39 +0100 (6.x branch):
```
 Entry    Item  Reference  Chance  QuestRequired  LootMode  GroupId  MinCount  MaxCount  Comment
------  ------  ---------  ------  -------------  --------  -------  --------  --------  ---------
  3425    5096          0      80              1         1        0         1         1  (NULL)
```
This is clearly wrong when you take into consideration that the quest has changed.
```sql
SELECT `entry`,`name`,`lootid`,`VerifiedBuild` FROM `creature_template`
WHERE `name` IN ('Savannah Prowler','Savannah Huntress');
```
```
 entry  name               lootid  VerifiedBuild
------  -----------------  ------  --------------
  3415  Savannah Huntress    3415          20173
  3425  Savannah Prowler     3425          20173
```
```sql
SELECT * FROM `creature_loot_template` WHERE `Entry` IN (3415,3425) AND `QuestRequired`!= 0;
```
```
 Entry    Item  Reference  Chance  QuestRequired  LootMode  GroupId  MinCount  MaxCount  Comment
------  ------  ---------  ------  -------------  --------  -------  --------  --------  ---------
  3415    4893          0      55              1         1        0         1         1  (NULL)
  3425    4893          0      55              1         1        0         1         1  (NULL)
  3425    5096          0      80              1         1        0         1         1  (NULL)
```
http://www.wowhead.com/item=4893/savannah-lion-tusk is no longer supposed to be in the game.
Based on these facts, I suggest the following solution:
```sql
--
-- remove loot item 4893, 'Savannah Lion Tusk' from the loot table
-- move loot item 5096 from Savannah Prowler (3425) to Savannah Huntress (3415)
DELETE FROM `creature_loot_template` WHERE `Item` IN (4893,5096);
INSERT INTO `creature_loot_template` (`Entry`,`Item`,`Reference`,`Chance`,`QuestRequired`,`LootMode`,`GroupId`,`MinCount`,`MaxCount`,`Comment`) VALUES
(3415, 5096, 0, 80, 1, 1, 0, 1, 1, NULL);
```
( I don't know the 6.03 equivalent of `item_template`, otherwise I had suggested deleting it there too.)

**Comment by Exodius** [comment]
I don't have the time to follow all issues lately and submit my input. I can just stroll through commits and see what has happened during the development.

@tkrokli When working with Quest Items, the best source of information about the drop rates is battle.net
I explained a little bit about drop rate "fluctuation" because armory does not supply the actual numbers and it seemed as it was accepted as a basic guideline by some people. https://github.com/TrinityCore/TDB_4.3.4_NLU/commit/6a40f587c88ec33e09bc7d64bfa0c781685752ba#commitcomment-2598694

Huntress Claws: http://eu.battle.net/wow/en/item/5096
Drop Chance: Guaranteed

Suggested Fix:
```sql
-- Huntress Claws: http://eu.battle.net/wow/en/item/5096
-- Drop Chance: Guaranteed
UPDATE `creature_loot_template` SET `Chance`=100 WHERE `Item`=5096;
