### ISSUE TITLE
[3.3.5][6.x][Core/Pooling System] ICC weekly quests

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#16076]
Revision: 94e4bddb903d581293b5a7f50f9b32d1262d2c20

What should happen:
The server should pick a random quest from the pool, save it in char db and keep spawning the same quest every time the server is restarted for a week, then start all over again by picking another quest.

What happens instead:
The server picks a random quest every time it's restarted, ignoring what is saved in char db.

Why this happens:
We have this in db:

pool_quest
entry   pool_entry  description
24871   5685    Securing the Ramparts ALLY (10)
24870   5685    Securing the Ramparts HORDE (10)
24872   5684    Respite for a Tormented Soul (10)
24873   5683    Residue Rendezvous (10)
24869   5682    Deprogramming (10)
24874   5681    Blood Quickening (10)

pool_pool
pool_id mother_pool chance  description
5683    5679    0   Residue Rendezvous (10)
5682    5679    0   Deprogramming (10)
5681    5679    0   Blood Quickening (10)
5684    5679    0   Respite for a Tormented Soul (10)
5685    5679    0   Securing the Ramparts (10)

pool_template
entry   max_limit   description
5679    1   General ICC 10man pool
5680    1   General ICC 25man pool
5681    1   Blood Quickening (10)
5682    1   Deprogramming (10)
5683    1   Residue Rendezvous (10)
5684    1   Respite for a Tormented Soul (10)
5685    2   Securing the Ramparts (10)
At server start, the pool 5679 is spawned: since is a pool of pools, SpawnPool<Pool> is called, which calls PoolGroup<T>::SpawnObject; this funcion immediately spawns an object from the pool without checking table pool_quest_save: here is the bug

How to fix this
We should add some check in SpawnPool<Pool> to call PoolGroup<Quest>::SpawnObject instead, when the pool has a pool of quest as a child. Probably also the function that saves the quests in db will have to be modified.

**Comment by Jildor** [comment]
I think this happens to with Wintergrasp weekly quests:
https://github.com/TrinityCore/TrinityCore/commit/629442f9c1242a946dfa68de7b3ee726ff1728f8

But no with Dalaran raid weekly quests like Patchwerk must die!

I don't know why doesn't happens with Dalaran weekly quests.

When you start server table pool_quest_save have the pools stored with pool_id and quest_id
when you restart server, pool_quest_save not have stored the values, are deleted, the pools still ingame, but in the next server restart, pool_quest_save store another quest_id because not have stored any data.

If you run the query in char db:
```sql
SELECT * FROM `pool_quest_save` WHERE pool_id IN (5678,5707,5708,5709,5710);
```

pool_id 5678 (dalaran raid weekly quests) always is stored in DB, but 5707,5708,5709,5710 (wintergrasp weekly quests) if are stored in DB, when restart are deleted and in the next restart, are insert another values.

I don't know why 😄

**Comment by Jildor** [comment]
Dalaran raid weekly pool (5678) is less than icc weekly pools (5679+). and wintergrasp weekly pools (5707+) are greater than ICC weekly pools, so it's possible something fails in ICC weekly pool and bug bigger pool quests (wintergrasp)???
@shauren

**Comment by Killyana** [comment]
Why Securing the Ramparts has `max_limit`=2 ?

**Comment by Treeston** [comment]
retest after a5e73e4

**Comment by Killyana** [comment]
Fixed.
