### ISSUE TITLE
3.3.5 Missing Text for Quest 2358

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#16078]
TrinityCore rev. 1f839b24340f 2015-12-19 14:34:05 +0100 (HEAD branch)
Missing 2 Text for Quest "Horns of Nez'ra"

OfferRewardText and RequestItemsText

http://www.wowhead.com/quest=2358/horns-of-nezra

**Comment by tkrokli** [comment]
OK, this quest is a 3.3.5-only quest. I tried to look up the texts in `broadcast_text`, but didn't find them.
I can only post a suggested solution based on the texts on the wowhead page in your link and the wowpedia page http://wow.gamepedia.com/Quest:Horns_of_Nez'ra .
```sql
--
-- Update (insert) missing CompletionText for Quest 2358, Horns of Nez'ra
UPDATE `quest_request_items` SET `CompletionText` = "Do you have the demon prince's horns?" WHERE `ID` = 2358;

-- Insert completely missing `quest_offer_reward` info
DELETE FROM `quest_offer_reward` WHERE `ID` = 2358;
INSERT INTO `quest_offer_reward` (`ID`,`Emote1`,`Emote2`,`Emote3`,`Emote4`,`EmoteDelay1`,`EmoteDelay2`,`EmoteDelay3`,`EmoteDelay4`,`RewardText`) VALUES
(2358, 0, 0, 0, 0, 0, 0, 0, 0, "To deny Ravenholdt the artifact, would be to deny one's own existence. Well done, <class>. You may yet walk among the assassins of Ravenholdt.$B$BAs a young rogue adventuring in Darkshore, I discovered a tea that replenishes energy in combat. It has served me well throughout the years and now I pass on a taste of the thistle tea to you. Drink of it when you tire, <name>, and fight with vigor once more!$B$B");
```
Can you test this and see if it works exactly as intended and Blizzlike? The 3.3.5 `quest_*` tables have had quite a few changes since August 2015, so I don't remember 100% if this is the correct way of doing it.
It would also be nice to have one of the TC developers confirming that the above method is correct.

**Comment by Tauriella** [comment]
It works :+1:

**Comment by tkrokli** [comment]
OK, thanks, glad to hear that. I only had time to check that it ran OK on the MySQL server.
Added just a couple of polishing touches to it now, so the commands are more complete. :santa:
