### ISSUE TITLE
Ulduar vehicles  BUG

### ISSUE THREAD

**Issue by danqu** [TrinityCore/TrinityCore#16105]
Core Rev: 3473732
TDB: 335.60

Open GM mode ， Salvaged Siege Turret Can see it ，Ordinary player mode, can not see the vehicle，Vehicle entry:33067

**Comment by Killyana** [comment]
I cannot reproduce.

**Comment by danqu** [comment]
@Killyana Did you not find the problem?

**Comment by Killyana** [comment]
For me Turrets are on the Salvaged Siege vehicles, sometimes the accessory is loaded before the vehicle on client side so it appears on the floor, there's already a ticket for this issue.

**Comment by tkrokli** [comment]
Do you mean like @Keader's **[[3.3.5] NPCs that are vehicles of other NPCs #15153](15153)** ?

**Comment by danqu** [comment]
@tkrokli    Yes, that is how to solve this problem?

**Comment by tkrokli** [comment]
@danqu : No, I meant to ask Killyana if that is what he referred to by "already a ticket for this issue".
Also No to "that is how to solve this problem", because there is no solution there (read issue #15153 ).

Since this issue is closed, please follow the other issue if that issue is the same as you have.

**Comment by danqu** [comment]
@tkrokli    Thank you very much, but this problem can not be solved!much to my regret!

**Comment by tkrokli** [comment]
Oh well. Not much we can do about it, except to hope someone will come up with a solution in the future.
After all, this is free software and the developers are not paid to work on it. Such is life.
