### ISSUE TITLE
[3.3.5] "You are dead" spam in ICC

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16102]
Branch 3.3.5, commit 0bb2ba7b35c7cd136b4371f6d284eba0bd34b6e5

While dead inside Icecrown Citadel, you are spammed with an error message "You are dead" approximately once a second.

**Comment by dr-j** [comment]
are you sure this is not an addon issue as cannot reproduce I am asking about addons since some addons eg dbm have option to announce in /say about certain spellcasts, aoe spells near you and if this triggers may cause these errors same if any other addon trys to do something you cant do while dead.

Only other way I can think of this happening is if you are selected for a invoker cast by a npc and the spell has cast time and/or the spell cannot be cast while dead but dont think this is the case.

**Comment by Treeston** [comment]
This was without any addons enabled. I'll try to get a more accurate repro when I get home.

**Comment by Shauren** [comment]
conditional breakpoint in sendcastresult and find out which spell it is?

**Comment by Treeston** [comment]
Yup, that's what I had in mind too.

**Comment by Treeston** [comment]
Repro attempts show that this was an issue related to my DB being messed up that merely started to show itself in ICC by coincidence. Closed.
