### ISSUE TITLE
[3.3.5] A Mammoth Undertaking (12607)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16160]
Branch 3.3.5, rev. 8a0bbc386982
[Quest: A Mammoth Undertaking](http://www.wowhead.com/quest=12607/a-mammoth-undertaking)
Mounted [Shattertusk Mammoth](http://www.wowhead.com/npc=28379/shattertusk-mammoth) keeps its AI, chasing mobs and fighting against the player's control.

**Comment by Killyana** [comment]
Related to: https://github.com/TrinityCore/TrinityCore/issues/7450

**Comment by dr-j** [comment]
seems setting passive + periodically updating home position solves vehicle issues with some of these vehicles ie seems the random movement is due to vehicle returning to home position on leaving combat, movement while in combat is due to vehicle itself attacking in defense,

Seems for vehicles which do not follow waypoints but are controlled by player doing this works not effective on vehicles which follow wp though as these will still stop when entering into combat.

**Comment by Treeston** [comment]
That's a colossal hack though. SmartAI _needs_ to be rewritten to properly handle a player-controlled state (see #16020 for discussion on this).

**Comment by Rushor** [comment]
well https://github.com/TrinityCore/TrinityCore/issues/7450 is pretty much the reason for this issue. so we will close this, i will add the description from this issue to https://github.com/TrinityCore/TrinityCore/issues/7450
