### ISSUE TITLE
[3.3.5] DB/Phasing: A Cold Front Approaches (13070)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16162]
Branch 3.3.5, rev. 8a0bbc386982

[Quest: A Cold Front Approaches](http://www.wowhead.com/quest=13070/a-cold-front-approaches)
[Siegemaster Fezzik](http://www.wowhead.com/npc=30657) is not initially visible upon accepting the quest. Zoning into his shack (or leaving the zone/returning) will properly update the phase and allow the player to see him.

**Comment by tkrokli** [comment]
Related to issue #10725, "**Quest phasing done on complete, not turn-in**", where the zoning and phasing issues in the Argent Vanguard has been discussed in detail.

**Comment by Killyana** [comment]
Looks to be a core issue, I will try to explain how the phasing works for this 2 quests (13070, 13141)

Phase 1: Set by the spell 57673, starts= none, ends= quest 13070 Rewarded
Phase 2: Set by the spell 57569, starts= quest 13070 Rewards, ends= quest 13086 Rewarded

Notice: The condition "quest 13070 Rewarded" is used to remove the aura 57673 and set the aura 57569, the problem here is the cast of 57569 fails. Looks like the spell is casted before the state of the quest changes.

To understand the issue enter the area, .quest add 13070 then .cast 57569 , you will get the message "you're in the wrong area" actually the area is not wrong but the condition to cast the spell is not met, and I think this happen when the quest 13086 is rewarded, as it tries to cast the spell before the quest status changes for the player.

**Comment by Aokromes** [comment]
5560c23 fixed this?

**Comment by tkrokli** [comment]
TrinityCore rev. 5800cd8248f3 2016-07-04 21:49:05 +0200 (3.3.5 branch) (Win64, Release, Static)
TDB 335.61 plus updates up to and including `2016_07_04_13_world.sql` (commit https://github.com/TrinityCore/TrinityCore/commit/5560c23d0aae95e483d6b8686f613fab8080c3ba)

No, Siegemaster Fezzik is still invisible until you go inside his hut and back out again (phasing). Even more confusing, you need to go back in and out again for the quest objective to be completed (Report to Siegemaster Fezzik at the Argent Vanguard in Icecrown). The phasing issue still exists for all the other NPCs too, they fade away as soon as quest is accepted, while the expected result is that they should not fade away before the quest is rewarded. Some images from my testing:

Opening the quest dialogue, the NPCs are still present before the quest is accepted:
![wowscrnshot_070516_045252](https://cloud.githubusercontent.com/assets/4903600/16572872/c8f853bc-426d-11e6-89a2-56308b9bd4f0.jpg)

Quest accepted, the NPCs have faded (phased) away.
![wowscrnshot_070516_045303](https://cloud.githubusercontent.com/assets/4903600/16572895/f86ac6e8-426d-11e6-82c0-e5062e443001.jpg)

Landing in front of Siegemaster Fezzik's hut, he is still invisible:
![wowscrnshot_070516_045406](https://cloud.githubusercontent.com/assets/4903600/16573042/b743bf1a-426f-11e6-8559-efb58107a62a.jpg)

I suppose you don't need my 2 extra images from moving in + out, then in and out of the hut again.

**Comment by Killyana** [comment]
Fixed by https://github.com/TrinityCore/TrinityCore/pull/17509
