### ISSUE TITLE
[3.3.5] Quest: Hand of the Oracles (The Oracles Reputation)

### ISSUE THREAD

**Issue by dixanackmad** [TrinityCore/TrinityCore#16425]
The quest '' Hand of the Oracles '' does not set the reputation with The Oracles to Honored
http://www.wowhead.com/quest=12689/hand-of-the-oracles
http://wowwiki.wikia.com/wiki/Oracles
Our revision: https://github.com/TrinityCore/TrinityCore/commit/b1d0855624d1c83850fc36f5242437d7f7c1336b

**Comment by dr-j** [comment]
Cannot Reproduce http://s2.postimg.org/qssgtpoop/Wo_WScrn_Shot_012916_194052.jpg

If you already have higher then honored rep for faction it wont set to honored thats intentional

I know this may not always work if player does not have both Oracles & Frenzyheart as encountered factions, same as how bloodsail and booty bay rep does not work properly if player only has one of the factions encountered.

**Comment by Rushor** [comment]
working like @dr-j explained
