### ISSUE TITLE
[3.3.5] DB/Quest: Pie for Billy (86)

### ISSUE THREAD

**Issue by Phentora** [TrinityCore/TrinityCore#16570]
After taking the (http://www.wowhead.com/quest=86/pie-for-billy) quest and starting to hunt for the required quest item (http://www.wowhead.com/item=769/chunk-of-boar-meat), it can be noticed that there is no info on the NPC that it drops the quest item.

Proof:https://www.youtube.com/watch?v=NmpU3ijE9jE
          https://www.youtube.com/watch?v=jEaiym2oABU

Core hash: 55100e57bfb5

**Comment by Saben65** [comment]
I think it is because [Chunk of Boar Meat](http://www.wowhead.com/item=769/chunk-of-boar-meat#comments) is a generic drop and thus not entered as a quest item in `creature_template_loot`. Therefore it doesn't show up in the tooltip when mousing over boars. 

I think blizz fixed this after Cata by changing the required item to [Tender Board Meat](www.wowhead.com/item=60401).

**Comment by Aokromes** [comment]
Indeed, it's that.
