### ISSUE TITLE
[3.3.5] Quest: Stunning Defeat at the Ring (11300)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16682]
3.3.5 fef06781f510b

[Quest: Stunning Defeat at the Ring](http://www.wowhead.com/quest=11300/stunning-defeat-at-the-ring)

Spawn behavior in general seems weird. Sometimes multiple spawns, sometimes no spawns at all. When it starts not spawning, it keeps not spawning until server restart even if you abandon/re-take quest.

Sorry for no detailed repro on this one.

**Comment by dr-j** [comment]
Well how this quest is currently scripted is that on quest accept first npc in chan is spawned however this npc sometimes enters into combat (and gets killed rather quickly) by other npcs which are spawned in the area but when this first npc is killed it spawns the next and son and upon killing the 3rd the npc which you actually need to kill for the quest will spawn.

Not sure if this is correct since have never done this quest on official

**Comment by Rushor** [comment]
the mechanic seems to be right, see http://www.wowhead.com/quest=11300/stunning-defeat-at-the-ring#videos:id=85617

**Comment by Treeston** [comment]
I just ran into another bug on this quest. When accepting, [Firjus the Soul Crusher](http://www.wowhead.com/npc=24213/firjus-the-soul-crusher) is spawned properly, enters combat for a split second, then leaves combat again (distance from spawn point, probably?). I then didn't pay attention for a few seconds because I was busy with another mob, and when I wanted to go aggro him, he had disappeared.

**Comment by Aokromes** [comment]
no answer after 2 years, if this bug is still valid post results with updated core.
