### ISSUE TITLE
[3.3.5] DB/Event: Game event start dates

### ISSUE THREAD

**Issue by edward4885** [TrinityCore/TrinityCore#16705]
**Description**: Fix timer for Love in the air.

**Current behaviour**: In game.

**Steps to reproduce the problem**:

1.Wrong Timer for event.

**Branch(es)**: 335

**TC hash/commit**:
TrinityCore rev. 1c86d286d4f9+ 2016-02-26 17:54:46 -0300 (master branch) (Unix, Release)
**TDB version**:
TDB 3.3.5 60
**Operating system**:
Linux & Windows

FIx is : Apply on table world db.
```
UPDATE `game_event` SET `start_time`= '2016-02-15 19:01:00' WHERE `eventEntry`= 8;

**Comment by tkrokli** [comment]
Your suggested fix could be valid (I don't know), just a few codestyle details in your query to be fixed:
```sql
UPDATE `game_event` SET `start_time`= '2013-02-15 19:01:00' WHERE `eventEntry`= 8;
```
- no need for `LIMIT 1` because there is only 1 event row in that table where `eventEntry`= 8
- parentheses `( )` not needed at that end part, it is a format chosen by your editor app
- generally speaking, TC don't use single quotes `'8'` around numbers if they count as number values (date/time group obviously needs quoting because of spaces and punctuation)

**Comment by edward4885** [comment]
Ho thanks man :)

**Comment by joschiwald** [comment]
we live in year 2016

**Comment by edward4885** [comment]
Fix now :)

**Comment by Aokromes** [comment]
Since it already expired it's useless to push it with 2013 or 2016, and on 2017 very likely will use a different date.

**Comment by edward4885** [comment]
Ok ...

**Comment by Demonid** [comment]
Should we update all world events to these dates?

http://www.wowhead.com/events#holidays:0+2+1

**Comment by Aokromes** [comment]
IMHO, the priority must be ingame calendar, then wowhead.

**Comment by Kittnz** [comment]
Love is in the air is not even in that @Aokromes

**Comment by Aokromes** [comment]
I don't have added it because no data on wowhead/ingame wow 6 calendar for 2017.

**Comment by Aokromes** [comment]
Updated by 396498b

**Comment by Aokromes** [comment]
added Love is in the air for 2017 retail.

**Comment by SnapperRy** [comment]
Event start dates updated to 2017. Closing this, since every date has to be updated yearly anyway :P
