### ISSUE TITLE
[3.3.5] Quest: Fel Spirits (10909)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16746]
3.3.5 8e152e0d4a553bdc215d2c7fda41083b5382b235

[Quest: Fel Spirits](http://www.wowhead.com/quest=10909/fel-spirits)

Multiple issues:
- Players can right-click the spawned [Anchorite Relic](http://www.wowhead.com/object=185298/anchorite-relic), "using" it and despawning it. It should not be usable.
- The Anchorite Relic does not affect additional mobs pulled into its area of affect after it has been deployed. This makes the quest very difficult to complete.

**Comment by Rushor** [comment]
```sql
UPDATE `gameobject_template` SET `flags` = 16 WHERE `entry` = 185298;
```

**Comment by dr-j** [comment]
Affraid the Relic is meant to be clickable the bug is the sai action on the go to despawn on been clicked

First a comment from wowhead

~~~
The spirits will die on their own if you avoid fighting them for too long, and you won't get credit for the kill. Found this out by polymorph-chaining to regen mana, and the spirit eventually just dropped dead.

Also, don't be distracted by the fact that you can click on the Anchorite Relics. Despite Blizzard's mistake of making your cursor change to the gear icon on them, clicking on the relics doesn't do anything.

And to reinforce what Gandalug said, only the berserkers will release spirits upon death.
~~~

and some sniff data which also suggests this go is clickable but nothing happens

~~~
ClientToServer: CMSG_GAMEOBJ_USE (0x00B1) Length: 8 ConnIdx: 0 Time: 03/01/2010 18:59:47.000 Number: 121820
GUID: Full: 0xF11002D3D213537C Type: GameObject Entry: 185298 Low: 1266556

ClientToServer: CMSG_GAMEOBJ_REPORT_USE (0x0481) Length: 8 ConnIdx: 0 Time: 03/01/2010 18:59:47.000 Number: 121821
GUID: Full: 0xF11002D3D213537C Type: GameObject Entry: 185298 Low: 1266556
~~~
