### ISSUE TITLE
[3.3.5] Player::SendTalentsInfoData: Spamming in console

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#16781]
**Description**: After create Hunter and tame some pet, this mensage spamming in console.

**Steps to reproduce the problem**:
1.  Create a Hunter
2.  Tame Some Pet
3.  Console Spam !

https://gist.githubusercontent.com/Keader/5033ced7b9f9aa37f18e/raw/b29ed14cf925179b73c803d4a5c4564d6d650cb4/TC.txt

**Branch(es)**: 335

**TC hash/commit**:  fdc8b7b38a2aa974427e79454e1f94ef67a133ea

**TDB version**: TDB 335.60

**Operating system**: Win10.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Aokromes** [comment]
Really annoying bug.

**Comment by ariel-** [comment]
Issue caused by bff45bbb146b24b90e1d8134bf3dc096ab0e9569.

The log is inaccurate too: It says `Player::SendTalentsInfoData` when in reality it's being generated from `Player::BuildPetTalentsInfoData`

https://github.com/TrinityCore/TrinityCore/blob/bff45bbb146b24b90e1d8134bf3dc096ab0e9569/src/server/game/Entities/Player/Player.cpp#L25213
