### ISSUE TITLE
[3.3.5] [FIX] Console Errors Fix

### ISSUE THREAD

**Issue by cooler-SAI** [TrinityCore/TrinityCore#16807]
https://github.com/TrinityCore/TrinityCore/commit/576f37934416262e0d71ceff3635b06efb9e314e

Fix For Last Core Build Console Errors

```sql
UPDATE creature_template SET ScriptName='npc_tirion_fordring' WHERE entry=12126;
UPDATE `creature_template` SET `ScriptName` = 'npc_archmage_malin' WHERE `entry` = 2708;
UPDATE `creature_template` SET `ScriptName` = 'npc_lady_katrana_prestor' WHERE `entry` = 1749;
UPDATE `creature_template` SET `ScriptName`= "npc_netherweb_victim" WHERE `entry` =22355;
```

**Comment by Aokromes** [comment]
3.3.5a TC don't have startup errors atm.

**Comment by cooler-SAI** [comment]
hm, don't know, Installed Last TDB 335.60, then applyed all sql updates and have this errors

**Comment by tkrokli** [comment]
@cooler-SAI : those scripts were removed because 
- I moved npc_tirion_fordring to SAI because it is a quest with Gossip window actions + condition.
- NPC 1749 (npc_lady_katrana_prestor) and NPC 2708 (npc_archmage_malin) were removed in patch 3.0.2 because they were part of the alliance Onyxia key chain in Classic WoW & TBC.
- **Naios** removed `npc_netherweb_victim` in https://github.com/TrinityCore/TrinityCore/commit/ecd74a8 & **dr-j** converted it to SAI in https://github.com/TrinityCore/TrinityCore/commit/546c8a5

**Comment by cooler-SAI** [comment]
@tkrokli, thanks, I already Updated Core and DB and all good :-)
