### ISSUE TITLE
[335] Moon Priestess Amara double spawn

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#16829]
**Description**:

Moon Priestess Amara and her companions are spawned twice with different dynamic guids

**Current behaviour**:

The dynamic guid system appears to be spawning Moon Priestess Amara and her followers more than once. They end up passing each other on the road in Teldrassil.

Moon Priestess Amara:
  Entry: 2151
  DB GUID: 46394
  current GUID 1: 3169
  current GUID 2: 1001

Huntress Nhemal
  Entry: 10604
  DB GUID: 46414
  current GUID 1: 3170
  current GUID 2: 1002

Huntress Yaeliura
  Entry: 10606
  DB GUID: 46416
  current GUID 1: 3171
  current GUID 2: 1003

*NOTE:* See edits at end of post

**Expected behaviour**:

There should only be one spawn of each of them

**Steps to reproduce the problem**:

1. Go to Dolanaar
2. Wait
3. 

**Branch(es)**: 335

**TC hash/commit** : cebdf03349ed0c50a40cf52ddae887cf666d1eb5

**TDB version**: TDB_full_world_335.60_2015_11_07.sql

**Operating system**: Windows XP / 7

__*Edit 2016-03-23:*__

I don't know if this has any bearing but Amara is a questgiver and I only noticed the double spawns when I went to turn in the quest. Since then I've only seen a single spawn.

Also, she stops patrolling while her gossip is displayed but her followers continue pathing (old bug, actually). Is it possible that this causes a duplicate spawn?

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Kittnz** [comment]
@r00ty-tc i think this might interest you

**Comment by tkrokli** [comment]
rev. 48a12cb2f551 2016-03-26 09:49:16 +0100 (3.3.5 branch) (Win64, Release) / TDB 335.60

To my big surprise, all 3 of the riders (Huntress Nhemal, Huntress Yaeliura and Moon Priestess Amara) stopped at the very moment I interacted with the quest giver Moon Priestess Amara to pick up the 2 quests available at level 6 (night elf

**Comment by MrSmite** [comment]
@tkrokli Thanks, looks like the movement issue may have been fixed recently. I still can't figure out why there were two spawns though. They only showed up after I took the quest "The Road to Darnassus". 

Once I handed it in and left the area, there was only one spawn. The second spawn group never reappeared while I continued questing.

**Comment by Killyana** [comment]
I fixed the formation here https://github.com/TrinityCore/TrinityCore/commit/f835d16b2c878ac6e88b4974ff22182686986cc7
I don't have any Idea from where the second spawn appears, I never saw that before.

**Comment by tkrokli** [comment]
I can't say I have noticed a second spawn, but then again, I never looked for something like it either. Last night while checking the NPCs and the quest, most of it looked OK to me, except for a brief glitch: When I came back to Dolanaar after handing in quest to Amara and also moving around a lot in the Teldrassil zone before returning to Dolanaar, I found only the 2 hunters mounted and standing still at the entrance of Dolanaar. After a game & server restart, the riders were complete again, moving as expected.

**Comment by MrSmite** [comment]
> I don't have any Idea from where the second spawn appears, I never saw that before.

Same, it was the first time I saw it too.

I took the quest "The Road to Darnassus" and then ran off to work on it. I got sidetracked with herb gathering so it took me about an hour to finish. When I met up with Amara on the road, as I was speaking with her another copy of her and her followers walked right through us. The second copy also had the quest turn-in mari over her head ("?").

I completed the turn-in and logged out. So far I have not seen the double spawns again.

**Comment by Aokromes** [comment]
Have you tried to update your core? because i am quite sure somewhere this year this issue was fixed.

**Comment by tkrokli** [comment]
Thanks, will make a new  attempt to replicate the issue within a few days (or the next weekend if needed).

**Comment by MrSmite** [comment]
> Have you tried to update your core? because i am quite sure somewhere this year this issue was fixed.

Which issue? The followers stopping or the double spawn?

**Comment by Aokromes** [comment]
The double spawn, the patrolling thing was fixed by killyana few days ago.

**Comment by r00ty-tc** [comment]
https://github.com/TrinityCore/TrinityCore/commit/fe2a0fda4464effeb2fb655da84a0460328b1aeb from original issue https://github.com/TrinityCore/TrinityCore/issues/16462

Would only happen if you have grid unload enabled, and with that commit it should resolve the problem. There is a really rare series of events that could potentially create a double spawn still. But, much much less likely.

If you knew how to do it, you could potentially keep making copies.

**Comment by MrSmite** [comment]
@r00ty-tc Thanks, I do actually have grid unload enabled though I increased the time by quite a bit.

I do have one curiosity about that commit you linked:
```
// If only dead instance(s) exist, despawn them and spawn a new (maybe also dead) version
```
Why despawn and respawn a creature that's dead instead of just leaving the dead one? Finally, would it perhaps be better to never unload grids if an NPC has a path?

PS: I'm going to close this ticket since it looks like the issue was resolved. Feel free to continue to comment if you wish.

**Comment by r00ty-tc** [comment]
@MrSmite the reason for that is because of the following situation (imagine that code wasn't there). It's actually the correct thing to do. If it's time to respawn and there is somehow already a corpse around then we can't leave that around to respawn later (even though the event would likely be caught in the Load action again).

There's actually other situations where this can always go wrong (creatures can be lost completely) because of grid loading. In this situation for example. Say, there's a lot of players in the home grid.The creature moves into another active grid (there's players there now). But the players leave and that grid becomes unloaded.

When players go back to that grid (maybe looking for this NPC) it won't be there (since there's no storage of roaming NPCs at grid unload). It also won't "respawn" either because the home grid never unloaded.

The only way around this is to have some kind of storage when a grid unloads of "travelling creatures" (creatures which were in the grid at unload, but don't have the grid as their home location). I think this is a lot of work to support grid unloading which should be used by less and less people these days, as memory increases in computers generally.

But, maybe there can be a general consensus as to whether this is a good feature to have.

**Comment by Shauren** [comment]
The situation of "lost" creatures - find why https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Maps/Map.cpp#L1463 could possibly be not called

**Comment by Shauren** [comment]
I don't think creatures can be "lost" like you described - this code runs at grid unload https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Grids/ObjectGridLoader.cpp#L31 moving all creatures to their home grid if it isn't the current one.

**Comment by r00ty-tc** [comment]
Aha. OK, so with the commit I made to solve the duplicates, it shouldn't be possible to end up with none spawned as a I feared. That's good to know at least.

I was working on an "in theory it could happen" scenario. I'd never tested it was actually possible.

**Comment by MrSmite** [comment]
@r00ty-tc I wonder, how much work would it be to consider the home grid of a pathing NPC to be all grids in the path? Then a searcher could just iterate over them and see if it needs to be respawned. A flag in the DB could indicate wether thie spawn needs special handling.

A long time ago I submitted a patch that keeps the grids of flightmasters from unloading so as you fly in on a taxi you don't get the occasional lag that was caused by a grid load on a small population server. I suppose something like this wouldn't be as simple ;)

**Comment by Kittnz** [comment]
@MrSmite what about BaseMapLoadAllGrids ?

**Comment by MrSmite** [comment]
> what about BaseMapLoadAllGrids ?

Wouldn't something like that cause a lag spike? It would end up loading grids that aren't in view.

**Comment by r00ty-tc** [comment]
@MrSmite 

> Wouldn't something like that cause a lag spike? It would end up loading grids that aren't in view.

Only during server load. But it wouldn't solve your problem and uses around 5GB of ram.

> I wonder, how much work would it be to consider the home grid of a pathing NPC to be all grids in the path?

I'm not sure what this would achieve. We can already check if a creature exists and is alive (provided the grid is loaded). With the check Shauren mentions this will protect against the only alive instance of a creature being stranded in an unloaded grid. The change I referenced protects against the opposite. So in total this problem is solved.

If it's another issue, we've discussed before activating creatures that roam through a grid based on a player being within visual range of any point on the path. But, that's another story entirely.

**Comment by MrSmite** [comment]
> If it's another issue, we've discussed before activating creatures that roam through a grid based on a player being within visual range of any point on the path. But, that's another story entirely.

Yeah, what I was trying to describe was a system where the core would never unload a grid if it was part of an NPC path. That would allow the NPC to always path, even if no players were in the area.

The other benefit to this is that it makes it so you can't "park" npcs. For example, there's a group of Horde NPCs that are supposed to patrol the road on the Southern Barrens. With the current system, if you see them and run out of range and the grid then unloads, they will be right where you left them when you come back. If they continued their path because the grid never unloaded then it would be more natural.

**Comment by r00ty-tc** [comment]
The framework exists to mark grids to not be unloaded in dynamic spawning branch. But it won't really offer much of an advantage really.

**Comment by MrSmite** [comment]
> The framework exists to mark grids to not be unloaded in dynamic spawning branch. But it won't really offer much of an advantage really.

Perhaps not with the double spawn issue but from a "realism" standpoint it would allow pathing NPCs to continue pathing even when there's nobody around.

**Comment by r00ty-tc** [comment]
No. That's the mistake too many people make. If you set grids to never unload and load them all. The pathing creatures still won't come to you currently because even if they're loaded, they're only activated if a player comes within visible range of the cell (not grid) they're in.

Hence the solution to this specific problem lies elsewhere and is part of a bigger solution. One that covers other scenarios (long range visible and active like Fel reaver vs active but normal visibility etc).

**Comment by MrSmite** [comment]
Ah, ok. That makes sense. The Fel Reaver is actually a good example too.
