### ISSUE TITLE
[3.3.5] PvP-enabled creatures fighting in a Sanctuary area

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16830]
3.3.5 f37682b

Repro:
1. Use the portal to Blasted Lands
2. Walk through the Dark Portal into Outland
3. Walk towards the hostile faction's emissary
4. They will engage you in combat

Expected:
4. They will not engage you, because The Stair of Destiny is a Sanctuary area.

**Comment by dr-j** [comment]
Well appears nethergarde infantry have wrong unit flags or should be 832 currently 64

http://www.wowhead.com/npc=16831/nethergarde-infantry

(16831, 0, 59, 60, 1756, 0, 1, 1.142857, 2000, 2000, 1, 832, 2048, 0, 0, 1), -- 16831

Also Thrallmar Grunt http://www.wowhead.com/npc=16580/thrallmar-grunt

(16580, 0, 68, 68, 714, 0, 1, 1.142857, 2000, 2000, 1, 33536, 2048, 0, 0, 1), -- 16580

Thrallmar Marksman http://www.wowhead.com/npc=16582/thrallmar-marksman

(16582, 0, 60, 60, 714, 0, 1, 1.142857, 2000, 2000, 1, 768, 2048, 0, 0, 1), -- 16582

since only npcs at stairs of destiny should be immune flags probably should be set via creature and not creature_template

**Comment by dr-j** [comment]
~~~sql
UPDATE `creature` SET `unit_flags`=832 WHERE  `guid`IN(57890,57891) AND `id`=16831;
UPDATE `creature` SET `unit_flags`=33536 WHERE  `guid`IN(57492) AND `id`=16580;
UPDATE `creature` SET `unit_flags`=768 WHERE  `guid`IN(57542,57543) AND `id`=16582;
UPDATE `creature` SET `unit_flags`=768 WHERE  `guid`IN(58137) AND `id`=16864;
