### ISSUE TITLE
[3.3.5] Creature: Proto-Drake Egg (23777)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16900]
3.3.5 f37682b

[Creature: Proto-Drake Egg](http://www.wowhead.com/npc=23777/proto-drake-egg) turns to face player that hits it. It shouldn't. It's an egg. Eggs don't turn.

**Comment by Kodekc** [comment]
```sql
-- Proto-Drake Egg
UPDATE `creature_template` SET `unit_flags`='262148' WHERE  `entry`=23777;
```
Add UNIT_FLAG_STUNNED

**Comment by dr-j** [comment]
Believe changing unit flags on these would be a hack as in sniff these have no auras and unit_flags =0 yet these still dont move when attacked, however on tc these already have unit flags 4 disable move.

**Comment by Treeston** [comment]
They don't move, they just turn.

**Comment by dr-j** [comment]
well theres nothing in the script for these which targets player all actions use self as target so this is probably due to combat,

The following removes the unit_flag hack and the eggs still dont move however they still turn upon entering combat when not killed with a single hit.

~~~sql
DELETE FROM `smart_scripts` WHERE  `entryorguid`=23777 AND `source_type`=0 AND `id`=6 AND `link`=0;

UPDATE `smart_scripts` SET `link`=6 WHERE  `entryorguid`=23777 AND `source_type`=0 AND `id`=1 AND `link`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(23777, 0, 6, 0, 61, 0, 100, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Proto-Drake Egg - On Reset - Set Passive');


UPDATE `creature_template` SET `unit_flags`=0 WHERE  `entry`=23777;
