### ISSUE TITLE
[3.3.5] NPC - Atal'alarion <Guardian of the Idol>

### ISSUE THREAD

**Issue by Kodekc** [TrinityCore/TrinityCore#16946]
http://www.wowhead.com/npc=8580/atalalarion
http://wotlk.openwow.com/object=148831
ScriptName: go_atalai_statue

.go object 5521
The first one that lights will be SOUTH. From there follow this order until all six are lit up.
S, N, SW, SE, NW, NE

After activation of the statues is not summon Atal'alarion

Branch: 3.3.5
TC hash/commit: d59e1b2
TDB version: 335.61

**Comment by dr-j** [comment]
Well thought there was a recent commit to fix this, had not actually personally tested this since but have not heard any comments about this not working again since my original "hack" fix for this which I will not post here as used bunnies which are not meant to exist i sunken temple but these statues have event - scripts

S 3094
N 3095
SW 3097
SE 3098
NW 3099
NE 3100

**Comment by Kodekc** [comment]
I am very sorry, really missed update https://github.com/TrinityCore/TrinityCore/commit/768a5cf354b447e19e7e5b12c78dc4920d8b1caa
