### ISSUE TITLE
Some GO respawn timer fix for Quest 3361

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#16977]
```sql
-- Wrong respawntimer for Quest GameObjects
-- Felix's Bucket of Bolts, Felix's Chest, Felix's Box
UPDATE `gameobject` SET `spawntimesecs` = 10 WHERE `guid` IN (1386,1394,1380);
```
PS: Tested on live Server

http://www.wowhead.com/quest=3361/a-refugees-quandary

**Branch(es)**: 335/6x

**TC hash/commit**:
TrinityCore rev. e38e1c0c549c 2016-04-15 01:56:05 +0200 (335 branch)

**TDB version**:
.61
**Operating system**:
Win7

**Comment by Tauriella** [comment]
Sorry i have edited my first post i have changed the id to guid

**Comment by tkrokli** [comment]
Is there a practical reason why you changed to `guid` instead of `id` in this case? If the object only has 1 spawned entry in the `gameobject` table, it is safe to use the `id` value. Theoretically, `guid` could change, so `id` is usually safer, given that there is only 1 entry (`id`) of that object.

IMHO it is more practical to use `guid` when you want to change specific separate spawned objects from a group of objects with the same `id`, while leaving identical objects in other gps locations unchanged (when there are multiple spawns of the same `id`, but with different GUIDs).

**Comment by Aokromes** [comment]
Yeah Better ID than guid.

**Comment by Tauriella** [comment]
I think you mean GUID is safer in gameobject.sql a GUID number occurs only once

**Comment by Aokromes** [comment]
No, guid can change, if that object is only target of quest the id will continue to be the same, the guid can be changed and be diferent object.

**Comment by tkrokli** [comment]
As long as there is only 1 `guid` in use by a gameobject, it is safer to use `id` in your SQL query. It will only be practical to use `guid` if there are more than 1 `guid` for the same type (`id`) of gameobject.

I am sure that the TC collaborators will decide if your suggested change is correct, but it would also be nice for us other users / readers to know if you have got a source or some proof for that DB change.
