### ISSUE TITLE
[3.3.5] Hodir- NPC's are being affected by biting cold

### ISSUE THREAD

**Issue by Bullfface** [TrinityCore/TrinityCore#16999]
NPC's during Hodir encounter are getting high amounts of stacks of biting cold and dying super quickly.
http://www.wowhead.com/npc=32845/hodir#article (NPC links)

NPC's suffer from biting cold http://www.wowhead.com/spell=62039/biting-cold, thus dying and making the fight much more difficult and impossible for Hardmode

NPC's should not be affected by biting cold

Go to Ulduar and start Hodir encounter
Break NPC's out of Flash Freeze

3.3.5

Commit hash:    4afea55b2c6035a986162a8d800a57fb1ae4cf98

TDB 335.60

Win7

**Comment by adeutscher** [comment]
I originally made a stab at this issue with #17313 while testing something else involving Hodir, but @joschiwald pointed that the true problem is that the `SPELL_ATTR3_ONLY_TARGET_PLAYERS` flag that is present on Biting Cold is being ignored.

To confirm my new understanding of Biting Cold, it is in fact two spells:
* http://wotlk.openwow.com/spell=62038 - '38 is a periodic dummy effect. This aura appears in the combat log, but is not displayed immediately on the default buff/debuff display. This is the Biting Cold that the aura script is written for.
* http://wotlk.openwow.com/spell=62039 - '39 is the damage effect. Fairly straightforward paintimes. This appears on the default buff/debuff display.

When Hodir is engaged, '38 is applied to all targets, so this is the point that needs to be blocked. My original idea was a bit of a hack because the periodic script would still be unnecessarily run on each NPC.

**Comment by mik1893** [comment]
fixed by #17321

**Comment by ariel-** [comment]
Fixed by 449ec0d6ff74ccd1874bc09073353d97c1d0151c
