### ISSUE TITLE
[3.3.5] Core/Mechaic: Crash after skipping character cinematic

### ISSUE THREAD

**Issue by dimasiu** [TrinityCore/TrinityCore#17077]
**Description**: The server crashes after skipping the character cinematic immediately.

**Current behaviour**: The server crashes after skipping the cinematic.

**Expected behaviour**: The server shouldn't crash by skipping the cinematic.

**Steps to reproduce the problem**:

1. Create a new character
2. Enter World
3. Spam Esc really fast to skip the cinematic immediately (or use valgrind to slowdown the server)
4. Server crashes

**Crashlog**: https://gist.github.com/dimasiu/5a70061ed53a9efcd7b5b051d0fc0705

**Branch(es)**: 335 

**TC hash/commit**:  d82534a7bbd401f4b672786749f10f5a95f6e76c

**TDB version**:  TDB 335.61

**Operating system**:  Arch Linux x86_64

**Linking model**: static

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Aokromes** [comment]
So, that was the reason, thx for the repro.

**Comment by Treeston** [comment]
Hmmmmmmm cinematic code.

Paging @r00ty-tc

**Comment by Nawuko** [comment]
Hmm, i really tried to recreate the crash but without success, using botfarm (with 4000 bots logging in at the same time) and an autohotkey script to spam ESC as fast as possible on a debug session profiling (call stack/heap analyse) with VS 2015 and no crash :(

**Comment by jackpoz** [comment]
Some crashes just take a breakpoint well set or a Sleep() at the right place to be triggered

**Comment by r00ty-tc** [comment]
If it's the same as other crash reports, it's assert on destroy temp summon with seer still attached. 

My thinking is that potentially the end cinematic is sent before the next camera (which starts the server side action). Leaving it running forever. The temp summon is then later destroyed (probably by grid unload) and that's where it goes wrong. 

If that's the case then the fixes (along with redesign) I've done in the cinematic changes branch on my repo might well solve it already. 

I'll see if I can reproduce on my debug branch and then compile the changes debug and valgrind to see if it's solved. Later, when I'm back home

**Comment by r00ty-tc** [comment]
I checked on the newer code and it also still happens. It's weird, because I thought the reason might be because the events fired in the wrong order. But that's not the case. I added debug messages to both event handlers. It's not the case. It looks to me like the seer is somehow added AFTER the object is removed. I thought it was because the client requests it with the far sight opcode but I see an error to say the object already doesn't exist is shown. So, it must be something else.

**Comment by r00ty-tc** [comment]
Try this (of course for you applying to Player.cpp not CinematicMgr.cpp).

```Diff
diff --git a/src/server/game/Entities/Player/CinematicMgr.cpp b/src/server/game/Entities/Player/CinematicMgr.cpp
index c0e6fed..07bf733 100644
--- a/src/server/game/Entities/Player/CinematicMgr.cpp
+++ b/src/server/game/Entities/Player/CinematicMgr.cpp
@@ -84,8 +84,10 @@ void CinematicMgr::EndCinematic()
     m_activeCinematicCameraId = 0;
     if (m_CinematicObject)
     {
-        if (player->m_seer && player->m_seer == m_CinematicObject)
-            player->SetViewpoint(m_CinematicObject, false);
+        if (WorldObject* vpObject = player->GetViewpoint())
+            if (vpObject == m_CinematicObject)
+                player->SetViewpoint(m_CinematicObject, false);
+
         m_CinematicObject->AddObjectToRemoveList();
     }
 }
```

**Comment by dimasiu** [comment]
Ok, i tried both (the patch and your branch) and the crash does not occur anymore.
Thank you.

**Comment by tkrokli** [comment]
Thanks for testing and reporting back. I have not been able to provoke this issue alone, on Windows.

**Comment by ariel-** [comment]
After applying the patch, I get this output at console:

```Player Crashtest (GUID Full: 0x0000000000000004 Type: Player Low: 4) requests non-existing seer GUID Full: 0x0000000000000000 Type: None Low: 0```

Is this expected?

**Comment by r00ty-tc** [comment]
@ariel-  you would have received that message JUST before the crash before the patch. 

It's because the server sent to the client that far sight was about to happen, the cinematic ended, and the farsight removed and object destroyed. After the object is destroyed the client sends the far sight opcode and the server states that it cannot find the object.

At least that's what I think is happening. You should only receive the message on the rare time when the end cinematic is received before the farsight is properly established.

**Comment by Aokromes** [comment]
Test after de918a0

**Comment by dimasiu** [comment]
I'm sorry for the late response. I just tested it on https://github.com/TrinityCore/TrinityCore/commit/0d5adf356ebaf57507c2a937e47db5e6b97c3e22 and could not reproduce the problem. So this issue seems to be solved.
