### ISSUE TITLE
[3.3.5] Quests: Priest class quests

### ISSUE THREAD

**Issue by sinisterDei** [TrinityCore/TrinityCore#17075]
This entry is regarding the following priest class quests:
5624 - Garments of the Light
5625 - Garments of the Light
5650 - Garments of Darkness
5621 - Garments of the Moon
5648 - Garments of Spirituality

and is regarding the following associated NPCs respectively:
12423 - Guard Roberts
12427 - Mountaineer Dolf
12428 - Deathguard Kel
12429 - Sentinel Shaya
12430 - Grunt Kor'ja

**Current behaviour**:
In all the quests, the new priest is assigned to both heal and buff an assigned NPC. Currently, that NPC is not interactive to the player and attempts to heal or buff have no effect on the NPC.
This appears to be due to improperly set **unit_flags** for the associated NPCs.

**Expected behaviour**: 
Obviously, in order to pass the quest the player should be able to heal the NPC.

**Steps to reproduce the problem**:

1. Make a priest ( I used a troll )
2. Level to 5
3. Attempt one of the quests listed above. For trolls, it's 5648

**Branch(es)**: 335 

**TC hash/commit**:  02d7df6aa435 

**TDB version**:  TDB 335.61

**Operating system**:  Windows Server 2012 R2

**Linking model**: static/dynamic Sorry, don't know that one.

Database fix is included:
[Fix-Priest-Class-Quests.txt](https://github.com/TrinityCore/TrinityCore/files/246304/Fix-Priest-Class-Quests.txt)

**Comment by Kittnz** [comment]
```SQL
/*
Fix the following NPCs to be healable as part of Priest class quests
QuestID - QuestName - CreatureID - CreatureName
5624 - Garments of the Light - 12423 - Guard Roberts
5625 - Garments of the Light - 12427 - Mountaineer Dolf
5650 - Garments of Darkness - 12428 - Deathguard Kel
5621 - Garments of the Moon - 12429 - Sentinel Shaya
5648 - Garments of Spirituality - 12430 - Grunt Kor'ja
*/

UPDATE `world`.`creature_template` SET `unit_flags`='8' WHERE `entry`='12423';
UPDATE `world`.`creature_template` SET `unit_flags`='8' WHERE `entry`='12427';
UPDATE `world`.`creature_template` SET `unit_flags`='8' WHERE `entry`='12428';
UPDATE `world`.`creature_template` SET `unit_flags`='8' WHERE `entry`='12429';
UPDATE `world`.`creature_template` SET `unit_flags`='8' WHERE `entry`='12430';

```

**Comment by tkrokli** [comment]
Please don't use apostrophes (single quotation marks) around numbers (this is what it should look like):
```sql
-- Fix the following NPCs to be healable as part of Priest class quests:
--
-- QuestID - QuestName        - CreatureID - CreatureName
--
-- 5624 - Garments of the Light    - 12423 - Guard Roberts
-- 5625 - Garments of the Light    - 12427 - Mountaineer Dolf
-- 5650 - Garments of Darkness     - 12428 - Deathguard Kel
-- 5621 - Garments of the Moon     - 12429 - Sentinel Shaya
-- 5648 - Garments of Spirituality - 12430 - Grunt Kor'ja

UPDATE `creature_template` SET `unit_flags` = 8 WHERE `entry` = 12423;
UPDATE `creature_template` SET `unit_flags` = 8 WHERE `entry` = 12427;
UPDATE `creature_template` SET `unit_flags` = 8 WHERE `entry` = 12428;
UPDATE `creature_template` SET `unit_flags` = 8 WHERE `entry` = 12429;
UPDATE `creature_template` SET `unit_flags` = 8 WHERE `entry` = 12430;
```
2 dashes is preferred as SQL comment characters, although it is not as important as the numbers format.

**Comment by sinisterDei** [comment]
Sounds good; to be honest, I copy/pasted the entries out of MySQL workbench, so I blame it for the formatting.

Also, It's possible the unit_flags should be set to 4104; I'm not sure which is correct/more blizzlike. Setting unit_flags to 8 allows the quest to be completed, but I'm not sure the interaction differences with players of the opposite faction.

**Comment by sinisterDei** [comment]
It would appear your fix is much better and more thought out, which doesn't surprise me. Adding the UNIT_FLAG_PVP_ATTACKABLE definitely fixes the problem, so I'd say your line is all that needs be done to the database.

**Comment by tkrokli** [comment]
OK, but I have not had time to test this myself in-game, so it may take a day or 2 before I can verify it
(busy elsewhere for the rest of the day and evening). Other users: feel free to test this, before & after.

**Comment by tkrokli** [comment]
TrinityCore rev. d82534a7bbd4 2016-05-02 22:22:17 +0200 (3.3.5 branch) (Win64, Release)
TDB 335.61 + updates up to and including `2016_05_02_01_world.sql`

![wowscrnshot_050416_041432](https://cloud.githubusercontent.com/assets/4903600/15004276/51a83f5e-11b5-11e6-97b4-dbd445883f21.jpg)

Garments of the Light (Quest 5624) + Guard Roberts (NPC 12423) works for me on current core & DB.

Garments of Spirituality (Quest 5648) and Grunt Kor'ja (NPC 12430) do not seem to work, though, but I think that is because Grunt Kor'ja already has got `unit_flags`=`UNIT_FLAG_PVP` (4096), but not `UNIT_FLAG_PVP_ATTACKABLE` (8). I have tested using the same `unit_flags` as Guard Roberts (0) for Grunt Kor'ja, but that did not make any difference. Only when I set `unit_flags` = 4104 did it work:
```sql
SELECT `entry`,`name`,`unit_flags`,`ScriptName`,`VerifiedBuild` FROM `creature_template`
 WHERE `entry` IN (12423,12427,12428,12429,12430);
```
```
 entry  name              unit_flags  ScriptName              VerifiedBuild
------  ----------------  ----------  ----------------------  -------------
 12423  Guard Roberts              0  npc_garments_of_quests          12340
 12427  Mountaineer Dolf        4104  npc_garments_of_quests          12340
 12428  Deathguard Kel         36872  npc_garments_of_quests          12340
 12429  Sentinel Shaya          4104  npc_garments_of_quests          12340
 12430  Grunt Kor'ja            4104  npc_garments_of_quests          12340
```
![wowscrnshot_050416_052810](https://cloud.githubusercontent.com/assets/4903600/15004622/8693e232-11b9-11e6-8259-520550b4b4af.jpg)

So in my case, the necessary change was this one:
```sql
UPDATE `creature_template` SET `unit_flags`=`unit_flags`| 8 WHERE `entry` = 12430;
```
I'm feeling somewhat uncertain about this, so it would be nice if someone else could test & verify which NPC needs to be changed and which one does not. Also, if you look up the old issues regarding these priest class healing quests, you can find these: "Unable to proceed with Priest Class quests that require healing of an NPC" #4598 and "Human priest chain quests: can't heal Guard Roberts [$15]" #13676 `->` commit https://github.com/TrinityCore/TrinityCore/commit/5ae6b9dc504d2ce6170b1b504ee8f60dacb0abd4 containing the following fix:
```sql
UPDATE `creature` SET `unit_flags`=4104 WHERE `id`=12423;
```
So check the NPCs in both tables and compare the `unit_flags` to verify what you got:
```sql
SELECT `entry`,`modelid1`,`name`,`unit_flags`,`ScriptName`,`VerifiedBuild`
 FROM `creature_template` WHERE `ScriptName` = 'npc_garments_of_quests';
```
```
 entry  modelid1  name              unit_flags  ScriptName              VerifiedBuild
------  --------  ----------------  ----------  ----------------------  -------------
 12423      3258  Guard Roberts              0  npc_garments_of_quests          12340
 12427     12474  Mountaineer Dolf        4104  npc_garments_of_quests          12340
 12428     12475  Deathguard Kel         36872  npc_garments_of_quests          12340
 12429     12476  Sentinel Shaya          4104  npc_garments_of_quests          12340
 12430     12477  Grunt Kor'ja            4096  npc_garments_of_quests          12340
```
```sql
SELECT `guid`,`id`,`modelid`,`spawntimesecs`,`curhealth`,`unit_flags`
  FROM `creature` WHERE `id` IN (12423,12427,12428,12429,12430);
```
```
  guid      id  modelid  spawntimesecs  curhealth  unit_flags
------  ------  -------  -------------  ---------  ----------
 81085   12423        0            180        137        4104
   224   12427        0            180        330           0
 44557   12428    12475            300        310           0
 46717   12429    12476            300        310           0
  3431   12430    12477            300        137           0
```
At least this explains why `unit_flags` makes Quest 5624 work for me on current core & DB.
I am more curious if this means that the `creature` table needs to be updated instead of the template, since `creature_template` values comes from sniffs. We also need to have this issue confirmed or refuted by other users, since I could only confirm this for Grunt Kor'ja, but not for Guard Roberts.

**Comment by MrSmite** [comment]
Guard Roberts is working in **TDB_full_world_335.60_2015_11_07.sql**, not sure about the other NPCs though.

**Comment by tkrokli** [comment]
Yes, that is because the right `unit_flags` are set in `creature` instead of `creature_template`.

**Comment by velinath** [comment]
apologies for bumping an ancient issue - I don't know the protocol on reopening versus opening new - but it seems like the NPC for the Undead priest quest - Deathguard Kel - still isn't working.

**Comment by Kittnz** [comment]
Yes, just make an new issue ticket.
