### ISSUE TITLE
Flight Master Ghostland

### ISSUE THREAD

**Issue by SQLfix** [TrinityCore/TrinityCore#17082]
if u use flight master on Eversong woods OR Ghostlands and go to other maps out of Patch 2.x maps to Azeroth or Bottom Maps flight go back and never u arrive to your select map
[ you cannot go on portals with flight master

1. Go on Eversong woods OR Ghostlands Find a Flight Master
2. Use it and Select Other map Like Eastern Plaguelands
3. When Flight runing and u near Portal Ghostland [ Portal to Go other Map in bottom Ghostland]
4. Flight (fly) Go back and u fly without mount
5. U fly forever Go near flightmaster go near portal 
6.relog and other way dont fix problem

3.3.5

https://github.com/TrinityCore/TrinityCore/commit/02d7df6aa4352d7112073898826ef195bedb6cff

**TDB version**:  

Centos 6

check in : mmap off /on  - vmaps off/on and confirm

**Comment by Aokromes** [comment]
Cannot reproduce.

**Comment by SQLfix** [comment]
screen shots
http://uploads.im/?g=sNFit.jpg

**Comment by Aokromes** [comment]
You can make screenshots, i still cannot reproduce it.

**Comment by Nawuko** [comment]
Same result as @Aokromes, I cannot reproduce the problem on 3.3.5 (5668bc32340bd15ac2195781b8da3ad62d9c56ee) 
Tested with .gm off, From Tranquillien Ghostlands To Lightss Chappel.

**Comment by tkrokli** [comment]
TrinityCore rev. 59ac77522347 2016-05-05 13:20:52 +0200 (3.3.5 branch) (Win64, Release)
TDB 335.61 (world DB reloaded for this test) + updates up to and including `2016_05_05_00_world.sql`

Unable to reproduce / replicate this issue, just like Nawuko & Aokromes said. Tested the following:
- vmaps & mmaps enabled
- mmaps disabled
- mmaps, vmaps.enableHeight and vmap.enableLOS disabled

Flightpaths tested:
- Silvermoon City / Eversong Woods (Skymistress Gloaming) `->` Light's Hope Chapel, EPL
- Tranquillien / Ghostlands (Skymaster Sunwing) `->` Light's Hope Chapel, EPL
- Hatchet Hills / Zul'Aman (Kiz Coilspanner) `->` Light's Hope Chapel, EPL
- all of the 3 above `->` Light's Hope Chapel, EPL as well as Acherus / Ebon Hold, DK char. (6 flights)

My dbc, maps vmaps were extracted 2016-04-16, mmaps extracted 2016-03-19.

Judging by your images on uploads.im I presume you were using the FP in Hatchet Hills, Zul'Aman, since that FP is the only one going from Ghostlands or Eversong that uses a bat as a horde mount, as well as that is the only FP which goes through the portal between the Thalassian Pass (Ghostlands) and Eastern Plaguelands. My other flights from Skymistress Gloaming or Skymaster Sunwing, flying to either Light's Hope Chapel (NPC: Georgia) or Acherus / Ebon Hold (NPC: Grimwing) used the Dragonhawk mount model for my flights all the way until the flights were completed.

I guess you could have a game client issue, but I recommend that you also check the following:
- drop & rebuild your world DB to be sure it is a default TDB + updates
- test with a verified and unmodified 3.3.5a (12340) game client
- extract dbc, maps, vmaps from an unmodified 3.3.5a game client

**Comment by Nawuko** [comment]
:+1: tkrokli that is what i call effort :)

**Comment by tkrokli** [comment]
Thanks. My only concern before starting this test was about my own game client and the fact that the loading screens say "World of Azerothshard" instead of "World of Warcraft". Maybe it is only cosmetic and a result from using some kind of MPQ patch file, not sure. I haven't noticed anything else. I was also a bit uncertain if it is correct that the Dragonhawk mount changes zone inside the Thalassian Pass, about 50 to 100 meters before the portal on the Ghostlands side, as well as looks like it flies above the portal, while the Bat mount goes through the portal and "teleports" (does the zone transition) in the zone portal.

**Comment by Shauren** [comment]
it works.
