### ISSUE TITLE
Compile Warnings under Windows

### ISSUE THREAD

**Issue by genion18** [TrinityCore/TrinityCore#17140]
**Description**: 3.3.5 compile Warnings

**Current behaviour**: Tell us what happens
12>  Weather.cpp
13>isle_of_conquest.cpp.obj : warning LNK4006: "void __cdecl AddSC_isle_of_conquest(void)" (?AddSC_isle_of_conquest@@YAXXZ) ist bereits in "isle_of_conquest.cpp.obj" definiert; zweite Definition wird ignoriert.
13>isle_of_conquest.cpp.obj : warning LNK4221: Die Objektdatei definiert keine zuvor undefinierten ÷ffentlichen Symbole. Sie wird daher von keinem Verkn³pfungsvorgang verwendet, der diese Bibliothek benutzt.
12>  WeatherMgr.cpp

**Expected behaviour**: Tell us what should happen instead No errors

**Steps to reproduce the problem**:

1. boost 1.59
2. boost 1.61
3. 

**Branch(es)**: 335  

**TC hash/commit**:  d812505fc29daa51d549439eaa2c72221dbefe07

**TDB version**:  latest

**Operating system**:  Windows 6.1.7601

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by tkrokli** [comment]
I can not remember seeing any warnings in VS2013 for at least more than a year, but let's check.
***
TrinityCore rev. d812505fc29d 2016-05-16 18:45:44 +0200 (3.3.5 branch) (Win64, Release)
Using SSL version: OpenSSL 1.0.2g  1 Mar 2016 (library: OpenSSL 1.0.2g  1 Mar 2016)
Using Boost version: 1.59.0
Using World DB: TDB 335.61
CMake 3.5.2 output:
```
Detected 64-bit platform
MSVC: 64-bit platform, enforced -D_WIN64 parameter
MSVC: Enabled increased number of sections in object files
MSVC: Overloaded standard names
MSVC: Disabled NON-SECURE warnings
MSVC: Disabled POSIX warnings
MSVC: Disabled generic compiletime warnings
Found MySQL library: C:/Program Files/MySQL/MySQL Server 5.6/lib/libmysql.lib
Found MySQL headers: C:/Program Files/MySQL/MySQL Server 5.6/include
Found MySQL executable: C:/Program Files/MySQL/MySQL Server 5.6/bin/mysql.exe
Found git binary : C:/Program Files/Git/cmd/git.exe

* TrinityCore revision   : d812505fc29d 2016-05-16 18:45:44 +0200 (3.3.5 branch)

* Install core to        : C:/Program Files/TrinityCore

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (static)
* Build map/vmap tools   : Yes
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Show source tree       : Yes (hierarchical)
* Use GIT revision hash  : Yes (default)

Boost version: 1.59.0
Found the following Boost libraries:
  system
  filesystem
  thread
  program_options
  iostreams
  regex
Found OpenSSL library: optimized;C:/OpenSSL-Win64/lib/VC/ssleay32MD.lib;C:/OpenSSL-Win64/lib/VC/libeay32MD.lib;debug;C:/OpenSSL-Win64/lib/VC/ssleay32MDd.lib;C:/OpenSSL-Win64/lib/VC/libeay32MDd.lib
Found OpenSSL headers: C:/OpenSSL-Win64/include

* Script configuration (static):
    |
    +- worldserver
    |   +- Commands
    |   +- Custom
    |   +- EasternKingdoms
    |   +- Events
    |   +- Kalimdor
    |   +- Northrend
    |   +- OutdoorPvP
    |   +- Outland
    |   +- Pet
    |   +- Spells
    |   +- World
    |

Configuring done
Generating done
```
Microsoft Visual Studio Community 2013, Version 12.0.40629.00 Update 5
Microsoft .NET Framework, Version 4.6.01038
***
`========== Build: 23 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========`
Error List: | 0 Errors | 0 Warnings | 0 Messages |

Output-Build.txt on pastebin.com : http://pastebin.com/r9e3jadN
***
I can not reproduce your issue, compiled this rev. hash 2 times tonight with no warnings.
The 3.3.5 build passes in Travis CI (Travis does not tolerate warnings much), so I doubt this should happen with the TC 3.3.5 branch at all. If you check https://travis-ci.org/TrinityCore/TrinityCore/builds/130613896#L1400, you will find that there was a completely different issue in d812505fc29d which should be fixed by joschiwald's very recent commit https://github.com/TrinityCore/TrinityCore/commit/ab2466a ("**Makes travis happy**").
See https://travis-ci.org/TrinityCore/TrinityCore/builds

**Comment by jackpoz** [comment]
Build Warnings are warnings, not errors so not an issue so they shouldn't even be reported on GitHub issue tracker. Posting the warnings in a language other than english makes it even less useful.

Please clean your cmake cache by following the instructions on the forum and if the warning persists just ignore it.
