### ISSUE TITLE
DB/Quest: ExclusiveGroup for breadcrumb quests in Mudsprocket, Dustwallow Marsh

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17217]
**Description**: only one out of the three (Alliance, Horde and neutral) breadcrumb quests leading to Mudsprocket (Dustwallow Marsh) should be completable. The others become unavailable after turning in one of them ([source](http://www.wowhead.com/quest=11211/help-for-mudsprocket#comments:id=1694664)).

**Branch(es)**: 3.3.5

**TC hash/commit**:  71081c2

**TDB version**:  335.61

**Suggested fix**: 
```sql
DELETE FROM `quest_template_addon` WHERE `ID` IN (11211, 11214, 11215);
INSERT INTO `quest_template_addon` (`ID`, `ExclusiveGroup`) VALUES
(11211, 11211),
(11214, 11211),
(11215, 11211);
```
(not using an UPDATE query in case [this](https://github.com/TrinityCore/TrinityCore/issues/17214#issuecomment-222383183) is accepted)

**Comment by tkrokli** [comment]
Well, all of those 3 rows contain only zeros (`0`) except for the `ID` value, so it is quite safe to delete them. But it is generally preferred that existing lines are updated instead of using `DELETE FROM` / `INSERT INTO`. In this case, though, I would suggest using update instead, because the query gets a lot simpler:
```sql
UPDATE `quest_template_addon` SET `ExclusiveGroup` = 11211 WHERE `ID` IN (11211,11214,11215);
```

**Comment by Aokromes** [comment]
Or i can simply push 1st this with update and the delete after :)
