### ISSUE TITLE
[3.3.5][6.x] DB/Loot: item "Primed Key Mold" should not be droppable by any NPC

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17224]
**Description**: title says it all. Coilfang Emissary drops an item that's given when you accept another, unrelated quest.

**Branch(es)**: 3.3.5 / 6.x

**TC hash/commit**:  291a264

**TDB version**:  335.61

**Suggested fix**:
```sql
DELETE FROM `creature_loot_template` WHERE `Item`=31245;
```

**Comment by SnapperRy** [comment]
I'm going to get the title right eventually, just you wait!

**Comment by Kittnz** [comment]
Rushor is just nit picking :P

**Comment by SnapperRy** [comment]
It's a matter of principle now :D

**Comment by tkrokli** [comment]
I thought that issue labels could be used instead of [3.3.5] / [6.x], but maybe it is easier to read the issues when they have got [3.3.5] / [6.x] in the title. (Maybe the labels look messy if there are too many of them, I don't know. It would be easier to use the github sort feature if the issues had [3.3.5] / [6.x] labels, though.
