### ISSUE TITLE
[3.3.5][6.x] DB/Creature: remove wrong spawn in Eversong Woods

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17230]
**Description**: creature [Mistbat](http://www.wowhead.com/npc=16353/mistbat) has no place in Eversong Woods. It's the last of three pets required to be tamed by Hunters for their quest, so it was probably parsed together with other creatures around there. But it shouldn't be found outside of the Ghostlands. [Source](http://www.wowhead.com/npc=16353/mistbat#comments:id=83633).

**Branch(es)**: 3.3.5 / 6.x

**TC hash/commit**:  291a264

**TDB version**:  335.61

**Suggested fix**:
```sql
DELETE FROM `creature` WHERE `guid`=57016;
```

**Comment by Kittnz** [comment]
Overall, this zone seems not to be very blizzlike spawning wise. Some have the right spawn positions but not the right entryid. It's an overall issue in TC. And some are manually spawned.

**Comment by tkrokli** [comment]
Because I play the hunter class a lot and often choose the horde/blood elf combo, I often notice this [mistbat](http://www.wowhead.com/npc=16353/mistbat) spawned right outside [Farstrider Retreat](http://wow.gamepedia.com/Farstrider_Retreat) where I went on my bloodelf hunter character to deliver the quest [Seek the Farstriders](http://wow.gamepedia.com/Quest:Seek_the_Farstriders) to [Lieutenant Dawnrunner](http://wow.gamepedia.com/Lieutenant_Dawnrunner). The funny part is that it looks like someone wanted the 3 beasts ([Crazed Dragonhawk](http://wow.gamepedia.com/Crazed_Dragonhawk), [Elder Springpaw](http://wow.gamepedia.com/Elder_Springpaw), [Mistbat](http://wow.gamepedia.com/Mistbat)) tamed in the 3 hunter quests ([Taming the Beast (Blood Elf 1)](http://wow.gamepedia.com/Quest:Taming_the_Beast_%28Blood_Elf_1%29), [Taming the Beast (Blood Elf 2)](http://wow.gamepedia.com/Quest:Taming_the_Beast_(Blood_Elf_2)), [Taming the Beast (Blood Elf 3)](http://wow.gamepedia.com/Quest:Taming_the_Beast_(Blood_Elf_3))) to be near Farstrider Retreat just to save time finishing those quests. It is not blizzlike, of course, so someone probably put those 2 extra creatures right outside the building with simplification in mind, without caring about blizzlike spawns. Mistbats should only be spawned in Ghostlands, of course.

**Comment by SnapperRy** [comment]
The hunter quest is the reason I kept remembering about this one mob :P

Yeah, the zone itself is (was? It's way better thanks to Kittnz) quite messy. This one mob really seems out of place (as in, spawned by hand or parsed from some hunter as a pet). It's very close to Farstrider Retreat (~40 yards from the closest guard) and often gets killed by the patrolling guard that walks near it.

So I think it can safely be deleted. Unless it was originally meant to be a critter, which would make sense considering the location :P

**Comment by tkrokli** [comment]
Thanks for the comment, I even doubt the existence of a bat critter at that position for 3.3.5. (Not that I remember many critters (level 1-5) from Eversong Woods in retail back in 3.3.5a or earlier, of course.)

**Comment by SnapperRy** [comment]
Maybe not a bat, but a rabbit or squirrel (do they even exist in Eversong Woods?) if the position is right but the entry was messed up somehow.

**Comment by Aokromes** [comment]
Nothing spawned there on retail.

**Comment by tkrokli** [comment]
Yes, I think that spot is supposed to be empty, not much to see near the guard's path.

**Comment by SnapperRy** [comment]
Thanks for confirming it ;)

**Comment by Kittnz** [comment]
Might want to delete the other spawns too

**Comment by SnapperRy** [comment]
Do we know which spawns are wrong? This one is a completely out of place entry, others aren't as easy to notice.

**Comment by tkrokli** [comment]
I think he means the Crazed Dragonhawk just behind the Mistbat, not sure if there is anything else.
The Elder Springpaws are on the hillside above Farstrider Retreat, nothing wrong with them.

**Comment by lyn1337** [comment]
The Crazed Dragonhawk (GUID: 57016) seems correctly positioned to me. It's there on blizz servers.

**Comment by lyn1337** [comment]
Suggestion:
```sql
-- remove mis-spawned Mistbat (entry: 16353)
DELETE FROM `creature` WHERE `guid`=57016;

-- remove one too many spawned Elder Springpaw (entry: 15651)
DELETE FROM `creature` WHERE `guid`=55946;

-- set random movement and spawn distance to the common value for that creature
UPDATE `creature` SET `spawndist`=5, `MovementType`=1 WHERE `guid`=55942;
UPDATE `creature` SET `spawndist`=5, `MovementType`=1 WHERE `guid`=55945;

```

These are the ones I have checked. I think that's it. Most of the spawns here don't seem to have been verified so there clearly is some work to be done, but the Mistbat - misplacement is nasty.

**Comment by Kittnz** [comment]
I am actually respawning deatholme in ghostlands atm, such a mess there and many waypoints missing..
