### ISSUE TITLE
wow client 6.2.4.21742 to login recent release a1f59c9 problem

### ISSUE THREAD

**Issue by darkz1984** [TrinityCore/TrinityCore#17402]
**Description**:
I download a1f59c9  release and build the server,then config is OK
Then I use balltenet client to download newest client version is 6.2.421742
extract maps is ok
path connector is ok.
import database is ok
start server is ok

When I try to login to server,Clent tell me ,login to server,please wait

What is the problem? The version is not support or something wrong?

**Branch(es)**:
6.x 
download the release from https://github.com/TrinityCore/TrinityCore/releases
**TC hash/commit**:  
The newly release,a1f59c9 

**TDB version**:  
TDB_full_6.04_2016_04_11.7z

**Operating system**:  
Windows 10 64 bit profession version

**Comment by Aokromes** [comment]
The hash you linked is  6.2.4/21355 not 6.2.4 21742

**Comment by darkz1984** [comment]
How to support 6.2.4 21742?

**Comment by darkz1984** [comment]
I can't find the version support 6.2.4 21742

**Comment by DDuarte** [comment]
Current Git HEAD supports that version.Clone the repo as explained by https://trinitycore.atlassian.net/wiki/display/tc/Installation+Guide

**Comment by darkz1984** [comment]
I pull newest code from github，and build it，it still told me is logining to the game servers。。。so sad

**Comment by tkrokli** [comment]
It happens to me some times on current source that the client hangs on "Logging in to game server", but I usually fix that by closing the servers + game client, deleting the game client Cache folder, checking that my source folder is up to date and run the servers again before logging in. So I don't get it as a constant issue, just a random event that can be caused by my computer's OS or files. If it gets really difficult to fix, I also drop my world DB to make Worldserver reload the DB. Usually works for me.

**Comment by Aokromes** [comment]
Well, connection issues don't belongs to bug tracker when it's known working for most of persons..
