### ISSUE TITLE
[6.x] Encounter Progress Panel

### ISSUE THREAD

**Issue by OrzelBialy** [TrinityCore/TrinityCore#17506]
**Description**:
Hello TrinityCore devs. I have noticed that the boss encounter progress panel is not working. I know this is only a cosmetic thing; and TC is appearing to be focused on playability. But many of us are here to study and to learn about how, maybe, a real MMO will be structured back-end. It is nice that a spell works, but it doesn't help with the model of TrinityCore (an educational project). I would really love to learn more from you about this system.

**Current behaviour**: Tell us what happens
When you enter a dungeon from the instance portal, you do not see the encounter progress panel on the right of the screen.

**Expected behaviour**: Tell us what should happen instead
On retail, when entering the instance, we will see something like this
![Image of Progress Panel](http://image.prntscr.com/image/e2259d78b8934a10ad6f6b796fefc4bd.png)

**Steps to reproduce the problem**:
1. Make any character
2. Teleport to the entrance of any dungeon
3. Enter the dungeon

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
6.x

**TC hash/commit**:  
77f980035a43a9156c22130042d1fb6597139ee0

**TDB version**:  
6.04

**Operating system**:  
Windows 10

**Comment by Aokromes** [comment]
I am sure this ticket is duplicate, but can't find original one.

**Comment by OrzelBialy** [comment]
I did search for an open ticket too, but did not find one so I created this.

**Comment by ViktorIvanenko** [comment]
NO! PLEASE CLOSE! why tc should doing that while all pservers already having this? for make difficulty with merge? better for work on quests and spells which not pservers having. for improving state of private conditions source.

**Comment by humaniti** [comment]
@ViktorIvanenko well this is not only a cosmetic. This makes players to get more bonuses like Experience and Gold.. Thats a huge thing to get fixed : )

**Comment by Ovahlord** [comment]
@ViktorIvanenko TC has no business with private servers so if TC implements scenarios on their own they don't have to care about their servers. (Scenarios is the point that is being asked for here.)

**Comment by Krudor** [comment]
**Wall of text warning**

I'm working on implementing Scenarios for TrinityCore at the moment, but have been asked to put it on hold for a while, while I spend some time to update and push some uncommited PvE encounter scripts for Dragon Soul / Terrace of Endless Spring and Heart of Fear.

Main issue with the scenario system I'm currently working on is the missing information about Criteria Tree operator flags which the scenario system, and achievement system build upon.

Basically the operator flags help determine whether or not a criteria has been fulfilled (which Scenarios use to track progress).
We currently only know 2 operator flags for processing criteria progresses, and there appears to be at least 2 more that are currently unknown.

Basically what doesn't work is if the scenario asks you to kill 30 creatures in the instance, then the criterias behind it might look something like this:

Description: Kill 30 enemies (CriteriaTreeId: 123)
Amount to complete criteria is determined from the CriteriaTreeId, and that amount is 30 (30 enemies)

CriteriaIds to be fullfilled to complete CriteriaTreeId: 123 are the following: 50,  51, 52.
Criteria 50 corresponds to killing creature with entry 1001, 15 times.
Criteria 51 corresponds to killing creature with entry 1002, 15 times.
Criteria 52 corresponds to killing creature with entry 1005, 15 times.

The currently criteria system will then only fulfill the criteriatree, if all criterias are complete.
And they  currently  require you to kill exactly 15 of creature entry: 1001, 15 of creature entry: 1002, and 15 of creature entry: 1005.
Which is a total of 45, and a strict requirement to kill 15 of a certain creature, when the CriteriaTree asked for 30, from any of those criterias listed.

This is the behavior that I've observed so far, but I could use some help from Shauren to verify this and see if he has any idea of what the currently unknown operator flags might do.

There's also another problem with the criteria UI, and I believe it's related to a loading screen issue currently present in TrinityCore.
When you get a loading screen, you bar will fill up to indicate loading progress, just like retail.
However when it reaches 100% on trinitycore, the loading bar disappears after a small delay, without removing the loading screen itself. The loading screen eventually goes away but it has already caused an impact in displaying the scenario UI, whos opcode has been sent properly.

Resending the scenario UI opcode whilst playing will correctly show the UI.

These 2 problems are currently impeding the progress of pushing this feature, so if you have any knowledge about helping/fixing this, please contact me.

**The 2 issues recapped:**

- Unknown CriteriaTree.db2 operator flags
- TrinityCore Loading screen issue (I might be very wrong about this being the root cause for the scenario UI not showing, if sent during the loading screen)

**Comment by OrzelBialy** [comment]
So I was wrong, this is more than a cosmetic issue. I am now even more intrigued about this Scenario system. Maybe you can push a PR to TC and the community can improve / complete the system?

**Comment by Shauren** [comment]
@Krudor I fixed loading screens 3 weeks ago - 2fe6fc63d79655a96ee2135a6b380ce353729088

**Comment by Krudor** [comment]
@Shauren Great! Sorry for refering to outdated rev.

**Comment by ViktorIvanenko** [comment]
@Krudor better to not make pr. why to do pr of scinario to tc? all pserver have already this. only to making merge conflict? for making battle with git?! open sources dose not need it! do the encounter script, the "Dragon Soul / Terrace of Endless Spring and Heart of Fear" is lot better for you.

pls. many respect to tc devs, but pls close issue.

**Comment by Shauren** [comment]
@ViktorIvanenko please kindly fuck off and mind your own server with this attitude. While at it please also don't use TrinityCore as you clearly already have everything fixed and are just leeching things you are unable to fix yourself from here.

**Comment by Ulduar** [comment]
@ViktorIvanenko  объясни мне пожалуйста, на кой чёрт твои приват сервера вообще сдались. Что  бабло на этом решил заработать?

**Comment by lorac2k14** [comment]
@ViktorIvanenko you know a simple thank you goes a long way?
It shows you are nothing more than a Leech!
Who the ---- do you think you are dictating what and what the opensource needs?

As for your request to get something done... How about placing a bounty on it so the person who caters to you actually gains something for providing you what you want since you cant provide fixes.

If you are running a pserver which mind you is NOT supported by TC or any other core development community this means you are gaining from it in some way or you would not be doing it how about throwing the dev team a Monitory tip for their efforts.
Clearly you are too incompetent.
Or hey wait even better.. Learn to code and move away from TrinityCore.
WAIT A F--ken moment here So you have that working and yet you didn't provide a solution or p/r?
You have no one to blame but yourself for merge conflicts because you didn't offer a p/r 
Here's your tissue mate.

I Second Shauren in his statement.
@Shauren Nice response! I could not say it any better :) 
@ Trinity Development Team and Community You guys rock and Don't let people like this discourage you.
People like ViktorIvanenko Hold very little value and only acts for their own gain not anyone else.

**Comment by Aokromes** [comment]
8444ab736568667cb6425757ce5f832cb6068379
