### ISSUE TITLE
[3.3.5] DB/Gossip: add npc text for Baine Bloodhoof

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17575]
**Description**: not sniffed, found said text [here](https://youtu.be/6sMVoXENDYI?t=188). Not sure if ids are appropriate, change as needed.

**Branch(es)**: 3.3.5

**TC hash/commit**:  8835607

**TDB version**:  335.61

**Suggested fix**:
```sql
DELETE FROM `npc_text` WHERE `ID`=50000;
INSERT INTO `npc_text` (`ID`, `text0_0`, `VerifiedBuild`) VALUES
(50000, "The land has been good to our people, $c. We must be thankful for our good fortune.", -1);

DELETE FROM `gossip_menu` WHERE `entry`=50000;
INSERT INTO `gossip_menu` (`entry`, `text_id`, `VerifiedBuild`) VALUES (50000, 50000, -1);

UPDATE `creature_template` SET `gossip_menu_id`=50000 WHERE `entry`=2993;
```

**Comment by Aokromes** [comment]
Include the new VerifiedBuild column with a value of  -1 :)

**Comment by tkrokli** [comment]
Well, since Baine Bloodhoof (`entry` 2993) has neither got any `gossip_menu_id`, `AIName` nor `ScriptName`, I suppose we will have use the current value 50000 until a real value can be found in sniffs (if at all possible).

**Suggested fix:** (updated)
```sql
DELETE FROM `npc_text` WHERE `ID`=50000;
INSERT INTO `npc_text` (`ID`, `text0_0`, `Probability0`, `VerifiedBuild`) VALUES
(50000,"The land has been good to our people, $c. We must be thankful for our good fortune.",1,-1);

DELETE FROM `gossip_menu` WHERE `entry`=50000;
INSERT INTO `gossip_menu` (`entry`,`text_id`,`VerifiedBuild`) VALUES
(50000, 50000, -1);

UPDATE `creature_template` SET `gossip_menu_id`=50000 WHERE `entry`=2993;
```
I would have liked to see a full line of column names for `npc_text`, although that requires filling in the empty or zero values, if required. I could not find the text `The land has been good to our people, $c. We must be thankful for our good fortune.` in `broadcast_text`, but I guess that table does not contain all `npc_text` occurrences or quest related texts. So in this case, the `BroadcastTextID0` will have to remain 0.

Feel free to check if `Probability0` should use 1 or 0 in the `npc_text` SQL above.

**Comment by SnapperRy** [comment]
Already checked existing data, there is no entry for this text.

Default values are appropriate for the fields I don't change, so I think it's more appropriate to leave them out :) otherwise the query would be mostly filled with redundant data.

Thought the default value for VerifiedBuild was the right one, hehe, sorry. Changed that.
