### ISSUE TITLE
[3.3.5] Quest: Honor is for the Weak

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#17625]
3.3.5 931a7623b24831adf679e0581735375077c8d252

[Quest: Honor is for the Weak](http://www.wowhead.com/quest=13170/honor-is-for-the-weak)
You can assassinate the same target multiple times, which makes the target award credit twice (instead of once).

**Comment by malcrom** [comment]
That is not a valid issue. Give more detail.

**Comment by tkrokli** [comment]
Quest: http://www.wowhead.com/quest=13170/honor-is-for-the-weak
Target(s): http://www.wowhead.com/npc=30951/restless-lookout (20 required)

According to the related quests in the same area, the player is supposed to use an object named "Eye of Domination" (I could not find an wowhead or openwow entry) to control the NPC http://www.wowhead.com/npc=31110/eidolon-watcher and use its controlled abilities http://www.wowhead.com/npc=31110/eidolon-watcher#controlled-abilities to kill the target NPCs.

I would have thought the respawn time would make it impractical to wait for the NPC to respawn, but maybe something has changed in the DB regarding that respawn time for NPC 30951?
I agree, more details would be better in order to fully understand this issue.

**Comment by Treeston** [comment]
The [Eidolon Watcher](http://www.wowhead.com/npc=31110/eidolon-watcher) has the ability [Assassinate Restless Lookout](http://www.wowhead.com/spell=58563/assassinate-restless-lookout), which is used on the [Restless Lookout](http://www.wowhead.com/npc=30951/restless-lookout) to apply a debuff which stuns them and kills them after 4 seconds.

If you apply this debuff twice before the target dies, you are credited twice for killing them. This is a bug.

**Comment by Killyana** [comment]
Related to https://github.com/TrinityCore/TrinityCore/issues/17363
Once fixed this could be tested:
``` sql
UPDATE `smart_scripts` SET `event_flags`=1 WHERE `entryorguid`=30951 AND `source_type`=0 AND `id`=0;
