### ISSUE TITLE
Core/unit: Guards no longer attaking players

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#17635]
**Description**:
Guards like http://www.wowhead.com/npc=3502/ratchet-bruiser are supposed to attacks any player that hit any other player, but with the recent changes, they just turn aggressive, but they doesn't attack and they cannot be attacked (wrong target as message)

**Steps to reproduce the problem**:
1.  connect 2 characters horde and alliance
2.  .go c id 19488
3.  hit the player in front of you and notice the react of the guard

**Branch(es)**: 3.3.5 / 6.x 

**TC hash/commit**:  rev. cdf8f3c2e1f0

**Comment by Core002** [comment]
confirmed

**Comment by tkrokli** [comment]
@Core002 : please add the TC core rev. hash you have used to confirm this issue. This is for future reference and to verify on which commit you have found this issue to still be present in, because we can't know which core rev. hash you used, only based on the time you commented on. Many users don't necessarily use the same commit as the available one at the time of the comment they have posted, so please add your rev.
