### ISSUE TITLE
Spam message on console from creature "Bone Warrior" 

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#17655]
**Description**:
Spam message on console from creature

**Current behaviour**: Tell us what happens
CreatureTextMgr: Could not find Text for Creature Bone Warrior (Entry 26126, GUID 15797)in 'creature_text' table. Ignoring.

**Branch(es)**: 3.3.5 / 6.x

**TC hash/commit**:  
TC>TrinityCore rev. 09a1cfdf771a 2016-07-23 03:37:09 +0200 (335 branch)

**TDB version**:  
TDB_full_world_335.61_2016_04_11 + all updates
**Operating system**:  
Win7 64Bit

**Comment by Aokromes** [comment]
@Tauriella I think this is duplicate issue

**Comment by Tauriella** [comment]
Ahh o sorry 
if it so then Close please
thx

**Comment by tkrokli** [comment]
No current open issues for the error text `CreatureTextMgr: Could not find Text for Creature`.

**Comment by Tauriella** [comment]
The message comes only if the Bone Warrior attacks Defendo-tank-66D

http://www.wowhead.com/npc=25758/defendo-tank-66d

**Comment by tkrokli** [comment]
That is weird, because both those creatures have got SmartAI in the DB, but only the Defendo-tank-66D has got any `creature_text`. The only SAI row for creature 26126 is using the ability `Cast 'Sunder Armor'`.

**Comment by Tauriella** [comment]
Now i fix my locales :) 

go to 4071 4790 -2 571
and with for the fight :)

**Comment by Tauriella** [comment]
@tkrokli 

This Fix solved the console spam Problem
```sql
UPDATE `smart_scripts` SET `action_param3`=1 WHERE `entryorguid`=25758 AND `event_type`=4 AND `id`=1;
```
But i think the creature gives general a wrong text

**Comment by dr-j** [comment]
Actually the reason for console spam is the first line of sai on the defendo tanks (On agro - say - target invoker') which makes the npc say a line of text to using target invoker to fill missing data.

If invoker is not a player it will throw up a console error

the below should fix this as is the same how I shut up all those vendors in Dalaran which were throwing up errors due to invoker been a npc rather than player

~~~sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=22 AND `SourceEntry`=25758;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES 
(22, 1, 25758, 0, 0, 31, 0, 4, 0, 0, 0, 0, 0, '', 'Defendo-tank 66D - Only run SAI if invoker is player');

**Comment by Tauriella** [comment]
Work's great :+1:
