### ISSUE TITLE
Many *_locale tables in world database is empty

### ISSUE THREAD

**Issue by cjl3230** [TrinityCore/TrinityCore#17680]
**Description**:Many locales_\* tables in world database *loc4 *loc5 is empty, so when I use zhCN or zhTW client.E.g quest text is English.

**Current behaviour**:  when I use zhCN or zhTW client many text is English.
E.g quest text.

**Expected behaviour**: 
1.In the game, quest text is client version language.

**Steps to reproduce the problem**:
1. build rev 2439e2d5ee212d3d0761586bc1b95bad6e30bc92
2. use TDB_full_335.61_2016_04_11 + All updates
3. start server and start client(zhCN or zhTW)
4.many tables name locales_\* tables in world database *loc4 and *loc5 is empty,E.g. locales_quest table.

**Branch(es)**: 3.3.5

**TC hash/commit**:  2439e2d5ee212d3d0761586bc1b95bad6e30bc92

**TDB version**:  TDB_full_335.61_2016_04_11 + All updates

**Operating system**:  Win10 64bits

**Comment by Shauren** [comment]
As far as I know, we only intend to provide english data so this is intended.
Perhaps someone else can give you a better answer

**Comment by cjl3230** [comment]
@Shauren I have some zhCN sql, can I take it to TDB.

**Comment by tkrokli** [comment]
Because TrinityCore is a community-driven project with a dynamic group of core team developers (collaborators or members) and with most of the members coming from Western Europe or other countries with focus on using English/German/French/Spanish, not enough people with both good Chinese and English skills have invested much time in trying to contribute with Chinese translation suggestions. https://community.trinitycore.org/forum/29-languages/ does not even have a dedicated Chinese or Korean language group, so there has not been enough incentive to provide support for Chinese databases content. As said already, English will stay as the main focus for TrinityCore. Any content updates in Chinese needs some form of verification to make sure it contains correct and as blizzlike as possible information. But feel free to post solution suggestions.

**Comment by tkrokli** [comment]
I did not mean to disappoint you with what I wrote. I meant to explain why there is no existing support in the community for Chinese translations to be added to the TDB in a meaningful amount so the client GUI can contain enough Chinese content to be useful. I hope your reason for closing this is based on not enough material to contribute, rather than thinking that I tried to discourage you from posting more.

**Comment by cjl3230** [comment]
@tkrokli  https://github.com/keyshuwen/wow_db_chinese   This is what I gathered, and the official Chinese version of World of Warcraft is very close.

**Comment by tkrokli** [comment]
Looks interesting, I just I wish I knew someone already, from earlier, who knows Chinese and who could verify if it is a working solution. Also, I can only offer general advice, while the TrinityCore member users (like Shauren and others) are the ones who decide how to deal with suggested material like that. Please be patient, sometimes it takes a while (a few days or weeks) before a progress decision is made.

**Comment by MrSmite** [comment]
Can you write a script to use google translate to validate?

Enter the Chinese text into GT and if the English output is the same (or close) to the TDB English then keep the entry otherwise make a note of it.

**Comment by tkrokli** [comment]
Well, I don't know coding well enough to create a setup just to perform a task like that. I might as well paste each file into translate.google.com and see what it looks like. Anyway, I am a bit busy working on PRs of my own as well, so I was not looking forward to do the work involved in verifying the content. I also meant that it would be useful to hear from others who have tested the suggested SQL files on their own Chinese game client. I don't have a Chinese game client myself (would be a bit bothersome to read error messages when you don't know how to read Chinese), that is why I suggested feedback from someone else who actually knows how to read Chinese.

**Comment by MrSmite** [comment]
@tkrokli Sorry, I didn't mean "you" literally. I meant "you" as a collective, excluding me of course ;)

**Comment by Aokromes** [comment]
table names and update of https://github.com/keyshuwen/wow_db_chinese of the needed tables to new structure is welcomed.

**Comment by offl** [comment]
https://github.com/keyshuwen/wow_db_chinese probably was updated to cata+, so be careful

**Comment by cjl3230** [comment]
https://github.com/dusksoft/TrinityCore_Chinese_Locale    @Shauren @MrSmite @Aokromes @offl

**Comment by Aokromes** [comment]
very bad, it overwrites english values everywhere instead use locales where possible.

**Comment by cjl3230** [comment]
@Aokromes We can modify the file(.sql) to update only the necessary fields

**Comment by Aokromes** [comment]
access_requirement, areatrigger_tavern, areatrigger_teleport, game_event, game_tele, needs locales support, trinity_string needs update to new locales system.

**Comment by cjl3230** [comment]
What do i need to do? @Aokromes

**Comment by illfated** [comment]
Depends on how TC wants to accept contributions to add zhCN and zhTW text, if those tables Aokromes mentioned need to be adapted to use locales before more locales text can be added in the DB.

Which TDB tables are already clear to accept the addition of zhCN and zhTW text?

**Comment by cjl3230** [comment]
@funjoker ,Can you handle the 3.3.5 branch?I don't know much about Trinitycore development

**Comment by cjl3230** [comment]
Can I use the translation content (E.g. task description) from DBC files？

**Comment by illfated** [comment]
Maybe, I don't know. @offl - do you happen to know more about the question above, the DBC files and if text content from there can be used to propose TC DB content translation to zhCN and zhTW text?

**Comment by offl** [comment]
The DBC files are not for locales
