### ISSUE TITLE
[335] Tracking abilities should not interrupt Eagle Eye

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#17727]
**Description**:

The Hunter's tracking abilities (eg: Track Beasts) should not interrupt Eagle Eye

**Current behaviour**:

While channeling Eagle Eye, casting any of the trackers causes Eagle Eye to cancel

**Expected behaviour**:

The Hunter should be able to cycle through the trackers without interrupting Eagle Eye

**Steps to reproduce the problem**:
1. Cast Eagle Eye
2. Cast Track Beasts
3. 

**Notes:**

I'm sure some people will disagree because it's channeled however the tracking abilities are instant cast with no GCD.

Unfortunately I couldn't find anything on Google / Youtube to back up my claim because this is a relatively minor ability that most people only used in BGs until that was changed. This is purely from personal experience with retail WotLK where I would scout during quests and make sure an area was safe by using Eagle Eye and then switching between trackers.

**Branch(es)**: 3.3.5

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/2db9269ec1c06b5fccc45dc0a5b4f714f9b48804

**TDB version**:  TDB_full_world_335.61_2016_04_11.sql + updates

**Operating system**:

**Comment by CraftedRO** [comment]
According to cata ptr 4.4.0.55639 this issue seems invalid:


https://github.com/user-attachments/assets/c6a3fd70-4faa-4046-9d1d-3d462a658b02

**Comment by MrSmite** [comment]
This is a bug report for 3.3.5, not Cata. I raided a lot on my Hunter in 3.3.5 and Eagle Eye was not interrupted.

**Comment by CraftedRO** [comment]
we still need some proofs also the [wiki Notes](https://wowpedia.fandom.com/wiki/Eagle_Eye):
Eagle Eye is canceled by pressing escape, jumping, or casting it again. It can be prevented from canceling on re-cast by using the macro /cast !Eagle Eye. This allows you to relocate your Eagle Eye directly from its existing location, rather than having to return to your own viewpoint first.
This ability is similar to a shaman's Spell nature farsight [[Far Sight]](https://wowpedia.fandom.com/wiki/Far_Sight).

Far Sight IS also intrerupted by Eagle Eye, even if it's maybe not the perfect comparison but most likely this is the way it worked back then too.

**Comment by CraftedRO** [comment]
is still a thing why on 3.3.5 is not intrerupted by Escape key too, as it shoud.

**Comment by MrSmite** [comment]
I saw that wiki but it's also not for 3.3.5. The patch list shows 4.0.1 as the closest.

Anyway, it's probably not worth the hassle. I can't find any old videos that would support my claim and it certainly isn't game breaking to have it cancel. Maybe me switching tracking spells on WotLK retail with it active was actually the bug  :)

**Comment by CraftedRO** [comment]
I also tested this on current 2.5.5.64796 tbc classic era ptr and Eagle Eye is still intrerupted by by Tracking abilities (will test it on wotlk classic ptr too when available):

https://github.com/user-attachments/assets/0eac0078-eb08-4018-9a64-4a19a6170235

**Comment by CraftedRO** [comment]
only when you uncheck tracking you won't be intrerrupted atm, also you can see that enabling tracking will actually trigger GCD.
