### ISSUE TITLE
[6.x] Barber Worldserver crash

### ISSUE THREAD

**Issue by mhubregtse** [TrinityCore/TrinityCore#17741]
When buying new cut at barbershop the server crashes.

Crashlog: 
https://drive.google.com/open?id=0B3HW2Z0MMhLVSEhNV1ZQLWpmTjA

Branch: 6.x 9bc28632b3fb
TDB 6.04
windows 10 64x

**Comment by mhubregtse** [comment]
Sorry that was a release crashlog..

This is the debug crashlog and newer version: 93bf99fe7026
https://drive.google.com/file/d/0B3HW2Z0MMhLVbk1RRDRESmxfa3M

**Comment by mhubregtse** [comment]
Any updates?

**Comment by tkrokli** [comment]
Except for the labels being added when you opened this issue, none of those who know how to read the logs and find possible causes have had time to do so here. Maybe because of other activities, maybe because of the frequent updates to the official game client lately, which leads to more updates needed in the TC source.

**Comment by Vincent-Michael** [comment]
9f7c26273b96ae54542cf90872fd6c638879f0eb
