### ISSUE TITLE
[3.3.5] Quest items related to multiple quests and repeatable quests being all destroyed on quest turn in

### ISSUE THREAD

**Issue by Nyeriah** [TrinityCore/TrinityCore#17758]
**Description**:
There are quest items that can relate to multiple quests or are used by repeatable quests and due to the latest changes they're all destroyed now whenever the first quest they relate to is turned in.

**Expected behaviour**: Tell us what should happen instead
They're not supposed to be destroyed... just the instance of them required to complete the quest being turned in.

**Steps to reproduce the problem**:

1.  Add quests 4723, 4728, 4730, 4733 ("Beached Sea Creature")
2.  Try to turn in any of the aforementioned quests
3.  Notice every Sea Creature Bones in your inventory are deleted leaving you incapable of turning in any of the remaining quests, unless you drop them and pick up again.

The same happens to the stranglethorn fishing extravaganza quest, where on the first fish turn in you get all of the 250 fishes you may have destroyed...

![video_1470745853](https://cloud.githubusercontent.com/assets/2879479/17522646/2ef44cb2-5e2e-11e6-8faf-616e8c096218.gif)

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
335

**TC hash/commit**:  
https://github.com/TrinityCore/TrinityCore/commit/ac35f93c2d6d5436054be474da06c9483e311c36

**TDB version**:  
TDB 335.61

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by dr-j** [comment]
Confirm also happens with the quest-in-quests for A sample of slime / and a batch of ooze where players must first correct samples from felwood/ungoro crater and then test them in undercity to hopefully get pure samples, all quest items are destroyed on first turn in

https://www.youtube.com/watch?v=VQ0gQCOpYXk

**Comment by tkrokli** [comment]
Extra info:
The 4 quests mentioned in the first post, links to their pages on gamepedia.com :
- http://wow.gamepedia.com/Quest:Beached_Sea_Creature_(1)
- http://wow.gamepedia.com/Quest:Beached_Sea_Creature_(2)
- http://wow.gamepedia.com/Quest:Beached_Sea_Creature_(3)
- http://wow.gamepedia.com/Quest:Beached_Sea_Creature_(4)

Links to the wowhead pages, note that the quests were removed in patch 4.0.3a
- http://www.wowhead.com/quest=4723/beached-sea-creature
- http://www.wowhead.com/quest=4728/beached-sea-creature
- http://www.wowhead.com/quest=4730/beached-sea-creature
- http://www.wowhead.com/quest=4733/beached-sea-creature

Quest item is the same, http://www.wowhead.com/item=12242/sea-creature-bones for all 4 quests,
just like Nyeriah said.

**Stranglethorn Fishing Extravaganza:** http://www.wowhead.com/event=301/301

**Comment by Aokromes** [comment]
@runningnak3d

**Comment by Nyeriah** [comment]
Yeah https://github.com/TrinityCore/TrinityCore/commit/da204ad78c0a960da9fe3ea009ac91f8f39b6af2#diff-5589ee47b3a7ad220cff105a8fe7eac3R14889

May be related to this curious "9999" value when deleting quest required items

**Comment by runningnak3d** [comment]
Are you supposed to be able to accept all of the quests at once? It was a long time ago that I played the that quest on offy, and I don't remember being able to accept all of them (in which case this would be a quest chain issue). If I am wrong, and you are supposed to be able to accept them all, then I will look for some flag that indicates whether ALL of the items should be destroyed, or only the required count. It is a simple fix in either case, just need to know what the offy like behavior is. I chose 9999 because it is not possible to have that many items in bags / banks / guild banks.

**Comment by Nyeriah** [comment]
Yes, you could, and as the other reporters mentioned, the issue isn't that quest *only*

**Comment by MrSmite** [comment]
> Are you supposed to be able to accept all of the quests at once?

In the case of the *Beached Sea Creature*, you get the bones by looting the various skeletons and that triggers the quest to return them to someone in town. I don't think there is any prerequisite for looting the bones other than having completed the *Washed Ashore* quests:

http://www.wowhead.com/?quest=3524
http://www.wowhead.com/?quest=4681

This is probably a more generic problem in that the code is ignoring the required amount. Maybe this was an old anti-cheat mechanic someone put in?

**Comment by Nyeriah** [comment]
@MrSmite Have you read the comments above? It's not checking for any stack, I've already pointed that out, and the author of the PR already acknowledged it too in the message you quoted. Whenever a quest is turned in, "9999" items are destroyed regardless of how many are required to actually complete the quest.

**Comment by MrSmite** [comment]
> Have you read the comments above?

I only quickly skimmed them after reading the OP and I didn't even look at the PR.

I have to question why the PR was necessary at all. The original code took care of deleting the required amount. Even if you were left with extras it shouldn't matter, the player can just destroy them.

**Comment by Shauren** [comment]
Because on retail you are not left with any extras

**Comment by MrSmite** [comment]
> Because on retail you are not left with any extras

Can you verify that behavior for 3.3.5 though?

**Comment by Shauren** [comment]
The "abandon quest on item delete" is he new thing (and not implemented yet, unless its handled clientside)

**Comment by dr-j** [comment]
That is not the issue and dont believe that functionality to remove quest on item delete did not exist in 3.3.5 only to remove quest items if quest is abandoned ie deleting quest item should have no effect even though you probably wont be able to return quest.

This issue is with repeatable quests where player may have multiple items in quest log and should be able to complete repeatable quest several times but currently can only be completed a single time as when turned in takes all quest items from inventory rather than just what was needed for turn in.

Think this issue is with repeatable quests with soulbound items.

**Comment by runningnak3d** [comment]
@dr-j "Think this issue is with repeatable quests with soulbound items." <-- THIS!

Dude, you found it. Only it isn't soulbound, it is quest bound items. If the quest is repeatable, then don't destroy ALL quest bound items that were associated with the quest. I just checked all the quests listed here plus a bunch of others and adding a check for qinfo->IsRepeatAble() will solve all these problems. Patch incoming....

**Comment by runningnak3d** [comment]
Hmmm ... I think the solution here is much simpler. If the item is quest bound and multidrop (bonding=4 && Flags&0x800) then delete all. I need some more examples of quests that should not delete all the quest items on turn in.

**Comment by Aokromes** [comment]
http://www.wow-one.com/forum/topic/6397-thorium-brotherhood-rep-guide/
