### ISSUE TITLE
Core/Loot Issue with item Reins of the Grand Black War Mammoth

### ISSUE THREAD

**Issue by sirikfoll** [TrinityCore/TrinityCore#17768]
**Description**:
Item Reins of the Grand Black War Mammoth(item=43959 | item=44083 ) can not be looted from [Toravon the Ice Watcher(npc=38433)](http://www.wowhead.com/npc=38433/toravon-the-ice-watcher) if the group is using Master Looter

I saw it fails on the check in player.cpp at line 25699

``` cpp
    if (!qitem && item->is_blocked)
    {
        SendLootRelease(GetLootGUID());
        return;
    }
```

but i dunno what causes that, note that this item is a conditional loot(different items for alliance and horde),could be related, or not.

**Current behaviour**: Everybody can see and try to loot the item, but nobody can actually loot the item, it fails for all of them.

**Expected behaviour**: Master looter should be able to select the player who will receive the item and be able to do so.

**Steps to reproduce the problem**:
1. Run sql bellow to increase the drop chance(original is 1%)

``` sql
DELETE FROM `creature_loot_template` WHERE `Entry`=38433 and`Item` IN(1,49426);
UPDATE `creature_loot_template` SET `Chance`=100 WHERE `Entry`=38433 and`Item`=2;
```
1. Assemble a raid group(2 players are enough)
2. Change lootMode to Master loot
3. .go crea id 38433 (just the leader with the master loot are enough)
4. Kill Toravon (.damage is fine)
5. Try to loot the Mount
6. See that you are not able to loot it

**Branch(es)**: 3.3.5

**TC hash/commit**:  70b3373da1d0

**Comment by Aokromes** [comment]
I am quite sure another ticket for this exist, not only for mount.

**Comment by sirikfoll** [comment]
there is, but nothing there is confirmed or doesn't even exist, this repro steps works

**Comment by Aokromes** [comment]
Yeah, but if it's a generic but better post there.

**Comment by sirikfoll** [comment]
Your call, i can't confirm that is generic, just saw it with the mount

**Comment by Aokromes** [comment]
I think it's the same as #14328

**Comment by dr-j** [comment]
Well confirm this but one thing I will say since on this subject of drop chance for this mount

Drop chance is currently 0.5% chance not 1% due to the fact that creature loot has 1% chance of calling reference loot and then the same reference loot entry contains both horde and alliance mounts and both are in same loot group resulting in 50/50 chance of correct faction mount which reduces chance to 0.5% as 1% chance of reference loot been called and then 50% chance of your factions mount been dropped

The solution to this is to put both mounts in different loot groups so when the reference loot is called both drop and then conditions deal with which is visible to players

~~~sql
UPDATE `reference_loot_template` SET `GroupId`=2 WHERE  `Entry`=34203 AND `Item`=43959;
~~~

This does not fix the reported issue though but this seems recent bug as this used to be always be master lootable.

**Comment by sirikfoll** [comment]
@jackpoz  This could be of your interest ^^

**Comment by sirikfoll** [comment]
Already fixed by https://github.com/TrinityCore/TrinityCore/commit/f5d3343f27f68c7837152fc592310397a686a83e 😄
