### ISSUE TITLE
Incorrect error message for name-unique items

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#17775]
3.3.5 330e5b0

When trying to equip two different versions of the same item (heroic vs normal), the error message displayed is incorrect.

**Repro:**
`.additem 50344`
`.additem 50341`
Try to equip both items.

Error message displayed incorrectly:
_"You have the maximum number of those gems socketed into equipped items."_

**Comment by tkrokli** [comment]
Could this be caused by a defined constant being too small, like uint8 instead of uint16 or smallint instead of uint8 (or even an explicit constant being too restrictive)?

**Comment by Treeston** [comment]
.......no

**Comment by Nawuko** [comment]
The problem is the `Player::HasItemOrGemWithLimitCategoryEquipped` check in `Player::CanEquipUniqueItem`. The `CanEquipUniqueItem` function returns `EQUIP_ERR_ITEM_MAX_COUNT_EQUIPPED_SOCKETED` if the `HasItemOrGemWithLimitCategoryEquipped` returns `false`.
Maybe the `Player::HasItemOrGemWithLimitCategoryEquipped` should return a InventoryResult instead of True/False.

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Player/Player.cpp#L10093

**Comment by Treeston** [comment]
fixed at some point since filing
