### ISSUE TITLE
[3.3.5] Phasing issues with Ebon Blade (shadow vault)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#17804]
3.3.5 dc78f1e

Since #17509 was merged, the Ebon Blade area is experiencing multiple phasing issues.

After you complete "It's all Fun and Games" (offered by Thassarian), you are (incorrectly) phased into the "liberated" Shadow Vault. Every time you accept a quest in the liberated vault, all present NPCs flicker for a second. Changing sub-zones fixes this and properly reverts you to the scourge-invested Vault. While outside the Vault zone, you can still see the "liberated" vault. Re-entering the zone shows the infested vault again, but accepting another quest (such as the follow-up from Baron Sliver) will phase you back into the liberated vault.

Overall, it's confusing (and buggy). Tagging @SnapperRy for this.

**Comment by dr-j** [comment]
Strange because there are only two spell_area spells for area id 4477 (The Shadowvault) one for horde and one for alliance both with quest end for If He Cannot be turned.

Sounds like something wrong with phasing system if phase changes between quests but this is not the only place where this happens as same with sons of hodir chain when npcs in the village turn hostile when you turn quest in leaving and returning also corrects that.

**Comment by SnapperRy** [comment]
This happens because there are two spell_area entries for this zone, as dr-j said. And both are checked against the player.

One will always be false (the one for the opposite faction), and so the spell will always be removed. The other will always be true (the one for the right faction), and the spell is re-applied. The order of remove/add aura depends on faction, so Horde will experience the opposite as Alliance. Confusing indeed :P

It is indeed an issue introduced by my commit. Need to filter search by both area and quest id. Working on it, thanks for the heads-up :)
