### ISSUE TITLE
creatures without equipment

### ISSUE THREAD

**Issue by ter884** [TrinityCore/TrinityCore#17821]
creatures without equipment
![wowscrnshot_081916_203228](https://cloud.githubusercontent.com/assets/6825541/17818465/597dc67c-664c-11e6-8c5b-2647a3fc16fa.jpg)
![wowscrnshot_081916_203455](https://cloud.githubusercontent.com/assets/6825541/17818475/6a40b5aa-664c-11e6-9a59-26db4f95fd43.jpg)

7.0.3
https://github.com/TrinityCore/TrinityCore/commit/650ab693a8366847d7db8bd8443b3b4aaf99ff85

**Comment by funjoker** [comment]
yeah tons of missing database stuff =)
Need patience till WPP works

**Comment by Kinzcool** [comment]
Aren't those supposed to be cataclysm NPCs?

**Comment by funjoker** [comment]
Maybe they changed some things due to Legion. That's why we should wait

**Comment by Killyana** [comment]
Equipments are on the DB, the problem is on creature table equipment_id=0
https://github.com/TrinityCore/TrinityCore/commit/f8d5031fca9a639d61e66f0122e1491d43e6fe44
https://github.com/TrinityCore/TrinityCore/issues/16416

**Comment by Farrarie** [comment]
its not fixed yet just compiled the latest trinitycore master 7.1.0 22996
![wowscrnshot_112316_210228](https://cloud.githubusercontent.com/assets/16207131/20573357/635c5568-b1c0-11e6-8ecf-7f65151c6d2f.jpg)

**Comment by Kizarr** [comment]
Description:
The NPCs are missing their respective equipment for weapons and should have all the gear equipped.

Current behaviour: The Scarlet Infantryman NPCs do not have weapons equipped.

Expected behaviour: The Scarlet Infantryman NPCs should have weapons equipped.
http://www.wowhead.com/npc=28609/scarlet-infantryman
http://www.wowhead.com/npc=28896/scarlet-infantryman

Steps to reproduce the problem:

Create a fresh Death Knight and complete quest line until you reach death breach go down below and you will see npc's with missing equipment.
http://image.prntscr.com/image/f24a6c7404ea4702b371585d0d473e53.png
http://image.prntscr.com/image/6fbfa55ca0b747e7bdf839ebbbfc8efd.png
Wowhead Images campare to my images:
http://wow.zamimg.com/uploads/screenshots/small/556933.jpg
http://wow.zamimg.com/uploads/screenshots/small/90138.jpg

Branch(es): 3.3.5 / master

TC rev. hash/commit: c809c22

TDB version: TDB_full_world_335.62_2016_10_17 + updates

Operating system: Windows Server 2012 R2

Note: It is located in the database in creature_equip_template because I fixed this issue before manually I had to find the weapons and shield ID from wowhead for the npc's I spent a hours try to find the correct equipment on wowhead.

**Comment by Killyana** [comment]
This issue is fixed, if the npc doesn't have any equipment it means data is missing.
