### ISSUE TITLE
[6.x] Crash on WorldSocket updater

### ISSUE THREAD

**Issue by Nelidon** [TrinityCore/TrinityCore#17862]
can be closed

**Comment by OrzelBialy** [comment]
What's heimcore? I don't think this crash is related to TrinityCore. Also, 200/300 connected? Definitely pserver activity here, which TrinityCore does not support. Development for educational purposes involves 1 person connected, and I've left TrinityCore running over night many times with no crash.

**Comment by Nelidon** [comment]
Sorry guys, i won't disturb you again.

**Comment by funjoker** [comment]
I think He named it like that, like indicating that He works at home in it. HomeCore

**Comment by jackpoz** [comment]
> Also, 200/300 connected? Definitely pserver activity here, which TrinityCore does not support.

who are you and why do you talk like if you were the official voice of TrinityCore project ?

**Comment by OrzelBialy** [comment]
@jackpoz Is there anything about my statement which is inaccurate? Does TrinityCore support private servers?

**Comment by tkrokli** [comment]
@OrzelBialy : it is not inaccurate, but I have experienced myself how statements like that can be taken as a discouragement or felt like a very negative response to the user who posted the issue in question. It is better left to the TrinityCore developer team members to decide if the issue content breaks any rules or not and then reply to the issue author if the issue is invalid or contains invalid data for TC troubleshooting.

As you can see, none of the actual TC members have posted any negative comments here. They have instead labelled this issue correctly as a Branch 6.x issue related to "Comp-Core" and with BackTrace. What the source code is used for by the issue poster matters less than keeping the source code itself mostly unmodified to be able to trace the origin of a crash or other problems.

@Nelidon : Please don't feel discouraged from contributing. If you still have got the crash dump, feel free to add it back to your original issue post (first comment) and continue testing the TC 6.x source. :+1:

**Comment by OrzelBialy** [comment]
@tkrokli Well written response, you're quite the diplomat :)

**Comment by jackpoz** [comment]
> Is there anything about my statement which is inaccurate?

All of it, plus the fact that you added no useful info to the issue and instead made the author delete it.
I kindly ask you to stop doing that. If you don't have any info about the issue (in this case possible reasons of the crash or how to reproduce steps), then please don't write anything at all.
