### ISSUE TITLE
[7.0.3] connection_patcher.exe problem

### ISSUE THREAD

**Issue by jcmillions** [TrinityCore/TrinityCore#17975]
**Description**: The connection_patcher works and everything, but the realms say incompatible.

**Current behaviour**: Realms say incompatible even though my wow.exe is patched and the realmlist build is updated in the DB.

**Expected behaviour**: The realm should not say incompatible.

**Steps to reproduce the problem**:

1. Update to the latest legion build
2. Patch your wow.exe
3. login and see that you can't change to a different realm

**Branch(es)**: 6.x

**TC hash/commit**:  3c0b075

**TDB version**:  6.0.4 with latest updates

**Operating system**:  Windows 7 Ultimate x64

**Comment by Aokromes** [comment]
update you core / db / client. there is no such thing as latest.

**Comment by jcmillions** [comment]
Closed, yet no help at all. I understand you guys are busy and are probably tired of helping people out, but you could just tell me that. I'd completely understand.

**Comment by DDuarte** [comment]
Build was changed to 7.0.3.22624 (only) 6 hours ago: https://github.com/TrinityCore/TrinityCore/commit/3c0b075df50efc5e868557ae4b82d8d0f8df8fc2

You need to update your core and DB so that it matches your client build (which you haven't specified).

**Comment by Aokromes** [comment]
I told you what to do to fix your "issue" documented on readme 1st what you must read before posting issues.

**Comment by jcmillions** [comment]
I am running 7.0.3 22624, TDB 6.0.4 with all updates, everything is up to date because I cloned the repository 2 hours ago, the build number in the auth database is up to date, and I patched both the wow.exe and wow-64.exe using the connection_patcher.exe with admin privileges. And I just want you to know that I wasn't trying to be rude in any way shape or form.

**Comment by DDuarte** [comment]
The only person rude here is Aok.
Issue under triage

**Comment by jcmillions** [comment]
@DDuarte Thank you much sir :)

**Comment by Shauren** [comment]
Cannot reproduce myself, using connection patcher built on db29752fa0e8 (2016-07-22), Wow-64 build 7.0.3.22624
![wowscrnshot_092116_230706](https://cloud.githubusercontent.com/assets/297439/18729027/4cbafa40-8050-11e6-9917-6e2b8d17232d.jpg)

**Comment by jcmillions** [comment]
Strange... Well thank you for the help, maybe the auth DB needs reinstalled. If it works then I'll post it on here so other people have a fix if they get the same issue. I appreciate the help and the hasty responses though :D

**Comment by JaredNinja** [comment]
Can you take a look at the columns in your auth->realmlist and see if the client build number matches the one you find in there?

This error almost always means there is a mismatch between the client and database. That usually is caused by the client updating itself while the DB is not yet updated or the other way around.

To play it safe, just disable client updates (wow game) and DB updates (world server config) once your setup is working.

You can always update again when you know Trinity/TDB is compatible with the latest wow client.

(Ps; use at your own risk.. sometimes you can simply change the build number in the realmlist table to correspond to your client build. Then it works again. Obviously this does mean your Trinity/Database is not actually upgraded and tested with the new client build, so it could cause trouble)
