### ISSUE TITLE
6.x extractor have some bug

### ISSUE THREAD

**Issue by bozoweed** [TrinityCore/TrinityCore#17990]
**Description**: the same probleme like this https://github.com/TrinityCore/TrinityCore/issues/14321
but on new update
error on vmpas extract/compile

**Comment by Aokromes** [comment]
ignore template is evil.

**Comment by bozoweed** [comment]
?

**Comment by tkrokli** [comment]
@bozoweed : 1) You did not include build ver. (TC rev. hash) & DB version info from your core. 2) The error messages you see can usually be ignored (although the safe error messages should have been hidden). 3) This issue is a duplicate of issue #14321 (even if the other issue is closed, but it is seen as a non-important case).

Also: "ignore template is evil." refers to the fact that you removed the lines TC want you to use to fill in the necessary info for better troubleshooting of any new issue. Next time, please keep that info (don't remove).

**Comment by bozoweed** [comment]
okey thanks
