### ISSUE TITLE
Scripts/Azjol: Anub'arak

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#18013]
**Description**:
Incorrect wall behaviour

**Current behaviour**: Tell us what happens
Wall instantly appears when engaged

**Expected behaviour**: Tell us what should happen instead
There should be a 5 second ish timer on the wall

**Steps to reproduce the problem**:
1. attack

**TC hash/commit**:  a573e8f680429c03abba6e04f9bc326a0ebfb378

**Comment by Treeston** [comment]
Do you have a recording of this on retail? As far as I remember, the visual GO would appear immediately, but wouldn't have any collision for the first few seconds.

**Comment by SnapperRy** [comment]
[Here](https://www.youtube.com/watch?v=RV0CvQIoxoU) you can see that the wall appears roughly 7 seconds after the fight starts

**Comment by ConradBunton** [comment]
I have a problem with Anub. He respawns again and again...

**Comment by ConradBunton** [comment]
I have a problem with the Anub'ar crusher. He endless respawns.

**Comment by tkrokli** [comment]
@ConradBunton : If your problem is an issue for all users of the source code, please open a new ticket
(as long as there is no existing open issue ticket for it already).

Otherwise, post in the TC forum pages or ask in the IRC channel [`#trinity` @ irc.rizon.net](https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130200/IRC)
