### ISSUE TITLE
[6.x/7.x] SPELL_EFFECT_SUMMON

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#18036]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: some Creatures are Not summoned 

**Current behaviour**: A lot of creatures are Not summoned. I guess because of incorrect summonproperties? 

**Expected behaviour**: spawn npc with correct summonproperties 

**Steps to reproduce the problem**:

1. Use a spell with this effect with MiscValueB > 1400
2. 
3. 

**Branch(es)**:  6.x

**TC hash/commit**:  
2b4006f
**TDB version**:  
6.04
**Operating system**:  

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by matukaa** [comment]
Blizzard changed the format of their DB structure. You will need to update it properly, check [here](https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/DataStores/DB2Structure.h#L2546).  
Current order is ID, Flags, Category, Faction, Type and Slot.
Also a really important change. [Flags](https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/DataStores/DB2Structure.h#L2553) for you is set to uint32. Since legion there are some spells that have slot = 255 (that is -1 for uint8 type). If you don't change it to uint8, you will crash the server each time such a summon happens. There is a check for the summons `if (slot > 0)` already, but you must update it to uint8, since Player::m_SummonSlot is defined as an array with static 9 elements (that is, you try to reference the 255th element in an array of size 9)

**Comment by vanasis** [comment]
```
diff --git a/src/server/game/DataStores/DB2Structure.h b/src/server/game/DataStores/DB2Structure.h
index 7be7706..6415c0b 100644
--- a/src/server/game/DataStores/DB2Structure.h
+++ b/src/server/game/DataStores/DB2Structure.h
@@ -2530,12 +2530,12 @@ struct SpellXSpellVisualEntry
 
 struct SummonPropertiesEntry
 {
-    uint32 ID;
-    uint32 Category;
-    uint32 Faction;
-    uint32 Type;
-    int32 Slot;
-    uint32 Flags;
+    uint32 ID; 
+    uint32 Flags; // wrong
+    uint32 Category; 
+    int32 Faction; 
+    uint32 Type; 
+    uint32 Slot;  // wrong
 };
 
 #define TACTKEY_SIZE 16
```

use this code for test

**Comment by Shauren** [comment]
@vanasis nice find, but not a complete solution (you would need to update summon_properties table structure in hotfix db)

**Comment by nerv234** [comment]
With this totems have white and blue boxes models

**Comment by vanasis** [comment]
I'm not sure you summoned totems right , but for blue boxes issue I think problem is in 

> uint32 Unit::GetModelForTotem(PlayerTotemType totemType)

that function called in 

> void Totem::InitStats(uint32 duration)

and the **PlayerTotemType**  need right MiscValueB to process but totem MiscValueB has changed originally from blizzard so the old GetModelForTotem() not work correctly
need a more research for totems 

>

here is a old datas
```
enum PlayerTotemType
{
    SUMMON_TYPE_TOTEM_FIRE  = 63,
    SUMMON_TYPE_TOTEM_EARTH = 81,
    SUMMON_TYPE_TOTEM_WATER = 82,
    SUMMON_TYPE_TOTEM_AIR   = 83
};
```

For test ( if totems summoned correct from SummonPropertiesEntry or No) I find a totem that it must work correct  ( yes it must work with old totem **GetModelForTotem**
here is the id of that totem

> ID - 108280 Healing Tide Totem

@nerv234 you can summon this totem with right Visual ( not like a blue box ) , But other totems were not lucky

**Comment by funjoker** [comment]
thanks

**Comment by matukaa** [comment]
as @Shauren said it's not complete. I've mentioned already that Slot is not correct (check SummonProperties.db2)

**Comment by Shauren** [comment]
Slot IS correct. All that changed was Flags being moved, everything else kept the relative order it had before.
