### ISSUE TITLE
[3.3.5] Quest: Gambling Debt (11464)

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#18063]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:
I can't complete this quest.
This quest has not worked due to second gossip option never getting displayed to player to collect the debt after beating "silvermoon" harry down.

http://www.wowhead.com/quest=11464/gambling-debt
https://www.youtube.com/watch?v=pMWuvYX-Tco

**Branch(es)**: 3.3.5 / 6.x 
**TC hash/commit**:  
TC>TrinityCore rev. 10437a1e2ec0 2016-10-09 01:55:14 -0300 (335 branch)
**TDB version**:  
TDB_full_world_335.61_2016_04_11.sql + updates
**Operating system**:  
Win7 64Bit

**Comment by SnapperRy** [comment]
The issue here is that the npc resets almost instantly, so it keeps showing the "fight me" dialogue.

Right-click him really, really fast after defeating him, and the right gossip will appear.

Will fix. :P

**Comment by dr-j** [comment]
its because condition to display second gossip option uses condition for health but at this moment the sai action for disable regen hp is broken so as soon as npc evades ready to display gossip option hp resets so condition to display second gossip option is never displayed.

Think this has been broken since around the time of that commit to fix loading hp from creature_template

**Comment by SnapperRy** [comment]
Going to rewrite SAI to use event_phases instead. Although they reset on evade... need to change that in core first. SAI phases should always be handled via script.
