### ISSUE TITLE
[7.x] Chat Channels

### ISSUE THREAD

**Issue by cocolino** [TrinityCore/TrinityCore#18078]
**Description**: Chat channels do not work properly.

**Current behaviour**: Chat channels do not display at login / zone change.

**Expected behaviour**: When you login you should be notified of joining local channels. Also on changing zones / teleporting you should be notified of channels you join / leave.

**Steps to reproduce the problem**:
1. Login. Teleport to any zone afterwards.
2. No Channels shown on either.
3. Commenting out "return on login" first code lines in void Player::UpdateLocalChannels(uint32 newZone) does not fix the login display problem.
4. I found that going in instances like ICC and out seems to "temp-fix" it, and channels will display afterwards (even after going out / teleporting to some other place).
5. Also found that there is a new ChannelFlags enum value, 0x100, which seems to be sent as base for any built-in ones (might be something like CHANNEL_FLAG_BUILT_IN maybe?), on top of which the other flags like CHANNEL_FLAG_GENERAL etc. are added. This is not implemented yet.
6. Also, it seems Channel::JoinChannel does not currently use sWorld->GetAvailableDbcLocale(locale) for building channel names (LocaleConstant locale not used in builder).
7. Unsure if these are all connected to the base problem, i even suspected the packets string sizes changed, but it doesn't look like it.

Note: Thank you! :smiley: 

**Branch(es)**: 6.x (7.x)

**TC hash/commit**:  b4c47817234a99c0a4032a24cef90e11c54df701

**Comment by tkrokli** [comment]
Which mode(s) did you check this in (out of these) : `.gm on` / `.gm off` / `.gm visible` / `.gm invisible`

**Comment by DJScias** [comment]
Hello there,

I spoke to @ariel- a while ago about this on IRC and came to the conclusion that the issues were introduced in the following commits: https://github.com/TrinityCore/TrinityCore/commit/015bc75d7577b6832f9152d8c26f9a74630a0f16, https://github.com/TrinityCore/TrinityCore/commit/8a35fb2323e0d587e62275df51de06d7d2ee277b, 
https://github.com/TrinityCore/TrinityCore/commit/5071dc8465583d5491215b022508468606ce482e and https://github.com/TrinityCore/TrinityCore/commit/59a9bc5ca0ae81ef58107f9b24b1a92b11478fd8.

By reverting these (in the order as I've posted them, latest -> oldest) the chat channels should once again work as before. Whether or not ariel wants to try this on the master branch or try to figure out the issue is up to him.

Kind regards,
DJScias

**Comment by Aokromes** [comment]
This bug is still valid?
