### ISSUE TITLE
[6.x] Mount spells with attribute SPELL_ATTR0_DONT_AFFECT_SHEATH_STATE appear as debuff + spell targeting broken

### ISSUE THREAD

**Issue by nerv234** [TrinityCore/TrinityCore#18072]
**Description**:  Mount spells with attribute SPELL_ATTR0_DONT_AFFECT_SHEATH_STATE appears as debuff instead of buff and also some spells targets caster instead of target. I think it is related to d34020da7f34943e9cc84482ce19f829154334bd and this is why i made single issue about it.

**Steps to reproduce the problem**:

1.  `.cast 171850` (http://www.wowhead.com/spell=171850/llothien-prowler).
2.  You will see mount aura as debuff instead of buff.

Steps to reproduce second problem:
1.  `.cast 80240` (warlock spell http://www.wowhead.com/spell=80240/havoc)
2. You'll see debuff is applied to caster instead of target.

**Branch(es)**: 6.x

**TC hash/commit**:   ac4cb2b98494d0238306b08344ad0bfd88aa8395

**TDB version**:  Latest (not related to db)

**Operating system**:  win7 (not related)

Btw. Do you thought about renaming 6.x branch to sth. like 7.x?

**Comment by tkrokli** [comment]
About "renaming 6.x branch to  sth. like 7.x" - it would be better to create a new branch named 'master' and move any open issues and Pull Requests to the new branch, because renaming the current 6.x branch will cause all the existing open issues and PRs to close (it would unlink the existing issues and Pull Requests from the existing branch they are linked to). But that change will also create more work than most TC developers currently can find the time to do, because none of them are paid to maintain it.

Secondly, the ideal way of reporting issues is to report only 1 specific problem in each new issue (given that there are no already open issue tickets about that problem).

**Comment by Magoxx** [comment]
confirm not only mounts, many spells do damage to caster instead enemy.

**Comment by joschiwald** [comment]
target is loaded as 1 where 0 is excepted
