### ISSUE TITLE
[3.3.5][CRASH] When creature Vacillating Voidcaller (ID: 19527) is in combat

### ISSUE THREAD

**Issue by noryad** [TrinityCore/TrinityCore#18225]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** When creature Vacillating Voidcaller (ID: 19527) is in combat

**Current behaviour:** When creature Vacillating Voidcaller is in combat the server stops.

**Expected behaviour:** When creature Vacillating Voidcaller is in combat the server must works ok.

**Steps to reproduce the problem:**
1. Go to south of Hellfire in Outland.
2. To attack any Vacillating Voidcaller.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  51bd38a

**TDB version:**  335.62 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
Can't reproduce in 70a867531d6c6dba13dcd56a44db855b39aa6471

**Comment by jackpoz** [comment]
When you clicked on "New issue" there was on top
>Please review the guidelines for contributing to this repository.

That had a link to https://github.com/TrinityCore/TrinityCore/blob/master/CONTRIBUTING.md  with a section
>Issues
Read this before creating a ticket.

which pointed to https://community.trinitycore.org/topic/37-the-trinitycore-issuetracker-and-you/ .

You are reporting a crash without a crash log which means we cannot fix anything because there's nothing to fix. Please read the links above and post a proper crash report.

**Comment by noryad** [comment]
I am sorry i forgot to attach de log file, it will not happen again, About the issue in newest revision works ok. Thankyou.
