### ISSUE TITLE
[Master] Improper Reward Placement in Quest Dialogue Box - Invaders in our Home

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#18372]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Reward picture is showing up in a very odd location in the middle of the quest text box. Quest is Invaders in our Home - No. 25172. See photo. 

**Current behaviour:** This.... http://i.imgur.com/yhZ5Za3.jpg

**Expected behaviour:** Photo should be at the bottom of the quest box. 

**Steps to reproduce the problem:**

1. Roll toon to Horde Orc start area Valley of Trials. Complete 'Cutting Teeth' and turn in.
2. Accept next quest in chain.
3. Observe

**Branch(es):** Master
**TC rev. hash/commit:**  e0fb444

**TDB version:**  7.x

**Operating system:**  Win 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
TrinityCore rev. 8b2e07166f72 2016-12-14 00:09:32 +0100 (master branch) (Win64, Release, Static) / TDB 703.00 + updates up to and including `2016_12_13_00_world.sql`

Cannot confirm, the problem seems different from my side:
1. http://www.wowhead.com/item=53378/mottled-bracers is a reward from http://www.wowhead.com/quest=25126/cutting-teeth and **_not_** from http://www.wowhead.com/quest=25172/invaders-in-our-home
2. My version of the issue seems to be that the reward item image does not show up in the Quest Gossip window at all (only money & XP), but it shows up in its expected spot in the Quest Log:

![wowscrnshot_121416_234322](https://cloud.githubusercontent.com/assets/4903600/21204527/34f56d6a-c258-11e6-9455-91ec9444071e.jpg)

![wowscrnshot_121416_234355](https://cloud.githubusercontent.com/assets/4903600/21204547/411e7e06-c258-11e6-9634-e6b407a73713.jpg)

I also tried to reset my game settings (game client version 7.1.0 (23222)), but it still looks the same. Not sure if I need to rebuild my DBC, maps & GT folders, they are fairly recent (48 hours old).

My immediate reaction is that there is something off, either in your DB, source or DBC/DB2/GT folders. Not sure where the problem lies, but the reward image shows up in the wrong quest for you.

**Comment by Shauren** [comment]
@tkrokli but something is wrong with your screen as well (1st picture), rewarded item is completely missing on it

**Comment by tkrokli** [comment]
Yes, I tried to describe what I found like this (maybe I was too vague about it) :
> the problem seems different from my side:

Not sure if this happens to others, it would be nice if someone else could confirm or refute this issue.

**Comment by BahDumbBugs** [comment]
As of commit 6bfcdea, everything appears to be normal (AS FAR AS I CAN SEE - with an Orc Warlock). I compared it side by side, blow by blow with retail and the *ONLY* thing missing is reputation with Orgrimmar increasing after each quest. But that's another ticket. I recommend we have other people confirm all is working with other classes before we close this. My notes read, for Cutting Teeth, 
Rewards: Mottled Bracers, 65 Copper, 220 Exp. (Retail gave +250 Rep with Orgrimmar)

**Comment by tkrokli** [comment]
So in your latest test, you did not see any issues in the graphics at all, the reward image being present in the right spot even in the first Quest dialog window too? (just so we are clear on that detail, that I may have had a local bug in my test and that it does not appear to other users)

**Comment by BahDumbBugs** [comment]
Correct. Everything shows up as normal. Including preceding quests and next quest items.
