### ISSUE TITLE
[3.3.5] Spell/Druid: Cyclone on targets under cyclone effects should be immune

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#18479]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Cyclone: Tosses the enemy target into the air, preventing all action **but making them invulnerable** for up to 6 sec...

**Current behaviour:** 
In current revision when the target is under effects of cyclone and the druid casts cyclone again, the target is affected.

**Expected behaviour:** 
The targets under cyclonic effects should be immune to cyclone while the effect is active.

**Steps to reproduce the problem:**
1. Druid casts cyclone to target under cyclonic effects.
2. Target is affected again.

**Branch(es):** 3.3.5 

**TC rev. hash/commit:**  e1a2b1a

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
Part of 560c882b364630bf95e1c6859ceaa6fa3cb6ed2e...

If IsRankOf is removed, breaks Banish (because effect shouldn't be immune to itself), if it left it breaks Cyclone (because effect SHOULD be immune to itself)

Now, comparing both Cyclone and Banish, the only differences are:
Dispel Type: Cyclone has NONE; Banish has MAGIC

Spell Attributes: 
Cyclone 
Attributes: 0x00010000 (SPELL_ATTR0_NOT_SHAPESHIFT)
AttributesEx4: 0x20000800 (SPELL_ATTR4_UNK11, SPELL_ATTR4_UNK29)

Banish
Attributes: 0x40010000 (SPELL_ATTR0_NOT_SHAPESHIFT, SPELL_ATTR0_HEARTBEAT_RESIST_CHECK)
AttributesEx2: 0x00000040 (SPELL_ATTR2_CANT_TARGET_TAPPED)
