### ISSUE TITLE
3.3.5 - Into The Wild Green Yonder

### ISSUE THREAD

**Issue by starrheld** [TrinityCore/TrinityCore#18729]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

Description: bugged can't drop off the NPCs

Current behaviour: bugged can't drop off the NPCs... says ability not ready

Expected behaviour: You should be able to drop off the NPCs

Steps to reproduce the problem:

1. Fly and grab an NPC
2. fly back
3. try to drop it off

Branch(es): 3.3.5

TC rev. hash/commit: 5c1fe47f7a1f6e192a109536020e789943da3fc1 

TDB version: 3.3.5.62

Operating system: Windows 7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
TrinityCore rev. de4eee3abbc3 2017-01-05 01:20:34 +0100 (3.3.5 branch) (Win64, Release, Static) / TDB 335.62

No problem at all dropping them off, as long as I was near Father Gustav and the burning Bonfire. Maybe you tried to drop them off somewhere else within the Argent Vanguard? That will cause a warning like yours, because you try more than 1 time to drop them off outside of the target area.

(The only issue I could see was a visual cosmetic issue where the flying vehicle animation froze after each delivery, but the animation started working again as soon as I picked up the next Crusader in Scourgeholme.)
