### ISSUE TITLE
Disconnected from server on Character Creation/Selection screen

### ISSUE THREAD

**Issue by MauroEldritch** [TrinityCore/TrinityCore#18734]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description: Get Disconnected from Server error on character creation/selection screen (not related to pressing the BACK button-old bug)**

**Current behaviour:** Whenever I try to create a character or select one, after no more than 50 seconds (not idle), I get disconnected from server error. Worldserver does not crash nor display any error. This does not happen once playing (managed to create a character fastly and logged into the world)

**Expected behaviour:** It shouldnt be disconnected, as Im not AFK/idle.

**Steps to reproduce the problem:** 

1.  Login
2.  Create a character or if created, wait a few seconds in selection screen.
3.  Crashes.

**Branch(es):** 3.3.5 

**TC rev. hash/commit:** TrinityCore rev. e3700df8fa8b 2017-01-02 21:38:05 +0100 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)
Using SSL version: OpenSSL 1.0.2j  26 Sep 2016 (library: OpenSSL 1.0.2j  26 Sep 2016)  

**TDB version:**  TDB_full_335.62_2016_10_17

**Operating system:**  Windows 7 Pro SP1 64/Bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Star-lion** [comment]
I was sitting on the character creation screen for 5 minutes without this happening. This could be a networking issue with the server you are trying to use.

**Comment by tkrokli** [comment]
TrinityCore rev. a88d4e9b0014 2017-03-21 19:21:11 -0300 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.0.2j  26 Sep 2016 (library: OpenSSL 1.0.2j  26 Sep 2016)
Using World DB: TDB 335.62

I have never had any disconnect from the character selection or create screen unless I closed the Worldserver by mistake or messed about with my Firewall settings. I often spend several minutes on the character creation screen, sometimes so much time that I get logged off for inactivity, just because I can't decide on the character name. I have never had any disconnect caused by the Worldserver while on the character screen in all the years I have been using TC source since 2013.

I don't think this issue has got anything to do with the source. I vote for closing this issue, both because nobody else has reported it and because it is most likely a local network or OS software issue instead of a TC source code issue.

**Comment by MauroEldritch** [comment]
Agreed, you can close it. After a clean reinstall, everything worked fine. Thanks.

**Comment by Aokromes** [comment]
you can close your own tickets yourself.
