### ISSUE TITLE
[Crash] Hunter spell ''Mongoose Bite''

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#18867]
**Description:**  

The spell ''Mongoose Bite'' [Spell ID: 190928] of Hunter class, in the specialization of survival, is crashing the server.  

**Current behaviour: (Tell us what happens.)**  

When using the spell ''Mongoose Bite'' [Spell ID: 190928] on an enemy target, the spell crashes the server. The console show "\src\server\game\Spells\Spell.cpp:1191 in Spell::SelectImplicitAreaTargets ASSERTION FAILED:false && "Spell::SelectImplicitAreaTargets: received not implemented target reference type""  

**Expected behaviour: (Tell us what should happen instead.)**  

When using the spell ''Mongoose Bite'' [Spell ID: 190928], it shouldn't create any critical failure to the server.  

**Steps to reproduce the problem:**  

1. Create a Hunter character.  
2. Reach level 20.  
3. Use the spell ''Mongoose Bite'' [Spell ID: 190928] on an enemy target.  

**Branch(es):**  
Master  
**TC rev. hash/commit:**  
6f669043  
**TDB version:**  
7.0.3+updates  
**Operating system:**  
Windows 10

**Comment by tkrokli** [comment]
Please follow the rules in https://github.com/TrinityCore/TrinityCore/blob/master/CONTRIBUTING.md
- When reporting a crash, you MUST compile in debug mode because release dumps are useless (not enough information) - if you don't know how to compile in debug, read [this](https://community.trinitycore.org/topic/1518-trouble-with-your-trinity-install-starting-login-readme-1st-faqs/?#comment-47672)

**Comment by Edreisantafe** [comment]
Thanks, I thought it was an incomplete or poorly implemented method, when I have the debug I leave it here.

**Comment by Keader** [comment]
same case https://github.com/TrinityCore/TrinityCore/issues/18868#issuecomment-273220847
