### ISSUE TITLE
[3.3.5] Crash Exploit

### ISSUE THREAD

**Issue by HelloKitty** [TrinityCore/TrinityCore#19128]
[redacted]

**Comment by Vincent-Michael** [comment]
you should build in debug and post the crashlog

**Comment by HelloKitty** [comment]
@Vincent-Michael It's because of WorldSocket::HandleAuthSession's reading of addon data that didn't get sent.

I'll compile a debug build and post the log though as soon as I have a chance.

**Comment by HelloKitty** [comment]
Here is the debug crash log https://gist.github.com/HelloKitty/9f111c683c608834427244e72c5bfd8e

**Comment by jackpoz** [comment]
Unhandled ByteBufferSourceException()

**Comment by Keader** [comment]
why  closed?

**Comment by HelloKitty** [comment]
@Keader Jackpoz posted the solution. I'm a player first before developer and the realms I play on are affected by the issue so I don't want the information available to repro it to be available now that a solution is available.

**Comment by Keader** [comment]
yes... but has no commit fixing it, so this issue should keep open.

**Comment by r00ty-tc** [comment]
@HelloKitty if you don't want to include detailed methods to perform an exploit, then put all the info in an unlisted pastebin and send to an @ or % in channel. Including steps to reproduce and any crash dumps you have.

Don't just remove all the information "because private servers". Where do you think most of them are going to get any correction for this?

**Comment by jackpoz** [comment]
as a step to reproduce the issue just throw ByteBufferSourceException() in the auth handler of WorldSocket .
