### ISSUE TITLE
vmap extractor fails on 23420 (Linux)

### ISSUE THREAD

**Issue by rmcshane** [TrinityCore/TrinityCore#19237]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

Running vmap4extractor on a recently patched client to build 23420 is failing. mapextractor completes without any errors. Then ran vmap4extractor which fails with `Read Map.dbc file... Fatal error: Invalid Map.db2 file format! BAD_FORMAT`. Both server and client running on Linux (Ubuntu 16.04).

**Current behaviour:**

[vmap4extractor output](https://gist.github.com/rmcshane/b2c2b0c17bee274f9bf93b69015b48e9)

**Expected behaviour:**

Previously this had no errors and successfully extracted vmap files.

**Steps to reproduce the problem:**

1. Update client to 23420 through updater (via WINE in my case)
2. Pull latest from master
3. make TC according to regular instructions
4. run mapextractor
5. run vmap4extractor

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. 59d48ce7e42a 2017-03-01 22:03:35 +0100 (master branch) (Unix, Release, Static) (bnetserver)

**TDB version:**  Haven't gotten this far

**Operating system:** Ubuntu Server 16.04 / Kubuntu desktop 16.04

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
TrinityCore rev. 53d535dfc901 2017-03-05 04:02:47 +0100 (master branch) (Win64, Release, Static)
TDB 703.00 + updates up to & including `2017_03_05_04_world_2016_10_04_04_world.sql`

I doubt that the TC source code is responsible for those errors. I find it more likely that they are the result from missing file access rights or file system read errors, even though there are no external error messages in your log. (I don't know if you have run this on a VPS or some other external host where your admin rights might be limited.) I also think it is possible that your game client is incomplete (maybe something unseen happened in the WINE session?), thereby causing all the `No such file.` error messages, including the `Could not open all Group file for:` messages.

Here is what the CMD + vmap4extractor output looks like when run on my local Windows 10 computer:
https://gist.githubusercontent.com/tkrokli/e8723fabcbe9f28d6e86a7f77183af06/raw/4686f9e0b60babb6058b12072017cd5d64b89aa8/vmap4extractor.txt

Notice also that if your personal issue had been caused by the TC source, more people would have reported it or confirmed it on this page.
