### ISSUE TITLE
Items disappearing from inventory bags after disconnect

### ISSUE THREAD

**Issue by Pixel-Pirate** [TrinityCore/TrinityCore#19252]
**Description:** inventory in secondary bags disappearing after a disconnect.

**Steps to reproduce the problem:**

1. Create a character
2. Add one or more Item in a secondary bag
3. Quit realm and reconnect
4. Items are not in bag.

**Branch(es):** master

**TC rev. hash/commit:**  53d535dfc90148ed5b5a2a01d1c4c05d8bdafad9

**TDB version:** Latest 

**Operating system:**  Linux

**Comment by HannibalRoG** [comment]
I can´t reproduce that problem.

**Comment by Pixel-Pirate** [comment]
In table character_inventory if I change column bag with a value different from 0 and if I connect to the realm, my item disappeared and is no longer present in the bag where I placed it. This is how this item wasn't loaded by core.

Very very strange. With clean database en core.

**Comment by Rochet2** [comment]
> In table character_inventory if I change column bag with a value different from 0 and if I connect to the realm, my item disappeared and is no longer present in the bag where I placed it.

Can you give a detailed description of what you are doing?
Currently it sounds like you added an item to a player and the item was in his main backpack. Then he logged out and you edited the item's bag column in character_inventory to for example from 0 to 1 and then tried to log in with the character. Then you observed that the item is not in backpack and not in any of the additional bags you are carrying. Is this right?

Because if this is what you did, then you should know that 1 is not really a backpack number, so you are not going to find the item from any backpack.

Why are you editing the database manually and what is it that you are trying to accomplish with it?

**Comment by Pixel-Pirate** [comment]
Hi Rochet2,

When I go in game and then une .add command with any item, for exemple .add 123456, if I switch this item into an additional bag and then disconnect from world and come back into world pouf the item is not in my secondary bag but in database in character_inventory the item is here so I change the value of bag collum to 0 (main bag) and log into again, now the item 123456 is loaded by Core and in my main bag.

**Comment by Shauren** [comment]
and you still did not explain how are you doing this? by editing db? ingame moving bag?

**Comment by Pixel-Pirate** [comment]
Moving item in anu secondary bag (in game)

**Comment by MrSmite** [comment]
> the item is not in my secondary bag but in database in character_inventory the item is here so I change the value of bag collum to 0 (main bag) and log into again, now the item 123456 is loaded by Core and in my main bag.

* Before you make this change, what is the value in the column? It's possible it is an invalid bag ID.
* Are there any console errors triggered when you move the item, before logging out?
* Are there any console errors triggered if you log in before editing the db?

**Comment by Pixel-Pirate** [comment]
0 error. The problem was solved by a complete reinstallation of sources and the databases. It will remain a real mystery :) Thanks you for you help boys !
