### ISSUE TITLE
Core/GameObjects: GAMEOBJECT_TYPE_DOOR

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#19261]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:** GAMEOBJECT_TYPE_DOOR turn closed after 5 secs of ativation

This happen only with the gm command, if the gob is licked it will remain open

**Current behaviour:** After activation doors turn closed

**Expected behaviour:** Doors must remain open after activation if data2=0

1. .go obj 20835 (ID: 18895)
2. .gob act 20835
3. After some seconds the door will turn closed

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 8089f1816c9b

**Comment by karlbunch** [comment]
Just tested on e1f14215d86fc9f0cd041f0e87bf0a689c086329 and the door stays open.

Looked at changes between e1f14215d86fc9f0cd041f0e87bf0a689c086329 and 8089f1816c9b5a53a94711586530c808509c5f33 found 7567cafec84080d26ea513242a1f540a823b8f9d which resulted in the changes from seconds to ms for GameObject's.

.gob act uses [object->UseDoorOrButton(10000, false, handler->GetSession()->GetPlayer());](https://github.com/TrinityCore/TrinityCore/blob/8089f1816c9b5a53a94711586530c808509c5f33/src/server/scripts/Commands/cs_gobject.cpp#L94)

The latest change makes '.gob act' timeout in 10s instead of 10,000 seconds: 071ba2c924ce4b27c9e16b38277ac729500f7445

Perhaps @xinef1 or someone can edit the call in HandleGameObjectActivateCommand() also?

**Comment by Treeston** [comment]
Try always licking your doors in the future, @Killyana.
