### ISSUE TITLE
Random voice talking to you in Shattrath

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19427]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
While you're in Shattrath there is an omnipotent Blood Elf voice that says things to you at random about every 30 seconds or so.

"Not very intelligent are you?"
"You waste my time."
and a few others

I don't know if this is supposed to be for a quest where you're berated by a blood elf but it's certainly not normal.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. b7329a460e58 2017-04-01 03:19:57 +0200 (3.3.5 branch) (Win64, Release, Static)

**TDB version:**
335.62

**Operating system:**
Windows 10 Server & Client

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by MrSmite** [comment]
Yes, very annoying. I just noticed this the other day and couldn't find anything about it online.

I don't remember this from retail but I thought in my case perhaps it was because I was only level 40 and you're not really supposed to be there at that low level. Either way, I wish it would stop. It's almost as annoying as the Draenei that laughs but at least you can get away from him. This stupid voice ruins the ambience of Shattrath.

**Comment by offl** [comment]
```sql
--
UPDATE `waypoint_scripts` SET `datalong2` = 2 WHERE `id` = 14 AND `command` = 16 AND `datalong` = 9739;
```

**Comment by jerbookins** [comment]
Beautiful

**Comment by jerbookins** [comment]
Reopened?

**Comment by DDuarte** [comment]
Issue is closed when the fix is added to the repository.
