### ISSUE TITLE
Core/Spell: Distance calculations in AoE spells

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#19505]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:** After https://github.com/TrinityCore/TrinityCore/pull/16290 it has become impossible to avoid some spell hit techniques like http://www.wowhead.com/spell=66770/ferocious-butt  and  http://www.wowhead.com/spell=70123/blistering-cold

The distance seems to be really huge and impossible to avoid getting hit.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/f42ff8c6ba0609c2f774440dd30981356c1ffd63

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
I noticed that your linked spells are used by http://www.wowhead.com/npc=34797/icehowl and http://www.wowhead.com/npc=36853/sindragosa (respectively). Could those spell effects be adapted for the creatures in the instance scripts, or is this something you have experienced in general, making it a general issue?

**Comment by Killyana** [comment]
It's a general issue, also the bump spell used by Yogg on the 2nd phase doesn't allow melee players to dps the boss
SPELL_KNOCK_AWAY = 64022,

**Comment by sirikfoll** [comment]
Wield guess, but couldn't the "misterious" bounding radius field be used in those spell calculations instead of the Combat Reach? Didn't test or looked into anything, just saw the big difference between them

BoundingRadius  | CombatReach | Npc
------------ | ------------- | -------------
4 | 14 | Icehowl
0.775 | 18.75 | Sindragosa
0.3 | 20 | Yogg-Saron

**Comment by Killyana** [comment]
I tested spells range for Sindragosa and Yogg-Saron using BoundingRadius instead of CombatReach  and it looks more logic, But as BoundingRadius is almost =0 don't know if it's correct.

**Comment by Adizbek** [comment]
Sindragosa casts spells bigger radius than described in dbc. In my opinion spell radius depends on boss size?

**Comment by chaodhib** [comment]
With my PR, the range of AoE has been modified: Now, they also take into account the combat reach (CR) of the caster. Therefore, if the caster has a huge CR, the range of the AoE will be high. This explains the issue with blistering cold. I'm surprised that there is an issue with ferocious butt (since it's not an AoE). Are you sure it's not another spell of this boss that's problematic?

Anyway I will propose a solution to this issue as soon as I can (I have been a little swamped lately). Before I can though, I need to first find relevant data on these spells. I got no luck so far with Sindragosa and Halion (Living Inferno). I need to see how far players would get hit by these spells in retail. Help is welcomed.

In the meantime, a temporary fix would be to cap the added range bonus given by caster combat reach to 10 yards.

Meaning, before, the formula is: `range = spell radius + caster CR + target CR`
In the temp fix, the formula would be: `range = spell radius + min(caster CR, 10.0f) + target CR`

PS: Some relevant discussion about the issue can also be found [HERE](https://github.com/TrinityCore/TrinityCore/commit/a1f2f30c145f6ad9c4baeffeff32618e71ff537c#commitcomment-21593313).

**Comment by ariel-** [comment]
Halion's Combustion (74630) and Consumption (74802) are also affected, damage range way exceeds the visual

**Comment by Demonid** [comment]
Seems like this also affects PvP Spells like Divine Storm, you can hit enemies from really far:

http://i.imgur.com/RijxPEJ.jpg

This issue is game breaking =/

**Comment by chaodhib** [comment]
I'm actively working on this. I will probably remove the added bonus radius given by the caster's combat reach. This may have been a mistake.

**Comment by chaodhib** [comment]
Done. https://github.com/TrinityCore/TrinityCore/commit/2ff76e828f7c757b5120aba41947a6d63e082e17 removes the bonus given by the caster's CR to the AoE radius until a better formula is found for that class of AoEs.
