### ISSUE TITLE
Map 0000_43_31.map is missing

### ISSUE THREAD

**Issue by HamAndRock** [TrinityCore/TrinityCore#19791]
**Description:**

When i start server with ./worldserver on Debian, its wont start because there is missing 0000_43_31.map. But that is not correct, because the file is uploaded correctly in maps folder.

**Current behaviour:**

Map file './maps/0000_43_31.map' does not exist!
Please place MAP-files (*.map) in the appropriate directory (./maps/), or correct the DataDir setting in your worldserver.conf file.

**Expected behaviour:**

Server should load.

**Steps to reproduce the problem:**

Started the server

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. cd7c4478ba0d 2017-05-23 17:06:49 +0200 (master branch) (Unix, Release, Static) (bnetserver)

**TDB version:**  7.2

**Operating system:** Debian

**Comment by Aokromes** [comment]
configuration problems belongs to forum. anyway re-check paths, if you still have issues use absolute paths instead relative.

**Comment by HamAndRock** [comment]
ok, do under stard, but why is not having problems with other maps + vmaps ?

**Comment by tkrokli** [comment]
If your game client & source is up to date and your source unchanged, mapextractor will extract that file.

![image](https://cloud.githubusercontent.com/assets/4903600/26382795/2bd5ee1c-402f-11e7-8e1a-87b45e68f3c3.png)

Your problem is not an issue in the source code. Use [**TC Forum**](https://community.trinitycore.org/) or [#trinity on IRC](https://trinitycore.atlassian.net/wiki/display/tc/IRC) for questions about it.

**Comment by HamAndRock** [comment]
Problem was solved by running ./worldserver with root priviliges.

**Comment by whitelionV** [comment]
I can reproduce this behavior when trying to run `./server/bin/worldserver` as a relative path. Since from that location `../data/maps` does not exist, the file can't be found.

Just use an absolute route (`~/server/bin/worldserver`) or `cd` into the `bin` directory and run `./worldserver`

**Comment by Shauren** [comment]
Not a bug, l2 bash.
