### ISSUE TITLE
Core/Vehicle: Combat called on spell cast and not on hit

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#19920]
**Description:** If a vehicle casts a spell using a missile, the combat will start when the spell is cast and not when it hits the NPC.

**Expected behaviour:** The combat should start on spell hit and not when it is cast.

**Steps to reproduce the problem:**

1. ` .go c 207537`
2. `.mod phase 256`
3. ` .cast 63215`
4. Use ability number 2 in any mob around while you are staying in max range.
5. Notice that the combat starts when you click the ability and not when the spell hits the target.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 9fc35785307e

**Comment by Shauren** [comment]
Is this a spell that you need to have a target selected? If yes then its not a bug - on retail you enter combat when you launch the spell (after cast time, if any), not when it hits the target. Aggro (chase, melee) happens after it hits

**Comment by Killyana** [comment]
Aggro (chase, melee) happens also when the spell is casted.

**Comment by Warpten** [comment]
wat no

**Comment by Killyana** [comment]
Test it on 3.3.5, The issue doesn't happen on master.

**Comment by Shauren** [comment]
master does not even have that fix which puts you in combat when spell is launched

**Comment by Killyana** [comment]
Tested, and npcs still aggro the vehicle upon the spell casted.

**Comment by tkrokli** [comment]
TrinityCore rev. a217c0be922f 2018-01-31 00:59:14 -0200 (3.3.5 branch) (Win64, Release, Static)
I didn't think much of it at the time, but I have been able to reproduce this phenomenon quite often, only using my own orc hunter character while leveling up as well as grinding reputation in Ghostlands.

It is easier to notice it happening when the hostile mob has got a pet (beastmaster or warlock pet) because the pet will aggro and start attacking almost at the same fraction of a second as the spell is cast, before the ranged spell has landed on the target mob. Although it can also be reproduced when attacking mobs (beasts sometimes react more visibly) when attacking from max spell range, so you get time to see the spell missile fly and trigger aggro before it lands.

**Comment by Langerz82** [comment]
I will have to look into this more ty for feedback.

**Comment by Langerz82** [comment]
Ok, think I have a patch you can test. Bear in mind this is only a rough approximation and CalcSpellHitTime needs to extrapolate it's proper values from the SpellMissile.dbc most likely.

See Patch:
https://gist.github.com/Langerz82/6b28adae41dce87d8b1809407005cbaa

**Comment by Killyana** [comment]
Fixed by https://github.com/TrinityCore/TrinityCore/commit/a891eb364e941a5146fba4af16e1ecf65cdd9239 probably, or previous commit
