### ISSUE TITLE
NPC not add next quest

### ISSUE THREAD

**Issue by mazdafil** [TrinityCore/TrinityCore#19938]
**Description:** After complete quest 9836 NPC 15608 not add next quest 9837

**Current behaviour:**
After complete quest 9836 NPC 15608 not add next quest 9837

**Expected behaviour:**

After complete quest 9836 NPC 15608 most add next quest 9837

**Steps to reproduce the problem:**

1.NPC 18166 add quest 9836
2. Go to The Black Morass.
3. Close all time rift and kill all bosses/
4 Complete and reward quest 9836 npc 15608
5 NPC 15608 not add quest 9837

**Branch(es):**

3.3.5
**TC rev. hash/commit:** 
TC>TC>TrinityCore rev. dcc43de72fb5+ 2017-06-22 02:37:09 -0300 (3.3.5 branch) (Unix, Release, Static) (worldserver-daemon) ready...

**TDB version:**  TDB 335.63

**Operating system:** Ubuntu 14.04

Solution 
UPDATE quest_template_addon SET NextQuestID=0 WHERE ID=10737

**Comment by dr-j** [comment]
There are two versions of 'The Masters Touch'

Return to Khadjar 9837 had The Masters Touch 9836 has previous quest but there was second version of the Masters Touch 10737 which had return to khadjar set as next quest and since these two conditions contradicted each other return to khadjar was never offered

~~~sql
UPDATE `quest_template_addon` SET `NextQuestID`=0 WHERE `ID`=10737;

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/commit/9a03ba3c1f3ee1174510ca36b3c469987a76b51d
