### ISSUE TITLE
[Master] Error in loot "Already looted" again.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19961]
**Description:**

Again the error appears when loot some objects.

**Current behaviour:**

In the quest orc starting zone the quest [Sarkoth] id 25120 the objet [Sarkoth's Mangled Claw] id 4905 show the error "Already looted"

**Expected behaviour:**

Loot the object without errors.

**Steps to reproduce the problem:**

1. Take quest 25120 in the orc starting zone
2. Kill Sarkoth
3. Try to loot

**Branch(es):**

Master

**TC rev. hash/commit:** 

5734643cecbadfffb7ee1b66c9665d57108923f6

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

**Comment by tkrokli** [comment]
Please post full links to the quests/NPCs/items instead of just numbers, to make the troubleshooting job easier for the devs, but also to make it easier for us others to read your post and look at the related information. (I have been told that I should stop editing other users' posts, so please edit it yourself and add the missing information.)

**Comment by tkrokli** [comment]
TrinityCore rev. 5734643cecba 2017-06-26 00:31:48 +0200 (master branch) (Win64, Release, Static)
Using World DB: TDB 720.00 (using updates up to and including `2017_06_25_00_world.sql`)

Confirmed. Unable to loot quest item 4905 (http://www.wowhead.com/item=4905/sarkoths-mangled-claw).
- http://www.wowhead.com/quest=25129/sarkoth
- http://www.wowhead.com/npc=3281/sarkoth
- http://www.wowhead.com/item=4905/sarkoths-mangled-claw

You receive the on-screen error message (in bold red text): **`Already looted(1327950336/-25364272)`**

DB entries look just fine, so this could be a similar error to **Core/Loot: Already Looted #19812** in Sunstrider Isle (blood elf starter area) with the [Tainted Arcane Sliver](http://www.wowhead.com/item=20483/tainted-arcane-sliver) as a quest starter item, although this item is not a quest starter item, just a quest item.
Screenshot of the error message & situation (tested 3 times in a row and in 2 extra consecutive logins):

![wowscrnshot_062617_211439](https://user-images.githubusercontent.com/4903600/27556689-e0fa0e4e-5ab6-11e7-9815-4396b5d9f0ba.jpg)

As you probably can notice in the chat log, it is possible to loot any other items from Sarkoth (I have not tested [Scorpid Worker Tail](http://www.wowhead.com/item=4862/scorpid-worker-tail) specifically in addition to [Sarkoth's Mangled Claw](http://www.wowhead.com/item=4905/sarkoths-mangled-claw), though). [Scorpid Worker](http://www.wowhead.com/npc=3124/scorpid-worker) NPCs drop [Scorpid Worker Tail](http://www.wowhead.com/item=4862/scorpid-worker-tail) as expected and intended, so that item should not pose an issue AFAIK.

**Comment by HannibalRoG** [comment]
@tkrokli was very well documented here https://github.com/TrinityCore/TrinityCore/issues/19812 but your comment is valid ;)
