### ISSUE TITLE
[master] Food items do not restore any hp

### ISSUE THREAD

**Issue by kr0n4ik** [TrinityCore/TrinityCore#19987]
**Description:**

Does not restore health when used
http://www.wowhead.com/item=27854/smoked-talbuk-venison

**Current behaviour:**

**Expected behaviour:**

**Steps to reproduce the problem:**

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. 77d20127cf5b 2017-07-01 00:02:53 +0200 (master branch) (Unix, Release, Static) (worldserver-daemon)

**TDB version:**  TDB_full_720.00_2017_04_18

**Operating system:** win64

**Comment by tkrokli** [comment]
How many other food items have you tested? Is this the only item where this issue happens?

**Comment by kr0n4ik** [comment]
I checked on one. Now I looked and others in the handwrap do not restore the hp

**Comment by tkrokli** [comment]
OK, so by looking through your testing, would you be able to say if any food items at all can restore HP or if this feature does not work at all?

**Comment by kr0n4ik** [comment]
Any food does not restore life

**Comment by Faq** [comment]
What about drinks for mana restore?

**Comment by tkrokli** [comment]
Good point. Anyone got time to check those too? 🍹 🍺 🍸

**Comment by HannibalRoG** [comment]
I tested with appropiate level to see regeneration and work as intended in food:

Freshly baked bread [4541] level 5
Moist Cornbread [4542] level 15
Bristle Whisker catfish [4593] level 15
Clefthoof ribs [29451] level 65
Smoked Talbuk Venison [27854] level 55
Roasted quail [8952] level 45

Drink not tested because the mana fill more quickly than it expend, its a bug.

Master 7e643eaa115e4eed79e312c0b8321bad28c5b507

**Comment by HannibalRoG** [comment]
I fucked up, i missunderstand the number, its not working at all with the list above, sorry.
