### ISSUE TITLE
[3.3.5] The Tome of Valor

### ISSUE THREAD

**Issue by GnaXi** [TrinityCore/TrinityCore#20053]
**Description:**

Defias Raiders not behaving correctly

**Current behaviour:**

When the quest is picked up at Daphne Stilwell she runs to the house and picks up her gun.
When she walks outside, 3 Defias Raiders spawn in the distance, but they just stand there for about 30 seconds, then they despawn.
Quest cannot be completed after this.

**Expected behaviour:**

The Defias Raiders are supposed to attack you and Daphne Stilwell

**Steps to reproduce the problem:**

1. Pick up the The Tome of Valor quest (https://wotlk.evowow.com/?quest=1651)
2. Wait for Daphne Stilwell to pick up her gun
3. Wait for the Defias Raiders to spawn and despawn

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 348b02155bca 2017-07-16 18:26:05 +0200 (3.3.5 branch) (Unix, Release, Dynamic)

**TDB version:**  335.63

**Operating system:** Debian 9

**Comment by tkrokli** [comment]
I wonder if this could have something to do with aggro range when SAI is involved. As we have already seen the last month or so, scripted SAI creatures display a "string ball" effect during waypoint movement or in aggro range of non-scripted hostile NPC creatures.

I may be wrong, of course. This particular issue could just as well be caused by a broken SAI script (for example if the Defias Raiders despawn because the script AI finds no target for the attackers, treating the situation as a "player missing" event).

**Comment by Tauriella** [comment]
The same issue have the Quest "The Escape"
http://www.wowhead.com/quest=863/the-escape

Just before you finish the quest disappears the Shredder

**Comment by tkrokli** [comment]
There is a very similar issue with the following 4 quests in Kirin'Var Village, Netherstorm, Outland:
- http://www.wowhead.com/quest=10305/abjurist-belmara
- http://www.wowhead.com/quest=10306/conjurer-luminrath
- http://www.wowhead.com/quest=10307/cohlien-frostweaver
- http://www.wowhead.com/quest=10182/battle-mage-dathric

Each quest requires that you take the quest item to a specific location (Bookshelf, Dresser, Footlocker or weapon rack), use the item (the item despawns on use) to spawn the original owner of that item.

**Current behaviour:**
The NPC spawns as hostile, is untargetable, stands still for a minute, then despawns. None of the 4 quests can be completed.

**Expected behaviour:**
The NPC should spawn with a neutral faction to the player, turn and walk to their gameobject (Bookshelf, Dresser, Footlocker or weapon rack), say some text about their own item, then despawn at the same time as quest completes (kill credit or quest state change).

**Steps to reproduce the problem:**
1. Use a level 68-70 character, go to Kirin'Var Village in Netherstorm.
2. .additem
    - http://www.wowhead.com/item=28336/belmaras-tome
    - http://www.wowhead.com/item=28352/luminraths-mantle
    - http://www.wowhead.com/item=28353/cohliens-cap
    - http://www.wowhead.com/item=28351/dathrics-blade
3. Right-click the quest items and accept the quests.
4. Take the quest items to their respective target gameobjects (Bookshelf, Dresser, Footlocker or weapon rack)
5. Right-click the item (which despawns) on their respective locations and see that the NPC spawns, but nothing more happens.

TrinityCore rev. e2565c2597a7 2017-08-11 23:06:37 -0300 (3.3.5 branch) (Win64, Release, Static)
Using configuration file C:/TrinityCore/core/335/worldserver.conf.
Using SSL version: OpenSSL 1.0.2k  26 Jan 2017 (library: OpenSSL 1.0.2k  26 Jan 2017)
Using Boost version: 1.63.0
Using World DB: TDB 335.63 + updates up to and including `2017_08_09_00_world_335.sql`

**Comment by Killyana** [comment]
Cannot reproduce in rev. 47add89a11b3
Also I tested all quests in this issue, and all works fine.

**Comment by Tauriella** [comment]
@Killyana You're right it works again :+1:
