### ISSUE TITLE
Flying mount and shallow water flying exploit

### ISSUE THREAD

**Issue by Foereaper** [TrinityCore/TrinityCore#20079]
**Description:**

If you use a flying mount while standing in shallow water (Water not deep enough to make the character swim), and jump at the exact correct moment when the cast ends, your flying mount will be removed and your character will fly around, able to cast spells and the likes.

**Current behaviour:**

As stated above, this causes characters to fly around and they are able to attack and cast spells like normal.

**Expected behaviour:**

The cast should either complete correctly, allowing the character to mount and fly, or stop the cast which seems to be the current intended behavior.

**Steps to reproduce the problem:**

1. Go to an area where you are allowed to fly (Northrend, Outlands) and find a suitable location with shallow water. ( The Geyser Fields in Borean Tundra works wonders for this.)
2. While standing in the water, summon any flying mount.
3. At the end of the cast bar, the exact moment your character is supposed to mount, jump.
4. This will cause your character to fly, but retains the ability to cast spells and attack.

**Branch(es):** Tested on 3.3.5

**TC rev. hash/commit:** 21b03e7

**TDB version:** 335.63

**Operating system:** Windows

Attached is a video link to the exploit in action: https://www.youtube.com/watch?v=3n3_cRvPbOE

**Comment by Pharonax** [comment]
Can reproduce this.
http://imgur.com/a/4OgAQ

**Comment by Treeston** [comment]
Reproduced. Investigating...

**Comment by Treeston** [comment]
Issue identified. `Player::SetCanFly` sends `SMSG_MOVE_(UN)SET_CAN_FLY`, but only if the player's last movement info had `MOVEMENTFLAG_CAN_FLY` set. Since the shallow water instantly cancels the mount aura, the last movement info didn't yet have this flag, so `SMSG_MOVE_UNSET_CAN_FLY` is never sent.

Thus, while the server (correctly) doesn't think the player is capable of flying, the client thinks they can - since it never got a `SMSG_MOVE_UNSET_CAN_FLY` packet. We're effectively making the player inadvertently fly hack.
