### ISSUE TITLE
Master not compiling

### ISSUE THREAD

**Issue by Ferelith** [TrinityCore/TrinityCore#20081]
**Description:**

Master doesn't compile due to rc.exe not being found. (TRK005 & LNK1158) error codes. 

**Current behaviour:**

TRK005 & LNK1158 error are displaying in Visual Studio error log. (see screenshot)

**Expected behaviour:**

Master should compile and successfully build.

**Steps to reproduce the problem:**

1. Get core version fc8f0fbc2d6f
2.  Use git extension to pull recent updates
3. Compile

**Branch(es):**

Master

**TC rev. hash/commit:** 

TrinityCore rev. fc8f0fbc2d6f 2017-07-08 20:31:51 +0200 (master branch) (Win64, Release, Static)

CHANGEME Copy the first line of the `worldserver`, `authserver` or `bnetserver` startup.
For example: TrinityCore rev. 0000000000 2000-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (bnetserver)

**TDB version:**  TDB 720

**Operating system:** Windows 10

**Comment by Ferelith** [comment]
![errors_on_compile](https://user-images.githubusercontent.com/25698730/28647750-f1aa463e-7260-11e7-95a2-51db7401725d.PNG)

**Comment by tkrokli** [comment]
Your source code is too old (2017-07-08 20:31 CEST (18 days old as of this comment) and any issues related to that specific commit (https://github.com/TrinityCore/TrinityCore/commit/fc8f0fbc2d6f903f7e742dbfb0d5315470f5414d) has been fixed in later commits. Please update your source (like you stated yourself in your step 2 of **Steps to reproduce the problem:** `"2. Use git extension to pull recent updates` , which would solve your reported issue.

A similar issue occurred in master branch yesterday in commit https://github.com/TrinityCore/TrinityCore/commit/0cd5179726f91cc163910dd0806d622fe86d9a8c , but was fixed in the follow-up commit https://github.com/TrinityCore/TrinityCore/commit/b85d46138bf6cd0fd50a0f8060f1512002ced731  (at least as far as release build goes, specifically for MSVC), even if travis-ci complains in current builds about a warning which is treated as an error (for troubleshooting purposes).

TrinityCore will not support outdated source like the one you have linked as long as the issue has been fixed in later builds.

**Comment by tkrokli** [comment]
By the way, neither [Travis (travis-ci)](https://travis-ci.org/TrinityCore/TrinityCore/builds/251539716?utm_source=github_status&utm_medium=notification)  nor [AppVeyor (VS2015)](https://ci.appveyor.com/project/DDuarte/trinitycore/build/1.0.5769) found any issues in the source code as of the commit you referred to (https://github.com/TrinityCore/TrinityCore/commit/fc8f0fbc2d6f903f7e742dbfb0d5315470f5414d) so I wonder if you are not using the correct version of Visual Studio to produce your issue. Make sure you are using the recommended versions MS Visual Studio (Community) ≥ 14 (2015 update 3) or any of the VS2017 versions to compile the TC source code.
- Travis (travis-ci): https://travis-ci.org/TrinityCore/TrinityCore/builds/251539716?utm_source=github_status&utm_medium=notification
- AppVeyor (using VS2015): https://ci.appveyor.com/project/DDuarte/trinitycore/build/1.0.5769

Unfortunately I can not tell which version you are using from the screenshot alone, so please state your Visual Studio version (including update numbers) if you still get this kind of issue. I am fairly certain you won't get this issue if you use the recommended versions of Visual Studio, following the TrinityCore wiki guide: https://trinitycore.atlassian.net/wiki/display/tc/Windows+Requirements

**Comment by Ferelith** [comment]
Thanks for the explanation. I've checked the version of Visual Studio and it is up to-date. I've used the compiler previously and it worked fine, most likely as you stated, it's the version of the commit so I'll have to pull a fresh one. Thanks for the input.
