### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by neltharionorg** [TrinityCore/TrinityCore#20169]
**Description:** Compile Error

CHANGEME Description of the problem or issue here.

**Current behaviour:** Cant Compile

**Branch(es):** master

**TC rev. hash/commit:**b8479333c25c92675909c2077e8e3bdd72d4d58a

**TDB version:**  TDB 720.00

**Operating system:** Debian 9

**Comment by tkrokli** [comment]
Please post a better description of your problem if there is something wrong with the source.
" Compile Error / Cant Compile " does not tell us exactly what your problem is.

The TC source compiles without errors on Linux & Windows:
- https://travis-ci.org/TrinityCore/TrinityCore/builds/266611297
- https://ci.appveyor.com/project/DDuarte/trinitycore/branch/master
- https://travis-ci.org/TrinityCore/TrinityCore/builds/266649159
- https://ci.appveyor.com/project/DDuarte/trinitycore/branch/3.3.5

Your problem is therefore a problem with your configuration and not a general issue.
Ask in IRC or read the Forum pages if you can not get your source compiled:
- https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130200/IRC
- https://community.trinitycore.org/forum/5-help-and-support/
- https://community.trinitycore.org/topic/120-compile-or-cmake-problems/
