### ISSUE TITLE
[Crash] - SpellEvent::~SpellEvent

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#20172]
**Description:**
I found in server logs this:
```
Server_2017-07-15_17-02-27.log:84497:2017-07-16_05:43:08 ~SpellEvent: Creature 11642 tried to delete non-deletable spell 63886. Was not deleted, causes memory leak.
Server_2017-07-25_02-34-45.log:7308:2017-07-25_03:29:00 ~SpellEvent: Creature 3388 tried to delete non-deletable spell 63886. Was not deleted, causes memory leak.
Server_2017-07-26_00-30-47.log:373799:2017-07-29_01:16:17 ~SpellEvent: Creature 12235 tried to delete non-deletable spell 63886. Was not deleted, causes memory leak.
Server_2017-08-13_03-05-25.log:29822:2017-08-13_07:16:44 ~SpellEvent: Creature 10819 tried to delete non-deletable spell 63886. Was not deleted, causes memory leak.
Server_2017-08-15_05-15-54.log:1301:2017-08-15_05:30:39 ~SpellEvent: Creature 2120 tried to delete non-deletable spell 63886. Was not deleted, causes memory leak.
```
spell ID - 63886 Death Ray Damage Visual (Yogg Saron - Ulduar)

Crashlog: https://gist.github.com/Jildor/f9f1823b12a93e1a4487881af6b4e37d

I think is related with this issue: https://github.com/TrinityCore/TrinityCore/issues/16675

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 445c5a00e8

**TDB version:**  TDB335.63

**Operating system:** Debian

**Comment by jackpoz** [comment]
Btw as unrelated note, having loggers with LOG_LEVEL_TRACE level causes the log system to check more often if messages should be logged. This might not be what you want in a production environment and for performance reasons you might want to enable logs only with LOG_LEVEL_WARN or LOG_LEVEL_ERROR levels.

You can find the list of levels at https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/common/Logging/LogCommon.h#L24 and some details in the code about the logic in place at https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/common/Logging/Log.cpp#L343 .

Thread 34 in your crashlog is inside Log::ShouldLog() function in WorldSocket::ReadHandler() and you want that function to be blazing fast (instead of wasting time checking if the opcode received should be logged)

**Comment by Laintime** [comment]
confirm https://gist.github.com/Laintime/82eed8cd2c8713734d206b6cf3858ba8

**Comment by n4ndo** [comment]
Confirmed

- https://pastebin.com/LaNwA75L
- https://pastebin.com/CLrU2upA

**Comment by jackpoz** [comment]
does it always happen with spell id 63886 only ?

**Comment by Jildor** [comment]
I think yes

**Comment by jackpoz** [comment]
I wonder if it's because the AuraScript::OnRemove() hook casts a spell that schedules an event when the creature is being deleted from world

**Comment by Strazhnik** [comment]
Confirmed.
