### ISSUE TITLE
Core/Script: The Key of Warlord Zol'Maz (OPEN_DOOR)

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#20246]
**Description:** When you use the item http://www.wowhead.com/item=39314/tiki-dervish-ceremony it will spawn a guardian (28927) that use a set data action on creature (28902).

The problem is the first time you use the item nothing will happen, the second time the script will be triggered.

Before the dynamic spawns only the first time you use the item after a reboot will do nothing,
But after the dynamic spawns for every new respawn of (28902) the item must be used twice to trigger the script.
```sql
SELECT * FROM smart_scripts WHERE entryorguid IN (28927,28902);
```
**Current behaviour:** Creature (28902) must receive twice the DATA set event before triggering the script.

**Expected behaviour:** Creature (28902) must receive the DATA set event  only once to trigger the script.

**Steps to reproduce the problem:**

1. `.go c 115830`
2. `.add 39314`
3. Use the item ( first time)
4. Notice nothing happen
5. `.add 39314`
6. Use the item ( second time)
7. Notice the script is triggered
8. GM on
9. `.add 39314` and use the item again
10. Notice the script is triggered as the npc is the already get a data set event
11. `.die` and `.resp` (28902)
12. `.add 39314` and use the item again
13. Notice the script is not triggered as the new copy of the NPC doesn't get a data set event before.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. a1a12ec755e

**Comment by jerbookins** [comment]
1f9f59b4b3b9

Still broken.

I can confirm that the script is not triggered fully on the first use of [Tiki Dervish Ceremony](http://www.wowhead.com/item=39314/tiki-dervish-ceremony). The NPC follower is spawned, and the sound of the gate opening is made but Warlord Zol'Maz does not agro.

On the second use of a Tiki Dervish Ceremony, a new NPC follower is spawned (killing the original), the sound of the gate opening is played once more, and this time Warlord Zol'Maz is agroed but he glitches through the wall because the gate is still closed.

**Comment by Langerz82** [comment]
Wheres the Script to the spell: https://www.wowhead.com/spell=52669/tiki-dervish-ceremony
Located in code/db?

**Comment by Killyana** [comment]
``` sql
SELECT * FROM `event_scripts` WHERE `id`=18940;

**Comment by Killyana** [comment]
SAI fixed, the remaining issue is the gate doesn't open, it's handled by `event_scripts` `id`=18940 (11 OPEN_DOOR)
When the item is used you will see the grid move a little bit, but it didn't open.
