### ISSUE TITLE
[3.3.5] Taming Rod

### ISSUE THREAD

**Issue by ogeraisi** [TrinityCore/TrinityCore#20323]
**Description:**

Dismissing a pet obtained by using quest item Taming Rod for Taming the Beast hunter quest will not stop the creature from following the player.

**Current behaviour:**

The creature continues to follow the hunter after dismissing it when it was obtained using the quest item.

**Expected behaviour:**

The creature should stop following the player.

**Steps to reproduce the problem:**

1. Get quest Taming the beast (hunter quest, level 10).
2. Use Taming Rod item to tame a creature.
3. Set the creature to follow (by default it stays still which might be another bug).
4. Dismiss the creature before or after finishing the quest.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 4505a4a30d8f 2017-09-13 18:29:48 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows 10 Professional x64

**Comment by Killyana** [comment]
I noticed that with every charmed npc, it will keep following the player even once the charm is broken or fades.

**Comment by tkrokli** [comment]
That is a bit weird, I never noticed that issue. I usually did those quests using an orc hunter for a long time and each time I abandoned/dismissed the pet, it became aggressive and started attacking me, unless I left it too far away with the stay command. a year or so back, I also experienced that some tamed temp pets would start attacking from really far away, but I think that issue was fixed long ago. Maybe it could be caused by me not setting the pet to follow me, because I mostly focused on completing the whole hunter level 10 quest line to get the last pet spells from the trainer at the end. I will have to test this again on current source to be able to confirm it. Thank you for the Steps to reproduce the problem.

**Comment by Solzz** [comment]
Also from what I've seen if you use taming rod a neutral mob such as a boar at Razorhill it doesn't attack other mobs, If you tame a hostile mob it works as intended.

**Comment by tkrokli** [comment]
Interesting. I will test that too as soon as my source is updated and compiled. I might take the trouble to test other races too, but I won't be done testing until some time this coming weekend.

**Comment by Killyana** [comment]
Cannot reproduce on rev. 71188062314e
