### ISSUE TITLE
[3.3.5] Minor issue with combat

### ISSUE THREAD

**Issue by ArcaneFox** [TrinityCore/TrinityCore#20500]
**Description:**
Hostile NPCs will target you while you are in Ghost Form.

**Expected behaviour:**
Hostile NPCs won't target you while you are in Ghost Form.

**Steps to reproduce the problem:**

1. Create a level 15 human
2. Go to Moonbrook
3. Die in combat
4. Go back to your corpse
5. Every NPC you have fought will target you while you are in Ghost Form

**Branch(es):** 3.3.5

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/035993d4cc618532b926df21abd816b593f2bc26

**TDB version:**  TDB 335.63 + updates

**Operating system:** Windows 10 64-bit

**Comment by tkrokli** [comment]
TrinityCore rev. 035993d4cc61 2017-09-30 17:24:28 +0200 (3.3.5 branch) (Win64, Release, Static)

Unable to confirm this. Just tested with a level 16 human female warrior, using quest greens (armor, weapon), but all the attacking mobs behaved as expected, i.e. returning (running) to home position upon player death. Ran back to the corpse, but no reaction from the mobs until I resurrected my player character. Tested several times, just to be sure, also tested if attacking several of them or none of them would make a difference, but nothing unexpected happened.

I even tested lowering that character's level down to 15 in case there could be anything weird at that level. Still no luck in reproducing your issue. Are you 100% sure you have tested with a clean core & DB ? Could it have anything to do with a particular class, like warlock or mage?

If your character is on a GM account, please test if your issue is there also after using the GM command `.unaura all` (either on yourself or from a GM character).

**Comment by ArcaneFox** [comment]
My client is enGB 3.3.5a 12340

![1](https://user-images.githubusercontent.com/25306170/31068048-6e6e1fe0-a756-11e7-9708-93dffeca2c67.jpg)
![2](https://user-images.githubusercontent.com/25306170/31068047-6e13414c-a756-11e7-8a68-b392a9b22b66.jpg)

**Comment by ArcaneFox** [comment]
.unaura all didn't help

The good news is only the mages are targeting me before and after the resurrect.

**Comment by Killyana** [comment]
It's just the focus is not cleared: https://github.com/TrinityCore/TrinityCore/issues/18373
