### ISSUE TITLE
DB/Creature: Keeper Witherleaf

### ISSUE THREAD

**Issue by Wyreth** [TrinityCore/TrinityCore#20514]
**Description:**

Add missing spell cast and flee-at-low-health behaviour for [Keeper Witherleaf](http://www.wowhead.com/npc=24638).

**Branch(es):** both.

**TC rev. hash/commit:** 1af6df41a5e382c1068a04d496eb3d316873def6

**TDB version:** 335.63

**Suggested fix**:
```sql
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=24638;
DELETE FROM `smart_scripts` WHERE `entryorguid`=24638 AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(24638, 0, 0, 0, 9, 0, 100, 0, 0, 8, 2800, 2800, 11, 43619, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, "Keeper Witherleaf - On Target Within 0-8 Yards - Cast 'Wrath'"),
(24638, 0, 1, 0, 2, 0, 100, 1, 0, 15, 0, 0, 25, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Keeper Witherleaf - Between 0-15% Health - Run In Fear (No Repeat)");


```

**Comment by Killyana** [comment]
Better to use IC-CMC in this case.

**Comment by Wyreth** [comment]
I thought the same, but he only casts it if the target is close to him. [Check here](https://youtu.be/MjqrspqQ3MY?t=40).

**Comment by Killyana** [comment]
Just the first cast is delayed.

**Comment by Killyana** [comment]
Test the script, the npc will run towards the player before start casting like in the video.

**Comment by Wyreth** [comment]
Right, didn't think of that :D thanks!

**Comment by Teppic1** [comment]
Slightly off topic question, is there a newer version of SAI utils that include these newer actions like run in fear as you've used here?

**Comment by Wyreth** [comment]
I'm not sure. @Killyana or @tkrokli maybe knows about that :P

**Comment by Teppic1** [comment]
Ah ok I assumed you were using one to generate the SQL :)

**Comment by Wyreth** [comment]
Everything by hand :)

It's a bit troublesome at first, but after a while you start remembering the exact number of fields in tables like conditions and smart_scripts, then it is actually faster compared to using tools :P

**Comment by Killyana** [comment]
I don't know if SAI editors are outdated or not https://github.com/jasperrietrae/SAI-Editor http://keira2.altervista.org/Keira2-dev/#/sai
You must always check: http://collab.kpsn.org/display/tc/smart_scripts

**Comment by tkrokli** [comment]
@Teppic1 : Not sure what you mean by "a newer version of SAI utils", because I have only used Keira2 Database Editor by Helias and ShinDarth. There used to be an updated version on gnaxi.net, but that site has been changed during the last year to gnaxi.io and with a completely different layout, so I could not locate Keira2 there now. I have not been very active in the #trinity channel on irc.rizon.net lately, so I have no idea whether Gnaxi has been available online for questions regarding an updated version of Keira2 based on current TDBs. Like Wyreth said, I mostly write stuff by hand in Notepad++ and check existing TDB content to verify most of the details. If you are comfortable with setting up Keira2 yourself and base it on an updated TDB, it can be a useful tool to view & edit existing data. Killyana's suggestion is also good and to the point.

Please use either the TC forums or the #trinity help channel on irc.rizon.net for questions not belonging to the issue tracker and the issue discussed on the page. (This is **not** a forum.)
