### ISSUE TITLE
Core/SAI: SMART_EVENT_FRIENDLY_HEALTH_PCT is broken

### ISSUE THREAD

**Issue by Teppic1** [TrinityCore/TrinityCore#20536]
**Description:**

The event is supposed to trigger an action when a friendly unit matches the health percentage set.

**Current behaviour:**

The event code directly depends on the target, which makes no sense because only the action is supposed to use the target.

The correct way to implement this is via TARGET_ACTION_INVOKER, but since the event code depends on the target that won't work.

As a result, all SAI that uses this event with an action that uses a target is currently broken -- the event's action (likely a heal) will reprocess the target list regardless of health.

**Branch(es):**

both

**TC rev. hash/commit:** 

TrinityCore rev. 3994286+ 2017-09-28 19:33:39 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:** Windows 10

**Steps to Reproduce**

1. Use a cast action with a heal on an NPC
2. Use a target of nearest friendly
3. NPC will cast when any nearby friendly loses health, but will always just cast on the nearest friendly

Alternatively:

1. Use a cast action with a heal on an NPC
2. Use TARGET_ACTION_INVOKER, as you would normally
3. Nothing will ever happen

**Comment by dr-j** [comment]
Well I have bever used this action to make a npc cast a healing spell as I always used Smart event friendly health deficit if casting a healing spell with a target other than self and that works with target 7 invoker or when a friendly unit goes below the deficit event is triggered with that friendly target with the health deficit as invoker

**Comment by Teppic1** [comment]
Yeah. The regular one (not _PCT) works fine as it calculates a nearby friendly and then passes it to the action, so you can use ACTION_INVOKER. The trouble is you need to know the exact health value.

**Comment by illfated** [comment]
Oh well. This issue is now in search of a new PR to deal with the outstanding issues listed in the opening comment of PR #23377.

**Comment by offl** [comment]
Almost opened new issue :/
>`SMART_EVENT_FRIENDLY_HEALTH_PCT` must work both for creature(healer) and its friends. Because the healing spells which are used in this event must be used on creature(healer) and its nearby allies.
We can't use two separate events(one for healer and one for allies) because it's simply incorrect to hold two similar events with similar spells.
And it should work with new target `SMART_TARGET_CREATURE_RANGE_OR_SELF` (alalogue of `SMART_TARGET_CREATURE_RANGE` but without the `creature entry` param, it's not needed here) or with target `SMART_TARGET_ACTION_INVOKER`.
>
>SMART_EVENT_FRIENDLY_HEALTH will be unused one day so it shouldn't be updated.

**Comment by offl** [comment]
> SMART_EVENT_FRIENDLY_HEALTH will be unused one day so it shouldn't be updated.

This thing is evil, difficult to work with and logically incorrect. It uses health value so if the creature level is changed, the health value will be too changed. And creature will cast healing spell at 47% HP instead of 50%.
As the result healer creature will cast one spell on allies at 43, 46, 49 or 40% health instead of 50%.

**Comment by illfated** [comment]
Thank you for following up on this, it truly looks like a messy problem.

**Comment by offl** [comment]
I wasn't prepared for this
```sql
(@ID,0,4,0,74,0,100,2,0,50,13200,19300,11,25058,0,0,0,0,0,9,0,0,15,0,0,0,0,"Cabal Acolyte - On Friendly Between 0-50% Health - Cast 'Renew' (Normal Dungeon)"),
```
Spider gains 0 Health from Cabal Acolyte's Renew.(978 Overhealed) (Critical)

**Comment by Teppic1** [comment]
Yeah, the code will always just heal the nearest friendly regardless of its health.

**Comment by offl** [comment]
So https://github.com/TrinityCore/TrinityCore/issues/20536#issuecomment-640732097 must be implemented
And I'll make SMART_EVENT_FRIENDLY_HEALTH completely unused, I already converted some of them

I guess we don't need a new target type here, everything can be done with SMART_TARGET_ACTION_INVOKER. The event just must include healer too, maybe with param5 (self too 0/1, self too by default) in case this event should be used only for friends(I doubt since the event now is used only to cast healing spells which should be used on healer too)

And the event must support SMART_TARGET_ACTION_INVOKER of course

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/cbed1039c47f0e3487cea555bb8552a4e6445f5a
