### ISSUE TITLE
[Crash] - InstanceSaveManager::_ResetSave

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#20592]
**Description:**
seems similar, but, it's not the same crash (If it is necessary to separate in two issues, say it)
Crashlog1: https://gist.github.com/Jildor/38fd99b38729989e10234690a6039229
Crashlog2: https://gist.github.com/Jildor/2001141952bc5481892d70eaf614cf37

in the crashlog appear:
difficulty = REGULAR_DIFFICULTY, mapid = 632 (The Forge of Souls)
difficulty = DUNGEON_DIFFICULTY_HEROIC, mapid = 576 (The Nexus)
then, only happens in dungeons??

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 445c5a00e8

**TDB version:**  TDB335.63

**Operating system:** Debian

**Comment by tkrokli** [comment]
Even though the crashes are triggered by different events (`crash2_InstanceSaveManager::_ResetSave.log` on mapid=632 was triggered by `ASSERT` and `crash1_InstanceSaveManager::_ResetSave.log` on mapid=576 was triggered by something else), both relate to `InstanceSaveManager::instance()::instance` in some way. I will add the instance label just in case, but we need feedback from some of the devs who know more about crashes like these ones to be sure if they both are caused by the same kind of issue.

**Comment by Jildor** [comment]
I put another crashlog: https://gist.github.com/Jildor/9e01dd572ce74396649d2f8919c596bd
this time: difficulty = DUNGEON_DIFFICULTY_HEROIC, mapid = 604 (Gundrak)

**Comment by Jildor** [comment]
I just realized that it's duplicated: #19842

sorry 😄
