### ISSUE TITLE
[3.3.5] DB/Spell: Violet Hold - Defense System

### ISSUE THREAD

**Issue by Cannix** [TrinityCore/TrinityCore#20628]
**Description:**

The Defense System in Violet Hold should also target Ichor Globule (Entry: 29321)

[http://wowwiki.wikia.com/wiki/Dehydration](url)

**Current behaviour:**

Does not target Ichor Globule

**Expected behaviour:**

Should target Ichor Globule

**Steps to reproduce the problem:**

1. Start Ichoron encounter
2. Use Activation Crystal during splitting phase

**Branch(es):**

3.3.5, probably master too?

**TC rev. hash/commit:** 

TrinityCore rev. 9fc35785307e 2017-06-17 03:42:29 +0200 (3.3.5 branch) (Win64, Debug, Static) (worldserver-daemon) ready...

**TDB version:**  TDB 335.63

**Operating system:** Win

**Fix:**
```sql
-- DB/Spell: Spell 58152, Arcane Lightning should also target NPCs 29321, Ichor Globule
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=13 AND `SourceEntry`=58152 AND `ElseGroup`=18;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(13,1,58152,0,18,31,0,3,29321,0,0,0,0,'','Defense System - Arcane Lightning');
```

**Comment by tkrokli** [comment]
As you correctly state in the comment line, `CONDITION_SOURCE_TYPE_SPELL_IMPLICIT_TARGET` (13) with `ConditionTarget` = Potential spell Target (0) indicates that spell 58152, Arcane Lightning should target NPC 29321, Ichor Globule
Just make it part of the condition comment field too (or instead of a complete top comment line).

The condition comment could be written like this:
```sql
(13,1,58152,0,18,31,0,3,29321,0,0,0,0,'','Defense System - Arcane Lightning can target Ichor Globule');
```
- https://wow.gamepedia.com/Defense_Control_Crystal
- http://www.wowhead.com/spell=58152/arcane-lightning
- https://wow.gamepedia.com/Ichor_Globule
- http://www.wowhead.com/npc=29321/ichor-globule

**Comment by Cannix** [comment]
df21162fe44d2ff29c201a9004586f560789c38b

I just added a condition to the previous ones and copied the commit. Shall i change all of them too?

**Comment by Aokromes** [comment]
No need.

**Comment by Cannix** [comment]
But im still supposed to change mine?

**Comment by tkrokli** [comment]
OK, sorry about that. I see now that the TDB content is formatted the same way as yours.
Keep it the way it is (like Aokromes said), because it is the same format as existing content.
