### ISSUE TITLE
DK Minecart Quest Issue

### ISSUE THREAD

**Issue by sigbinium** [TrinityCore/TrinityCore#21042]
Description:
http://www.wowhead.com/quest=12701/massacre-at-lights-point

Current Behaviour:
Scarlet Miner wont say his dialogue and drag the minecart towards the ships.

Expected Behaviour:
Scarlet Miner says his dialogue, drags cart towards the ships at Light's Point.

Steps to Reproduce the Problem:
1. Clone repository
2. Compile
3. Run Server

Branch: 3.3.5a

TC Rev. Hash/Commit: 54d0b31 

TDB Version: 335.63

OS: Windows 8.1

**Comment by Aokromes** [comment]
..... search! we closed a ton of duplicate tickets of this.

**Comment by sigbinium** [comment]
My bad senpai! Been working 16 hour shifts lately but will search.

**Comment by tkrokli** [comment]
**Core/Movement: waypoint system issues #20310**
No need to search further about this issue. It has been pointed out before that this specific issue (as well as related ones) are caused by a _general waypoint issue_ so you don't need to open new issue tickets about it or add more info about it in the existing ones. It will be fixed when the waypoint system issues are solved.
