### ISSUE TITLE
[3.3.5] Windows compil - Boost error

### ISSUE THREAD

**Issue by ConradBunton** [TrinityCore/TrinityCore#21151]
MSVC 14.1 with boost 1.63 (libs 14.0) works, however there's warning "Unknown compiler version - please run the configure tests and report the results"
With Boost 1.65, the file libboost_filesystem-vc141-mt-1_65_1.lib is unreadable.
Same error with Boost 1.64 and 1.66

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 02022d3cd65f072874e9f5de061e0b158b6eb634

CHANGEME Copy the first line of the `worldserver`, `authserver` or `bnetserver` startup.
For example: TrinityCore rev. 071b23d606 2017-12-28 23:34:33 +0100 (3.3.5) (Win64, Release, Static)

**TDB version:**  335.63

**Operating system:** Win 7

**Comment by Aokromes** [comment]
not tc issue instead boost. also no error instead sort of warning.

**Comment by ConradBunton** [comment]
Its happen after a commit who force using MSVC 14.1 instead 14.0.
Boost 1.65 come from the link in TC Atlassian.

**Comment by tkrokli** [comment]
It would have happened anyway with any Visual Studio 2017 version after 19.11 (2017 version 15.3).
See also Boost 1.65.1 `C:\local\boost_1_65_1\boost\config\compiler\visualc.hpp` :
```cpp
//
// last known and checked version is 19.11.25506 (VC++ 2017.3):
#if (_MSC_VER > 1911)
#  if defined(BOOST_ASSERT_CONFIG)
#     error "Unknown compiler version - please run the configure tests and report the results"
#  else
#     pragma message("Unknown compiler version - please run the configure tests and report the results")
#  endif
#endif
```
In theory, you could claim that the change in TC source requirements to need the use of Visual Studio 2017 instead of Visual Studio 2015 caused it, but the actual cause of this warning message is that Boost has not yet updated the support in its config files for VS 2017 19.12 and newer (15.4 and 15.5 - current updated version being 15.5.2).

We simply need to wait for Boost to produce a version with updated config support for newer/current versions of Visual Studio 2017. In theory, you could try downgrading Visual Studio 2017 to version 15.3 to get rid of the warning, but as long as it does not cause the compile to fail, it will not be a requirement by TrinityCore.

**Comment by Aokromes** [comment]
added a note to https://community.trinitycore.org/topic/1518-trouble-with-your-trinity-install-starting-login-readme-1st-faqs/

**Comment by ConradBunton** [comment]
(Sorry for my english, I do with I can)
"Unknown compiler version - please run the configure tests and report the results"
That warning doesn't make error.
The problem is about MSVC 14.1. I dont understand why force it in the code if no boost is really ready for that. Cause Boost 1.65.5 (for example) make reals errors. Understand what I mean ?

**Comment by tkrokli** [comment]
**Stay with Boost 1.65.1 for now.** Boost 1.66.0 seems worse, it can actually cause the compile to fail.
The decision to support C++ 14.1 in the source is made by TC main developers and owners.

**Comment by ConradBunton** [comment]
Boost 1.64.0 or upper dont works. I always have the error with the file libboost_filesystem-vc141-mt-1_xx_x.lib
Boost 1.63 is the highest version working.

**Comment by tkrokli** [comment]
Not sure why you can't get Boost 1.65.0 or 1.65.1 to work (it works for me with current updated VS 2017), but as long as you are able to compile the source (even with warnings), that should be all you need for now.

We all have to wait for http://www.boost.org/ to create support VS 2017 15.4 (19.12) and newer.

**Comment by ConradBunton** [comment]
I tried Boost 1.64 1.64 1.65 and 1.66 (All from official site). They all make error and I cant compil.
1.66 doesnt work at all (error everywhere), 1.64 to 1.65 all make the same error :
"Can't open libboost_filesystem-vc141-mt-1_xx_x.lib"

I made that issue to talk about that problem but it was closed about 30 sec after.

**Comment by tkrokli** [comment]
That is because not everyone have got your errors, which means this is not a TrinityCore problem.

For discussions on personal compile problems, use the TrinityCore Forum pages (https://community.trinitycore.org) or visit the #trinity IRC channel @ irc.rizon.net (https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130200/IRC)
