### ISSUE TITLE
Core/Spell: Penance

### ISSUE THREAD

**Issue by ArcaneFox** [TrinityCore/TrinityCore#21227]
**Description:**
Penance damages the enemy and the player too.

**Expected behaviour:**
Penance shouldn't damage the player when targeting an enemy.

**Steps to reproduce the problem:**

1. Create a priest
2. Level up to 10
3. Choose Discipline spec
4. Hit an enemy with Penance

**Branch(es):** master

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/3d7af56f5cab503518fb2202ca839793c2b08862

**TDB version:**  720 + Updates

**Operating system:** Windows 10 x64

**Comment by tkrokli** [comment]
Have you checked that it is not caused by something in
https://github.com/TrinityCore/TrinityCore/blob/master/src/server/scripts/Spells/spell_priest.cpp (Scripts)
(instead of your reference to
https://github.com/TrinityCore/TrinityCore/tree/master/src/server/game/Spells (Core))?

(I have not checked myself, but I presume you would know more about priest spells.)

**Comment by ArcaneFox** [comment]
Yes, I checked the spell_pri_penance and the code seems good to me. Maybe it's outdated (line 1015:  7.1.5) but I don't know for sure.
