### ISSUE TITLE
Pets missing

### ISSUE THREAD

**Issue by daddycaddy** [TrinityCore/TrinityCore#21266]
**Description:**
Hi there,
I'm having the following issue, pets do not appear in stable after they are dismiss

To replicate have a hunter with two tamed pets one in stable one not. Dismiss current pet(not abandon) and use call stabled pet. The other pet will now be missing from your tamed pets.

Thanks

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. f1896144c00e+ 2018-01-18 19:14:38 -0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (authserver)
TrinityCore rev. f1896144c00e+ 2018-01-18 19:14:38 -0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows Server 2012

**Comment by tkrokli** [comment]
TrinityCore rev. f1896144c00e 2018-01-18 19:14:38 -0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
TDB 335.63 + updates up to and including `2018_01_18_02_world_335.sql`

I can confirm this behaviour on any level 10+ hunter too, when visiting a Stable Master.
Call Stabled Pet is simply a tool to make the pet stable available anywhere.
If the pet is dismissed, it is not available / not visible to be handled.

General spell details, Call Stabled Pet (hunter level 80 ability):
- https://wow.gamepedia.com/Call_Stabled_Pet
- https://web.archive.org/web/20100812021100/http://www.wowhead.com/spell=62757

BTW, what is the expected result? That the hunter pet should be available when dismissed too?

**Comment by funjoker** [comment]
#21016 <--- will fix this

**Comment by funjoker** [comment]
Sure it is 3.3.5 ?
Sounds more like master :D

**Comment by tkrokli** [comment]
Sure, I would have thought so, but the OP obviously uses the `3.3.5` branch.

**Comment by Killyana** [comment]
Could be the same issue as https://github.com/TrinityCore/TrinityCore/issues/3610

**Comment by tkrokli** [comment]
To me, the issue #3610 (**Hunters pet disappear after change spec**) is different because in that issue, the pet is completely removed from DB (exotic pet does not reappear after changing from BM with exotic pet mastery to a different spec and then back again to the old BM exotic pet spec), whereas the issue on this page is that the pet is not visible to the stable master or in the Call Stabled Pet UI -- which I thought was intended (or at least it has been like this for several years here on TC). The pet becomes visible again if you call it back from being dismissed (not abandoned) and can be handled normally as expected.

I just don't know if it should be possible (if it used to be possible on retail in 3.3.5a) to manage a temporarily dismissed pet at the stable master or in Call Stabled Pet. I also don't know if there is any difference between current retail hunter pet behaviour at the stable master from what it used to be in 3.3.5a.

**Comment by Aokromes** [comment]
100% repo:

get a beast mastery maxed talent to get beast mastery talent.
tame 2 exotic pets.
leave pet to die on combat.
use call stabled pet.
move stabled pet from stabled pets to current pet.
cry.

**Comment by illfated** [comment]
So, if I understand it correctly, this feature has not been implemented yet here in TC source?
