### ISSUE TITLE
Scripts/Naxxramas: Loatheb's spore spawn locations

### ISSUE THREAD

**Issue by Foereaper** [TrinityCore/TrinityCore#21270]
**Description:**

Loatheb in Naxxramas currently spawns the spores directly underneath himself instead of in a random corner of the room.

**Current behaviour:**

Description above.

**Expected behaviour:**

The spores should spawn in a random corner of the room and not directly underneath the boss.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** f189614

**TDB version:**  TDB 335.63

**Operating system:** Windows Server 2012

**Comment by grigory9** [comment]
Can't reproduce, it works as expected

![screen shot 2018-03-11 at 21 20 16](https://user-images.githubusercontent.com/11505031/37256916-6a28a366-2572-11e8-8fc1-8e9414aa0331.png)

Expected behaviour:
> The spores should spawn in a random corner of the room and not directly underneath the boss.


Branch(es): 3.3.5
rev. hash/commit: 02f1399
TDB version: 335.64
Operating system: Mac OSX High Sierra

**Comment by Keader** [comment]
Update your core @Foereaper

**Comment by Foereaper** [comment]
Yep, did Naxxramas again yesterday and it worked again. Guess it got fixed in the mean time :)
