### ISSUE TITLE
DB/Quest: A Refugee's Quandary

### ISSUE THREAD

**Issue by Ravens62** [TrinityCore/TrinityCore#21312]
**Description:**

Find and Retrieve Items.

**Current behaviour:**

Some items can not be collected but have aura around them.

**Branch(es):**  master

**TC rev. hash/commit:** 

TrinityCore rev. 9e8b4bd 2018-01-20 16:48:26 +0100 (master branch) (Win32, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  TDB 720.00

**Operating system:** Windows 10

**Comment by Aokromes** [comment]
change gameobject_template data1 to 30 fields without sniff is hack.

**Comment by tkrokli** [comment]
Tip: add **```sql** on top of your SQL code to make a code block and add syntax highlighting (even if the code is hack).

Also recommended: add one or more links from web pages about the items/quest/objects you refer to, for easier lookup by people who would like to help out with the issue.

**Comment by Kodekc** [comment]
Related to issue: https://github.com/TrinityCore/TrinityCore/issues/21311
The object should not be despawn

**Comment by JamesHoffer** [comment]
The issue I'm having with this quest is that once the item/s are looted, another player or even character can not see or loot Felix's 3 items, they never re-spawn. The only way for the item to reappear for me is to restart the world server. I strictly play on a LAN set up with the wife and kids. I tried just with my characters too, but the only way to get these items to re-appear was to restart the world-server. 

Is this the issue? anyone else having this issue? If not, any suggestions? I did try to re-install a fresh world database.  I update daily and have the latest build and database as of today. cc788bb8 Using TDB 335.19031, I did notice a couple weeks ago there is a TDB 335.19061 - 2019/06/15, should I use that instead, or is that not quite ready?

The issue in this thread is different since the poster says they see the aura/sparkles, but can't loot. I can loot, but only once until a restart. I didn't want to make a new post since this is the same quest. I'm also new here so forgive me if I'm doing wrong by replying to this issue.

**Comment by Aokromes** [comment]
test on 50c5d30

**Comment by JamesHoffer** [comment]
> test on [50c5d30](https://github.com/TrinityCore/TrinityCore/commit/50c5d30d13fe12af2a2028baf845fb6eab329a57)

Thanks for the quick reply, unfortunately, the problem still exists, I had to restart the world server for them to re-appear. I simply made two toons on the same account, did the quest, logged out, got on the next toon, and the items were not there. I would like to add that I originally waited over 15 minutes to see if the items would respawn, I couldn't find the spawn times in the db, so I waited. 

I'm not sure if the items are supposed to even disappear though, I thought just the sparkles did, can't quite remember that far back in 3.3.5. Thanks again for the quick reply, we're going to move on with our questing, but hopefully someone will eventually take a look at it and figure it out. Thanks again for the quick reply.

**Comment by Wyrserth** [comment]
@JamesHoffer issue fixed in e77c2d55c40bc9d4a15de471de754376f4ec1c49, sorry for the inconvenience.

**Comment by CraftedRO** [comment]
on 86551ba71669712cadf82f2dc1f0c5481f0fba1b this is no longer an issue, you can loot items on multiple characters.

**Comment by Naddley** [comment]
[e4fc6b9] - quest works
