### ISSUE TITLE
Core/Entities: Low level creature hit rate - never misses

### ISSUE THREAD

**Issue by kaldown** [TrinityCore/TrinityCore#21352]
**Description:**

Low level creatures never misses attacking me.

**Current behaviour:**

When you 80lvl fighting with 20lvl creature, why they never miss

**Expected behaviour:**

they should miss not only white attacks, but skills magical\physical either.
It'ls almost ridiculous when you can't run away from 20lvl mob why gouge\stun you every 2 seconds

**Steps to reproduce the problem:**

1. .go creature 9739 
2. stay and watch combat log. Look how many misses, and how many skills misses.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. a217c0be922f 2018-01-31 00:59:14 -0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  TDB_full_world_335.63_2017_04_18 Version of the TrinityCore database

**Operating system:** Debian 9.0 OS

**Comment by tkrokli** [comment]
Your description is vague and not specific enough to tell us that there is an issue at all.
I tested the following:
1. create a new human warrior
2. `.character level 80`
2. `.go creature 9739` // Dragonmaw Bonewarder, entry 1057
3. Get beaten to death because the player skill levels = 1 for all skills.

Notice how the player character will need a lot more time to skill up than it takes for a level 24 hostile NPC to remove 9621 xp from you, 25-35 hp for each hit. (To make matters worse, there are 2 NPCs within aggro range there, so they will kill you in half as much time because you have not understood the game mechanics.

**Comment by kaldown** [comment]
Interesting that your 9739 creature is something different from my 'Sickly refugee'. 
Ok now I understand that GUID is not strict. Thanks.
Let me explain more precisely.
Find any low level humanoid, in my case 20 lvl 'Sickly refugee' aggro him. At watch full combat log.
He almost never miss. I mean, too often for 60lvl difference and 400lvl my defense.
That's all I want to say.

**Comment by tkrokli** [comment]
OK, so any other changes necessary to check the difference, like added armor or which weapons are used?

Skill level 400 is max at level 80 (IIRC), so I guess your steps to reproduce the problem needs to include, for example, the command `.maxskill` as the GM command to set all skills to max to avoid skill being a factor in your issue. (Make sure to include any other necessary steps and practical NPC information so other users can test it the same way you did.)

**Comment by gmillerd** [comment]
Is the expectation that a level 80 character (naked, but with level 400 defense and base avoidance % for class) against a level 20 character has "total avoidance"? I am not trying to say "lrn2tank", but this is where all the endless "discussions" about the math of tanking comes into play, elite-like websites, theory crafting addons, etc.

Remember that "hit" is a very specific term, that term means "the npc didn't miss, you didn't dodge, you didn't parry, it wasn't a glancing blow, or blocked, or a critical strike" [here](http://wowwiki.wikia.com/wiki/Hit#Auto_attacks) and [here](https://wow.gamepedia.com/Melee_mitigation)

If your character doesn't have any other mitigation besides 400 "defense" and the base avoidance ... you aren't really giving a good showing of "total avoidance"

FWIW, you have obtain a "total avoidance" macro for your character and it will show you where you are at. You likely should have these available if you are tanking and specing gear.

I was able to take a bis 80 avoidance warrior warrior to that area, and yes I got "hit" plenty. 

My test was to ".npc add 1502 temp" the Undead starting area area level 1/2 "Wretched Ghoul" (taunt one, build rage, repeat adding obnoxiously and then a demo shout and you should have something to look at) and watch the combat log and scrolling combat text. Clearly I am dodging, blocking and parrying on a level 1 mob! I am also "missed" without a doubt. Even with adding dual +1000 def rings .additem 12947, not much of a difference.

"Watch yer back" ... Back to that "lrn2tank" stuff (or maybe lrn2rogue), if your character turns its back to the mobs ... even with >2600 defense your just going to have just hits and misses. The avoidance stats are removed in this position, you cannot dodge, block, parry outside of the character facing.

The level 1 guys (even with my back turned) couldn't damage me), the level 19 sickly guys (.npc add 2054 temp) could "hit" me head on.

I guess it goes without saying that these "hits" are physical strikes, spells (the trips and ignites are spells that are under a whole different mechanic)

I would also guess (or perhaps demand) that NPCs don't "miss" everything, else I would never dodge, parry or block which is the mechanic tanks often live by. Obviously the game system is "optimized" for max level and the rest is just "make it not broken" at times.

I couldn't find a skill "hit rating" for low level computation to share why level 1 NPCs have their goofy chance of hitting and what it exactly is. It's not the same as PCs. It would be cute to have that in logging somehow and watch the dice roll is it were, but it already is there.

**Comment by Treeston** [comment]
Issue has potential to be valid. Hit logic is _very_ old, and probably hasn't been reviewed in forever.

I will do some digging.

**Comment by Killyana** [comment]
I compared the miss rate between the actual revision and an old one from july 2017 and the result is exactly the same.

**Comment by Treeston** [comment]
Unsurprising, hit formula hasn't been touched in forever (it's probably still a holdover from mangos).

**Comment by Treeston** [comment]
Alright, [here](https://github.com/TrinityCore/TrinityCore/blob/21ad8761e9a6621b58262f89da9a0052d3aa0e6a/src/server/game/Entities/Unit/Unit.cpp#L12859)'s the current melee spell¹ miss formula as of 21ad8761e9a6621b58262f89da9a0052d3aa0e6a (the last commit to touch Unit.cpp at time of writing):

1. Base miss chance is 5%.
2. If the target is a player, increase the miss chance using target's defense skill
    * This includes some DR formulae, which are irrelevant to this issue - so I'm skipping the details²
3. If this is a white hit (auto-attack) and we are dual wielding, miss chance is increased by 19%
4. Adjust the miss chance by the difference between the attacker's weapon skill³ and `<victim level> * 5`
  * If the attacker's weapon skill is more than two unit levels (10 skill levels) behind, increase miss chance by 1% flat, plus another 0.4% per skill level difference (2% per unit level) beyond 10.
  * Otherwise, miss chance is increased (or decreased) by 0.1% per skill level (0.5% per unit level) of difference.
5. If the victim is below level 10, reduce miss chance to `<victim level> / 10` times the ordinary amount.
6. For yellow hits (spells), reduce miss chance by any `SPELLMOD_RESIST_MISS_CHANCE` that apply⁴
7. Reduce miss chance by the appropriate hit chance modifier
  * For players, the base value is derived from hit rating. For other units, it is zero.
  * Auras can then apply on top of this base value.
8. Cap the miss chance to be at most 60%.
9. Apply any incoming miss chance modifiers on the victim.⁵
10. Cap the miss chance to be at least 0%.

**_(Note: This is not intended as a factual statement about retail correctness of any of the above - there are a few things (which I won't point out to avoid tainting discussion) that stand out to me as maybe being wrong.)_**

Any way, that's what TC currently does to calculate miss chance. Feel free to look up actual formulae from the era to verify or point out incorrectness.

¹ _White attacks are considered "spells" for the purpose of miss calculation._
² _If you're interested, the full calculations are [here](https://github.com/TrinityCore/TrinityCore/blob/21ad8761e9a6621b58262f89da9a0052d3aa0e6a/src/server/game/Entities/Unit/StatSystem.cpp#L725) and [here](https://github.com/TrinityCore/TrinityCore/blob/21ad8761e9a6621b58262f89da9a0052d3aa0e6a/src/server/game/Entities/Unit/StatSystem.cpp#L688)._
³ _NPCs are always considered to have maxed weapon skill for their respective level._
⁴ _Any effect that reduces the miss chance of certain spells - certain talents do this._
⁵ _These effects (for example Deterrence) can exceed the 60% miss chance cap._

**Comment by ariel-** [comment]
> Hit logic is very old, and probably hasn't been reviewed in forever.

Not true, I did review this system in 0c24e4ee0e1f0bbb37f740aa6f0d45c384ee955d

**Comment by ariel-** [comment]
Miss chance of a level 20 creature as 'Sickly Refugee (id: 2054) against a level 80 player with 400 defense is 17% (5% base miss + 300 defense diff * 5 / 100), checked with the debugger this was the case.

Then I proceded to do a field test:

<details>

Sickly Refugee's melee swing hits Jasper for 9 Physical.
Sickly Refugee's Trip hits Jasper for 2 Physical.
Jasper is afflicted by Sickly Refugee's Trip.
Sickly Refugee's melee swing hits Jasper for 8 Physical.
Sickly Refugee's melee swing hits Jasper for 8 Physical.
Sickly Refugee's Trip dissipates from Jasper.
Sickly Refugee's attack misses Jasper.
Sickly Refugee's melee swing hits Jasper for 8 Physical.
Sickly Refugee's attack misses Jasper.
Sickly Refugee's melee swing hits Jasper for 7 Physical.
Sickly Refugee's melee swing hits Jasper for 8 Physical.
Sickly Refugee's melee swing hits Jasper for 8 Physical.
Sickly Refugee's Trip hits Jasper for 2 Physical.
Jasper is afflicted by Sickly Refugee's Trip.
Sickly Refugee's melee swing hits Jasper for 7 Physical.
Sickly Refugee's melee swing hits Jasper for 7 Physical.
Sickly Refugee's Trip dissipates from Jasper.
Sickly Refugee's melee swing hits Jasper for 7 Physical.
Sickly Refugee's melee swing hits Jasper for 8 Physical.
Sickly Refugee's melee swing hits Jasper for 7 Physical.
Sickly Refugee's attack misses Jasper.
Sickly Refugee's attack misses Jasper.
Sickly Refugee's Trip hits Jasper for 2 Physical.
Jasper is afflicted by Sickly Refugee's Trip.
Sickly Refugee's melee swing hits Jasper for 8 Physical.
Sickly Refugee's melee swing hits Jasper for 7 Physical.
Sickly Refugee's Trip dissipates from Jasper.
Sickly Refugee's attack misses Jasper.
Sickly Refugee's melee swing hits Jasper for 8 Physical.
Sickly Refugee's melee swing hits Jasper for 9 Physical.
Sickly Refugee's melee swing hits Jasper for 8 Physical.
Sickly Refugee's melee swing hits Jasper for 8 Physical.
Sickly Refugee's melee swing hits Jasper for 9 Physical.
Sickly Refugee's Trip hits Jasper for 2 Physical.
Jasper is afflicted by Sickly Refugee's Trip.
Sickly Refugee's melee swing hits Jasper for 8 Physical.
Sickly Refugee's Trip dissipates from Jasper.
Sickly Refugee's attack misses Jasper.
Sickly Refugee's melee swing hits Jasper for 7 Physical.
Sickly Refugee's attack misses Jasper.
Sickly Refugee's melee swing hits Jasper for 7 Physical.
Sickly Refugee's attack misses Jasper.
Sickly Refugee's attack misses Jasper.
Sickly Refugee's melee swing hits Jasper for 7 Physical.
Sickly Refugee's Trip hits Jasper for 2 Physical.
Jasper is afflicted by Sickly Refugee's Trip.
Sickly Refugee's melee swing hits Jasper for 7 Physical.
Sickly Refugee's Trip dissipates from Jasper.
Sickly Refugee's melee swing hits Jasper for 7 Physical.
Sickly Refugee's melee swing hits Jasper for 7 Physical.
Sickly Refugee's attack misses Jasper.
Sickly Refugee's melee swing hits Jasper for 8 Physical.
Sickly Refugee's melee swing hits Jasper for 7 Physical.
Sickly Refugee's attack misses Jasper.
Sickly Refugee's melee swing hits Jasper for 7 Physical.
Sickly Refugee's Trip hits Jasper for 2 Physical.
Jasper is afflicted by Sickly Refugee's Trip.

</details>

11 misses out of 57 total hits, including spell 'Trip (id 101)' casts, I agree the sample could be bigger but even this small sample size turns out to be 11/57 = 19.30% frequency of misses, which seems consistent with the numbers seen on debugger.
