### ISSUE TITLE
new bugged character !

### ISSUE THREAD

**Issue by irgc** [TrinityCore/TrinityCore#21467]
Hi, Friends

I compiled the latest version Tc 3.3.5

Me and my friend in duel , have a problem
my hero rouge i use blind and invisable and sap hunter

The character hunter is bugged and all the level spells are silenced and locked at one point!
I did not test other characters

just for fixed logout and again login on game!

Why is this?

image:

https://imgur.com/a/fbYSe

os: debian
TC: 3.3.5 LAST CLONE

**Comment by tkrokli** [comment]
Looks a bit like the description in issue **[3.3.5] [Spells] Loss of character control** #21460
You need to learn how to use the TrinityCore issue template instead of deleting it (which is evil).
You have not given us a valid TrinityCore rev. hash ("last clone" is not precise enough).
Try again on HEAD.

**Comment by irgc** [comment]
Hi, thank you

I' been downloading again!

Is fixed?

**Comment by tkrokli** [comment]
See: https://github.com/TrinityCore/TrinityCore/commits/3.3.5
Commits || https://github.com/TrinityCore/TrinityCore/commit/640dd138a5916a54808b9c1a363e87026d1af184 || https://github.com/TrinityCore/TrinityCore/commit/eb7d22d23eedb0d1b5374f80518cd7994d7c7b3a || https://github.com/TrinityCore/TrinityCore/commit/ba27711145d1b015578aedb48ea8532b4f0bec75  ||
