### ISSUE TITLE
Core/SAI: SMART_ACTION_SET_RUN with waypoints

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#21463]
**Description:** The action SMART_ACTION_SET_RUN no longer override the movement_type set on SMART_ACTION_WP_START

**Steps to reproduce the problem:**

1. use this SAI:
``` sql
UPDATE `creature_template` SET `AIName`= 'SmartAI' WHERE `entry` IN (321);
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (321) AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`)  VALUES
(321,  0, 0,0,  1, 0,100,1,     0,    0,0,0, 53,   0,    321,0,   0,    0,0, 1,   0,0,0,0,0,0,0, '321 - ooc no repeat - start wp'),
(321, 0, 1, 0, 40, 0, 100, 0, 2, 321, 0, 0, 59, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, '321 - on wp2 - set run on');
DELETE FROM `waypoints` WHERE `entry`=321;
INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) VALUES
(321, 1, -1.33869, -3.56321, -144.709, '321'),
(321, 2, -13.1266, -3.51810, -144.709, '321'),
(321, 3, -29.9264, -3.45383, -144.709, '321'),
(321, 4, -44.1643, -3.39935, -144.709, '321');
```
2. .tele test
3. .npc add temp 321
4. Notice the npc will not start runnig on wp2

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  rev. 01386cf44718

**Comment by Killyana** [comment]
@ccrs could you take a look to this issue please ? I need it to be fixed before pushing some quest scripts.

**Comment by ccrs** [comment]
its a tricky one, that is, if its resolved like it should

**Comment by Killyana** [comment]
The movement_type is updated only when the waypoint start and not in every node.
If you test this, you will notice the npc will start running only when he repeat the waypoint:
``` sq
UPDATE `creature_template` SET `AIName`= 'SmartAI' WHERE `entry` IN (321);
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (321) AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`)  VALUES
(321,  0, 0,0,  1, 0,100,1,     0,    0,0,0, 53,   0,    321,1,   0,    0,0, 1,   0,0,0,0,0,0,0, '321 - ooc no repeat - start wp'),
(321, 0, 1, 0, 40, 0, 100, 0, 2, 321, 0, 0, 59, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, '321 - on wp2 - set run on'),
(321, 0, 2, 0, 40, 0, 100, 0, 3, 321, 0, 0, 59, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, '321 - on wp2 - set run on');

DELETE FROM `waypoints` WHERE `entry`=321;
INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) VALUES
(321, 1, -1.33869, -3.56321, -144.709, '321'),
(321, 2, -13.1266, -3.51810, -144.709, '321'),
(321, 3, -29.9264, -3.45383, -144.709, '321'),
(321, 4, -44.1643, -3.39935, -144.709, '321');

**Comment by Killyana** [comment]
@ccrs any chance to fix this issue?

**Comment by ccrs** [comment]
here is the situation:

waypoint rewrite unified core waypoint structure, everything now is ``WaypointPath`` and ``WaypointNode``
ref https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Movement/Waypoints/WaypointDefines.h

there were many reasons to do this, but mainly, there were 4 different implementations for the same information "type"

main problem: the different implementations were not equal, they had notable differencies. For example, movement type was not present in each of them. You can still see the differencies in each database table.

to minimize the impact, each path load done by the AI has a "conversion" step. this conversion step assumes, for example, that the whole path movement type is the current of the AI entity. not a real change compared to the old logic, it did exactly the same.

the problem comes in the generated path handling. pre-rework everything was handled in the AI, to the extent that each path node was launched with an explicit call to MovePoint... really ugly. now the path is "converted" or rather "standarized" and sent to MotionMaster.

so, pre-rework you could change, for example, from walk to run and it affected current path because the next point will be launched with entity's current state. after the rework, that change wont take effect because MotionMaster's stored WaypointMovementGenerator does not "know about the change", to put it in some way.

what can be done? well a couple things
- finish the rework unifiying all the waypoin tables: huge, inmense, monstruous pain in the ass because of what I described before, each has different structure ergo new information has to be assumed at some point.
- create a method within WaypointMovementGenerator to change movement type on one or several of its nodes. This will need a chained logic from AI to MotionMaster to propagate the change.
- probably more

to solve this issue? with the implementation of the second point should be enough.

**Comment by HannibalRoG** [comment]
I think there are other situations where the first waypoint is not taken into account.
Sai for creature id 49141
only when the invoker enters combat does the sai begin its first waypoint
