### ISSUE TITLE
[master] Monk - Effuse

### ISSUE THREAD

**Issue by Gwyndrichstein** [TrinityCore/TrinityCore#21462]
**Description:**

Effuse does'nt heal anyone (player, group member or allied player).  

**Current behaviour:**

Effuse is succesfuly casted, but doesn't heal. 

**Expected behaviour:**

Effuse should heal the friendly target. 

**Steps to reproduce the problem:**

1. Select Monk
2. Cast Effuse

**Branch(es):** master

**TC rev. hash/commit:** 880a135e348da5762e9bdc469760c5436200f8bf

**TDB version:**  7.3.5 (latest release)

**Operating system:** Debian 9, Windows 10 64-bit(localhost)

**Comment by arazmus** [comment]
Hi Guys,
Just looking through the code... The spell works in Mistweaver spec because when GetTotalAttackPowerValue is called (Unit.cpp @ 6914) the function IsRangedWeaponSpell() return true. Therefore the attack power is calculated based on RangedAttackPower which for a Windwalker will be 0!
I think the IsRangedWeaponSpell code needs to be revisited.
Cheers!

**Comment by matanshukry** [comment]
Spell has been removed.
Partially replaced with Vivify which works.

Can close this.
