### ISSUE TITLE
Divine Intervention Issue

### ISSUE THREAD

**Issue by Tatara902** [TrinityCore/TrinityCore#21520]
**Description:**
When a paladin use the spell "Divine Intervention" in a DK or Warrior to remove any harmful Aura, it doesn't work like it should, making the target immune to damage, but not removing that aura, it can be tested on Professor Putricide with the spell http://www.wowhead.com/spell=72451/mutated-plague. Divine intervention works well when the target is another paladin.
Screenshot: https://image.prntscr.com/image/VEq2fd6tSf6pa4-qsQ66AQ.jpg

**Current behaviour:**

Divine Intervention doesn't remove harmful auras to other classes that aren't paladins

**Expected behaviour:**

Divine Intervention should remove harmful auras 

**Steps to reproduce the problem:**

1.  Test on a boss like Professor Putricide (Third phase)
2. Let that boss add the debuff "Mutated plague" to a tank (Warrior or DK )
3. Use Divine intervention on that tank

**Branch(es):**  3.3.5

**TC rev. hash/commit:**  c9b730c

**TDB version:**  335.64

**Operating system:** Win 10 x64

**Comment by tkrokli** [comment]
Divine Intervention:
- https://woehead.way-of-elendil.fr/?spell=19752 (triggers spell 19753)
- https://woehead.way-of-elendil.fr/?spell=19753 (triggered by 19752)

**Comment by Foereaper** [comment]
I also noticed during a raid that divine intervention doesn't seem to drop aggro (?) on bosses as well when dispelled. We wiped on Gluth in Naxxramas, used divine intervention on our healer, and the boss left combat when everyone else died. As soon as our healer dispelled divine intervention and casted resurrection, it instantly pulled the boss out of nowhere, even though our healer was far out of aggro range.

**Comment by Faq** [comment]
@Foereaper did you notice that boss had revenge aura on it?

You sure he did pull aggro after using this spell and not something else. btw on what rev you are?

**Comment by Foereaper** [comment]
I'm currently on ad796318, I can't say for sure whether the boss had revenge aura active or not, I honestly didn't look, but I'd imagine it wouldn't have the aura since it was not showing as in combat at all.

The only action performed after canceling divine intervention was paladin resurrection, where the paladin was standing by the door leading out of Gluths area, so far enough away to where he wouldn't have pulled normally.

**Comment by Foereaper** [comment]
Actually. I think I know what the issue might have been, and it's probably coincidental that it happened during the divine intervention spell. This is probably related to the ghosts pulling aggro when releasing, which is another issue I posted about previously.

If a player close enough to the boss released spirit after the paladin had canceled divine intervention, it would pull the boss onto the paladin regardless how far away he was, since he'd still be within the boss area. I'll test this theory later.

**Comment by ariel-** [comment]
Can't reproduce on efef6b5e36a8cd8eca023b8aa6a5d8cbd532ca68

**Comment by Tatara902** [comment]
@ariel- Did you tested with a warr or DK as the one who got the mutated plague ? because with paladin as a tank it works well, i updated the core to efef6b5 and i keep having the same issue. https://prnt.sc/imrp0z
