### ISSUE TITLE
DB/Quests: Old Hillsbrad Foothills (instance)

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21661]
**Description:**
https://www.wowhead.com/old-hillsbrad-foothills
https://www.wowhead.com/quest=10277/the-caverns-of-time

**Current behaviour:**
You can enter the instance without having completed The Caverns of Time quest (10277). The first NPC's are interactive, they give you the explosives, but nothing else works. You can open the gate to Thrall's cell, but you can't talk to him and he doesn't provide a quest.

The rest of the instances in Caverns of Time appear to be correctly locked with quest progression stemming from 10277. Seeing how quest 10277 is broken at the moment (#21516, fingers crossed Golrag works some magic in Caverns of Time), I just want to make sure it works every step of the way.

**Expected behaviour:**
I don't know for sure if "attunement" to the caverns of time instances was removed prior to 3.3.5, particularly for Hillsbrad Foothills, but it used to be required level 66 and completion of quest 10277. 

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 1c8d9af08460

**Operating system:** Windows 10

**Comment by tkrokli** [comment]
Don't know if this is helpful, since it does not say refer to patches or builds after 2007:
- https://wow.gamepedia.com/Escape_from_Durnholde_Keep
"In order to be able to access this first instance in the Caverns of Time, the player must be level 66 and complete the quest [To The Master's Lair](https://wow.gamepedia.com/Quest:To_The_Master%27s_Lair) from Steward of Time, and then the other quest [The Caverns of Time](https://wow.gamepedia.com/Quest:The_Caverns_of_Time) from Andormu."

**Comment by Killyana** [comment]
This will fix the issue: 
But there's no message displayed for the requirements:
``` sql
UPDATE `access_requirement` SET `quest_done_A`=10277, `quest_done_H`=10277 WHERE `MapID` IN (560);

**Comment by tkrokli** [comment]
Neat. I had completely forgot about that table as an option in this case.
