### ISSUE TITLE
Quest/Loot: Gaffer Jacks

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21690]
**Description:**
https://www.wowhead.com/quest=1579/gaffer-jacks

**Current behaviour:**
The fish Gaffer Jacks are apparently unfishable near Auberdine. I've fished about a hundred fish in and around Auberdine and have not fished a single one. Fishing skill is 80+

**Expected behaviour:**
Gaffer Jacks are (according to wowhead comments) supposed to have a 100% drop rate if you have the quest and are fishing near Auberdine and have a chance to drop along with other fish.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** fb31cb7c047f

**Operating system:** Windows 10

**Comment by tkrokli** [comment]
This is one of the cases where it would have been great to be able to see a hint of documentation or info pointer in the `Comment` field in `reference_loot_template` and `fishing_loot_template` :
```sql
SELECT * FROM `reference_loot_template` WHERE `item`=6717;
```
http://www.wowhead.com/item=6717/gaffer-jack
```
Entry    Item  Reference  Chance  QuestRequired  LootMode  GroupId  MinCount  MaxCount  Comment
-----  ------  ---------  ------  -------------  --------  -------  --------  --------  ---------
11104    6717          0     100              1         1        0         1         1  (NULL)
```
```sql
SELECT * FROM `fishing_loot_template` WHERE `Reference`=11104;
```
```
Entry    Item  Reference  Chance  QuestRequired  LootMode  GroupId  MinCount  MaxCount  Comment
-----  ------  ---------  ------  -------------  --------  -------  --------  --------  ---------
  148   11104      11104     100              0         1        1         1         1  (NULL)
```
-- info from TDB 335.64 content based on
TrinityCore rev. fb31cb7c047f 2018-03-23 17:34:10 +0100 (3.3.5 branch) (Win64, Release, Static)

I have not tested this myself yet, so I cannot confirm or refute the posted issue. I'll be back.

**Comment by tkrokli** [comment]
`TC>server debug`
```
TrinityCore rev. fb31cb7c047f 2018-03-23 17:34:10 +0100 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.0.2n  7 Dec 2017 (library: OpenSSL 1.0.2n  7 Dec 2017)
Using Boost version: 1.65.1
Using MySQL version: 5.6.38
Using CMake version: 3.10.1
Compiled on: Windows 10.0.16299
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64
```
Confirmed, [Gaffer Jacks](https://www.wowhead.com/quest=1579/gaffer-jacks) can no longer be looted even when following the wowhead tips and using improved gear to maximize the fishing loot chance. I picked up the quest Gaffer Jacks (1579) after getting my fishing skill up to 51 (achievement [[50 fish]](https://wow.gamepedia.com/50_Fish)) and fished all the way to [Journeyman Fisherman](https://wow.gamepedia.com/Journeyman_Fisherman) before giving up. This loot table has definitely stopped working for this quest now. I don't know when it stopped working, because it has been more than a year since I last tested this quest. Normally it should be completable within 8 - 20 catches (ideally as few as 8-9 because of the 100% factor).

**Comment by tkrokli** [comment]
I am pondering where to start looking for the cause of this issue.
```sql
SELECT * FROM `reference_loot_template` WHERE `Entry`=11104;
```
```
Entry    Item  Reference  Chance  QuestRequired  LootMode  GroupId  MinCount  MaxCount  Comment
-----  ------  ---------  ------  -------------  --------  -------  --------  --------  ---------
11104    6303          0    18.5              0         1        1         1         1  (NULL)
11104    6307          0     0.5              0         1        1         1         1  (NULL)
11104    6351          0     0.5              0         1        1         1         1  (NULL)
11104    6353          0     0.5              0         1        1         1         1  (NULL)
11104    6358          0      10              0         1        1         1         1  (NULL)
11104    6361          0       0              0         1        1         1         1  (NULL)
11104    6717          0     100              1         1        0         1         1  (NULL)
11104   12238          0      30              0         1        1         1         1  (NULL)
```
@Teppic1 or @ZenoX92 : do you have any ideas what could be worth testing here?
Is it possible that the loot table fails because the non-quest `Chance` values don't add up to 100?

**Comment by jerbookins** [comment]
I know little about the data structure and how all that works, but i am familiar with how mysql databases work in general. the row for the quest item (6717) has "questrequired" is marked 1, is there a corresponding data entry that specifies the quest id required?

**Comment by tkrokli** [comment]
The `*_loot_template` tables do not specify quest IDs, as far as I know. Maybe I should look in `conditions` to see if there is anything related to the item ID.

**Comment by jerbookins** [comment]
or is the QuestRequired field supposed to be the quest id rather than boolean?

**Comment by Aokromes** [comment]
QuestRequired  can only have 0 or 1 as value.

**Comment by tkrokli** [comment]
I haven't tested yet, but since item 6717 (Gaffer Jack) only figures once in `reference_loot_template` (`Entry`=11104), maybe we need to create new extra `reference_loot_template`s for each sub-zone/Area, like it is done for http://www.wowhead.com/item=6718/electropeller ? I am fairly sure https://wow.gamepedia.com/Quest:Electropellers (http://www.wowhead.com/quest=1580/electropellers) still works, but I haven't tested lately.

(Then again, I did try to fish in Area 148, North top of the Darkshore map, where both Zone=148 & Area=148, so I don't know if that will help.)

**Comment by tkrokli** [comment]
(**[WildCoffee](https://github.com/WildCoffee)** commented on issue TrinityCore/TrinityCore#21690 / 2018-03-27 22:17 GMT+0200)
> Is this related to the closed issue #19111?

**Comment by illfated** [comment]
@TecDian, do you have any ideas about this issue? (still present, BTW)
Could you check if there is anything related to `GroupId` 0 or 1 for this non-working loot?

TC>server debug
TrinityCore rev. 743980a6255a 2018-04-15 17:08:48 +0200 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.65.1
Using MySQL version: 5.6.38
Using CMake version: 3.10.1
Compiled on: Windows 10.0.16299
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64

**Comment by WildCoffee** [comment]
There should be an entry in the fishing_loot_template for zone 442 (Auberdine) because there is area specific loot there. This should fix it (or at least, it does on mine)

```sql
INSERT INTO `fishing_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequited`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (442, 11104, 11104, 100, 1, 1, 0, 1, 1, `Auberdine`);
```

**Comment by illfated** [comment]
Fair point, maybe zone 148 (Darkshore) is too general and not compatible with the quest details.
Just remember to add the `DELETE FROM` line in your suggested solution, similar to this:
```sql
DELETE FROM `fishing_loot_template` WHERE `Entry`= 442;
INSERT INTO `fishing_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequited`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES
(442, 11104, 11104, 100, 1, 1, 0, 1, 1, 'Auberdine');
```
Please also notice that comment (text) values are quoted with apostrophes instead of back ticks:
```
'Auberdine' <<---> `Auberdine`
```

**Comment by illfated** [comment]
Otherwise, your SQL works as you said. Just have to wait and see if it will be accepted as a solution.

TC>server debug
TrinityCore rev. 16f524ff2537 2018-06-26 20:17:59 +0200 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.65.1
Using MySQL version: 5.6.38
Using CMake version: 3.10.1
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64

**Comment by jerbookins** [comment]
@illfated I'd be happy with a solution that the devs agree is Blizzlike
