### ISSUE TITLE
Quest: City of Light

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21700]
**Description:**
https://www.wowhead.com/quest=10211/city-of-light

**Current behaviour:**
Khadgar's Servant begins walking outside of the Terrace and immediately sinks beneath the ground. It walks through the floor and down through the wall to the next waypoint near lower city.

I don't know if it's because I got too far away from it while looking for it after it sunk through the floor, but the only thing it said script wise was

> Follow me, stranger. This won't take long.

https://streamable.com/r9bg4

**Branch(es):** 3.3.5

**TC rev. hash/commit:**
TrinityCore rev. fb31cb7c047f 2018-03-23 17:34:10 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.0.2k  26 Jan 2017 (library: OpenSSL 1.0.2k  26 Jan 2017)
Using Boost version: 1.64.0
Using MySQL version: 5.5.38
Using CMake version: 3.10.1
Compiled on: Windows 10.0.15063
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Operating system:** Windows 10

**Comment by Killyana** [comment]
Cannot reproduce on rev. fb31cb7c047f

**Comment by Aokromes** [comment]
again, stop ignoring the new requirement of use the command server debug to report bugs.

**Comment by jerbookins** [comment]
Again? What? You lost me @Aokromes

**Comment by Aokromes** [comment]
13 days ago we included one new requirement to report bugs you are ignoring.

**Comment by jerbookins** [comment]
Okay, ignoring isn't really a fair word. I didn't realize there was a change. I updated the ticket.

**Comment by jerbookins** [comment]
I also updated the ticket with a video demonstrating the issue

**Comment by Killyana** [comment]
@jerbookins I started the quest many times, and the npc never go under map like in the video.

**Comment by Aokromes** [comment]
cannot reproduce here maybe it's windows only bug?

mmaps directory located in ./mmaps. Total size: 2152621724 bytes
but my mmaps on linux are:
mmaps directory located in ./mmaps. Total size: 2226791232 bytes

**Comment by Killyana** [comment]
I also use windows.
mmaps directory located in ./mmaps. Total size: 2229000480 bytes

**Comment by tkrokli** [comment]
`TC> server debug`
TrinityCore rev. 99993a7f62b2 2018-03-26 16:24:46 -0300 (3.3.5 branch) (Win64, Release, Static)
```
Using SSL version: OpenSSL 1.0.2n  7 Dec 2017 (library: OpenSSL 1.0.2n  7 Dec 2017)
Using Boost version: 1.65.1
Using MySQL version: 5.6.38
Using CMake version: 3.10.1
Compiled on: Windows 10.0.16299
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64
TC>_
```
I am able to reproduce the part where Khadgar's Servant drops below the floor inside the Central Dome in the Terrace of Light, just before the exit/entrance of the dome (X: -1845 Y: 5392.3 Z: -12.427637 / ZoneX: 56.899223 ZoneY: 42.594765 GroundZ: -26.036556 FloorZ: -12.428146 (these last 2 values vary with distance from the Dome entrance)), on its way to the ramp down to the Alliance Battlemasters. Khadgar's Servant resurfaces just before the end of the ramp to the Battlemasters, so I am able to complete the quest as long as I keep pace with my guardian (having set focus helps).

I am not 100% certain why it happens, but it might be due to a bit old maps/vmaps/mmaps (last dbc/maps rebuild was done on 16.02.2018 22:00 GMT+0100). I have not tested my theory yet, but it could either be that or maybe because Worldserver.conf is not 100% default values (AHBot is enabled).

**Comment by Killyana** [comment]
@tkrokli it happens every time you test the quest or only sometimes?

**Comment by Aokromes** [comment]
Humm another with small mmaps 

mmaps directory located in ./mmaps. Total size: 2152621724 bytes

**Comment by tkrokli** [comment]
The NPC dropping under Z floor is 100% reproducible on my current commit (and has been for about a month now). I am planning to rebuild maps/vmaps/mmaps next evening, so I will be able to test again in about 24h (unless something unexpected happens that will hinder my plans). I suspect that it is the same thing that bugs some NPCs at some random points, but I haven't thought much about it, since we are waiting for another core/maps update from Golrag. Anyway, I am fairly convinced that my issue is caused by outdated Mmaps.

**Comment by ArcaneFox** [comment]
I've just updated my wotlk server and the mmaps folder size is 2,152,621,724 bytes.

Latest commit: https://github.com/TrinityCore/TrinityCore/commit/b274c4b5c346655f2a524dd800591fa9f0259eae

**Comment by tkrokli** [comment]
TrinityCore rev. b274c4b5c346 2018-03-28 04:15:09 +0200 (3.3.5 branch) (Win64, Release, Static)
```
Using SSL version: OpenSSL 1.0.2n  7 Dec 2017 (library: OpenSSL 1.0.2n  7 Dec 2017)
Using Boost version: 1.65.1
Using MySQL version: 5.6.38
Using CMake version: 3.10.1
Compiled on: Windows 10.0.16299
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64
```
Rebuilt Cameras, dbc, maps, vmaps & mmaps with Tools from the same core rev. hash: b274c4b5c346 
There is no change in the file/folder sizes what so ever.
Still no change in the behaviour in Shattrath, Khadgar's Servant still drops below the floor inside the Central Dome and resurfaces just before the Alliance Battlemasters.
Does this indicate a less than complete game client?
What should a working size of mmaps be like?

**Comment by jerbookins** [comment]
71a4f68d66f9

Still broken

**Comment by Killyana** [comment]
Try with vmaps only then mmaps only to see if it's related to what exactly.

**Comment by Shauren** [comment]
MMAPS after edb2b16f546d18bb66f1527dddb6189f617ec1b3

![obraz](https://user-images.githubusercontent.com/297439/39089526-5a42a3bc-45c9-11e8-9195-458e7041c27d.png)

**Comment by illfated** [comment]
Hmm... you closed a 3,3,5 issue with a commit to the master branch.
Is this because the issue is identical in master (Legion game client) to the WotLK client?

**Comment by funjoker** [comment]
prolly mmaps issues in 3.3.5 are same in master (or compareable)

**Comment by jerbookins** [comment]
Rebuild MMAPS?

**Comment by Aokromes** [comment]
-#define MMAP_VERSION 8
+#define MMAP_VERSION 9

**Comment by jerbookins** [comment]
@Aokromes this quest is still broken c5fa08afc1d1

**Comment by illfated** [comment]
Maybe re-open the issue until the 3.3.5 cherry-pick has been done?

**Comment by Killyana** [comment]
The word broken doesn't make sense.

**Comment by jerbookins** [comment]
@killyana the servant walks below the surface of the ground for the first part of the quest.

**Comment by Saurelius** [comment]
Servant never falls into textures if add to creature_template_movement next row:
INSERT INTO `creature_template_movement` (`CreatureId`, `Ground`, `Swim`, `Flight`, `Rooted`) VALUES
(19685, 2, 1, 1, 0); 
(Ground State=Hover, Fly State=NoGravity)
But may be it's wrong?

**Comment by illfated** [comment]
Thank you for pointing it out, the `creature_template_movement` table is definitely usable, not a hack.
Allow me to show you the complete query as it needs to be in a commit:
```sql
-- Khadgar's Servant
DELETE FROM `creature_template_movement` WHERE `CreatureId`= 19685;
INSERT INTO `creature_template_movement` (`CreatureId`, `Ground`, `Swim`, `Flight`, `Rooted`) VALUES
(19685, 2, 1, 1, 0);
```

**Comment by Saurelius** [comment]
> Thank you for pointing it out, the `creature_template_movement` table is definitely usable, not a hack.
> Allow me to show you the complete query as it needs to be in a commit:
> 
> ```sql
> -- Khadgar's Servant
> DELETE FROM `creature_template_movement` WHERE `CreatureId`= 19685;
> INSERT INTO `creature_template_movement` (`CreatureId`, `Ground`, `Swim`, `Flight`, `Rooted`) VALUES
> (19685, 2, 1, 1, 0);
> ```
> 
> edit: I have got some doubts about the `Flight` value being non-zero, though.

Thank. Indeed, Flight Statе does not affect the result. Just reinsured. The following code is sufficient.
```
-- Khadgar's Servant
DELETE FROM `creature_template_movement` WHERE `CreatureId`= 19685;
INSERT INTO `creature_template_movement` (`CreatureId`, `Ground`, `Swim`, `Flight`, `Rooted`) VALUES
(19685, 2, 1, 0, 0);
```

**Comment by Killyana** [comment]
This issue was fixed, I don't see why such hack will be used.

**Comment by illfated** [comment]
TC>server debug
TrinityCore rev. 59682bbd9b33 2019-02-09 21:06:09 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0j  20 Nov 2018 (library: OpenSSL 1.1.0j  20 Nov 2018)
Using Boost version: 1.69.0
Using MySQL version: 5.6.41
Using CMake version: 3.13.2
Compiled on: Windows 10.0.17763
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2153471900 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64
TC>_

Well, the quest is completable as long as I am aware of the issue, putting a raid marker on Khadgar's Servant to make sure I keep up with the NPC, but (for me, at least) the NPC still drops under the texture inside the dome and resurfaces down at the Lower City level near the Alliance Battlemasters. Is this related to mmaps and only happening to those of us who may have incomplete mmaps due to something missing in the game client? I was hoping it would not be, but the issue still seems to be present for me on a clean core & DB.

**Comment by illfated** [comment]
Thank you for the cherry-picking, Shauren. Looking forward to see the results.
(BTW, will rebuilding mmaps or other maps be required?)

**Comment by jerbookins** [comment]
I think maps is up to v9 now because of this, yes?

**Comment by illfated** [comment]
Correct. Any core rebuilt on or after the commits above needs to include Tools and rebuild all maps.
