### ISSUE TITLE
[3.3.5] Scripts/ICC: Valithria Dreamwalker (20$)

### ISSUE THREAD

**Issue by Strazhnik** [TrinityCore/TrinityCore#21887]
**Description:**

After kill Valithria event don't stop

**Current behaviour:**

Event don't stop 

**Expected behaviour:**

Event should stop

**Steps to reproduce the problem:**

1. Kill Valithria
2. Wait a few seconds
3. Event start again

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

5a22467912ef038c4a8df20547cab4b1b747ad09

**Operating system:** Ubuntu

**Comment by Strazhnik** [comment]
@Treeston  help 😊

**Comment by Treeston** [comment]
why me again 😢

**Comment by Strazhnik** [comment]
Help please :)

**Comment by illfated** [comment]
Would be quite useful to have someone else confirm or disconfirm this issue.

**Comment by Langerz82** [comment]
How do you activate the event? Is it a quest? Id please.

**Comment by tje3d** [comment]
@Langerz82 after healing Valithria, a chest should be appear and Valithria should not revive again. But if progress fails and Valithria dead, she should be revive after a few minutes.

**Comment by Strazhnik** [comment]
After complete healing Teaches, mobs start to appear again (after few seconds)

**Comment by Aokromes** [comment]
test again on head after latest thread fixes.

**Comment by Xatmo980** [comment]
She still resets

**Comment by illfated** [comment]
@Xatmo980 : can you test again on current source (clean and unchanged) to see that it works?

**Comment by ccrs** [comment]
try 10HC with 2 players, it used to be the ugly one

**Comment by Xatmo980** [comment]
ill update agian and check it soon

**Comment by Winchester1987** [comment]
Tested with 10 players, doing the instance as it should be.
If the raid wipes on Valithria, she does not reset.

**Comment by PatricNox** [comment]
rev. b50f35f56bff 

**Tested on all Scenarios** 
On wipe reset, summoned adds from gates does not despawn properly. Everything else does though
On Completion, Valithira does the dying animation which is wrong.

-
Encounter does Not reset 5 sec after iniation as stated by @Winchester1987 
The gate does open after completed scenario.


> Healed with Lay on Hands, Paladin.

> Completing the encounter too fast, as in before even killing the lich's etc, makes her respawn after completion

**Comment by PatricNox** [comment]
in other words she is completable just missing some cosmetic fixes such as the gate adds to despawn properly and the complete encounter scenario

**Comment by TheWinchesters** [comment]
I cannot reproduce all the cases mentioned here, so I do not know which ones are still valid.
Can anyone test this?
It worked for my case (reset after wipe)

```diff
diff --git a/src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp b/src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp
index 7752d697da..e48bebab50 100644
--- a/src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp
+++ b/src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp
@@ -292,6 +292,7 @@ class boss_valithria_dreamwalker : public CreatureScript
 
             void Reset() override
             {
+                _events.Reset();
                 me->SetHealth(_spawnHealth);
                 me->SetReactState(REACT_PASSIVE);
                 me->LoadCreaturesAddon();
```

**Comment by TheWinchesters** [comment]
Update:
It should be noted that the situations reported here, I have not seen them happen in normal raids.
I will list every case here and my results (rev: c7445669e8577884fd512fe009f7d3da4cf0429a and I have the line of code commented above):
**"you walk up and it will reset in like 5 seconds or somethining":**
Not valid for normal raids. This will happen if you are a GM and do something like .go c id 36789 and start the encounter.
The core will reset the encounter because, ofcourse, the bosses needed to be there as a normal raid are not "done".
This did not happen to me in any other situation.

**On Completion, Valithira does the dying animation which is wrong.**
I've never seen this happen in normal raids.
You can reproduce this if you .mod hp 999999999999 (so your health will be 2147483647) and use Lay on hands on her.
Somewhere this big amount of heal is not handled correctly and Valithria success and dies.
(Combat log will show that you healed her 0 and 2147483647 overhealing).

If the amount of heal is smaller (something like 20000000) but you do not start the encounter, she uses AOE to kill all the mobs and stands there, full healed, ignoring all the things she should do after that spell.
- If first bosses are 'done', she will stand there full healed.
- If first bosses are 'not started', she will stand full healed and reset after some seconds.

If you are a GM and wanna do a quick heal on her, use a smaller amount of heal, set the first bosses as 'done' and start the encounter. Other ways do not give good results (either for playing around, testing or reporting things like this issue)
Not sure how importat this is since this situation only exists if the player is a gm doing abnormal healing.

**She does not reset if a normal raid wipes**
This is the only case I have seen and the only one that really affects normal raids.
The line of code I suggested seems to work but someone with more knowledge could confirm.

So, after all I tested and if I am not wring, there are two things to check:
- What will happen if the amount of heal she receives is really big?
- Does she correctly reset after a normal raid wipe?

These are all the result I have got. Maybe someone else has something different o can give more information.

**Comment by Treeston** [comment]
> What will happen if the amount of heal she receives is really big?

That one is easy. None of our HP modifications check for overflow - why would they? healing that much is impossible in actual play.

If HP overflows, funky things happen.

**Comment by ccrs** [comment]
>  and use Lay on hands on her

IIRC % heal for Valithria is currently capped in some way

**Comment by Keader** [comment]
dd81978f432f9c1ecb72ebcadcb5a50042e005ad

**Comment by Xatmo980** [comment]
Did this get fixed sry ive been away from wow for a bit
