### ISSUE TITLE
DB/Quest: Keeping Pace (Zamek's Distraction)

### ISSUE THREAD

**Issue by phantomdl** [TrinityCore/TrinityCore#2191]
Core 6f8f2ce130e
  TDB 335.11.41

http://www.wowhead.com/quest=1190

Zamek does not create a diversion for you. Also you are not able to steal the plans
##

**Comment by Rushor** [comment]
but the spawn of object=20805 already works fine

**Comment by tkrokli** [comment]
Yes, but Zamek does not create the diversion event, so the current quest behaviour is not "blizzlike". Last time I ran around in the Mirage Raceway area in the Shimmering Flats in Thousand Needles, it was possible to finish the quest without the NPC Rizzle Brassbolts running out of his hut. According to http://wow.gamepedia.com/Quest:Keeping_Pace and the linked word [[diversion]](http://wow.gamepedia.com/Quest:Zamek's_Distraction) (http://wow.gamepedia.com/Quest:Zamek's_Distraction), there is a chance that quest 1191 http://www.wowhead.com/quest=1191/zameks-distraction is not available in-game in the 3.3.5 source
 (I have not checked that part yet).

**Comment by bblewittAG** [comment]
Got the latest TrinityCore for 3.3.5a and still not working for the event?
Is there a work around for it I can input on my server to get the quest to be completed normally without having to do quest completed command?

**Comment by tkrokli** [comment]
TrinityCore rev. aa0b7dd1529a 2017-05-01 18:52:15 -0300 (3.3.5 branch) (Win64, Release, Static)
TDB 335.63 plus updates up to and including `2017_05_02_00_world_335.sql`

Confirmed, still not working (maybe even worse than when this issue was opened).

Looking at the names of the objects, I agree that it does not look like a change from [20805 (Rizzle's Unguarded Plans)](http://www.wowhead.com/object=20805/rizzles-unguarded-plans) to [179888 (Rizzle's Guarded Plans)](http://www.wowhead.com/object=179888/rizzles-guarded-plans) would match the intention of the objects' names, seeing that "Guarded Plans" indicates that the scripted activity should run first to change the object from Guarded to Unguarded to make it lootable. The first indication of a missing or not working script is that the player can not talk to the [NPC Zamek (entry 4709)](http://www.wowhead.com/npc=4709/deprecated-for-4-x-zamek#comments), his gossip is completely missing (condition or script issue?) and therefore can not start the diversion script which should also handle the gameobject(s).

In theory, the gameobject should be 179888 (Rizzle's Guarded Plans) as long as the diversion has not happened yet and the player char has taken, but not completed, quest 1190 yet. After the diversion, the gameobject should change into 20805 (Rizzle's Unguarded Plans), but something in the source or DB does not allow the item to be looted from that gameobject. (Maybe there is a condition blocking it, but I haven't looked up that part yet.) (this is also speculation without testing)
- http://www.wowhead.com/quest=1190/keeping-pace
- http://www.wowhead.com/quest=1191/zameks-distraction
- http://www.wowhead.com/object=20805/rizzles-unguarded-plans
- http://www.wowhead.com/object=179888/rizzles-guarded-plans#comments
- http://www.wowhead.com/quest=1194/rizzles-schematics

For the `quest_starter` part of your workaround, notice that the object should give you the followup quest, [[Rizzle's Schematics] (1194)](http://www.wowhead.com/quest=1194/rizzles-schematics), which is the current quest combined with `gameobject_queststarter`.`id` 20805, therefore, the workaround SQL queries should look like this:
```sql
-- Workaround for gameobject currently spawned for quests 1190 & 1194 in Mirage Raceway, Shimmering Flats
UPDATE `gameobject_questender` SET `id`= 179888 WHERE `quest`= 1190; -- "Keeping Pace"
UPDATE `gameobject_queststarter` SET `id`= 179888 WHERE `quest`= 1194; -- "Rizzle's Schematics"
```
And yes, I can confirm that this workaround works, but I have my doubts that this will be accepted, because we still need to make the SAI script for [Zamek (entry 4709)](http://www.wowhead.com/npc=4709/deprecated-for-4-x-zamek#comments) work and also need to make his quest [1191 Zamek's Distraction](http://www.wowhead.com/quest=1191/zameks-distraction) show up. I have tried with and without conditions, but no success so far. I have also tried looking into `quest_template_addon`, `creature_queststarter` and `creature_questender` to see if something is missing there, but it looks like quest 1191 is present. I just don't know what is blocking it from showing up as available from Zamek (even without conditions).

**Comment by BahDumbBugs** [comment]
I'll confirm @tkrokli 's confirmation. Still doesn't work. Had to log in my GM account, and complete/reward my player to move further in the chain. Upon attempting to loot the object "Rizzle's Guarded Plans" I get the dialogue text "Greetings (Player name here.)"

**Comment by RedSonja** [comment]
Same as above here too.

**Comment by ZenoX92** [comment]
I'm willing to help solving some of the old issues, starting with this one.
**Suggested Fix**
```sql
-- Fix availability for quest "Zamek's Distraction"
UPDATE `quest_template_addon` SET `PrevQuestID`=0 WHERE `ID`=1191;
UPDATE `conditions` SET `ConditionTypeOrReference`=28 WHERE `SourceTypeOrReferenceId`=19 AND `SourceEntry`=1191;

-- Add gossip text for gameobjects "Rizzle's Guarded Plans" & "Rizzle's Unguarded Plans"
UPDATE `gossip_menu` SET `TextID`=7182 WHERE `MenuID`=6029;
UPDATE `gossip_menu` SET `TextID`=7181 WHERE `MenuID`=6030;

-- Texts
DELETE FROM `creature_text` WHERE `CreatureID` IN (4709,4720);
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(4709,0,0,"Hehehe! Things go boom!",12,0,100,11,0,0,1540,0,"Zamek"),
(4720,0,0,"What was that!",14,0,100,5,0,0,1541,0,"Rizzle Brassbolts"),
(4720,1,0,"Bloody... Must have been the goblins... Let's see how bad the damage is.",12,0,100,5,0,0,1542,0,"Rizzle Brassbolts"),
(4720,2,0,"Guess there's nothing more to be done. Blast!",12,0,100,6,0,0,1543,0,"Rizzle Brassbolts");

-- Waypoints
DELETE FROM `waypoints` WHERE `entry` IN (4709,4720);
INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) VALUES
(4709,1,-6237.13,-3911.58,-60.5103,""),
(4709,2,-6257.43,-3879.56,-58.8595,""),
(4709,3,-6267.61,-3850.91,-58.7503,""),
(4709,4,-6266.24,-3846.35,-58.7503,""),
(4709,5,-6267.61,-3850.91,-58.7503,""),
(4709,6,-6257.43,-3879.56,-58.8595,""),
(4709,7,-6237.13,-3911.58,-60.5103,""),
(4709,8,-6226.13,-3944.94,-58.6251,""),
(4720,1,-6243.39,-3845.91,-58.7498,""),
(4720,2,-6250.63,-3847.35,-58.7491,""),
(4720,3,-6255.06,-3853.64,-58.7491,""),
(4720,4,-6262.2,-3851.84,-58.7491,""),
(4720,5,-6266.24,-3846.35,-58.7503,""),
(4720,6,-6262.2,-3851.84,-58.7491,""),
(4720,7,-6255.06,-3853.64,-58.7491,""),
(4720,8,-6250.63,-3847.35,-58.7491,""),
(4720,9,-6243.39,-3845.91,-58.7498,""),
(4720,10,-6236.99,-3831.23,-58.1364,"");

-- Zamek
DELETE FROM `smart_scripts` WHERE `entryorguid`=4709 AND `source_type`=0;
DELETE FROM `smart_scripts` WHERE `entryorguid`=470900 AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(4709,0,0,0,20,0,100,0,1191,0,0,0,53,1,4709,0,0,0,0,1,0,0,0,0,0,0,0,"Zamek - On Quest 'Zamek's Distraction' Finished - Start Waypoint"),
(4709,0,1,0,20,0,100,0,1191,0,0,0,83,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Zamek - On Quest 'Zamek's Distraction' Finished - Remove Npc Flag Questgiver"),
(4709,0,2,0,40,0,100,0,4,4709,0,0,80,470900,0,0,0,0,0,1,0,0,0,0,0,0,0,"Zamek - On Waypoint 4 Reached - Run Script"),
(4709,0,3,0,40,0,100,0,8,4709,0,0,66,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Zamek - On Waypoint 8 Reached - Set Orientation"),
(470900,9,0,0,0,0,100,0,0,0,0,0,54,7000,0,0,0,0,0,1,0,0,0,0,0,0,0,"Zamek - On Script - Pause Waypoint"),
(470900,9,1,0,0,0,100,0,0,0,0,0,66,0,0,0,0,0,0,8,0,0,0,0,0,0,0.943443,"Zamek - On Script - Set Orientation"),
(470900,9,2,0,0,0,100,0,2000,2000,0,0,50,144065,8,0,0,0,0,8,0,0,0,-6265.67,-3845.57,-58.75,0.943443,"Zamek - On Script - Summon Gameobject 'Explosive Charge'"),
(470900,9,3,0,0,0,100,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Zamek - On Script - Say Line 0"),
(470900,9,4,0,0,0,100,0,7000,7000,0,0,9,0,0,0,0,0,0,20,144065,0,0,0,0,0,0,"Zamek - On Script - Activate Gameobject 'Explosive Charge'"),
(470900,9,5,0,0,0,100,0,1000,1000,0,0,45,1,1,0,0,0,0,19,4720,0,0,0,0,0,0,"Zamek - On Script - Set Data to Rizzle Brassbolts"),
(470900,9,6,0,0,0,100,0,60000,60000,0,0,82,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Zamek - On Script - Add Npc Flag Questgiver");

-- Rizzle Brassbolts
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=4720;
DELETE FROM `smart_scripts` WHERE `entryorguid`=4720 AND `source_type`=0;
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (472000,472001) AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(4720,0,0,0,38,0,100,0,1,1,0,0,80,472000,0,0,0,0,0,1,0,0,0,0,0,0,0,"Rizzle Brassbolts - On Data Set - Run Script"),
(4720,0,1,0,40,0,100,0,5,4720,0,0,80,472001,0,0,0,0,0,1,0,0,0,0,0,0,0,"Rizzle Brassbolts - On Waypoint 5 Reached - Run Script"),
(4720,0,2,0,40,0,100,0,10,4720,0,0,66,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Rizzle Brassbolts - On Waypoint 10 Reached - Set Orientation"),
(472000,9,0,0,0,0,100,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Rizzle Brassbolts - On Script - Say Line 0"),
(472000,9,1,0,0,0,100,0,4000,4000,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Rizzle Brassbolts - On Script - Say Line 1"),
(472000,9,2,0,0,0,100,0,0,0,0,0,53,0,4720,0,0,0,0,1,0,0,0,0,0,0,0,"Rizzle Brassbolts - On Script - Start Waypoint"),
(472000,9,3,0,0,0,100,0,0,0,0,0,70,60,0,0,0,0,0,14,17087,179888,0,0,0,0,0,"Rizzle Brassbolts - On Script - Despawn Gameobject 'Rizzle's Guarded Plans'"),
(472000,9,4,0,0,0,100,0,0,0,0,0,70,60,0,0,0,0,0,14,13621,20805,0,0,0,0,0,"Rizzle Brassbolts - On Script - Respawn Gameobject 'Rizzle's Unguarded Plans'"),
(472001,9,0,0,0,0,100,0,0,0,0,0,54,25000,0,0,0,0,0,1,0,0,0,0,0,0,0,"Rizzle Brassbolts - On Script - Pause Waypoint"),
(472001,9,1,0,0,0,100,0,0,0,0,0,66,0,0,0,0,0,0,8,0,0,0,0,0,0,0.943443,"Rizzle Brassbolts - On Script - Set Orientation"),
(472001,9,2,0,0,0,100,0,20000,20000,0,0,1,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Rizzle Brassbolts - On Script - Say Line 2");

**Comment by tkrokli** [comment]
I took the liberty to edit the SQL slightly, only making cosmetic changes.
(replaced double quotation marks `" "` with apostrophes `' '` around texts with no apostrophes inside)

**Comment by Killyana** [comment]
@ZenoX92  the 2 gobs must be handled like this:
``` sql
(472000,9,3,0,0,0,100,0,0,0,0,0,41,0,60,0,0,0,0,14,17087,179888,0,0,0,0,0,"Rizzle Brassbolts - On Script - Despawn Gameobject 'Rizzle's Guarded Plans'"),
(472000,9,4,0,0,0,100,0,0,0,0,0,70,60,0,0,0,0,0,14,13621,20805,0,0,0,0,0,"Rizzle Brassbolts - On Script - Respawn Gameobject 'Rizzle's Unguarded Plans'"),
```
Also the gob 20805 provide the quest 1194 once 1190 is rewarded so the repeatable quest must be available if the quest 1190 is taken and not rewarded and if 1190 is rewarded and 1194  not taken or not rewarded

**Comment by ZenoX92** [comment]
Done it! I updated the script.
