### ISSUE TITLE
Hunter Talent "Explosive Shot" Issue

### ISSUE THREAD

**Issue by mymanjack** [TrinityCore/TrinityCore#21922]
**Description:**

The hunter talent "Explosive Shot" [Spell id: 53301] when casts on creatures below level 50 says "Target is to low level" 

**Expected behaviour:**

Believe this spell is supposed to be castable on all creatures regardless of level and deal the damage accordingly

**Steps to reproduce the problem:**

1. Create a hunter
2. Reach level 60 and learn the talent "Explosive Shot" [Spell id: 53301]
3. Cast "Explosive Shot" [Spell id: 53301] on any creature below level 50

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 1e25b215e5c5+ 2018-04-11 21:39:37 +0200 (3.3.5 branch) (Win32, RelWithDebInfo, Static)

**Operating system:** 

Windows 10

**Comment by adeutscher** [comment]
I think that this is because Explosive Shot (which has a DummyEffect-type effect) is not getting flagged as negative in `SpellInfo::_isPositiveEffectImpl()`. Because of this, it gets subjected to downranking when the target is below a certain level. Targets with a low enough level get scaled down to "do not cast at all". A similar problem last year looks like #14541, though the structure in SpellInfo has moved around since then. PR Incoming.
