### ISSUE TITLE
[Suggestion] Maps and DB directories

### ISSUE THREAD

**Issue by Smerdokryl** [TrinityCore/TrinityCore#21976]
**Description:**

Would it be possible to support maps and DBs being read from different directories? It would be much more convenient for people who have multiple servers, for whatever reason, which use different DBs, but do not want to store duplicated maps/vmaps/mmaps (they do take up a lot of space!).

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. 084da48ba15a+ 2018-05-26 18:48:09 +0200 (master branch) (Win64, Release, Static) (bnetserver)

**Operating system:** Windows 10

**Comment by Rochet2** [comment]
Changing the map / DBC / vmap etc directory is already supported through DataDir in worldserver.conf

**Comment by Smerdokryl** [comment]
@Rochet2 I meant having DBCs and maps in *different* directories.

Example: you have two servers, and each has a different bunch of DBCs. However, since they are of the same version, they can both use the same maps/vmaps/mmaps. So you have separate DBC folders for each, but the same maps/vmaps/mmaps folder for both.

**Comment by illfated** [comment]
What I get from your explanations, is that you are talking about different **drives**, **volumes**, **hardware** or **systems**, not simply different directories. The conf files support using a separate path for DBC/DB2/maps etc. compared to the core files.

I must admit I am a bit confused when you mention "DB" because I automatically think "MySQL Server DB" which is by default in a totally different directory and can easily be on a different OS/IP address/hardware. I must have misunderstood your meaning somehow.

**Comment by Aokromes** [comment]
use symbolic links.

**Comment by Smerdokryl** [comment]
What I mean is that, instead of having two copies of the same (rather voluminous) map files, I'd like to have this:
![image](https://user-images.githubusercontent.com/35412834/40626276-6ec1a24a-62af-11e8-91e0-0437fb5ec8cf.png)

**Comment by illfated** [comment]
Oh. Right. Good point. `ln -s` on Linux, `LINK.EXE -k` (hard link) on Windows.
