### ISSUE TITLE
Quest: "The Gift That Keeps On Giving" not working correcty

### ISSUE THREAD

**Issue by Addra** [TrinityCore/TrinityCore#22063]
**Description:**
Quest: [The Gift That Keeps On Giving](http://www.wowhead.com/quest=12698/the-gift-that-keeps-on-giving)
NPC: [Scarlet Ghoul](http://www.wowhead.com/npc=28845/scarlet-ghoul)

**Current behaviour:**
Item not work 100%! Gives an warning in TC Core Log:
_GameObject (template id: 190769) has invalid faction (faction template id) #0_
If Ghouls are created they do not follow player after fight (see this [video](https://www.youtube.com/watch?v=1fGcWBbqKfA))

**Branch(es):**
3.3.5 (maybe branch _master_ too)

**TC rev. hash/commit:** 
TrinityCore rev. 7187420 2018-06-17 17:03:10 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**Operating system:**
Ubuntu 18.04

**Comment by illfated** [comment]
`GameObject (template id: xxxxxx) has invalid faction (faction template id) #0`
 is more or less a known 3.3.5 issue.
I don't know if it has migrated to the master branch yet.

**Comment by Addra** [comment]
This Errorwarning belongs to that Gameobject, that will becreated by using the Questitem! But the Problem is that the Ghouls not follow after fight. I tried to change the script, but i am not be able to fix that

**Comment by Langerz82** [comment]
Patch see:
https://gist.github.com/Langerz82/7797e9c4bf1781a9e0470da8c6f93a77

**Comment by Killyana** [comment]
The issue about guardians stop following the player after a combat must be fixed on core side: https://github.com/TrinityCore/TrinityCore/issues/17981

**Comment by Langerz82** [comment]
Which UpdateAI function in class should I edit? There is a few of them lol.

**Comment by Langerz82** [comment]
Ok, here we go for testing:
https://gist.github.com/Langerz82/c0dbc73cd006fbb72312f72334f943e5

I have made the ScriptedAI do basic update events which can be overridden. This should theoretically preserve old scripts and they should remain the same in terms of functionality.

Notice the HasVictim which is necessary if you override the DoAttack function because it may be called before the DoVictim (they have seperate timers).

**Comment by Addra** [comment]
@Langerz82 your fix solved 1 of 2 Problems i have tested it!
Ghouls now follow after fight but the items isnt working correctly

**Comment by Aokromes** [comment]
full list of GOs afected by this issue, https://gist.github.com/Aokromes/05c6c61d63c99d834daf5e3c2d22c750 for some it's legit not having faction.

**Comment by jackpoz** [comment]
could you open another issue just for the gameobject part so we can discuss how to handle those cases ?(should we ignore the error if Faction ID = 0 ? should we fallback to another faction ? does TC already handle this case ?)

**Comment by funar** [comment]
Can confirm this is still occurring.  Is there a workaround?

**Comment by illfated** [comment]
@funar : I have only noticed the patch by Langerz in https://github.com/TrinityCore/TrinityCore/issues/22063#issuecomment-401995383
Notice also that Addra commented below that only the "not following player" issue seems to be fixed in it.

Looks like this could be related to the general issue with spells cast by gameobject and that spell targeting could be one of the problems.
(I noticed that the "Love is in the air" item https://woehead.way-of-elendil.fr/?item=34480/romantic-picnic-basket did set up the umbrella, blanket & basket, but did not trigger the spell https://woehead.way-of-elendil.fr/?spell=45123/romantic-picnic . Not sure if this is closely enough related to the general gameobject spell cast issue.)

**Comment by Killyana** [comment]
The spell https://woehead.way-of-elendil.fr/?spell=52479#used-by-object cast by the gob will sometimes miss because of https://github.com/TrinityCore/TrinityCore/issues/23142
The issue related to guardians not following the player after a combat already exist https://github.com/TrinityCore/TrinityCore/issues/17981
The issue about the trap animation:  https://github.com/TrinityCore/TrinityCore/issues/23109
