### ISSUE TITLE
The Black Knight's Fall

### ISSUE THREAD

**Issue by Nocturne1501** [TrinityCore/TrinityCore#22211]
**Description:**

The Black Knight's Fall is an uncompletable quest.

**Current behaviour:**

After summing and fighting the Black Knight, he will force the played off his/her mount and demand the player face him without it. After his invulnerability bubble wears off, the Black Knight turns into a corpse, sliding around while attacking the player. He is impossible to slay in this state, rendering the quest uncompletable.

**Expected behaviour:**

Presumably, the Black Knight should fight the player on foot normally, and become able to be slain.

**Steps to reproduce the problem:**

1. .quest add 13664
2. Call the Black Knight out to fight via Squire Calvin
3. Defeat the Black Knight and observe

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 44819052a743+ 2018-07-26 03:23:06 +0000 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**Operating system:**

Ubuntu 18.04

**Comment by Killyana** [comment]
The issue comes from: https://woehead.way-of-elendil.fr/?spell=64498
Apply Aura : Mod Increase Health Valeur : -37500
I will take a look when I get some free time.

**Comment by Killyana** [comment]
After investigation, it's a spell issue: the npc starts the fight with 50000 HP, on phase 2 it dismounts and cast 64498 on self to modifies HP to 12500 (Effect #2 | Apply Aura: Mod Increase HealthValue: -37500)  and heal self (Effect #3 | Heal: Value: 15000)

The issue is upon the HP are modified the npc will get 0 HP instead of 1HP, this will trigger the "death state"
