### ISSUE TITLE
Bugs on Combat Reseting for Bosses

### ISSUE THREAD

**Issue by pedroevil51** [TrinityCore/TrinityCore#22226]
Description: Instance Bug/Core Bug , boss resets after becoming inivisible/untargetable 

Current behaviour: Bosses resets after chaning to certain phases check steps

Steps to reproduce the problem:

1. After a certain hp %, Herald Volazj = 29311 enters a phase where we becomes invencible and invisible, but after he comes back, his HP resets / On shadowfangkeep, the last boss keeps reseting as well / Malygos resets when enter his 3rd phase 

Branch:3.3.5

TC rev. hash/commit: https://github.com/TrinityCore/TrinityCore/commit/5cdb53896f89bfff82ad627dd30aebe3834aabf5

**Comment by shamage** [comment]
Is this link on wow head correct? = >> [Herald Volazj](http://www.wowhead.com/npc=29311/herald-volazj)

TrinityCore rev. 5cdb53896f89 2018-08-02 19:09:40 +0200 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.0.2o  27 Mar 2018 (library: OpenSSL 1.0.2o  27 Mar 2018)
Using Boost version: 1.67.0
Using MySQL version: 5.7.21
Using CMake version: 3.11.1
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Disabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64

**Comment by pedroevil51** [comment]
@shamage Yes it is

**Comment by illfated** [comment]
I don't know for sure if this bug is caused by core or scripts, so I can't tell if this issue belongs to the category **Scripts/instance** or **Core/Combat** .
Anyhow, I would like to suggest a few improvements to the title and the first issue post:

**Core/Combat: various bugs in Combat Reset for bosses**

**Steps to reproduce the problem:**

1. After a certain %hp, Herald Volazj  (29311) enters a phase where we becomes invincible and invisible, but after he comes back, his HP resets.
2. in Shadowfang Keep, the last boss keeps resetting as well.
3. Malygos resets when entering his 3rd phase.

Those 3 examples are more indications of the issue than actual description of how to replicate the issue, so it would be appropriate to move those 3 lines to a bullet list under **Current behaviour:** and fill in a more step-by-step description under **Steps to reproduce the problem:** on how to get one of the bosses to the point where this issue will become apparent.

I also recommend adding back the template setting for **bold text** ( `** **` ) for the categories **Description:** , **Current behaviour:** , **Branch(es):** and **TC rev. hash/commit:** for readability.

In case of any users/readers unfamiliar with the original behaviour of those bosses, I recommend adding back the missing category **Expected behaviour:**
followed by a short description of what the blizzlike behaviour is supposed to be.

**Comment by SpaceArtisanWD** [comment]
Probably a big hack somewhere, or something related to outdated code in the scripts. Go figure, lol.

**Comment by pedroevil51** [comment]
Re-open this issue malygos still resets on entering his 3rd phase

**Comment by pedroevil51** [comment]
@Treeston this issue is not closed

**Comment by Treeston** [comment]
Malygos is a vehicle-related issue exposed by 532ab1c. Need to deliberate the best way to fix the underlying source while minimizing performance impact.

**Comment by pedroevil51** [comment]
@Treeston that new commit did not fixed the problem, malygos still resets on 3rd phase

**Comment by Treeston** [comment]
it's not meant to
