### ISSUE TITLE
Fishing

### ISSUE THREAD

**Issue by Ravens62** [TrinityCore/TrinityCore#22228]
**Description:**

There is no typical "splash" when catching fish.
But when I try to blindly tap on the flood, you can catch something from time to time ...

**Expected behaviour:**

The sound should sound, indicating the fish on the hook.

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. c2d61e05cf3d 2018-06-29 22:38:38 +0200 (master branch) (Win32, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:** Windows 10

**Comment by shamage** [comment]
I confirm that fishing really works, but there is a lack of "splash" that says something was caught on the rod.

TrinityCore rev. c2d61e05cf3d 2018-06-29 22:38:38 +0200 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.0.2o  27 Mar 2018 (library: OpenSSL 1.0.2o  27 Mar 2018)
Using Boost version: 1.67.0
Using MySQL version: 5.7.21
Using CMake version: 3.11.1
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 900650049 bytes
vmaps directory located in ./vmaps. Total size: 5127494765 bytes
mmaps directory located in ./mmaps. Total size: 6432765312 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 735.00

**Comment by chazh** [comment]
This is still an issue as of 6/16/2019 on version master (Sha:  eef87a9cc06bea80b9867491e126c6500dc608a9) client version 8.1.5.30706 and Database TDB_full_735.00_2018_02_19 ( hotfixes from master)

**Expected behaviour:**
The bobber does not play the splash animation as well.

Is there anyone working on this? If not, I would like to take a stab at it and see what i can find out. I am guessing its something to due with either the timing or the message packet being sent back to the client.
