### ISSUE TITLE
[boss] Bug Azgalor !

### ISSUE THREAD

**Issue by Hir0shi** [TrinityCore/TrinityCore#22308]
full buged boss azgalor

https://www.wowhead.com/npc=17842/azgalor

windows: 2008

version: d2d9f47

**Comment by Faq** [comment]
Such reports without minimal info should be just closed.

**Comment by illfated** [comment]
@Hir0shi : if you want this issue to be kept open, you need to add back the missing issue template lines from https://github.com/TrinityCore/TrinityCore/issues/new (open the link in a new browser tab), copy & paste and then fill in more information, like what kind of "bug" you are talking about and what the expected behaviour should be.
