### ISSUE TITLE
[3.3.5] Core/Spells: "Distract" should interrupt player spellcasts

### ISSUE THREAD

**Issue by diegobfl** [TrinityCore/TrinityCore#22334]
**Description:**

Rogue Spell [Distrac] does not work correctly.

**Current behavior:**

When the spell is cast on the target, it turns player correctly, but if the spell is casting a spell it does not cancel the spell

**Expected behavior:**

When using the spell, and the target casting a spell he should cut off the spell

**Steps to reproduce the problem:**

Throw the magic at the target [player] it will turn and if it is casting a spell it has to cancel the release

Subsidiary (s):

3.3.5

TC rev. hash / commit:

Rev TC da21ca8

Operational system:

Win 8 R2

**Comment by Killyana** [comment]
If you're talking about https://woehead.way-of-elendil.fr/?spell=1725 it works only against npcs that are not in combat, an it doesn't interrupt spells.

**Comment by Killyana** [comment]
Distract is not an interrupt in the way that kick is, but...

If you distract a caster who is out of combat so that they are facing away from the target they are casting toward, it will interrupt their spell(if it is a projectile attack)

If you distract an eating or drinking target, they will stand up and lose the food/drink(not sure if this has been changed)
