### ISSUE TITLE
Paladin Hand of Reckoning not dealing damage.

### ISSUE THREAD

**Issue by WOW-Reborn** [TrinityCore/TrinityCore#22353]
**Description:**

Paladin spell Hand of Reckoning is no longer dealing damage

**Current behaviour:**

Paladin spell Hand of Reckoning is no longer dealing damage since server update. It taunts but doesn't do damage.

**Expected behaviour:**

Should be doing damage.

**Steps to reproduce the problem:**

Use hand of reckoning on a mob as a paladin.  It will taunt the mob but will not do any damage to it.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

8e4f6777a28ac7b5d59ff1ff852e5184d877ff96

**Operating system:** 

Windows Server 2016

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/1315

**Comment by WOW-Reborn** [comment]
This is not a Dup.  this spell was working fine a few days ago now its not after the updates.  Does anyone at TrinityCore even verify things anymore or is it always just a quick Close thread post

**Comment by WOW-Reborn** [comment]
[Core / Spell] Hand Of Reckoning no damage when taunting players pet #9068
This is in regards to the player pet while using the spell.  This spell used to issue damage out to mobs that you used it on, then when I done my recent updates now It no longer does.  This isn't the same situation as #9068.

**Comment by Killyana** [comment]
I linked this issue not the 9068

**Comment by illfated** [comment]
Should issue #1315 be expanded to include "Paladin spell Hand of Reckoning does not do any damage at all" ?
The way I read issue 1315 is that it only appears as a problem when hitting fleeing mobs.

BTW, I don't know the paladin class enough to be sure if that is the only scenario when Hand of Reckoning is used in the first place.

**Comment by tarwyn** [comment]
I support illfated suggestion. The spell is currently broken because it's not doing any damage AT ALL.

What Hand of Reckoning should do:
- apply a taunt
- apply damage if the target is not currently attacking the caster

What it does:
- apply a taunt

The current implementation does not work IMO because it is based on threat and not on targets. 

A possible fix could be:
```
    if (effectHandleMode == SPELL_EFFECT_HANDLE_HIT)
    {
        if (!unitCaster)
            return;

        // Hand of Reckoning
        if (m_spellInfo->Id == 62124)
        {
            if (!m_targets.GetUnitTarget() || m_targets.GetUnitTarget()->GetTarget() != unitCaster->GetGUID())
                unitCaster->CastSpell(nullptr, 67485, true);
        }

        return;
    }

```
This goes before anything else in Spell::EffectTaunt, while the original implementation (2 lines) in there for Hand of Reckoning can be removed. I am none to familiar with the coding conventions for TC so I am sure the maintainers can come up with a proper fix.
