### ISSUE TITLE
Hozzer

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#22487]
**Description:**
https://www.wowhead.com/npc=24547/hozzer

![wowscrnshot_092118_185914](https://user-images.githubusercontent.com/16745918/45911450-bb6b0380-bdd0-11e8-86a6-5a22947cfccc.jpg)

**Current behaviour:**
Hozzer is below the ground and he isn't asleep. He _appears_ to be standing under the "bridge" and when you agro him he will sometimes pops up above (where he should be) and runs down the path around the bend to attack you (because he is technically supposed to be on the upper level).

**Expected behaviour:**
Hozzer should be above the ground and should be asleep unless you attack "Mad" Jonah Sterling.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 6490408d4ef5 2018-09-20 03:03:00 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.66.0
Using MySQL version: 5.5.38
Using CMake version: 3.12.0
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Operating system:** Windows 10 Pro

**Comment by illfated** [comment]
TrinityCore rev. 28a91300eb9c 2018-09-22 04:56:39 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Confirmed, Hozzer is standing instead of sleeping and is hostile by default instead of neutral.
Should only wake up and become hostile when "Mad" Jonah Sterling is low on health and wakes him up.
- https://www.wowhead.com/npc=24547/hozzer#comments:id=373747
- https://www.wowhead.com/npc=24547/hozzer#comments:id=669894
- https://www.wowhead.com/npc=24547/hozzer#comments:id=836117

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/23483
