### ISSUE TITLE
Brewfest: Glodrak Huntsniper

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22493]
**Description:**
Glodrak Huntsniper (npc=24657) should give an option to obtain Synthebrew Goggles (item=46735) but instead, his gossip option is: `Here's a gold, buy yourself something nice.`
And when you use it, it says something like `Are you sure you want to bribe Olga?`

Since the alliance version of this NPC works perfectly, I noticed the difference in the field `gossip_menu_id` and this is what I did:
```UPDATE `world`.`creature_template` SET `gossip_menu_id`='9006' WHERE `entry`='24657';```

It worked for me. I hope this is useful.

Branch: 3.3.5
TC Rev: ce46a0d53c3dbd6d2837020686e3880d98c545ed
OS: Windows 8.1 / Debian 9

**Comment by illfated** [comment]
Couple of tips regarding SQL codestyle: TC will not use any DB prefix like `world.` because user databases may be named differently than just `auth` / `characters` / `world`. DB name is omitted for that reason. (Myself, I use 335_auth/335_characters/335_world .)

To highlight code syntax in GitHub Flavored MarkDown, use **```sql** for SQL syntax and cpp, diff etc. for other types of content (you may want to look this up in the github MarkDown pages).

Your suggested fix could look something like this:
```sql
-- set main gossip ID for Glodrak Huntsniper
UPDATE `creature_template` SET `gossip_menu_id`= 9006 WHERE `entry`= 24657;
```
And BTW: TC SQL codestyle requires that no quotation marks ( ' ) are used around integers or number values. Use them for text values only.

**Comment by TheWinchesters** [comment]
Thanks a lot illfated.
I am learning something new everyday :smiley:
