### ISSUE TITLE
[3.3.5] Atal'alarion despawns immediately after he's killed.

### ISSUE THREAD

**Issue by TerrorBringer** [TrinityCore/TrinityCore#22531]
**Description:**

https://www.wowhead.com/npc=8580/atalalarion despawns 5 seconds after someone kills him, which means you cannot loot him and cannot complete the horde druid and paladin class quest. All the statutes are working.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

151ed6f

**Operating system:** 

Win 10 x64

**Comment by illfated** [comment]
TrinityCore rev. ab3eab990eb0 2018-09-27 20:59:48 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Confirmed. After being killed, Atal'alarion (entry 8580) despawns in less than 10 seconds (7.2 seconds, I presume).
I was able to loot 1 of 2 visible items (money), but could not loot the blue (rare) item because he despawned while looting.

Maybe this could have something to do with the `TEMPSUMMON_CORPSE_TIMED_DESPAWN` timing:
https://github.com/TrinityCore/TrinityCore/blob/ab3eab990eb01e6209b8527b98ef169136f81a24/src/server/scripts/EasternKingdoms/SunkenTemple/instance_sunken_temple.cpp#L190
I suspect that either
A) the author thought `TEMPSUMMON_CORPSE_TIMED_DESPAWN, 7200` would mean 7200 seconds (= 2 hours), or
B) many years ago 7200 used to mean 7200 seconds (and not milliseconds) in the TrinityCore source code.

Compare that idea with the following lines of code:
https://github.com/TrinityCore/TrinityCore/blob/ab3eab990eb01e6209b8527b98ef169136f81a24/src/server/scripts/Outland/Auchindoun/ManaTombs/boss_nexusprince_shaffar.cpp#L94-L96
The despawn time here is 1000x longer (2 hours), like a boss despawn timer in a big dungeon.

**Suggested solution:**
```diff
diff --git a/src/server/scripts/EasternKingdoms/SunkenTemple/instance_sunken_temple.cpp b/src/server/scripts/EasternKingdoms/SunkenTemple/instance_sunken_temple.cpp
index e760684949..0ed8deaf14 100644
--- a/src/server/scripts/EasternKingdoms/SunkenTemple/instance_sunken_temple.cpp
+++ b/src/server/scripts/EasternKingdoms/SunkenTemple/instance_sunken_temple.cpp
@@ -185,11 +185,11 @@ public:
         void UseLastStatue(GameObject* go)
         {
             for (uint8 i = 0; i < nStatues; ++i)
                 go->SummonGameObject(GO_ATALAI_LIGHT2, statuePositions[i], QuaternionData(), 0);
 
-            go->SummonCreature(NPC_ATALALARION, atalalarianPos, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 7200);
+            go->SummonCreature(NPC_ATALALARION, atalalarianPos, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 7200000);
         }
 
          void SetData(uint32 type, uint32 data) override
          {
             if (type == EVENT_STATE)
```
As you can imagine, it worked pretty well. I did not have patience to hang around for more than 10 minutes.
I don't have sniffs for the timing. When I left the instance and got back 15 minutes later, he was despawned.

@DanVS : is it practical to use Chrono Literals here? Or is this a different type of function?

**Comment by illfated** [comment]
I could easily make a PR for the suggested solution above (even if it is a very small change), but I would prefer more feedback from real coders first, to find out if there are better ways of achieving the same result.

**Comment by illfated** [comment]
Very well. I will test that right now. I presume "soft reset" means that corpses despawn, but no respawns happen, because those few mobs I killed (elite & normal) had not re-spawned during that time.

**Comment by offl** [comment]
You don't have to wait 2 hours, simply change the timer to 1 minute

**Comment by illfated** [comment]
OK, so I tested now and I only achieved to make his corpse despawn at the same rate as regular elite NPC corpses:
```
Looted state: despawned after 2 minutes 30 seconds (180 seconds)
-- identical to other looted elite mobs. Tested 3 times.
unlooted st.: despawn after 5 minutes (300 seconds)
-- same as the 3 elites in the pit, killed in the same AoE attack
```
So, is this a correct despawn timer, or should he despawn according to Boss criteria?

**Comment by DanVS** [comment]
@illfated, seems to me that it is not possible here (according to [Map.h](https://github.com/TrinityCore/TrinityCore/blob/738f37d3cf45d4e10eda9d44a4cb17079b7bbc1b/src/server/game/Maps/Map.h#L448)).

**Comment by illfated** [comment]
Fair enough. Do you have a suggestion for what would be the most correct value in that `TEMPSUMMON_CORPSE_TIMED_DESPAWN` timer? Existing value x1000, or `5 * 60 * 1000 (milliseconds)` ?

**Comment by illfated** [comment]
Well, so I tested again with a minimal change based on commit https://github.com/TrinityCore/TrinityCore/commit/bbb868cc8686d4feb31cde2944f931625994fadf :
```patch
diff --git a/src/server/scripts/EasternKingdoms/SunkenTemple/instance_sunken_temple.cpp b/src/server/scripts/EasternKingdoms/SunkenTemple/instance_sunken_temple.cpp
index e760684949..bd7b0223ef 100644
--- a/src/server/scripts/EasternKingdoms/SunkenTemple/instance_sunken_temple.cpp
+++ b/src/server/scripts/EasternKingdoms/SunkenTemple/instance_sunken_temple.cpp
@@ -185,11 +185,11 @@ public:
         void UseLastStatue(GameObject* go)
         {
             for (uint8 i = 0; i < nStatues; ++i)
                 go->SummonGameObject(GO_ATALAI_LIGHT2, statuePositions[i], QuaternionData(), 0);
 
-            go->SummonCreature(NPC_ATALALARION, atalalarianPos, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 7200);
+            go->SummonCreature(NPC_ATALALARION, atalalarianPos, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 600000);
         }
 
          void SetData(uint32 type, uint32 data) override
          {
             if (type == EVENT_STATE)
```
This time I tested if 10 minutes (600000 ms) would affect the time he stays summoned, but it doesn't.
The actual problem is that it does not increase the despawn time above default Elite NPC despawn
(5 minutes unlooted/2 minutes 30 seconds after looting).

Oh well. I will open a Pull Request just to solve this particular issue and look into boss despawn timers later.
