### ISSUE TITLE
[Pit of Saron] Krick's Pursuit ability

### ISSUE THREAD

**Issue by wonopon** [TrinityCore/TrinityCore#2261]
Pit of Saron : (http://old.wowhead.com/zone=4813)
Krick : (http://old.wowhead.com/npc=36477)
Ick : http://old.wowhead.com/npc=36476)
Pursuit : (http://old.wowhead.com/spell=68987)

Pursuit is cast at all members of the party. Ick doesn't begin chasing anyone. The fight goes on as normal. Broken spell, please review this. Thank you :D
##

**Comment by AshaX** [comment]
problem is still keep or fixed?

**Comment by tkrokli** [comment]
> problem is still keep or fixed?

Not sure if it is a problem. I would think that the reason the [[Pursuit]](http://www.wowhead.com/spell=68987) spell is cast on all players could be because Ick will target a random player from all members of the group. I also think that the title of this issue could be misleading, because both [[Pursuit]](http://wotlk.openwow.com/spell=68987) and [[Pursuit Confusion]](http://www.wowhead.com/spell=69029/pursuit-confusion) are listed as Ick's abilities:
- Pursuit spell: http://wotlk.openwow.com/spell=68987 -- Used by (2):
- Ick, normal mode: http://wotlk.openwow.com/npc=36476
- Ick, Hc or 25 Man: http://wotlk.openwow.com/npc=37627
- Pursuit Confusion: http://wotlk.openwow.com/spell=69029 (Triggered by [spell 68987](http://wotlk.openwow.com/spell=68987))

(Note: wowhead lists only 1 version of Krick and Ick, maybe they got changed in later expansions.)

Maybe it's just me, but I find it slightly confusing that the creature script https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/FrozenHalls/PitOfSaron/boss_krickandick.cpp refers to Krick as the ability owner, but maybe it has got something to do with Ick being `<Krick's Minion>`.
- Krick, normal mode: http://wotlk.openwow.com/npc=36477
- Krick, Hc or 25 Man: http://wotlk.openwow.com/npc=37629

You should test it and see for yourself on current source. I don't know what the status is now.
