### ISSUE TITLE
[3.3.5] Player position after bg/instance ends

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22859]
**Description:**
When the player is mounted on a vehicle inside a instance or battleground, if the battleground ends or the player gets expelled of the instance, the players appears in the zone that corresponds to .go xyz 0 0 0 (MapId of the map where the player was before entering the bg/instance).
Once in that zone, using .gm fly on and .gps every 2 seconds, the .gps command will show that the character is "moving" throught maps but if you press "m", you will see the character in the same place.
Once the player die (fatigue or falling), he/she will appear in the zone that should have been sent in first place.

**Steps to reproduce the problem:**
1. Go to Ulduar instance and mount a vehicle or go to Strand of the Ancients and mount a cannon
2. Stay mounted till bg closes or the instance expells you because "You are not in a group".

**Branch(es):** 3.3.5
**TC rev. hash/commit:** df641e993ac4e058c55ec97cceb19cf397a51105
**Operating system:** Win 8.1

**Comment by Langerz82** [comment]
This is for my reference:
To get to cannons:
1. .go xyz -735 -170 430 603
Zone: 4273

**Comment by jackpoz** [comment]
Confirmed on 24fbbee4b9af7b5226772378dd83b78c103d969d when doing .tele gmisland while mounted on a dragon inside The Oculus

**Comment by Killyana** [comment]
Looks to be related to https://github.com/TrinityCore/TrinityCore/issues/23384
When the player cast the spll to ride the vehicle it will be teleport to 0,0,0 and the waypoint starts from there, even if it's not visible in client side.

**Comment by Astrono1293** [comment]
confirmed

**Comment by jackpoz** [comment]
Fun fact: in my case with .tele gmisland, the player is actually teleported to gmisland in the first place (while debugging I saw my character was there until MSG_MOVE_TELEPORT_ACK

**Comment by jackpoz** [comment]
@ccrs this is caused by GenericMovementGenerator being initialized after teleporting to another map while mounted on a vehicle using the spline of vehicle ejection from the previous map.
Callstack:
> 	worldserver.exe!Movement::MoveSplineInit::Launch() Line 61	C++
	worldserver.exe!GenericMovementGenerator::Initialize(Unit * __formal) Line 45	C++
 	worldserver.exe!MotionMaster::Update(unsigned int diff) Line 292	C++
 	worldserver.exe!Unit::Update(unsigned int p_time) Line 456	C++
 	worldserver.exe!Player::Update(unsigned int p_time) Line 1044	C++
 	worldserver.exe!Map::Update(unsigned int t_diff) Line 791	C++
 	worldserver.exe!MapUpdateRequest::call() Line 43	C++
 	worldserver.exe!MapUpdater::WorkerThread() Line 115	C++

Values:
>_splineInit.args.path[0]
{x=0.000000000 y=0.000000000 z=0.000000000 }
    x: 0.000000000
    y: 0.000000000
    z: 0.000000000
_splineInit.args.path[1]
{x=943.350403 y=1047.36011 z=374.211792 }
    x: 943.350403
    y: 1047.36011
    z: 374.211792

path[0] is set to current position in MoveSplineInit::Launch()
>args.path[0]
{x=16226.2002 y=16257.0000 z=13.2021999 }
    x: 16226.2002
    y: 16257.0000
    z: 13.2021999

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/72fc79a9e63d77754699a3da90d81219b2defb0d
