### ISSUE TITLE
worldserver memory leak soap service!

### ISSUE THREAD

**Issue by Hir0shi** [TrinityCore/TrinityCore#22934]
Description:
1. enable soap service on worldserver.conf
2. start worldserver
3. restart or shutdown worldserver
4. After two or three minutes start, worldserver
5. error acceptor soap port is ready use ! worldserver can't to started

tested on linux.

Branch(es): 3.3.5
TC rev. hash/commit:
https://github.com/TrinityCore/TrinityCore/commit/57d7b194522d6d44f4d2e9400c03cfc13d5a706a

**Comment by Aokromes** [comment]
#20032

**Comment by Hir0shi** [comment]
You So Bad Aokromes !

**Comment by Hir0shi** [comment]
StartNetwork failed to bind socket acceptor
Failed to initialize network
Couldn't bind to 0.0.0.0:7878
terminate called without an active exception
Segmentation fault (core dumped)

Freeze worldserver.

**Comment by illfated** [comment]
@Hir0shi : That error message & log is already discussed in issue **#20032** [**StartNetwork failed to bind socket acceptor**](https://github.com/TrinityCore/TrinityCore/issues/20032)
That is why Aokromes closed this issue, because we already have got an open issue for this kind of error.
(Also known as "Duplicate issue" -- we do not want duplicate issues open unless important details are different.)
Please post in issue **#20032** **StartNetwork failed to bind socket acceptor** to keep us updated.

**Comment by Aokromes** [comment]
^^ And it was looked because this guy spamming on it.
