### ISSUE TITLE
Creature/script: High Priestess Mar'li

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#22974]
**Description:** This boss https://www.wowhead.com/npc=14510/high-priestess-marli must hatch spider eggs https://www.wowhead.com/object=179985/spider-egg that summon a spider.

In the current script the spider is summoned manually:
if (Creature* spider = me->SummonCreature(NPC_SPIDER, target->GetPositionX(), target->GetPositionY(), target->GetPositionZ(), 0, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 15000))

Spell that must be used to hatch eggs: https://woehead.way-of-elendil.fr/?spell=24082

Hatched eggs must respawn after a wipe.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 813cf761fcf8

**Comment by offl** [comment]
Btw currently the EffectActivateObject effect is implemented incorrectly. Here's more proper implementation: https://github.com/cmangos/mangos-tbc/blob/d2d2043801eb103c660a5f84af4ed3ccd05d3b13/src/game/Spells/SpellEffects.cpp#L7491

**Comment by kuskmen** [comment]
@Killyana , can you tell how often must eggs be hatched, do they hatch only in human form and is there any reliable source that I can watch from in order to see the whole encounter?

**Comment by Killyana** [comment]
this 2 lines: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/ZulGurub/boss_marli.cpp#L127-L147

4 random eggs must be chosen and hatched instead summoning spiders.

**Comment by kuskmen** [comment]
I've been working on this issue last 2 days (first issue in the project please don't blame) and I think I am almost ready however one thing stops me from being ready. I can't make eggs respawn themselves on reset of encounter and discord hasn't been many helpful either.

> Hatched eggs must respawn after a wipe.

This is what I am trying

https://github.com/kuskmen/TrinityCore/commit/73207d653d2766c7517fde71e80a765f43569bff

Problem with this solution is that [here](https://github.com/kuskmen/TrinityCore/commit/73207d653d2766c7517fde71e80a765f43569bff#diff-7525493bbf35b11e4a0668f8109c8938R105) `_hatchedEggs` vector consists of invalid (default I assume) gameobjects rather than real eggs that I am adding [here](https://github.com/kuskmen/TrinityCore/commit/73207d653d2766c7517fde71e80a765f43569bff#diff-7525493bbf35b11e4a0668f8109c8938R115) and therefore respawn doesn't work in the reset phase.
It would be lovely if someone tell me how to keep state between events or where I am making mistake cause this is the last thing before this issue is fixed I think.

Thanks in advance,
kuskmen

**Comment by Killyana** [comment]
Open a PR you will get more help

**Comment by kuskmen** [comment]
@Killyana what about the spiders that are summoned during the encounter? Do they need to be despawned as well?

**Comment by Killyana** [comment]
Yes, when the boss evades
