### ISSUE TITLE
[3.3.5] Spells movement - Warrior's Charge launch visual while jumping backwards

### ISSUE THREAD

**Issue by Natureknight** [TrinityCore/TrinityCore#23059]
**Description:**

Warrior's Charge animation (**for players around, but not for the warrior itself**) get very weird sometimes. The problem is when the facing of the caster changes together with the launch of the charge movement, OR even more often, while jumping backwards and then immediately launching charge. This happens with intervene as well, and probably more spells like these.

**Current behaviour:**

The warrior appears like teleporting, the charge animation starts, then warrior moves about 2-3 yards forward, then gets back, and immediately teleported to the target after that.

**Expected behaviour:**

Charge animation should be smooth.

**Steps to reproduce the problem:**

1. Make Warrior
2. Make another character as target
3. Jump backwards and immediately press charge

Charge animation always looks smooth on the warrior's client, but very weird and broken on the target's client (this is not always happening, im using a macro to reproduce it easily:

> /cast charge
> /target player
> .cool
> /targetlasttarget

**Branch(es):**

3.3.5, not sure for other branches

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/43dec9e4d0b6f7da3c2051624742e9fb8a9bcb31

**Operating system:** Windows 10 x64

**Comment by Quadrall** [comment]
This is because when the user is charging, the server sends SMSG_ON_MONSTER_MOVE to surrounding players which creates the charge animation effect. Even though the user is charging, the user client still continues to send CMSG movement packets which of course the server processes and sends out to surrounding players - this overrides the SMSG_ON_MONSTER_MOVE animation thus creating a 'teleport' effect.

We shouldn't be sending any SMSG movement packets if the current user spline has not finished. 
We can add a check after here:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Handlers/MovementHandler.cpp#L293

To check if the player spline has not finished, if player spline has not finished then we don't process the movement packet.

I tested this on my local MoP revision, and the charge animation now correctly plays.

**Comment by illfated** [comment]
Even so, one of the reasons for opening a PR is to discuss the code and if it is used correctly.
Then again, if you don't feel strongly enough about it, I understand your choice of caution.

**Comment by Quadrall** [comment]
> Even so, one of the reasons for opening a PR is to discuss the code and if it is used correctly.
> Then again, if you don't feel strongly enough about it, I understand your choice of caution.

I'll open a PR later

**Comment by Natureknight** [comment]
```diff
@@ -290,10 +290,16 @@ void WorldSession::HandleMovementOpcodes(WorldPacket& recvData)
     {
         recvData.rfinish();                     // prevent warnings spam
         return;
     }
 
+    if (!mover->movespline->Finalized())
+    {
+        recvData.rfinish();                     // prevent warnings spam
+        return;
+    }
+
     /* handle special cases */
     if (movementInfo.HasMovementFlag(MOVEMENTFLAG_ONTRANSPORT))
     {
         // We were teleported, skip packets that were broadcast before teleport
         if (movementInfo.pos.GetExactDist2d(mover) > SIZE_OF_GRIDS)
```

**Comment by Quadrall** [comment]
> ```diff
> @@ -290,10 +290,16 @@ void WorldSession::HandleMovementOpcodes(WorldPacket& recvData)
>      {
>          recvData.rfinish();                     // prevent warnings spam
>          return;
>      }
>  
> +    if (!mover->movespline->Finalized())
> +    {
> +        recvData.rfinish();                     // prevent warnings spam
> +        return;
> +    }
> +
>      /* handle special cases */
>      if (movementInfo.HasMovementFlag(MOVEMENTFLAG_ONTRANSPORT))
>      {
>          // We were teleported, skip packets that were broadcast before teleport
>          if (movementInfo.pos.GetExactDist2d(mover) > SIZE_OF_GRIDS)
> ```

Forgot about opening a PR! Yes, that will fix the issue.
