### ISSUE TITLE
Core/Script: Extend SCRIPT_COMMAND_DESPAWN_SELF to Game Objects

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23067]
**Description:** We need SCRIPT_COMMAND_DESPAWN_SELF to be used also by game objects:

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Maps/MapScripts.cpp#L755-L759
``` sql
UPDATE `gameobject` SET `spawntimesecs`=240, `animprogress`=100 WHERE `id` IN (182196,182197,182198);
DELETE FROM `event_scripts` WHERE `id` IN (14592, 14593, 14595);
INSERT INTO `event_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `dataint`, `x`, `y`, `z`, `o`) VALUES
(14592, 2, 10, 22890, 240000, 0, -108.252,-510.302,21.4761,2.9688),
(14592, 0, 18, 0, 0, 0, 0,0,0,0),
(14593, 2, 10, 22891, 240000, 0, 19.6039,-304.914,-66.1715,3.4178),
(14593, 0, 18, 0, 0, 0, 0,0,0,0),
(14595, 2, 10, 22892, 240000, 0, 320.304,-21.8057,22.4412,2.0042),
(14595, 0, 18, 0, 0, 0, 0,0,0,0);
```
.quest add 9832
.go game 11322

Once the gob despawn it must respawn after `spawntimesecs`=240 secs without calling any extra action
**Branch(es): both

**TC rev. hash/commit:** rev. c10c8c6bba27

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/da19ad117e3c4c15793ba8f84738efaecb4d1428

it might be better to add a function that tries to use Creature or GameObject and logs an error only if it doesn't find any, since right now it logs an error about "neither source nor target are creatures, skipping" but then it actually continues trying with the GameObject. For now it will be like this.
