### ISSUE TITLE
Bug in Ulduar - Yoggsaron  does not reset.

### ISSUE THREAD

**Issue by aifirst** [TrinityCore/TrinityCore#23293]
**Description:**
Yoggsaron does not reset after player killed by mind control.

**Current behaviour:**
After player killed by mind control in battle with Yoggsaron, Yoggsaron does not reset.
20~30 minutes after, Yoggsaron will be reset.

**Expected behaviour:**
After player was killed by mind control, Yoggsaron must be reset soon.

**Steps to reproduce the problem:**
Do single play.
Combat with yoggsaron
Player is killed by mind control.
Yoggsaron does not reset. 
Player cannot reenter dungeon. 
If player use gm mode, player can reenter dungeon(and can see Yoggsaron which not resetted).
20~30 minutes after, Yoggsaron will be reset.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
386b5a6f (2019/04/13)

**Operating system:** Windows 10

**Comment by illfated** [comment]
Although I don't know if changes applied to TC source during the last month will improve your issue, I would like to recommend updating to a newer core revision (unless you have noticed something has broken which you need to be working). Reporting issues on cores 1 month old or older can make it more difficult to know what causes your issue at the current revision (unless it is limited to scripts which have not changed during this time).

Even so, I assume your issue is about core combat state / combat handling as well as boss reset issues, which can change whenever movement or scripting changes are applied to the core part of the source.

**Comment by Killyana** [comment]
Duplicates of https://github.com/TrinityCore/TrinityCore/issues/16723
