### ISSUE TITLE
Core/GameObjects: Spells cast by gameobjects doesn't have visuals

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23301]
**Description:** When a gameobject cast a spell with a visual, like spell= 9056 the visual is not displayed (in this case the light)

**Steps to reproduce the problem:**

1. use this sql https://github.com/TrinityCore/TrinityCore/issues/6388#issuecomment-491542050
2. .quest add 1948
3. .go game 99869
4. .add 7273 10
5. use Witherbark Totem Sticks and wait 10 secs
6. The spell 9056  will be cast by the gob but the light animation is not displayed

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 534348797f65

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** CHANGEME OS

**Comment by xvwyh** [comment]
I dug into the client, and turns out it's not the server's fault. Apparently the only case in which GO-cast spells will display ground visuals, is if the spell's visual has ImpactAreaKit. The spell in question only has InstantAreaKit, and that one only works if there is a unit caster. CastKit also only works on units.

Either in older clients the code was different, or the lightning visual never actually was visible.

<details>
<summary>Random investigation</summary>

I also checked alpha client's code. It already has support for GO-cast spell visuals. But just like in 3.3.5 client, apart from playing ImpactKit on all affected targets, it only attempts to play a certain `SpellVisualRec::m_areaModel` at ground target. Now, alpha's SpellVisual.dbc contains two columns side-by-side - `m_areaModel` and `m_areaKit`. I dunno what `m_areaModel` references, but in 3.3.5 all the "area" columns are now references to SpellVisualKit, and if you compare SpellVisual data between alpha and 3.3.5, sadly, all the records that had `m_areaModel` and `m_areaKit` in alpha now contain SpellVisualKit references around ID 9160, so I assume some kind of a conversion process once took place. And the saddest part is - these references are seemingly randomly in either InstantAreaKit or ImpactAreaKit columns without any sort of pattern that could give us a clue which alpha columns got converted into which 3.3.5 columns.

But regardless, it's not the server's fault, but rather either this particular spell's designer's misake, or a bug in client code that appeared as development went on.
</details>

**Comment by Kittnz** [comment]
So dbc needs to be modified ?

**Comment by Shauren** [comment]
You would need to do this modification on client side
