### ISSUE TITLE
Spell Bug [Blast Wave]

### ISSUE THREAD

**Issue by Hir0shi** [TrinityCore/TrinityCore#23328]
Description: Mage Class Spell [Blast Wave] Buged , throw !

A wave of flame radiates outward from the caster, damaging all enemies caught within the blast for 277 to 330 Fire damage, knocking them back and dazing them for 6sec.

https://wotlk-twinhead.twinstar.cz/?spell=13019

Branch(es):

3.3.5

TC rev. hash/commit:
https://github.com/TrinityCore/TrinityCore/commit/64dabaad8007f632388f6147a24cacd453a365fc

Operating system:
Windows 2016

**Comment by Hir0shi** [comment]
why are you laughing ?!

**Comment by MaxtorCoder** [comment]
Maybe would be best to explain the current behaviour + how to reproduce ;)

**Comment by Hir0shi** [comment]
@Killyana  please test this server is bug ! [Blast Wave]

**Comment by Riztazz** [comment]
Jesus dude, use a google translate at least. Noone can understand anything you write

**Comment by illfated** [comment]
Like MaxtorCoder said, please tell us what the current behaviour is and how to replicate the bug.
It looks like you only have described the expected result in your issue post.
There is a good reason why the TC issue template contains all the lines you removed,
because we need more information than you have provided, in order to know what the actual problem is.
