### ISSUE TITLE
DBC storage uses undefined behavior

### ISSUE THREAD

**Issue by kelno** [TrinityCore/TrinityCore#23333]
DBC loading logic uses undefined behavior.
They load everything into stores with type `char**`

Like here:
https://github.com/TrinityCore/TrinityCore/blob/8bc5451864570c07eff6d427846335044f85a509/src/common/DataStores/DBCFileLoader.cpp#L214

And then store various types in it, doing pointers conversion like here:
https://github.com/TrinityCore/TrinityCore/blob/8bc5451864570c07eff6d427846335044f85a509/src/common/DataStores/DBCFileLoader.cpp#L235

But this is actually invalid because this violate pointer alignment. I've submitted the issue on stackoverflow here for some more details:
https://stackoverflow.com/questions/56386527/casting-and-writing-in-pointer-array-reports-misaligned-address-with-clang-sanit#comment99373050_56386527

(After a quick check, master branch seems to have the same issue)

**Comment by jackpoz** [comment]
Please note the SO answer:
>You cannot cast an **arbitrary** char* to uint32_t*, even if it points to an array large enough to hold a uint32_t.
That means that an arbitrary char* is unlikely to be aligned properly for a uint32_t.

The data loaded from DBCs is not arbitrary, it's well defined data. There is nothing unsure, "unlikely" doesn't apply as this is exactly how the data is stored and it's how the data should be read.

This is possible due to https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/shared/DataStores/DBCStructure.h#L30 which forces the alignment to 1 byte, having no padding bytes (while the default platform-specific alignment would create padding if storing a char and then a uint64.
https://docs.microsoft.com/en-us/cpp/preprocessor/pack?view=vs-2019
https://gcc.gnu.org/onlinedocs/gcc-4.4.4/gcc/Structure_002dPacking-Pragmas.html

**Comment by Shauren** [comment]
This is about alignment, not padding

Either way, this is a non-issue because we only support x86/x64 cpus where accessing non-aligned uint32* is not a problem

**Comment by kelno** [comment]
Very well thanks for clarifications
