### ISSUE TITLE
[3.3.5] Different displayID after taming NPC 2926

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#23353]
**Description:**
NPC 2926 is a white/grey wolf that can be tamed by Hunters.

**Current behaviour:**
The color of this NPC changes once is tamed and the player changes map.
So, the hunter gets a black wolf pet after taming a white/grey wolf.
NPC 2926 has modelid1 9562 (black wolf) in creature_template table and modelid 11418 (white/grey wolf) in creature table.

**Expected behaviour:**
Not sure which modelid should be the right one once the NPC is tamed.

**Steps to reproduce the problem:**
1. go c id 2926
2. learn 1515 or npc tame
3. tele gmisland

**Branch(es):** 3.3.5
**TC rev. hash/commit:** b64583b7c14da408b34d2c92a02e5529594ef181
**Operating system:** Win 8.1

**Comment by Killyana** [comment]
The model of the npc: DisplayID: 11418 (Native: 11418).
The model of the pet once timed: DisplayID: 11418 (Native: 9562).
The model of the pet when it changes to blak: DisplayID: 9562 (Native: 9562).

**Comment by illfated** [comment]
Maybe this could have something to do with it?
https://wow.gamepedia.com/Silvermane_Stalker

**Patch changes**
![Wrath-Logo-Small 1](https://user-images.githubusercontent.com/38162891/58821163-c4d18e80-8634-11e9-9ac7-797c5ca8bef9.png)  **[Patch 3.2.0](https://wow.gamepedia.com/Patch_3.2.0) (2009-08-04):** _Undocumented_: These stalkers no longer stealth, to make finding them a lot easier, however they are black instead of grey as well.

**Comment by Killyana** [comment]
No the color of the npc is gray https://www.wowhead.com/quest=26223/stalking-the-stalkers#videos:id=51753 it doesn't make sense to change it in black as the name is Silvermane Stalker

**Comment by illfated** [comment]
Fair enough. According to the wowhead page, there was a change during WoTLK 3.3 and again in Cataclysm in 2011:
- https://www.wowhead.com/npc=2926/silvermane-stalker#screenshots
- https://www.wowhead.com/npc=2926/silvermane-stalker#comments

**Comment by Killyana** [comment]
The model 11418 is forced in creature table the npc has the model 9562 in creature_template so it makes sense that the pet turns black.
