### ISSUE TITLE
Using compiled binaries as a portable version

### ISSUE THREAD

**Issue by IranDeveloper** [TrinityCore/TrinityCore#23364]
**Description:**

I compiled the 3.3.5 branch successfully and got no errors. now I want to use this compiled binaries on other pc as a game server. when I run worldserver.exe I got this error :
database auth is empty. auto populating it ...
>> Base file D:/Trinity/sql/base/auth_database.sql is missing. try to fix it by cloning source code again ...
In the PC, I'm compiling the source code my source directory is on D drive and when I run compiled binary the addresses are fixed and refer to D drive.
finally, I want to use it on different devices, what should I do for having a portable version?
such as others like Jeuties Repack.
**Branch(es):**

3.3.5

**Operating system:** Compiled on Windows 10, Use on Windows 7

**Comment by illfated** [comment]
`Base file D:/Trinity/sql/base/auth_database.sql` is part of the source (cloned repository). If it is not placed in `D:/Trinity/` you either need to compile the core again on the other computer, or clone the source to `D:/Trinity/` on the new computer where you want to build the new DB. (This is default behaviour for TrinityCore, regardless of Windows or Linux, so it is not an issue at all.) Please note that this ticket will be closed, because it is not an issue with the source at all, and that you need to find out how you want to make the source files available to the core if you decide to run it on a different computer from where you compiled it.

Your problem is basic setup for TrinityCore source & servers, so it does not belong in the issue tracker.
Please use the Forum pages or IRC to ask for help with your setup.

**Comment by jackpoz** [comment]
If you are using the automatic database importer and updater, than you need to build and run TC on the same machine.
If you want to run it on a different machine then you probably need to disable the automatic database importer/updater and run those SQL scripts manually (but that will cause a whole set of new issues)

**Comment by Jinnaix** [comment]
I compile on my private computer and run the server on my vServer with automatic database updater.
It works because i clone the git repo on my vServer too and point to it in the worldserver config.

**Comment by IranDeveloper** [comment]
I just edit authserver.conf Line 156 : SourceDirectory  = ""
Thanks all.
