### ISSUE TITLE
Core/Creature: Creatures cannot add more than one unit to the threat list via los

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23368]
**Description:** In the case where we have 2 groups of npcs fighting each other if there's no aoe or multiple target spell involved, when a npc kill its target it will evade instead of acquiring a new one.
I'm not sure about the retail behavior or if the creature must add multiple unit to the threat list at los.

**Steps to reproduce the problem:**

1. .go c 79409  (with gm on)
2. notice the behavior of  the 4 Arcatraz Defenders
3. when they aggro they will add only on unit to the threat list (You can see that with Omen)
4. once this unit is killed they will evade, then acquire again a single target ect...

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. bb60122f2c0a

**Comment by Wyrserth** [comment]
I recall this was a nasty way to get people killed, the famous mob train. You aggro a mob and run away, when the mob leashes back it looks for nearby potential targets instead of evading straight away. So you could "train" a mob to another player and make it attack them.

Don't have any video or article at hand though, just my memory. Sorry.

**Comment by Killyana** [comment]
I don't think creature adds hostile unit via los if already in combat, I saw similar behavior in classic beta.
