### ISSUE TITLE
Achievements [Friend or Fowl?]

### ISSUE THREAD

**Issue by Astrono1293** [TrinityCore/TrinityCore#23387]
**Describe the bug**
The process doesn't count the amount of killed turkeys you do.

**To Reproduce**

Howling Fjord
Start killing turkeys.
Even if you killed 50 under 3 minutes, the achievement wont be marked as completed for some reason. I see that this issue was marked and solved but it still doesnt work.

**Expected behavior**
After killing 15 turkeys in 3 minutes, You gain the achievement: [Friend or Fowl?]

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
4051d4c61e5292d2c6a9fefd316d246cb72ac4e8

**Comment by kuskmen** [comment]
Just for the sake of testing and completeness, can you try to kill 15(or more) under 3 minutes, the moment you do quickly logout and login and check if achievement progress is completed?

I remember playing on servers which had this behaviour, but I don't know if they were based on Trinity or not so I want to make sure if Trinity has the same "Feature" like they did.

**Comment by Killyana** [comment]
The aura id: 25281 is not stacking jusst a new one is added
``` 
id: 25281 [Marqueur de dinde] effmask: 1 charges: 0 stack: 1 slot 0 duration: 109733 maxduration: 180000   caster: creature guid: 2330
id: 25281 [Marqueur de dinde] effmask: 1 charges: 0 stack: 1 slot 1 duration: 118787 maxduration: 180000   caster: creature guid: 2325
id: 25281 [Marqueur de dinde] effmask: 1 charges: 0 stack: 1 slot 2 duration: 137285 maxduration: 180000   caster: creature guid: 2324
id: 25281 [Marqueur de dinde] effmask: 1 charges: 0 stack: 1 slot 3 duration: 150695 maxduration: 180000   caster: creature guid: 2862
id: 25281 [Marqueur de dinde] effmask: 1 charges: 0 stack: 1 slot 4 duration: 157130 maxduration: 180000   caster: creature guid: 2863
id: 25281 [Marqueur de dinde] effmask: 1 charges: 0 stack: 1 slot 5 duration: 167915 maxduration: 180000   caster: creature guid: 2878
id: 25281 [Marqueur de dinde] effmask: 1 charges: 0 stack: 1 slot 6 duration: 171567 maxduration: 180000   caster: creature guid: 2870

**Comment by Wyrserth** [comment]
One issue left with that achievement: the spell used to track turkeys killed should not refresh the duration every time it's applied (you get three minutes to kill all 15 turkeys, not three minutes between each kill).

**Comment by adeutscher** [comment]
The duration in from `.list auras` displays a refreshed duration when another turkey is killed, but the control of the stack count and the casting of the achievement-granting Turkey Vengeance spell goes off of a list of timestamps defined in the `spell_gen_turkey_marker` class. If the earliest logged turkey kill time came greater than the max duration ago (3min), then a stack is removed.

```cpp
void OnPeriodic(AuraEffect const* /*aurEff*/)
{
    if (_applyTimes.empty())
        return;

    // pop stack if it expired for us
    if (_applyTimes.front() + GetMaxDuration() < GameTime::GetGameTimeMS())
        ModStackAmount(-1, AURA_REMOVE_BY_EXPIRE);
}
```

That being said, I think there's a bit of a hiccup here with the aura. Since `_applyTimes` is never popped as the comment implies, that the current check floors out all stacks of the buff no matter how recent they are once the first one expires. For example, the following wouldn't currently grant the achievement, though I think that it should:

1. 0:00: Kill 3 turkeys (total 3)
2. 1:30: Kill 4 more turkeys (total 7)
3. 2:45-3:15: Observe the behavior of `.list auras`. When the first application expires, all 7 stacks will quickly drain away.
  * The expected outcome is that we have 4 stacks, and that we could get the achievement by killing 11 more turkeys before the 4 from 1:00 expire completely at 4:30

I've made a branch/PR that should solve this. Testing steps in the branch:

1. Spawn as many turkeys as you need: `.npc add temp 24746`
2. Confirm that GM mode is off.
3. Kill 3 turkeys, start timer. Observe stack count, should be 3.
4. At 1:30, kill 7 more turkeys. Observe stack count, should be 10.
5. Wait until 3:00. Observe stack count, should fall to 7 and stay there.
6. Before 4:30, kill 7 more turkeys. Observe stack count, should be 14.
7. Before 4:30, kill 1 more turkey. This brings us to 15, spawning angry turkeys and granting the achievement.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/pull/24048
