### ISSUE TITLE
Core/SAI: Moving `spell_scripts` & `event_scripts` & `waypoint_scripts` To SAI

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23414]
**Description:**   `spell_scripts` & `event_scripts` & `waypoint_scripts` have a poor scripting engine, it lacks event, actions and targets.

We need to move this 3 tables to SAI with new source type:

SMART_SCRIPT_TYPE_SPELL=         6 (event_type= Effect_ID)
SMART_SCRIPT_TYPE_EVENT=        3 (SMART_EVENT_TRIGGERED=78)
SMART_SCRIPT_TYPE_WAYPOINT= 10  (event_type= Point_ID)

**TC rev. hash/commit:** rev. a1b2aa97fcb6

**Comment by Rushor** [comment]
most SMART_SCRIPT_TYPE_EVENT are used in gameobjects and can be converted to sai already

**Comment by dr-j** [comment]
Yes but there’s spells which send event ID too as used by quest items to start quest events etc

**Comment by dr-j** [comment]
We should probably also update some sai scripts to use event inform instead of state changed to trigger events

Type 3 Chest - Data6 = Loot event
~~~
entry - type - name - Data6
187027 - 3 - Cannonball - 16443
179828 - 3 - Dark Iron Pillow - 8540
17155 - 3 - Defias Gunpowder - 619
9630 - 3 - Flagongut's Fossil - 601
187026 - 3 - Long Tail Feather - 16442
187022 - 3 - Mound of Debris - 16440
179499 - 3 - Ogre Tannin Basket - 8175
187023 - 3 - Unlocked Chest - 16441~~~

Type 10 Goober Data 2  event id
~~~
entry - type - name - Data2
188463 - 10 - Anub'ar Mechanism - 17671
184999 - 10 - Auchenai Coffin - 14444
190618 - 10 - Blue Cauldron - 18684
188104 - 10 - Cart Release - 17451
164881 - 10 - Cleansed Night Dragon - 293
173325 - 10 - Cleansed Night Dragon - 4178
174609 - 10 - Cleansed Night Dragon - 4247
174685 - 10 - Cleansed Night Dragon - 4265
164882 - 10 - Cleansed Songflower - 4059
171940 - 10 - Cleansed Songflower - 4079
174610 - 10 - Cleansed Songflower - 4215
174612 - 10 - Cleansed Songflower - 4216
174613 - 10 - Cleansed Songflower - 4217
174614 - 10 - Cleansed Songflower - 4218
174615 - 10 - Cleansed Songflower - 4219
174714 - 10 - Cleansed Songflower - 4276
174715 - 10 - Cleansed Songflower - 4280
164883 - 10 - Cleansed Whipper Root - 4118
174622 - 10 - Cleansed Whipper Root - 4234
174623 - 10 - Cleansed Whipper Root - 4235
174624 - 10 - Cleansed Whipper Root - 4236
174625 - 10 - Cleansed Whipper Root - 4237
174687 - 10 - Cleansed Whipper Root - 4260
164884 - 10 - Cleansed Windblossom - 4102
173326 - 10 - Cleansed Windblossom - 4185
174616 - 10 - Cleansed Windblossom - 4192
174617 - 10 - Cleansed Windblossom - 4193
174618 - 10 - Cleansed Windblossom - 4194
174619 - 10 - Cleansed Windblossom - 4195
174620 - 10 - Cleansed Windblossom - 4196
174621 - 10 - Cleansed Windblossom - 4197
174710 - 10 - Cleansed Windblossom - 4284
174711 - 10 - Cleansed Windblossom - 4288
202443 - 10 - Dedication of Honor - 23787
186944 - 10 - Dirt Mound - 16326
190630 - 10 - Green Cauldron - 18683
190695 - 10 - Heb'Jin's Drum - 18773
181433 - 10 - Irradiated Power Crystal - 10292
183941 - 10 - Jakk's Cage - 12787
201844 - 10 - Light's Vengeance - 22966
201922 - 10 - Light's Vengeance - 23299
1721 - 10 - Locked ball and chain - 312
1722 - 10 - Locked ball and chain - 313
184725 - 10 - Mana Bomb - 13470
183936 - 10 - Manni's Cage - 12785
193025 - 10 - Metal Stake - 20092
183940 - 10 - Moh's Cage - 12786
190619 - 10 - Purple Cauldron - 18681
190620 - 10 - Red Cauldron - 18682
160840 - 10 - Soft Dirt Mound - 3561
181964 - 10 - Statue of Queen Azshara - 11027
153556 - 10 - Thaurissan Relic - 3361
188422 - 10 - The Pearl of the Depths - 17612
19027 - 10 - Tome of Mel'Thandris - 663
193028 - 10 - War Horn of Jotunheim - 20108~~~

The ones of these which are using action 70 to lauch event should be changed to 71 using event id from wdb data

**Comment by offl** [comment]
> Some or all can be converted. And later it will be easier to convert them from SAI.. to SAI. I mean all events should be handled not inside gameobject(on event inform) or creature but on their own. Like areatriggers.

"Small" update: we can convert only a few of them because on event inform does not work with chest(s) and also we can't use target invoker for this event type.
Also it does not work with some gameobjects with type 10.

**Comment by dr-j** [comment]
ye but the ones which just set data or summon a creature or only trigger a text should be able to

**Comment by dr-j** [comment]
as of yet untested to confirm which ones work and which dont but 
~~~sql
UPDATE `smart_scripts` SET `event_type`='71', `event_param1`='17671', `comment`='Anub ar Mechanism - On Event Inform 17671 - Set Data on Roanauk Icemist' WHERE  `entryorguid`=188463 AND `source_type`=1 AND `id`=0 AND `link`=1;
UPDATE `smart_scripts` SET `event_type`='71', `event_param1`='18684', `comment`='Blue Cauldron - On Event Inform 18684 - Set Data 0 1' WHERE  `entryorguid`=190618 AND `source_type`=1 AND `id`=0 AND `link`=0;
UPDATE `smart_scripts` SET `event_type`='71', `event_param1`='17451', `comment`='Cart Release - On Event Inform 17451 - Set Data 1 1' WHERE  `entryorguid`=188104 AND `source_type`=1 AND `id`=0 AND `link`=0;
UPDATE `smart_scripts` SET `event_type`='71', `event_param1`='16326', `comment`='Dirt Mound - On Event Inform 16326 - Add Go Flag ' WHERE  `entryorguid`=186944 AND `source_type`=1 AND `id`=0 AND `link`=1;
UPDATE `smart_scripts` SET `event_type`='71', `event_param1`='18683', `comment`='Green Cauldron - On Event Inform 18683 - Set Data 0 1' WHERE  `entryorguid`=190630 AND `source_type`=1 AND `id`=0 AND `link`=0;
UPDATE `smart_scripts` SET `event_type`='71', `event_param1`='10292', `comment`='Irradiated Power Crystal - On Event Inform 10292 - Say Line 1 (Neutralizing Emote Placeholder)' WHERE  `entryorguid`=181433 AND `source_type`=1 AND `id`=0 AND `link`=0;
UPDATE `smart_scripts` SET `event_type`='71', `event_param1`='12787', `comment`='Jakks Cage - On Event Inform 12787 - Set Data 0 1' WHERE  `entryorguid`=183941 AND `source_type`=1 AND `id`=0 AND `link`=0;
UPDATE `smart_scripts` SET `event_type`='71', `event_param1`='22966', `comment`='Lights Vengeance - On Event Inform 22966 - Set Data on Lights Vengeance Vehicle Bunny 2' WHERE  `entryorguid`=201844 AND `source_type`=1 AND `id`=0 AND `link`=1;
UPDATE `smart_scripts` SET `event_type`='71', `event_param1`='23299', `comment`='Lights Vengeance - On Event Inform 23299 - Set Data 4 4 on Lights Vengeance Bunny 2' WHERE  `entryorguid`=201922 AND `source_type`=1 AND `id`=0 AND `link`=1;
UPDATE `smart_scripts` SET `event_type`='71', `event_param1`='312', `comment`='Locked ball and chain - On Event Inform 312 - Set Data to Drull' WHERE  `entryorguid`=1721 AND `source_type`=1 AND `id`=0 AND `link`=0;
UPDATE `smart_scripts` SET `event_type`='71', `event_param1`='313', `comment`='Locked ball and chain - On Event Inform 313 - Set Data to Tog\'thar' WHERE  `entryorguid`=1722 AND `source_type`=1 AND `id`=0 AND `link`=0;
UPDATE `smart_scripts` SET `event_type`='71', `event_param1`='13470', `comment`='Mana Bomb - On Event Inform 13470 - Set Data 1 1' WHERE  `entryorguid`=184725 AND `source_type`=1 AND `id`=0 AND `link`=1;
UPDATE `smart_scripts` SET `event_type`='71', `event_param1`='12785', `comment`='Mannis Cage - On Event Inform 12785 - Set Data 0 1' WHERE  `entryorguid`=183936 AND `source_type`=1 AND `id`=0 AND `link`=0;
UPDATE `smart_scripts` SET `event_type`='71', `event_param1`='20092', `comment`='Metal Stake - On Event Inform 20092 - Set Data 1 1 on "Patches"' WHERE  `entryorguid`=193025 AND `source_type`=1 AND `id`=0 AND `link`=1;
UPDATE `smart_scripts` SET `event_type`='71', `event_param1`='12786', `comment`='Mohs Cage - On Event Inform 12786  - Set Data 0 1' WHERE  `entryorguid`=183940 AND `source_type`=1 AND `id`=0 AND `link`=0;
UPDATE `smart_scripts` SET `event_type`='71', `event_param1`='18681', `comment`='Purple Cauldron - On Event Inform 18681 - Set Data 0 1' WHERE  `entryorguid`=190619 AND `source_type`=1 AND `id`=0 AND `link`=0;
UPDATE `smart_scripts` SET `event_type`='71', `event_param1`='18682', `comment`='Red Cauldron - On Event Inform 18682 - Set Data 0 1' WHERE  `entryorguid`=190620 AND `source_type`=1 AND `id`=0 AND `link`=0;
UPDATE `smart_scripts` SET `event_type`='71', `event_param1`='3561', `comment`='Soft Dirt Mound - On Event Inform 3561 - Summon Gameobject \'Gor\'tesh\'s Lopped Off Head\'' WHERE  `entryorguid`=160840 AND `source_type`=1 AND `id`=0 AND `link`=0;
UPDATE `smart_scripts` SET `event_type`='71', `event_param1`='11027', `comment`='Statue of Queen Azshara - On Event Inform 11027  - Summon Creature \'Atoph the Bloodcursed\'' WHERE  `entryorguid`=181964 AND `source_type`=1 AND `id`=0 AND `link`=0;
UPDATE `smart_scripts` SET `event_type`='71', `event_param1`='17612', `comment`='The Pearl of the Depths - On Event Inform 17612 - Run Script' WHERE  `entryorguid`=188422 AND `source_type`=1 AND `id`=0 AND `link`=0;
UPDATE `smart_scripts` SET `event_type`='71', `event_param1`='663', `comment`='Tome of Mel\'Thandris - On Event Inform 663 - Summon Creature \'Velinde Starsong\'' WHERE  `entryorguid`=19027 AND `source_type`=1 AND `id`=0 AND `link`=0;
~~~

None of these use invoker or stored targets but I need to test tomorrow

**Comment by dr-j** [comment]
All of the above work except for Statue of Queen Azshara which does nothing when using event inform and the mana bomb which does trigger event but player does not get credit due to group invoker credit all of the rest work

**Comment by dr-j** [comment]
I have had a thought as to reason I’m curious if there is a such thing as targeting via client data for event scripts maybe not all trigger on self?

**Comment by offl** [comment]
With all new info all of that looks not good at all
