### ISSUE TITLE
[Spells/DB] Wrong stack rules in spirit/intellect buffs

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#23534]
**Description:** We use ```SPELL_GROUP_STACK_RULE_EXCLUSIVE_HIGHEST``` as rule to control Spirit/Intlellect buffs.
It cause weird behavior and is not blizzlike. (e.g. https://www.youtube.com/watch?v=qGjdn1k5ars)
Buffs should co-exist, but not stack same effect.
So rule need be updated to ```SPELL_GROUP_STACK_RULE_EXCLUSIVE_SAME_EFFECT```

Fix:

```sql
UPDATE `spell_group_stack_rules` SET `stack_rule`=3 WHERE `group_id`=1083;
```

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 62b2c379b37b843076eb4df379e7de86b18303eb

PS: I tested only some buffs and works fine, will be nice if someone with free time test all and check if has some side effect.

**Comment by Jildor** [comment]
Seems ok ;)

**Comment by Jildor** [comment]
Ok, I think here the problem is the spell Fel Intelligence (Group ID 1073)
We have a Spirit Buffs (Group ID 1085) and Intellect Buffs (Group ID 1083)
Spirit buffs spells should have stack rule 4 (this is correct) and the same Intellect Buffs, but Fel Intelligence should have stack rule 3 in two groups

We should split Fel Intelligence in two groups and link with Spirit Buff and another link with Intellect Buffs and assign stack rule 3 in those two new groups.

So, the fix should be:

```sql
SET @GROUPID1 := xxxx; -- change with a new unused groupid number
SET @GROUPID2 := xxxx; -- change with a new unused groupid number

DELETE FROM `spell_group` WHERE `id` IN (1083,1085) AND `spell_id`=-1073;
DELETE FROM `spell_group` WHERE `id`=@GROUPID1 AND `spell_id` IN (-1085,-1073);
DELETE FROM `spell_group` WHERE `id`=@GROUPID2 AND `spell_id` IN (-1083,-1073);
INSERT INTO `spell_group` (`id`,`spell_id`) VALUES
(@GROUPID1,-1085), -- Spirit Buffs
(@GROUPID1,-1073), -- Fel Intelligence
(@GROUPID2,-1083), -- Intellect Buffs
(@GROUPID2,-1073); -- Fel Intelligence

DELETE FROM `spell_group_stack_rules` WHERE `group_id` IN (@GROUPID1,@GROUPID2);
INSERT INTO `spell_group_stack_rules` (`group_id`,`stack_rule`) VALUES
(@GROUPID1,3),
(@GROUPID2,3);
```

**Comment by CraftedRO** [comment]
60b75e3b6e81 I applied the above sql and now it seems fel inteligence coexist and don't remove arcane brilliance.
maybe we can merge this
```sql
-- I used 1124 and 1125 seems not used
SET @GROUPID1 := 1124;
SET @GROUPID2 := 1125;
```
