### ISSUE TITLE
[DB/quest]Counterattack!

### ISSUE THREAD

**Issue by soniczhang11** [TrinityCore/TrinityCore#23543]
**Description:**

When player get the quest Counterattack!, no mobs respawn.

**Current behaviour:**

Nothing respawn after getting the quest and there is no error or warning in logs . I can sure this quest worked fine by the commit weeks ago. 

**Expected behaviour:**

fix it

**Steps to reproduce the problem:**

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

d213970719bfcfeba16dd400217aa722e63b2615

**Operating system:** CentOS 7

**Comment by Wyrserth** [comment]
For some very strange reason, the SAI actionlist had two useless actions at the end, one of which kept it active for a whole two hours without reason. That made it conflict with 2b1cde25604b6400ac327801d8e1649e30688f5a.

**Comment by offl** [comment]
Maybe it was related to limits?
> Time limit for the Counterattack! quest has been increased to 20 minutes.

**Comment by Wyrserth** [comment]
I don't think so, basically the event should be available to start when the event isn't ongoing and there isn't the banner spawned (it lasts roughly five minutes, and in the existing script the event can be restarted after five minutes as intended).

The two deleted actions in the list set the event phase to 4 after 20 seconds since the event ended, and then set it to 1 after 2 hours (!!!). But the NPC script already sets the phase to 1 after 5 minutes since the start of the event.
