### ISSUE TITLE
CMake is ignoring the variable - Boost_ROOT

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/TrinityCore#23685]
Description:

CMake Warning (dev) at dep/boost/CMakeLists.txt:41 (find_package):
    Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
    Run "cmake --help-policy CMP0074" for policy details. Use the cmake_policy
    command to set the policy and suppress this warning.

    Environment variable Boost_ROOT is set to:

        C:\boost

    For compatibility, CMake is ignoring the variable.
This warning is for project developers. Use -Wno-dev to  suppress it.

Steps to reproduce the problem:

1. Open Cmake (cmake-gui) 3.13.2.
2. Click on Configure button.

Branch(es): master

Operating system:  Windows 10 Pro. 1903 (compilacion de SO 18362.239)
Boost version: 1.68.0
Cmake version: 3.13.2

**Comment by Shauren** [comment]
>This warning is for project developers. Use -Wno-dev to suppress it.

We know, its not breaking anything

**Comment by illfated** [comment]
I have looked at that detail a lot lately, but since I have not checked how this behaviour is on Linux, I have not suggested any changes to the source.

For the time being, those of us who have noticed this in CMake on Windows can only try out the change in our local source, or skip the OS environment variable, to stop seeing this message.

**Comment by Shauren** [comment]
No, dont suggest crap, the variable is still required

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/18cc36bc67023dc9ca58e77733c2b8c74655cf86 killed the warning in 3.3.5 branch (nothing really changed other than not seeing the message anymore)
