### ISSUE TITLE
[DB/Item] Crudely-Written Log - Dropconditions

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#2380]
Core revision: 4147106373ae+
Database revision: TDB 335.11.41

Crudely-Written Log should drop from High Chief Winterfall while doing "High Chief Winterfall" quest or after you've completed it. At the moment it either isn't included in the loot table or isn't triggered by the quest.

http://www.wowhead.com/item=12842/crudely-written-log#comments
http://www.wowhead.com/quest=5121/deprecated-high-chief-winterfall
http://www.wowhead.com/npc=10738/high-chief-winterfall#

**Comment by Nyeriah** [comment]
The item currently has illogical conditions.

It requires http://www.wowhead.com/quest=5128/deprecated-words-of-the-high-chief to be **rewarded** in order to drop but that quest is obtained **after** a quest that starts by the item, so it never drops.

According to comments it should drop while http://www.wowhead.com/quest=5121/deprecated-high-chief-winterfall is **taken**

**Comment by Rushor** [comment]
```sql
DELETE FROM `conditions` WHERE `sourceentry`=12842;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES 
(1, 10738, 12842, 0, 2, 8, 0, 5121, 0, 0, 0, 0, 0, '', 'Loot Condition: Crudely-Written Log'),
(1, 10738, 12842, 0, 0, 28, 0, 5121, 0, 0, 0, 0, 0, '', 'Loot Condition: Crudely-Written Log'),
(1, 10738, 12842, 0, 1, 9, 0, 5121, 0, 0, 0, 0, 0, '', 'Loot Condition: Crudely-Written Log');
```

**Comment by Nyeriah** [comment]
Works, thanks :)
