### ISSUE TITLE
[Quest/Dun Morogh] Vent Horizon

### ISSUE THREAD

**Issue by Casshern** [TrinityCore/TrinityCore#2391]
Core Revision: 17c3ac6b0732665e8b5144ebf3be5245e9fea9b4
DB Revision: TDB 335.11.41
Windows XP

Okay, in the quest "Vent Horizon," you have to board the "Thunderflash" and scan Gnomeregan. I get the quest and talk to Thunderflash, but when I click the choice to "Board the flying machine," nothing happens...

EDIT: I believe you must be a gnome to get the quest, which I was. You get the quest in Steelgrill's Depot.
##

**Comment by Aokromes** [comment]
Anyone can make a PR of https://github.com/TrinityCore/TrinityCore/issues/2391#issuecomment-1991886 if it's valid?

**Comment by LEO33SoFo** [comment]
Is anyone working on this and with **Operation: Gnomeregan** event in general yet?

**Comment by offl** [comment]
I doubt, also this quest is not accessible currently without commands since first quest in chain was disabled by removing questender\queststarter. It's an easy quest to script, all you need is cast taxi spell on gossip select and spawn https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=39420 and award credit at spellhit from quest item
