### ISSUE TITLE
Creature/Movement: Creature with movement_type=0 incant spells whille chasing if the flag 64 is used

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24019]
**Description:** Creature with movement_type=0 incant spells while chasing if the flag 64 is used.

When a creature use an SAI to cast a spell like a fire ball with the cast flag=64 it will behave like a caster and will not move unless out of range, not in los or silenced or out of mana,
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/AI/SmartScripts/SmartAI.cpp#L805-L813
This works correctly if the npc has movement_type=1 or movement_type=2

But if it use movement_type=0 (don't move) once it need to chase the target because one of the reason above, at some point it will incant the spell while moving without stopping.

Video: https://mega.nz/#!09RkHALR!m6C6bHEkkUeK9hK1uW_FSHACfvcGKb0tswA3WmT5Nng

**Steps to reproduce the problem:**

1. .go c 7514
2. aggro the npc
3. move away to put it out of range
4. notice it will incant the spell while is still chasing you

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 88a14251e276

**Comment by jackpoz** [comment]
what is the correct behavior here ?

**Comment by offl** [comment]
Do not move while casting

**Comment by jackpoz** [comment]
@ccrs this is caused by ChaseMovementGenerator::Finalize() letting the current spline continue

Spline info in ChaseMovementGenerator::Finalize()
>owner->movespline->splineflags.done
false

See how the mob is casting before the spline is finalized (on next Creature::Update() ) :
![image](https://user-images.githubusercontent.com/1153754/89537895-3806ff80-d7fa-11ea-9cd3-f909f37de04f.png)
