### ISSUE TITLE
Ulduar: Flame Leviathan encounter

### ISSUE THREAD

**Issue by xParad0x** [TrinityCore/TrinityCore#24079]
Ulduar: Flame Leviathan encounter doesnt work as intended and it seems as Tar has no effect on Flame Leviathan, also no matter what you do , you can never hook the Pyrite.

**Steps to reproduce the problem:**

1. Go to Ulduar, pick up a demolisher.
2. Engage Flame Leviathan
3. Try using Tar to slow him down or try to refuel by Hooking up a Pyrite.

**Current behaviour:**
During Flame Leviathan encounter you cannot pick up a Pyrite, you cannot slow him down, the tar should slow him down if not burning, seems he is immune to it

**Expected behaviour:**
You should be able to hook the Pyrite and get it as fuel for your Demolishers and the tar should slow him  down if its not burning, creating a specific tactic when fighting Flame Leviathan

**Branch(es):**
3.3.5
https://github.com/TrinityCore/TrinityCore/commit/c1df161e1ddf95584030480d3dcb15149aacd7a6

**Operating system:** CHANGEME OS
Windows x64 | 2012 Server Edition

**Comment by Killyana** [comment]
All this issues are already here https://github.com/TrinityCore/TrinityCore/issues/16520

**Comment by xParad0x** [comment]
the issues from 2016 you mean?  We are 2020. Maybe this should be addressed in a different manner

**Comment by Aokromes** [comment]
pull requests are welcomed, no one here is paid to work on some raid, or whatever.

**Comment by xParad0x** [comment]
Some raid? Nobody is telling you to do anything, at the same time what is the point of reporting issues here? So you can tell people that nobody gets paid for doing anything here?  I was under impression that this is a public project, if you are planning to reply in such manner then you should quit now and stop posting arrogant replies.

**Comment by D-CellX** [comment]
@Aokromes to be completely honest here, that reply shocked me. 
```pull requests are welcomed, no one here is paid to work on some raid, or whatever.``` so you welcome pull requests yet you tell people nobody gets paid here? You should be very careful next time you decide to post statements such as these.

**Comment by illfated** [comment]
@D-CellX : Both your comment https://github.com/TrinityCore/TrinityCore/issues/24079#issuecomment-575913293 and Aokromes' comment https://github.com/TrinityCore/TrinityCore/issues/24079#issuecomment-575916399 can be interpreted in at least 2 different ways, depending on the reader's viewpoint. To me, as a former member of TC (but not a real coder), your comment seems to ask the TC members to make a change in what they are doing to work more on raid content than choosing what they want to do based on personal preference.

Reading your comments with a mindset favorable to what you said last, Aokromes' comment still seems fair and explanatory, not in any way disrespectful.

**Comment by Jinnaix** [comment]
When I fist started with TrinityCore (and git!) I thought the same - that old issues won't be touched or seen and reposting stuff is a good idea.
It's not. 
Use the search function before you create a issue.
If you can't hold your horses and you see an issue that hasn't got any post in a long time, test it and post that it's still valid in a recent revision. But unless you can't give new insights on a problem, there is no way of speed up the process.
You only make yourself look silly this way.

**Comment by illfated** [comment]
https://github.com/TrinityCore/TrinityCore/search?q=Flame+Leviathan&state=open&type=Issues

**Comment by D-CellX** [comment]
@illfated there should not be a "Personal Preference" in a public project. Issues that are most important and game breaking should be addressed first.  The prosperity and future of this project shouldnt be built on Personal Preferences. Thus why so many Devs left Trinitycore because there is no common goal or focus and I personally couldn't stomach @Aokromes comment, it contradicts everything about Public Projects and Game Emulation.

**Comment by illfated** [comment]
Sure. In an ideal world, it would be preferable to do what you suggested. Under the current circumstances, it takes a lot of idealistic enthusiasts who would also be OK with the rules of this repository.

Maybe you are aware of this already, but some developers (more than one) found it too hard to keep up their amount of contribution while also having a real life job and a normal daytime schedule.

**Comment by Aokromes** [comment]
@D-CellX no one on project gets paid to work on something, if you have your preferences (ulduar) other devs have their own preferences, we cannot force no one to work on what you want, because they do for free, and if they are forced they leave.

**Comment by Demonasus** [comment]
```pull requests are welcomed, no one here is paid to work on some raid, or whatever.```

I agree 100%, this comment made me sick to my stomach.

And on the same note., @xParad0x only expressed his opinion on what should be addressed as a priority. Last time I checked, Ulduar is a shit storm and there is absolutely nothing wrong with him stating that a change of focus would be great.

@illfated this a Public Licensed Emulation Project, there shouldn't be a personal preference focus, if TC Devs entertain this notion then it should be closed and marked as Private,.

**Comment by Aokromes** [comment]
@Demonasus the oposite, private projects are the ones working on targets and get paid to fix specific things.

**Comment by illfated** [comment]
@Demonasus / @xParad0x / @D-CellX : I get it, you are passionate about the game and the ability to run it on TC servers built from public source code. Please be aware that it is the result from idealistic work, and the closest thing you can come to being paid when working on this source code is to solve an issue linked to a Bountysource ticket. Otherwise, it is purely spare time work for free and idealistic. There is also the motto or idea that TrinityCore is about the ability to use this source code to improve on your own coding skills, as well as finding out how to get it approved in this repository.

**Comment by Keader** [comment]
Well, recently only me and sirikfoll was working in Ulduar...
I just stopped, because good part of PRs no one give a shit to help, no even help with test. (And i dont have free time anymore)
Like Aokromes said, no one here is paid for anything, so we do wherever we want. Since everyone here has university/school, jobs, girlfriend/boyfriend... a real life.
And since it's a open source project, everyone can contribute with (that's why aokromes said that PRs are welcome).
Anyway... i want continue working in ulduar after first semester of 2020.
Right now, me and sirikfoll rewrited: Razorscale, XT002, Algalon,  and ariel rewrited Thorim.
Still need work: Ignis, Flame Leviathan, Freya, Hodir, General Vezax and Yogg.
Missing trash mobs spells, first floor event (towers ones), train handler (mimiron)
Kologarn had a work in progress, maybe when sirikfoll get time, can finish: https://github.com/TrinityCore/TrinityCore/pull/22386 or... if someone takeover it

**Comment by davkorss** [comment]
Hi guys, I'm new to this project and I really want to contribute to this raid and the project in general.
An obstacle that I have found in my learning is that I don't know how debug this bosses.
It would be great if any can teach me how to debug the things that are wrong.
Thanks you so much guys and sorry for my bad english 😅

**Comment by illfated** [comment]
@davkorss : you can ask in IRC : channel #trinity @ irc.rizon.net
