### ISSUE TITLE
How to config the TrinityCore to support naming character's nickname with Chinese.

### ISSUE THREAD

**Issue by wplatform** [TrinityCore/TrinityCore#24132]
Typing the character's nickname with Chinese is not allowed

My configuration as following, but not available.

RealmZone = 16
//#2 - (Enabled, Strictly realm zone specific, See RealmZone setting,
StrictPlayerNames = 0
StrictCharterNames = 2
StrictPetNames = 2

**Comment by jackpoz** [comment]
Follow the issue template, it's there for a reason



**Description:**

CHANGEME Description of the problem or issue here.

**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Branch(es):**

CHANGEME 3.3.5, master or both

**TC rev. hash/commit:** 

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** CHANGEME OS
