### ISSUE TITLE
Delete.

### ISSUE THREAD

**Issue by warcrafte** [TrinityCore/TrinityCore#24186]
Fixed

**Comment by warcrafte** [comment]
I think All spells By "Channeling" is Buged.

**Comment by jackpoz** [comment]
Don't change the title to "Delete" and just write "fixed": if you had an issue and you resolved it, post the solution so others can use it too.

**Comment by illfated** [comment]
It is more likely that this issue is covered by one of TC's more general issues about channeled casts, Therefore, this one would have been a duplicate. The original text is under "Edited" if you think it is worth pasting back in a new comment (or the original one). See also:
- **Bug vanish with channeled spells #7425**
- **[Spell] Mage / Interrupted #24185** (pointing to #7425 )
