### ISSUE TITLE
Quest "Digging for Prayer Beads" problem

### ISSUE THREAD

**Issue by aleigood** [TrinityCore/TrinityCore#24218]
Description:
After the Honor Hold was attacked by Infernal Rain, NPC did not return to its original location, and the Digging for Prayer Beads quest could not be completed, The dog Fei Fei took the wrong path.

Steps to reproduce the problem:
1. .character level 60
2. .go xyz -684.60302 2626.43994 89.15503 530
3. .quest add 10916
4. .additem 31799
5. wait for Infernal Rain
6. complete the quest

Branch(es):
3.3.5

TC rev. hash/commit:
94186a5e79d5d3fe29ac80245992af6365999a93

Operating system:
CentOS

**Comment by dr-j** [comment]
I dont understand what issue is here other than your instructions to reproduce been wrong as there is no item 10916 its quest not item

as for dog been in wrong place this could be due to previous run of script and grid has been unloaded by there been no player in area before script completed  and thus when next player came was in wrong position

And I have no idea what you are exactually going on about when you say infernal rain

**Comment by dr-j** [comment]
It is also possible there maybe more than one path fei fei may use

**Comment by aleigood** [comment]
> It is also possible there maybe more than one path fei fei may use as think I was last person to do any work on this and that was from sniff but there was a prior implementation of this in tc before

Sorry, I've updated the steps

![image](https://user-images.githubusercontent.com/3367999/75626257-03ff3100-5c01-11ea-84df-34db49dd2352.png)

**Comment by Killyana** [comment]
Related to https://github.com/TrinityCore/TrinityCore/issues/21106
