### ISSUE TITLE
DB/Creature : Julianne's first death sound

### ISSUE THREAD

**Issue by aleigood** [TrinityCore/TrinityCore#24304]
The sound of Julianne's first death should be 9198, current is 9199.
``` sql
UPDATE `creature_text` SET `Sound` = '9198' WHERE `CreatureID` = '17534' and `GroupID` = '2' and `ID` = '0';
```

**Comment by illfated** [comment]
I know that it can be easy to confuse the real life world names with the in-game names, especially with the pop culture references. Please note that skipping the entire issue ticket template (and also removing it) makes it more difficult for us others to research the game details you have based your short  description on. 

Using the name "Juliet", I thought you meant [**Juliet Stonehelm** `<Shaman Glyphs>`](https://www.wowhead.com/npc=32760/juliet-stonehelm) (Kirin Tor vendor) (https://www.wowhead.com/npc=32760/juliet-stonehelm), but when I read your SQL line, it is clear that you mean the Opera event in Karazhan, featuring Romulo & Julianne (https://www.wowhead.com/npc=17534/julianne).

To compare the sound files, see these pages:
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=17534#sounds (uses "HumanFemalePlayerDeath" a non-specific death sound (https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?sound=2940))
- https://www.wowhead.com/npc=17534/julianne#sounds (A_JulianneDeath01 - https://www.wowhead.com/sound=9198/a-juliannedeath01)

I do not know how accurate the wowhead page is, because it lists the HumanFemalePlayerDeath (2940) sound too, as well as A_JulianneDeath01 (9198).

**Comment by illfated** [comment]
Please change your issue ticket title to:

**DB/Creature : Julianne's first death sound**
