### ISSUE TITLE
Causes a server crash, don’t know where to write, so I write here

### ISSUE THREAD

**Issue by BoomHouse** [TrinityCore/TrinityCore#24534]
Description:
Causes a server crash, don’t know where to write, so I write here
\ src \ server \ game \ Maps \ Map.h: 853 in Map :: GetRespawnMapForType ASSERTION FAILED:
false
Id: 1 InstanceId: 0 Difficulty: 0 HasPlayers: true

Current behaviour:
Namely, it points to this line: ASSERT (false);

Here is a script that indicates crash

Steps to reproduce the problem:
{
switch (type)
{
default:
ASSERT (false);
case SPAWN_TYPE_CREATURE:
return _creatureRespawnTimesBySpawnId;
case SPAWN_TYPE_GAMEOBJECT:
return _gameObjectRespawnTimesBySpawnId;
}
}

Branch: 3.3.5
Operating system: Window 64

How can I fix this so that there would be no more server crash?

**Comment by jackpoz** [comment]
Please fill the issue template with the informations required (without them we can't even start working on the issue you have)



**Description:**

CHANGEME Description of the problem or issue here.

**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Branch(es):**

CHANGEME 3.3.5, master or both

**TC rev. hash/commit:** 

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** CHANGEME OS

**Comment by BoomHouse** [comment]
Description:
Causes a server crash, don’t know where to write, so I write here
\ src \ server \ game \ Maps \ Map.h: 853 in Map :: GetRespawnMapForType ASSERTION FAILED:
false
Id: 1 InstanceId: 0 Difficulty: 0 HasPlayers: true

Current behaviour:
Namely, it points to this line: ASSERT (false);

Here is a script that indicates crash

Steps to reproduce the problem:
{
switch (type)
{
default:
ASSERT (false);
case SPAWN_TYPE_CREATURE:
return _creatureRespawnTimesBySpawnId;
case SPAWN_TYPE_GAMEOBJECT:
return _gameObjectRespawnTimesBySpawnId;
}
}

Branch: 3.3.5
Operating system: Window 64

How can I fix this so that there would be no more server crash?

**Comment by illfated** [comment]
You need to post a link to your Debug crash log. making sure that this is _clean_ TrinityCore 3.3.5 branch (not modified) and also post the revision commit hash from your crashing server.

Nobody here can say for sure what causes the crash if we don't have a Debug crash log to check.

**Comment by BoomHouse** [comment]
> Необходимо опубликовать ссылку на журнал сбоев отладки. убедитесь, что это _чистая _ветвь TrinityCore 3.3.5 (без изменений), а также разместите хэш фиксации версии с вашего сервера сбоя.
> 
> Никто здесь не может сказать наверняка, что вызывает сбой, если у нас нет журнала сбоев отладки для проверки.

[WoW Citadel_worldserver.exe_[1-5_23-34-20].txt](https://github.com/TrinityCore/TrinityCore/files/4567589/WoW.Citadel_worldserver.exe_.1-5_23-34-20.txt)

**Comment by Aokromes** [comment]
Revision: WoW Citadel. WoW Citadel 1.05.2020g Rev +3224 (WoW-Citadel.servepics.com) (Win64, Release, Static)

release mode crashlogs and who knows how much custom patches....

**Comment by Faq** [comment]
@BoomHouse compile using Debug (not Release mode) and then post again.

**Comment by jackpoz** [comment]
is that WoW Citadel hosted somewhere ? got a link ?

**Comment by jackpoz** [comment]
Run this query in the characters database and post here the result:
```sql
SELECT * FROM respawn WHERE TYPE NOT IN (0,1);
```

As suggested by someone else, run this query in your characters database to remove all respawns:
```sql
TRUNCATE TABLE respawn;
```
