### ISSUE TITLE
Mobs in Azjol Nerub drop skinning stuff https://i.imgur.com/80lKF72.png

### ISSUE THREAD

**Issue by jaxidor** [TrinityCore/TrinityCore#24582]
**Description:**

All mobs in Azjol Nerub drop skinning stuff https://i.imgur.com/80lKF72.png.

**Current behaviour:**

Mobs in Azjol Nerub drops unique skinning stuff that should only be obtainable through skinning.

**Expected behaviour:**

Mobs in Azjol Nerub should not drop these skinning items.

**Branch(es):**

3.3.5

**Comment by jackpoz** [comment]
Which commit hash are you using ?

**Comment by jaxidor** [comment]
c6c7ee03fa26

**Comment by jaxidor** [comment]
> Which commit hash are you using ?

c6c7ee03fa26

**Comment by jackpoz** [comment]
do you have any custom patch applied ? could you push your branch to a github fork ?

**Comment by Rushor** [comment]
pls post the id of the creatures here aswell

**Comment by ccrs** [comment]
ancient issue, its valid

**Comment by Keader** [comment]
Minions of first boss, should quick despawn and not drop anything.
If i remember right, they are summon group.
Just need change summon type+timer in creature_summon_groups table

**Comment by ccrs** [comment]
nope, not those, the ones just at the entrance, not boss related

**Comment by offl** [comment]
One week ago I removed TBC & classic leather, but the chance to drop was low.
In this case the chance is really huge and wowhead shows Borean Leather should drop from multiple NPCs, but the chance is pretty much lower so we can presume these items were added to wowhead site due to the bugged wowhead addon.
It's still the case https://www.wowhead.com/item=33568/borean-leather and the chance is still low.

But [here](https://youtu.be/egcI6gRWw-g?t=40) someone looted Borean Leather from Anub'ar Warrior or Anub'ar Skirmisher. Maybe it was skinned.
[Here](https://youtu.be/17_-_zKOCdI?t=336) it can be clearly seen two Anub'ar Prime Guard didn't drop something but later they were skinned with the result of leather and chitin.

```sql
--
DELETE FROM `creature_loot_template` WHERE `Reference` = 0 AND `Item` IN (33567,33568,38557,38558,44128);
UPDATE `creature_template` SET `lootid` = 0 WHERE `entry` IN (28340,28341);
```

**Comment by Aokromes** [comment]
while you are at it, can you fix also heroic mode creatures aren't skinables? :)

**Comment by Jildor** [comment]
Heroic creatures can't be skinables seems generic issue
New issue for this @Aokromes :smile:

**Comment by offl** [comment]
Updated

**Comment by jaxidor** [comment]
> do you have any custom patch applied ? could you push your branch to a github fork ?

I dont have any custom patch applied, i pulled latest changes yesterday.

**Comment by jaxidor** [comment]
Thank you for the skinning fix! much appricated however it seems like now the mobs dont have any drop table at all, the whole dungeon except bosses.

**Comment by offl** [comment]
You're welcome
They all were without loot before and after the fix

**Comment by jaxidor** [comment]
Thanks again :)
