### ISSUE TITLE
% of the Berserk

### ISSUE THREAD

**Issue by princen4** [TrinityCore/TrinityCore#24625]
Hello everyone
Tell me how you can fix the problem of berserk in the last cores of Trinity, so that the berserk then multiplied and gave out a lot, but just summed up? To get 1020% when using id71195 + id64238, instead of 3 or 4 K
Thank you all in advance

**Comment by jackpoz** [comment]
please follow the template of new issues:



**Description:**

CHANGEME Description of the problem or issue here.

**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Branch(es):**

CHANGEME 3.3.5, master or both

**TC rev. hash/commit:** 

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** CHANGEME OS
