### ISSUE TITLE
Received not handled opcode

### ISSUE THREAD

**Issue by dopiks** [TrinityCore/TrinityCore#24762]
**Description:**
Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x36BD (14013)] from [Player: Account: 1]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PRODUCT_LIST 0x36BC (14012)] from [Player: Account: 1]
Received not handled opcode [CMSG_UPDATE_VAS_PURCHASE_STATES 0x36F6 (14070)] from [Player: Account: 1]
WorldSocket::ReadHeaderHandler(): client 192.168.1.21 sent malformed packet (size: 124814)

cant login, closes window with realm select and disconect  

**Expected behaviour:**
login to create a new character 

**Steps to reproduce the problem:**

1.compile 
2. start
3.login

**Branch(es):**
master

**TC rev. hash/commit:** 
TrinityCore rev. afcb8ff8e9f6 2020-06-07 00:20:13 +0200 (master branch) (Win64, Release, Static) 

**Operating system:** 
Windows 10 x64

**Comment by Aokromes** [comment]
duplicate.

**Comment by illfated** [comment]
The open ticket **[master] Received not handled opcode** #14216 is the active ticket, although that ticket is not open to adding comments by users outside the TC collaborators group. 
(adding this comment and ticket reference here for logging purposes)

@dopiks : The issue is known and it is still an open issue in #14216 .
