### ISSUE TITLE
[3.3.5a] Random Crash

### ISSUE THREAD

**Issue by Khardoom** [TrinityCore/TrinityCore#24775]
**Description:**

Hello guys, I have an old server where I play with my family and I've noticed that every morning around 7:30, it randomly crashes. At that time the server is empty, with no players on.

CrashLog: https://gist.github.com/Khardoom/7df4d1a3d273d2a8f253307b0e998e30

**Branch(es):** 3.3.5

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/971f486176e9f9de1670402a15d44c584e8150ac

**Operating system:** Windows 10 x64

I don't know if you support such an old core, but any help would be greatly appreciated, as we don't want to update.
If a fix is not possible, maybe you could point me in the right direction and show me what is the cause of this crash.

Thanks a lot!

**Comment by Aokromes** [comment]
we don't support 6 years old cores.

**Comment by illfated** [comment]
Your best chance to find any help for your problem is to post on forums where old source code is discussed, or where someone with coding experience might want to help you find a solution.

The issue you describe sounds like something that was fixed even in some repacks back in 2015 or 2016 (look for those, if you can't get any help in forums). Other workarounds might include hack-fixing the settings to have one or more accounts logged in permanently, or even deploy one or more bots to keep the server occupied with something.

Sorry that I can't help any more than that, but your issue is clearly Forum material.
