### ISSUE TITLE
NPC Oralius is missing his RP script

### ISSUE THREAD

**Issue by Rothend** [TrinityCore/TrinityCore#24860]
**Description:**

I couldn't find much info about this one, but according to [this](https://wowwiki.fandom.com/wiki/Oralius), [Oralius](https://classic.wowhead.com/npc=9177) in Burning Steppes should talk about an imaginary pirate named Winky. Couldn't find anything about it on broadcast_text, though.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 05025d79f3cb34fa135cb820badeef32883f7eb4

**Comment by offl** [comment]
1. Try to read his quest content, probably it's just about the quest content
2. They removed the texts from broadcast_text or replaced them by new. Rare case, usually they just leave them untouched. Someone here got broadcast_text from classic, try to ask in IRC but quite possible it's not yet added in classic since it's not displayed in wowhead. Or because of 1.

Imho we need classic broadcast_text anyway.

**Comment by Rothend** [comment]
That's it, thanks! All the text I found mentioned about him is in one of his quests' text. This is invalid, then.

We still need classic broadcast_text though, I do recall Blizzard updating some texts, at least from WotLK to Cataclysm.

**Comment by Killyana** [comment]
I cannot fin any text containing "winky" in classic broadcast_text.

**Comment by Rothend** [comment]
Thanks for checking! All the RP of this one is in the quest text then, comments on Wowhead weren't very clear so I thought he had some out of combat text. My bad :P
