### ISSUE TITLE
Core/Spell: Phantom Strike, Slow, Death Coil must be negative

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24899]
**Description:** Auras from this spells must be displayed as debuffs and to buffs:  33925,39332,25603,38065
Sql from the main issue https://github.com/TrinityCore/TrinityCore/issues/24808
``` sql
-- Phantom Strike, Slow, Death Coil must be negative
DELETE FROM `spell_custom_attr` WHERE `entry` IN (33925,39332,25603,38065);
INSERT INTO `spell_custom_attr` (`entry`,`attributes`) VALUES
(33925,4096|8192|16384),
(39332,4096|8192|16384),
(25603,4096|8192),
(38065,8192);
```

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. e6b06c4f039f

**Comment by Jildor** [comment]
the only spell that isn't negative is 38065 and maybe needs a specific fix like that sql:

```sql
-- Mana-Tombs: Death Coil must be negative
DELETE FROM `spell_custom_attr` WHERE `entry`=38065;
INSERT INTO `spell_custom_attr` (`entry`,`attributes`) VALUES
(38065,8192);
```

**Comment by Jildor** [comment]
oh I see, if aura is applied with .aura
by example: .aura 33925 is applied as debuff.
if you do .cast 33925 or .learn 33925 and cast spell, is applied as buff because the first effect is SPELL_AURA_MOD_MELEE_RANGED_HASTE and that effect isn't checked as negative. (I will try to open a PR with that now)

The key here I think should be checked all effects first and then check if should be positive or negative or what?

**Comment by Jildor** [comment]
Can be closed ;)
