### ISSUE TITLE
DB/Item: Diabolical Plans & Flayed Demon Skin

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#24971]
**Description:**

Drop chances of these items are too low (1-3%). They should be much higher.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. cc5bea023a0c+ 2020-05-19

**TDB version:**  335.64

**Operating system:** Windows 7

**Suggested Fix:**
```sql
UPDATE `creature_loot_template` SET `Chance`=20 WHERE `Item` IN (23797,23777,20310);

**Comment by illfated** [comment]
It has been a while since I did those quests or looked up any of the background information for them.

- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=20310
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=23777
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=23797

By the way, if the player has done the quest for that item already, where in the DB is it handled to avoid dropping the item or not showing it in loot?
(I have completely forgotten this, it has been a long time since I looked it up.)
