### ISSUE TITLE
DB/Quest: Traitors Among Us

### ISSUE THREAD

**Issue by LEO33SoFo** [TrinityCore/TrinityCore#25083]
**Description:**

When you talk to **Deserter Agitators**, those who are not turned hostile just continue to speak to the guard they are assigned, like nothing happened.
Also, during my gameplay, only one **Deserter Agitator** decided to turn hostile and attack me, the other four didn't turn hostile. Is the chance for this to happen really random?

**Expected behaviour:**

According to [Wowpedia](https://wow.gamepedia.com/Traitors_Among_Us), and according to [Wowhead](https://www.wowhead.com/quest=11126/traitors-among-us#comments) comments, those who are not turned hostile should flee.

**Steps to reproduce the problem:**

1. `.go creature id 23566`
2. `.quest add 11126`
3. Do the quest normally and notice the **Deserter Agitators**' behaviour when some decide not to turn hostile.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

d974800e9d1e393ce3459ed8be4f4bd9defcc8f3

**Operating system:** Windows 7 Enterprise 64bit

**Comment by CraftedRO** [comment]
The report were partially true , this specific npc won't turn hostile for the first time when you talk with him , most likely because he got a SAI with dialogue with the Guard Lasiter.
However it will count when you click on him so I guess is fine.

![WoWScrnShot_100921_142314](https://user-images.githubusercontent.com/24683355/136656091-fd2faf09-00ea-4b35-b5e9-bf3ff3786b4e.jpg)
