### ISSUE TITLE
quest 809 Visual quest bug

### ISSUE THREAD

**Issue by genion18** [TrinityCore/TrinityCore#25344]
.go crature 3415
take the quest id 809  Warlock (https://classic.wowhead.com/quest=809/akzeloth)
.go creature 20268

see in the screenshots the differnt.

3.3.5

7478c2c65aea853a2086c9c7ecc56c14ad6ee338

Original:

![WoWScrnShot_022620_005554](https://user-images.githubusercontent.com/321832/91492653-49ea3880-e8b6-11ea-94db-382c76220d8c.jpg)

Trinity:

![WoWScrnShot_082720_223650](https://user-images.githubusercontent.com/321832/91492681-540c3700-e8b6-11ea-8982-c746c7418260.jpg)

**Comment by Treeston** [comment]
Disable your addons. We cannot fix your UI for you.

**Comment by genion18** [comment]
We testet it thit norhing addons and it´s the same. see Original and the Trinityversion!

The original says "Zerstört die Demonensaat: 0/1" and this is thit addons

Trinity says nothing and this is thit nothing addons

**Comment by offl** [comment]
Seems like objective 'Destroy the Demon Seed' is missing
https://classic.wowhead.com/quest=809/akzeloth
https://www.wowhead.com/quest=809/akzeloth

But this objective looks like a bug because you don't need to destroy something in this quest, the quest is also completed automatically. Also the objective is not shown in http://web.archive.org/web/20100623154417/www.wowhead.com/quest=809 but for some reason shown in actual wowhead for 8xx - https://www.wowhead.com/quest=809/akzeloth
I think better to touch nothing here or you can find a video of this quest from 3xx so we can be sure this requires changes or not (wasn't able to find something).

This objective belongs to http://web.archive.org/web/20100420065059/http://www.wowhead.com/quest=924

**Comment by genion18** [comment]
Yes, the quest is completed but he´s say "Zerstört die Demonensaat: 0/1" (see in original retrail).

**Comment by offl** [comment]
As I said above the objective is not shown in archieved page of wowhead from 2010 http://web.archive.org/web/20100623154417/www.wowhead.com/quest=809
So there's a chance it was fixed between Classic and WotLK
In other words I doubt it's a good idea to change something here by using data from Classic videos

**Comment by jackpoz** [comment]
Stop comparing WoW Classic from 2019 to WoW 3.3.5 from 2006

**Comment by illfated** [comment]
WoTLK = October 14, 2008 (3.0.2)  - June 29, 2010 (3.3.5a), but sure, your point remains.
