### ISSUE TITLE
Wrong 'CompletionText` in quest 191 and 192

### ISSUE THREAD

**Issue by Cerveciento** [TrinityCore/TrinityCore#25499]
**Description:**

The text shown in both missions corresponds to mission 193.

https://classic.wowhead.com/quest=191/panther-mastery
https://classic.wowhead.com/quest=192/panther-mastery
https://classic.wowhead.com/quest=193/panther-mastery

**Fix:**
``` sql
UPDATE `quest_request_items` SET `CompletionText` = 'Go kill 10 panthers! Show us what you\'ve got!', `VerifiedBuild` = 0 WHERE `ID` = 191; 
UPDATE `quest_request_items` SET `CompletionText` = 'What are you doing here, $n! You should be crawling through the brush, trying to kill 10 Shadowmaw Panthers. I thought you fancied yourself a big game $c? ', `VerifiedBuild` = 0 WHERE `ID` = 192; 
```
**Branch(es):** 3.3.5
**TC rev. hash/commit:** b038dd985fce
**Operating system:** debian 10

**Comment by illfated** [comment]
Thank you for spotting those copy-paste issues. Good job. Current content as of f45600fb2e6b 2020-09-24 00:06:17 +0200 (3.3.5 branch):
```sql
SELECT * FROM `version`;
```
```
core_version                                                                                     core_revision  db_version     cache_id
-----------------------------------------------------------------------------------------------  -------------  -------------  --------
TrinityCore rev. f45600fb2e6b 2020-09-24 00:06:17 +0200 (3.3.5 branch) (Win64, Release, Static)  f45600fb2e6b   TDB 335.20091     20091
```
```sql
SELECT * FROM `quest_request_items`WHERE `ID` IN (190,191,192,193);
```
```
 ID  EmoteOnComplete  EmoteOnIncomplete  CompletionText                                                                                                                              VerifiedBuild
---  ---------------  -----------------  ------------------------------------------------------------------------------------------------------------------------------------------  -------------
190                1               25    A true panther hunter would be out in the fields, trying to stalk his prey. Show some commitment to your goal, $c, and get back out there.          12340
191                1                0    Bhag'thera can prove to be an elusive beast. How fairs the hunt?                                                                                    12340
192                1                0    Bhag'thera can prove to be an elusive beast. How fairs the hunt?                                                                                    12340
193                6                6    Bhag'thera can prove to be an elusive beast.  How fares the hunt?                                                                                   12340
```
A bit odd to see that the lines were attributed to being verified by sniffs (VerifiedBuild = 12340) when there are typos as well as obvious signs of copy-pasting.

**Comment by illfated** [comment]
By the way, I think wowhead got it wrong with the `class` (`$c`) variable in the following sentence:
```
I thought you fancied yourself a big game <class>?
```
The term is "big game hunter" - regardless of player class. The whole quest series (raptor, panther, tiger) is about hunting big game animals. See for yourself by browsing all the Nesingwary Safari quest texts, it refers to big game hunting/big game hunter quite a few times, so it should be quite easy to notice (at least for people familiar with the term "big game hunter").

I searched for evidence that this should be the case, but I could only locate a handful of fringe uses of the correct wording:
https://www.google.com/search?newwindow=1&sxsrf=ALeKk02plsp3sp8knSPNc0L_qef6jG7Pcg%3A1601135271336&source=hp&ei=p2JvX-aeEtL4aJOxq4gL&q=%22I+thought+you+fancied+yourself+a+big+game+hunter%3F%22&oq=%22I+thought+you+fancied+yourself+a+big+game+hunter%3F%22&gs_lcp=CgZwc3ktYWIQAzIECCMQJ1CINFjsb2DgdGgAcAB4AIABY4gB_QKSAQE1mAEAoAECoAEBqgEHZ3dzLXdpeg&sclient=psy-ab&ved=0ahUKEwimjtXYlYfsAhVSPBoKHZPYCrEQ4dUDCAY&uact=5
- https://vanilla-twinhead.twinstar.cz/?quest=192
- https://vanillawowaddons.com/database/?quest=192
- https://metagit.org/blizzlike/cmangos-tbc-db-localized/src/commit/c2cb933e3bcf9cc81db19cc8bb44634fec62b031/Translations_TODO/Italian/Italian_Quest_missing.sql?lang=lv-LV#L337-L346

Then again, because quest 192 does not request any item hand-in, the `CompletionText` text should only be visible if you read the quest from the quest giver before the quest is completed, so it may not be that important to most people (except for us grammar autists). 😉

**Comment by ratkosrb** [comment]
I have those quests sniffed from classic.
```
INSERT INTO `quest_request_items` (`ID`, `EmoteOnComplete`, `EmoteOnIncomplete`, `CompletionText`, `VerifiedBuild`) VALUES 
(190, 25, NULL, 'A true panther hunter would be out in the fields, trying to stalk his prey. Show some commitment to your goal, $c, and get back out there.', 35000),
(191, 5, NULL, 'Go kill 10 panthers!  Show us what you\'ve got!', 35000),
(192, 6, NULL, 'What are you doing here, $N!  You should be crawling through the brush, trying to kill 10 Shadowmaw Panthers.  I thought you fancied yourself a big game hunter?', 35000);
```

**Comment by illfated** [comment]
Thanks, that is at least a useful confirmation that the _hunter_ part of the sentence is not meant to be a class variable. The only open question is what the text used to be back in the day, between 2006 and 2010. Also, to reiterate myself, it could be seen as less important since the quest does not have any item hand-in at the end. The modern (post-Cataclysm) version of the quest skips the `CompletionText` part completely.

**Comment by ratkosrb** [comment]
The `CompletionText` from `quest_request_items` is only shown if one of these 2 conditions is met:
- quest requires items
- quest is not completed

That's how it works for all quests. If the quest does not require items and has been completed, meaning the required creatures have been killed, it skips straight to the offer reward window. You need to talk back to the npc after accepting the quest but before completing it in order to be able to see that quest.

**Comment by illfated** [comment]
Fair point, thanks. I guess that is sort of what I talked about when mentioning that it shows up when talking to the quest giver before the quest is completed.

Anyway, I vote for correcting the `CompletionText` fields for 191 + 192, as well as using text instead of the $c variable. Most non-hunters won't notice it anyway. 😉
