### ISSUE TITLE
[3.3.5] Quest item in inventory does not count when completing the quest

### ISSUE THREAD

**Issue by Wombyte2** [TrinityCore/TrinityCore#25603]
**Description:**

This is a bit tricky to explain:
Lets say you have a quest where you need to collect 20 linen cloth. But you collect more than 20, you collect 30. 
Then you sell the first 10 that you collected, so that you still have 20 in your backpack. 
If you try to complete the quest now, it will tell you that you have not enough linen cloth in your backpack. 

As a workaround you can sell those 20 linen cloth and rebuy them, or put them on your bank and then back in your inventory. 
Then it will count them as collected. 

**Expected behaviour:**

It shouldn't matter if those 20 linen cloth are the first 20 you collected, or the last 20. 

**Steps to reproduce the problem:**

1. Get any quest where you need to collect something and where you are able to collect more than you need (e.g. you need 20 linen cloth)
2. Collect more of those things than you need.  (like 30 linen cloth) 
3. Sell the first 10 that you collected (not the last one's you got, but the first ones, thats very important!). 
4. Try to complete the quest. it will tell you that it's not possible. 
5. Put the 20 linen cloth on your bank and back in your inventory. 
6. Now you can complete the quest.

**Branch(es):**

3.3.5 rev. 07845b4

**Comment by offl** [comment]
Please include your rev hash

**Comment by Wombyte2** [comment]
> 
> 
> Please include your rev hash
can you tell my what my rev hash is:
TrinityCore rev. 07845b4 2020-10-05 01:55:35 +0300 (3.3.5 branch) (Win64, Release, Static)

**Comment by illfated** [comment]
Thanks for noticing. I have also noticed similar quest item issues a few times during the last month, but I thought it was my addons and/or using 34 slot bags (([Foror's Crate of Endless Resist Gear Storage](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=23162) (_This item is not available to players._)) to store my stuff, so I ignored the issue and just used GM commands to swap them in and out of the bank, or log out and back in to get the quest completed with the same items.

I may have sold some of the excess items or used the same type of items in my professions, like blacksmithing, engineering, leatherworking or tailoring, so I thought that the quest tracking got messed up by me when I caused the item count to fluctuate a lot, either by creating or gathering too many of those items.

This was particularly noticeable while doing the blacksmithing quests to deliver a specific amount of metal bars, but also for those involving crafted armor and weapons.

Sadly, I did not make any notes about which exact quests these were, but I will gladly report back now as soon as I see it happening again. I also need to note down if it happens when I keep all the items in my bags or if I have to move some of them between my bank bags and character bags to replicate this issue.

**Comment by Wombyte2** [comment]
@illfated what i can say is that I did not use any addons, and i also didn't use the 34 slot bag (my biggest one is a 22 slot bag, but it also happend to me with smaller bags), if that helps somehow :)

**Comment by illfated** [comment]
Sure thing, it helps a lot to see that you have confirmed my suspicion that it could be a source bug, by providing reasonable reproduction steps (although not naming any specific quests) and also confirming that you did not use addons and not use bags unavailable to normal players. This supports the validity of your bug report.

**Comment by dr-j** [comment]
Usually a sure way to reproduce this is with quests in blasted lands to correct animal parts and multiple quests require same items

**Comment by illfated** [comment]
True, that soup of quest items is a messy deal if you plan on handing in a lot of quests at once.

**Comment by offl** [comment]
Another detailed description here: #25669
I remember that bug since 2008 but two new issues in one month makes me think about recently broken opcodes

**Comment by offl** [comment]
While testing #26592 I crafted 5 items and then spawned quest-ender, then crafter last item (6th). Quest icon became yellow. Then I deleted one item and quest icon became grey. Then I crafted again 6th item and quest icon still was grey. But then I crafted 7th item and quest icon became yellow again. Funny.

**Comment by Freeman256** [comment]
I again encountered this problem during quest [Voren'thal's Visions](https://tbc.wowhead.com/quest=10024/vorenthals-visions). As you can see in the screenshot, I got 8 [eyes](https://tbc.wowhead.com/item=25744/dampscale-basilisk-eye), but [Arcanist Adyria](https://tbc.wowhead.com/npc=18596/arcanist-adyria) does not allow to close the quest.
![WoWScrnShot_072421_143824](https://user-images.githubusercontent.com/73786888/126867385-7faf5de9-6f7a-4c8a-b23e-350c2546cef3.jpg)
I tried to remove the eyes, create them with the **.additem** command and talk to the NPC again, but nothing changed. Then I tried to remove only 1 eye, create it with the **.additem** command and talk to the NPC again - this time I again could not complete the quest, but the question mark above the NPC's head turned gray. Moreover, when I created the eyes with the **.additem** (and when I picked them up from crocodiles), it was seen how the counts of collected items increased. Very strange.
![WoWScrnShot_072421_144615](https://user-images.githubusercontent.com/73786888/126867530-6d9cedff-4670-4e2b-bd59-270a7277305d.jpg)

**Comment by Jildor** [comment]
Seems caused by this @Shauren commit: 449bd9058bce87ade6831ba38d1a0b83b9cbfb18
because after that commit, first setcount of destroyed item and then check ItemRemovedQuestCheck and I think ItemRemovedQuestCheck check itemCount, so seems incorrect required item value and set IncompleteQuest
