### ISSUE TITLE
DB/Spell: Added missing difficulty mode to Ancient Rune Giant Stomp spell (Thorim - Ulduar)

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#25640]
**Description:**

Stomp:
https://www.wowhead.com/spell=62411/stomp
https://www.wowhead.com/spell=62413/stomp

http://www.worldoflogs.com/reports/oUqvm9IXfRTlQ3Va/xe/?s=8759&e=9156&x=spellID+%3D+62413

**Fix:**

```sql
-- Ulduar: Ancient Rune Giant (Thorim) missing Stomp spell difficulty 25 mode
DELETE FROM `spelldifficulty_dbc` WHERE `id`=62411;
INSERT INTO `spelldifficulty_dbc`(`id`, `spellid0`, `spellid1`) VALUES
(62411, 62411, 62413);
```

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/be8b251b58b82caf78df5a18f74af435b98bfe63

**Comment by illfated** [comment]
Cosmetic/readability/editability suggestion: When SQL lines are very short, like in the VALUES row, add a space between the comma-separated values to make it easier to select single values, because some editors or UIs can select all the values when double-clicking one of them. (Just a suggestion, not a request.)

**Comment by Jildor** [comment]
Edited 4 issues with suggestion ;)
