### ISSUE TITLE
DB/Quest: Uldaman Reagent Run Tracker Issue

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#25757]
**Description:**

The Magenta Fungus Cap counter is displaying too many objective update counts (x3)

<details>

![image](https://user-images.githubusercontent.com/66294837/103048943-5d977880-45e4-11eb-8359-86b6601c6859.png)

</details>

**Expected behaviour:**

Object count should only exist on 1 line

**Steps to reproduce the problem:**

1. Pick up the quest "Uldaman Reagent Run" from Ghak Healtouch in Loch Modan  (If you're alliance)
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=17  
2. Run inside Uldaman enterance and start collecting the Magenta Fungus Caps (1-2 per click)
3. Quest tracker counter displays and counts object on 3 different rows

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 95c4fcdeaf49 2020-12-23 21:44:44 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**

Windows 7 64bit

**Comment by Faq** [comment]
opcodes? But then for similar quests should be the same

**Comment by illfated** [comment]
Hmm, I have been leveling up a night elf character by playing through the quests and dungeons up to level 38, ever since this ticket was opened.

(just in case this was not obvious, here is an extra explanation based on how I had to find out what this issue is about)

I think it is important to notice the following: **This is not the quest log or quest log output you see. What you see is a display label when pointing to the activated GameObject where you can loot the item by the same name.** Allow me to confirm that the image above can easily be reproduced as follows:

1. Get the quest, either via commands or via game play in Thelsamar, Loch Modan
2. Teleport to [Hammertoe Grez** (2909) (`.go creature id 2909`)](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=2909)
3. Point your cursor at the gameobject
4. See the name label appear in the lower right hand corner of the screen:

![image](https://user-images.githubusercontent.com/38162891/103486980-fce91680-4e01-11eb-91fa-8c6167b1244b.png)  ![image](https://user-images.githubusercontent.com/38162891/103486990-1d18d580-4e02-11eb-9991-62c041fd96bc.png)

Figure 1: game addon Carbon Copy 3.3.5 / Figure 2: addons disabled, game client UI

***

<details>
<summary><b>9 individual screenshots from picking all 12 quest items, with and without addons</b> (click to expand)</summary>

![WoWScrnShot_010321_191735](https://user-images.githubusercontent.com/38162891/103486889-84825580-4e01-11eb-8c7c-b494ae75fb7c.jpg)

![WoWScrnShot_010321_192253](https://user-images.githubusercontent.com/38162891/103486899-8cda9080-4e01-11eb-9789-ce8333560774.jpg)

![WoWScrnShot_010321_192454](https://user-images.githubusercontent.com/38162891/103486902-9237db00-4e01-11eb-89ae-fe8588bb1012.jpg)

![WoWScrnShot_010321_192950](https://user-images.githubusercontent.com/38162891/103486908-96fc8f00-4e01-11eb-94ec-e7f24eb11021.jpg)

![WoWScrnShot_010321_193211](https://user-images.githubusercontent.com/38162891/103486914-a1b72400-4e01-11eb-8bc0-3ae5c21f16db.jpg)

![WoWScrnShot_010321_193442](https://user-images.githubusercontent.com/38162891/103486925-b09dd680-4e01-11eb-93e4-ce488db4d473.jpg)

![WoWScrnShot_010321_193838](https://user-images.githubusercontent.com/38162891/103486929-b5fb2100-4e01-11eb-9c67-c81e573a882b.jpg)

![WoWScrnShot_010321_195925](https://user-images.githubusercontent.com/38162891/103486931-bbf10200-4e01-11eb-923a-15f05bd199f5.jpg)

![WoWScrnShot_010321_195938](https://user-images.githubusercontent.com/38162891/103486933-c14e4c80-4e01-11eb-95a2-f3654b633dbb.jpg)

</details>

**Comment by illfated** [comment]
Trying to rethink this issue and looking in the `gameobject` table without finding clues to why the name comes up 3 times, and only when the quest is active, could this be some form or DBC communication or extraction issue?

- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=8047/magenta-fungus-cap
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?object=126049/magenta-cap-clusters
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?object=128293/magenta-cap-clusters

**Comment by illfated** [comment]
```sql
SELECT * FROM `gameobject_template` WHERE `entry` IN (126049, 128293);
```
```sql
 entry    type  displayId  name                  IconName  castBarCaption  unk1      size   Data0   Data1   Data2   Data3   Data4   Data5   Data6   Data7   Data8   Data9  Data10  Data11  Data12  Data13  Data14  Data15  Data16  Data17  Data18  Data19  Data20  Data21  Data22  Data23  AIName  ScriptName  VerifiedBuild
------  ------  ---------  --------------------  --------  --------------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ----------  -------------
126049       3       2090  Magenta Cap Clusters                                         1     259    5212       0       1       0       0       0  128196       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0                              12340
128293       3       2090  Magenta Cap Clusters                                         1     259    5212       0       1       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0                              12340
```
```sql
SELECT * FROM `gameobject` WHERE `ID` IN (126049, 128293) ORDER BY `guid`;
```
```sql
 guid    id      map   zoneId  areaId  spawnMask  phaseMask  position_x  position_y  position_z  orientation  rotation0  rotation1  rotation2  rotation3  spawntimesecs  animprogress  state   ScriptName  VerifiedBuild
-----  ------  ------  ------  ------  ---------  ---------  ----------  ----------  ----------  -----------  ---------  ---------  ---------  ---------  -------------  ------------  ------  ----------  -------------
11427  128293       0    1337    1337       1         1        -6118.81    -2911.51      210.97     -2.37365       0         0      -0.927184   0.374606            300           100     1                       0
11434  126049       0    1337    1337       1         1        -6171.99    -3029.98      222.44      1.18682       0         0       0.559191   0.829039            300           100     1                       0
11436  126049       0    1337    1337       1         1        -6294.55    -2925.82     232.211    -0.872665       0         0      -0.422618   0.906308            300           100     1                       0
11457  128293       0    1337    1337       1         1        -6064.14     -3091.2     250.611     -2.21657       0         0      -0.894935   0.446197            300           100     1                       0
11458  126049       0      38     923       1         1        -6096.92    -2979.69     207.402      1.44862       0         0       0.662619   0.748957            300           100     1                       0
11460  128293       0    1337    1337       1         1        -6138.42     -3099.2     223.775      2.98451       0         0       0.996917  0.0784606            300           100     1                       0
11461  126049       0    1337    1337       1         1        -6142.52    -3013.78     220.446            0       0         0              0          1            300           100     1                       0
11518  126049       0    1337    1337       1         1        -6061.82     -3019.5     230.494      -1.6057       0         0      -0.719339   0.694659            300           100     1                       0
12888  128293       0    1337    1337       1         1        -6061.82     -3019.5     230.494      -1.6057       0         0      -0.719339   0.694659            300           100     1                       0
12900  128293       0    1337    1337       1         1        -6142.52    -3013.78     220.446            0       0         0              0          1            300           100     1                       0
12901  128293       0    1337    1337       1         1        -6171.99    -3029.98      222.44      1.18682       0         0       0.559191   0.829039            300           100     1                       0
40674  128293      70    1337    1337       1         1        -358.599     100.755    -53.1931       1.0472       0         0       0.500001   0.866025            300           100     1                       0
40675  126049      70    1337    1337       1         1        -203.678     214.625    -46.4376      2.23402       0         0       0.898794   0.438372            300           100     1                       0
40677  126049      70    1337    1337       1         1          57.257     322.762    -41.8984    -0.418879       0         0      -0.207912   0.978148            300           100     1                       0
40679  128293      70    1337    1337       1         1         -164.64     301.678    -53.1613     -1.71042       0         0      -0.754709    0.65606            300           100     1                       0
40680  126049      70    1337    1337       1         1         1.60166     236.356    -32.3796     -2.63545       0         0      -0.968148   0.250379            300           100     1                       0
40682  126049      70    1337    1337       1         1        -95.1379     337.393    -47.0908     -1.43117       0         0      -0.656059    0.75471            300           100     1                       0
40684  126049      70    1337    1337       1         1        -112.397     230.632    -52.1536    -0.471239       0         0      -0.233445    0.97237            300           100     1                       0
40686  126049      70    1337    1337       1         1        -129.112      384.45    -39.9942     -2.04204       0         0      -0.852641   0.522496            300           100     1                       0
```

**Comment by offl** [comment]
Blizzlike bug
gameobject_questitem is responsible for that
```txt
GameObjectEntry     Idx  ItemId  VerifiedBuild  
---------------  ------  ------  ---------------
         126049       0    8047            12340
         126049       1    8047            12340
         126049       2    8047            12340
         128293       0    8047            12340
         128293       1    8047            12340
         128293       2    8047            12340
```
<details>

ServerToClient: SMSG_QUERY_GAME_OBJECT_RESPONSE (0x005F) Length: 163 ConnIdx: 0 Time: 08/21/2010 00:27:20.000 Number: 53248
Entry: 126049
Type: 3 (Chest)
Display ID: 2090
[0] Name: Magenta Cap Clusters
[1] Name: 
[2] Name: 
[3] Name: 
Icon Name: 
Cast Caption: 
Unk String: 
[0] Data: 259
[1] Data: 5212
[2] Data: 0
[3] Data: 1
[4] Data: 0
[5] Data: 0
[6] Data: 0
[7] Data: 128196
[8] Data: 0
[9] Data: 0
[10] Data: 0
[11] Data: 0
[12] Data: 0
[13] Data: 0
[14] Data: 0
[15] Data: 0
[16] Data: 0
[17] Data: 0
[18] Data: 0
[19] Data: 0
[20] Data: 0
[21] Data: 0
[22] Data: 0
[23] Data: 0
Size: 1
[0] Quest Item: 8047 (8047)
[1] Quest Item: 8047 (8047)
[2] Quest Item: 8047 (8047)
[3] Quest Item: 0 (0)
[4] Quest Item: 0 (0)
[5] Quest Item: 0 (0)

ServerToClient: SMSG_QUERY_GAME_OBJECT_RESPONSE (0x005F) Length: 163 ConnIdx: 0 Time: 08/21/2010 00:33:46.000 Number: 66238
Entry: 128293
Type: 3 (Chest)
Display ID: 2090
[0] Name: Magenta Cap Clusters
[1] Name: 
[2] Name: 
[3] Name: 
Icon Name: 
Cast Caption: 
Unk String: 
[0] Data: 259
[1] Data: 5212
[2] Data: 0
[3] Data: 1
[4] Data: 0
[5] Data: 0
[6] Data: 0
[7] Data: 0
[8] Data: 0
[9] Data: 0
[10] Data: 0
[11] Data: 0
[12] Data: 0
[13] Data: 0
[14] Data: 0
[15] Data: 0
[16] Data: 0
[17] Data: 0
[18] Data: 0
[19] Data: 0
[20] Data: 0
[21] Data: 0
[22] Data: 0
[23] Data: 0
Size: 1
[0] Quest Item: 8047 (8047)
[1] Quest Item: 8047 (8047)
[2] Quest Item: 8047 (8047)
[3] Quest Item: 0 (0)
[4] Quest Item: 0 (0)
[5] Quest Item: 0 (0)

</details>

**Comment by illfated** [comment]
Oh. OK, well, thanks for making us aware of this forgotten game behaviour. I presume those fields below (copied from your sniff sample) are related to your description.
```
[0] Name: Magenta Cap Clusters
[1] Name:
[2] Name:
[3] Name:
```
