### ISSUE TITLE
Core/Profession: Both Gnomish & Goblin Engineering can be learnt on same character

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#25855]
**Description:**

Similar to the Blacksmithing profession, engineering offers 2 paths (disciplines): Gnomish Engineering OR Goblin Engineering

You should not be able to undertake both paths - currently both are available and can be completed in normal game play.

<details>

I have Gnomish Engineering - however, I can still learn Gobin recipies even if I don't own Goblin Engineering.

![image](https://user-images.githubusercontent.com/66294837/104784823-372cbd80-57dd-11eb-85ad-55566c586750.png)

The quest to learn Goblin Engineering is also available ....

![image](https://user-images.githubusercontent.com/66294837/104784951-8115a380-57dd-11eb-95c8-674693bbf121.png)

... and can be completed. Allowing you to own both paths. Activating 1 also activates the other.

![image](https://user-images.githubusercontent.com/66294837/104785159-000adc00-57de-11eb-99bf-f6c20e4e1efc.png)

</details>

**Expected behaviour:**

You should only be able to choose 1 path with the other one no longer being attainable.

**Steps to reproduce the problem:**

(The steps I took ...)
1. Speak with [Springspindle Fizzlegear](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=5174#starts) in Ironforge
2. Choose [Gnomish Engineering](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=3632) and complete quest
   (NPC no longer offers Goblin Engineering discipline)
3. Head to Tanaris and speak with [Nixx Sprocketspring](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=8126#starts) in Gadgetzan
    (Optional - notice Goblin Engineering Recipies can be bought already)
4. Undertake his quest [Show Your Work](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=3639) which unlocks Goblin Engineering.
5. Complete it and you now have both

**Branch(es):**
3.3.5

TC rev. hash/commit:
TrinityCore rev. f6b22df9bd22 2021-01-13 00:53:43 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**
Windows 7 Ultimate x64 SP1

**Comment by illfated** [comment]
I was aware that it is possible to buy the engineering skills from both Goblin and Gnomish engineering at the same time (which I presume should not be available), but I was not aware that there is no blocking mechanism to hinder players from training both the Goblin and the Gnomish engineering skill at the same time. I wonder if this could be affected in any way by allowing more than 2 trade skills (I have enabled all 11 skills in my local setup). Going to check if the same applies to Horde engineering.

BTW, have you modified your game client to use the new (post-Cataclysm) models, could that affect the testing at all, in any way?

**Comment by Jinnaix** [comment]
As far as i can tell you shouldnt be able to get Quest 3639 without completing Quest 3638 and this one is not obtainable for players. Did you by chance added yourself quests with gm commands or modified anything in the database?

**Comment by TQPS** [comment]
I was alerted to the restriction from the game text:

`<name>, read this manual. If you want to learn more on gnome engineering, then take that manual to Tinkmaster Overspark here in Ironforge. **Remember - membership is permanent and prevents joining the other discipline**, so make sure you are sure before finishing his task!`

Taken from https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=3632

Since I too have all 11 professions - I kind of wanted both but knew I shouldn't - so I tested it. I believe the Blacksmithing equivalent works fine. I could not learn the other after doing the first one.

I am using 2 MPQ files for updated models only but not any that require a modified EXE as far as I'm aware. I'm not big on the modding and ATLAS for the dungeon maps is the only add I use.

Also using stock DB and I do not use GM commands or GM mode - my testing is all as a normal player.

If no one else can replicate it - I'm not going to sweat it - something's amiss my end and I'll accept it.

**Comment by illfated** [comment]
> If no one else can replicate it - I'm not going to sweat it - something's amiss my end and I'll accept it.

I have not tested your specific steps to reproduce the problem, but I suspect that the issue could very well be there. I think we should keep this ticket open for now, just to see how many would be able to replicate/reproduce the issue by testing as recommended.

**Comment by Jinnaix** [comment]
Okay, well first of all, you are right, Learning Gnomish Engineering in Ironforge first and going to Nixx afterwards let you obtain both specializations.

![WoWScrnShot_011621_010837](https://user-images.githubusercontent.com/37972361/104790507-b0a1bd00-5797-11eb-8d74-1a7e1d601544.jpg)

Second thing is - we miss a lot stuff for the trainer_spell table.
The Goblin recipes from your screenshot should be exclusive to Goblin Engineering, we miss Spell 20222 in ReqAbility1 in these cases.
We only have 5 Reciepes that require this skill while it should be somewhat around 22 in total. Im pretty sure this also goes for other profession specializations too.

Seems to be a bigger task. Summoning @offl to take a look at this issue.

**Comment by dr-j** [comment]
The quests to learn specialisation should believe quests to learn specialisation should be exclusive grouped so player can only ever complete quests to learn first specialisation and once player has started to chain they have to complete the chain they originally chose to change book must be used in tanaris but quests should remain unavailable since once done single chain to learn specialisation as once you have learnt you have to pay to change specialisation

**Comment by offl** [comment]
Looks like all over github nobody can explain how exactly you need to reproduce it

**Comment by offl** [comment]
Finally

**Comment by offl** [comment]
Ok, what I did is

.npc add temp 5174
take Gnome Engineering
.npc add temp 7944
complete Gnome Engineering
take The Pledge of Secrecy
.q c 3640
.q rew 3640

.npc add temp 8126

you can take Show Your Work from both 7944 and 8126 which are goblin and gnome engineers

this will allow to take only one of them

```sql
UPDATE `quest_template_addon` SET `ExclusiveGroup` = 3639 WHERE `ID` IN (3639,3641,3643);
```

However I don't get how those quests are implemented. There are 3 The Pledge of Secrecy and 3 Show Your Work and after completing one of The Pledge of Secrecy you can take any of Show Your Work for some reason. And it's weird because once you completed The Pledge of Secrecy from gnome engineer, you can take Show Your Work from a goblin engineer. Wasn't able to find any info about this except classic wowhead, classic wowhead is a complete copy of how those quests are implemented currently but as we can see that leads to 2 specs at once and is completely irrelogical in general.
Decided to make 3 unique completely separate chains.

In case I will return to this
SELECT * FROM quest_template_Addon WHERE id IN (SELECT id FROM quest_template WHERE logtitle='Goblin Engineering' OR logtitle='Gnome Engineering') ORDER BY NextQuestID
SELECT * FROM quest_template_Addon WHERE id IN (SELECT id FROM quest_template WHERE logtitle='The Pledge of Secrecy')
SELECT * FROM quest_template_Addon WHERE id IN (SELECT id FROM quest_template WHERE logtitle='show your work')
