### ISSUE TITLE
DB/Creature: Some School of Fish in Dustwallow Marsh have incorrect Z position

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#25858]
**Description:**

Some of the creature entries for [School of Fish](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=6145) have incorrect Z position and are therefore floating above the water

Some examples to highlight:

```sql
SELECT `guid`, `id`, `position_x`, `position_y`, `position_z` FROM creature WHERE guid IN (30570, 30558, 30959);
```

| guid | id | position_x | position_y | position_z | |
| ---: | ---: | ---: | ---: | ---: | ---: | 
| 30558 | 6145 | -3401.44 | -4368.7 | -2.09004 | |
| 30570 | 6145 | -2409.71 | -4230.6 | -7.86645 | <- Correct |
| 30959 | 6145 | -2812.1 | -4252.93 | -5.48593 | |

<details>

![image](https://user-images.githubusercontent.com/66294837/104797586-71b14d00-5813-11eb-8066-9cdca4c3143f.png)

| guid | id | position_x | position_y | position_z | |
| ---: | ---: | ---: | ---: | ---: | ---: | 
| 30558 | 6145 | -3401.44 | -4368.7 | -2.09004 | |

![image](https://user-images.githubusercontent.com/66294837/104797609-93123900-5813-11eb-93db-e2e377ecf655.png)

| guid | id | position_x | position_y | position_z | |
| ---: | ---: | ---: | ---: | ---: | ---: | 
| 30959 | 6145 | -2812.1 | -4252.93 | -5.48593 | |

</details> 

**Expected behaviour:**

This creature should be underwater.

<details>

This one is correct

![image](https://user-images.githubusercontent.com/66294837/104797619-b806ac00-5813-11eb-82c9-670777184def.png)

| guid | id | position_x | position_y | position_z | |
| ---: | ---: | ---: | ---: | ---: | ---: | 
| 30570 | 6145 | -2409.71 | -4230.6 | -7.86645 | <- Correct |

</details>

**Steps to reproduce the problem:**

1. Travel to the coast of Dustwallow Marsh  

<details>

![image](https://user-images.githubusercontent.com/66294837/104797767-bab5d100-5814-11eb-87bb-d04c05d6c66d.png)

</details>

2. Locations found in table above
3. Some of these are found above water, some are below

**Branch(es):**
3.3.5

TC rev. hash/commit:
TrinityCore rev. f6b22df9bd22 2021-01-13 00:53:43 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**
Windows 7 Ultimate x64 SP1

**Comment by Faq** [comment]
Those looks like https://www.nationalgeographic.com/animals/fish/group/flying-fish/

**Comment by illfated** [comment]
Yeah, those are definitely flying fish. Screenshot from 
```sql
Map: 1 (Kalimdor) Zone: 15 (Dustwallow Marsh) Area: 518 (Dreadmurk Shore) Phase: 1
X: -3399.055908 Y: -4372.308105 Z: 0.000000 Orientation: 5.375996
grid[25,23]cell[5,6] InstanceID: 0
 ZoneX: 64.710632 ZoneY: 39.020653
GroundZ: -6.103348 FloorZ: -6.103348 MinHeight: -500.000000 Have height data (Map: 1 VMap: 1 MMap: 1)
Liquid level: 0.000000, ground: -6.103348, type: 2, flags 2, status: 2.
```

<details>
<summary>Screenshot</summary>

![WoWScrnShot_011621_132439](https://user-images.githubusercontent.com/38162891/104811838-9d760800-57fe-11eb-8a88-75ecb735856f.jpg)

</details>

If possible, get a list of as many `creature`.`guid` entries as you can, because this could be happening anywhere in the classic part of Azeroth.

**Comment by offl** [comment]
Thing is those are sniffed positions but they are obviously always incorrect for creatures with random movement because it's always not default position where Blizz spawned creature but CURRENT position when someone sniffed them
So they may be in those positions in retail but in some cases we just need to move creature somewhere closer to their their spawn point

Default positions of moving \ randomly moving creatures can be sniffed but it will take literally years and you can't sniff unkillable creatures

30959 looks fine
