### ISSUE TITLE
Fix for NPCs Volgar entry 30483 and Brita entry 30484 AI

### ISSUE THREAD

**Issue by malcrom** [TrinityCore/TrinityCore#25909]
Description:

NPCs Volgar entry 30483 Brita entry 30484 have grunt sounds added to SAI which do not belong there.
Also the sounds where added to creature_text with no text as a hack to add to the AI system. This is a bad practice.

Expected behaviour:

These sounds are handled by core and should not be in the AI system.

Steps to reproduce the problem:

Aggro npcs and get wrong sounds on aggro

Sugested fix " With update id line from Meji"

```
-- Fix Volgar and Brita AI
DELETE FROM smart_scripts WHERE (entryorguid=30483 AND id=1) OR (entryorguid=30484 AND id=6);
UPDATE smart_scripts SET id=id-1 WHERE (entryorguid=30483 AND id > 1) OR (entryorguid=30484 AND id > 6);
DELETE FROM creature_text WHERE CreatureID IN (30483,30484);
```
Branch(es):

335

Core Revision

Core: bb24c6a
DB: TDB 837.20101

Operating system:

Win 10 x64

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/commit/d4cdc655d502eacdc9005684c4442e69fb0e585a#diff-01236184e3b4799f6638dc4680af49f0e528231f9459512e1ea172f08883bfa9R138
This was a more preferable solution than 20 action lists
They are from sniffs and they are not handled by core, handled by core sounds has Activity column filled https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=30483
If I remember correctly I even tested this

Also they cannot be handled by core because each text should be linked to corresponding sound https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=23990

**Comment by malcrom** [comment]
All ten of those sounds are not aggro sounds. Some are even mage sounds, as per Meji's research. having all ten in creature text to make scripting easy is bad practice.

**Comment by malcrom** [comment]
13533    1    NPCVrykulMaleMagicUser01
13534    1    NPCVrykulMaleMagicUser02
13535    1    NPCVrykulMaleMagicUser05
13536    1    NPCVrykulMaleMagicUser06
13537    1    NPCVrykulMaleWarrior01
13538    1    NPCVrykulMaleWarrior03
13539    1    NPCVrykulMaleWarrior04
13540    1    NPCVrykulMaleWarrior05
13541    1    NPCVrykulMaleWarrior07
13542    1    NPCVrykulMaleStandard03
don't make sense (warrior and mage sound for the same npc)

**Comment by malcrom** [comment]
You have 1 of 10 random sounds called on aggro and i'm 100% sure that is wrong.

**Comment by malcrom** [comment]
From your website you posted https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?sound=11947 that sound should be played on aggro.

**Comment by offl** [comment]
> Some are even mage sounds

Exactly why I checked few movies + one sniff and turned out creature can make both mage and warrior sounds. This logic also applies to all similar mobs and it's already implemented for mostly all of them long time ago

> having all ten in creature text to make scripting easy is bad practice

This is the only thing I can agree and disagree at the same time and the reason is because we don't know what is exact structure of Blizz's creature_text https://github.com/TrinityCore/TrinityCore/issues/25723#issuecomment-744705279
> There are no emotes and sounds in broadcast_text for creature_text for first 3 expansions, mostly. They added sounds to last WotLK dungeons and raids.

There are multiple examples where 1-2 texts and 1 sound without text comes as one group (on aggro, on death, special, etc.), mostly all of those cases are not handled properly(mostly all currently used texts without BroadcastTextId should have no text but only sound))

**Comment by offl** [comment]
ServerToClient: SMSG_PLAY_OBJECT_SOUND (0xCC57) Length: 12 ConnIdx: 0 Time: 11/29/2011 07:08:31.000 Number: 71292
Sound Id: 13540
GUID 2: Full: 0xF1307713008A8BB0 Type: Creature Entry: 30483 Low: 9079728

ServerToClient: SMSG_HIGHEST_THREAT_UPDATE (0x5E7B) Length: 23 ConnIdx: 0 Time: 11/29/2011 07:08:31.000 Number: 71293
GUID: Full: 0xF1307713008A8BB0 Type: Creature Entry: 30483 Low: 9079728

ServerToClient: SMSG_PLAY_OBJECT_SOUND (0xCC57) Length: 12 ConnIdx: 0 Time: 11/29/2011 07:08:50.000 Number: 71642
Sound Id: 14389
GUID 2: Full: 0xF1307714008A8BB1 Type: Creature Entry: 30484 Low: 9079729

ServerToClient: SMSG_HIGHEST_THREAT_UPDATE (0x5E7B) Length: 23 ConnIdx: 0 Time: 11/29/2011 07:08:50.000 Number: 71643
GUID: Full: 0xF1307714008A8BB1 Type: Creature Entry: 30484 Low: 9079729

**Comment by malcrom** [comment]
I was going by your website but sniff is best. What you are showing me is the two NPCs playing a sound on aggro. I have no issue with that. I'm wondering why  one has ten different sounds assigned to play on aggro. I'm sure you can play that one sound on aggro in the AI without adding ten creature text.

**Comment by offl** [comment]
Yes, sniff + videos, this is why I added all sounds, because in videos they plays more sounds
All similar creatures can play all those sounds and each sound is linked to unique text
But Volgar and Brita plays only sounds without texts. The only way to implement it currently is to add action list for each sound but I have no idea if we should go this way. Probably yes but at the same time both options sucks

**Comment by malcrom** [comment]
But you added all sounds to one GroupID in creature_text and they are only used on aggro. There is no way this is correct.

**Comment by offl** [comment]
With texts they too will be in group 0
https://github.com/TrinityCore/TrinityCore/commit/db8f2eadd445983689b14dc76530a3c7f992d9df#diff-931d19a62d6d416abc126c88e51755ccd72fa0b41838c00b84c12405d160f1a7R14

**Comment by offl** [comment]
Now it's clear it's a hack because on retail all texts are handled in a completely different way without creature_text, 15fa7c59e6a6e7e4364238606b94db9624965294
