### ISSUE TITLE
unable to resurrect without spirit healer if you die inside a raid on heroic mode and leave group

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#25969]
**Description:**

you are unable to resurrect without spirit healer if you die inside a raid on heroic mode and leave group and try to go raid to resurrect.

**Expected behaviour:**

you resurrect on area trigger of raid entrance. (outside raid)

**Steps to reproduce the problem:**

1. die in raid on heroic mode
2. leave group
3. get teleported out
4. try to resurrect on raid entrance
5. you cannot

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

1ff4a7e75b56

**Operating system:** 

N/R

**Comment by Aokromes** [comment]
on master branch you are teleported alive to raid instance entrance.

**Comment by J-Cieplinski** [comment]
Seems to be working as intended in 6e1b9d775c

**Comment by Aokromes** [comment]
nope still bug if heroic mode.

**Comment by Aokromes** [comment]
somewhere at src/server/game/Maps/MapManager.cpp needs to be fixed
Map::EnterState MapManager::PlayerCannotEnter(uint32 mapid, Player* player, bool loginCheck)

**Comment by CraftedRO** [comment]
PlayerCannotEnter -> PlayerCanEnter ? :D woud be great if c++ was easy and logic like this

**Comment by CraftedRO** [comment]
for some resons I coudn't reproduce this , In ruby sanctum works as intended , in toc same , in icc you need achiev to get inside alive so if u die you need achiev too idk

**Comment by illfated** [comment]
(just for reference, direct source link)
https://github.com/TrinityCore/TrinityCore/blob/1ff4a7e75b56e1ad68d83f75b493a42ac1ae85c3/src/server/game/Maps/MapManager.cpp#L125-L207

**Comment by CraftedRO** [comment]
Im not so sure if this is a bug , after you die in a raid (heroic) > you leave party while one minute teleport timmer is on screeen , atm when you get teleported out at spirit healer , your corpose will be teleported out near spirit healer too in tc 3.3.5 , and of course you can't resurect back in raid because you get error : you'r corpose is not in that instance , but atm you are able to resurect near outside near spirit where the corpose is being teleported .

I died in ruby sanctum 25 heroic.
![WoWScrnShot_041021_184000](https://user-images.githubusercontent.com/24683355/114275706-2da5a100-9a2c-11eb-993f-16099fe45513.jpg)

**Comment by Aokromes** [comment]
[11:45:27] You have left the raid group.
[11:45:53] You must have defeated The Lich King in the 10 Player raid before attempting 10 Player Heroic difficulty.

changing to 10n ressurrects you properly on entrance outside raid.

**Comment by CraftedRO** [comment]
I will try to look if it's about wrong check order or if maybe we can add a bypass to respective check to ignore achievement kind checks if player have corpose inside.

**Comment by Aokromes** [comment]
394f125fdc158a37b46dcb4343a8266d141ec2c7
