### ISSUE TITLE
Wrong attack speed of dire maul creatures

### ISSUE THREAD

**Issue by T1ti** [TrinityCore/TrinityCore#26012]
**Description:**

Currently the attack speed of most ogres in dire maul is set to ~1.175. 
![image](https://user-images.githubusercontent.com/40864460/106552342-6f3f3a80-6517-11eb-9159-4d4e05be7b23.png)

I was running a dungeon with friends and noticed there was something wrong because how low their damage was, our tank was taking nearly no damages in shit green gear, so I did some reasearch to try to find a reason and noticed their dmg on the aowow database was super low.
i'm mostly gonna use Gordok reaver for this issue, i haven't looked at all of them, this is the main one I analyzed but I Believe the others are also wrong.
![image](https://user-images.githubusercontent.com/40864460/106552499-c2b18880-6517-11eb-90fe-7cbc1a379122.png)
Based on official data from Blizzard's bestiary book (from TBC) : 499-675dmg
![image](https://user-images.githubusercontent.com/40864460/106552545-d6f58580-6517-11eb-98cc-333f739dca19.png)

I don't have sniffs and I have no idea if AS is sniffable so I used other methods.

notice :  
1.175 / 2 = 0.5875. (attack speed)
0.5875 * 499 = 293.1625
499 being the min dmg of this creature in blizzard's official book, and in trinity core they have exactly 293 min dmg. By converting blizz dmg to 1.175 AS you get TC's value. Which proves blizzard is using 2.0

2nd proof : video (from Classic https://youtu.be/vVupB139VcU?t=689 ) 
https://i.gyazo.com/c73501e70e317a5ad0df2d36ae73e670.mp4 
Look at the left ogre, roughly, he hits at 2.601then he hits again at 4.602.

- Their dps is the same so how would they do less damage ? Because of blocks mostly. Blocks are a flat values so high attack speed mobs do a lot less damage to shield tanks. Also many of those mobs have cleaves or mortal strikes that might do less damage because of this(not sure)

**Expected behaviour:**

2000 is correct attack speed, this is also the value blizzard uses by default that most humanoids and creatures in the game have. This is also the values other emulators use for those creatures

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

92c8ffc047ea35ea9a534a878cd4be5726f20974

I might calculate some other creatures later using first technique which isn't very time consuming, if you guys think it is correct, I'm not a math genius this formula was pure instinct and I got the exact right value on first try.

**Comment by offl** [comment]
Things are worse actually. Those funny numbers added from random number generator were there probably since very beginning. Right now 1500+ creatures has obviously wrong attack time (so damage). Mostly they are temp spawns or located in instances and they all are related to TBC or classic. So yeah, they weren't updated from sniffs in tbc or wotlk

What I'm going to do is set it to default without sniffs and the reasons why is because we don't have sniffs of all of those creatures, nobody does. Also it doesn't really matter how exactly they will be updated since 2000 is default value.
It's not dangerous because I know which ones to update but yeah, some of current values are closer to correct than 2000.
But it's 50-100 cases vs 1500 and after all it's exactly how 335 works: 2000 was default value since beggining and speed_walk 1.14 too. Now we just update those valus from sniffs if sniffed value is different

Speed too was added from random number generator but speed is different story. Considering there is a chance everything related to speed will be removed and reworked, I don't care much about speed. But it's possible in nearly all cases to set walk speed to default without corrupting sniffed values because we know which values Blizz uses. And in mostly all cases this change will be correct because 1 / 1.14 are default speed values. In some cases it's not possible because 1.2 is valid speed walk and 1.2 is also used as old `speed`. So there's no way to update it without sniffs or without corrupting correctly added 1.2
It was really good if 10 years ago speed_walk was just changed to 1 but it didn't happened. There were absolutely no reason to hold old values

**Comment by gygyti** [comment]
where can we get the correct data?
will wowhead suitable?
if wowhead is suitable for getting 2-3 thousand data on creatures and their attacks, then I can do it
