### ISSUE TITLE
Stinglasher

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26086]
Stinglasher in Feralas doesn't give in to aggression. If you start to attack him, he will go further 
[https://www.wowhead.com/npc=14661/stinglasher](https://www.wowhead.com/npc=14661/stinglasher)
Entry 14661

3.3.5
rev. 0dee695

**Comment by offl** [comment]
Ohhhh I love this

Ok, here's what happened
I removed flight state
```sql
CreatureId  Ground    Swim  Flight  Rooted   Chase  Random  
----------  ------  ------  ------  ------  ------  --------
     14661       0       1       1       0       0         0
```
Here
```sql
CreatureId  Ground    Swim  Flight  Rooted   Chase  Random  InteractionPauseTimer  
----------  ------  ------  ------  ------  ------  ------  -----------------------
     14661       0       1       0       0       0       0                   (NULL)
```

And now creature is treated as aquatic by core. This. This is exactly why I said those should be flags. Because it's way much easier to work with one flag rather than with 5 bools which are linked together and the data of the whole table is incomplete, based on nothing and should be cleaned before retail data can be used. They are flags even in retail and they don't have old shitty data.

**Comment by offl** [comment]
```sql
--
UPDATE `creature_template_movement` SET `Ground` = 1 WHERE `CreatureId` = 14661;
```

**Comment by gygyti** [comment]
looks wonderful!  Ohh I cant update the table without rebooting the server to check this

**Comment by illfated** [comment]
BTW, is it correct for a constantly flying creature, especially one of the insect-like ones, to be able to swim?
