### ISSUE TITLE
Quest item: Jagged Shard

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26136]
Here's an interesting problem:

The item **Jagged Shard (43242)** must drop with a 100% chance (is needed to get the **quest=13136**).
This item dropped to me, but I could not put it in the bag (the massage is "You cannot use this item").
After I re-entered the game, this item stopped dropping at all. 
However, if you look at the **.npc showitem** command, the mob has this item 

[https://www.wowhead.com/item=43242/jagged-shard](https://www.wowhead.com/item=43242/jagged-shard)
[https://www.wowhead.com/quest=13136/jagged-shards](https://www.wowhead.com/quest=13136/jagged-shards)
[https://www.wowhead.com/item=43259/jagged-shard](https://www.wowhead.com/item=43259/jagged-shard)

3.3.5
rev. 0dee695

**Comment by dr-j** [comment]
Dont think this is loot issue in order to accept jagged shards player must have already have turned in Spill Their Blood item will drop while on this quest but you cant accept quest until spill your blood is turned in if I remember this was intentional as players would end up with this quest but been unable to complete it ever if player still had in log and turned in killing two scourge with one skeleton which causes permanent phase change in area and there was bigger issue here before last fix to this where player could skip previous quests in chain and skip straight to these quests and when player got the quest which should have led to this chain and then not be able to turn in quests due to dark rider arly been missing (due to phasing which is correct) or due to having turned in killing two scourge with one skeleton before earlier quests in chain)

**Comment by dr-j** [comment]
One note though item 43242 (quest starter item) has condition so this item will only drop while player has quest 13134 (Spill their blood) taken but not complete in quest log or conditiontype 9 and not if they have it complete in log or are already rewarded for it

**Comment by offl** [comment]
Already fixed
