### ISSUE TITLE
why i can't find  the Riding Trainer Storm City

### ISSUE THREAD

**Issue by byMoWen** [TrinityCore/TrinityCore#26152]
Description:
why i can't find  the Riding Trainer Storm City
![image](https://user-images.githubusercontent.com/28382859/109101859-85c96200-7762-11eb-9e4a-89a1b285a428.png)

Branch(es):

3.3.5

Notes:
  TrinityCore-TDB335.21021.tar.gz
![微信图片_20210225121226](https://user-images.githubusercontent.com/28382859/109101974-be693b80-7762-11eb-9765-65f31113f20d.png)

**Comment by byMoWen** [comment]
TrinityCore-3.3.5-attackstart
CMake Deprecation Warning at CMakeLists.txt:22 (cmake_policy):
  The OLD behavior for policy CMP0005 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


CMake Deprecation Warning at CMakeLists.txt:24 (cmake_policy):
  The OLD behavior for policy CMP0043 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

CMake Warning (dev) at dep/boost/CMakeLists.txt:50 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable Boost_ROOT is set to:

    E:\WorkTools\boost_1_70_0

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by byMoWen** [comment]
when i use the boost_1_70_0 build  3.3.5-attackstart  ， the above warning was issued,

**Comment by illfated** [comment]
> why i can't find the Riding Trainer Storm City

Stormwind city did not have a riding trainer before Cataclysm. They were added in patch 4.0.3a .
Before Cataclysm, you had to go to Eastvale Logging Camp in Elwynn Forest.


> TrinityCore-3.3.5-attackstart

Latest commit added in that branch was on May 15, 2019. If you need support using TrinityCore sources, use either the 3.3.5 branch or the master branch, because the other branches are not supported by the issue ticket system. They are only provided for you to experiment on your own and to use material not present in the main branches.

Please also note that some warnings can be caused by Boost or older versions of CMake.
