### ISSUE TITLE
902—Startup error-DBC

### ISSUE THREAD

**Issue by dfree686** [TrinityCore/TrinityCore#26164]
![未标题-2](https://user-images.githubusercontent.com/36804851/109184265-c7412800-77c9-11eb-87ad-6c374f13c029.jpg)
wow9.0.2.37474    Map file extraction decompression, always lost files, resulting in the server can not start! 

"SceneScriptText.db2"

This file is always missing,There is no such document.

**Comment by MaxtorCoder** [comment]
Follow issue template please.

**Comment by dfree686** [comment]
What template? Is there a link?

**Comment by dfree686** [comment]
Map decompression has always been done according to the tutorial, I don't know why it didn't work until 902.

**Comment by illfated** [comment]
Just to clear up any misunderstanding regarding the first red marking in your cmd image: That vnaps error text happens to all of us, regardless of branch, and is to be expected. It is not related to your issue.

Regarding the error while reading 'G:\[(zhCN_path_name)]\World of Warcraft\dbc\zhCN\SceneScriptText.db2' :
I don't know if that is caused by a source issue or if it is simply a read error for that particular file (local read/write error).

**Comment by Aokromes** [comment]
i suggest  you to try rename directory containing wow client to games or something like that.

**Comment by dfree686** [comment]
Move the "world of Warcraft" folder to the root of the disk without any Chinese, which is the same error.

**Comment by illfated** [comment]
Hmm, OK, I see. Well, there is still the possibility that it could be caused by a damaged or incomplete `SceneScriptText.db2` file, please check if that could be the cause.

**Comment by dfree686** [comment]
Problem solved!
It may be caused by the incompleteness of the client after automatic update. After re installing the client, the extraction is successful!
