### ISSUE TITLE
Core/Spell - Not working spells, Shaman class 9.0.2

### ISSUE THREAD

**Issue by DintyGadget** [TrinityCore/TrinityCore#26182]
**Description:**
The following spells do not work:
(318038) Flametongue Weapon - Does nothing when used.
(8143) Tremor Totem - The summoned totem does nothing, or is not summoned at all (Npc id: 5913). 
(5394) Healing Stream Totem - The summoned totem does nothing (Npc id: 3527). Heal spell from totem, 52042
(192222) Liquid Magma Totem - The summoned totem does nothing (Npc id: 97369). Totem using spell 192226 (this only visual)
(73920) Healing Rain - Does nothing when used. Visual spell 147490, heal spell 73921.
(192058) Capacitor Totem - The summoned totem does nothing (Npc id: 61245). Totem using spell, 118905.

**Expected behaviour:**

(318038) Flametongue Weapon - Should apply an effect to the weapon on the left hand when used.
(8143) Tremor Totem - When used, must remove stun debuffs from party members or allies within 30m.
(5394) Healing Stream Totem - Heals allies (47% of Spell power) within 40m every 2 seconds for 15 seconds.
(192222) Liquid Magma Totem - The summoned totem attacks the enemy with liquid magma.
(73920) Healing Rain - Heals allies within the radius for 10 seconds. [(26.5% of Spell power) * 6 * 2 / 2]
(192058) Capacitor Totem - When a totem is summoned, after 2 seconds it explodes, stunning enemies within a radius of 8m, for 3 seconds.

**Steps to reproduce the problem:**

1. Create a Shaman class character.
2. Give a character 60 lvl.
3. Try using any of the spells listed.

**Branch(es):**

master

**TC rev. hash/commit:** 

c86cffe

**Operating system:** 

Windows 10 x64

**Comment by Faq** [comment]
1 bug report per issue, easier to handle.

**Comment by matanshukry** [comment]
> 1 bug report per issue, easier to handle.

I actually like this 1 bug report for class, at least in the current situation where most spells aren't scripted.

**Comment by matanshukry** [comment]
Started working on it:

* Flametongue - not sure what buff is given or if its' something special since the icon is the weapon icon (I think)
* Tremor Totem - actual effect fixed. Does it have some visual effect though? either on the ground and/or on the totem buff list?
* Healing Stream Totem - This one currently works. It will only target units with non-full health. If everyone has full health, it will cast it on it self.
* Liquid Magma Totem - which spell does the actual damage?
* Healing Rain - Not familira enough with area spells that "stick" to a target location. I thinkt they create npc, but if so - which one is it? If through spell, which one is that?

I'll try to look for more information later, if anyone knows anything though it would be helpful.

**Comment by Naddley** [comment]
Liquid Magma Totem -> I see only the name in Details! Addon there is nothing in Combat log. I think its https://de.wowhead.com/spell=192231/fl%C3%BCssiges-magma#modified-by

**Comment by DintyGadget** [comment]
NPC that works for healing rain 73400.

**Comment by matanshukry** [comment]
@DintyGadget the npc says "healing RAN" and not rain, looks a bit suspicious. Are you sure it's that one?

**Comment by DintyGadget** [comment]
> @DintyGadget the npc says "healing RAN" and not rain, looks a bit suspicious. Are you sure it's that one?

At least another core uses exactly this npc

**Comment by Naddley** [comment]
Tremor Totem -> Tested with my shaman on Retail. There is no animation or Buff if you get the "fear dispell" or after that.
