### ISSUE TITLE
Riding Horse in Tanaris is Attackable (Wrong Faction ID)

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#26224]
```
UPDATE `creature_template` SET `faction`=35 WHERE `entry`=8883;
```

**Description:**

https://github.com/azerothcore/azerothcore-wotlk/issues/4674
Those Riding Horses are attackable.

**Expected behaviour:**

A H both green/friendly.

https://classic.wowhead.com/npc=8883/riding-horse

**Steps to reproduce the problem:**

1. Go to Gadgetzan-Tanaris
2. Find horses
3. Notice that you can attack them.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 84ad438d15cf

TrinityCore rev. 84ad438d15cf 2021-03-05 22:22:56 +0100 (3.3.5 branch) (Win64, Release, Static)

**Operating system:** 

Windows 10 x64

before
![before](https://user-images.githubusercontent.com/24683355/110784654-9c97aa80-8272-11eb-8fa7-810e45d62c44.jpg)
after
![after](https://user-images.githubusercontent.com/24683355/110784699-a91c0300-8272-11eb-9b73-ea700268a68c.jpg)

**Comment by offl** [comment]
This fix changes correct faction for the ones spawned in another locations, in other words this fixes faction in one place and breaks in another
faction column can be changed only in less than 0.1% cases, and not in this case since correct and default faction is not 35

We can wait for #25803 or create guid-scripts in SAI like I already did in https://github.com/TrinityCore/TrinityCore/commit/c91c3cb09f6288ba66949a544b81d64099ead3e1#diff-e81f1e6829f7cf897fc05cc05a4e9b717470540cc335d00cc919a228ebea3d9bR49
