### ISSUE TITLE
DB/Loque'nahak updating SAI

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#26267]
```
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 32517;

DELETE FROM `smart_scripts` WHERE (`source_type` = 0 AND `entryorguid` = 32517);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(32517, 0, 0, 0, 0, 0, 100, 0, 0, 0, 12000, 15000, 0, 11, 61184, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Loque\'nahak - In Combat - Cast Pounce'),
(32517, 0, 1, 0, 0, 0, 100, 0, 1000, 5000, 8000, 13000, 0, 11, 61186, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Loque\'nahak - In Combat - Cast Frozen Bite');
```

**Description:**

Loque'nahak does only cast [Pounce ](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=61184).

**Expected behaviour:**

According to Gamepedia [Loque'nahak](https://wow.gamepedia.com/Loque%27nahak) shoud cast [Pounce ](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=61184) and [Frozen Bite](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=61186) .

**Steps to reproduce the problem:**

1. Go to Sholazar and find Loque'nahak
2. Attack him
3. Notice it does only cast Pounce.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 8c3cddd0d221 

TrinityCore rev. 8c3cddd0d221 2021-03-15 17:34:11 +0000 (3.3.5 branch) (Win64, Release, Static)

**Operating system:** 

Windows 10 x64

**Comment by offl** [comment]
Just in case finally wrote it https://github.com/offl/ScriptInfo/wiki/How-to:-Web-archive#how-to-visit-archieved-page-wowhead
It's pretty basic and incomplete description
I'm too slow in writing such things because they takes lot of time but I'd like to create more pages like this just to add link to them if needed instead of writing same things every time

**Comment by CraftedRO** [comment]
well I guess Il stop with SAI things since I can't prove other than gamepedia ,web.archive may be a solution but it will take too much to check last year / day / month closest to 3.3.5 patch , so I had some fun for the moment playng with this :)))

**Comment by offl** [comment]
I knew it
Too much info, right?

Scripts are fine, I'll just edit them later before push because there are some things you miss

> I can't prove other than gamepedia ,web.archive may be a solution but it will take too much to check last year / day / month closest to 3.3.5 patch

2010 year is 3xx, you don't need to find closest to 3.3.5 because there's no real difference between archived in august and november. Moreover sometimes page will be archived only once
