### ISSUE TITLE
DB/Pustulent Colossus missing SAI

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#26274]
```sql
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 32482;

DELETE FROM `smart_scripts` WHERE (`source_type` = 0 AND `entryorguid` = 32482);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(32482, 0, 0, 0, 0, 0, 100, 0, 7000, 8000, 8000, 9000, 0, 11, 28405, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, "Pustulent Colossus - IC - Cast 'Knockback'"),
(32482, 0, 1, 0, 0, 0, 100, 0, 6000, 7000, 12000, 12000, 0, 11, 63546, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, "Pustulent Colossus - IC - Cast 'Stomp'");
```

**Description:**

Atm this ones does only auto attack.

**Expected behaviour:**

According to [Gamepedia](https://wow.gamepedia.com/Pustulent_Colossus) and old wowhead Pustulent Colossus shoud cast : [Knockback](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=28405) and [Stomp](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=63546)
view-source:http://web.archive.org/web/20100415081520/http://www.wowhead.com/npc=32482

**Steps to reproduce the problem:**

1. Go to the Icecrown and find Pustulent Colossus
2. Attack him
3. Notice does only auto attack you.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 8c3cddd0d221

TrinityCore rev. 8c3cddd0d221 2021-03-15 17:34:11 +0000 (3.3.5 branch) (Win64, Release, Static)

**Operating system:** 

Windows 10 x64

**Comment by CraftedRO** [comment]
I tested the above script ingame and it seems that knockback part works well but the stomp not really I think is related to target_type not sure if SMART_TARGET_SELF is the right choice for that kind of spell

**Comment by offl** [comment]
512 is SMART_EVENT_FLAG_WHILE_CHARMED | 512 | 0x200 | Event can occur while player controlled
Don't use it

***

11, 28405, 2, 0, 0, 0, 0
11, 63546, 2, 0, 0, 0, 0

2 is SMARTCAST_TRIGGERED | 2 | 0x02 | Triggered (this makes spell cost zero mana and have no cast time)
It also allows creature to cast spells while stunned, we don't want that

*** 

```sql
(32482, 0, 0, 0, 0, 0, 100, 512, 3000, 5000, 3000, 7000, 0, 11, 28405, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Pustulent Colossus - IC - Cast Knock Back'"),
(32482, 0, 1, 0, 0, 0, 100, 512, 4000, 6000, 5000, 9000, 0, 11, 63546, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Pustulent Colossus - IC - Cast Stomp'");
```

It will throw error, ```sql can show potential problems > '"),

**Comment by CraftedRO** [comment]
is now a bit better ?

**Comment by offl** [comment]
>is now a bit better ?

Yep

More about timers
This creature has 80k health (elite(read high damage)) and uses Knockback (... it knockes you back) and Stomp (main damage spell)
It's important to understand what you can't cast such spells so often because when you test that script in game with GM, everything may look correct to you
But when you will tank that creature without GM(let's say you will have 20-25k HP), you will notice that it uses spells too often (you will be knocked back every 5 seconds)
Of course some creatures are crazy but in general Blizz tries to not kill players at every step. For example in raids in case of large packs of not strong mobs they can make timers more random and decrease chance to cast spells

Of course we are talking about guessed timers only, but it's still important to guess more properly

For example melee spells like Hamstring, Mortal Strike, Cleave usually are treated as main attack and may be initially used after 5-15 seconds, maybe less, maybe more
Special attacks like Knockback may has initial timers 10-20 seconds and repeat after 10-15 to 20-25-30 seconds because they are game-changing spells (like CC spells), they knocks player from creature and also mostly all knockbacks reduces threat. CC stuns player. If CC will be used too often, you will be killed really fast during normal gameplay
15 seconds is not too much in case of WotLK, TBC and classic
