### ISSUE TITLE
Bride of the Enbalmer -  invisible as of late

### ISSUE THREAD

**Issue by NightrunLP** [TrinityCore/TrinityCore#26595]
**Description:**

During the "Bride of the Enbalmer" questline in Duskwood, Eliza (the wraith) is invisible since the latest build. In older builds (April) she was still visible. She spawns and attacks you, but you can't target and see her.

**Expected behaviour:**

She should be visible of course.

**Steps to reproduce the problem:**

https://classic.wowhead.com/quest=253/bride-of-the-embalmer
https://de.classic.wowhead.com/npc=314/eliza

Get yourself the quest, go to her grave and dig in the dirt. She spawns invisible, her guard is still visible.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 7c6ee033e05f+ 2021-06-07 00:32:57 +0300 (HEAD branch) (Unix, RelWithDebInfo, Dynamic)
Using SSL version: OpenSSL 1.1.1d  10 Sep 2019 (library: OpenSSL 1.1.1d  10 Sep 2019)
Using Boost version: 1.67.0
Using MySQL version: 100327
Using CMake version: 3.13.4
Compiled on: Linux 4.19.0-16-amd64
Automatic database updates are disabled for all databases!
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/wow/server/data/maps. Total size: 291014951 bytes
vmaps directory located in /home/wow/server/data/vmaps. Total size: 657797442 bytes
mmaps directory located in /home/wow/server/data/mmaps. Total size: 1961820680 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.21051

**Operating system:** 

Linux Debian 10

**Comment by offl** [comment]
Because after https://github.com/TrinityCore/TrinityCore/commit/ee839fee1ec059e618ddcc296c19ed16d336e896 action_param5 is used as SmartActionSummonCreatureFlags and 1 is PersonalSpawn. And somehow currently action_param5 = 1 is used in 40 actions even if that param wasn't used by core before https://github.com/TrinityCore/TrinityCore/commit/ee839fee1ec059e618ddcc296c19ed16d336e896
So in that case gameobject is summoner. So Eliza became personal spawn of gameobject or something like that

Dunno how gameobject can have PersonalSpawn and why creature still can 'aggro' me but can't damage me or cast spells at me if it's not my PersonalSpawn
Somehow I also see what she says
Maybe it's because gameobject is summoner, dunno

@jackpoz you may be interested in this

**Comment by offl** [comment]
Non-empty fields not used by core is same problem as invalid boolean values, imho

**Comment by jackpoz** [comment]
@offl I discussed some days ago in irc about warning on unused parameters, that's the next step after the bool pr gets merged
