### ISSUE TITLE
[3.3.5 DB/Quest] Incorrect display of Russian text during the quest "The Exorcism of Colonel Jules" (10935)

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#26718]
### Description

Ref. https://github.com/TrinityCore/TrinityCore/issues/26716, https://github.com/TrinityCore/TrinityCore/issues/26715, https://github.com/TrinityCore/TrinityCore/issues/26645 and https://github.com/TrinityCore/TrinityCore/issues/26629#issuecomment-869051571
During quest [The Exorcism of Colonel Jules](https://tbc.wowhead.com/quest=10935/the-exorcism-of-colonel-jules), [Colonel Jules](https://tbc.wowhead.com/npc=22432/colonel-jules-saved) in the Russian version of the game refers to the character by gender. For some reason, construction **$Gmale:female;** doesn't work. See screenshots below for clarity. Should I keep reporting similar issues, or can you combine them into one big one? Perhaps this problem manifests itself in other localizations besides Russian. I am already uncomfortable making similar messages about this error, so sorry if I already pissed you off, but the problem exists. Maybe scan a table broadcast_text_locale in database for the presence of construction **$Gmale:female;**, and if it is available, change some values in Smart_Scripts? As I mentioned earlier, my knowledge is not enough to fix such problems when they are detected, but I would like to do it. 

![WoWScrnShot_071721_235318](https://user-images.githubusercontent.com/73786888/126049427-64f582ec-87a2-4215-ab4c-2824245d84dc.jpg)
![WoWScrnShot_071721_235429](https://user-images.githubusercontent.com/73786888/126049428-2a766c0a-0043-453e-bedd-5d346d03792c.jpg)

### Expected behaviour

Construction **$Gmale:female;** should work during the execution of not only this quest, but in general always. 

### Steps to reproduce the problem

1. Launch the Russian version of the game;
2. Create an alliance character;
3. **.character level 59**;
4. Complete quests in Honor Hold, and take the quest [The Exorcism of Colonel Jules](https://tbc.wowhead.com/quest=10935/the-exorcism-of-colonel-jules);
5. Make sure that [Colonel Jules](https://tbc.wowhead.com/npc=22432/colonel-jules-saved) is addressing the player by gender, and construction **$Gmale:female;** does not work in the Russian version of the game (and possibly in some other localizations); 
6. Get upset because you have to face this problem again and again, and there is no universal solution to it.

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/a47926ceab7091dd0c06b6bb16a0d1f64bd30a63
TrinityCore rev. 2021-07-16 ‏‎18:51:35 +0300 (3.3.5 branch) (Win64, Release, Static)

### Operating system

Win7 SP1 x64 with all updates (build 6.1.7601).

### Custom changes

None.

**Comment by offl** [comment]
> Should I keep reporting similar issues, or can you combine them into one big one?

Each script requires different approach and different fix, it's easier to fix one issue, close it and jump to another

> Maybe scan a table broadcast_text_locale in database for the presence of construction $Gmale:female;, and if it is available, change some values in Smart_Scripts?

This and script from previous issue are not handled in SAI

This returns only texts not inside action lists and in general is really limited, it shows probably less than half of texts with $G. I even don't know if it's possible to select all texts with $G and where they are used in SAI, I mean, it will be hard enough just to create select query
Easiest way is select all texts and check each script where they are used. After all that is exactly what any dev will do to fix any of those cases because you need to see whole script with all actions to change correctly one row or rewrite script
```sql
SELECT * FROM smart_scripts a LEFT JOIN creature_text b ON a.entryorguid=b.creatureid AND a.action_param1=b.groupid LEFT JOIN broadcast_text_locale c ON c.id=b.broadcasttextid WHERE a.source_type=0 AND action_type=1 AND locale='ruru' AND (c.text LIKE '%$g%' OR c.text1 LIKE '%$g%')
```
Half of them uses target_type=1, so half of those texts displayed incorrectly in game

We can't just change 'some values' to fix all of them, lots of those scripts should be updated and in some of those cases it will require to spent lot of time by rewriting them
In some cases all we need is indeed change 'some values'

Considering we treat locales as cosmetics and fixing those bugs will require lot of time and experience, better to report all those cases in a single issue
Fixing that issue in some cases will require to create additional actions in scripts and I don't think it's a good idea because with current scripting engine it will make those scripts more complicated while we want to make SAI less complicated in general. If some parts of SAI will be updated, fixing that issue in some cases will be easier and by using more correct solutions

**Comment by Aokromes** [comment]
here maybe 
Talk(SAY_BARADA_2);
Talk(SAY_BARADA_3);
etc
needs tp ne
Talk(SAY_BARADA_2, player);
Talk(SAY_BARADA_3, player);
like on other c++ scripts.

**Comment by Freeman256** [comment]
**offl**
So, it turns out, I need to report all such problems right here in the message with this error (https://github.com/TrinityCore/TrinityCore/issues/26718)? I understand that there will be a lot of similar errors, and I would not like to create many new messages about such errors. I could paraphrase the NPC's lines with the construction **$Gmale:female;** to avoid referring to the gender of the characters, but this would not be a blizzlike, but the meaning would be preserved. Maybe I should do this in the future? Or do I not need to make such corrections, and report each such issue in a separate thread?

By paraphrasing, I mean, for example, this (in this quest):
"Move away, this fool (M) / fool (F) is mine."
to this:
"Move away, your assistant belongs to me."

**Comment by offl** [comment]
> So, it turns out, I need to report all such problems right here in the message with this error (#26718)?

Create another issue with a list of creature entries with wrongly displayed $G
For example here entry is 22432

> I could paraphrase the NPC's lines with the construction $Gmale:female; to avoid referring to the gender of the characters, but this would not be a blizzlike, but the meaning would be preserved. Maybe I should do this in the future? Or do I not need to make such corrections, and report each such issue in a separate thread?

We don't change content of broadcast_text and broadcast_text_locale tables

**Comment by offl** [comment]
> Talk(SAY_BARADA_2, player);

'player' is not even declared usually

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/commit/22a1797731ad1ae8e666c6a32ac36965db5f760b sample of how other c++ was fixed.
