### ISSUE TITLE
[3.3.5] Game Event: Fall of the Infernals in Honor Hold

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#26721]
### Description

Infernals periodically drop in Honor Hold. Because of this, the characters enter the state of battle, however, after the end of the fall of the infernals, the state of the battle is not removed for a very long time (more than 20 minutes, I timed it), or it may not be removed at all. 

### Expected behaviour

After the fall of the Infernals in Honor Hold, the battle condition should be removed soon (ideally immediately after the end). 

### Steps to reproduce the problem

1. Create an alliance character;
2. **.go xyz  -680 2700  95 530**;
3. Wait for the beginning of the fall of the infernals in Honor Hold;
4. Make sure that your character enters a state of battle when an infernal falls nearby (in fact, it is not an infernal that falls, but just a stone); 
5. Make sure that your character does not leave the combat state after the end of the fall of the infernals in Honor Hold;
6. Use **.gm on** or **Alt+F4** if you want to eat, drink, use the flight master or if you want to mount.

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/a47926ceab7091dd0c06b6bb16a0d1f64bd30a63
TrinityCore rev. 2021-07-16 ‏‎18:51:35 +0300 (3.3.5 branch) (Win64, Release, Static)

### Operating system

Win7 SP1 x64 with all updates (build 6.1.7601).

### Custom changes

None.

**Comment by jackpoz** [comment]
There is agm command to check with which npc you are still in combat with, maybe we have to add a no-combat flag to that (or maybe an old script has to be changed)

**Comment by Jinnaix** [comment]
Use ".debug combat" on yourself to get the information we are looking for in this case.
Im personally interested in this, since i thought its all good now with the honor hold event, after i fixed the fear bug that existed before.

**Comment by Jinnaix** [comment]
Valid.

Caused by the Infernal Rain NPC´s (Entry 18729).
There are 5 static one (spawn id 86525 - 86529) and 10 moving around (spawn id 86515 - 86524).

The static ones take the moving ones as targets for spells.

After the event is done, several NPC and potentially the player himself can get stuck in combat with the 5 static Infernal Rain NPC.

Example Picture taken from Spawnid 86525 after event is over:

![image](https://user-images.githubusercontent.com/37972361/126171806-09f2ab20-61b2-45bb-8589-9704eafc404a.png)

Aside from that, there is a linked spell (https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=33637#triggered-by) that stuns (this is the one that gets you into combat) - this spell also seems to break NPC´s home position when it hits them while they are feared.

**Comment by Freeman256** [comment]
After recent fixes (https://github.com/TrinityCore/TrinityCore/commit/39e1d293bf5c26c26d26fe9509189a67ce0c4f37 and https://github.com/TrinityCore/TrinityCore/commit/b1b5bc650bd679b78c5f0d1289e827096341d78c), the issue has been resolved. Many thanks to everyone!
