### ISSUE TITLE
DB/Quest: More Components of Importance - Drop chance too high

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#26801]
### Description

The quest [More Components of Importance](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?search=More+Components+of+Importance) requires a [Brilliant Sword of Zealotry](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=22228) which drops off Scarlet Praetorians.

The drop chance is currently set to 100% - the item is not meant to drop this quickly.

### Expected behaviour

The item should have a varying drop rate; research suggests its "a low drop rate".

I do not have a more accurate value.

### Steps to reproduce the problem

Note: This is part of the Dungeon 2 / Tier 0.5 quest line

1. Pick up quest from [Bodley](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=16033) who is in ghost form just outside LBRS entrance
2. Head to Tyr's Hand in Eastern Plaguelands (roughly 78, 76 - SW corner of zone)
3. Make your way straight up the path to where the Scarlet Praetorians spawn
4. Kill 1, the item will drop

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 87a4bc3 2021-07-23 00:12:58 +0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 7 x64

### Custom changes

Trickerer's Bots

**Comment by RedSonja** [comment]
I found an old quote for what the drop rate used to be: (the droprate is listed as 0.2%.)  You can go into the creature_loot_template and find it, just change the droprate to 0.02.  It's been awhile since I posted any fixes and I am using an old db but I am sure you can figure it out if it is different.
`UPDATE `creature_loot_template` SET `Chance` = '0.02' WHERE `creature_loot_template`.`Entry` = 9448 AND `creature_loot_template`.`Item` = 22228;`

**Comment by offl** [comment]
>0.2%

He talks about value shown in wowhead which never should be used for quest items because wowhead calculates chance based on total kill count. That means in case of quests items the chance will be always low because mostly creature was killed by players without quests.
Also 0.2% will make any quest uncompletable.

**Comment by RedSonja** [comment]
I actually agree, Wowhead has not been a good source for a very long time, however, Trinity used to use it a lot. Especially when doing loot tables. More than an actual fix I guess I was trying to show how it can be changed. We have always had higher drop rates for the most part. Why do you think Blizz makes some of the drop rates so obscurely low?  Simply so the players have to spend more time and money there.

**Comment by offl** [comment]
>Wowhead has not been a good source for a very long time, however, Trinity used to use it a lot

Yes but not for quest items
