### ISSUE TITLE
[NPC] Succubus Minion 10928

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26885]
### Description

Problem: she does not attack anyone. Seems to be the extra flag (civilian) 
https://www.wowhead.com/npc=10928/succubus-minion

### SQL fix

```sql
-- Update flags_extra 2 to 0 (civilian to none)
UPDATE `creature_template` SET `flags_extra` = 0 WHERE `Entry` = 10928;
```

### Branch

3.3.5

### TC rev. hash/commit

fece5bd

**Comment by dr-j** [comment]
I’ve previously noticed there are other creatures with civilian flags which are meant to be hostile or change to hostile state but don’t agro due to these flags

**Comment by offl** [comment]
Unfortunately, there is no such thing as civilian flag in CreatureDifficulty and we can't re-apply it using Blizz's data
There is combination of Call Guards flag(tons of civilians but also used by some bosses and obviously non-civilian creatures) and PVP flag. Probably closest thing to treat as civilian
I selected all creatures without Call Guards flag but with our civilian flag and got 4k results(half of all units with civilian flag). Tons of triggers, 1500 friendly units, hostile units, non attackable units, normal mobs, kids(always unkillable and not attackable due to age rating), hundreds of never used creatures
Eh
