### ISSUE TITLE
Database errors

### ISSUE THREAD

**Issue by PersonPlay** [TrinityCore/TrinityCore#27968]
### Description

After compiling the kernel and starting the server, I have error logs. There are no special problems in 3.3.5. I removed the cards of the Russian version 9.2.0.43345 for about 7 hours. Because of what, the starting quest on the ship-island does not work.

[Logs.zip](https://github.com/TrinityCore/TrinityCore/files/8749826/Logs.zip)

### Expected behaviour

Clean error logs

### Steps to reproduce the problem

Compile master kernel
Extract cards from client 9.2.0.43345 (RU)
Start the island's starting quest.

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 703452d28d05

### Operating system

11

### Custom changes

No

**Comment by Aokromes** [comment]
duplicate.

**Comment by PersonPlay** [comment]
I do not understand why the issue is closed?

**Comment by Jinnaix** [comment]
Greetings Person Play,

we have the rule to only have one open issue for the same problem. In this case, that issue is https://github.com/TrinityCore/TrinityCore/issues/15829. Normally we also reference it when a issue gets closed so the user knows what is up here.

You did nothing wrong, master is missing tons of content right now and the errors you see exist for everyone.
