### ISSUE TITLE
DB/Spawns add init. spawns to Alliance GarrisonV1

### ISSUE THREAD

**Issue by Naddley** [TrinityCore/TrinityCore#28072]
### Description

Creature and Gob spawns
Handle of Garrison V1 Phase

-> Since Garrisons use some system like dynamic Waypoints (nyi) there are no WPs done atm

### SQL fix

```sql
https://gist.github.com/Naddley/9da0aa09fe3f1c8ce40c7c9c7521d5f0
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 737d94d7efe0

**Comment by Nyr97** [comment]
This is just a suggestion to the SQL: you still could try to obtain the WP whether they dynamically change or not. It could take you much more time since you'd need to obtain several waypoints for each GUID. @mdX7 have you guys given any thoughts to making it possible for a creature to hold several waypoint paths so that they're chosen dynamically after certain event happens, whether it is WP finishing or getting back to home position?

**Comment by offl** [comment]
What's dynamic waypoints?

**Comment by Nyr97** [comment]
Dynamically chosen* waypoints, my wording was not the best. Basically, they choose a different waypoint path for a certain range of actions they want to perform rather than having to create creature scripts or DB actions to choose a different path.

**Comment by offl** [comment]
You mean creature performs certain list of actions, like says things, then chooses random path?

**Comment by Nyr97** [comment]
It's more like, they choose a path and then they perform actions available to them, say it's sitting on a chain object, talking to a different creature when stopping by a certain place, getting close to a certain tent to get a beverage while they're patrolling.
