### ISSUE TITLE
[3.3.5] Warsong Gulch Flag Debuff [40$]

### ISSUE THREAD

**Issue by immvp** [TrinityCore/TrinityCore#28088]
### Description

Focused Assault (https://wotlkdb.com/?spell=46392) and Brutal Assault ((https://wotlkdb.com/?spell=46393) is currently triggered by both Flags being held for 10 minutes, and 15 minutes, respectively. This is **correct**. 

However, the Timer for the 10 and 15 minutes gets reset if **_bothFlagsKept = false**. This is not correct. It should reset on Flag Capture, or if both Alliance and Horde Flags have been reset to their original state.

### Expected behaviour

In Warsong Gulch, after 10 minutes of both teams being in **posession** of the flag (Or more accurately, 10 minutes of both teams NOT having the Flag Gameobject in its original position), whoever holds the Flag will get a Debuff named Focused Assault (https://wotlkdb.com/?spell=46392).

After 5 more minutes, so 15 minutes total, whoever holds the Flag will get a Debuff named Brutal Assault (https://wotlkdb.com/?spell=46393).

Timer should only reset on Flag Capture or if both Flags have been returned. (Both of which result in the Flag Gameobject being on its original position in the base)

### Steps to reproduce the problem

1. Pick up Flag on both Teams (Horde and Alliance)
2. Wait 10 minutes for the Focused Assault debuff to appear (Or Custom edit the Timer so it's shorter, for easier testing)
3. **Drop** the flag on One team, and **Return** it with the other, while still holding the Flag on the other.
4. Focused Assault debuff will now dissapear from whoever is still holding the Flag.
5. Pick the Flag up again, and wait 10 minutes. You'll see Focused Assault debuff appears again, which means the Timer has been reset from the Return.

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 0d27a7bdef35 2022-07-04 02:36:22 +0200 (main branch) (Unix, Release, Static)

### Operating system

Ubuntu 20.04

### Custom changes

Transmog Patch. 

Anything related to Battleground and Battlefield has not been touched.

**Comment by adeutscher** [comment]
@immvp I'd like to confirm some phrasing since these seem in conflict (or maybe I'm just misreading):

"In Warsong Gulch, after 10 minutes of both teams being in posession of the flag (Or more accurately, 10 minutes of both teams NOT having the Flag Gameobject in its original position)"

If both flags have been taken from their pedestal but the one flag is on the ground (whether dropped intentionally or from a dead carrier), then is the flag debuff timer expected to still go up during this time?

**Comment by immvp** [comment]
> 



> @immvp I'd like to confirm some phrasing since these seem in conflict (or maybe I'm just misreading):
> 
> "In Warsong Gulch, after 10 minutes of both teams being in posession of the flag (Or more accurately, 10 minutes of both teams NOT having the Flag Gameobject in its original position)"
> 
> If both flags have been taken from their pedestal but the one flag is on the ground (whether dropped intentionally or from a dead carrier), then is the flag debuff timer expected to still go up during this time?
> 
> Edit: Reflecting on it, I think that my question is probably out of scope for this bug.

Yes, so basically the timer is expected to start once both flags are off the pedestal simultaneously, and should only stop / reset when both flags have returned to the pedestal.

**Comment by immvp** [comment]
Moreover, using PvP Trinket will remove this debuff currently (not intended).

**Comment by adeutscher** [comment]
Alternatively, I haven't 100% tested to see if my timer-running question is an issue at all. It could be that I'm just interpreting this unfamiliar file a bit weirdly. All the more reason for a separate investigation afterwards. And the scope of this bug is pretty clear with testing/reproducing.

**Comment by adeutscher** [comment]
Created PR. Perfect-world, the only thing left is final testing.

**Comment by adeutscher** [comment]
Tested and confirmed.

**Comment by immvp** [comment]
Reviewing the code, this looks like it SHOULD work. 

I'm gonna apply this fix to my Warsong Gulch-only competitive private server, and see what players say. If you could add my Discord Mvq#0670, I'd love to have you look at more Bugs at the benefit of TrinityCore. I'd pay you for your time of course, similar to how this Bounty did! ^_^ @adeutscher

**Comment by immvp** [comment]
Effect PvP Trinket [42292](https://wotlkdb.com/?spell=42292) can be used to remove the Debuff (Timer keeps going tho')

Even tho it's outside of the scope of the bug report, it is most likely a simple fix that goes under the banner of "Flag Debuff bug". ^_^ @adeutscher 

If you wanna take a look and apply it to this PR that would probably be good!

**Comment by adeutscher** [comment]
I think that the cause of this is a bit different. From what I can see, `BattlegroundWS.cpp` is pretty good about managing the game state, and the instances of Assault removal in this file look pretty sane (dropped flag, capped flag, etc)

I think what's going on is that the PvP trinket catches on the Assault debuffs' movement limiter and axes it.

When I'm able to test (probably this afternoon/evening Pacific time) I'll be looking into `SpellInfo::ApplyAllSpellImmunitiesTo`. It seems to have all the "remove auras when the target gains an immunity" logic. I'd bet that there's some sort of "ignore immunity" attribute on the Assaults that's not getting checked here. From a quick ctrl-F of `SharedDefines.h`, perhaps `SPELL_ATTR2_UNAFFECTED_BY_AURA_SCHOOL_IMMUNE` or `SPELL_ATTR6_ASSIST_IGNORE_IMMUNE_FLAG`?

**Comment by adeutscher** [comment]
@immvp , a possible alternative just came to mind that I wanted to bring up before I forgot.

Debuff application happens in the battleground's update method, which is invoked very often. At the moment, application is walled off between checks on the debuff state and timing checks.

If I have no leads on adjusting `SpellInfo::ApplyAllSpellImmunitiesTo`, would it be acceptable to have the battleground re-apply the Assault debuff 2ms after it got removed? It does feel pretty hacky though, so I'm really hoping that it's unnecessary.

**Comment by immvp** [comment]
Hmm that is very hacky, and I'm not sure if TrinityCore would accept that type of fix. Spells like Divine Shield, Ice Block etc. - Things that kinda remove "everything" also removes the Flag Debuff. 

I'm pretty sure the Flag Debuff has a filter called [Unaffected by invulnerability](https://www.wowhead.com/spells?filter=46;1;0), it does on WoWhead atleast. Maybe doing something around that is the move..

**Comment by adeutscher** [comment]
Yeah, I should have figured that was too hacky to be an option.

After this comment I'm going to shelve things until the later afternoon, but here's where my understanding is on avoiding the dispelling in the first place:

* `SpellInfo::_LoadImmunityInfo` carves out a switch case for the PvP trinket that applies a `mechanicImmunityMask` value for movement impairment and control loss.
* Not executed (I think), but school-immunity handling in `SpellInfo::ApplyAllSpellImmunitiesTo` has a call to CanDispelAura. If `SPELL_ATTR0_UNAFFECTED_BY_INVULNERABILITY` is present on the aura, then `true` is returned. (to allow for Mass Dispel and such)
* Confirmed in Wowhead with your link that the Assaults have `SPELL_ATTR0_UNAFFECTED_BY_INVULNERABILITY`.
* In the section handling mechanic immunity, there doesn't seem to be any check for `SPELL_ATTR0_UNAFFECTED_BY_INVULNERABILITY` (see below)

Within `SpellInfo::ApplyAllSpellImmunitiesTo`:

```
if (uint32 mechanicImmunity = immuneInfo->MechanicImmuneMask)
{
    for (uint32 i = 0; i < MAX_MECHANIC; ++i)
        if (mechanicImmunity & (1 << i))
            target->ApplySpellImmune(Id, IMMUNITY_MECHANIC, i, apply);

    if (apply && HasAttribute(SPELL_ATTR1_DISPEL_AURAS_ON_IMMUNITY))
        target->RemoveAurasWithMechanic(mechanicImmunity, AURA_REMOVE_BY_DEFAULT, Id);
}
```


Content of `Unit::RemoveAurasWithMechanic`:

```
void Unit::RemoveAurasWithMechanic(uint32 mechanic_mask, AuraRemoveMode removemode, uint32 except)
{
    for (AuraApplicationMap::iterator iter = m_appliedAuras.begin(); iter != m_appliedAuras.end();)
    {
        Aura const* aura = iter->second->GetBase();
        if (!except || aura->GetId() != except)
        {
            if (aura->GetSpellInfo()->GetAllEffectsMechanicMask() & mechanic_mask)
            {
                RemoveAura(iter, removemode);
                continue;
            }
        }
        ++iter;
    }
}
```

When I test this evening, I plan to add a check in `Unit::RemoveAurasWithMechanic` for `SpellInfo::HasAttribute(SPELL_ATTR0_UNAFFECTED_BY_INVULNERABILITY)`

The part that's getting me worried now is if adding in this check to something in such a central place as `Unit`, if there is some kind of necessary "remove by mechanic" that's not immunity-based. If that's the case, then maybe `Unit::RemoveAurasWithMechanic` needs a new parameter to say "this removal is because of an immunity"? Or am I overthinking this and any by-mechanic removal would be for an immunity?

At any rate, when I can test I'll see if it fundamentally works and then worry about complications afterwards.

**Comment by adeutscher** [comment]
Looks like my thinking with `SpellInfo::ApplyAllSpellImmunitiesTo` was completely out to lunch. Even commenting out all the method's content didn't stop the removal. Investigation is ongoing.

Because the solution is probably so far afield from the fixes to the original Warsong problem, when I find the cause I'm probably going to be making a separate branch for a separate PR.

**Comment by adeutscher** [comment]
Or I'm a complete dolt. When there didn't seem to be any effect I was editing files in a `wotlk-dev` folder, when my branch checkout and building is out of `wotlk`. `-dev` is getting chucked off a cliff now.

One bonus to this misadventure is that the it seems that a call to `Unit::RemoveAurasByType` has a hand removing some debuffs (if it were to survive the ByMechanic delete?).

Will continue in another sitting this evening.

**Comment by adeutscher** [comment]
@immvp Created the PvP trinket ignore in a separate branch/PR as planned.

**Comment by Shauren** [comment]
b1db528780c455ad0adc5b8a10c20719e461d3aa
