### ISSUE TITLE
3.3.5a new startup errors

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#28711]
### Description

2023-01-10_10:05:30 ERROR [sql.sql] Creature (Entry: 11280) has invalid sheath state (69) defined in `creature_addon`. Truncated to 0.
2023-01-10_10:05:30 ERROR [sql.sql] Creature (Entry: 11316) has invalid sheath state (69) defined in `creature_addon`. Truncated to 0.
2023-01-10_10:05:30 ERROR [sql.sql] Creature (Entry: 30731) has invalid sheath state (221) defined in `creature_addon`. Truncated to 0.
2023-01-10_10:05:30 ERROR [sql.sql] Creature (Entry: 32643) has invalid sheath state (3) defined in `creature_addon`. Truncated to 0.
2023-01-10_10:05:30 ERROR [sql.sql] Creature (Entry: 34045) has invalid sheath state (19) defined in `creature_addon`. Truncated to 0.
2023-01-10_10:05:31 ERROR [sql.sql] Creature (GUID: 8143) has invalid sheath state (43) defined in `creature_addon`. Truncated to 0.
2023-01-10_10:05:31 ERROR [sql.sql] Creature (GUID: 8146) has invalid sheath state (43) defined in `creature_addon`. Truncated to 0.
2023-01-10_10:05:31 ERROR [sql.sql] Creature (GUID: 8147) has invalid sheath state (43) defined in `creature_addon`. Truncated to 0.
2023-01-10_10:05:31 ERROR [sql.sql] Creature (GUID: 63387) has invalid sheath state (98) defined in `creature_addon`. Truncated to 0.
2023-01-10_10:05:31 ERROR [sql.sql] Creature (GUID: 78195) has invalid sheath state (16) defined in `creature_addon`. Truncated to 0.
2023-01-10_10:05:31 ERROR [sql.sql] Creature (GUID: 78196) has invalid sheath state (16) defined in `creature_addon`. Truncated to 0.
2023-01-10_10:05:31 ERROR [sql.sql] Creature (GUID: 78197) has invalid sheath state (16) defined in `creature_addon`. Truncated to 0.
2023-01-10_10:05:31 ERROR [sql.sql] Creature (GUID: 78198) has invalid sheath state (16) defined in `creature_addon`. Truncated to 0.
2023-01-10_10:05:31 ERROR [sql.sql] Creature (GUID: 82292) has invalid sheath state (43) defined in `creature_addon`. Truncated to 0.
2023-01-10_10:05:31 ERROR [sql.sql] Creature (GUID: 112378) has invalid sheath state (252) defined in `creature_addon`. Truncated to 0.
2023-01-10_10:05:31 ERROR [sql.sql] Creature (GUID: 135230) has invalid sheath state (5) defined in `creature_addon`. Truncated to 0.

### Expected behaviour

no errors.

### Steps to reproduce the problem

update to 6f835c233f7605d74926a2a3058634c9de478617
start core

### Branch

3.3.5

### TC rev. hash/commit

6f835c233f7605d74926a2a3058634c9de478617

### Operating system

n/7r

### Custom changes

n/r

**Comment by Logandros** [comment]
Same issue here:

Loading Creature template addons...
Creature (Entry: 11280) has invalid sheath state (69) defined in `creature_addon`. Truncated to 0.
Creature (Entry: 11316) has invalid sheath state (69) defined in `creature_addon`. Truncated to 0.
Creature (Entry: 30731) has invalid sheath state (221) defined in `creature_addon`. Truncated to 0.
Creature (Entry: 32643) has invalid sheath state (3) defined in `creature_addon`. Truncated to 0.
Creature (Entry: 34045) has invalid sheath state (19) defined in `creature_addon`. Truncated to 0.


Loading Creature Addon Data...
Creature (GUID: 8143) has invalid sheath state (43) defined in `creature_addon`. Truncated to 0.
Creature (GUID: 8146) has invalid sheath state (43) defined in `creature_addon`. Truncated to 0.
Creature (GUID: 8147) has invalid sheath state (43) defined in `creature_addon`. Truncated to 0.
Creature (GUID: 63387) has invalid sheath state (98) defined in `creature_addon`. Truncated to 0.
Creature (GUID: 78195) has invalid sheath state (16) defined in `creature_addon`. Truncated to 0.
Creature (GUID: 78196) has invalid sheath state (16) defined in `creature_addon`. Truncated to 0.
Creature (GUID: 78197) has invalid sheath state (16) defined in `creature_addon`. Truncated to 0.
Creature (GUID: 78198) has invalid sheath state (16) defined in `creature_addon`. Truncated to 0.
Creature (GUID: 82292) has invalid sheath state (43) defined in `creature_addon`. Truncated to 0.
Creature (GUID: 112378) has invalid sheath state (252) defined in `creature_addon`. Truncated to 0.
Creature (GUID: 135230) has invalid sheath state (5) defined in `creature_addon`. Truncated to 0.

I 'assume' all of these were unable to be converted during the [sql update](https://github.com/TrinityCore/TrinityCore/blob/6f835c233f7605d74926a2a3058634c9de478617/sql/updates/world/3.3.5/2023_01_09_00_world.sql) from bytes2 but I'm not sure how to figure out what their proper SheathState should be (0,1,2) so I can correct them in the DB. This doesn't seem to cause any issues with functionality that I can see but my OCD demands I try and get some help to get them set correctly so that they don't need to be truncated.

**Comment by CraftedRO** [comment]
well if sheath is now old bytes2 Killiana told me : 

> If the npc must have the melee weapon on hand OOC put bytes2=1 otherwise 0


so I guess Il try to make an update query based on npc type idk

**Comment by CraftedRO** [comment]
well if sheath is now old bytes2 Killyana told me : 

> If the npc must have the melee weapon on hand OOC put bytes2=1 otherwise 0


so I guess Il try to make an update query based on npc type idk

**Comment by Logandros** [comment]
I'm thinking they can all be set to '0' because I spawned 8143 (vendor) and 8147 (guard) both were truncated to 0 and 8143 had no visible weapon and 8147 did. Unless I'm misunderstanding your explanation of melee weapon on hand.

**Comment by CraftedRO** [comment]
something is wrong even with errors creature_addon doesn't even have entry table maybe description was messed up

**Comment by CraftedRO** [comment]
@Ovahlord something is wrong even with errors descriptions: creature_addon doesn't even have entry table maybe they were messed up ?

**Comment by Ovahlord** [comment]
no. What you see here now is the result of having dirty db data. These values have been wrong since they were added and went unchecked for years. So buckle up, sniff these npcs and get their proper values.

**Comment by CraftedRO** [comment]
so all those errors are about creature_addon table and they're all reffering to guid-s ?

**Comment by Ovahlord** [comment]
yes. obviously

**Comment by Logandros** [comment]
I mean, 16 out of .... not bad ...

**Comment by CraftedRO** [comment]
as I already said the errors description were messed up dude
If they were all creature_addon guid related errors my fix shoud deal with but they're not...
```sql
UPDATE `creature_addon` SET `SheathState`=0 WHERE `guid` IN (11280,11316,30731,34045,135230);
UPDATE `creature_addon` SET `SheathState`=1 WHERE `guid` IN (32643,8143,8146,8147,63387,78195,78196,78197,78198,82292,112378);
```

**Comment by Ovahlord** [comment]
> as I already said the errors description were messed up dude If they were all creature_addon guid related errors my fix shoud deal with but they're not...
> 
> ```sql
> UPDATE `creature_addon` SET `SheathState`=0 WHERE `guid` IN (11280,11316,30731,34045,135230);
> UPDATE `creature_addon` SET `SheathState`=1 WHERE `guid` IN (32643,8143,8146,8147,63387,78195,78196,78197,78198,82292,112378);
> ```

I'd recommend you to read these errors carefully again and you'll notice that the first bunch are template_addon entries which use... well.... entries. The other ones use guids.

**Comment by CraftedRO** [comment]
the othe table is creature_templete_addon is using entry and template_addon is using guid-s kek well meh I need to revert db back now :D

**Comment by Logandros** [comment]
yeah correct syntax would be (I think)

`UPDATE `creature_template_addon` SET `SheathState`=0 WHERE `entry` IN (11280,11316,30731,34045,135230);
UPDATE `creature_addon` SET `SheathState`=1 WHERE `guid` IN (32643,8143,8146,8147,63387,78195,78196,78197,78198,82292,112378);`

**Comment by CraftedRO** [comment]
nope because that fix was made checking every npc by guid, now the first row is entry so are totally different things

**Comment by Logandros** [comment]
Not sure if I can put this here, I will delete if it should be a new issue but, how can I go about manipulating the DB updater so that it believes this update was applied? I borked something while testing and now it's trying to reapply:

```
Reapplying update "2023_01_09_00_world.sql" '15F16D7' -> '15F16D7' (it changed)...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1060 (42S21) at line 1 in file: 'D:\BUILD STUFF\repos\Trinity335WotLK\sql\updates\world\3.3.5\2023_01_09_00_world.sql': Duplicate column name 'StandState'
Applying of file 'D:/BUILD STUFF/repos/Trinity335WotLK/sql/updates/world/3.3.5/2023_01_09_00_world.sql' to database 'world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from TrinityCore repository with your sql client. If you are a developer, please fix your sql query.
Could not update the World database, see log for details.
```

**Comment by Shauren** [comment]
clear hash column in updates table for that sql (set column to empty value, dont delete entire row)

**Comment by Logandros** [comment]
> clear hash column in updates table for that sql (set column to empty value, dont delete entire row)

Like a glove, tyvm!

**Comment by CraftedRO** [comment]
this is my final fix I also found a cosmetic issue on one npc but Il fix it separately
```sql
UPDATE `creature_template_addon` SET `SheathState`=0 WHERE `entry` IN (11280,30731,32643,34045);
UPDATE `creature_template_addon` SET `SheathState`=1 WHERE `entry` =11316;

UPDATE `creature_addon` SET `SheathState`=0, `StandState`=5 WHERE `guid` =135230;-- fix phantom guest sit on medium chair
UPDATE `creature_addon` SET `SheathState`=1 WHERE `guid` IN (8143,8146,8147,63387,78195,78196,78197,78198,82292,112378);
```

**Comment by Logandros** [comment]
> this is my final fix I also found a cosmetic issue on one npc but Il fix it separately
> 
> ```sql
> UPDATE `creature_template_addon` SET `SheathState`=0 WHERE `entry` IN (11280,30731,32643,34045);
> UPDATE `creature_template_addon` SET `SheathState`=1 WHERE `entry` =11316;
> 
> UPDATE `creature_addon` SET `SheathState`=0, `StandState`=5 WHERE `guid` =135230;-- fix phantom guest sit on medium chair
> UPDATE `creature_addon` SET `SheathState`=1 WHERE `guid` IN (8143,8146,8147,63387,78195,78196,78197,78198,82292,112378);
> ```

thank you for sharing!

**Comment by Ovahlord** [comment]
@offl  mind to validate these and push them?

**Comment by Aokromes** [comment]
@Killyana
