### ISSUE TITLE
WingcrestEmbassy

### ISSUE THREAD

**Issue by TheDdraig** [TrinityCore/TrinityCore#28985]
### Description

This spawns the Alliance camp at Wingcrest Embassy when leaving boat, all data is from sniff from retail and I added correct emotes along with SAI scripting. I have tested this and all seems to be working. Only thing I have left out is the waypoints and I will try to add this in an update.

### SQL fix

https://gist.github.com/TheDdraig/9589f67b9bb3adb18ea737b2a246daa2

### Branch

master

### TC rev. hash/commit

8a91448f282f7c1cb12223cbbc1c40dfac14bfef

**Comment by TheDdraig** [comment]
Branch is meant for Master just thought I'd mention, did set it to master but had issues with putting the sql code so guess it reverted back to 3.3.5 xD

**Comment by TheDdraig** [comment]
I will check the gossip for inn keeper, I know when you click that gossip it supposed to close and make npc say text, didnt know how to setup that up since I was literally going by sniff data alone. In regards to the Salty Salamander, its in the creature_addon because they aren't unique and I don't believe they all have the cast spell to make them asleep...If they do, I'll change it. Not sure what you mean about the Phaseid, it was giving me issues without adding value 0 on it.

**Comment by mdX7** [comment]
About phaseid: its an integer (non floating point number), so you write the phaseid value directly `0` instead of marking it as a string with quotes `'hello i have quotes at the beginning and end, im a string'`.
Wpp is generating it as string field, bcuz its printing all active phases of the player at spawn time

**Comment by Faq** [comment]
Good explaining, what could be added in some guide, so you not DRY per issue :)

**Comment by TheDdraig** [comment]
Updated PR, removed the quotes in creature spawns, corrected SAI to now be on respawn, setup SAI for Happy Hal inn keeper, where when you select gossip, will close and npc will say his text. I also setup creature_text for it and included the broadcast text for it. Hopefully I done it all correctly. xD

**Comment by meji46** [comment]
> Updated PR, removed the quotes in creature spawns, corrected SAI to now be on respawn, setup SAI for Happy Hal inn keeper, where when you select gossip, will close and npc will say his text. I also setup creature_text for it and included the broadcast text for it. Hopefully I done it all correctly. xD

- Field creature.spawnDifficulties is a varchar so you should mantain it as a string with quotes ('0')
- DELETE/INSERT for creature_template is wrong. You must use UPDATE (still missing)
- Add CREATURE_FLAG_EXTRA_TRIGGER for bunnies if they have a visible and an invisible model (180701, 197611, 198367) (still missing)
- You're using wrong the params for SMART_EVENT_RESPAWN (11)
  - 2,0,13644,0 (Zone/Area)
  - 1,2444,0,0 (Map)
  - 0,0,0,0 (I recommend this option as creature has only 1 spawn and we aren't using the parameters in any other case)
- 10,@CGUID+2,191148. Try to use SMART_TARGET_CLOSEST_CREATURE (19) if possible
- Happy Hal
  - Remove the DELETE/INSERT for broadcast_text since it's part of hotfixes and Modox takes care of updating them (and you shouldn't mix queries for different databases). Also, TDB has this row
  - Check in the sniff if the npc plays the following emote (ONESHOT_LAUGH (11) when talking (SMSG_EMOTE). If so, you must add it to creature_text.Emote
  
The rest seems to be fine 👍

**Comment by Naddley** [comment]
Row 125 - 235 are DELETE/INSERT template for mounts. We dont touch them. You can delete the whole DELETE/INSERT of creature template and just use the UPDATES one.
I can recommend to connect WPP to your DB so you only get UPDATE statements if we allready have values.

**Comment by malcrom** [comment]
You told him do not use OOC here ```(@ENTRY,@SOURCETYPE,0,0,11,0,100,0,2,2444,13644,0,11,375314,2,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Danielle Anglers - On Respawn - Cast (Fishing Mechagon Pole + Azsuna Bobber DNT)");``` and to use closest creature which is wrong.

This should be OOC with a one sec delay, no repeat if you want him to use closest creature to give it time to spawn.

**Comment by TheDdraig** [comment]
I ended up redoing the entire file, removed all queries that didnt relate to the creatures that are spawned, now the queries will only reflect the camp of the creatures that are currently spawned.

**Comment by meji46** [comment]
> You told him do not use OOC here `(@ENTRY,@SOURCETYPE,0,0,11,0,100,0,2,2444,13644,0,11,375314,2,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Danielle Anglers - On Respawn - Cast (Fishing Mechagon Pole + Azsuna Bobber DNT)");` and to use closest creature which is wrong.
> 
> This should be OOC with a one sec delay, no repeat if you want him to use closest creature to give it time to spawn.

I guess you are referring to other SAI because you have linked a different one.

First of all, I think you are mixing two different things:
- Target type: I prefer to avoid using guids where possible. In this case, the target SMART_TARGET_CLOSEST_CREATURE can be used without problem (there's only one kite near the npc). This has nothing to do with the spawning order problem you mention
- Event type: The problem that you point out that in SMART_EVENT_RESPAWN maybe the kite hasn't spawned (sometimes it has happened to me). I tried the fix and it didn't give me any problem even changing the order of the guids.

If you want a more complete solution you could define something like:
Kite -> On respawn -> Set data to Npc. Npc -> On data set -> Cast spell to kite
Npc -> On respawn -> Cast spell to kite

![image](https://github.com/TrinityCore/TrinityCore/assets/2695278/6c7224ac-2845-47d4-9fa2-bd0fdeedbc05)

**Comment by TheDdraig** [comment]
Also checked regarding one shot emote, seems the npc does not have this also checked the gossip select, seems it closes gossip upon selecting:

```
ServerToClient: SMSG_GOSSIP_MESSAGE (0x2A98) Length: 207 ConnIdx: 0 Time: 05/02/2023 19:06:52.196 Number: 4941
GossipGUID: Full: 0x203ADD3180B705000012410000498220 Creature/0 R3767/S4673 Map: 2444 Entry: 187412 Low: 4817440
GossipID: 28240
FriendshipFactionID: 0
GossipOptionsCount: 3
GossipQuestsCount: 0
HasBroadcastTextID: True
HasBroadcastTextID2: False
[0] (GossipOptions) GossipOptionID: 54923
[0] (GossipOptions) OptionNPC: 0
[0] (GossipOptions) OptionFlags: 0
[0] (GossipOptions) OptionCost: 0
[0] (GossipOptions) Language: 0 (Universal)
[0] (GossipOptions) Flags: 0
[0] (GossipOptions) OrderIndex: 0
[0] (GossipOptions) Status: 0
[0] (GossipOptions) Text: Why are you always so happy, Hal?
[0] (GossipOptions) Confirm: 
[1] (GossipOptions) GossipOptionID: 54924
[1] (GossipOptions) OptionNPC: 1
[1] (GossipOptions) OptionFlags: 0
[1] (GossipOptions) OptionCost: 0
[1] (GossipOptions) Language: 0 (Universal)
[1] (GossipOptions) Flags: 0
[1] (GossipOptions) OrderIndex: 1
[1] (GossipOptions) Status: 0
[1] (GossipOptions) Text: Let me browse your goods.
[1] (GossipOptions) Confirm: 
```

**Comment by malcrom** [comment]
I have done SAI before. If one creature is casting on another it is best to delay the cast 1 sec with OOC. If it's casting on self it's fine to do it on respawn. And yes I agree it's best to do closest if that will work for the situation.

**Comment by meji46** [comment]
> Also checked regarding one shot emote, seems the npc does not have this also checked the gossip select, seems it closes gossip upon selecting:
> Can't find any one shot emote, on retail he doesnt seem to do anything special except says text

It should be a SMSG_EMOTE sent before SMSG_CHAT (I ask this because the broadcast text has EmotesID = 11). Example:
> ServerToClient: SMSG_EMOTE (0x27B5) Length: 22 ConnIdx: 1 Time: 11/27/2021 20:55:33.922 Number: 11677
GUID: Full: 0x2016F400203E2280001F5500001E5467 Creature/0 R1469/S8021 Map: 1 (Kalimdor) Entry: 63626 (Varzok) Low: 1987687
Emote ID: 1 (OneShotTalk)
SpellVisualKitCount: 0
>
> ServerToClient: SMSG_CHAT (0x2BAD) Length: 102 ConnIdx: 0 Time: 11/27/2021 20:55:34.062 Number: 11687
SlashCmd: 12 (MonsterSay)
Language: 0 (Universal)
SenderGUID: Full: 0x2016F400203E2280001F5500001E5467 Creature/0 R1469/S8021 Map: 1 (Kalimdor) Entry: 63626 (Varzok) Low: 1987687

**Comment by TheDdraig** [comment]
I searched the entire SMSG_EMOTE and even searched with Entry:  187412 but no mention of emote. So I went onto retail and saw he laughed, so I did .npc playemote 11 and he does the same so I updated the creature_text to have this emote. I also removed broadcast text as mentioned.

**Comment by TheDdraig** [comment]
![image](https://github.com/TrinityCore/TrinityCore/assets/62179779/5ff8929c-fe9b-4b17-824b-a228c9ba5f28)

**Comment by TheDdraig** [comment]
Re-did the inn-keeper and removed creature text as Modox pointed out it has conversation and uses a spell to cast said conversation tied to emote, tested and now works. Sorry about that, but thanks for the help.

**Comment by Naddley** [comment]
Changed a few thing:

- added missing DisableGravity
- re-added NPCTEXTID+4 (this one was for the innkeeper)
-  deleted some unused data
- Added waypoints + SAI scripts for wps
