### ISSUE TITLE
UpdateSkillsForLevel - Code seems broken?

### ISSUE THREAD

**Issue by LabViewCode** [TrinityCore/TrinityCore#29070]
### Description

```cpp
            case 6776: // Player Maxskill
                CloseGossipMenuFor(player);
                player->UpdateSkillsForLevel();
                ChatHandler(player->GetSession()).SendSysMessage("Skills Maxed");
                break;
```

This Code will not work, whatever i do, .maxskill id the only option i have at this moment ...

### Expected behaviour

Should increase the skillpoints

### Steps to reproduce the problem

Build NPC with corescript
Click the gossip menu to increase the skill points
nothing work

### Branch

3.3.5

### TC rev. hash/commit

65929a1

### Operating system

Windows Server

### Custom changes

Added teleporter with some functions

**Comment by acidmanifesto** [comment]
I recommend you come on over to the discord where we have code enthusiasts in the custom channel. This issie git is for more issue reporting of the exsisting core.

**Comment by LabViewCode** [comment]
Nah, sry, i will not join some discords for getting support.

**Comment by acidmanifesto** [comment]
> Nah, sry, i will not join some discords for getting support.
> 

When failing to appease the machine spirit, you can always look at the method and see how that works and search the solution for any examples as well. Good luck. May the Omnissian guide you.

**Comment by Ovahlord** [comment]
your script does not work because the method does only max out skills under two conditions:

1. you need to enable  CONFIG_ALWAYS_MAX_SKILL_FOR_LEVEL (which will max out skills right away at any levelup)
2. next up is the condition that only skills defined in the SkillRaceClassInfo.dbc with the flag SKILL_FLAG_ALWAYS_MAX_VALUE will be maxed by this method because it's meant to handle this flag exclusively.

With that being said, this is not a bug, you just didn't read the code. In order to max skills, you gotta iterate over the players skills and max them individually.
