### ISSUE TITLE
Killing Machine talent

### ISSUE THREAD

**Issue by Manpower99** [TrinityCore/TrinityCore#29082]
### Description

Currently it procs from offhands aswell as mainhand white hits.
http://web.archive.org/web/20090201103330/http://elitistjerks.com/f72/t41658-dw_unholy_dps_discussion/
to cite : **Killing Machine: This is now a PPM that only triggers on white main hand attacks. The base number is 5 and improves with Haste.**

### Expected behaviour

It should only proc from mainhand white hits with PPM of 1 per rank ( 5 in total if maxxed ) with improvements by haste.

### Steps to reproduce the problem

Simply talent 5 Killing Machines and equip two 1handers and sit at dummy.

### Branch

3.3.5

### TC rev. hash/commit

[fb699dc](https://github.com/TrinityCore/TrinityCore/commit/fb699dc641342c1e1a094ec5bff7b5e581dd0d01)

### Operating system

windows10

### Custom changes

None

**Comment by CraftedRO** [comment]
Invalid, on wotlk ptr it does proc from off-hand autoattacks only too:


https://github.com/TrinityCore/TrinityCore/assets/24683355/f65227ba-5c0d-49e1-a41e-b426c3e77816

**Comment by CraftedRO** [comment]
it also proc without any weapon equipped:

https://github.com/TrinityCore/TrinityCore/assets/24683355/426a3e7e-cfbe-4139-9cf9-18ec3c183ebd

**Comment by Jildor** [comment]
I think it's a mistake to rely on wotlk classic to test certain spell mechanics from the 3.3.5 era as the results can vary considerably.
This is the 3.3.5 branch and we must find the data if possible from that version.
As stated in the main report: http://web.archive.org/web/20090201103330/http://elitistjerks.com/f72/t41658-dw_unholy_dps_discussion/

Also we can check that: https://www.bluetracker.gg/wow/topic/us-en/14578778025-killing-machine-bugged-gc-plz-review/
> Jan. 24, 2009, 6:08 a.m.
Blizzard Post
We originally talked about letting the MH and OH both proc but at different rates (Windfury does something like this). Then we became convinced that dual wielding by DKs would probably still be good even without the OH procs from Killing Machine. Now it is just main hand procs at a frequency of 5 per minute.

>PPM is a statistical average, so you will see a lot of variation unless you test for a long time. But we'll keep an eye on this thread and the talent itself to make sure.

And we can check patch notes: Cataclysm [Patch 4.2.0](https://wowpedia.fandom.com/wiki/Patch_4.2.0) (2011-06-28): 
>Can now properly be triggered from off-hand attacks as well as main-hand attacks.

https://wowpedia.fandom.com/wiki/Killing_Machine?oldid=2748901

So at least it makes me think that killing machine wotlk only worked with main hand hits due to a hotfix that they decided to remove from patch 4.2.0 and that maybe in wotlk classic they decided not to implement it or for unknown reason.

**Comment by Jildor** [comment]
Just to clarify, because I don't like to distort topics with unnecessary discussions, I see that certain wotlk classic mechanics are being taken as 100% valid data to confirm or deny 3.3.5 topics, which I see is an error for me, For this reason, I consider that warning is necessary and if I consider it appropriate to repeat it as many times as necessary, I will do it ;)

I do not have permissions to reopen issues, so if someone considers it appropriate to reopen the issue because wotlk should not always be taken as the only 100% reliable test for the 3.3.5 branch
