### ISSUE TITLE
Ride to Taunka'le Village

### ISSUE THREAD

**Issue by Berserker43** [TrinityCore/TrinityCore#29366]
### Description

Hello everyone. I found an error in the quest Ride to Taunka'le Village ( id 11888)
The problem is as follows:
1. You take the quest and the NPC id 26044, which gives out a wolf for the trip.
He doesn't give it away.
2. When you're on this quest, you can actually talk to the stable master right behind him: Durkot Wolfbrother. And he will ride you to your destination.
Enjoy your ride!
https://www.wowhead.com/wotlk/quest=11888/ride-to-taunkale-village

### Expected behaviour

Described in the paragraph below

### Steps to reproduce the problem

Make it so that the NPC gives out a riding wolf for a road trip to the village of Taunka'le.

### Branch

3.3.5

### TC rev. hash/commit

[2df1bc3](https://github.com/TrinityCore/TrinityCore/commit/2df1bc3ec12d4a3ed7bac1274d8810ca3538607d)

### Operating system

Win Server 10

### Custom changes

no

**Comment by CraftedRO** [comment]
This issue is invalid since [on the same comment you pointed](https://www.wowhead.com/wotlk/quest=11888/ride-to-taunkale-village#comments:id=607798) in your issue someone else also said that you actually have to do a quest chain and also this quest https://www.wowhead.com/wotlk/quest=11916/hellscreams-champion to be able to talk to stable master and get a "free trip".
