### ISSUE TITLE
Argent Vanguard Spirit Healer is phased out

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#29388]
### Description

Argent Vanguard Spirit Healer seems phased out and you won't be able to ressurect yourself after you die in that zone for some reason (probably related to that specific zone phase).

```sql
SELECT * FROM `creature` WHERE `guid` = 98912 AND `id` = 6491;
```

### Expected behaviour

I guess you shoud be able to ressurect there like on any other spirit healer.

### Steps to reproduce the problem

.go xyz 6080.320801 95.586464 369.534454 or .go c 98912

.die then press release spirit

notice no spirit healer available if you don't use .gm on

### Branch

3.3.5

### TC rev. hash/commit

d5b64a0bb23c

### Operating system

Windows 11 x64

### Custom changes

None

**Comment by CraftedRO** [comment]
Seems this might be a blizzlike bug since it happen on wotlk classic ptr 3.4.3 (51831) too but there sometimes spirit healer appear (if you go to the quatermaster as spirit and come back at gy).

**Comment by Windmere98** [comment]
Hi.  New here looking to make my first contribution.
Looks like that Argent Vanguard graveyard is in phase 2 be default until you complete some quests.
completing https://www.wowhead.com/wotlk/quest=13070/a-cold-front-approaches shifts you to phase 64.
completing https://www.wowhead.com/wotlk/quest=13086/the-last-line-of-defense shifts you to phase 128.
completing https://www.wowhead.com/wotlk/quest=13141/the-battle-for-crusaders-pinnacle shifts you to phase 1.
Since spirit healers are phase 1 you won't be able to see that spirit healer until you've completed that final quest in that chain.
I was able to fix the issue by:
```SQL
UPDATE `world`.`creature` SET `phaseMask` = '195' WHERE (`guid` = '98912');
```
So the phasemask will include all the phases you encounter in the graveyard but I did notice practically every Spirit Healer besides one other one has a phasemask as 1 so I'm not sure if this is the preferred method but it seems to work.
