### ISSUE TITLE
Gilneas Panicked Citizens

### ISSUE THREAD

**Issue by malcrom** [TrinityCore/TrinityCore#29590]
### Description

Cosmetic added pathing and SAI.

### SQL fix

```sql

```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. ba627c1d1c42+ 2024-01-16 23:49:03 +0100 (Gilneas branch) (Win64, Debug, Static)
Using SSL version: OpenSSL 1.1.1u  30 May 2023 (library: OpenSSL 1.1.1u  30 May 2023)
Using Boost version: 1.78.0
Using MySQL version: 80033
Using CMake version: 3.28.0-rc5
Compiled on: Windows 10.0.19045
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled

**Comment by mdX7** [comment]
i'd suggest to give the path name some purpose, something along `Panicked Citizen - On Respawn`, so it describes where its actually used

**Comment by malcrom** [comment]
Updated from phone

**Comment by malcrom** [comment]
3 weeks is long enough.

**Comment by malcrom** [comment]
It's been over a fucking month. What is the issue?

**Comment by Legoso** [comment]
> It's been over a fucking month. What is the issue?

Assignees too busy IRL, perhaps? And maybe nobody else checking for fixes like this one?

**Comment by malcrom** [comment]
I'll delete it then. Because this is disrespect of my time.

**Comment by mdX7** [comment]
> > It's been over a fucking month. What is the issue?
> 
> Assignees too busy IRL, perhaps? And maybe nobody else checking for fixes like this one?

Assigned people are planning to start Cataclysm classic branch and some Cataclysm stuff is already implemented in Ovahs Cataclysm Preservation Project fork where a lot of stuff will be ported from. And to prevent double-work i just assigned them.

> I'll delete it then. Because this is disrespect of my time.

Disrespect of your time because assigned people did not have time to review it yet? In other OSS projects people sometimes even wait years until something is being looked at (having some pr of jackpoz at Microsoft in mind with this statement fyi). Keep in mind people are having lifes, some even a family and other responsibilities which forces them to not look at TrinityCore stuff for a certain amount of time. 
At the end of the day we are still doing this for fun in our free time, voluntarily. So trying to put pressure onto reviewers is pretty much counterproductive and may even cause the exact opposite result. I mean reminders are totally fine imo, but not in an aggressive, pissed way as we've seen it above.

Also you're still intentionally causing more time required on review side because you are STILL not using our tools after telling you x times, causing more work on review end. 

Funny enough i just reminded Ovah yesterday about the GIlneas issues and he was like "they're fine, you can push" - but i didn't push them yet as it was late. If any proof is required: 
![image](https://github.com/TrinityCore/TrinityCore/assets/12143653/3ba56611-48c5-4adf-93ae-c297d40ad4a2)

Locking the conversation here. For any further discussion hop onto Discord and flame me there, thanks.
