### ISSUE TITLE
DB/Creature: Fix some dberrors

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#29653]
### Description

Not sure what this error is supposed to mean but as I coud check on db side everything seems fine related to this npc:

> WaypointMovementGenerator::DoInitialize: couldn't load path for creature (GUID Full: 0xf130003cb6000001 Type: Creature Entry: 15542  Low: 1) (_pathId: 0)

![Captură de ecran 2024-02-03 051309](https://github.com/TrinityCore/TrinityCore/assets/24683355/ff49c032-7df3-420d-86d5-659492be03fa)

### Expected behaviour

Either I miss something either this error information might be improved.

### Steps to reproduce the problem

.go c 43201
trigger the error

### Branch

3.3.5

### TC rev. hash/commit

b4783d6cace49ae0cfe2b0d5059ba776840b307b

### Operating system

Windows 11 x64

### Custom changes

[Passive anticheat](https://github.com/TrinityCore/TrinityCoreCustomChanges/commits/3.3.5-passive_anticheat)

**Comment by Ovahlord** [comment]
it means this creature is attempting to start a waypoint path with Id 0. Which means the movementType in the creature table is wrong.

**Comment by CraftedRO** [comment]
so now creature formation members shoud only use MovementType 0 instead ?

**Comment by Ovahlord** [comment]
yes. only the leader is meant to move along the path  so only the leader gets the waypoint movement type.

**Comment by CraftedRO** [comment]
I'm pretty sure there are others with same problem and I guess they can be fixed with a more general query but this will fix those ones at least.
```sql
-- Fix some dberrors
UPDATE `creature` SET `MovementType`=0 WHERE `guid` IN (43202,43203);
```

**Comment by Legoso** [comment]
To me, it looks like your issue was caused by killing these 2 NPCs https://aowow.trinitycore.info/?npc=15542/twilight-marauder (escort for https://aowow.trinitycore.info/?npc=15541/twilight-marauder-morna ) with the GM command `.die` and not aggroing Twilight Marauder Morna. But if you had aggroed NPC 15541, you would have triggered all 3 to dismount and attack your character, making it very unlikely that the error log entries you posted would be created. (Ref. issue #29652)

I don't know, but could it be that the escort NPCs need to have waypoint path movement type to be in their formation with Twilight Marauder Morna (NPC 15541)?

**Comment by Legoso** [comment]
Thank you for confirming this, I presume you have tested that the SQL line solves your error log issue.

**Comment by CraftedRO** [comment]
> yes. only the leader is meant to move along the path so only the leader gets the waypoint movement type.

can't creatureformation members have their own MovementType 1 for own wander_distance (in creature table) I mean there are few enties like this, will they use both: follow the leader and also using own wander distance at the same time ?
