### ISSUE TITLE
[Item] The Egg of Mortal Essence

### ISSUE THREAD

**Issue by EnteringCombat** [TrinityCore/TrinityCore#4485]
Hello,
This item http://old.wowhead.com/item=40685 is suppost to proc only off direct healing spells. It currectly procs off both healing and damaging spells.

We're using revision 090bb5a
Thanks in advance.

**Comment by Killyana** [comment]
Updated with 45secs CD:
``` sql
DELETE FROM `spell_proc_event` WHERE `entry` IN (33953);
INSERT INTO `spell_proc_event` (`entry`,`SchoolMask`,`SpellFamilyName`,`SpellFamilyMask0`,`SpellFamilyMask1`,`SpellFamilyMask2`,`procFlags`,`procEx`,`ppmRate`,`CustomChance`,`Cooldown`) VALUES
(33953, 0x00, 0x00, 0x00000000, 0x00000000, 0x00000000, 0x00004400, 0x00000000, 0, 0, 45);

**Comment by Demonid** [comment]
The Proc for Hots doesn't work on 5cb1555de6db43db03d6202b7edaa9c6835ecfab

`There's a few varying opinions here in regards to Druids, so I thought I'd take one for the team and buy the thing just to get the truth. I'll just state what I found and let you decide if it's worth the Emblems or not!

    It procs on HoT ticks!
    It procs on direct heals.
    It will proc regardless of who the heal is on.
    It does NOT proc on HoT ticks that were 100% overheal, but direct heal overheals can still proc it.
    As an exception to the above, the bloom from Lifebloom cannot proc it on an overheal, despite the overheal appearing in the combat log like a direct heal (unlike HoT ticks).
    There is a difference between the trigger on this trinket and "on spell hit/cast" trinkets/talents like Valonforth's Remembrance. For example where that trinket will proc on the initial casting of Rejuvenation, the Egg will only proc on the actual ticks.
    As expected there is an internal cooldown, the quickest I could get two successive procs was 48sec using Lifebloom.

Update: For the life of me I can't get this to proc on Swiftmend, overheal or otherwise.`

http://www.wowhead.com/item=40685/the-egg-of-mortal-essence#comments
