### ISSUE TITLE
Creature/Object View Distance During Loading

### ISSUE THREAD

**Issue by jaredjones** [TrinityCore/TrinityCore#4755]
So this issue has been persistant among all of the WoW private server distros since the beginning. Basically you know how in the .conf file you can specify view distance for objects, creatures, players ect... Well when a character is first created and the game takes you through the intro video around the terrain of the game you do not see any animals, objects, players, ect... Until you get within the view distance of your character, that you specified in the .conf file... Well this is not blizz-like, all animals, objects, and players should be noticeable during the intro video then it should return back to the conf file settings.

The way to circumvent this is to have the view distance for objects, players, creatures overridden from what is in the configuration file during the loading screen. You would change the view distance for all options to the radius of the starting zones.

**Comment by jaredjones** [comment]
Interesting assertion.

**Comment by Expecto** [comment]
Problem in Grid System...

**Comment by r00ty-tc** [comment]
Just to throw an update on this.

The problem isn't grid, that's not even close. Also the player doesn't send the info about location when the cinematic plays.

So, the solution to this is to retrieve waypoints, and set player viewpoint to simulate the cinematic locations.

I have this https://github.com/r00ty-tc/TrinityCore/tree/folly_cinematic which does the trick. But, it needs a bit more work yet.

Essentially, waypoints are extracted from camera M2 files, these are translated (because they use a geometry based on start orientation in the Cinematic DBC) to generate useful co-ordinate sets.

When the server sends cinematic start, the client sends the next camera opcode once it has actually started the cinematic. This triggers the process of spawning an invisible NPC, binding player sight to it and sending it along the path of the cinematic waypoints extracted before.

Because speed is often very high, visibility and grid activation distance is extended too.

**Comment by jaredjones** [comment]
Wow.... Bravo.
I never realized it would take this many changes to implement this now 4 year old bug report.

**Comment by tkrokli** [comment]
Yes, thank you r00ty for the new insight into how the cinematic view is supposed to work, it is really nice to know a bit more about what actually goes on during the cinematic intro. Keep up the good work! :+1:
