### ISSUE TITLE
[quest] Springing the Trap

### ISSUE THREAD

**Issue by TheMaaster** [TrinityCore/TrinityCore#5137]
when trying to do [Springing the Trap](http://old.wowhead.com/quest=11969) i can't seem to find the [signal fire]() (pile of wood)
and from what i read out there, looks like needs bunch of scripting aswell
##

**Comment by Rushor** [comment]
grid system is a problem here, if you don't set all envolved npcs active (malygos, KERISTRASZA) after the port, the will do nothing :/ else the script works perfectly.

**Comment by fvicaria** [comment]
Confirmed: 5310fb1aa7bb+

When using the quest item next to the bonfire it only shows a "misfire" animation and knocks you down.
Kerisstrasza does not appear.

**Comment by digz6666** [comment]
Confirmed e6571f9869ec725fb7d50c568f704d150a11b216

**Comment by ccrs** [comment]
you can set them active on script start and unactive on despawn/end :+1:

**Comment by Rushor** [comment]
nevertheless hack

**Comment by ccrs** [comment]
its not if you remove it.

Also even if you leave it active it wont be considered a hack. Its just a way to prevent big memory usage.

**Comment by DevQuad** [comment]
Any news?

**Comment by Kodekc** [comment]
summon @dr-j  :-)

**Comment by Axerion** [comment]
Well, I grabbed Dr. J's script and took a complete look over and it's good for the first half EXCEPT the position is wrong.. I changed the move position to 4039.16 7085.585449 167.927933 and the corpse spawn to 4033.788818 7086.634277 167.158249. To get the dragon to fly I changed Keri's (26237) InhabitType to 7 to allow for flight.. I fixed the move speed prior to flight which was ridiculously fast to 1.5 which makes it more casual. I adjusted the timing for the say and spell like this:

Id 6 to 5000
id 8 to 3000
id 10 to  3000 (to give a delay before the takeoff so it wasn't so rapid)

It feels more streamline for the first part... the reason why it doesn't work is because he used despawn at the end when really you're suppose to use the keri kill credit spell which gives credit to your quest and makes her despawn. But I plan to make the second half by changing:

id 11 (despawn) to move pos to a spot on the ground after the spell ends for transport > wait timer in id 12 which will activate the kill credit. This will work within Malygos's script which i'll make which at id 10 so all id's would get pushed up 1 so 11 becomes 12 and 12 becomes 13 but the new 11 will be a spawn script for Malygos.. when Malygos spawns on spawn will spawn the two red dragonflight dragons which will fly around him in a circle.. 1 for each at 4 waypoints and 4 attacks each.. Malygos will be on a spawn timer and so will the dragons themselves  but anywho it'll work like this:

after id 10 executes id 11 will spawn Malygos
Malygos spawns the 2 drakes
the 2 drakes start at their positions > attack
both will move to new position then attack
both will move to a new position then attack
then they both will be back at the start.. so think of a compass.. say one drake starts at East.. it'll attack.. then move to North.. then attack.. then move to West and attack.. then move to South and attack then move back to East then repeat... manipulate it within the timeframe it takes to get from point a to point b then when you are about to get to point b you can have them despawn. reach point b and id 12 activates.. you have the timer for Malygos to move to waypoint near Keri.. then enter chat which you can get from the youtube video before casting his spell at Keri.. which should fall close to the time before kill credit activates.. then set the timer for Malygos's despawn after the spell cast so he despawns after Keri... essentially you can plan it out via timeline. You just need to time the takes to get from point a to point b.. time it takes for your drakes to make a full rotation fill that in between the time it takes to get from point a to point b but do not go over the time it takes from point a to point b. I'll give more indepth details or if people desire I can possibly post the revised Dr. J script but I'll wait till after I have it completely fixed before I post again.

**Comment by Axerion** [comment]
But I have the first part done.. i'm going to work setting up Malygos and the drakes (Could make a cool band name!)

**Comment by Axerion** [comment]
Also, it's kinda off topic but my email is wowburner1@gmail.com i'm still working on learning the whole stuff but if anyone has questions about anything in the database. I also have compiled a list of hidden display id's for objects, working on making a similiar list for creature display id's and going to add the rest of the object display id's to the hidden ones. So if you guys end up becoming interested in object displays and creature displays!

**Comment by Axerion** [comment]
looks like the id for Malygos is 28859

**Comment by Axerion** [comment]
just need to find out what spell he used.. o.o

**Comment by Axerion** [comment]
Actually I would probably remake him into a fresh npc.. that npc 28859 is tied to the dungeon.. all the others i'm not sure of but making a new npc for it would work. Using 28859's display id which is 26752 and setting it's inhabit type to 3 and it's speed_run to 2 activating it's Smart AI.. creating a time action list on spawning, probably making it invincible, create the timing for when it should move position to Keri on the ground, to talk all the lines, then spell cast, then despawn after keri despawns

**Comment by Axerion** [comment]
sorry inhabit type to 7

**Comment by Axerion** [comment]
So far i've been able to make it work.. I created new npcs for Malygos and Ruby Drakes... he casts spells at the drakes but I need to script the drakes for movement.. but he flies down and the timing of the event works.. I don't know the spell for the ice on Keristrasza but i'm trying to make an Ice Block work as a substitute but she gives kill credit properly so the quest can be completed.. it's all just fine tuning for me.

**Comment by Axerion** [comment]
Dr J's script needed some minor tweaks but it definitely was the connector for the quest item to work.. the only extra that needs to be done is a condition to be able to use the item based on the game objects state to prevent it from being spammed on the gameobject.

**Comment by Pitcrawler** [comment]
You can just look at my fix above. All the spells and timings were sniffed.

**Comment by Axerion** [comment]
I see.. i'll have to test it XD so far i've got it reasonable the only thing i'm working on is the drakes.. minor tweak.. but shit I should have ran your script if the only thing wrong was the kill credit missing o.o if it was

**Comment by Axerion** [comment]
All you have to do to give credit to the player is to direct the spell 37712 to the player whenever you want them to have credit.. base it on range that is reasonable

**Comment by Axerion** [comment]
With Malygos not moving also, keep in mind you need to set his movement type to 2.. aside from that sometimes he won't move because of a timer or if he's in the middle of executing something else.. but I reduced the frequency of him attacking the Drakes so that makes him descend each time. o.ob

**Comment by jerbookins** [comment]
c5fa08afc1d1

Still not working. Does not trigger cut scene. Using the Raelorasz' Spark just knocks you on your back and nothing happens.

**Comment by CraftedRO** [comment]
This quest is still bugged on 2f9e386 
After this : "Keristrasza says: Come, Player. Let us see the fruits of our efforts." she teleport you at 34.35 , 25.20 without quest credit.
Am I wrong ?

**Comment by illfated** [comment]
@CraftedRO : I recommend opening a new ticket for the issue. The root cause for the issue may not be the same as the one discussed above, due to the overall source changes during the last 2 years, making it less likely that your observed issue is directly comparable to the old issue(s). You may link back to this issue (#5137) in your new ticket, if you find that there are important details in this page related to your discovered issue.
