### ISSUE TITLE
Continuous Quests sometimes fails

### ISSUE THREAD

**Issue by SpaHost** [TrinityCore/TrinityCore#5368]
If you finish a quest and has a new quest, if you accept that quest it fails to load, and you have to talk again with NPC to get the new quest.

Last core rev: Build 2012-02-22 03:45:52

**Comment by Killyana** [comment]
Cannot reproduce on rev. 68c4ea314443 seems fixed long time ago.

**Comment by zaphod77** [comment]
This issue is caused by DB errors, or by badly constructed quest chains.

When core opens a next quest up that's supposed to follow from finishing a quest, it skips the checks for it, but when you try to accept it, it gives the don't meet requirements message.  You are failing either a level check, a reputation check, a skill check, a race check, or a condition check.  Most of these chains that were messed up in BC should have been corrected by wotlk.  In the case of a level check causing the fail, that means next quest should have been empty. In fact if at any step of the way it's possible to complete a quest part and not meet requirements for the next one, nextquest should be cleared in database to stop this bug (PrevQuest will still be set, and the quest will still be locked down)

**Comment by tkrokli** [comment]
Not sure if this is directly related, but I am sometimes unable to click [Accept] on one of the 3.3.5 Orc starting quests, but it is automatically accepted in the chat window, so I just click the top right [X]
instead of the [Accept] button and then go on to do the quest and complete it normally.
