### ISSUE TITLE
[Missiles] Result of a spell is decided before it reaches the target

### ISSUE THREAD

**Issue by click** [TrinityCore/TrinityCore#577]
The result of a spell is decided before it reaches the target, what generates a serie of related issues.

Exemple #1:
1. Have a mage cast Frostbolt at a Rogue or Night Elf;
2. Rogue cast Vanish or Night Elf cast Shadowmeld;
3. Frostbolt hits him anyway. Should Evade.

Exemple #2:
1. Have a shaman cast Lava Burst at a Priest;
2. Then cast Purge at the priest's Power Word: Shield;
3. The Lava Burst is absorbed anyway. Should hit at full power.

Exemple #3:
1. Have a Warlock cast Death Coil at a Paladin;
2. Paladin cast Divine Shield;
3. Paladin is affected by Death Coil anyway. Should be Immune.

Exemple #4:
1. Have a Hunter cast Deterrence or a Paladin cast Divine Shield;
2. Wait until its 0.2 sec to end then cast some missile spell at him like Ice Lance;
3. Hunter deflects it anyway. The effect is gone, he should be hit at this point.

Exemple #5:
1. Cast a missle spell at someone;
2. Activate your Spell Power trinket;
3. The spell isn't affected by the additional Spell Power.
##

**Comment by Demonid** [comment]
Yesterday i was watching some old Brang (Hunter from retail) videos and this show up:

https://www.youtube.com/watch?v=umetTVtTb2A
Minute: 1:02

As you can see, Brang used deterrence AFTER the Shaman had casted (It was Mid Air) and it got reflected.

This video was was recorded during Season 6 on Retail.

So the question here is... is this how it should work on 3.3.5a or it got change between S6 and S8?

Thanks.

**Comment by Goatform** [comment]
Confirmed on 3d5c1b83b15cfc9f73888eb525c64323266c1fd4

**Comment by Rushor** [comment]
some more examples:

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
If you are warrior or rogue and you see spell is mid air poppin cloak or reflect/shieldwall is pointless due to damage will go through.
**Expected behaviour**: Tell us what should happen instead
you can use defensive cooldowns like cloak/reflect/shieldwall even when spell is mid air
**Steps to reproduce the problem**:

1. Start a duel against mage
2. Do a shatter combo
3.  Use cloak/reflect/shieldwall mid air of shatter combo

Cloak of shadows [http://wotlk.openwow.com/spell=31224]
Spell reflection [http://wotlk.openwow.com/spell=23920]
Shied wall [http://wotlk.openwow.com/spell=871]

Summoning @ariel- here. you did the most great changes to spells in the last months :) maybe it's a easy fix for you :)

**Comment by robinsch** [comment]
That's not blizzlike. You could never cloak or reflect something mid-air

**Comment by Rushor** [comment]
hm yeah https://eu.battle.net/forums/en/wow/topic/17614451290

> The fact that this post is upvoted deeply worries me.

> You can't reflect spells that are in mid-air, the cast has to have finished while Spell Reflect was up, not before.

But this should also count for shieldwall?

**Comment by chaodhib** [comment]
Rogues could vanish mage's Pyro and warlock's Death coil. That I know for sure. (there are plenty of well known arena players doing exactly that in videos, such as [Neilyo](https://youtu.be/rqbBDGa61-A?t=33s)). Same for mage ice blocking incoming pyros and death coil. I'm not sure regarding the Shadow Cloak.

**Comment by robinsch** [comment]
No it did not. Resists were calculated on spell release.

**Comment by Killyana** [comment]
This Issue is wrong the result of the spell is calculated when the spell is casted and not when it reaches the target.
https://us.battle.net/forums/en/wow/topic/7414944435
https://us.battle.net/forums/en/wow/topic/10671327071
