### ISSUE TITLE
damage before model contact ?

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#5794]
ive watched out this some times and the thing is:

on retail the melee attacks damage the npc/player at model hit so  if the weapon has contact to the body of the target. but in emus the damage already arrived during the player/npc is swinging his weapon....

**Comment by Aokromes** [comment]
If https://github.com/TrinityCore/TrinityCore/issues/5794#issuecomment-16180955 is valid anyone can create a PR for it?

**Comment by trickerer** [comment]
As for me, I can only give you final version of this patch. Hope someone will update it from revision which is two years old.

http://paste2.org/Y42v8Ikv

**Comment by tkrokli** [comment]
Copied your paste2.org page to Gist (secret) for easier reading in .diff format:
https://gist.github.com/tkrokli/9365bcd252fc48781680dd7d7d766f71#file-melee_damage_delay-diff

**Comment by trickerer** [comment]
I want to point out a problem which is not very noticeable but can cause some serious issues and not so easily resolved.

Put Player A and Player B in situation:
1) B is 1 hp left
2) A attacks B with normal melee attack which gonna deal 100 damage after 500 ms delay
3) B uses Divine Shield / Ice Block / any normal damage immunity mechanic ability
4) A and B (and everyone around) see combat log:
A's melee swing hits B for 1 Physical.(99 Overkill)
B casts Divine Shield.
5) B dies.

Result: Player B is invulnerable (and DS on cooldown) but still dies because damage was calculated at A's attack start. Player B is confused.

If all delayed melee damage against B is cancelled when he pops invulnerability then Player A is confused instead, seeing he deals damage (in combat log and on screen) with overkill which has to be a killing blow but actually isn't.

**Comment by P-Kito** [comment]
I like the part: "Player B is confused."   :-D

**Comment by Shauren** [comment]
https://github.com/TrinityCore/TrinityCore/pull/17549#issuecomment-233016509
This is not a bug.
