### ISSUE TITLE
{Quest/Zone} A Life Without Regret / Undercity [$50]

### ISSUE THREAD

**Issue by durrrr** [TrinityCore/TrinityCore#5988]
Hello,
I have encountered a problem while playing in "Undercity" Zone.

How to reproduce the bug:
1. Get quest "A Life Without Regret".
2. Go to Undercity.

What should happen, what happens instead:
You should have an epic quest (notice the quest data and links below) instead, there is no script for it, at all.

Links:
http://old.wowhead.com/quest=13266 --> The quest (Old Wowhead)
http://www.wowwiki.com/Quest:A_Life_Without_Regret --> The quest (Wowiki)
http://old.wowhead.com/zone=1497 --> The zone (Old Wowhead)
http://www.wowwiki.com/Undercity --> The zone (Wowiki)

I'm running Unix on hash: b23ff22 , TDB 335.11.46+
Addons: AH bot and WG.

Regards,
durrrr

**Comment by bieleib92** [comment]
Has there been any progress?

**Comment by Rushor** [comment]
nope and this quest cannot be sniffed anymore.

**Comment by Rushor** [comment]
summoning @tkrokli to research all the details for http://wowwiki.wikia.com/Quest:The_Battle_For_The_Undercity_%28Horde%29

**Comment by tkrokli** [comment]
Thanks for the summon and the chat on #trinity. I will start digging for info later tonight, though I don't know exactly how soon I can post anything useful. I would very much like to see this event in-game, though. :-)

**Comment by JamminWidYou** [comment]
50$ and noone is working on it?Oo i'll take a crack at it then

**Comment by tkrokli** [comment]
Feel free to do so. It is still a bit above my skills. I would have started if I was any good at coding as well as knowing enough about the phasing parts.

**Comment by vlomax** [comment]
There's another wiki page for this quest, with all or most of the relevent NPCs and auras - http://mmoarch.wikia.com/wiki/Herald_of_War
Hope it helps!

**Comment by JamminWidYou** [comment]
@vlomax Finished this quest, you can update your local core and check for bugs :p https://github.com/TrinityCore/TrinityCore/issues/16067

**Comment by tkrokli** [comment]
@JamminWidYou : we appreciate your effort and the work you have done. As far as the Bounty goes, I think it includes the "Battle for Undercity" part too, though I can't speak for the person posting the bounty @ bountysource.com -- that would be up to the bounty poster to decide, I think.

**Comment by JamminWidYou** [comment]
Issue is about this quest tho :> 
i'll probably script battle as well but it will take hella longer, lots of stuff to find and gotta write some kind of zone handling, but like i said in PR, make two issues for each battle for the undercity( horde and ally ) and post entries/GOs/worldstates/other stuff there

**Comment by tkrokli** [comment]
Since @vlomax is the Bounty poster, maybe we could have a word from him in that regard? :)

**Comment by vlomax** [comment]
@tkrokli Would be awesome to have the battle scripted - and that might've been the hope when I posted the bounty - but it is a huge undertaking.  I figure it'll get done when it gets done.

**Comment by tkrokli** [comment]
@vlomax : OK, thanks for the feedback. Just getting the phasing in place for the quest is a start, though.

**Comment by Rushor** [comment]
maybe you need to edit the bounty for this issue and add a new bounty for the new issue for the uc-fight

**Comment by JamminWidYou** [comment]
Issue was about life without regrets and backer himself posted link to wiki that explains this quest.
As far as battle goes, create issue about it, back it up with some info and ill give it a shot, not promising anything, that event is huge and without sniffs its really hard. There is some stuff that has to be implemented into TC (like zone-handler - something like instance_script but for zone) that will handle getting GUIDs, worldstates and shit like that so i dont have to search grids for units. Also fuckton of research for spells and triggers

**Comment by vlomax** [comment]
@JamminWidYou I may post a bounty soon at least for the Alliance version, since that one's arguably the easier of the two, and it's the one I've done the most research on.  Just have to double-check the wiki first, to make sure it's as thorough as possible.  :)

**Comment by JamminWidYou** [comment]
I shall take a look at it then ;)

**Comment by vlomax** [comment]
@JamminWidYou finally got a chance to test this, and noticed a few minor things.  The biggest one might be that if the player doesn't turn in the quest and waits to re-trigger the event, the guards won't close in on Jaina again.  Everything else repeats just fine, just not the guards.  
* It looks like the wrong area trigger is being used.  Currently 5311 (center of room) is used, but from the videos it looks like it should be 5279 (near Thrall).
* Spell 55761 should be cast on Jaina as she spawns, for a teleport-in effect and camera shaking.
* Jaina, Thrall, and Sylvanas should walk back to their starting points, instead of running.
* The left Undercity portal (when facing Thrall's throne) despawns with Jaina at the end.
* Thrall takes a while before he resumes pacing at the end.  I think he's supposed start pacing almost immediately, but I may be remembering it incorrectly, and the players in the Youtube videos don't stick around long enough.
* Sylvanas doesn't kneel at the start or end.

Overall it's looking good though!

**Comment by JamminWidYou** [comment]
Aight ill try to fix it when i find some time

**Comment by JamminWidYou** [comment]
@vlomax the part about portals, probably but the issue is we have no way to sniff this quest and i can't find invisibility aura that will handle that, so for now it has to stay like that. If someone finds that aura, we can move that portal to be perm spawned via DB and handle visibility in spell_area. 
The left portal is supposed to despawn afaik

I'll fix other reported stuff here and in PR later today

**Comment by JamminWidYou** [comment]
@vlomax aight i updated my PR, if you could check now. As i said earlier, portals cant be done other way without knowing proper invisiblity aura

**Comment by vlomax** [comment]
@JamminWidYou It looks like the guards are getting bored - when the event is triggered a second time, they now walk towards Jaina instead of running.  :P 

For the portals, there are a few options.  They may not be correct, but they're my best guess at the moment - auras [54500](http://www.wowhead.com/spell=54500/quest-invisibility-1) or [60190](http://www.wowhead.com/spell=60190/invisibility) could be applied to the portals (both have the same effect), while [59068](http://www.wowhead.com/spell=59068/post-wrathgate-invisibility-detect) will let players see them.

**Comment by JamminWidYou** [comment]
I think 59068 is supposed to be used in alliance version of the quest in SW, anyway whats the difference? phasing is setup that way that even if you miss your chance to go thru portal you can go to UC using zeppelin and you'll see thrall/sylvanas and voljin :p I'll try to find correct spell later tho

**Comment by vlomax** [comment]
Actually I think the Alliance has its [own set of auras](http://mmoarch.wikia.com/wiki/Fate,_Up_Against_Your_Will#Phasing), with a different level of invisibility.  The faction may not matter in any case, if the auras are tied to the quest and zone.
Either way I'm just being picky.  Years of waiting for these quests to be implemented, you know?  Tying the portal visibility to the follow-up quest would make it more Blizzlike, I think, and it'd save the player from having to catch the zepplin if the portals despawned while they're off fixing a sandwich instead of listening to the NPCs talk.  :P

**Comment by JamminWidYou** [comment]
Aight got an idea, will push it tonight ;p

**Comment by JamminWidYou** [comment]
@vlomax 
Moved the portals to DB and its handled by invisiblity aura now

**Comment by vlomax** [comment]
@JamminWidYou 
Looks good!  Only thing that sticks out is UC_Sylvanas is using the same entry as the Orgrimmar version.  Should be 31651 instead of 31419, but that'll only be an issue if/when the Battle gets scripted.
Other than that, I say ship it!  :)

**Comment by zaphod77** [comment]
stuff is hidden by phasing, as far as I know , not invisibility. I did find the phasing spells.

Anyway as I said, i sorta have battles scripted, but they are a bit glitchy,  And all my efforts at getting the end of quest cutscene to work right have failed miserably and i have no idea why.

I had the prequests working or at least able to turn in and the portals appearing when they should but just used phasing.

**Comment by JamminWidYou** [comment]
GOs cant have auras, its handled by invisibility in gameobject_addon and player can see that due to detect invisibility auras with proper values

As far as battle goes, there is some implementation required to do it properly without massive grid searches and other stuff like that but thats for another issue and another day

**Comment by ccrs** [comment]
GOs can be in one or several phases (bitmask value) and player can see them or not depending on their own auras which set the player in a determined phase, you shouldnt use invisibility in this case.

**Comment by JamminWidYou** [comment]
Portals are spawning when you get A life without regret quest, but in order to get that quest you have to be in phase 64 which is applied to you when you have previous quest, so how im supposed to hook it up to phasing when there is only one aura?:P

**Comment by Aokromes** [comment]
Test #16067

**Comment by Aokromes** [comment]
3002839
