### ISSUE TITLE
[Core/Spells] Dancing Rune Weapon

### ISSUE THREAD

**Issue by Amit86** [TrinityCore/TrinityCore#6192]
Below may be not valid anymore, here's more fresh description of what is broken here https://github.com/TrinityCore/TrinityCore/issues/21538 + https://github.com/TrinityCore/TrinityCore/issues/25675
https://github.com/TrinityCore/TrinityCore/issues/6192#issuecomment-109767527 and in comments below
Abandoned PRs https://github.com/TrinityCore/TrinityCore/pull/16281 https://github.com/TrinityCore/TrinityCore/pull/23191

--

This spell was recently ( 24b699d904aa ) fixed, but I am getting these log errors:

> 2012-04-13 08:31:43 ERROR: Unit::HandleDummyAuraProc: Spell 49028 has non-existing triggered spell 1206
> 2012-04-13 08:31:43 ERROR: Unit::HandleDummyAuraProc: Spell 49028 has non-existing triggered spell 1206
> ...

Using hash 4daafd0
##

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/64925-core-spells-dancing-rune-weapon?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).

**Comment by SQLfix** [comment]
Confirm

**Comment by Keader** [comment]
still bugged on rev. 3aa177410010

**Comment by robinsch** [comment]
@Keader What is not working correctly currently and how is it supposed to work? If you complete the report I will take a look at this.

**Comment by Keader** [comment]
It is not attacking after use(The infernal appears, however does not attack any target). The weapon should copy the Dk damage (however it always gives 50% of the copied damage) by 12 seconds. However in my tests it was giving only 1 damage.

Spell Description:

Summons a second rune weapon that fights on its own for 12 sec, doing the same attacks as the Death Knight but for 50% reduced damage.

http://wotlk.openwow.com/spell=49028

**Comment by robinsch** [comment]
Since no data for visual effects and melee damage is reported here the fix which is 100% not like Dancing Rune Weapon worked on retail.

Better fix for the melee swing would be to implement a script AI call when owner deals damage and implement a proper script for the pet:

```sql
INSERT INTO `spell_proc_event` (entry, procFlags) VALUES
('49028','69652');
```

```diff
diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index 6ea0882..42f079f 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -7139,11 +7139,26 @@ bool Unit::HandleDummyAuraProc(Unit* victim, uint32 damage, AuraEffect* triggere
                         break;
                     }
 
-                if (pPet && pPet->GetVictim() && damage && procSpell)
+                if (pPet && damage)
                 {
-                    uint32 procDmg = damage / 2;
-                    pPet->SendSpellNonMeleeDamageLog(pPet->GetVictim(), procSpell->Id, procDmg, procSpell->GetSchoolMask(), 0, 0, false, 0, false);
-                    pPet->DealDamage(pPet->GetVictim(), procDmg, NULL, SPELL_DIRECT_DAMAGE, procSpell->GetSchoolMask(), procSpell, true);
+                    if (procSpell)
+                    {
+                        uint32 procDmg = damage / 2;
+                        pPet->SendSpellNonMeleeDamageLog(victim, procSpell->Id, procDmg, procSpell->GetSchoolMask(), 0, 0, false, 0, false);
+                        pPet->DealDamage(victim, procDmg, NULL, SPELL_DIRECT_DAMAGE, procSpell ? procSpell->GetSchoolMask() : SPELL_SCHOOL_MASK_NORMAL, procSpell ? procSpell : NULL, true);
+                    }
+                    else
+                    {
+                        CalcDamageInfo damageInfo;
+                        CalculateMeleeDamage(victim, 0, &damageInfo, BASE_ATTACK);
+                        damageInfo.attacker = pPet;
+                        damageInfo.damage = damageInfo.damage / 2;
+                        // Send log damage message to client
+                        pPet->DealDamageMods(victim, damageInfo.damage, &damageInfo.absorb);
+                        pPet->SendAttackStateUpdate(&damageInfo);
+                        pPet->ProcDamageAndSpell(damageInfo.target, damageInfo.procAttacker, damageInfo.procVictim, damageInfo.procEx, damageInfo.damage, damageInfo.attackType);
+                        pPet->DealMeleeDamage(&damageInfo, true);
+                    }
                     break;
                 }
                 else
```

**Comment by Keader** [comment]
I and @sirikfoll  did some tests with the fix above.

Problem 1: The "weapon" does not follow the target, so if you use the spell and the target moves, she keeps hitting where it was called getting ugly visually

Problem 2: Apparently the Damage copied is just the Melee Damages (Auto-Attack), damages spells are not copied

**Comment by sirikfoll** [comment]
Also, the weapon sometimes copy a melee hit, and turn it into a melee crit. Don't know if it should.

**Comment by robinsch** [comment]
Can you provide me with a few videos from retail?

**Comment by ccrs** [comment]
https://github.com/Xanvial/TrinityCore/commit/c660ab721ada176419ab0aa0869d0a57951e4b24
https://github.com/Xanvial/TrinityCore/commit/969bcce033840fa41c3f88421f9fe08f48760d25

**Comment by ccrs** [comment]
https://www.youtube.com/watch?v=_ld_QsKa-gs
https://www.youtube.com/watch?v=2nWNlvRXAQ8

**Comment by robinsch** [comment]
First video shows that the weapon also swings without copying damage is this correct?

**Comment by Keader** [comment]
In other private servers apparently yes

https://www.youtube.com/watch?v=7niAMx0nOQo
https://www.youtube.com/watch?v=q9pkWT49aio

**Comment by robinsch** [comment]
Still need a valid video from retail.

**Comment by Keader** [comment]
I could not find any video that showed her to do the animation combat without being copying damages (spent two days looking for videos on youtube). In this case need tests on official servers.

**Comment by Keader** [comment]
@robinsch Take a look at this video: https://youtu.be/gJA7xHoQh0M?t=2m31s

**Comment by Keader** [comment]
@robinsch In its correction victim can not be null?
if (pPet && damage) Should not be if (pPet && damage && victim) ?

**Comment by sirikfoll** [comment]
what about spell [Death Knight Rune Weapon Scaling 02] (http://wotlk.openwow.com/spell=51906)?
shouldn't the DRW copy all of owner's spells and this aura handle the damage reduction?

**Comment by ccrs** [comment]
afaik it has to copy three main dk spells as well as attack and follow current DK's target.

also, only autoattack on owner attacks.

**Comment by Keader** [comment]
@ccrs  three? Blood Plague, Frost Fever and?!

**Comment by ccrs** [comment]
http://wotlk.openwow.com/spell=55078
http://wotlk.openwow.com/spell=55095

ur right

**Comment by ikir83** [comment]
Yes as you all know i can confirm still happens

**Comment by mayaren888** [comment]
@ccrs 

my pet_dk_rune_weapon  Each attack damage value =1?
Where is the problem?
https://github.com/TrinityCore/TrinityCore/commit/4fbffab5f8a43410c4e4487e15f22a5173b9bc9e

**Comment by massivezs** [comment]
@mayaren888 
Because your DRW pet hasn't deffined 50% copy of your autoattack damage from crit or noncrit damage > Trinity have bad spellscript for aura  [Death Knight Rune Weapon Scaling 02](http://wotlk.openwow.com/spell=51906) which you can see here
[https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Spells/spell_pet.cpp](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Spells/spell_pet.cpp#L1706)
The biggest problem in the definitions is only the damage is comprised dead inside a file spell_pet.cpp this file already not working at all. Calculations do statsystem. Deleting this file will cause nothing, because pets are coded in the file Statsystem.cpp globally. Each pet there has calculation the Health, Mana, Str, Agi Spell Damage. Unfortunatelly this is bad way how to fix those calculations. Codes which are located in https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Spells/spell_pet.cpp should be in class scripts e.g. in spell_dk.cpp or spell_warlock.cpp or spell_hunter.cpp maybe looks better for me. But it needs rewrite Statsystem and you will need create new codes in Unit.cpp Unit.h maybe spellauraeffect for all sripted auras.
Before a year ago maybe more I or Another next posts this link [http://pastebin.com/JDmVJzx5](http://pastebin.com/JDmVJzx5) This solution is relatively correct. There are a few mistakes because the core had undergone major fixing over the years, but they are not so important. It's just the principle of the solution. If you look Aura [here](http://wotlk.openwow.com/spell=51906) You can see 3 effects 1st  is SPELL_AURA_MOD_DAMAGE_DONE calculation pet damage for your DRW spells from your spells and base attack. 2nd is SPELL_AURA_MELEE_SLOW attack speed and 3th SPELL_AURA_MOD_DAMAGE_PERCENT_DONE this calculate percentable -50 of DK damage
DRW code in Unit.cpp is brutal hack ... eg now When you use in activated DRW spell RUNE TAP - IT'S DK heal but your DRW Hit victim with rune tap :D and if you have a tank eq you can hit with your drw more than your spells via spell rune tap used in drw :)

**Comment by hlainin** [comment]
Good evening. Need your help. I used a [hack ](http://pastebin.com/FZHYeJLe)to fix a Rune Weapon. Now I can't paste the code in Unit.cpp. Can't find where to. Please tell me where to insert. Thanks in advance for your help.

**Comment by ccrs** [comment]
lul

**Comment by hlainin** [comment]
ccrs
If you have no desire to help, then don't write your "lul"

**Comment by ariel-** [comment]
This is not a forum

**Comment by tkrokli** [comment]
Regarding previous fix suggestions to this issue, note that TDB 335 no longer uses `spell_proc_event`.
This change was implemented in commit https://github.com/TrinityCore/TrinityCore/commit/2ff855054f52bf2dcf81aa7a7da7bab7f8a99686 ([**Core/Scripts: Convert spells to new proc system**](https://github.com/TrinityCore/TrinityCore/commit/2ff855054f52bf2dcf81aa7a7da7bab7f8a99686))

**Comment by Regrad** [comment]
Any temporary fix? The ability does not work at all, is there any way to fix it, albeit not quite right?

**Comment by tkrokli** [comment]
At the moment, I don't know of any other solution than the open PR **Core/Spells: Dancing Rune Weapon** #16281

**Comment by Regrad** [comment]
There is no solution for several years. This is very bad. Even a workaround would be good.

**Comment by tkrokli** [comment]
Well, then we need someone with enough time and skills to write a new PR suggestion.

**Comment by sawd20** [comment]
@offl maybe we should open a new ticket for this isuue because no one worked on this lately maybe a new ticket  ncourage to work on it. Its a core spell for blood dk and its important i think

**Comment by offl** [comment]
Dunno, that's not common practice here
I added links to another issues and PRs in the description
This issue can be closed only if new will be filled with literally everything useful from comments here and from another issues and PRs and with links to PRs

To encourage people a bounty can be added and priority label added if more people can agree this is high-priority issue
Personally I think only description here should be updated because it's 8yo issue and nobody yet updated the description

**Comment by ccrs** [comment]
3e886c55611357581ecb69c671d021d29b715e64
