### ISSUE TITLE
[GO] Stratholme Postbox

### ISSUE THREAD

**Issue by Zaranthos** [TrinityCore/TrinityCore#6350]
http://old.wowhead.com/spell=17432

Crusaders' Square Postbox Key
Elders' Square Postbox Key
Festival Lane Postbox Key
Fras Siabi's Postbox Key
King's Square Postbox Key
Market Row Postbox Key

None of the postbox's seem to work. Should be able to open them and get some loot.

2012-04-15 17:41:37 +0200 (39b3589dcb54+) (Win64, Release)
TDB_full_335.11.46_2012_02_13 (+updates)

**Comment by Killyana** [comment]
There's no loot on the Postbox.
Each key corresponds to a mailbox in a certain part of the city. Wowwiki has a nice map showing the locations of each.
When you open a mailbox 2 or 3 http://www.wowhead.com/npc=11142/undead-postman will spawn

After you open the third mailbox, Postmaster Malown will appear. He used to be a popular kill because he drops all the pieces for The Postmaster set.
