### ISSUE TITLE
[Quest] Items of Power - Bolt Charged Bramble

### ISSUE THREAD

**Issue by Zaranthos** [TrinityCore/TrinityCore#6388]
http://www.wowhead.com/quest=1948

You gather the 10 witherbark totem sticks and use them at the circle of outer binding. It plays some animation but you never get the bolt charged bramble and no item is created that you can loot.

2012-04-28 15:10:52 +0200 (b53485e05326+) (Win64, Release) AHbot
b53485e05326f9ed6562aa78fee282f255eac339
TDB_full_335.11.46_2012_02_13 (+updates)
##

**Comment by Aokromes** [comment]
@Gacko give love to this!

**Comment by Gacko** [comment]
/love. There is probably still some data missing to identify how to spawn this properly... I'll see.

**Comment by Rushor** [comment]
there is no such thing as love @Gacko in this issue :(

**Comment by jempson** [comment]
OK then I will post in here.  Still no workie.

**Comment by Faq** [comment]
@Killyana any ideas about fixing this with all the gob changes made recently?

**Comment by Killyana** [comment]
The issue is still the same: the trap 103661 is not activated once summoned

**Comment by Faq** [comment]
Probably not lootable because for summoned gob player is not owner?
@xvwyh any insights about this?

**Comment by Killyana** [comment]
No the gob you see is 103661  a trap not the lootable one.
The lootable gob is never summoned because the trap never activate it self to cast the spell that summon this gob.

**Comment by xvwyh** [comment]
I can't add anything valuable here, sorry. Using the item should summon "Witherbark Totem Bundle" which in turn should summon "Witherbark Totem Bundle TRAP", but there is nothing there that would disturb the trap. No spell with `SPELL_EFFECT_ACTIVATE_OBJECT` within that ID range. And the trap doesn't have "charges" property set to 2, which would make it cast its spell immediately upon being summoned (this functionality seems to have appeared way later into the game's development, as only GOs with high IDs use it and the property is still called "charges" to this day even though it no longer matches its function). I don't know if this one case is enough evidence to suggest that `SPELL_EFFECT_TRANS_DOOR` must disturb linked traps upon summoning, pretty sure there are more cases of similar content in the game which must also be examined.

We can't exclude the possibility that the trap is being triggered by blizzard's serverside script, say, on trap's creation - disturb self, as @Killyana suggested. Except instead of manually casting the spell I would've preferred the trap to trigger itself - there's an action for that: `SMART_ACTION_ACTIVATE_GOBJECT`. Hopefully it will work even if there's no unit to trigger it. Then you won't need to bother with manually casting the spell and despawning - trap will take care of it.

@Killyana
`SPELL_EFFECT_TRANS_DOOR` effect's actual blizzlike name is "Summon Object"
`SPELL_EFFECT_SUMMON_OBJECT_WILD` blizzlike name is "Summon Object (Wild)"
Data from alpha client's SpellEffectNames.dbc. So yeah, nothing special there. Don't know what the difference between these two is supposed to be. For sure the "non-wild" version sets GOs owner to caster, but it also could be that it despawns when its owner leaves the map or something like that.

**Comment by Killyana** [comment]
I get a similar issue here https://github.com/TrinityCore/TrinityCore/commit/d1704cf83118a6ea5136ec709f3e360e60b05bb6#diff-bdce6139acd72f9fc6922ce2a9e43b7fR13
I tried SMART_ACTION_ACTIVATE_GOBJECT and SMART_ACTION_GO_SET_LOOT_STATE but nothing works, for the quest Second Chances the summoned gate cast the spell after 4 secs, so it's definitively done via script.

I'm wondering why Blizzard is using 3 gobs for the quest Items of Power, maybe there's some visual event that happen before spawning the last chest.

**Comment by xvwyh** [comment]
Yeah, there is. That makes me think now that blizzards script is "wait X seconds, disturb self".
This is how the model looks like in state `GO_STATE_ACTIVE`:
![image](https://user-images.githubusercontent.com/43143822/57572417-a0620800-7422-11e9-880e-740d6c6409d2.png)
And this - in `GO_STATE_READY` (also vibrating and with lightnings flashing):
![image](https://user-images.githubusercontent.com/43143822/57572429-e0c18600-7422-11e9-9365-b53d4822005f.png)

But now I am completely baffled by the existance of the spellfocus object "Witherbark Totem Bundle". ALL THREE objects (spellfocus, trap, chest) have this model. If item's spell was summoning the "Witherbark Totem Bundle TRAP", then great:
1. Trap with `GO_STATE_ACTIVE` appears, looking like a regular branch
2. After some time trap activates via script, casts spell "Bolt Charge Bramble" (which has the visual of a pillar of lightning coming from above)
3. "regular branch" trap despawns because the trap has exhausted its 1 charge
4. "Bolt Charged Bramble" is summoned looking like it was charged with lightning

My only guess would be that traps cannot be in `GO_STATE_ACTIVE`, so they have to summon a spellfocus GO just to have the "regular branch" visual displaying. But the linked trap is summoned immediately, so both regular and lightning branches would be visible at the same time. Unless the trap is meant to be invisibile (we don't have access to this serverside data about GOs), yet the spell it casts is meant to be visible.

1. Spellfocus with `GO_STATE_ACTIVE` appears, looking like a regular branch
2. Invisible trap is summoned alongside spellfocus as linked GO
3. After some time trap's script forces spellfocus to despawn
4. Immediately afterwards the trap's script disturbs the trap, which (visibly) casts spell "Bolt Charge Bramble" (which has the visual of a pillar of lightning coming from above)
5. "regular branch" trap despawns because the trap has exhausted its 1 charge
6. "Bolt Charged Bramble" is summoned looking like it was charged with lightning

**Comment by xvwyh** [comment]
https://classic.wowhead.com/quest=1948/items-of-power#comments:id=2744868
> 5. Go into the stone in the middle of the circle and right-click the sticks in your inventory and the bramble will be charged after some secs (around 10)

**Comment by Killyana** [comment]
This works fine, except the spell 9056 when casted by the gob has no light animation, the animation works fine if casted by a npc or  a player.
``` sql
UPDATE `gameobject_template` SET `AIName`='SmartGameObjectAI' WHERE `entry` IN (103661,174764);
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (103661,174764) AND `source_type`=1;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(174764, 1, 0, 0, 63, 0, 100, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Witherbark Totem Bundle TRAP - Just summonedd - cast spell"),
(103661, 1, 0, 0, 63, 0, 100, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Witherbark Totem Bundle TRAP - Just summonedd - cast spell"),
(103661, 1, 1, 2, 60, 0, 100, 1, 10000, 10000, 0, 0, 11, 9056, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Witherbark Totem Bundle TRAP - On link - Despawn"),
(103661, 1, 2, 0, 61, 0, 100, 0, 0, 0, 0, 0, 41, 0, 0, 0, 0, 0, 0, 20, 174764, 0, 0, 0, 0, 0, 0, "Witherbark Totem Bundle TRAP - On link - Despawn");

**Comment by xvwyh** [comment]
Oh, lol. I looked at `SMART_ACTION_ACTIVATE_GOBJECT` handler and had a good laugh. No wonder it doesn't work. But oh well, no point in changing it to `GameObject::Use` call now anyway, when it needs to be expanded to support #21078 eventually.

**Comment by Killyana** [comment]
My knowledge in cpp are very limited. I don't know how to do that.

**Comment by Killyana** [comment]
I spawned a generic npc trigger to cast the spell, it fixes the visual issue:
``` sql
UPDATE `spell_target_position` SET `positionX`=-1350.881714, `positionY`=-2739.897705, `positionZ`=61.57 WHERE `id`=9055;
UPDATE `gameobject_template` SET `AIName`='SmartGameObjectAI' WHERE `entry` IN (103661,174764);
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (103661,174764) AND `source_type`=1;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(174764, 1, 0, 0, 63, 0, 100, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Witherbark Totem Bundle - Just created - activate"),
(103661, 1, 0, 0, 63, 0, 100, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Witherbark Totem Bundle TRAP - Just created - activate"),
(103661, 1, 1, 2, 60, 0, 100, 1, 10000, 10000, 0, 0, 85, 9056, 0, 0, 0, 0, 0, 19, 15214, 5, 0, 0, 0, 0, 0, "Witherbark Totem Bundle TRAP - On update - cast spell"),
(103661, 1, 2, 0, 61, 0, 100, 0, 0, 0, 0, 0, 41, 0, 0, 0, 0, 0, 0, 20, 174764, 0, 0, 0, 0, 0, 0, "Witherbark Totem Bundle TRAP - On link - Despawn");

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` = 17 AND `SourceEntry` = 9055;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `ErrorTextId`, `ScriptName`, `Comment`, `NegativeCondition`) VALUES
(17, 0, 9055, 0, 30, 0, 174764, 30, 0, 0, '', "Create Witherbark Totem Bundle", 1),
(17, 0, 9055, 0, 30, 0, 103662, 30, 0, 0, '', "Create Witherbark Totem Bundle", 1);

DELETE FROM `creature` WHERE `guid` IN (105530)  AND `id`=15214;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES
(105530, 15214, 0, 0, 0, 1, 1, 0, 0, -1350.881714, -2739.897705, 61.57, 1.65806, 300, 0, 0, 0, 0, 0, 0, 0, 0, 0);

**Comment by xvwyh** [comment]
If you desperately want to hackfix the visual without regard for whether or not it even worked on retail servers - sure, it's a solution...

**Comment by Killyana** [comment]
Better to have it working properly.

**Comment by Warpten** [comment]
Actually, if visual does/did not work on retail, we shouldn't fix it
