### ISSUE TITLE
 Furious Attacks

### ISSUE THREAD

**Issue by oMadMano** [TrinityCore/TrinityCore#6532]
Bug Type: Talent
Fansite reference: http://www.wowwiki.com/Furious_Attacks

Status: Bugged
How it SHOULD work: Your normal melee attacks have a chance to reduce all healing done to the target by 25% for 10 sec. This can stack up to 2 times.
How it DOES work: Talent get bugs if you are hit with healing reduce effects and works no more. Which abilities effect on it 

Some spells that bugged this talent:
Hunter's [Aimed Shot] (An aimed shot that increases ranged damage by X and reduces healing done to that target by 50%. Lasts 10 sec.)
Rogue's [Wound Poison I,II,III,IV,V,VI,VII] ( Each strike has a chance of poisoning the enemy, causing X Nature damage and reducing all healing effects used on them by 50% for 15 sec.)
Warrior's [Mortal Strike] (deals weapon damage plus X and wounds the target, reducing the effectiveness of any healing by 50% for 10 sec.)
Warrior's [Furious Attacks] (Your normal melee attacks have a chance to reduce all healing done to the target by 25% for 10 sec. This can stack up to 2 times.)

**Comment by Frytiks** [comment]
@Trisjdc Not true, it's still happening on https://github.com/TrinityCore/TrinityCore/commit/51f5ce1b7364b730cb0bdabcfd6ad18794213f95 it's not procing.

**Comment by sirikfoll** [comment]
Still happen on 224b42c53a6a
It may be easy to fix by someone that understands better, the problem is in this method:
[`Unit::_RemoveNoStackAurasDueToAura(Aura* aura)`](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Unit/Unit.cpp#L3553)

Steps to reproduce:
- 1 Create a warrior, put points on talent [Furious Attacks(Rank 1: 46910, Rank 2: 46911)](http://wotlk.openwow.com/spell=46911)
- 2 With another player, do .cast 49050 tri targeting the warrior and watch the warrior's talent aura fading

**Comment by sirikfoll** [comment]
Suggested Fix:
```sql
-- Use the triggered spell, not the talent itself
UPDATE `spell_group` SET `spell_id`=56112 WHERE `id`=1061 and`spell_id`=46910;
