### ISSUE TITLE
[Bug/Spell]Ruby Drake - Searing Wrath

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#6671]
Bug:
This spell is supposed to have a 30 yard jumping radius. If you cast this on an enemy, the spell will jump to another enemy that is no further than 30 yards and it will keep doing so 5 times, but never hit the same targets again until the spell is cast by the player once more. Unfortunately instead of having a 30 yard radius to jump through mobs, it has only around 6.

Links:
Searing Wrath - http://old.wowhead.com/spell=50232
Ruby Drake - http://old.wowhead.com/npc=27756

Core revision: Trinity Core d98f36194bc2+
Database revision: TDB 335.11.47
Addons: Anticheat1

**Comment by dr-j** [comment]
This spell is screwed up and abused by a lot of people, note that the tool tip says dragons 'Breathes a stream of fire at an enemy dragon, dealing 10200 to 13800 Fire damage and then jumping to additional dragons within 30 yards.  Each jump increases the damage by 50%  Affects up to 5 total targets.'.

The spell itself can only be cast on dragons so that is working but where the problem comes from is when this spell jumps to another target ie it will hit mobs its not meant to hit and if you use ruby drake it is possible to do whole instance without even dismounting from drake by agroing a flying drake and kiting and mobs and then spamming searing wrath on the flying mob and this will jump to the ground mobs and kill them quicker than they should be killed and have seen this be done on 2 and 3rd bosses too when player is meant to dismount but instead agroing flying trash mobs and kiting to boss then using searing wrath to kill the dragon and this jumps to the bosses.

Have tried conditions for this there are already conditions of type 17 in db for this spell which is the condition which prevents spell from been cast on a invalid target but implicit conditons for spell wont work here.

**Comment by Rushor** [comment]
once used this:
 ```c++
enum SearingWrath
{
    NPC_RING_CAPTAIN    = 28236,
    NPC_RING_GUARDIAN   = 27638,
    NPC_LAY_WHELP       = 28276,
    SPELL_SEARING_WRATH = 50232,
};

class SearingWrathTargets
{
    public:
        bool operator()(WorldObject* object) const
        {
            return object->GetEntry() != NPC_EREGOS || object->GetEntry() != NPC_LAY_WHELP || object->GetEntry() != NPC_RING_GUARDIAN || object->GetEntry() != NPC_RING_CAPTAIN;
        }
};

class spell_searing_wrath : public SpellScriptLoader
{
    public:
        spell_searing_wrath() : SpellScriptLoader("spell_searing_wrath") { }

        class spell_searing_wrath_SpellScript : public SpellScript
        {
            PrepareSpellScript(spell_searing_wrath_SpellScript);

            void FilterTargets(std::list<WorldObject*>& unitList)
            {
                unitList.remove_if(SearingWrathTargets());
            }

            void Register()
            {
                OnObjectAreaTargetSelect += SpellObjectAreaTargetSelectFn(spell_searing_wrath_SpellScript::FilterTargets, EFFECT_0, TARGET_UNIT_TARGET_ENEMY);
            }
        };

        SpellScript* GetSpellScript() const
        {
            return new spell_searing_wrath_SpellScript();
        }
};
```
but yeah only a temp solution, EffectChainTarget = 5 needs to be fixed instead

**Comment by joschiwald** [comment]
impl target conditions should work, remember when copy expl target conditions and change them to impl target conds, don't forget to change cond target too

**Comment by dr-j** [comment]
nah I tried implicit conditions here did not work same issue as with the spell used during http://www.wowhead.com/quest=13236/army-of-the-damned with this spell http://www.wowhead.com/spell=58912/deathstorm if this is used right next to player it also kills player and implicit conditions wont work there either and know a number of people have unsucessfully tried with conditions for this one.
