### ISSUE TITLE
[Bug] Random Dungeon Finder - Average Wait Time

### ISSUE THREAD

**Issue by Amit86** [TrinityCore/TrinityCore#7028]
hash 6a83cd4

RDF - Average Wait Time doesn't work properly.

When I join an RDF it tells me the wait time is 4 seconds where its actually around an hour or so, It never updates or change accordingly.
##

**Comment by dr-j** [comment]
Well believe the average wait time displayed is the average wait time at the time you queued this does not update same when you queue for a bg average wait time never updates unless you leave queue and rejoin.

Also with dungeon finder queue if when queue does come up if someone from assembled group declines to enter dungeon that player gets removed from queue but the players who did accept go to back of rdf queue instead of being returned to front as it says which results in longer wait for dungeon if this happens and when it does it means people the queued after you may get dungeon before you.

**Comment by dmpaul26** [comment]
How were you able to reproduce this, dr-j? Players that didn't answer the LFG group found are supposed to return to the back of the line because they didn't accept.

**Comment by dr-j** [comment]
If a individual player or a member of a group of players who queued for a dungeon declines to enter dungeon then those players get removed from queue (that works correctly), however other players who were invited to join that dungeon and accepted but did not enter due to player(s) declning to eter who were not queued in same group the remaining players who were invited should be returned to front of queue.

Platers who did not accept are removed from queue all together.
Players who did accept but could not enter due to player who is not in same party declining invitiation should be returned to front of queue.

The bug on tc is that if a unrelated player declines dungeon invite the player who declines is removed and the rest of group goes to back of queue (thats the bug players who accepted and are not in same party as player who declined should go at front of queue

**Comment by dmpaul26** [comment]
Right, I get that. I'm asking how you tested to make sure it happens this way. How do you know the players were added to the back of the queue, rather than the front?

Also, rather than adding them to the front, they should be returned to their original positions I would imagine.

**Comment by Aokromes** [comment]
still valid?

**Comment by Aokromes** [comment]
no answer after 2 years, if this bug is still valid post results with updated core.
