### ISSUE TITLE
Stuck in Combat

### ISSUE THREAD

**Issue by ogeraisi** [TrinityCore/TrinityCore#7035]
How to reproduce:

- Cast "Eye of Kilrogg"
- Take the eye to a far place that any creature there is out of range for them to attack
- Attack the creature with Eye of Kilrogg
- Once the eye is dead or summon duration is over you are stuck in combat

**Comment by pete318** [comment]
So far as I can tell, most of the "combat bug" situations occur in this manner. Here's what I've observed:

When a player is in an area (any player) the area is active. creatures will attack players, pets other creatures etc. When there are no players in the "field of view" at all. Then the creatures don't attack. This happens whether unload grid is on or off.

So, you can replicate this problem in any of the following ways:

 - Eye of killrogg as described.
 - Attacking creature where an assist happens. E.g., you get initial aggro, an NPC attacks, you lose aggro. They continue fighting. You move away.

Usually in the latter case you'd assume eventually the creature will die and you'll lose aggro (as happens in the real game). Not true. When you leave the area, if there are no other players present, everything stops. You're still in combat with the creature, it's still in combat with you and the NPC. But, the creature and NPC aren't actually fighting any more (so neither will ever die).

If you enter back into the field of view (or even another player does) fighting will resume and once the creature dies you'll be out of combat.

This can also happen if somehow a creature is even pursuing you and somehow you get out of the "sight" range but it's still in combat with you (as GM set speed really high and it's quite easy to do). There are times as a genuine player you can accidentally do this too.

In this case, if you return to where it last was, it will re-appear and continue pursuit, or leave combat.

Likewise with the eye of killrogg, if you move toward where it died, again you will see the same, those creatures will engage you instead and then you can run evade them or engage. Either way you will get out of combat.

There's also another time when you can enter combat and not leave it with a creature not related to the above. This is when the creature has spawned such that is cannot pursue you (and you cannot attack it either due to LoS error). However, if you manage to hit it with an AoE, you can become stuck in combat.

Not looked into the code as to how to get around it yet though.

**Comment by Rushor** [comment]
this wasn't fixed with latest fixes on ifightbugs?

**Comment by pete318** [comment]
It should be. I didn't test it. But I think if the remote creature is in combat with the player they should remain activated and find the player eventually.

**Comment by Killyana** [comment]
I made some tests, I don't enter in combat once the eye dies.

**Comment by Rushor** [comment]
one last point why player get's stuck in combat could be because they fight against vehicles. vehicles should not create a aggrolist for the fighting enemy. i don't know if it is related to this issue here

**Comment by Killyana** [comment]
You mean vehicles accessory or just a vehicle? and it depend which AI is used.

**Comment by Killyana** [comment]
Well in both cases you will be stuck in combat.
vehicle: 28781 (with nullAI)
vehicle with accessory: 29698
There's 2 tickets for both issues.

**Comment by Rushor** [comment]
k nice, maybe someone can link these issues, i feel we will get a fix for this soon

**Comment by Killyana** [comment]
bug combat wiyh accessory: https://github.com/TrinityCore/TrinityCore/issues/15591
For bug combat with vehicles like 28781 (nullAI) there's no issue.
