### ISSUE TITLE
[Spell] Mind Control (Bug / Exploit)

### ISSUE THREAD

**Issue by Zedron** [TrinityCore/TrinityCore#7223]
Player A of faction A flags himself
Player B of faction B Mind Controls player A
Player A is no longer flagged for PvP

highly exploitable when you're trying to kill someone, and it just so happens he had an alt priest of the opposite faction to save his ass right before you land a killing blow >.<

DB:    335.11.47
Core: 484223e

**Comment by adeutscher** [comment]
I think that e7a12ed has successfully solved this issue. I didn't notice this issue when I wrote the fix because I was focused on the problem of the caster not being flagged for PvP, and I would test in a capital city where the victim would be perma-flagged.

Test performed:
1. Bring both players to a contested area on a non-PVP server so that both of them may be unflagged in the same zone if they choose.
2. Victim enables PvP.
3. Victim sets the disabling of PvP flag in motion, beginning the 5 minute unflag timer.
4. Attacker casts Mind Control.
5. Victim does not attack the caster or any other flagged target.
6. Observe flag state. The victim should still be flagged for PvP, and Mind Control should not have extended their PvP timer.

As an additional test, I tried to see if the attacker could force the victim to extend the PvP flag by having the victim attack a bystander while Mind Controlled. The victim's flag was not updated, as one would hope for.

Even if I'm wrong and e7a12ed wasn't the magic bullet, I was unable to reproduce the problem. If someone with more authority can confirm this result, then this ticket should be closed.
