### ISSUE TITLE
[Talent Bug] Tidal Waves

### ISSUE THREAD

**Issue by Nividan** [TrinityCore/TrinityCore#7315]
Greethings,

I found bug in "Tidal Waves" Talent.

What is supposed to do:
After you use the skill Chain Heal or Riptide you get 2 stuck of buff named Tidal Waves.
When you use  Lesser Healing Wave or Healing Wave its get 1 stuck down.
When you use  Lesser Healing Wave or Healing Wave again its remove the buff completely.

What happened:
After you use the skill Chain Heal or Riptide you get 2 stuck of buff named Tidal Waves.
When you use Healing Wave its get 1 stuck down.
When you use Lesser Healing Wave or Healing Wave again its remove the buff completely.
But when you use Lesser Healing Wave its get 1 stuck down.
When you use Lesser Healing Wave again you still see the buff and it still give you the bonus.

Tidal Waves - http://old.wowhead.com/spell=51564/tidal-waves
Lesser Healing Wave - http://www.wowwiki.com/Lesser_Healing_Wave
Healing Wave - http://old.wowhead.com/spell=331/healing-wave

Hash: f523192   Tdb: 335.11.47+

**Comment by Keader** [comment]
Still bugged on rev 5c97594a1691b78ab881437985dc5eeebb31a979
@Aokromes can you reopen this?

**Comment by ariel-** [comment]
Apparently the problem is that charges are being dropped twice by the core, one for each call to Unit::IsSpellCrit(), this function is called by Spell::DoAllEffectOnLaunchTarget and Spell::DoAllEffectOnTarget.

Does this mean spell crit is calculated twice? it uses roll_chance_f so maybe first time its crit, then its not, or the other way round.
