### ISSUE TITLE
summon friend (RAF)

### ISSUE THREAD

**Issue by Lavitz** [TrinityCore/TrinityCore#7395]
When one account is linked to another by refeer a friend in database, it is possible to summon your friend or being summoned just making party and raid with your parter, focusing him and clicking right button on him. However this spell only works if you are a few steps away from your friend. Otherwise it fails.

Spell id: http://www.wowhead.com/spell=45927
Spell effect: http://www.wowhead.com/spell=48955

There is an interesting issue with spell 48955: In dbc:  Effect 0: Id 85 (SPELL_EFFECT_SUMMON_PLAYER) and in Spell.cpp, the spell 48955 is handled with SPELL_EFFECT_SUMMON_RAF_FRIEND instead. This explains why it is required to gather raid to make it work. However, this does not explain why this spell works only a short distance from your friend. Any hint on this would be great as RAF is quite functional but this issue.
##

**Comment by StormBytePP** [comment]
3.3.5 did not have give levels to your friend, only exp x3 and summon (and only until level 60)

**Comment by Nyeriah** [comment]
335 has the grant a level option, and it works afaik.

**Comment by Rushor** [comment]
> 335 has the grant a level option, and it works afaik.

yes on 3.x it works perfectly  http://i.imgur.com/sfNCPy1.jpg http://i.imgur.com/2PeAdox.jpg

**Comment by Rushor** [comment]
adding SPELL_ATTR2_CAN_TARGET_NOT_IN_LOS will not help to fix the issue taht the player cannot summon another player if it's too far away or in another continent

**Comment by Rushor** [comment]
some more info on this here: https://github.com/dalaranwow/dalaran-wow/issues/1935

#1. Once the summon did not show up in the friend page at all. We were in a group, one in Tanaris, one in Hinterlands. We were logged out for at least an hour before that so we could not possibly have had cooldown on it. If there are more conditions attached to this spell, then it would be cool if they went into the refer a friend FAQ.
2. We were in a group. I started the summon my friend. One time with an NPC in target and one time with nothing in target. Nothing happened, no summon, no cooldown.
3. Immediately after those failed summons I started another one with the friend in target. I got the cooldown but the friend did not get the summon. IIRC the friend was on a flight in one case and on zeppelin in the other case. This might just be a result of the failed attempts right before it though.

PS: This is kind of hard/frustrating to debug as user so somebody with the ability to reset cooldowns might have better chances to get at it.

I can help a little and describe what the issue is, summon a friend will not work under these conditions currently on dalaran:
1.) Player is to far away, i.e.: On another continent, in another zone, in another instance ect.
2.) You do not have Player targeted (This also happen with normal summons too, so I don't know if this was intended or an oversite).

How it should work, player can be summoned regardless of their range to the summoner and should not have to be targeted for the summon to work. It should not matter if they are on a boat, a zep, or a flight path the summon should work regardless.

**Comment by starrheld** [comment]
Like @Rushor says, that is exactly what happens, hopefully someone brace and with high intellect can share some knowledge on this and get it resolved this great new year <3

**Comment by Hellangel1987** [comment]
any update on this ? Would be great - i will also give a donation for a fix.

**Comment by tkrokli** [comment]
From the issue post https://github.com/TrinityCore/TrinityCore/issues/7395#issue-6208898 :
## <bountysource-plugin>
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/64217-summon-friend-raf?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>
