### ISSUE TITLE
[QUEST] In Dreams (5944)

### ISSUE THREAD

**Issue by nelegalno** [TrinityCore/TrinityCore#7519]
http://old.wowhead.com/quest=5944
You need to escort Highlord Taelan Fordring ( http://old.wowhead.com/npc=1842 ) outside of Hearthglen, but it seems the event isn't scripted.

A script for mangos can be found at http://pastebin.com/1mbYQDa4, if someone can convert it to TC.

Also Myranda the Hag ( http://old.wowhead.com/npc=11872 ) should offer the dialog to use the Scarlet Illusion ( http://old.wowhead.com/spell=17961 ) spell on you if you don't have it and are on the quest. Otherwise once you loose the aura (death, by leaving the zone or time running out) you can't complete or reacquire the quest.

Quest video (link provided by mweinelt): http://www.youtube.com/watch?v=aHrFZgJt3Zg
TDB49 up to 2dc72ec7c85790c5f9bb0e0cbf408de1b6260ff2
##

**Comment by Rushor** [comment]
https://bitbucket.org/mangoszero/scripts/commits/00ffce187c8119d3ec203a9d9cf8a292dc8e72af

**Comment by Aokromes** [comment]
If the fix here is valid, plz open a PR.

**Comment by tkrokli** [comment]
i think this issue is redundant, because all the above is handled in SAI / DB / conditions now:

[**[3.3.5] Core/Scripts/DB Move script npc_myranda_the_hag to SAI**](https://github.com/TrinityCore/TrinityCore/pull/16438) #16438
https://github.com/TrinityCore/TrinityCore/pull/16438/files

Commit text in https://github.com/TrinityCore/TrinityCore/commit/9f78dc37f77453a225106560b6bb134501fb67d3 :
`Moves the entire NPC script to the database and corrects a logic error where players who have rewarded the quest Scarlet Subterfuge and lost the disguise before taking the quest In Dreams were no longer able to get the disguise.`

This issue was probably overlooked when PR #16438 got created and worked on. Close issue?

**Comment by sirikfoll** [comment]
The quest In Dreams does not have a script, still a valid issue.

**Comment by sirikfoll** [comment]
#18601
