### ISSUE TITLE
The Blood Furnace: Laughing Skull Rogue - Stealth not working

### ISSUE THREAD

**Issue by Failed-** [TrinityCore/TrinityCore#8161]
Stealth is not working properly for the Laughing Skull Rogue (http://www.wowhead.com/npc=17491) in The Blood Furnace.

You're able to spot the mobs from 15-20 yards, no matter which class you play and without the Warlock buff "Detect invisible".

Rev: f2e92b81a30d

**Comment by Killyana** [comment]
As explained invisibility detection depend on level difference between the player and the npc, if the player and the npc have the same level you cannot see it until he aggro.

**Comment by tkrokli** [comment]
I visited the instance a couple of times as a level 70 a couple of times on https://github.com/TrinityCore/TrinityCore/commit/3761d241196827c5d12f2af0ce1c124d9172fc82 and I got stabbed with poison every time before I was able to see them, just because I did not use any anti-stealth techniques. When I cheated and used some AoE explosion, I was able to aggro them and bring them out of stealth.
But otherwise, I did not see them even up close, so I agree on closing this issue.
