### ISSUE TITLE
[3.3.5][6.x] Core/Achievement: Pilgrim's Paunch 

### ISSUE THREAD

**Issue by Vn123** [TrinityCore/TrinityCore#8352]
Hi Tc.

this is the last achievement  that doesn't work in the world event: pilgrim's bounty

the problem is that all works fine and you get "the spirit of sharing" but when u look at the achiev if you get it complete you see it as uncompleted it just dont mark the city where you tried to do the achievement.
Wowhead link:http://www.wowhead.com/achievement=3557

here some video from youtube to see how it need to work:http://www.youtube.com/watch?v=mDi33abkHtw  

Tnx alot.

Tbd:335.11.47+

Hash:ba20aa8 
##

**Comment by Kittnz** [comment]
Does this work? Can anyone confirm this?

**Comment by sirikfoll** [comment]
With a few adjustments, some of them could be merged. But in order to get everything working, the vehicle issues with the Bountiful Table need to be fixed first.
At least the table need to install all its accessories, all the chairs and all the dishes(issues about that in 
https://github.com/TrinityCore/TrinityCore/issues/15224#issuecomment-147102556 and #15809

**Comment by sirikfoll** [comment]
Fixed by fb1f69c76eb91ca4d087e65378ade330f1580e79

**Comment by Simeon23** [comment]
Hello! I know that this issue is closed but...
This achievement doesn't work again. **The Sweet Potato Chair** instead of giving you **Feast On Sweet Potatoes** to stack it five times gives you one of the another 4 spells to stack. In most cases that is **Feast On Stuffing**. 
So instead of having 5 different spells to stack at every chair, you have 4 unique chairs and the last one (5) is a copy of **The Stuffing Chair**

Branch: 3.3.5.

**Comment by tkrokli** [comment]
The fix for this issue is almost 2 years old. I recommend that you open a new issue ticket (unless there are any open issues already covering the problem you describe).

**Comment by tkrokli** [comment]
The main point about opening a new issue is to fill in the required info in the issue template.
