### ISSUE TITLE
[3.3.5][Hunter] Master's Call

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#8403]
Spell: http://wotlk.openwow.com/?spell=53271

When hunter cast Master's Call and pet is dead, Master's Call can cast.
When pet has stunned and Hunter cast Master's Call, Master's Call can cast.
When target is dazed and Hunter cast Master's Call, Master's Call removes daze effect.

Wowwiki: http://www.wowwiki.com/Master's_Call

> Notes
> To work on "the pet's target", the hunter must actually select a friendly target either prior (if auto-self cast is enabled) or during.
> This does not work with daze effects and will not work when the pet and/or hunter are stunned.
> This ability relies on line of sight between the hunter and pet.

0a840fc
TDB

**Comment by lashia** [comment]
@zabustak need some changes in script im getting this error on compile
/root/source/TrinityCore/src/server/scripts/Spells/spell_hunter.cpp: In member function ‘virtual void spell_hun_last_stand_pet::spell_hun_last_stand_pet_SpellScript::Register()’:
/root/source/TrinityCore/src/server/scripts/Spells/spell_hunter.cpp:402:26: error: ‘spell_hun_masters_call_SpellScript’ was not declared in this scope
make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/Spells/spell_hunter.cpp.o] Error 1
rev: 335a279d0d88cde541172b6c11b679de5ae2e41a

**Comment by Aokromes** [comment]
If anything here is valid anyone can open a PR for it?

**Comment by kvipka** [comment]
https://rustemu.org/threads/spell-master-call.12/

**Comment by Aokromes** [comment]
Plz don't post links to places we can't open.

**Comment by Rushor** [comment]
moreover @kvipka - you deleted the sourcecode from https://github.com/healthstone/RE/commit/b1fed80b7a4fdd600ea797a9e57e8a11fdd303e5

**Comment by callmephil** [comment]
`
diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index 5d96de1..d74ee77 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -5067,6 +5067,23 @@ SpellCastResult Spell::CheckCast(bool strict)
         // for effects of spells that have only one target
         switch (m_spellInfo->Effects[i].Effect)
         {
+		case SPELL_EFFECT_DUMMY:
+		{
+			if (m_spellInfo->Id == 53271) // Master's Call
+			{
+				if (!m_caster->ToPlayer())
+					return SPELL_FAILED_BAD_TARGETS;
+
+				Unit* target = m_targets.GetUnitTarget();
+				Pet *pet = m_caster->ToPlayer()->GetPet();
+				if (!target || !pet || pet->isDead() || target->isDead())
+					return SPELL_FAILED_BAD_TARGETS;
+
+				if (!pet->IsWithinLOSInMap(target))
+					return SPELL_FAILED_LINE_OF_SIGHT;
+			}
+			break;
+		}
             case SPELL_EFFECT_LEARN_SPELL:
             {
                 if (m_caster->GetTypeId() != TYPEID_PLAYER)
`

if anyone need a temp solution, This Currently Works for me.

**Comment by Keader** [comment]
please use ```diff
^^

**Comment by noryad** [comment]
Confirmed in current version: eb093c1.
Master Call can not be casted if the pet is dead.
This does not work with daze effects and will not work when the pet and/or hunter are stunned.
This ability relies on line of sight between the hunter and pet. 
http://wowwiki.wikia.com/wiki/Master's_Call

**Comment by noryad** [comment]
Confirmed in 08057b6
Please @ariel- Master's Call needs validations.
1- Now if the pet is stuned the hunter can use Master's Call and should not.
2- Now if the hunter and/or the pet are dazzed can use Master's Call and should not. 
This does not work with daze effects and will not work when the pet and/or hunter are stunned. 
From http://wowwiki.wikia.com/wiki/Master's_Call segment Notes.
3- Now if the pet is dead the hunter can use Master's Call and should not. 
Master's Call relies on the fact that the pet is alive and in range in order to cast the effect.
From http://wow.gamepedia.com/Master's_Call segment Limitations.
4- Now if the hunter is not on line of sight with the pet can use Master's Call and should not. In this case the buffer not appear but the ability is in cooldown.
This ability relies on line of sight between the hunter and pet.
From http://wowwiki.wikia.com/wiki/Master's_Call segment Notes.
