### ISSUE TITLE
[Core / Pet] Movement impairing effects on the Hunter also slow the pet

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#8924]
**Rev:** all (tested on fb3245d12533cde3fb0765b114a6132dde836119)

**Bug:**

When the Hunter is afflicted with a movement impairing effect, it causes the pet to walk until the effect wears off.

**Details:**

To test, try the following:

> 1. Cancel any buffs and put your pet on **stay**
> 2. Move several yards away and enter combat (without moving)
> 3. Click **follow** and notice the pet runs to where you are

Now repeat the above with the exception: **activate Aspect of the Cheetah**

> Notice your pet walks instead of runs while the Hunter is afflicted with the daze effect

**Notes:**

So far I have not been able to track this one down. It is similar to how when the Hunter switches from run to walk, the pet also switches to walk. I also don't think it is spell related because Hamstring and others also do this but who knows...

This is also **not** related to the speed fix I submitted, if you try this on a revision before that merge it will still happen.
##

**Comment by tkrokli** [comment]
TrinityCore rev. 9e3001a44b7f 2015-05-25 01:07:52 +0200 (3.3.5 branch) (Win64, Release)

I can confirm MrSmite's issue description, though I thought the pet would behave like a party member in [[Aspect of the Pack]](http://wotlk.openwow.com/spell=13159). This does not seem to be the case for [[Aspect of the Cheetah]](http://wotlk.openwow.com/spell=5118).

Description of spell 5118, Aspect of the Cheetah :
`The hunter takes on the aspects of a cheetah, increasing movement speed by 30%.`
`If the hunter is struck, (s)he will be dazed for 4 sec. Only one Aspect can be active at a time.`

**Aspect of the Cheetah** (buff / aura tooltip) :
`30% increased movement speed. Dazed if struck.`

Maybe this issue is related to other and more general pet spell / handling issues?
