### ISSUE TITLE
Core/Scripts: Professor Putricide Ooze minions - Hand of Protection immunity

### ISSUE THREAD

**Issue by Kingswow** [TrinityCore/TrinityCore#9046]
When Professor Putricide Ooze minions target one of the players and a paladin casts Hand Of Protection (http://wotlk.openwow.com/spell=1022) on him/her, the target will be immune from oozes' explode damage.

Rev : 7cb9bf1
DB : TDB335.50

Sorry for my bad English.

---

(edited by @tkrokli)
##

**Comment by tkrokli** [comment]
@Kingswow : There are no NPCs in ICC named "Professor Ozz". Maybe you meant [[Professor Putricide]](http://www.wowhead.com/npc=36678/professor-putricide) (http://www.wowhead.com/npc=36678/professor-putricide) and his [[Volatile Ooze]](www.wowhead.com/npc=37697/volatile-ooze) NPC "minions"?

If so, there are already 81 issues (9 open) for the search term "Putricide", 14 (3 open) for Volatile Ooze and I would think that your issue is somehow covered by one of them.

Search examples:
https://github.com/TrinityCore/TrinityCore/search?utf8=✓&q=Putricide&type=Issues
https://github.com/TrinityCore/TrinityCore/search?utf8=✓&q=Volatile+Ooze&type=Issues

None of the open issues refer to the Paladin spell [[Hand Of Protection]](http://www.wowhead.com/spell=1022/hand-of-protection), but maybe it is covered by an issue regarding Volatile Ooze and mechanic_immune_mask (or related to immunity and flags in the C++ scripts).

**Comment by Keader** [comment]
still bugged in current revs.
Explosion is triggered by melee hits, and HoP let player immune from melee hits from Ooze...

**Comment by ariel-** [comment]
Already fixed by proc system
