### ISSUE TITLE
[Core / NPC] Evading mobs attack nearby players

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#9190]
__Rev:__ 1b4a6109764d74d6b440bcd796c2b375aa660096

__Bug:__

When you pull a mob past its aggro radius without damaging it, it is supposed to evade and return home. Instead it will attack any nearby player / pet that it is hostile to and then evade.

__Details:__

It appears that when my PR was merged (ce6785d9db569b31cb88e5d3e65077ffbced40e8) it was modified to add this behavior.

> - A mob that is beyond the ThreatRadius, it will return home (evade) after 10 seconds of no damage if there are no valid targets within attack distance of it, otherwise it will still attack

This is not correct behavior, it allows for griefing. For example, you can aggro a mob and drag it toward someone who is mining or herbing. When the mob stops chasing you to evade home it will hit the nearby player, interrupting them and then it will evade home. This brief period of interruption allows you to steal their mineral or herb node.

The proper behavior for an evading mob is that it does not attack __any__ unit that it is hostile to until it returns home and resets.

**Comment by Killyana** [comment]
Cannot reproduce on rev. 5dba91fb0e38

**Comment by tkrokli** [comment]
From my testing on TrinityCore rev. 5bd7c29 2015-05-13 22:29:49 +0200 (Win64, Release) :

Just in case anyone looks up this issue later, if they find a bug similar to this description, I can add the following from my experience a week ago:

if you have got 2 players logged in, both doing the Death Knight initial Quest Line and are both on the quest ID 12733 [[Death's Challenge]](http://www.wowhead.com/quest=12733/deaths-challenge) (#14700), you might be able to provoke this event to happen if you place one of the player characters somewhere close to the return path of the NPC and then challenge the NPC with the other. When fleeing from the duel challenge enough times (you may have to do it 10 or 20 times to provoke it), the NPC will randomly attack the passive player character.

Worth noticing (in case it can help in searching for the unwanted code) : If the originally passive player starts fighting this NPC and manages to push its HP down to 1%, the NPC will continue to attack even after its own HP has reached 1 (where the normal quest event would end with a successful quest credit update) and will not stop attacking before the player character's HP is less than 10% (maybe as low as 5%). I forgot to log the HP values, I thought the bug was too random to mention, as well as limited to the Scarlet Enclave area, beneath Acherus (the Ebon Hold).

After discovering this issue in the list of closed issues today, I think perhaps it may not be limited to the Scarlet Enclave after all. But I also need to update my core and DB before posting a valid confirmation.
