### ISSUE TITLE
Basic Campfire not buffing Cozy Fire

### ISSUE THREAD

**Issue by Registrar** [TrinityCore/TrinityCore#9437]
Basic Campfire, gameobject 31442 AND 29784 (one of either is created when the "Basic Campfire" spell is cast) should typically cause the player to be buffed with spell 7353, Cozy Fire, when in range. However, this is currently not the case.

Commit: 51b9e6d2c947d2151af09d7a25af45ff75b0d530
WDB: 335.51_2013_02_14 With all updates
##

**Comment by Killyana** [comment]
It buffs npc if they are ooc and player if they are IC, I cannot find any condition or code involving this gobs or spells.
http://wotlk.openwow.com/object=31442 casting   http://wotlk.openwow.com/spell=7353
http://wotlk.openwow.com/object=31510 casting   http://wotlk.openwow.com/spell=7358

**Comment by Kittnz** [comment]
ye confirmed
e6571f9869ec725fb7d50c568f704d150a11b216

http://www.wowhead.com/spell=7353
Apply Aura: Mod Stat (Spirit)
Value: 4
Radius: 10 yards

seems the spell isn't casted at all

**Comment by tkrokli** [comment]
Yes, confirmed on e6571f9 . [[Basic Campfire]](http://wotlk.openwow.com/object=31442) does not cast any spell or produce any aura at all.
I tried to use `.gobject near` , both with and without Basic Campfire on the ground, but no change.
Is the visible object not a "gameobject" because it is temporary or created by a spell? I was hoping to see entry 29784 or 31442 from `gameobject_template` , as in this lookup query :
```sql
SELECT * FROM `gameobject_template` WHERE `entry` IN (29784,31442);
```
```
entry    type  displayId  name            IconName  castBarCaption  unk1    faction   flags    size   Data0   Data1   Data2   Data3   Data4   Data5   Data6   Data7   Data8   Data9  Data10  Data11  Data12  Data13  Data14  Data15  Data16  Data17  Data18  Data19  Data20  Data21  Data22  Data23  AIName  ScriptName  VerifiedBuild  
------  ------  ---------  --------------  --------  --------------  ------  -------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ----------  ---------------
 29784       8        192  Basic Campfire                                          0       0       1       4      10   31442       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0                                12340
 31442       6        299  Basic Campfire                                         35       0       1       0       0      10    7353       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0                                11723
```
From http://collab.kpsn.org/display/tc/gameobject_template : type 8 = `GAMEOBJECT_TYPE_SPELL_FOCUS`
From http://collab.kpsn.org/display/tc/gameobject_template : type 6 = `GAMEOBJECT_TYPE_TRAP`
Using `.cast 7353` works to produce the 60 sec. aura [[Cozy Fire]](http://www.wowhead.com/spell=7353/cozy-fire) with the tooltip `Increases Spirit by 4.`

Not quite sure where to go from here, but I get a feeling that some ID or value is wrong somewhere.

**Comment by Killyana** [comment]
Can you read the old comments before posting useless comments:

It buffs npc if they are ooc or ic and players if they are IC, I cannot find any condition or code involving this gobs or spells.
http://wotlk.openwow.com/object=31442 casting http://wotlk.openwow.com/spell=7353
http://wotlk.openwow.com/object=31510 casting http://wotlk.openwow.com/spell=7358

**Comment by tkrokli** [comment]
OK, so the objects and spells are working as intended?

**Comment by Killyana** [comment]
Cast 7353 or 7358 near a neutral or hostile npc and you will be buffed (for the npc sometimes it's buffed sometimes not depending in its faction) if you casted near a friendly one you will not be buffed.
I tried to change the faction of the gobs but the issue is always the same, the faction condition is related to the player not the gob.

Targets (22, 30) (TARGET_SRC_CASTER, TARGET_UNIT_SRC_AREA_ALLY)

**Comment by Kittnz** [comment]
The question still remains, is the spell actually casted from the gob?

**Comment by tkrokli** [comment]
I just tested it again in combat, and the spell is cast then. But the button Tooltip does not say "in combat".

**Comment by Rushor** [comment]
related to https://github.com/TrinityCore/TrinityCore/issues/13023

**Comment by tkrokli** [comment]
Sorry about misunderstanding this issue so much, feel free to delete my posts if you need this issue cleaned up. Are you saying that it works as intended, so this issue can be closed?

**Comment by Rushor** [comment]
no the hell, it works wrong - i will not repeat killyana again, he said already everything in detail.

**Comment by Trisjdc** [comment]
The way traps (like Basic Campfire) behave is hardcoded in GO logic.
See https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Entities/GameObject/GameObject.cpp#L540
Obviously the issue is the complete disregard for the spell cast, not checking what type of target it requires.

It's a matter of studying the spells that show up in:
```
SELECT entry, name, data3 FROM gameobject_template WHERE type=6;
```

There are a lot more edges cases than just Basic Campfire, this is a general issue.

**Comment by Killyana** [comment]
Works fine rev. 12de860b4aef
