### ISSUE TITLE
SmartAI - Action 21 - Allow/Stop Combat Movement

### ISSUE THREAD

**Issue by ManuFe** [TrinityCore/TrinityCore#9512]
I've found some issues with this action. 
When this is set out of combat everything goes ok, but in combat it doesn't work properly.

For example.
On aggro. Stop combat movement.
0-5 yards. Allow combat movement.
5-15 yards. Stop combat movement.
35+ yards. Allow combat movement.

If I start at 5-35 yards with aggro everything is ok. As I go 35+ yards npc will move but on 5-15 range it won't stop.

It seems that at 15 yards it stops for a microsecond... then restart to move chasing me. 

I've done some tests with mmaps enabled and with a creature without letting him cast anything. 
Same thing is if he casts something. The difference is that he will try to chase me after he finishes to cast.

TDB 335 51 Full for TC
##

**Comment by offl** [comment]
> On aggro. Stop combat movement.
0-5 yards. Allow combat movement.
5-15 yards. Stop combat movement.
35+ yards. Allow combat movement.

Years ago I found the same problem with EAI(EventAI, Carl! The problem persists with SAI, Carl!)
It was an old hardcore method to simulate blizzlike behavior for casters and hunters, now replaced(mostly) by flag SMARTCAST_COMBAT_MOVE. I think the problem is these actions can't be used together in one script or something is wrong with params.
But as I said it's an old method and someone should convert all scripts with SMART_ACTION_ALLOW_COMBAT_MOVEMENT to new format with SMARTCAST_COMBAT_MOVE. A lot of work.
